import type { Course } from '../../../types/courses';

export const courseA1: Course = {
        level: 'A1',
        title: 'Foundations',
        description: 'Build your first French vocabulary and master essential grammar rules.',
        color: 'var(--course-a1)',
        textColor: 'var(--level-a1-text)',
        units: [
            { number: 1, title: 'Faire connaissance' },
            { number: 2, title: 'La vie quotidienne' },
            { number: 3, title: 'La maison et le quartier' },
            { number: 4, title: 'Manger et faire les courses' },
            { number: 5, title: 'Loisirs et vie sociale' },
            { number: 6, title: 'Se déplacer et voyager' },
            { number: 7, title: 'La vie en France' },
            { number: 8, title: 'FINAL EXAM', kind: 'final-exam' },
        ],
        steps: [
            // Unit 1 — Faire connaissance
            { id: 'a1-greetings',       title: 'Greetings & Basics',            module: 'vocabulary', type: 'vocabulary', contentId: 'greetings-basics',          path: '/vocabulary/greetings-basics',              unit: 1 },
            { id: 'a1-articles',        title: 'Articles',                       module: 'lectures', type: 'grammar',    contentId: 'articles',                   path: '/lectures/grammar/articles',                 unit: 1 },
            { id: 'a1-noun-gender',     title: 'Noun Gender',                    module: 'lectures', type: 'grammar',    contentId: 'noun-gender',                path: '/lectures/grammar/noun-gender',              unit: 1 },
            { id: 'a1-intro-yourself',  title: 'Introducing Yourself',           module: 'lectures', type: 'phrases',    contentId: 'introducing-yourself',       path: '/lectures/phrases/introducing-yourself',             unit: 1 },
            { id: 'a1-nationalities',   title: 'Countries & Nationalities',      module: 'vocabulary', type: 'vocabulary', contentId: 'nationalities',              path: '/vocabulary/nationalities',                 unit: 1 },
            { id: 'a1-classroom',       title: 'Classroom Survival',             module: 'lectures', type: 'phrases',    contentId: 'classroom-survival',         path: '/lectures/phrases/classroom-survival',               unit: 1 },
            { id: 'a1-stress-pronouns', title: 'Stress Pronouns',                module: 'lectures', type: 'grammar',    contentId: 'stress-pronouns',            path: '/lectures/grammar/stress-pronouns',          unit: 1 },
            { id: 'a1-reading-bonjour-je-mappelle-marie', title: 'Reading: Bonjour, je m’appelle Marie', module: 'lectures', type: 'reading', contentId: 'a1-bonjour-je-mappelle-marie', path: '/lectures/reading/a1-bonjour-je-mappelle-marie', unit: 1 },
            { id: 'a1-reading-vocab-bonjour-je-mappelle-marie', title: 'Vocabulary: Bonjour, je m’appelle Marie', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-bonjour-je-mappelle-marie', path: '/vocabulary/a1-bonjour-je-mappelle-marie', unit: 1 },
            { id: 'a1-reading-une-nouvelle-collegue', title: 'Reading: Une Nouvelle Collègue', module: 'lectures', type: 'reading', contentId: 'a1-une-nouvelle-collegue', path: '/lectures/reading/a1-une-nouvelle-collegue', unit: 1 },
            { id: 'a1-reading-vocab-une-nouvelle-collegue', title: 'Vocabulary: Une Nouvelle Collègue', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-une-nouvelle-collegue', path: '/vocabulary/a1-une-nouvelle-collegue', unit: 1 },
            { id: 'a1-reading-mon-ami-thomas', title: 'Reading: Mon Ami Thomas', module: 'lectures', type: 'reading', contentId: 'a1-mon-ami-thomas', path: '/lectures/reading/a1-mon-ami-thomas', unit: 1 },
            { id: 'a1-reading-vocab-mon-ami-thomas', title: 'Vocabulary: Mon Ami Thomas', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-mon-ami-thomas', path: '/vocabulary/a1-mon-ami-thomas', unit: 1 },
            { id: 'a1-famille-martin',  title: 'Reading: La Famille Martin',     module: 'lectures', type: 'reading',    contentId: 'a1-la-famille-martin',       path: '/lectures/reading/a1-la-famille-martin',             unit: 1 },
            { id: 'a1-reading-vocab-la-famille-martin', title: 'Vocabulary: La Famille Martin', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-la-famille-martin', path: '/vocabulary/a1-la-famille-martin', unit: 1 },
            { id: 'a1-exam-1', title: 'Unit 1 exam', module: 'exams', type: 'exams', contentId: 'a1-exam-1', path: '/exams/1', unit: 1, available: true, isDemo: true },
            // Unit 2 — La vie quotidienne
            { id: 'a1-numbers',         title: 'Numbers 1–100',                  module: 'vocabulary', type: 'vocabulary', contentId: 'numbers-time',               path: '/vocabulary/numbers-time',                  unit: 2 },
            { id: 'a1-days-months',     title: 'Days & Months',                  module: 'vocabulary', type: 'vocabulary', contentId: 'days-months',                path: '/vocabulary/days-months',                   unit: 2 },
            { id: 'a1-telling-time',    title: 'Telling the Time',               module: 'lectures', type: 'grammar',    contentId: 'telling-time',               path: '/lectures/grammar/telling-time',             unit: 2 },
            { id: 'a1-etre',            title: 'Verb: être',                     module: 'verbs', type: 'verbs',      contentId: 'etre',                       path: '/verbs/etre/table',                        unit: 2 },
            { id: 'a1-avoir',           title: 'Verb: avoir',                    module: 'verbs', type: 'verbs',      contentId: 'avoir',                      path: '/verbs/avoir/table',                       unit: 2 },
            { id: 'a1-present-er',      title: 'Present Tense: -ER Verbs',       module: 'lectures', type: 'grammar',    contentId: 'present-tense-er',           path: '/lectures/grammar/present-tense-er',         unit: 2 },
            { id: 'a1-clothing',        title: 'Clothing & Accessories',         module: 'vocabulary', type: 'vocabulary', contentId: 'clothing-accessories',       path: '/vocabulary/clothing-accessories',           unit: 2 },
            { id: 'a1-negation',        title: 'Negation',                       module: 'lectures', type: 'grammar',    contentId: 'negation',                   path: '/lectures/grammar/negation',                 unit: 2 },
            { id: 'a1-present-ir-re',   title: 'Present Tense: -IR & -RE Verbs', module: 'lectures', type: 'grammar',   contentId: 'present-tense-ir-re',        path: '/lectures/grammar/present-tense-ir-re',      unit: 2 },
            { id: 'a1-faire',           title: 'Verb: faire',                    module: 'verbs', type: 'verbs',      contentId: 'faire',                      path: '/verbs/faire/table',                       unit: 2 },
            { id: 'a1-journee-typique', title: 'Reading: Une Journée Typique',   module: 'lectures', type: 'reading',    contentId: 'a1-une-journee-typique',     path: '/lectures/reading/a1-une-journee-typique',           unit: 2 },
            { id: 'a1-reading-vocab-une-journee-typique', title: 'Vocabulary: Une Journée Typique', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-une-journee-typique', path: '/vocabulary/a1-une-journee-typique', unit: 2 },
            { id: 'a1-reading-le-samedi-de-sophie', title: 'Reading: Le Samedi de Sophie', module: 'lectures', type: 'reading', contentId: 'a1-le-samedi-de-sophie', path: '/lectures/reading/a1-le-samedi-de-sophie', unit: 2 },
            { id: 'a1-reading-vocab-le-samedi-de-sophie', title: 'Vocabulary: Le Samedi de Sophie', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-le-samedi-de-sophie', path: '/vocabulary/a1-le-samedi-de-sophie', unit: 2 },
            { id: 'a1-reading-une-journee-au-travail', title: 'Reading: Une Journée au Travail', module: 'lectures', type: 'reading', contentId: 'a1-une-journee-au-travail', path: '/lectures/reading/a1-une-journee-au-travail', unit: 2 },
            { id: 'a1-reading-vocab-une-journee-au-travail', title: 'Vocabulary: Une Journée au Travail', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-une-journee-au-travail', path: '/vocabulary/a1-une-journee-au-travail', unit: 2 },
            { id: 'a1-reading-apres-le-travail', title: 'Reading: Après le Travail', module: 'lectures', type: 'reading', contentId: 'a1-apres-le-travail', path: '/lectures/reading/a1-apres-le-travail', unit: 2 },
            { id: 'a1-reading-vocab-apres-le-travail', title: 'Vocabulary: Après le Travail', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-apres-le-travail', path: '/vocabulary/a1-apres-le-travail', unit: 2 },
            { id: 'a1-exam-2', title: 'Unit 2 exam', module: 'exams', type: 'exams', contentId: 'a1-exam-2', path: '/exams/2', unit: 2, available: true, isDemo: true },
            // Unit 3 — La maison et le quartier
            { id: 'a1-family',          title: 'Family & Relationships',         module: 'vocabulary', type: 'vocabulary', contentId: 'family-relationships',       path: '/vocabulary/family-relationships',           unit: 3 },
            { id: 'a1-possessives',     title: 'Possessive Adjectives',          module: 'lectures', type: 'grammar',    contentId: 'possessive-adjectives',      path: '/lectures/grammar/possessive-adjectives',    unit: 3 },
            { id: 'a1-home',            title: 'Home & Living',                  module: 'vocabulary', type: 'vocabulary', contentId: 'home-living',                path: '/vocabulary/home-living',                   unit: 3 },
            { id: 'a1-prepositions',    title: 'Prepositions of Place',          module: 'lectures', type: 'grammar',    contentId: 'prepositions-place',         path: '/lectures/grammar/prepositions-place',       unit: 3 },
            { id: 'a1-colors',          title: 'Colors & Descriptions',          module: 'vocabulary', type: 'vocabulary', contentId: 'colors-descriptions',        path: '/vocabulary/colors-descriptions',            unit: 3 },
            { id: 'a1-adjectives',      title: 'Adjective Agreement',            module: 'lectures', type: 'grammar',    contentId: 'adjective-basics',           path: '/lectures/grammar/adjective-basics',          unit: 3 },
            { id: 'a1-home-phrases',    title: 'Describing Your Home',           module: 'lectures', type: 'phrases',    contentId: 'describing-your-home',       path: '/lectures/phrases/describing-your-home',             unit: 3 },
            { id: 'a1-demonstratives',  title: 'Demonstrative Adjectives',       module: 'lectures', type: 'grammar',    contentId: 'demonstrative-adjectives',   path: '/lectures/grammar/demonstrative-adjectives',  unit: 3 },
            { id: 'a1-reading-mon-appartement', title: 'Reading: Mon Appartement', module: 'lectures', type: 'reading', contentId: 'a1-mon-appartement', path: '/lectures/reading/a1-mon-appartement', unit: 3 },
            { id: 'a1-reading-vocab-mon-appartement', title: 'Vocabulary: Mon Appartement', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-mon-appartement', path: '/vocabulary/a1-mon-appartement', unit: 3 },
            { id: 'a1-reading-chez-mes-parents', title: 'Reading: Chez Mes Parents', module: 'lectures', type: 'reading', contentId: 'a1-chez-mes-parents', path: '/lectures/reading/a1-chez-mes-parents', unit: 3 },
            { id: 'a1-reading-vocab-chez-mes-parents', title: 'Vocabulary: Chez Mes Parents', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-chez-mes-parents', path: '/vocabulary/a1-chez-mes-parents', unit: 3 },
            { id: 'a1-reading-mon-quartier', title: 'Reading: Mon Quartier', module: 'lectures', type: 'reading', contentId: 'a1-mon-quartier', path: '/lectures/reading/a1-mon-quartier', unit: 3 },
            { id: 'a1-reading-vocab-mon-quartier', title: 'Vocabulary: Mon Quartier', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-mon-quartier', path: '/vocabulary/a1-mon-quartier', unit: 3 },
            { id: 'a1-reading-une-promenade-dans-le-quartier', title: 'Reading: Une Promenade dans le Quartier', module: 'lectures', type: 'reading', contentId: 'a1-une-promenade-dans-le-quartier', path: '/lectures/reading/a1-une-promenade-dans-le-quartier', unit: 3 },
            { id: 'a1-reading-vocab-une-promenade-dans-le-quartier', title: 'Vocabulary: Une Promenade dans le Quartier', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-une-promenade-dans-le-quartier', path: '/vocabulary/a1-une-promenade-dans-le-quartier', unit: 3 },
            { id: 'a1-exam-3', title: 'Unit 3 exam', module: 'exams', type: 'exams', contentId: 'a1-exam-3', path: '/exams/3', unit: 3, available: false, isDemo: false },
            // Unit 4 — Manger et faire les courses
            { id: 'a1-food',            title: 'Food & Drinks',                  module: 'vocabulary', type: 'vocabulary', contentId: 'food-drinks',                path: '/vocabulary/food-drinks',                   unit: 4 },
            { id: 'a1-partitive',       title: 'Partitive Articles',             module: 'lectures', type: 'grammar',    contentId: 'partitive-articles',         path: '/lectures/grammar/partitive-articles',       unit: 4 },
            { id: 'a1-cafe-phrases',    title: 'At the Café',                    module: 'lectures', type: 'phrases',    contentId: 'at-the-cafe',                path: '/lectures/phrases/at-the-cafe',                      unit: 4 },
            { id: 'a1-shopping',        title: 'Shopping Basics',                module: 'lectures', type: 'phrases',    contentId: 'shopping-basics',            path: '/lectures/phrases/shopping-basics',                  unit: 4 },
            { id: 'a1-cafe-reading',    title: 'Reading: Au Café',               module: 'lectures', type: 'reading',    contentId: 'a1-au-cafe',                 path: '/lectures/reading/a1-au-cafe',                       unit: 4 },
            { id: 'a1-reading-vocab-au-cafe', title: 'Vocabulary: Au Café de la Paix', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-au-cafe', path: '/vocabulary/a1-au-cafe', unit: 4 },
            { id: 'a1-au-marche',       title: 'Reading: Au Marché',             module: 'lectures', type: 'reading',    contentId: 'a1-au-marche',               path: '/lectures/reading/a1-au-marche',                     unit: 4 },
            { id: 'a1-reading-vocab-au-marche', title: 'Vocabulary: Au Marché', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-au-marche', path: '/vocabulary/a1-au-marche', unit: 4 },
            { id: 'a1-reading-a-la-boulangerie', title: 'Reading: À la Boulangerie', module: 'lectures', type: 'reading', contentId: 'a1-a-la-boulangerie', path: '/lectures/reading/a1-a-la-boulangerie', unit: 4 },
            { id: 'a1-reading-vocab-a-la-boulangerie', title: 'Vocabulary: À la Boulangerie', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-a-la-boulangerie', path: '/vocabulary/a1-a-la-boulangerie', unit: 4 },
            { id: 'a1-reading-au-restaurant', title: 'Reading: Au Restaurant', module: 'lectures', type: 'reading', contentId: 'a1-au-restaurant', path: '/lectures/reading/a1-au-restaurant', unit: 4 },
            { id: 'a1-reading-vocab-au-restaurant', title: 'Vocabulary: Au Restaurant', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-au-restaurant', path: '/vocabulary/a1-au-restaurant', unit: 4 },
            { id: 'a1-exam-4', title: 'Unit 4 exam', module: 'exams', type: 'exams', contentId: 'a1-exam-4', path: '/exams/4', unit: 4, available: false, isDemo: false },
            // Unit 5 — Loisirs et vie sociale
            { id: 'a1-modals',          title: 'Vouloir, Pouvoir, Devoir',       module: 'lectures', type: 'grammar',    contentId: 'vouloir-pouvoir-devoir',      path: '/lectures/grammar/vouloir-pouvoir-devoir',   unit: 5 },
            { id: 'a1-questions',       title: 'Asking Questions',               module: 'lectures', type: 'grammar',    contentId: 'questions',                  path: '/lectures/grammar/questions',                unit: 5 },
            { id: 'a1-futur-proche',    title: 'Le Futur Proche',                module: 'lectures', type: 'grammar',    contentId: 'futur-proche',               path: '/lectures/grammar/futur-proche',             unit: 5 },
            { id: 'a1-venir',           title: 'Verb: venir',                    module: 'verbs', type: 'verbs',      contentId: 'venir',                      path: '/verbs/venir/table',                       unit: 5 },
            { id: 'a1-reading-jaime-le-sport', title: 'Reading: J’aime le Sport', module: 'lectures', type: 'reading', contentId: 'a1-jaime-le-sport', path: '/lectures/reading/a1-jaime-le-sport', unit: 5 },
            { id: 'a1-reading-vocab-jaime-le-sport', title: 'Vocabulary: J’aime le Sport', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-jaime-le-sport', path: '/vocabulary/a1-jaime-le-sport', unit: 5 },
            { id: 'a1-reading-on-va-au-cinema', title: 'Reading: On Va au Cinéma ?', module: 'lectures', type: 'reading', contentId: 'a1-on-va-au-cinema', path: '/lectures/reading/a1-on-va-au-cinema', unit: 5 },
            { id: 'a1-reading-vocab-on-va-au-cinema', title: 'Vocabulary: On Va au Cinéma ?', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-on-va-au-cinema', path: '/vocabulary/a1-on-va-au-cinema', unit: 5 },
            { id: 'a1-reading-une-soiree-entre-amis', title: 'Reading: Une Soirée Entre Amis', module: 'lectures', type: 'reading', contentId: 'a1-une-soiree-entre-amis', path: '/lectures/reading/a1-une-soiree-entre-amis', unit: 5 },
            { id: 'a1-reading-vocab-une-soiree-entre-amis', title: 'Vocabulary: Une Soirée Entre Amis', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-une-soiree-entre-amis', path: '/vocabulary/a1-une-soiree-entre-amis', unit: 5 },
            { id: 'a1-reading-tu-viens-samedi', title: 'Reading: Tu Viens Samedi ?', module: 'lectures', type: 'reading', contentId: 'a1-tu-viens-samedi', path: '/lectures/reading/a1-tu-viens-samedi', unit: 5 },
            { id: 'a1-reading-vocab-tu-viens-samedi', title: 'Vocabulary: Tu Viens Samedi ?', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-tu-viens-samedi', path: '/vocabulary/a1-tu-viens-samedi', unit: 5 },
            { id: 'a1-exam-5', title: 'Unit 5 exam', module: 'exams', type: 'exams', contentId: 'a1-exam-5', path: '/exams/5', unit: 5, available: false, isDemo: false },
            // Unit 6 — Se déplacer et voyager
            { id: 'a1-aller',           title: 'Verb: aller',                    module: 'verbs', type: 'verbs',      contentId: 'aller',                      path: '/verbs/aller/table',                       unit: 6 },
            { id: 'a1-transport',       title: 'Transport & Travel',             module: 'vocabulary', type: 'vocabulary', contentId: 'transport-basics',           path: '/vocabulary/transport-basics',              unit: 6 },
            { id: 'a1-directions',      title: 'Asking for Directions',          module: 'lectures', type: 'phrases',    contentId: 'asking-directions',          path: '/lectures/phrases/asking-directions',                unit: 6 },
            { id: 'a1-city',            title: 'City Places',                    module: 'vocabulary', type: 'vocabulary', contentId: 'city-places',                path: '/vocabulary/city-places',                   unit: 6 },
            { id: 'a1-reading-je-vais-au-travail', title: 'Reading: Je Vais au Travail', module: 'lectures', type: 'reading', contentId: 'a1-je-vais-au-travail', path: '/lectures/reading/a1-je-vais-au-travail', unit: 6 },
            { id: 'a1-reading-vocab-je-vais-au-travail', title: 'Vocabulary: Je Vais au Travail', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-je-vais-au-travail', path: '/vocabulary/a1-je-vais-au-travail', unit: 6 },
            { id: 'a1-reading-ou-est-la-gare', title: 'Reading: Où Est la Gare ?', module: 'lectures', type: 'reading', contentId: 'a1-ou-est-la-gare', path: '/lectures/reading/a1-ou-est-la-gare', unit: 6 },
            { id: 'a1-reading-vocab-ou-est-la-gare', title: 'Vocabulary: Où Est la Gare ?', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-ou-est-la-gare', path: '/vocabulary/a1-ou-est-la-gare', unit: 6 },
            { id: 'a1-reading-a-la-gare', title: 'Reading: À la Gare', module: 'lectures', type: 'reading', contentId: 'a1-a-la-gare', path: '/lectures/reading/a1-a-la-gare', unit: 6 },
            { id: 'a1-reading-vocab-a-la-gare', title: 'Vocabulary: À la Gare', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-a-la-gare', path: '/vocabulary/a1-a-la-gare', unit: 6 },
            { id: 'a1-reading-un-week-end-a-lyon', title: 'Reading: Un Week-end à Lyon', module: 'lectures', type: 'reading', contentId: 'a1-un-week-end-a-lyon', path: '/lectures/reading/a1-un-week-end-a-lyon', unit: 6 },
            { id: 'a1-reading-vocab-un-week-end-a-lyon', title: 'Vocabulary: Un Week-end à Lyon', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-un-week-end-a-lyon', path: '/vocabulary/a1-un-week-end-a-lyon', unit: 6 },
            { id: 'a1-exam-6', title: 'Unit 6 exam', module: 'exams', type: 'exams', contentId: 'a1-exam-6', path: '/exams/6', unit: 6, available: false, isDemo: false },
            // Unit 7 — La vie en France
            { id: 'a1-body-health',     title: 'Body & Health',                  module: 'vocabulary', type: 'vocabulary', contentId: 'body-health',                path: '/vocabulary/body-health',                   unit: 7 },
            { id: 'a1-seasons',         title: 'Seasons & Weather',              module: 'vocabulary', type: 'vocabulary', contentId: 'seasons-weather',            path: '/vocabulary/seasons-weather',               unit: 7 },
            { id: 'a1-health-phrases',  title: 'Talking About Health',           module: 'lectures', type: 'phrases',    contentId: 'talking-about-health',       path: '/lectures/phrases/talking-about-health',             unit: 7 },
            { id: 'a1-reading-une-journee-a-marseille', title: 'Reading: Une Journée à Marseille', module: 'lectures', type: 'reading', contentId: 'a1-une-journee-a-marseille', path: '/lectures/reading/a1-une-journee-a-marseille', unit: 7 },
            { id: 'a1-reading-vocab-une-journee-a-marseille', title: 'Vocabulary: Une Journée à Marseille', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-une-journee-a-marseille', path: '/vocabulary/a1-une-journee-a-marseille', unit: 7 },
            { id: 'a1-reading-une-visite-chez-des-amis', title: 'Reading: Une Visite Chez des Amis', module: 'lectures', type: 'reading', contentId: 'a1-une-visite-chez-des-amis', path: '/lectures/reading/a1-une-visite-chez-des-amis', unit: 7 },
            { id: 'a1-reading-vocab-une-visite-chez-des-amis', title: 'Vocabulary: Une Visite Chez des Amis', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-une-visite-chez-des-amis', path: '/vocabulary/a1-une-visite-chez-des-amis', unit: 7 },
            { id: 'a1-reading-mes-premieres-semaines-en-france', title: 'Reading: Mes Premières Semaines en France', module: 'lectures', type: 'reading', contentId: 'a1-mes-premieres-semaines-en-france', path: '/lectures/reading/a1-mes-premieres-semaines-en-france', unit: 7 },
            { id: 'a1-reading-vocab-mes-premieres-semaines-en-france', title: 'Vocabulary: Mes Premières Semaines en France', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-mes-premieres-semaines-en-france', path: '/vocabulary/a1-mes-premieres-semaines-en-france', unit: 7 },
            { id: 'a1-reading-un-week-end-a-la-campagne', title: 'Reading: Un Week-end à la Campagne', module: 'lectures', type: 'reading', contentId: 'a1-un-week-end-a-la-campagne', path: '/lectures/reading/a1-un-week-end-a-la-campagne', unit: 7 },
            { id: 'a1-reading-vocab-un-week-end-a-la-campagne', title: 'Vocabulary: Un Week-end à la Campagne', module: 'vocabulary', type: 'vocabulary', contentId: 'a1-un-week-end-a-la-campagne', path: '/vocabulary/a1-un-week-end-a-la-campagne', unit: 7 },
            { id: 'a1-exam-7', title: 'Unit 7 exam', module: 'exams', type: 'exams', contentId: 'a1-exam-7', path: '/exams/7', unit: 7, available: false, isDemo: false },
            // Level exam
            { id: 'a1-exam-final', title: 'A1 final exam', module: 'exams', type: 'exams', contentId: 'a1-exam-final', path: '/exams/final', unit: 8, available: true, isDemo: true },
        ],
    };
