import type { Course } from '../../../types/courses';

export const courseA2: Course = {
        level: 'A2',
        title: 'Everyday French',
        description: 'Master past tenses, pronouns, and real-world French situations.',
        color: 'var(--course-a2)',
        textColor: 'var(--level-a2-text)',
        units: [
            { number: 1, title: 'Unit 1 — Le Passé' },
            { number: 2, title: 'Unit 2 — Achats & Goûts' },
            { number: 3, title: 'Unit 3 — Voyages & Nature' },
            { number: 4, title: 'Unit 4 — Vie Sociale' },
            { number: 5, title: 'Unit 5 — Personnes & Bilan' },
        ],
        steps: [
            // Unit 1 — Le Passé (7 steps)
            { id: 'a2-work',              title: 'Work & Professions',            module: 'vocabulary', type: 'vocabulary', contentId: 'work-professions',          path: '/vocabulary/work-professions',                   unit: 1 },
            { id: 'a2-passe-compose',     title: 'Passé Composé',                 module: 'lectures', type: 'grammar',    contentId: 'passe-compose',             path: '/lectures/grammar/passe-compose',                 unit: 1 },
            { id: 'a2-imparfait',         title: "L'Imparfait",                   module: 'lectures', type: 'grammar',    contentId: 'imparfait-intro',            path: '/lectures/grammar/imparfait-intro',               unit: 1 },
            { id: 'a2-passe-vs-imparfait',title: 'Passé vs Imparfait',            module: 'lectures', type: 'grammar',    contentId: 'passe-compose-vs-imparfait', path: '/lectures/grammar/passe-compose-vs-imparfait',    unit: 1 },
            { id: 'a2-school',            title: 'School & Education',            module: 'vocabulary', type: 'vocabulary', contentId: 'school-education',           path: '/vocabulary/school-education',                   unit: 1 },
            { id: 'a2-daily-routine',     title: 'Daily Routine',                 module: 'lectures', type: 'phrases',    contentId: 'daily-routine',             path: '/lectures/phrases/daily-routine',                         unit: 1 },
            { id: 'a2-reading-journee',   title: 'Reading: La Journée de Clara',  module: 'lectures', type: 'reading',    contentId: 'a2-une-journee-typique',     path: '/lectures/reading/a2-une-journee-typique',                unit: 1 },
            // Unit 2 — Achats & Goûts (8 steps)
            { id: 'a2-shopping',          title: 'Shopping & Money',              module: 'vocabulary', type: 'vocabulary', contentId: 'shopping-money',             path: '/vocabulary/shopping-money',                     unit: 2 },
            { id: 'a2-adjectives',        title: 'Adjective Agreement',           module: 'lectures', type: 'grammar',    contentId: 'adjective-agreement',        path: '/lectures/grammar/adjective-agreement',           unit: 2 },
            { id: 'a2-comparatives',      title: 'Comparatives & Superlatives',   module: 'lectures', type: 'grammar',    contentId: 'comparatives-superlatives',  path: '/lectures/grammar/comparatives-superlatives',     unit: 2 },
            { id: 'a2-restaurant',        title: 'At the Restaurant',             module: 'lectures', type: 'phrases',    contentId: 'at-the-restaurant',          path: '/lectures/phrases/at-the-restaurant',                     unit: 2 },
            { id: 'a2-food-culture',      title: 'Food & Culture',                module: 'vocabulary', type: 'vocabulary', contentId: 'food-culture',               path: '/vocabulary/food-culture',                       unit: 2 },
            { id: 'a2-animals',           title: 'Animals',                       module: 'vocabulary', type: 'vocabulary', contentId: 'animals',                    path: '/vocabulary/animals',                            unit: 2 },
            { id: 'a2-imperative',        title: 'The Imperative Mood',           module: 'lectures', type: 'grammar',    contentId: 'imperative-mood',            path: '/lectures/grammar/imperative-mood',               unit: 2 },
            { id: 'a2-market-phrases',    title: 'At the Market',                 module: 'lectures', type: 'phrases',    contentId: 'at-the-market',              path: '/lectures/phrases/at-the-market',                         unit: 2 },
            // Unit 3 — Voyages & Nature (7 steps)
            { id: 'a2-weather',           title: 'Weather & Nature',              module: 'vocabulary', type: 'vocabulary', contentId: 'weather-nature',             path: '/vocabulary/weather-nature',                     unit: 3 },
            { id: 'a2-futur-simple',      title: 'Le Futur Simple',               module: 'lectures', type: 'grammar',    contentId: 'futur-simple-intro',         path: '/lectures/grammar/futur-simple-intro',            unit: 3 },
            { id: 'a2-transport',         title: 'Transport & Travel',            module: 'vocabulary', type: 'vocabulary', contentId: 'transport-travel',           path: '/vocabulary/transport-travel',                   unit: 3 },
            { id: 'a2-hotel',             title: 'At the Hotel',                  module: 'lectures', type: 'phrases',    contentId: 'at-the-hotel',               path: '/lectures/phrases/at-the-hotel',                          unit: 3 },
            { id: 'a2-direct-object',     title: 'Direct Object Pronouns',        module: 'lectures', type: 'grammar',    contentId: 'direct-object-pronouns',     path: '/lectures/grammar/direct-object-pronouns',        unit: 3 },
            { id: 'a2-regular-verbs',     title: 'Regular Verbs',                 module: 'verbs', type: 'verbs',      contentId: 'a2',              path: '/verbs/a2',                         unit: 3 },
            { id: 'a2-reading-bretagne',  title: 'Reading: Vacances en Bretagne', module: 'lectures', type: 'reading',    contentId: 'a2-vacances-en-bretagne',    path: '/lectures/reading/a2-vacances-en-bretagne',               unit: 3 },
            // Unit 4 — Vie Sociale (9 steps)
            { id: 'a2-sports',            title: 'Sports & Hobbies',              module: 'vocabulary', type: 'vocabulary', contentId: 'sports-hobbies',             path: '/vocabulary/sports-hobbies',                     unit: 4 },
            { id: 'a2-indirect-object',   title: 'Indirect Object Pronouns',      module: 'lectures', type: 'grammar',    contentId: 'indirect-object-pronouns',   path: '/lectures/grammar/indirect-object-pronouns',      unit: 4 },
            { id: 'a2-health-doctor',     title: 'Health & Doctor',               module: 'vocabulary', type: 'vocabulary', contentId: 'health-doctor',              path: '/vocabulary/health-doctor',                      unit: 4 },
            { id: 'a2-at-doctor',         title: 'At the Doctor',                 module: 'lectures', type: 'phrases',    contentId: 'at-the-doctor',              path: '/lectures/phrases/at-the-doctor',                         unit: 4 },
            { id: 'a2-depuis-pendant',    title: 'Depuis / Pendant',              module: 'lectures', type: 'grammar',    contentId: 'depuis-pendant',             path: '/lectures/grammar/depuis-pendant',                unit: 4 },
            { id: 'a2-conversation',      title: 'Everyday Conversation',         module: 'lectures', type: 'phrases',    contentId: 'everyday-conversation',      path: '/lectures/phrases/everyday-conversation',                 unit: 4 },
            { id: 'a2-on-phone',          title: 'On the Phone',                  module: 'lectures', type: 'phrases',    contentId: 'on-the-phone',               path: '/lectures/phrases/on-the-phone',                          unit: 4 },
            { id: 'a2-conditionnel',      title: 'Polite Conditionals',           module: 'lectures', type: 'grammar',    contentId: 'conditionnel-intro',         path: '/lectures/grammar/conditionnel-intro',            unit: 4 },
            { id: 'a2-making-plans',      title: 'Making Plans',                  module: 'lectures', type: 'phrases',    contentId: 'making-plans',               path: '/lectures/phrases/making-plans',                          unit: 4 },
            // Unit 5 — Personnes & Bilan (10 steps)
            { id: 'a2-reflexive-basics',  title: 'Reflexive Verbs',               module: 'lectures', type: 'grammar',    contentId: 'reflexive-verbs-basics',     path: '/lectures/grammar/reflexive-verbs-basics',        unit: 5 },
            { id: 'a2-personality',       title: 'Personality & Character',       module: 'vocabulary', type: 'vocabulary', contentId: 'personality-character',      path: '/vocabulary/personality-character',              unit: 5 },
            { id: 'a2-celebrations',      title: 'Celebrations & Events',         module: 'vocabulary', type: 'vocabulary', contentId: 'celebrations-events',         path: '/vocabulary/celebrations-events',                unit: 5 },
            { id: 'a2-reflexive',         title: 'Reflexive Verbs: Full',         module: 'lectures', type: 'grammar',    contentId: 'reflexive-verbs',            path: '/lectures/grammar/reflexive-verbs',               unit: 5 },
            { id: 'a2-adverbs',           title: 'Adverbs',                       module: 'lectures', type: 'grammar',    contentId: 'adverbs-ment',               path: '/lectures/grammar/adverbs-ment',                  unit: 5 },
            { id: 'a2-seasons-activities',title: 'Seasons & Activities',          module: 'vocabulary', type: 'vocabulary', contentId: 'seasons-activities',         path: '/vocabulary/seasons-activities',                 unit: 5 },
            { id: 'a2-reading-marche',    title: 'Reading: Le Marché du Dimanche',module: 'lectures', type: 'reading',    contentId: 'a2-le-marche',               path: '/lectures/reading/a2-le-marche',                          unit: 5 },
            { id: 'a2-reading-lettre',    title: "Reading: Une Lettre d'Amitié",  module: 'lectures', type: 'reading',    contentId: 'a2-une-lettre-damitie',      path: '/lectures/reading/a2-une-lettre-damitie',                 unit: 5 },
            { id: 'a2-reading-recette',   title: 'Reading: Tarte aux Pommes',     module: 'lectures', type: 'reading',    contentId: 'a2-recette-francaise',       path: '/lectures/reading/a2-recette-francaise',                  unit: 5 },
            { id: 'a2-postcard',          title: 'Writing a Postcard',            module: 'lectures', type: 'phrases',    contentId: 'writing-a-postcard',         path: '/lectures/phrases/writing-a-postcard',                    unit: 5 },
        ],
    };
