import type { PhraseCategory } from '../../../types/lectures/phrases';

export const phrasesA1: PhraseCategory[] = [
    {
        level: 'A1', unit: 1,
        id: 'greetings-and-politeness',
        title: 'Greetings & Politeness',
        titleFR: 'Salutations et politesse',
        description: 'Greet people and handle basic polite interactions',
        descriptionFR: 'Saluer et utiliser les formules de politesse essentielles',
        icon: '👋',
        color: '#2563EB',
        phrases: [
            { id: 1, french: 'Bonjour !', english: 'Hello! / Good morning!' },
            { id: 2, french: 'Bonsoir !', english: 'Good evening!' },
            { id: 3, french: 'Salut !', english: 'Hi! / Bye!', note: 'Informal' },
            { id: 4, french: 'Au revoir !', english: 'Goodbye!' },
            { id: 5, french: 'À bientôt !', english: 'See you soon!' },
            { id: 6, french: 'À demain !', english: 'See you tomorrow!' },
            { id: 7, french: 'S\'il vous plaît.', english: 'Please.', note: 'Formal or plural' },
            { id: 8, french: 'S\'il te plaît.', english: 'Please.', note: 'Informal singular' },
            { id: 9, french: 'Merci beaucoup.', english: 'Thank you very much.' },
            { id: 10, french: 'De rien.', english: 'You\'re welcome.' },
            { id: 11, french: 'Excusez-moi.', english: 'Excuse me.', note: 'Formal or plural' },
            { id: 12, french: 'Pardon.', english: 'Sorry. / Excuse me.' },
            { id: 13, french: 'Je suis désolé(e).', english: 'I\'m sorry.' },
            { id: 14, french: 'Ce n\'est pas grave.', english: 'It\'s okay. / It\'s not serious.' },
            { id: 15, french: 'Bonne journée !', english: 'Have a good day!' },
        ],
    },
    {
        level: 'A1', unit: 1,
        id: 'introducing-yourself',
        title: 'Introducing Yourself',
        titleFR: 'Se présenter',
        description: 'Introduce yourself and ask basic personal questions',
        descriptionFR: 'Se présenter et poser des questions personnelles simples',
        icon: '🙋',
        color: '#7C3AED',
        phrases: [
            { id: 1, french: 'Je m\'appelle...', english: 'My name is...' },
            { id: 2, french: 'Comment vous appelez-vous ?', english: 'What is your name?', note: 'Formal' },
            { id: 3, french: 'Comment tu t\'appelles ?', english: 'What is your name?', note: 'Informal' },
            { id: 4, french: 'Enchanté(e).', english: 'Nice to meet you.' },
            { id: 5, french: 'J\'ai vingt-cinq ans.', english: 'I am twenty-five years old.' },
            { id: 6, french: 'Quel âge avez-vous ?', english: 'How old are you?', note: 'Formal' },
            { id: 7, french: 'Je suis français(e).', english: 'I am French.' },
            { id: 8, french: 'Vous êtes de quel pays ?', english: 'What country are you from?' },
            { id: 9, french: 'Je viens de...', english: 'I come from... / I\'m from...' },
            { id: 10, french: 'J\'habite à...', english: 'I live in...' },
            { id: 11, french: 'Vous habitez où ?', english: 'Where do you live?' },
            { id: 12, french: 'Je travaille dans...', english: 'I work in...' },
            { id: 13, french: 'Je suis étudiant(e).', english: 'I am a student.' },
            { id: 14, french: 'Je parle français et anglais.', english: 'I speak French and English.' },
            { id: 15, french: 'Vous parlez anglais ?', english: 'Do you speak English?' },
            { id: 16, french: "Je m'appelle…", english: "My name is…" },
            { id: 17, french: "J'ai X ans.", english: "I am X years old." },
            { id: 18, french: "Je suis de…", english: "I'm from…" },
            { id: 19, french: "J'habite à…", english: "I live in…" },
            { id: 20, french: "Je parle français.", english: "I speak French." },
            { id: 21, french: "Je suis étudiant(e) / professeur.", english: "I'm a student / teacher." },
            { id: 22, french: "Enchanté(e).", english: "Pleased to meet you." },
            { id: 23, french: "Je ne comprends pas.", english: "I don't understand." },
            { id: 24, french: "Pouvez-vous répéter ?", english: "Could you repeat that?" },
            { id: 25, french: "Plus lentement, s'il vous plaît.", english: "More slowly, please." },
            { id: 26, french: "D'où venez-vous ?", english: "Where are you from?" },
            { id: 27, french: "Je suis britannique / irlandais(e).", english: "I'm British / Irish." },
            { id: 28, french: "Ravi(e) de vous rencontrer.", english: "Delighted to meet you." },
        ],
    },
    {
        level: 'A1', unit: 4,
        id: 'shopping-and-paying',
        title: 'Shopping & Paying',
        titleFR: 'Faire les achats et payer',
        description: 'Buy items and handle simple shop interactions',
        descriptionFR: 'Acheter des produits et communiquer simplement dans un magasin',
        icon: '🛍️',
        color: '#D97706',
        phrases: [
            { id: 1, french: 'Bonjour, je voudrais...', english: 'Hello, I would like...' },
            { id: 2, french: 'Vous avez... ?', english: 'Do you have...?' },
            { id: 3, french: 'Je cherche...', english: 'I\'m looking for...' },
            { id: 4, french: 'C\'est combien ?', english: 'How much is it?' },
            { id: 5, french: 'Combien ça coûte ?', english: 'How much does it cost?' },
            { id: 6, french: 'Je prends celui-ci.', english: 'I\'ll take this one.', note: 'Masculine object' },
            { id: 7, french: 'Je prends celle-ci.', english: 'I\'ll take this one.', note: 'Feminine object' },
            { id: 8, french: 'Vous avez une autre taille ?', english: 'Do you have another size?' },
            { id: 9, french: 'Vous avez une autre couleur ?', english: 'Do you have another colour?' },
            { id: 10, french: 'Je peux essayer ?', english: 'Can I try it on?' },
            { id: 11, french: 'C\'est trop grand.', english: 'It\'s too big.' },
            { id: 12, french: 'C\'est trop petit.', english: 'It\'s too small.' },
            { id: 13, french: 'Je peux payer par carte ?', english: 'Can I pay by card?' },
            { id: 14, french: 'Je paie en espèces.', english: 'I\'m paying in cash.' },
            { id: 15, french: 'Merci, bonne journée !', english: 'Thank you, have a good day!' },
        ],
    },
    {
        level: 'A1', unit: 5,
        id: 'problems-and-basic-needs',
        title: 'Problems & Basic Needs',
        titleFR: 'Problèmes et besoins essentiels',
        description: 'Ask for help and handle simple everyday problems',
        descriptionFR: 'Demander de l\'aide et gérer des problèmes simples du quotidien',
        icon: '🆘',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'J\'ai besoin d\'aide.', english: 'I need help.' },
            { id: 2, french: 'Pouvez-vous m\'aider ?', english: 'Can you help me?' },
            { id: 3, french: 'Je ne comprends pas.', english: 'I don\'t understand.' },
            { id: 4, french: 'Vous pouvez répéter ?', english: 'Can you repeat?' },
            { id: 5, french: 'Plus lentement, s\'il vous plaît.', english: 'More slowly, please.' },
            { id: 6, french: 'Comment on dit... en français ?', english: 'How do you say... in French?' },
            { id: 7, french: 'Qu\'est-ce que ça veut dire ?', english: 'What does that mean?' },
            { id: 8, french: 'Je suis perdu(e).', english: 'I\'m lost.' },
            { id: 9, french: 'Je ne trouve pas...', english: 'I can\'t find...' },
            { id: 10, french: 'Je suis malade.', english: 'I\'m sick.' },
            { id: 11, french: 'J\'ai mal à la tête.', english: 'I have a headache.' },
            { id: 12, french: 'J\'ai faim.', english: 'I\'m hungry.' },
            { id: 13, french: 'J\'ai soif.', english: 'I\'m thirsty.' },
            { id: 14, french: 'Je suis fatigué(e).', english: 'I\'m tired.' },
            { id: 15, french: 'Où sont les toilettes ?', english: 'Where are the toilets?' },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'describing-your-home',
        title: 'Describing Your Home',
        titleFR: 'Décrire son logement',
        description: 'Talk about where you live and what your home is like',
        descriptionFR: 'Parler de l\'endroit où vous vivez et de votre logement',
        icon: '🏠',
        color: '#7C3AED',
        phrases: [
            { id: 1, french: 'J\'habite dans un appartement / une maison.', english: 'I live in a flat / a house.' },
            { id: 2, french: 'Mon appartement est au troisième étage.', english: 'My flat is on the third floor.' },
            { id: 3, french: 'Il y a trois pièces.', english: 'There are three rooms.' },
            { id: 4, french: 'Ma chambre est grande / petite.', english: 'My bedroom is big / small.' },
            { id: 5, french: 'Le salon est au rez-de-chaussée.', english: 'The living room is on the ground floor.' },
            { id: 6, french: 'La cuisine est moderne.', english: 'The kitchen is modern.' },
            { id: 7, french: 'Il y a un jardin derrière la maison.', english: 'There is a garden behind the house.' },
            { id: 8, french: 'Mon bureau est à côté de la chambre.', english: 'My study is next to the bedroom.' },
            { id: 9, french: 'La salle de bains est en face de la cuisine.', english: 'The bathroom is opposite the kitchen.' },
            { id: 10, french: 'Il n\'y a pas de garage.', english: 'There is no garage.' },
            { id: 11, french: 'Nous avons un balcon.', english: 'We have a balcony.' },
            { id: 12, french: 'C\'est un quartier calme.', english: 'It\'s a quiet neighbourhood.' },
            { id: 13, french: 'L\'appartement est bien situé.', english: 'The flat is well located.' },
            { id: 14, french: 'J\'habite au centre-ville / en banlieue.', english: 'I live in the city centre / in the suburbs.' },
            { id: 15, french: 'C\'est lumineux et spacieux.', english: 'It\'s bright and spacious.' },
        ],
    },
    {
        level: 'A1', unit: 4,
        id: 'at-the-cafe',
        title: 'At the Café',
        titleFR: 'Au café',
        description: 'Order drinks and snacks, ask for the bill, and chat with the waiter',
        descriptionFR: 'Commander des boissons, demander l\'addition et échanger avec le serveur',
        icon: '☕',
        color: '#92400E',
        phrases: [
            { id: 1, french: 'Un café, s\'il vous plaît.', english: 'A coffee, please.', note: 'The default order — un café = an espresso in France' },
            { id: 2, french: 'Je voudrais…', english: 'I would like…', note: 'Polite way to order; more formal than je veux' },
            { id: 3, french: 'Je prends…', english: 'I\'ll have…', note: 'Casual alternative to je voudrais' },
            { id: 4, french: 'Vous avez une table pour deux ?', english: 'Do you have a table for two?' },
            { id: 5, french: 'La carte, s\'il vous plaît.', english: 'The menu, please.' },
            { id: 6, french: 'Qu\'est-ce que vous recommandez ?', english: 'What do you recommend?' },
            { id: 7, french: 'En terrasse ou à l\'intérieur ?', english: 'On the terrace or inside?', note: 'The waiter asks you this' },
            { id: 8, french: 'Avec du lait ?', english: 'With milk?' },
            { id: 9, french: 'Sans sucre, s\'il vous plaît.', english: 'Without sugar, please.' },
            { id: 10, french: 'C\'est délicieux !', english: 'It\'s delicious!' },
            { id: 11, french: 'C\'est combien ?', english: 'How much is it?' },
            { id: 12, french: 'L\'addition, s\'il vous plaît.', english: 'The bill, please.', note: 'Never ask for la facture in a café — that\'s for professional invoices' },
            { id: 13, french: 'Service compris ?', english: 'Is service included?' },
            { id: 14, french: 'Vous acceptez les cartes ?', english: 'Do you accept cards?' },
            { id: 15, french: 'Merci, au revoir !', english: 'Thank you, goodbye!' },
        ],
    },
    {
        level: 'A1', unit: 6,
        id: 'asking-directions',
        title: 'Asking for Directions',
        titleFR: 'Demander son chemin',
        description: 'Find your way around a French city — ask for directions and understand the answers',
        descriptionFR: 'Orientez-vous dans une ville française — demandez et comprenez les indications',
        icon: '🗺️',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'Pardon, où est… ?', english: 'Excuse me, where is… ?', note: 'Always start with Pardon — it\'s the polite opener' },
            { id: 2, french: 'Je suis perdu(e).', english: 'I\'m lost.', note: 'Add -e if you\'re female: perdue' },
            { id: 3, french: 'Pouvez-vous m\'aider ?', english: 'Can you help me?' },
            { id: 4, french: 'C\'est loin d\'ici ?', english: 'Is it far from here?' },
            { id: 5, french: 'C\'est à combien de minutes à pied ?', english: 'How many minutes on foot?' },
            { id: 6, french: 'Tournez à gauche.', english: 'Turn left.' },
            { id: 7, french: 'Tournez à droite.', english: 'Turn right.' },
            { id: 8, french: 'Allez tout droit.', english: 'Go straight ahead.' },
            { id: 9, french: 'Prenez la première rue à gauche.', english: 'Take the first street on the left.' },
            { id: 10, french: 'Au feu rouge, tournez à droite.', english: 'At the traffic lights, turn right.' },
            { id: 11, french: 'Au rond-point, prenez la deuxième sortie.', english: 'At the roundabout, take the second exit.' },
            { id: 12, french: 'C\'est en face de la mairie.', english: 'It\'s opposite the town hall.', note: 'en face de = opposite / facing' },
            { id: 13, french: 'C\'est à côté de la pharmacie.', english: 'It\'s next to the pharmacy.', note: 'à côté de = next to' },
            { id: 14, french: 'C\'est à deux kilomètres d\'ici.', english: 'It\'s two kilometres from here.' },
            { id: 15, french: 'Il y a un bus qui va là-bas ?', english: 'Is there a bus that goes there?' },
        ],
    },
    {
        level: 'A1', unit: 4,
        id: 'shopping-basics',
        title: 'Shopping Basics',
        titleFR: 'Faire les courses',
        description: 'Buy clothes, ask for prices, and handle transactions in French shops',
        descriptionFR: 'Acheter des vêtements, demander les prix et gérer les achats dans les magasins',
        icon: '🛍️',
        color: '#7C3AED',
        phrases: [
            { id: 1, french: 'Je cherche…', english: 'I\'m looking for…' },
            { id: 2, french: 'Vous avez ça en taille M ?', english: 'Do you have this in size M?', note: 'Replace M with S, L, XL as needed' },
            { id: 3, french: 'C\'est combien ?', english: 'How much is it?' },
            { id: 4, french: 'C\'est trop cher.', english: 'It\'s too expensive.' },
            { id: 5, french: 'C\'est ma taille.', english: 'It\'s my size.' },
            { id: 6, french: 'Ça ne me va pas.', english: 'It doesn\'t suit me / it doesn\'t fit me.' },
            { id: 7, french: 'Je vais le prendre.', english: 'I\'ll take it. (masc. item)', note: 'Use la for feminine items: je vais la prendre' },
            { id: 8, french: 'Vous acceptez les cartes bancaires ?', english: 'Do you accept bank cards?' },
            { id: 9, french: 'Un sac, s\'il vous plaît.', english: 'A bag, please.' },
            { id: 10, french: 'Avez-vous un reçu ?', english: 'Do you have a receipt?' },
            { id: 11, french: 'C\'est en solde ?', english: 'Is it on sale?', note: 'Les soldes = the sales (seasonal)' },
            { id: 12, french: 'Il y a une remise ?', english: 'Is there a discount?' },
            { id: 13, french: 'C\'est en promotion.', english: 'It\'s on special offer.' },
            { id: 14, english: 'Do you have change?', french: 'Avez-vous de la monnaie ?' },
            { id: 15, french: 'C\'est parfait, merci !', english: 'It\'s perfect, thank you!' },
        ],
    },
    {
        level: 'A1', unit: 7,
        id: 'talking-about-health',
        title: 'Talking About Health',
        titleFR: 'Parler de sa santé',
        description: 'Describe symptoms, find a pharmacy, and say how you feel',
        descriptionFR: 'Décrire des symptômes, trouver une pharmacie et dire comment on se sent',
        icon: '🏥',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'J\'ai mal à la tête.', english: 'I have a headache.', note: 'avoir mal à = to have pain in; à la for fem., au for masc.' },
            { id: 2, french: 'Je suis fatigué(e).', english: 'I am tired.', note: 'Add -e if you are female: fatiguée' },
            { id: 3, french: 'Je suis malade.', english: 'I am sick / ill.' },
            { id: 4, french: 'J\'ai de la fièvre.', english: 'I have a fever.' },
            { id: 5, french: 'Je tousse.', english: 'I am coughing.', note: 'tousser = to cough; je tousse (regular -er)' },
            { id: 6, french: 'J\'ai le rhume.', english: 'I have a cold.', note: 'avoir le rhume = to have a cold (not un rhume)' },
            { id: 7, french: 'Je me sens bien.', english: 'I feel well.', note: 'se sentir = to feel; reflexive verb' },
            { id: 8, french: 'Je suis en bonne santé.', english: 'I am in good health.' },
            { id: 9, french: 'J\'ai besoin d\'un médecin.', english: 'I need a doctor.' },
            { id: 10, french: 'Où est la pharmacie ?', english: 'Where is the pharmacy?', note: 'Pharmacies are marked by a green cross in France' },
            { id: 11, french: 'J\'ai mal au ventre.', english: 'I have a stomachache.', note: 'au ventre = in the stomach (ventre is masculine)' },
            { id: 12, french: 'Je suis allergique à…', english: 'I am allergic to…' },
            { id: 13, french: 'Ça fait mal.', english: 'It hurts.', note: 'faire mal = to hurt; Où est-ce que ça fait mal ? = Where does it hurt?' },
            { id: 14, french: 'J\'ai besoin de médicaments.', english: 'I need medicine / medication.' },
            { id: 15, french: 'Je vais mieux, merci.', english: 'I\'m feeling better, thank you.' },
        ],
    },
    {
        level: 'A1', unit: 1,
        id: 'classroom-survival',
        title: 'Classroom Survival',
        titleFR: 'Survie en classe',
        description: 'Essential phrases for the language classroom',
        descriptionFR: 'Phrases essentielles pour la salle de classe',
        icon: '🏫',
        color: '#059669',
        phrases: [
            { id: 1, french: 'Je ne comprends pas.', english: 'I don\'t understand.' },
            { id: 2, french: 'Pouvez-vous répéter ?', english: 'Could you repeat that?' },
            { id: 3, french: 'Comment dit-on… en français ?', english: 'How do you say… in French?' },
            { id: 4, french: 'Qu\'est-ce que ça veut dire ?', english: 'What does that mean?' },
            { id: 5, french: 'Comment ça s\'écrit ?', english: 'How do you spell that?' },
            { id: 6, french: 'Je n\'entends pas bien.', english: 'I can\'t hear properly.' },
            { id: 7, french: 'Pouvez-vous parler plus lentement ?', english: 'Could you speak more slowly?' },
            { id: 8, french: 'Est-ce que c\'est correct ?', english: 'Is that correct?' },
            { id: 9, french: 'Encore une fois, s\'il vous plaît.', english: 'Once more, please.' },
            { id: 10, french: 'J\'ai une question.', english: 'I have a question.' },
            { id: 11, french: 'Je ne sais pas.', english: 'I don\'t know.' },
            { id: 12, french: 'Peut-on traduire ?', english: 'Can we translate?' },
            { id: 13, french: 'Pouvez-vous l\'écrire au tableau ?', english: 'Could you write it on the board?' },
            { id: 14, french: 'Merci pour votre patience.', english: 'Thank you for your patience.' },
            { id: 15, french: 'Je comprends maintenant.', english: 'I understand now.' },
        ],
    },
];
