import type { PhraseCategory } from '../../../types/lectures/phrases';

export const phrasesA2: PhraseCategory[] = [
    {
        level: 'A2', unit: 4,
        id: 'everyday-conversation',
        title: 'Everyday Conversation',
        titleFR: 'Conversation quotidienne',
        description: 'Handle simple everyday conversations',
        descriptionFR: 'Participer à des conversations simples du quotidien',
        icon: '💬',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'Comment ça va ?', english: 'How are you?' },
            { id: 2, french: 'Ça va bien, merci.', english: 'I\'m fine, thank you.' },
            { id: 3, french: 'Et toi ?', english: 'And you?', note: 'Informal' },
            { id: 4, french: 'Et vous ?', english: 'And you?', note: 'Formal or plural' },
            { id: 5, french: 'Qu\'est-ce que tu fais ?', english: 'What are you doing? / What do you do?' },
            { id: 6, french: 'J\'aime beaucoup.', english: 'I like it a lot.' },
            { id: 7, french: 'Je n\'aime pas.', english: 'I don\'t like it.' },
            { id: 8, french: 'Je préfère...', english: 'I prefer...' },
            { id: 9, french: 'Moi aussi.', english: 'Me too.' },
            { id: 10, french: 'Moi non plus.', english: 'Me neither.' },
            { id: 11, french: 'D\'accord.', english: 'Okay. / I agree.' },
            { id: 12, french: 'Pas de problème.', english: 'No problem.' },
            { id: 13, french: 'Je ne comprends pas.', english: 'I don\'t understand.' },
            { id: 14, french: 'Vous pouvez répéter ?', english: 'Can you repeat?' },
            { id: 15, french: 'Plus lentement, s\'il vous plaît.', english: 'More slowly, please.' },
            { id: 16, french: "Ça fait longtemps !", english: "It's been a while! / Long time no see!" },
            { id: 17, french: "Comment ça se passe ?", english: "How's it going? / How are things?" },
            { id: 18, french: "Ça marche !", english: "Works for me! / Sure!" },
            { id: 19, french: "C'est pas grave.", english: "It's no big deal. / Don't worry about it.", note: "Very common informal reassurance" },
            { id: 20, french: "On verra.", english: "We'll see." },
            { id: 21, french: "À ta place, je...", english: "If I were you, I would..." },
            { id: 22, french: "Je n'en reviens pas !", english: "I can't believe it! / I'm amazed!" },
            { id: 23, french: "Tu plaisantes ?", english: "Are you joking? / Are you serious?" },
            { id: 24, french: "Sans blague ?", english: "No kidding? / Really?" },
            { id: 25, french: "Ça me dit quelque chose.", english: "That rings a bell. / That sounds familiar." },
            { id: 26, french: "Je m'en fiche.", english: "I don't care. / I couldn't care less.", note: "Informal; stronger version: je m'en fous" },
            { id: 27, french: "Ça dépend.", english: "It depends." },
            { id: 28, french: "Franchement...", english: "Honestly... / Frankly..." },
            { id: 29, french: "En tout cas...", english: "In any case... / Anyway..." },
            { id: 30, french: "Il ne faut pas exagérer !", english: "Don't exaggerate! / Let's not go overboard!" },
        ],
    },
    {
        level: 'A2', unit: 4,
        id: 'making-plans',
        title: 'Making Plans',
        titleFR: 'Faire des projets',
        description: 'Invite someone and arrange simple plans',
        descriptionFR: 'Inviter quelqu\'un et organiser une sortie simple',
        icon: '📅',
        color: '#DB2777',
        phrases: [
            { id: 1, french: 'Tu es libre samedi ?', english: 'Are you free on Saturday?' },
            { id: 2, french: 'Tu veux venir ?', english: 'Do you want to come?' },
            { id: 3, french: 'On va au cinéma ?', english: 'Shall we go to the cinema?' },
            { id: 4, french: 'On prend un café ?', english: 'Shall we have a coffee?' },
            { id: 5, french: 'Bonne idée !', english: 'Good idea!' },
            { id: 6, french: 'Oui, avec plaisir.', english: 'Yes, gladly. / I\'d love to.' },
            { id: 7, french: 'Désolé(e), je ne peux pas.', english: 'Sorry, I can\'t.' },
            { id: 8, french: 'Peut-être une autre fois.', english: 'Maybe another time.' },
            { id: 9, french: 'Quel jour ?', english: 'What day?' },
            { id: 10, french: 'À quelle heure ?', english: 'At what time?' },
            { id: 11, french: 'Où est-ce qu\'on se retrouve ?', english: 'Where shall we meet?' },
            { id: 12, french: 'On se retrouve à huit heures.', english: 'Let\'s meet at eight.' },
            { id: 13, french: 'Ça te va ?', english: 'Does that work for you?' },
            { id: 14, french: 'Oui, ça me va.', english: 'Yes, that works for me.' },
            { id: 15, french: 'À samedi !', english: 'See you Saturday!' },
            { id: 16, french: "Tu es libre ce week-end ?", english: "Are you free this weekend?" },
            { id: 17, french: "On pourrait aller au cinéma.", english: "We could go to the cinema.", note: "On pourrait = we could (conditional)" },
            { id: 18, french: "Ça te dirait d'aller dîner ?", english: "Would you fancy going for dinner?" },
            { id: 19, french: "J'ai très envie de voir cette expo.", english: "I really want to see that exhibition." },
            { id: 20, french: "Rendez-vous à vingt heures devant le cinéma.", english: "Let's meet at 8pm in front of the cinema." },
            { id: 21, french: "Je passerai te chercher à sept heures.", english: "I'll come and pick you up at seven." },
            { id: 22, french: "C'est annulé, désolé(e).", english: "It's cancelled, sorry." },
            { id: 23, french: "Je suis désolé(e), je ne peux pas.", english: "I'm sorry, I can't make it." },
            { id: 24, french: "Une autre fois peut-être ?", english: "Another time maybe?" },
            { id: 25, french: "C'était une excellente idée !", english: "That was an excellent idea!" },
            { id: 26, french: "On recommence quand ?", english: "When shall we do it again?" },
            { id: 27, french: "Je te rappelle ce soir.", english: "I'll call you back tonight." },
            { id: 28, french: "C'est noté !", english: "Got it! / Noted!" },
            { id: 29, french: "On se retrouve où exactement ?", english: "Where exactly shall we meet?" },
            { id: 30, french: "À tout à l'heure !", english: "See you later!" },
        ],
    },
    {
        level: 'A2', unit: 2,
        id: 'at-the-restaurant',
        title: 'At the Café & Restaurant',
        titleFR: 'Au café et au restaurant',
        description: 'Order food and drinks in simple situations',
        descriptionFR: 'Commander à boire et à manger dans des situations simples',
        icon: '🍽️',
        color: '#EA580C',
        phrases: [
            { id: 1, french: 'Une table pour deux, s\'il vous plaît.', english: 'A table for two, please.' },
            { id: 2, french: 'Je voudrais...', english: 'I would like...' },
            { id: 3, french: 'Je vais prendre...', english: 'I\'ll have...' },
            { id: 4, french: 'Un café, s\'il vous plaît.', english: 'A coffee, please.' },
            { id: 5, french: 'Une bouteille d\'eau, s\'il vous plaît.', english: 'A bottle of water, please.' },
            { id: 6, french: 'Qu\'est-ce que vous avez comme dessert ?', english: 'What do you have for dessert?' },
            { id: 7, french: 'Je ne mange pas de viande.', english: 'I don\'t eat meat.' },
            { id: 8, french: 'Je suis allergique à...', english: 'I\'m allergic to...' },
            { id: 9, french: 'Sans..., s\'il vous plaît.', english: 'Without..., please.' },
            { id: 10, french: 'Encore de l\'eau, s\'il vous plaît.', english: 'Some more water, please.' },
            { id: 11, french: 'C\'est très bon.', english: 'It\'s very good.' },
            { id: 12, french: 'C\'est délicieux.', english: 'It\'s delicious.' },
            { id: 13, french: 'L\'addition, s\'il vous plaît.', english: 'The bill, please.' },
            { id: 14, french: 'Je peux payer par carte ?', english: 'Can I pay by card?' },
            { id: 15, french: 'Merci, au revoir.', english: 'Thank you, goodbye.' },
            { id: 16, french: "Avez-vous une réservation ?", english: "Do you have a reservation?" },
            { id: 17, french: "Je voudrais voir la carte, s'il vous plaît.", english: "I'd like to see the menu, please." },
            { id: 18, french: "Qu'est-ce que vous recommandez ?", english: "What do you recommend?" },
            { id: 19, french: "Je vais prendre le plat du jour.", english: "I'll have the dish of the day." },
            { id: 20, french: "C'est inclus dans le menu ?", english: "Is it included in the set menu?" },
            { id: 21, french: "La cuisson, s'il vous plaît ?", english: "How would you like it cooked?", note: "said by the server for steak" },
            { id: 22, french: "Saignant / à point / bien cuit.", english: "Rare / medium / well done." },
            { id: 23, french: "Le service est compris ?", english: "Is service included?" },
            { id: 24, french: "C'était délicieux, merci.", english: "It was delicious, thank you." },
            { id: 25, french: "On partage ?", english: "Shall we split the bill?" },
            { id: 26, french: "Je vous offre.", english: "It's on me. / I'm treating you." },
            { id: 27, french: "Encore un peu de vin ?", english: "A little more wine?" },
        ],
    },
    {
        level: 'A2', unit: 1,
        id: 'daily-routine',
        title: 'Daily Routine',
        titleFR: 'La routine quotidienne',
        description: 'Describe your day, habits, and schedule',
        descriptionFR: 'Décrire sa journée, ses habitudes et son emploi du temps',
        icon: '📅',
        color: '#059669',
        phrases: [
            { id: 1, french: 'Je me lève à sept heures.', english: 'I get up at seven o\'clock.' },
            { id: 2, french: 'Je prends mon petit-déjeuner.', english: 'I have breakfast.' },
            { id: 3, french: 'Je vais au travail en métro.', english: 'I go to work by metro.' },
            { id: 4, french: 'Je commence à neuf heures.', english: 'I start at nine o\'clock.' },
            { id: 5, french: 'Je rentre chez moi à dix-huit heures.', english: 'I get home at six o\'clock.' },
            { id: 6, french: 'Le week-end, je fais du sport.', english: 'At the weekend, I do sport.' },
            { id: 7, french: 'D\'habitude, je prépare le dîner.', english: 'Usually, I make dinner.', note: 'D\'habitude = usually, triggers imparfait in the past' },
            { id: 8, french: 'Parfois je mange au restaurant.', english: 'Sometimes I eat at a restaurant.' },
            { id: 9, french: 'Je n\'ai pas le temps de regarder la télé.', english: 'I don\'t have time to watch TV.' },
            { id: 10, french: 'Qu\'est-ce que tu fais ce soir ?', english: 'What are you doing tonight?' },
            { id: 11, french: 'On se retrouve à quelle heure ?', english: 'What time shall we meet?' },
            { id: 12, french: 'Je dois finir ce travail d\'abord.', english: 'I need to finish this work first.' },
            { id: 13, french: 'Je me couche vers onze heures.', english: 'I go to bed around eleven o\'clock.' },
            { id: 14, french: 'Ça m\'arrive souvent.', english: 'That happens to me often.' },
            { id: 15, french: 'Ma journée est bien chargée.', english: 'My day is very busy.' },
        ],
    },
    {
        level: 'A2', unit: 3,
        id: 'at-the-hotel',
        title: 'At the Hotel',
        titleFR: 'À l\'hôtel',
        description: 'Check in, report problems, and manage your hotel stay',
        descriptionFR: 'S\'enregistrer, signaler un problème et gérer son séjour',
        icon: '🏨',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'J\'ai une réservation au nom de…', english: 'I have a booking under the name of…' },
            { id: 2, french: 'Une chambre pour deux personnes, s\'il vous plaît.', english: 'A room for two people, please.' },
            { id: 3, french: 'Avec salle de bains privée, s\'il vous plaît.', english: 'With a private bathroom, please.' },
            { id: 4, french: 'Le petit-déjeuner est inclus ?', english: 'Is breakfast included?' },
            { id: 5, french: 'À quelle heure est le check-out ?', english: 'What time is check-out?' },
            { id: 6, french: 'Avez-vous le wifi ?', english: 'Do you have wifi?', note: 'Pronounced "wee-fee" in French' },
            { id: 7, french: 'Ma chambre n\'est pas encore prête.', english: 'My room isn\'t ready yet.' },
            { id: 8, french: 'Il y a un problème dans ma chambre.', english: 'There\'s a problem in my room.' },
            { id: 9, french: 'Pouvez-vous m\'appeler un taxi ?', english: 'Could you call me a taxi?' },
            { id: 10, french: 'La clé de ma chambre, s\'il vous plaît.', english: 'My room key, please.' },
            { id: 11, french: 'Est-ce qu\'il y a un parking ?', english: 'Is there a car park?' },
            { id: 12, french: 'Je voudrais prolonger mon séjour.', english: 'I\'d like to extend my stay.' },
            { id: 13, french: 'C\'est trop bruyant.', english: 'It\'s too noisy.' },
            { id: 14, french: 'Merci pour tout, c\'était parfait.', english: 'Thank you for everything, it was perfect.' },
            { id: 15, french: 'Je reviendrai avec plaisir.', english: 'I\'ll be back with pleasure.' },
        ],
    },
    {
        level: 'A2', unit: 4,
        id: 'at-the-doctor',
        title: 'At the Doctor\'s',
        titleFR: 'Chez le médecin',
        description: 'Describe symptoms, get a prescription, and manage a medical visit',
        descriptionFR: 'Décrire des symptômes, obtenir une ordonnance et gérer une visite médicale',
        icon: '🩺',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'J\'ai mal à la gorge depuis trois jours.', english: 'I\'ve had a sore throat for three days.', note: 'depuis + present tense for ongoing symptom' },
            { id: 2, french: 'J\'ai de la fièvre depuis hier.', english: 'I\'ve had a fever since yesterday.' },
            { id: 3, french: 'Depuis quand avez-vous ces symptômes ?', english: 'How long have you had these symptoms?' },
            { id: 4, french: 'Je suis allergique à la pénicilline.', english: 'I\'m allergic to penicillin.' },
            { id: 5, french: 'Je prends ces médicaments en ce moment.', english: 'I\'m currently taking this medication.' },
            { id: 6, french: 'C\'est urgent ?', english: 'Is it urgent?' },
            { id: 7, french: 'Pouvez-vous me faire une ordonnance ?', english: 'Could you write me a prescription?' },
            { id: 8, french: 'Je n\'ai pas d\'appétit.', english: 'I have no appetite.' },
            { id: 9, french: 'J\'ai du mal à dormir.', english: 'I\'m having trouble sleeping.' },
            { id: 10, french: 'Est-ce grave ?', english: 'Is it serious?' },
            { id: 11, french: 'Combien de fois par jour ?', english: 'How many times a day?' },
            { id: 12, french: 'À jeun ou après les repas ?', english: 'On an empty stomach or after meals?' },
            { id: 13, french: 'Je me sens mieux depuis ce matin.', english: 'I\'ve been feeling better since this morning.' },
            { id: 14, french: 'Quand dois-je revenir vous voir ?', english: 'When should I come back to see you?' },
            { id: 15, french: 'Avez-vous votre carte Vitale ?', english: 'Do you have your health card?', note: 'The Carte Vitale is the French social security health card' },
        ],
    },
    {
        level: 'A2', unit: 4,
        id: 'on-the-phone',
        title: 'On the Phone',
        titleFR: 'Au téléphone',
        description: 'Make and receive phone calls, leave messages, and handle common phone situations in French',
        descriptionFR: 'Passer et recevoir des appels, laisser des messages et gérer des situations téléphoniques courantes',
        icon: '📞',
        color: '#2563EB',
        phrases: [
            { id: 1, french: 'Allô ?', english: 'Hello? (on the phone)' },
            { id: 2, french: 'C\'est de la part de qui ?', english: 'Who is calling?' },
            { id: 3, french: 'Ne quittez pas.', english: 'Hold on. / Please hold.' },
            { id: 4, french: 'Je voudrais parler à M. / Mme…', english: 'I would like to speak to Mr. / Mrs. …' },
            { id: 5, french: 'Pouvez-vous rappeler plus tard ?', english: 'Can you call back later?' },
            { id: 6, french: 'Je peux laisser un message ?', english: 'Can I leave a message?' },
            { id: 7, french: 'La ligne est occupée.', english: 'The line is busy.' },
            { id: 8, french: 'Vous avez fait un faux numéro.', english: 'You have the wrong number.' },
            { id: 9, french: 'Je vous entends mal.', english: 'I can\'t hear you well.' },
            { id: 10, french: 'Pouvez-vous parler plus lentement ?', english: 'Can you speak more slowly?' },
            { id: 11, french: 'Je vous rappelle dès que possible.', english: 'I will call you back as soon as possible.' },
            { id: 12, french: 'Il n\'est pas disponible pour le moment.', english: 'He / She is not available at the moment.' },
            { id: 13, french: 'Quel est votre numéro de téléphone ?', english: 'What is your phone number?' },
            { id: 14, french: 'J\'ai reçu votre message.', english: 'I received your message.' },
            { id: 15, french: 'À bientôt. Au revoir !', english: 'Talk soon. Goodbye!' },
        ],
    },
    {
        level: 'A2', unit: 2,
        id: 'at-the-market',
        title: 'At the Market',
        titleFR: 'Au marché',
        description: 'Buy fresh produce, ask about prices, and chat with vendors',
        descriptionFR: 'Acheter des produits frais, demander les prix et discuter avec les vendeurs',
        icon: '🥦',
        color: '#059669',
        phrases: [
            { id: 1, french: 'C\'est combien le kilo ?', english: 'How much is it per kilo?' },
            { id: 2, french: 'Je voudrais cinq cents grammes de…', english: 'I\'d like five hundred grams of…' },
            { id: 3, french: 'Vous avez des tomates bien mûres ?', english: 'Do you have some ripe tomatoes?' },
            { id: 4, french: 'C\'est de la région ?', english: 'Is it local / from the region?' },
            { id: 5, french: 'Je prends ça, s\'il vous plaît.', english: 'I\'ll take this one, please.' },
            { id: 6, french: 'Donnez-m\'en un peu plus.', english: 'Give me a bit more.' },
            { id: 7, french: 'C\'est pour aujourd\'hui ?', english: 'Is it for today?' },
            { id: 8, french: 'Avez-vous autre chose à me conseiller ?', english: 'Do you have anything else to recommend?' },
            { id: 9, french: 'C\'est un peu trop mûr.', english: 'It\'s a bit too ripe.' },
            { id: 10, french: 'Je cherche des herbes fraîches.', english: 'I\'m looking for fresh herbs.' },
            { id: 11, french: 'Ça sent bon !', english: 'That smells good!' },
            { id: 12, french: 'Le marché ferme à quelle heure ?', english: 'What time does the market close?' },
            { id: 13, french: 'Vous êtes là tous les samedis ?', english: 'Are you here every Saturday?' },
            { id: 14, french: 'C\'est fait maison ?', english: 'Is it home-made?' },
            { id: 15, french: 'Merci, bonne journée !', english: 'Thank you, have a good day!' },
        ],
    },
    {
        level: 'A2', unit: 5,
        id: 'writing-a-postcard',
        title: 'Writing a Postcard',
        titleFR: 'Écrire une carte postale',
        description: 'Write a postcard to a French friend while on holiday',
        descriptionFR: 'Écrire une carte postale à un ami français pendant les vacances',
        icon: '✉️',
        color: '#D97706',
        phrases: [
            { id: 1, french: 'Je t\'écris de Barcelone.', english: 'I\'m writing to you from Barcelona.' },
            { id: 2, french: 'Il fait très beau ici.', english: 'The weather is lovely here.' },
            { id: 3, french: 'Je suis en vacances depuis une semaine.', english: 'I\'ve been on holiday for a week.' },
            { id: 4, french: 'J\'ai visité le musée Picasso hier.', english: 'I visited the Picasso museum yesterday.' },
            { id: 5, french: 'J\'ai mangé des spécialités locales.', english: 'I\'ve eaten local specialities.' },
            { id: 6, french: 'Les gens sont très accueillants.', english: 'The people are very welcoming.' },
            { id: 7, french: 'Le voyage s\'est bien passé.', english: 'The journey went well.' },
            { id: 8, french: 'Je rentre le quinze août.', english: 'I\'m coming back on the fifteenth of August.' },
            { id: 9, french: 'Tu me manques !', english: 'I miss you!', note: 'tu me manques = you are missing to me (structure reversed vs. English)' },
            { id: 10, french: 'Je pense souvent à toi.', english: 'I often think of you.' },
            { id: 11, french: 'Grosses bises !', english: 'Lots of love! / Big kisses!' },
            { id: 12, french: 'À bientôt !', english: 'See you soon!' },
            { id: 13, french: 'La ville est magnifique.', english: 'The city is magnificent.' },
            { id: 14, french: 'Je t\'enverrai des photos.', english: 'I\'ll send you some photos.' },
            { id: 15, french: 'Prends soin de toi.', english: 'Take care of yourself.' },
        ],
    },
];
