import type { PhraseCategory } from '../../../types/lectures/phrases';

export const phrasesB1: PhraseCategory[] = [
    {
        level: 'B1', unit: 3,
        id: 'getting-around',
        title: 'Getting Around',
        titleFR: 'Se déplacer',
        description: 'Ask for directions and use basic public transport',
        descriptionFR: 'Demander son chemin et utiliser les transports en commun',
        icon: '🗺️',
        color: '#059669',
        phrases: [
            { id: 1, french: 'Excusez-moi, où est la gare ?', english: 'Excuse me, where is the station?' },
            { id: 2, french: 'Où est la station de métro ?', english: 'Where is the metro station?' },
            { id: 3, french: 'Je cherche cette adresse.', english: 'I\'m looking for this address.' },
            { id: 4, french: 'C\'est loin ?', english: 'Is it far?' },
            { id: 5, french: 'C\'est près d\'ici ?', english: 'Is it near here?' },
            { id: 6, french: 'Continuez tout droit.', english: 'Continue straight ahead.' },
            { id: 7, french: 'Tournez à gauche.', english: 'Turn left.' },
            { id: 8, french: 'Tournez à droite.', english: 'Turn right.' },
            { id: 9, french: 'C\'est en face de...', english: 'It\'s opposite...' },
            { id: 10, french: 'C\'est à côté de...', english: 'It\'s next to...' },
            { id: 11, french: 'Je voudrais un billet pour...', english: 'I\'d like a ticket to...' },
            { id: 12, french: 'À quelle heure part le train ?', english: 'What time does the train leave?' },
            { id: 13, french: 'Ce bus va à... ?', english: 'Does this bus go to...?' },
            { id: 14, french: 'Je descends où ?', english: 'Where do I get off?' },
            { id: 15, french: 'Merci pour votre aide.', english: 'Thank you for your help.' },
            { id: 16, french: "Où se trouve la station de métro la plus proche ?", english: "Where is the nearest metro station?" },
            { id: 17, french: "Je cherche la rue...", english: "I'm looking for... street." },
            { id: 18, french: "C'est loin d'ici ?", english: "Is it far from here?" },
            { id: 19, french: "À pied, ça prend combien de temps ?", english: "How long does it take on foot?" },
            { id: 20, french: "Prenez la première à gauche / droite.", english: "Take the first left / right." },
            { id: 21, french: "Continuez tout droit.", english: "Carry straight on." },
            { id: 22, french: "C'est au bout de la rue.", english: "It's at the end of the street." },
            { id: 23, french: "À quelle heure part le prochain train ?", english: "What time does the next train leave?" },
            { id: 24, french: "Est-ce que ce bus s'arrête à... ?", english: "Does this bus stop at...?" },
            { id: 25, french: "J'ai raté mon train.", english: "I missed my train." },
            { id: 26, french: "Le vol est à l'heure ?", english: "Is the flight on time?" },
            { id: 27, french: "Pouvez-vous appeler un taxi ?", english: "Could you call a taxi?" },
            { id: 28, french: "Je suis perdu(e).", english: "I'm lost." },
            { id: 29, french: "Déposez-moi ici, s'il vous plaît.", english: "Drop me off here, please." },
        ],
    },
    {
        level: 'B1', unit: 2,
        id: 'expressing-opinions',
        title: 'Expressing Opinions',
        titleFR: 'Exprimer ses opinions',
        description: 'Share your views, agree, and disagree in French',
        descriptionFR: 'Partagez vos idées, approuvez et désapprouvez',
        icon: '💭',
        color: '#7C3AED',
        phrases: [
            { id: 1, french: 'À mon avis...', english: 'In my opinion...' },
            { id: 2, french: 'Selon moi...', english: 'According to me... / As I see it...' },
            { id: 3, french: 'Je trouve que...', english: 'I find that... / I think that...' },
            { id: 4, french: 'Je suis (tout à fait) d\'accord.', english: 'I (completely) agree.' },
            { id: 5, french: 'Je ne suis pas du tout d\'accord.', english: 'I completely disagree.' },
            { id: 6, french: 'C\'est discutable.', english: 'That\'s debatable. / You could argue either way.' },
            { id: 7, french: 'Dans une certaine mesure...', english: 'To a certain extent...' },
            { id: 8, french: 'Il faut nuancer.', english: 'We need to be nuanced. / It\'s more complicated than that.' },
            { id: 9, french: 'D\'un côté... de l\'autre...', english: 'On one hand... on the other...' },
            { id: 10, french: 'Cela dit...', english: 'That said... / Having said that...' },
            { id: 11, french: 'Je n\'avais pas pensé à ça.', english: 'I hadn\'t thought of that.' },
            { id: 12, french: 'Tu as un point.', english: 'You have a point. / That\'s a fair point.' },
            { id: 13, french: 'Je ne suis pas convaincu(e).', english: 'I\'m not convinced.' },
            { id: 14, french: 'C\'est une question de perspective.', english: 'It\'s a matter of perspective.' },
            { id: 15, french: 'En définitive...', english: 'Ultimately... / When all is said and done...' },
        ],
    },
    {
        level: 'B1', unit: 1,
        id: 'expressing-feelings',
        title: 'Expressing Feelings',
        titleFR: 'Exprimer ses émotions',
        description: 'Describe your emotions and inner states in nuanced French',
        descriptionFR: 'Décrivez vos émotions et états intérieurs en français nuancé',
        icon: '💛',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'Je me sens…', english: 'I feel…' },
            { id: 2, french: 'Ça m\'a beaucoup touché(e).', english: 'It really moved / touched me.' },
            { id: 3, french: 'Je suis bouleversé(e).', english: 'I\'m overwhelmed / deeply affected.' },
            { id: 4, french: 'J\'ai du mal à expliquer ce que je ressens.', english: 'I\'m finding it hard to explain what I\'m feeling.' },
            { id: 5, french: 'Je suis soulagé(e).', english: 'I\'m relieved.' },
            { id: 6, french: 'Ça m\'a rendu(e) triste.', english: 'It made me sad.' },
            { id: 7, french: 'Je suis fier / fière de…', english: 'I\'m proud of…' },
            { id: 8, french: 'Je ne m\'y attendais pas.', english: 'I wasn\'t expecting that.' },
            { id: 9, french: 'Ça m\'a surpris(e).', english: 'It surprised me.' },
            { id: 10, french: 'J\'en suis ravi(e).', english: 'I\'m delighted about it.' },
            { id: 11, french: 'Je regrette de…', english: 'I regret…' },
            { id: 12, french: 'Je suis déçu(e) par…', english: 'I\'m disappointed by…' },
            { id: 13, french: 'Ça m\'a mis(e) en colère.', english: 'It made me angry.' },
            { id: 14, french: 'Je me sens mieux maintenant.', english: 'I feel better now.' },
            { id: 15, french: 'C\'était une expérience inoubliable.', english: 'It was an unforgettable experience.' },
        ],
    },
    {
        level: 'B1', unit: 2,
        id: 'expressing-disagreement',
        title: 'Expressing Disagreement',
        titleFR: 'Exprimer son désaccord',
        description: 'Disagree politely and constructively in French',
        descriptionFR: 'Exprimer son désaccord de manière polie et constructive',
        icon: '⚖️',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'Je ne suis pas d\'accord.', english: 'I don\'t agree.' },
            { id: 2, french: 'Je comprends votre point de vue, mais…', english: 'I understand your point of view, but…' },
            { id: 3, french: 'À mon avis, c\'est différent.', english: 'In my opinion, it\'s different.' },
            { id: 4, french: 'Permettez-moi de nuancer.', english: 'Allow me to add some nuance.' },
            { id: 5, french: 'Ce n\'est pas tout à fait exact.', english: 'That\'s not quite right.' },
            { id: 6, french: 'Vous avez raison sur ce point, cependant…', english: 'You\'re right on that point, however…' },
            { id: 7, french: 'D\'un autre côté…', english: 'On the other hand…' },
            { id: 8, french: 'Il faut prendre en compte que…', english: 'We need to take into account that…' },
            { id: 9, french: 'C\'est plus compliqué que ça.', english: 'It\'s more complicated than that.' },
            { id: 10, french: 'Je vois les choses autrement.', english: 'I see things differently.' },
            { id: 11, french: 'C\'est discutable.', english: 'That\'s debatable.' },
            { id: 12, french: 'En revanche…', english: 'On the other hand… / By contrast…' },
            { id: 13, french: 'Tout dépend de…', english: 'It all depends on…' },
            { id: 14, french: 'La réalité est plus nuancée.', english: 'The reality is more nuanced.' },
            { id: 15, french: 'Je maintiens ma position.', english: 'I stand by my position.' },
        ],
    },
    {
        level: 'B1', unit: 3,
        id: 'at-the-museum-event',
        title: 'At the Museum / Event',
        titleFR: 'Au musée / à un événement',
        description: 'Navigate cultural venues and events in French',
        descriptionFR: 'Se repérer dans les musées et événements culturels',
        icon: '🎨',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'Combien coûte l\'entrée ?', english: 'How much is the entry / admission?' },
            { id: 2, french: 'Y a-t-il des audioguides ?', english: 'Are there audio guides?' },
            { id: 3, french: 'À quelle heure ferme le musée ?', english: 'What time does the museum close?' },
            { id: 4, french: 'Cette œuvre date de…', english: 'This work dates from…' },
            { id: 5, french: 'Je ne connais pas cet artiste.', english: 'I don\'t know this artist.' },
            { id: 6, french: 'C\'est magnifique !', english: 'It\'s magnificent / beautiful!' },
            { id: 7, french: 'Ça me fait penser à…', english: 'It reminds me of… / It makes me think of…' },
            { id: 8, french: 'Y a-t-il une boutique ?', english: 'Is there a gift shop?' },
            { id: 9, french: 'Vous faites des visites guidées ?', english: 'Do you offer guided tours?' },
            { id: 10, french: 'Je voudrais un catalogue.', english: 'I\'d like a catalogue.' },
            { id: 11, french: 'Où se trouve l\'exposition temporaire ?', english: 'Where is the temporary exhibition?' },
            { id: 12, french: 'Il est interdit de photographier.', english: 'Photography is not allowed.' },
            { id: 13, french: 'Puis-je laisser mon manteau à la consigne ?', english: 'Can I leave my coat in the cloakroom?' },
            { id: 14, french: 'La file d\'attente est longue.', english: 'The queue is long.' },
            { id: 15, french: 'Merci pour cette visite, c\'était enrichissant.', english: 'Thank you for this visit, it was enriching.' },
        ],
    },
    {
        level: 'B1', unit: 4,
        id: 'talking-about-work',
        title: 'Talking About Work',
        titleFR: 'Parler du travail',
        description: 'Discuss your job, workplace and professional life in French',
        descriptionFR: 'Parler de son travail, de son lieu de travail et de sa vie professionnelle',
        icon: '💼',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'Je travaille dans…', english: 'I work in…' },
            { id: 2, french: 'Mon poste consiste à…', english: 'My role involves…' },
            { id: 3, french: 'J\'ai une réunion à…', english: 'I have a meeting at…' },
            { id: 4, french: 'Je suis en télétravail.', english: 'I\'m working from home.' },
            { id: 5, french: 'Mon responsable s\'appelle…', english: 'My manager\'s name is…' },
            { id: 6, french: 'On cherche quelqu\'un pour…', english: 'We\'re looking for someone to…' },
            { id: 7, french: 'Je postule à un emploi.', english: 'I\'m applying for a job.' },
            { id: 8, french: 'J\'ai passé un entretien.', english: 'I had / went for an interview.' },
            { id: 9, french: 'J\'ai été embauché(e).', english: 'I was hired / taken on.' },
            { id: 10, french: 'Je donne ma démission.', english: 'I\'m handing in my notice.' },
            { id: 11, french: 'Les horaires sont flexibles.', english: 'The hours are flexible.' },
            { id: 12, french: 'Je suis en congé.', english: 'I\'m on leave / holiday.' },
            { id: 13, french: 'On a une échéance vendredi.', english: 'We have a deadline on Friday.' },
            { id: 14, french: 'Je collabore avec…', english: 'I work / collaborate with…' },
            { id: 15, french: 'C\'est un environnement dynamique.', english: 'It\'s a dynamic environment.' },
        ],
    },
    {
        level: 'B1', unit: 5,
        id: 'health-lifestyle-phrases',
        title: 'Health & Lifestyle',
        titleFR: 'Santé & mode de vie',
        description: 'Talk about your health habits and lifestyle in French',
        descriptionFR: 'Parler de ses habitudes de santé et de son mode de vie',
        icon: '🌿',
        color: '#0891B2',
        phrases: [
            { id: 1, french: 'Je fais du sport trois fois par semaine.', english: 'I exercise three times a week.' },
            { id: 2, french: 'J\'essaie de bien manger.', english: 'I try to eat well.' },
            { id: 3, french: 'Je dors huit heures par nuit.', english: 'I sleep eight hours a night.' },
            { id: 4, french: 'Je suis stressé(e) en ce moment.', english: 'I\'m stressed at the moment.' },
            { id: 5, french: 'Ça fait du bien de se détendre.', english: 'It\'s good to relax.' },
            { id: 6, french: 'J\'ai arrêté de fumer.', english: 'I quit smoking.' },
            { id: 7, french: 'Je suis végétarien(ne).', english: 'I\'m vegetarian.' },
            { id: 8, french: 'J\'ai une intolérance au lactose.', english: 'I\'m lactose intolerant.' },
            { id: 9, french: 'Il faut faire attention à sa santé.', english: 'You have to take care of your health.' },
            { id: 10, french: 'Mon médecin m\'a conseillé de…', english: 'My doctor advised me to…' },
            { id: 11, french: 'Je pratique la méditation.', english: 'I practise meditation.' },
            { id: 12, french: 'Je me sens en pleine forme.', english: 'I feel in great shape.' },
            { id: 13, french: 'J\'ai besoin de me ressourcer.', english: 'I need to recharge / take a break.' },
            { id: 14, french: 'Le sport me libère l\'esprit.', english: 'Exercise clears my mind.' },
            { id: 15, french: 'La santé, c\'est la richesse.', english: 'Health is wealth.' },
        ],
    },
    {
        level: 'B1', unit: 4,
        id: 'customer-service',
        title: 'Customer Service & Complaints',
        titleFR: 'Service client & réclamations',
        description: 'Handle complaints, returns, and customer service interactions in French',
        descriptionFR: 'Gérer les réclamations, les retours et les interactions avec le service client',
        icon: '🛎️',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'Je voudrais faire une réclamation.', english: 'I would like to make a complaint.' },
            { id: 2, french: 'Ce produit est défectueux.', english: 'This product is defective.' },
            { id: 3, french: 'Je voudrais être remboursé(e).', english: 'I would like a refund.' },
            { id: 4, french: 'Puis-je parler au responsable ?', english: 'Can I speak to the manager?' },
            { id: 5, french: 'J\'ai perdu mon ticket de caisse.', english: 'I have lost my receipt.' },
            { id: 6, french: 'Cela ne correspond pas à ce que j\'ai commandé.', english: 'This is not what I ordered.' },
            { id: 7, french: 'Le colis n\'est jamais arrivé.', english: 'The parcel never arrived.' },
            { id: 8, french: 'Je souhaite échanger cet article.', english: 'I would like to exchange this item.' },
            { id: 9, french: 'Pouvez-vous vérifier ma commande ?', english: 'Can you check my order?' },
            { id: 10, french: 'Le service était décevant.', english: 'The service was disappointing.' },
            { id: 11, french: 'J\'attends une réponse depuis une semaine.', english: 'I have been waiting for a response for a week.' },
            { id: 12, french: 'Voici mon numéro de commande.', english: 'Here is my order number.' },
            { id: 13, french: 'Je suis très insatisfait(e) de cet achat.', english: 'I am very dissatisfied with this purchase.' },
            { id: 14, french: 'Pouvez-vous m\'envoyer un bon de retour ?', english: 'Can you send me a return label?' },
            { id: 15, french: 'Je compte déposer une plainte formelle.', english: 'I intend to make a formal complaint.' },
        ],
    },
];
