import type { PhraseCategory } from '../../../types/lectures/phrases';

export const phrasesB2: PhraseCategory[] = [
    {
        level: 'B2', unit: 3,
        id: 'work-professional',
        title: 'Professional French',
        titleFR: 'Français professionnel',
        description: 'Language for the workplace and formal contexts',
        descriptionFR: 'Vocabulaire pour le lieu de travail et les contextes formels',
        icon: '💼',
        color: '#D97706',
        phrases: [
            { id: 1, french: 'Je vous contacte au sujet de...', english: 'I\'m contacting you regarding...' },
            { id: 2, french: 'Pourriez-vous me préciser... ?', english: 'Could you clarify... for me?' },
            { id: 3, french: 'Je vous envoie le document en pièce jointe.', english: 'I\'m sending you the document as an attachment.' },
            { id: 4, french: 'Pouvons-nous fixer un rendez-vous ?', english: 'Can we schedule a meeting?' },
            { id: 5, french: 'Je suis disponible le... à partir de...', english: 'I\'m available on the... from...' },
            { id: 6, french: 'Permettez-moi de me présenter.', english: 'Allow me to introduce myself.' },
            { id: 7, french: 'Je vous prie d\'agréer mes cordiales salutations.', english: 'Yours sincerely.', note: 'Formal letter closing formula' },
            { id: 8, french: 'Nous accusons réception de votre courrier.', english: 'We acknowledge receipt of your letter.' },
            { id: 9, french: 'Dans les plus brefs délais.', english: 'As soon as possible. / At the earliest opportunity.', note: 'Formal register' },
            { id: 10, french: 'Suite à notre entretien téléphonique...', english: 'Further to our telephone conversation...' },
            { id: 11, french: 'Sous réserve de...', english: 'Subject to... / Provided that...' },
            { id: 12, french: 'Dans l\'attente de votre réponse...', english: 'Awaiting your reply... / I look forward to hearing from you...' },
            { id: 13, french: 'Nous restons à votre disposition.', english: 'We remain at your disposal. / Please don\'t hesitate to contact us.' },
            { id: 14, french: 'Je me permets de...', english: 'I take the liberty of... / I\'d like to...' },
            { id: 15, french: 'C\'est noté.', english: 'Noted. / I\'ve made a note of that.' },
        ],
    },
    {
        level: 'B2', unit: 4,
        id: 'emotions-reactions',
        title: 'Emotions & Reactions',
        titleFR: 'Émotions & Réactions',
        description: 'Express how you feel with authenticity',
        descriptionFR: 'Exprimez ce que vous ressentez avec authenticité',
        icon: '❤️',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'Ça me touche vraiment.', english: 'That really moves me. / That really touches me.' },
            { id: 2, french: 'Je suis aux anges !', english: 'I\'m over the moon! / I\'m thrilled!', note: 'Literal: I\'m among the angels' },
            { id: 3, french: 'J\'en ai assez !', english: 'I\'ve had enough! / I\'m fed up!' },
            { id: 4, french: 'Ça me fait chaud au cœur.', english: 'That warms my heart.' },
            { id: 5, french: 'Je suis à bout.', english: 'I\'m at the end of my rope. / I\'m exhausted.', note: 'Lit: I\'m at the end' },
            { id: 6, french: 'Je n\'en peux plus.', english: 'I can\'t take it anymore. / I\'m exhausted.' },
            { id: 7, french: 'Ça m\'est égal.', english: 'It\'s all the same to me. / I don\'t mind either way.' },
            { id: 8, french: 'Je suis ému(e) aux larmes.', english: 'I\'m moved to tears.' },
            { id: 9, french: 'J\'ai le cœur serré.', english: 'My heart is heavy. / I feel a pang of sadness.' },
            { id: 10, french: 'Ça m\'a laissé sans voix.', english: 'It left me speechless.' },
            { id: 11, french: 'Je suis soulagé(e).', english: 'I\'m relieved.' },
            { id: 12, french: 'Je m\'en veux.', english: 'I\'m annoyed with myself. / I feel bad about it.' },
            { id: 13, french: 'Ça me préoccupe.', english: 'It worries me. / It\'s on my mind.' },
            { id: 14, french: 'Je déborde de joie !', english: 'I\'m overflowing with joy! / I\'m bursting with happiness!' },
            { id: 15, french: 'J\'ai la pêche !', english: 'I\'m full of energy! / I\'m on top form!', note: 'Informal and very common' },
        ],
    },
    {
        level: 'B2', unit: 3,
        id: 'formal-correspondence',
        title: 'Formal Correspondence',
        titleFR: 'Correspondance formelle',
        description: 'Write professional letters and emails in formal French',
        descriptionFR: 'Rédiger des lettres et e-mails professionnels en français formel',
        icon: '✉️',
        color: '#D97706',
        phrases: [
            { id: 1, french: 'Je me permets de vous contacter au sujet de…', english: 'I am writing to you regarding…' },
            { id: 2, french: 'Suite à notre entretien du…', english: 'Further to our conversation of…' },
            { id: 3, french: 'Je vous serais reconnaissant(e) de bien vouloir…', english: 'I would be grateful if you would…' },
            { id: 4, french: 'Dans l\'attente de votre réponse…', english: 'Awaiting your reply…' },
            { id: 5, french: 'Je reste à votre entière disposition.', english: 'I remain at your complete disposal.' },
            { id: 6, french: 'Veuillez agréer l\'expression de mes salutations distinguées.', english: 'Yours faithfully / Yours sincerely (very formal close).' },
            { id: 7, french: 'En référence à votre courrier du…', english: 'With reference to your letter of…' },
            { id: 8, french: 'J\'ai l\'honneur de vous informer que…', english: 'I have the honour of informing you that…' },
            { id: 9, french: 'Dans le cadre de…', english: 'In the context of… / As part of…' },
            { id: 10, french: 'Il me semble opportun de…', english: 'It seems appropriate to…' },
            { id: 11, french: 'Je vous prie de bien vouloir excuser…', english: 'Please accept my apologies for…' },
            { id: 12, french: 'Conformément à votre demande…', english: 'In accordance with your request…' },
            { id: 13, french: 'En vous remerciant par avance…', english: 'Thanking you in advance…' },
            { id: 14, french: 'Je me tiens à votre disposition pour tout renseignement complémentaire.', english: 'I am available for any further information.' },
            { id: 15, french: 'Cordialement,', english: 'Kind regards,' },
        ],
    },
    {
        level: 'B2', unit: 2,
        id: 'debating-persuading',
        title: 'Debating & Persuading',
        titleFR: 'Débattre et convaincre',
        description: 'The language of structured argument, debate and persuasion in French',
        descriptionFR: 'Le langage de l\'argumentation structurée, du débat et de la persuasion',
        icon: '🗣️',
        color: '#D97706',
        phrases: [
            { id: 1, french: 'Je soutiens que…', english: 'I maintain / argue that…' },
            { id: 2, french: 'Les faits montrent que…', english: 'The facts show that…' },
            { id: 3, french: 'Il est indéniable que…', english: 'It is undeniable that…' },
            { id: 4, french: 'On ne peut pas nier que…', english: 'One cannot deny that…' },
            { id: 5, french: 'En effet…', english: 'Indeed… / In fact…' },
            { id: 6, french: 'D\'après les études…', english: 'According to the studies…' },
            { id: 7, french: 'L\'argument principal est que…', english: 'The main argument is that…' },
            { id: 8, french: 'Pour illustrer ce propos…', english: 'To illustrate this point…' },
            { id: 9, french: 'En guise de conclusion…', english: 'By way of conclusion…' },
            { id: 10, french: 'Il convient de souligner que…', english: 'It is worth emphasising that…' },
            { id: 11, french: 'Force est de constater que…', english: 'One is forced to note that… / It cannot be denied that…' },
            { id: 12, french: 'À titre d\'exemple…', english: 'By way of example…' },
            { id: 13, french: 'En définitive…', english: 'Ultimately… / In the final analysis…' },
            { id: 14, french: 'Qui plus est…', english: 'Furthermore… / What is more…' },
            { id: 15, french: 'Je maintiens ma position.', english: 'I stand by my position.' },
        ],
    },
    {
        level: 'B2', unit: 5,
        id: 'discussing-society',
        title: 'Discussing Society',
        titleFR: 'Parler de société',
        description: 'Talk about social issues and current affairs in sophisticated French',
        descriptionFR: 'Parler des enjeux sociaux et de l\'actualité en français soutenu',
        icon: '🏛️',
        color: '#D97706',
        phrases: [
            { id: 1, french: 'La société française est marquée par…', english: 'French society is characterised by…' },
            { id: 2, french: 'Un phénomène qui prend de l\'ampleur est…', english: 'A growing phenomenon is…' },
            { id: 3, french: 'On observe une tendance à…', english: 'There is a tendency towards…' },
            { id: 4, french: 'Il faut distinguer entre…', english: 'One must distinguish between…' },
            { id: 5, french: 'Les inégalités persistent malgré…', english: 'Inequalities persist despite…' },
            { id: 6, french: 'Un débat anime l\'opinion publique autour de…', english: 'A debate is stirring public opinion around…' },
            { id: 7, french: 'Cette évolution soulève des questions sur…', english: 'This evolution raises questions about…' },
            { id: 8, french: 'La loi prévoit que…', english: 'The law provides that…' },
            { id: 9, french: 'Le gouvernement a décidé de…', english: 'The government has decided to…' },
            { id: 10, french: 'Les associations militent pour…', english: 'Campaign groups are advocating for…' },
            { id: 11, french: 'L\'opinion publique est divisée.', english: 'Public opinion is divided.' },
            { id: 12, french: 'En France, contrairement à d\'autres pays…', english: 'In France, unlike in other countries…' },
            { id: 13, french: 'Cette question est au cœur du débat politique.', english: 'This issue is at the heart of the political debate.' },
            { id: 14, french: 'La presse francophone rapporte que…', english: 'The French-language press reports that…' },
            { id: 15, french: 'Les jeunes générations pensent que…', english: 'Younger generations think that…' },
        ],
    },
    {
        level: 'B2', unit: 5,
        id: 'formal-argumentation',
        title: 'Formal Argumentation',
        titleFR: 'Argumentation formelle',
        description: 'The language of essays, debates and intellectual discourse',
        descriptionFR: 'Le langage des dissertations, débats et discours intellectuels',
        icon: '🎓',
        color: '#1A1A2E',
        phrases: [
            { id: 1, french: 'Dans un premier temps... dans un second temps...', english: 'Firstly... secondly...', note: 'Standard essay structure marker' },
            { id: 2, french: 'Force est de constater que...', english: 'One cannot help but notice that... / It is undeniable that...' },
            { id: 3, french: 'Il convient de distinguer... de...', english: 'We must distinguish... from...' },
            { id: 4, french: 'Or, il s\'avère que...', english: 'Yet, it turns out that... / However, it appears that...' },
            { id: 5, french: 'En définitive, il ressort que...', english: 'Ultimately, what emerges is that...' },
            { id: 6, french: 'Il serait réducteur de penser que...', english: 'It would be an oversimplification to think that...' },
            { id: 7, french: 'Dans cette optique...', english: 'From this perspective... / With this in mind...' },
            { id: 8, french: 'À l\'aune de...', english: 'In the light of... / By the yardstick of...', note: 'Elevated register; very common in formal essays' },
            { id: 9, french: 'Tout porte à croire que...', english: 'Everything suggests that... / There is every reason to believe that...' },
            { id: 10, french: 'Sans aller jusqu\'à dire que...', english: 'Without going so far as to say that...' },
            { id: 11, french: 'Il n\'en demeure pas moins que...', english: 'It remains the case that... / That said, it is still true that...' },
            { id: 12, french: 'On ne saurait nier que...', english: 'One cannot deny that...', note: 'ne saurait is a formal/literary use of savoir' },
            { id: 13, french: 'Dans la mesure où...', english: 'Insofar as... / To the extent that...' },
            { id: 14, french: 'Quoi qu\'il en soit...', english: 'Be that as it may... / Whatever the case...' },
            { id: 15, french: 'En filigrane de cette analyse...', english: 'Running through this analysis... / Underlying this...', note: 'Very elevated; lit: as a watermark' },
        ],
    },
];
