import type { PhraseCategory } from '../../../types/lectures/phrases';

export const phrasesC2: PhraseCategory[] = [
    {
        level: 'C2', unit: 2,
        id: 'literary-analysis',
        title: 'Literary Analysis',
        titleFR: 'Analyse littéraire',
        description: 'Essential phrases for writing and speaking literary commentary in French',
        descriptionFR: 'Expressions essentielles pour rédiger et présenter une analyse littéraire en français',
        icon: '📚',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'Ce texte appartient au registre…', english: 'This text belongs to the… register.' },
            { id: 2, french: 'On peut identifier plusieurs niveaux de lecture.', english: 'Several levels of reading can be identified.' },
            { id: 3, french: 'L\'auteur joue sur l\'ambiguïté de…', english: 'The author plays on the ambiguity of…' },
            { id: 4, french: 'La structure du texte reflète…', english: 'The structure of the text reflects…' },
            { id: 5, french: 'Ce passage est révélateur de…', english: 'This passage is revealing of…' },
            { id: 6, french: 'Le narrateur adopte un point de vue…', english: 'The narrator adopts a… point of view.' },
            { id: 7, french: 'La polyphonie du texte permet de…', english: 'The polyphony of the text allows… to…' },
            { id: 8, french: 'On note une tension entre le dit et le non-dit.', english: 'One notes a tension between what is said and what is left unsaid.' },
            { id: 9, french: 'Cette métaphore illustre…', english: 'This metaphor illustrates…' },
            { id: 10, french: 'Le lecteur implicite est…', english: 'The implied reader is…' },
            { id: 11, french: 'L\'ironie fonctionne ici comme…', english: 'Irony operates here as…' },
            { id: 12, french: 'La clôture du texte laisse…', english: 'The closure of the text leaves…' },
            { id: 13, french: 'L\'intertextualité avec… est manifeste.', english: 'The intertextuality with… is evident.' },
            { id: 14, french: 'Ce choix stylistique produit un effet de…', english: 'This stylistic choice produces an effect of…' },
            { id: 15, french: 'L\'écriture se fait ici performative.', english: 'The writing here becomes performative.' },
        ],
    },
    {
        level: 'C2', unit: 3,
        id: 'high-register-speech',
        title: 'High-Register Speech',
        titleFR: 'Expression soutenue',
        description: 'Formal and elevated expressions for high-level discourse and academic speech',
        descriptionFR: 'Expressions formelles et élevées pour le discours de haut niveau et la communication académique',
        icon: '🎩',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'Permettez-moi d\'aborder cette question sous un angle différent.', english: 'Allow me to approach this question from a different angle.' },
            { id: 2, french: 'Je souscris pleinement à cette analyse.', english: 'I fully subscribe to this analysis.' },
            { id: 3, french: 'Il me semble opportun de souligner que…', english: 'It seems appropriate to emphasize that…' },
            { id: 4, french: 'La pertinence de cette remarque n\'échappera à personne.', english: 'The relevance of this remark will not escape anyone.' },
            { id: 5, french: 'On ne saurait trop insister sur…', english: 'One cannot emphasize… enough.' },
            { id: 6, french: 'Cette position mérite d\'être examinée avec rigueur.', english: 'This position deserves to be examined with rigour.' },
            { id: 7, french: 'Il serait vain de nier que…', english: 'It would be futile to deny that…' },
            { id: 8, french: 'Loin de moi l\'idée de…', english: 'Far be it from me to…' },
            { id: 9, french: 'Je me garderai bien de trancher.', english: 'I will take care not to pass judgment.' },
            { id: 10, french: 'À cet égard, il importe de préciser que…', english: 'In this regard, it is important to specify that…' },
            { id: 11, french: 'Le mérite de cette thèse est de…', english: 'The merit of this thesis is to…' },
            { id: 12, french: 'Je ne partage pas entièrement ce point de vue, bien que…', english: 'I do not entirely share this view, although…' },
            { id: 13, french: 'Voilà qui mérite réflexion.', english: 'That is worthy of reflection.' },
            { id: 14, french: 'Ce n\'est pas là un mince paradoxe.', english: 'That is no small paradox.' },
            { id: 15, french: 'Je ne suis pas loin de penser que…', english: 'I am not far from thinking that…' },
        ],
    },
    {
        level: 'C2', unit: 5,
        id: 'debating-at-length',
        title: 'Debating at Length',
        titleFR: 'Débattre en profondeur',
        description: 'Phrases for structuring, developing, and concluding extended arguments in formal debate and essay',
        descriptionFR: 'Expressions pour structurer, développer et conclure des arguments étendus dans le débat formel et l\'essai',
        icon: '⚖️',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'Reprenons le fil de l\'argumentation.', english: 'Let us pick up the thread of the argument.' },
            { id: 2, french: 'La démonstration est convaincante sur ce point, mais…', english: 'The demonstration is convincing on this point, but…' },
            { id: 3, french: 'On aurait pu s\'attendre à…', english: 'One might have expected…' },
            { id: 4, french: 'C\'est précisément là que le bât blesse.', english: 'That is precisely where the problem lies.' },
            { id: 5, french: 'Cette objection n\'est pas sans fondement.', english: 'This objection is not without foundation.' },
            { id: 6, french: 'Pour autant, on ne peut se satisfaire de…', english: 'Even so, one cannot be satisfied with…' },
            { id: 7, french: 'Revenons à la question initiale…', english: 'Let us return to the initial question…' },
            { id: 8, french: 'Ce point étant établi, passons à…', english: 'This point being established, let us move on to…' },
            { id: 9, french: 'La conclusion s\'impose d\'elle-même.', english: 'The conclusion speaks for itself.' },
            { id: 10, french: 'On ne saurait clore ce débat sans mentionner…', english: 'One could not close this debate without mentioning…' },
            { id: 11, french: 'Voilà une piste de réflexion féconde.', english: 'That is a fruitful line of inquiry.' },
            { id: 12, french: 'J\'ajouterai un dernier argument.', english: 'I will add a final argument.' },
            { id: 13, french: 'Pour conclure sur une note…', english: 'To conclude on a… note…' },
            { id: 14, french: 'Cette question appelle des recherches ultérieures.', english: 'This question calls for further research.' },
            { id: 15, french: 'Le débat reste ouvert.', english: 'The debate remains open.' },
        ],
    },
    {
        level: 'C2', unit: 4,
        id: 'translation-commentary',
        title: 'Translation Commentary',
        titleFR: 'Commentaire de traduction',
        description: 'Phrases for discussing translation choices, equivalences, and the limits of translatability',
        descriptionFR: 'Expressions pour commenter les choix de traduction, les équivalences et les limites de la traductibilité',
        icon: '🔄',
        color: '#DC2626',
        phrases: [
            { id: 1, french: 'Le terme français n\'a pas d\'équivalent exact en anglais.', english: 'The French term has no exact equivalent in English.' },
            { id: 2, french: 'Cette expression est intraduisible littéralement.', english: 'This expression cannot be translated literally.' },
            { id: 3, french: 'La nuance se perd dans la traduction.', english: 'The nuance is lost in translation.' },
            { id: 4, french: 'Le contexte culturel est essentiel ici.', english: 'The cultural context is essential here.' },
            { id: 5, french: 'On pourrait rendre cela par…', english: 'One could render this as…' },
            { id: 6, french: 'Une traduction plus libre donnerait…', english: 'A freer translation would give…' },
            { id: 7, french: 'Le registre original est…', english: 'The original register is…' },
            { id: 8, french: 'La connotation de ce mot est…', english: 'The connotation of this word is…' },
            { id: 9, french: 'En anglais, l\'équivalent le plus proche serait…', english: 'In English, the closest equivalent would be…' },
            { id: 10, french: 'Le jeu de mots repose sur…', english: 'The wordplay relies on…' },
            { id: 11, french: 'La traduction trahit forcément quelque chose.', english: 'Translation inevitably betrays something.' },
            { id: 12, french: 'L\'original a une cadence que la traduction ne peut capturer.', english: 'The original has a rhythm that translation cannot capture.' },
            { id: 13, french: 'Fidèle ou belle — rarement les deux.', english: 'Faithful or beautiful — rarely both.' },
            { id: 14, french: 'Cette formulation est proprement française.', english: 'This formulation is distinctively French.' },
            { id: 15, french: 'La version anglaise doit compenser par…', english: 'The English version must compensate with…' },
        ],
    },
];
