import type { GrammarLesson } from '../../../types/lectures/grammar';

export const grammarA1: GrammarLesson[] = [
    {
        unit: 2,
        id: 'en-articles',
        title: 'Les Articles en Anglais',
        level: 'A1',
        description: "A, an, the ou rien ? Maîtrisez les articles anglais et leurs différences avec le français.",
        icon: '📖',
        color: '#2563EB',
        sections: [
            {
                title: "A / An — L'article indéfini",
                explanation: "On utilise « a » devant une consonne et « an » devant une voyelle (son vocalique). Équivalent de « un/une » en français. Attention : en anglais, pas d'accord de genre !",
                examples: [
                    { french: 'a cat', english: 'un chat' },
                    { french: 'a book', english: 'un livre' },
                    { french: 'an apple', english: 'une pomme' },
                    { french: 'an umbrella', english: 'un parapluie' },
                    { french: 'an hour', english: 'une heure', note: '« h » muet → an, pas a' },
                    { french: 'a university', english: 'une université', note: '« u » se prononce « you » → a, pas an' },
                ],
            },
            {
                title: "The — L'article défini",
                explanation: "« The » est invariable — une seule forme pour le masculin, le féminin et le pluriel. On l'utilise pour désigner quelque chose de précis ou déjà mentionné.",
                examples: [
                    { french: 'the cat', english: 'le chat / la chatte' },
                    { french: 'the children', english: 'les enfants' },
                    { french: 'I saw a dog. The dog was big.', english: "J'ai vu un chien. Le chien était grand." },
                    { french: 'the Eiffel Tower', english: 'la tour Eiffel', note: 'Noms uniques → the' },
                    { french: 'the internet', english: 'internet', note: 'Institutions connues → the' },
                ],
            },
            {
                title: 'Zéro article — quand ne rien mettre',
                explanation: "Contrairement au français, l'anglais omet l'article pour les généralités, les matières scolaires, les repas et certains noms propres.",
                examples: [
                    { french: 'I love music.', english: "J'aime la musique.", note: 'Généralité → pas d\'article' },
                    { french: 'She studies history.', english: 'Elle étudie l\'histoire.', note: 'Matière scolaire → pas d\'article' },
                    { french: 'We have breakfast at 8.', english: 'Nous prenons le petit-déjeuner à 8h.', note: 'Repas → pas d\'article' },
                    { french: 'He lives in France.', english: 'Il vit en France.', note: 'Pays → pas d\'article' },
                    { french: 'I like dogs.', english: "J'aime les chiens.", note: 'Généralité au pluriel → pas d\'article' },
                ],
            },
        ],
        exercises: [
            { sentence: 'She is ___ engineer.', answer: 'an', hint: '« engineer » commence par une voyelle' },
            { sentence: 'I want ___ coffee, please.', answer: 'a', hint: '« coffee » commence par une consonne' },
            { sentence: 'Have you seen ___ keys? I left them here.', answer: 'the', hint: 'Les clés sont précises / déjà mentionnées' },
            { sentence: 'He plays ___ guitar every evening.', answer: 'the', hint: 'Instrument de musique → the' },
            { sentence: '___ sun rises in the east.', answer: 'The', hint: 'Objet unique → the' },
        ],
    },
    {
        unit: 2,
        id: 'en-present-simple',
        title: 'Le Présent Simple et Continu',
        level: 'A1',
        description: 'Quand dire « I work » et quand dire « I am working » ? La distinction clé du présent anglais.',
        icon: '⏰',
        color: '#059669',
        sections: [
            {
                title: 'Le présent simple (Present Simple)',
                explanation: "Le présent simple exprime les habitudes, les vérités générales et les états permanents. On ajoute « -s » à la 3ème personne du singulier (he/she/it). Pour les questions et négations, on utilise do/does.",
                examples: [
                    { french: 'I work every day.', english: 'Je travaille tous les jours.' },
                    { french: 'She lives in Paris.', english: 'Elle habite à Paris.' },
                    { french: 'The sun rises in the east.', english: 'Le soleil se lève à l\'est.' },
                    { french: 'Do you speak English?', english: 'Parlez-vous anglais ?' },
                    { french: 'He does not eat meat.', english: 'Il ne mange pas de viande.' },
                ],
            },
            {
                title: 'Le présent continu (Present Continuous)',
                explanation: "Le présent continu (be + verbe-ing) exprime une action en cours au moment où on parle, ou une situation temporaire. Équivalent de « être en train de... » en français.",
                examples: [
                    { french: 'I am working right now.', english: 'Je suis en train de travailler.' },
                    { french: 'She is studying for her exam.', english: 'Elle est en train de réviser pour son examen.' },
                    { french: 'They are living in London this year.', english: 'Ils habitent à Londres cette année (temporaire).' },
                    { french: 'What are you doing?', english: 'Qu\'est-ce que tu fais ?' },
                ],
            },
            {
                title: 'Les verbes d\'état (Stative Verbs)',
                explanation: "Certains verbes expriment des états et ne s'utilisent jamais au présent continu : know, understand, like, love, hate, want, need, believe, seem, own, contain...",
                examples: [
                    { french: 'I know the answer. ✓', english: 'Je connais la réponse.' },
                    { french: 'I am knowing the answer. ✗', english: 'Forme incorrecte — jamais « know » en -ing', note: 'Erreur classique des francophones' },
                    { french: 'She loves coffee.', english: 'Elle adore le café.' },
                    { french: 'He seems tired.', english: 'Il a l\'air fatigué.' },
                    { french: 'This bag contains milk.', english: 'Ce sac contient du lait.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'She ___ (work) in a hospital. She is a doctor.', answer: 'works', hint: 'Habitude / état permanent → présent simple, 3ème personne' },
            { sentence: 'Be quiet! The baby ___ (sleep) right now.', answer: 'is sleeping', hint: 'Action en cours → présent continu' },
            { sentence: '___ you ___ (like) spicy food?', answer: 'Do / like', hint: 'Verbe d\'état → présent simple, question avec Do' },
            { sentence: 'He ___ (not / eat) breakfast on weekdays.', answer: 'does not eat', hint: 'Négation au présent simple → does not + infinitif' },
        ],
    },
    {
        unit: 2,
        id: 'en-plurals-nouns',
        title: 'Le Pluriel et les Noms en Anglais',
        level: 'A1',
        description: "Comment former le pluriel, les pluriels irréguliers, et les noms qui n'ont pas de pluriel en anglais.",
        icon: '📚',
        color: '#0891B2',
        sections: [
            {
                title: 'Le pluriel régulier',
                explanation: "En anglais, le pluriel se forme généralement en ajoutant « -s » à la fin du nom. Quelques règles supplémentaires s'appliquent selon la terminaison du mot : on ajoute « -es » après -s, -sh, -ch, -x, -z ; et si le nom finit par une consonne + y, le y devient -ies. Contrairement au français, le pluriel ne change pas l'article : « the » reste « the » au singulier et au pluriel.",
                examples: [
                    { french: 'cat → cats', english: 'chat → chats' },
                    { french: 'book → books', english: 'livre → livres' },
                    { french: 'bus → buses', english: 'bus → bus' },
                    { french: 'box → boxes', english: 'boîte → boîtes' },
                    { french: 'baby → babies', english: 'bébé → bébés' },
                    { french: 'city → cities', english: 'ville → villes' },
                ],
            },
            {
                title: 'Les pluriels irréguliers',
                explanation: "Certains noms très courants ont un pluriel irrégulier qu'il faut mémoriser. Ces formes ne suivent aucune règle — elles viennent de l'ancien anglais. Attention : « person » a deux pluriels possibles (persons, mais surtout people).",
                examples: [
                    { french: 'child → children', english: 'enfant → enfants' },
                    { french: 'man → men', english: 'homme → hommes' },
                    { french: 'woman → women', english: 'femme → femmes' },
                    { french: 'tooth → teeth', english: 'dent → dents' },
                    { french: 'foot → feet', english: 'pied → pieds' },
                    { french: 'mouse → mice', english: 'souris → souris' },
                ],
            },
            {
                title: 'Les noms indénombrables (Uncountable Nouns)',
                explanation: "Certains noms anglais sont indénombrables : ils n'ont pas de pluriel et ne peuvent pas être précédés de « a/an ». En français, ces mêmes mots sont souvent dénombrables ou ont un article partitif (du, de la). Pour ces noms, on utilise « some » ou des expressions de quantité (a glass of, a piece of...).",
                examples: [
                    { french: 'water (not a water / waters)', english: 'de l\'eau' },
                    { french: 'information (not an information)', english: 'une information / des informations' },
                    { french: 'advice (not an advice)', english: 'un conseil / des conseils' },
                    { french: 'luggage (not a luggage)', english: 'un bagage / des bagages' },
                    { french: 'Can I have some water?', english: 'Puis-je avoir de l\'eau ?' },
                    { french: 'a piece of advice', english: 'un conseil' },
                ],
            },
        ],
        exercises: [
            { sentence: 'There are three ___ in the garden. (enfant)', answer: 'children', hint: 'Pluriel irrégulier de child' },
            { sentence: 'She has two ___ on her left foot. (orteil)', answer: 'toes', hint: 'Pluriel régulier : toe → toes' },
            { sentence: 'Can you give me some ___ about this job? (information)', answer: 'information', hint: 'Information est indénombrable — pas de pluriel' },
            { sentence: 'The ___ brushed their teeth twice a day. (femme)', answer: 'women', hint: 'Pluriel irrégulier de woman' },
            { sentence: 'He gave me a very useful piece of ___. (conseil)', answer: 'advice', hint: 'Advice est indénombrable : un conseil = a piece of advice' },
        ],
    },
    {
        unit: 2,
        id: 'en-questions',
        title: 'Poser des Questions en Anglais',
        level: 'A1',
        description: "Oui/non, qu'est-ce que, où, quand... Toutes les structures pour poser des questions en anglais.",
        icon: '❓',
        color: '#7C3AED',
        sections: [
            {
                title: 'Les questions oui/non',
                explanation: "Pour poser une question oui/non en anglais, on inverse l'ordre sujet–verbe. Avec les verbes be et have, on déplace le verbe devant le sujet. Avec les autres verbes, on ajoute l'auxiliaire do/does (présent) ou did (passé). En français, on peut ajouter « est-ce que » — en anglais, on utilise toujours l'inversion.",
                examples: [
                    { french: 'Are you a student?', english: 'Es-tu étudiant(e) ?' },
                    { french: 'Is she at home?', english: 'Est-elle à la maison ?' },
                    { french: 'Do you speak English?', english: 'Parlez-vous anglais ?' },
                    { french: 'Does he work here?', english: 'Est-ce qu\'il travaille ici ?' },
                    { french: 'Have you got a pen?', english: 'Avez-vous un stylo ?' },
                ],
            },
            {
                title: 'Les questions avec un mot interrogatif (Wh- questions)',
                explanation: "Les mots interrogatifs (what, where, when, who, why, how) se placent toujours EN DÉBUT de question, avant l'auxiliaire. C'est l'ordre inverse du français, où le mot interrogatif peut parfois rester en fin de phrase.",
                examples: [
                    { french: 'What is your name?', english: 'Comment vous appelez-vous ?' },
                    { french: 'Where do you live?', english: 'Où habitez-vous ?' },
                    { french: 'When does the train leave?', english: 'Quand le train part-il ?' },
                    { french: 'Who is that man?', english: 'Qui est cet homme ?' },
                    { french: 'Why are you laughing?', english: 'Pourquoi riez-vous ?' },
                    { french: 'How do you go to work?', english: 'Comment allez-vous au travail ?' },
                ],
            },
            {
                title: 'Les réponses courtes',
                explanation: "En anglais, on ne répond pas seulement par « yes » ou « no » — on répète l'auxiliaire de la question. Ces réponses courtes sonnent naturelles et polies. Ne jamais répondre uniquement « Yes » sans l'auxiliaire dans un registre soigné.",
                examples: [
                    { french: 'Do you like coffee? — Yes, I do. / No, I don\'t.', english: 'Est-ce que vous aimez le café ? — Oui. / Non.' },
                    { french: 'Is she coming? — Yes, she is. / No, she isn\'t.', english: 'Est-ce qu\'elle vient ? — Oui. / Non.' },
                    { french: 'Does he work here? — Yes, he does. / No, he doesn\'t.', english: 'Est-ce qu\'il travaille ici ? — Oui. / Non.' },
                    { french: 'Have you finished? — Yes, I have. / No, I haven\'t.', english: 'Avez-vous terminé ? — Oui. / Non.' },
                ],
            },
        ],
        exercises: [
            { sentence: '___ she from Italy? (is/are/do)', answer: 'Is', hint: 'Question avec be → inversion : Is + sujet' },
            { sentence: '___ do you live? (where/what/who)', answer: 'Where', hint: 'On demande un lieu → where' },
            { sentence: 'Does he play football? — Yes, he ___. (réponse courte)', answer: 'does', hint: 'Réponse courte avec does → Yes, he does' },
            { sentence: '___ time does the film start?', answer: 'What', hint: 'On demande l\'heure → What time' },
            { sentence: '___ are you tired? (explication)', answer: 'Why', hint: 'On demande une raison → why' },
        ],
    },
    {
        unit: 2,
        id: 'en-negation',
        title: 'La Négation en Anglais',
        level: 'A1',
        description: "Don't, isn't, never... Comment former les phrases négatives en anglais, sans faire de double négation.",
        icon: '🚫',
        color: '#DC2626',
        sections: [
            {
                title: "Don't / Doesn't + infinitif",
                explanation: "Pour nier un verbe ordinaire au présent, on utilise don't (do not) avec je/tu/nous/vous/ils et doesn't (does not) avec il/elle. L'auxiliaire porte la négation — le verbe principal reste à l'infinitif sans « to ». C'est une différence importante avec le français, qui ajoute ne...pas autour du verbe.",
                examples: [
                    { french: 'I don\'t eat meat.', english: 'Je ne mange pas de viande.' },
                    { french: 'She doesn\'t live here.', english: 'Elle n\'habite pas ici.' },
                    { french: 'They don\'t understand.', english: 'Ils ne comprennent pas.' },
                    { french: 'He doesn\'t want to come.', english: 'Il ne veut pas venir.' },
                ],
            },
            {
                title: "Am not / Isn't / Aren't",
                explanation: "Pour nier le verbe « be », on ajoute simplement « not » après le verbe. Pas besoin de do/does ! Les formes contractées sont très courantes à l'oral. Notez que « I am not » ne se contracte pas en « amn't » — on dit « I'm not ».",
                examples: [
                    { french: 'I am not ready.', english: 'Je ne suis pas prêt(e).' },
                    { french: 'She isn\'t at school today.', english: "Elle n'est pas à l'école aujourd'hui." },
                    { french: 'We aren\'t sure.', english: 'Nous ne sommes pas sûrs.' },
                    { french: 'It isn\'t cold outside.', english: 'Il ne fait pas froid dehors.' },
                ],
            },
            {
                title: 'Never, nothing, nobody — pas de double négation !',
                explanation: "En anglais, il est INTERDIT de faire une double négation comme en français populaire (« je ne vois personne »). En anglais, on choisit soit la forme négative du verbe + something/anyone/ever, soit le verbe affirmatif + nothing/nobody/never. Les deux ensemble donnent une affirmation, pas une négation renforcée.",
                examples: [
                    { french: 'I never eat fast food.', english: 'Je ne mange jamais de fast-food.' },
                    { french: 'Nobody came to the party.', english: 'Personne n\'est venu à la fête.' },
                    { french: 'There is nothing in the box.', english: "Il n'y a rien dans la boîte." },
                    { french: 'She doesn\'t know anyone here.', english: 'Elle ne connaît personne ici.' },
                    { french: 'I don\'t have anything. = I have nothing.', english: 'Je n\'ai rien.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'He ___ (not/like) spicy food.', answer: "doesn't like", hint: '3ème personne du singulier → doesn\'t + infinitif' },
            { sentence: 'I ___ (not/be) hungry right now.', answer: "am not", hint: 'Négation de be → am not (pas de contraction amn\'t)' },
            { sentence: 'There is ___ in the fridge. (rien)', answer: 'nothing', hint: 'Rien = nothing — pas de double négation avec isn\'t' },
            { sentence: 'They ___ come to class on Fridays.', answer: "don't", hint: 'Pluriel → don\'t + infinitif' },
            { sentence: 'She ___ visited Japan. (jamais)', answer: 'has never', hint: 'Never se place entre l\'auxiliaire et le participe' },
        ],
    },
    {
        unit: 2,
        id: 'en-can-modals',
        title: 'Can, Could, May et Might',
        level: 'A1',
        description: "Can, can't, could, may... Les premiers verbes modaux pour exprimer la capacité, l'autorisation et la possibilité.",
        icon: '💪',
        color: '#059669',
        sections: [
            {
                title: 'Can — capacité et possibilité',
                explanation: "Can exprime la capacité (savoir faire quelque chose) et la possibilité. Il se place avant l'infinitif sans « to » et ne prend jamais de -s à la 3ème personne. C'est l'équivalent de « pouvoir » ou « savoir » en français. Can't (cannot) exprime l'impossibilité ou l'interdiction.",
                examples: [
                    { french: 'I can swim.', english: 'Je sais nager.' },
                    { french: 'She can speak three languages.', english: 'Elle parle trois langues.' },
                    { french: 'Can you help me?', english: 'Pouvez-vous m\'aider ?' },
                    { french: 'I can\'t find my keys.', english: 'Je ne trouve pas mes clés.' },
                    { french: 'You can\'t park here.', english: 'Vous ne pouvez pas vous garer ici.' },
                ],
            },
            {
                title: 'Could — passé et politesse',
                explanation: "Could est le passé de can. Il s'utilise pour parler de capacités passées, mais aussi pour faire des demandes plus polies que can. Pour des demandes au passé ou hypothétiques, could est préférable à can dans un registre soigné.",
                examples: [
                    { french: 'When I was young, I could run fast.', english: 'Quand j\'étais jeune, je pouvais courir vite.' },
                    { french: 'Could you open the window, please?', english: 'Pourriez-vous ouvrir la fenêtre, s\'il vous plaît ?' },
                    { french: 'I couldn\'t understand what he said.', english: 'Je n\'arrivais pas à comprendre ce qu\'il disait.' },
                    { french: 'Could I use your phone?', english: 'Puis-je utiliser votre téléphone ?' },
                ],
            },
            {
                title: 'May et Might — permission et possibilité',
                explanation: "May exprime la permission formelle ou une possibilité assez probable. Might exprime une possibilité plus incertaine ou hypothétique. En français, « may » correspond souvent à « avoir la permission de » ou « il est possible que ». Might équivaut à « il se pourrait que ».",
                examples: [
                    { french: 'May I sit here?', english: 'Puis-je m\'asseoir ici ?' },
                    { french: 'It may rain this afternoon.', english: 'Il se peut qu\'il pleuve cet après-midi.' },
                    { french: 'She might be late — I\'m not sure.', english: 'Elle est peut-être en retard — je ne suis pas sûr.' },
                    { french: 'You may leave now.', english: 'Vous pouvez partir maintenant.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'She ___ play the piano very well.', answer: 'can', hint: 'Capacité → can + infinitif sans to' },
            { sentence: '___ you pass me the salt, please?', answer: 'Could', hint: 'Demande polie → Could (plus formel que Can)' },
            { sentence: 'You ___ smoke in here. (interdit)', answer: "can't", hint: 'Interdiction → can\'t' },
            { sentence: 'It ___ snow tonight — the sky looks heavy.', answer: 'might', hint: 'Possibilité incertaine → might' },
            { sentence: '___ I open the window? It\'s very warm.', answer: 'May', hint: 'Demande de permission formelle → May' },
        ],
    },
];
