import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

export const modulesA1: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'A1', unit: 1, id: 'a1-bonjour-je-mappelle-marie', title: 'Reading Vocabulary: Bonjour, je m’appelle Marie', titleFR: 'Vocabulaire de lecture : Bonjour, je m’appelle Marie', description: 'Words from Bonjour, je m’appelle Marie', descriptionFR: 'Vocabulaire du texte Bonjour, je m’appelle Marie', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to be called / named', french: 's\'appeler' },
        { id: 2, english: 'French (nationality)', french: 'français / française' },
        { id: 3, english: 'to live', french: 'habiter' },
        { id: 4, english: 'the south', french: 'le sud' },
        { id: 5, english: 'to work', french: 'travailler' },
        { id: 6, english: 'a travel agency', french: 'une agence de voyages' },
        { id: 7, english: 'to speak', french: 'parler' },
        { id: 8, english: 'to learn', french: 'apprendre' },
        { id: 9, english: 'languages', french: 'les langues' },
        { id: 10, english: 'travel / trips', french: 'les voyages' },
        { id: 11, english: 'music', french: 'la musique' },
        { id: 12, english: 'the weekend', french: 'le week-end' },
        { id: 13, english: 'to go to the cinema', french: 'aller au cinéma' },
        { id: 14, english: 'to drink a coffee', french: 'boire un café' },
        { id: 15, english: 'once a month', french: 'une fois par mois' },
    ] },
    { level: 'A1', unit: 1, id: 'a1-une-nouvelle-collegue', title: 'Reading Vocabulary: Une Nouvelle Collègue', titleFR: 'Vocabulaire de lecture : Une Nouvelle Collègue', description: 'Words from Une Nouvelle Collègue', descriptionFR: 'Vocabulaire du texte Une Nouvelle Collègue', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'a colleague', french: 'un / une collègue' },
        { id: 2, english: 'new', french: 'nouveau / nouvelle' },
        { id: 3, english: 'the office', french: 'le bureau' },
        { id: 4, english: 'the first day', french: 'le premier jour' },
        { id: 5, english: 'to come towards', french: 'venir vers' },
        { id: 6, english: 'to smile', french: 'sourire' },
        { id: 7, english: 'welcome!', french: 'bienvenue !' },
        { id: 8, english: 'nice to meet you', french: 'enchanté / enchantée' },
        { id: 9, english: 'the company', french: 'l\'entreprise' },
        { id: 10, english: 'to show', french: 'montrer' },
        { id: 11, english: 'to introduce', french: 'présenter' },
        { id: 12, english: 'the team', french: 'l\'équipe' },
        { id: 13, english: 'at noon', french: 'à midi' },
        { id: 14, english: 'to suggest / propose', french: 'proposer' },
        { id: 15, english: 'to have lunch', french: 'déjeuner' },
    ] },
    { level: 'A1', unit: 1, id: 'a1-mon-ami-thomas', title: 'Reading Vocabulary: Mon Ami Thomas', titleFR: 'Vocabulaire de lecture : Mon Ami Thomas', description: 'Words from Mon Ami Thomas', descriptionFR: 'Vocabulaire du texte Mon Ami Thomas', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'a friend', french: 'un ami' },
        { id: 2, english: 'tall', french: 'grand' },
        { id: 3, english: 'brown hair', french: 'les cheveux bruns' },
        { id: 4, english: 'brown eyes', french: 'les yeux marron' },
        { id: 5, english: 'calm', french: 'calme' },
        { id: 6, english: 'funny', french: 'drôle' },
        { id: 7, english: 'a bookshop', french: 'une librairie' },
        { id: 8, english: 'the city centre', french: 'le centre-ville' },
        { id: 9, english: 'a book', french: 'un livre' },
        { id: 10, english: 'to read', french: 'lire' },
        { id: 11, english: 'to cook', french: 'cuisiner' },
        { id: 12, english: 'to ride a bike', french: 'faire du vélo' },
        { id: 13, english: 'to listen to music', french: 'écouter de la musique' },
        { id: 14, english: 'often', french: 'souvent' },
        { id: 15, english: 'to have a good time', french: 'passer un bon moment' },
    ] },
    { level: 'A1', unit: 1, id: 'a1-la-famille-martin', title: 'Reading Vocabulary: La Famille Martin', titleFR: 'Vocabulaire de lecture : La Famille Martin', description: 'Words from La Famille Martin', descriptionFR: 'Vocabulaire du texte La Famille Martin', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the husband', french: 'le mari' },
        { id: 2, english: 'a doctor', french: 'un médecin' },
        { id: 3, english: 'the hospital', french: 'l\'hôpital' },
        { id: 4, english: 'kind / nice', french: 'gentil' },
        { id: 5, english: 'the children', french: 'les enfants' },
        { id: 6, english: 'the son', french: 'le fils' },
        { id: 7, english: 'the daughter', french: 'la fille' },
        { id: 8, english: 'to draw', french: 'dessiner' },
        { id: 9, english: 'to sing', french: 'chanter' },
        { id: 10, english: 'the flat / apartment', french: 'l\'appartement' },
        { id: 11, english: 'comfortable', french: 'confortable' },
        { id: 12, english: 'the bedrooms', french: 'les chambres' },
        { id: 13, english: 'the living room', french: 'le salon' },
        { id: 14, english: 'a garden', french: 'un jardin' },
        { id: 15, english: 'a walk / stroll', french: 'une promenade' },
    ] },
    { level: 'A1', unit: 2, id: 'a1-une-journee-typique', title: 'Reading Vocabulary: Une Journée Typique', titleFR: 'Vocabulaire de lecture : Une Journée Typique', description: 'Words from Une Journée Typique', descriptionFR: 'Vocabulaire du texte Une Journée Typique', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the secondary school (ages 11–15)', french: 'le collège' },
        { id: 2, english: 'to get up', french: 'se lever' },
        { id: 3, english: 'to take a shower', french: 'prendre une douche' },
        { id: 4, english: 'to get dressed', french: 's\'habiller' },
        { id: 5, english: 'breakfast', french: 'le petit-déjeuner' },
        { id: 6, english: 'the bread', french: 'le pain' },
        { id: 7, english: 'the butter', french: 'le beurre' },
        { id: 8, english: 'orange juice', french: 'le jus d\'orange' },
        { id: 9, english: 'the bus', french: 'le bus' },
        { id: 10, english: 'the classes / lessons', french: 'les cours' },
        { id: 11, english: 'the school canteen', french: 'la cantine' },
        { id: 12, english: 'the afternoon', french: 'l\'après-midi' },
        { id: 13, english: 'to come / go back home', french: 'rentrer' },
        { id: 14, english: 'homework', french: 'les devoirs' },
        { id: 15, english: 'to go to bed', french: 'se coucher' },
    ] },
    { level: 'A1', unit: 2, id: 'a1-le-samedi-de-sophie', title: 'Reading Vocabulary: Le Samedi de Sophie', titleFR: 'Vocabulaire de lecture : Le Samedi de Sophie', description: 'Words from Le Samedi de Sophie', descriptionFR: 'Vocabulaire du texte Le Samedi de Sophie', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'Saturday', french: 'le samedi' },
        { id: 2, english: 'to get up', french: 'se lever' },
        { id: 3, english: 'around / approximately', french: 'vers' },
        { id: 4, english: 'quietly / leisurely', french: 'tranquillement' },
        { id: 5, english: 'jam', french: 'la confiture' },
        { id: 6, english: 'in the morning', french: 'le matin' },
        { id: 7, english: 'to do some shopping', french: 'faire des courses' },
        { id: 8, english: 'the neighbourhood', french: 'le quartier' },
        { id: 9, english: 'to prepare', french: 'préparer' },
        { id: 10, english: 'lunch', french: 'le déjeuner' },
        { id: 11, english: 'to meet / meet up with', french: 'retrouver' },
        { id: 12, english: 'in town', french: 'en ville' },
        { id: 13, english: 'to stay', french: 'rester' },
        { id: 14, english: 'to watch a film', french: 'regarder un film' },
        { id: 15, english: 'pleasant', french: 'agréable' },
    ] },
    { level: 'A1', unit: 2, id: 'a1-une-journee-au-travail', title: 'Reading Vocabulary: Une Journée au Travail', titleFR: 'Vocabulaire de lecture : Une Journée au Travail', description: 'Words from Une Journée au Travail', descriptionFR: 'Vocabulaire du texte Une Journée au Travail', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'a hotel', french: 'un hôtel' },
        { id: 2, english: 'to start', french: 'commencer' },
        { id: 3, english: 'to arrive', french: 'arriver' },
        { id: 4, english: 'a computer', french: 'un ordinateur' },
        { id: 5, english: 'a reservation / booking', french: 'une réservation' },
        { id: 6, english: 'to welcome', french: 'accueillir' },
        { id: 7, english: 'a customer / guest', french: 'un client' },
        { id: 8, english: 'to answer', french: 'répondre' },
        { id: 9, english: 'the telephone', french: 'le téléphone' },
        { id: 10, english: 'to give information', french: 'donner des informations' },
        { id: 11, english: 'the city', french: 'la ville' },
        { id: 12, english: 'a tourist', french: 'un touriste' },
        { id: 13, english: 'to have lunch', french: 'déjeuner' },
        { id: 14, english: 'to finish', french: 'terminer' },
        { id: 15, english: 'the tram', french: 'le tramway' },
    ] },
    { level: 'A1', unit: 2, id: 'a1-apres-le-travail', title: 'Reading Vocabulary: Après le Travail', titleFR: 'Vocabulaire de lecture : Après le Travail', description: 'Words from Après le Travail', descriptionFR: 'Vocabulaire du texte Après le Travail', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'after work', french: 'après le travail' },
        { id: 2, english: 'to leave', french: 'quitter' },
        { id: 3, english: 'to meet up with', french: 'retrouver' },
        { id: 4, english: 'a metro station', french: 'une station de métro' },
        { id: 5, english: 'both', french: 'tous les deux / toutes les deux' },
        { id: 6, english: 'to have a drink', french: 'prendre un verre' },
        { id: 7, english: 'to accept', french: 'accepter' },
        { id: 8, english: 'to talk about', french: 'parler de' },
        { id: 9, english: 'the day', french: 'la journée' },
        { id: 10, english: 'to order', french: 'commander' },
        { id: 11, english: 'tea', french: 'le thé' },
        { id: 12, english: 'fruit juice', french: 'le jus de fruit' },
        { id: 13, english: 'to say goodbye', french: 'se dire au revoir' },
        { id: 14, english: 'dinner', french: 'le dîner' },
        { id: 15, english: 'before', french: 'avant' },
    ] },
    { level: 'A1', unit: 3, id: 'a1-mon-appartement', title: 'Reading Vocabulary: Mon Appartement', titleFR: 'Vocabulaire de lecture : Mon Appartement', description: 'Words from Mon Appartement', descriptionFR: 'Vocabulaire du texte Mon Appartement', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'an apartment / flat', french: 'un appartement' },
        { id: 2, english: 'bright', french: 'lumineux / lumineuse' },
        { id: 3, english: 'comfortable', french: 'confortable' },
        { id: 4, english: 'a living room', french: 'un salon' },
        { id: 5, english: 'a bedroom', french: 'une chambre' },
        { id: 6, english: 'a kitchen', french: 'une cuisine' },
        { id: 7, english: 'a bathroom', french: 'une salle de bain' },
        { id: 8, english: 'a sofa', french: 'un canapé' },
        { id: 9, english: 'a table', french: 'une table' },
        { id: 10, english: 'a bookcase', french: 'une bibliothèque' },
        { id: 11, english: 'a room', french: 'une pièce' },
        { id: 12, english: 'a window', french: 'une fenêtre' },
        { id: 13, english: 'next to', french: 'à côté de' },
        { id: 14, english: 'to cook', french: 'cuisiner' },
        { id: 15, english: 'to feel good / comfortable', french: 'se sentir bien' },
    ] },
    { level: 'A1', unit: 3, id: 'a1-chez-mes-parents', title: 'Reading Vocabulary: Chez Mes Parents', titleFR: 'Vocabulaire de lecture : Chez Mes Parents', description: 'Words from Chez Mes Parents', descriptionFR: 'Vocabulaire du texte Chez Mes Parents', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'my parents\' house / at my parents\'', french: 'chez mes parents' },
        { id: 2, english: 'a house', french: 'une maison' },
        { id: 3, english: 'near', french: 'près de' },
        { id: 4, english: 'twice a month', french: 'deux fois par mois' },
        { id: 5, english: 'a street', french: 'une rue' },
        { id: 6, english: 'quiet', french: 'calme' },
        { id: 7, english: 'a tree', french: 'un arbre' },
        { id: 8, english: 'the ground floor', french: 'le rez-de-chaussée' },
        { id: 9, english: 'a dining room', french: 'une salle à manger' },
        { id: 10, english: 'upstairs', french: 'à l\'étage' },
        { id: 11, english: 'behind', french: 'derrière' },
        { id: 12, english: 'a garden', french: 'un jardin' },
        { id: 13, english: 'a terrace', french: 'une terrasse' },
        { id: 14, english: 'when', french: 'quand' },
        { id: 15, english: 'the weather is nice', french: 'il fait beau' },
    ] },
    { level: 'A1', unit: 3, id: 'a1-mon-quartier', title: 'Reading Vocabulary: Mon Quartier', titleFR: 'Vocabulaire de lecture : Mon Quartier', description: 'Words from Mon Quartier', descriptionFR: 'Vocabulaire du texte Mon Quartier', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the neighbourhood', french: 'le quartier' },
        { id: 2, english: 'lively / busy', french: 'animé' },
        { id: 3, english: 'the city centre', french: 'le centre-ville' },
        { id: 4, english: 'a shop', french: 'un magasin' },
        { id: 5, english: 'a restaurant', french: 'un restaurant' },
        { id: 6, english: 'an apartment building', french: 'un immeuble' },
        { id: 7, english: 'a bakery', french: 'une boulangerie' },
        { id: 8, english: 'opposite / across from', french: 'en face de' },
        { id: 9, english: 'a pharmacy', french: 'une pharmacie' },
        { id: 10, english: 'a supermarket', french: 'un supermarché' },
        { id: 11, english: 'on foot', french: 'à pied' },
        { id: 12, english: 'at the end of the street', french: 'au bout de la rue' },
        { id: 13, english: 'a park', french: 'un parc' },
        { id: 14, english: 'practical / convenient', french: 'pratique' },
        { id: 15, english: 'pleasant', french: 'agréable' },
    ] },
    { level: 'A1', unit: 3, id: 'a1-une-promenade-dans-le-quartier', title: 'Reading Vocabulary: Une Promenade dans le Quartier', titleFR: 'Vocabulaire de lecture : Une Promenade dans le Quartier', description: 'Words from Une Promenade dans le Quartier', descriptionFR: 'Vocabulaire du texte Une Promenade dans le Quartier', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to visit someone', french: 'rendre visite à' },
        { id: 2, english: 'to know', french: 'connaître' },
        { id: 3, english: 'after lunch', french: 'après le déjeuner' },
        { id: 4, english: 'to suggest', french: 'proposer' },
        { id: 5, english: 'a walk', french: 'une promenade' },
        { id: 6, english: 'to go out / leave', french: 'sortir' },
        { id: 7, english: 'to turn right', french: 'tourner à droite' },
        { id: 8, english: 'the post office', french: 'la poste' },
        { id: 9, english: 'favourite', french: 'préféré' },
        { id: 10, english: 'a little further', french: 'un peu plus loin' },
        { id: 11, english: 'a square', french: 'une place' },
        { id: 12, english: 'a fountain', french: 'une fontaine' },
        { id: 13, english: 'to continue', french: 'continuer' },
        { id: 14, english: 'to walk a dog', french: 'promener son chien' },
        { id: 15, english: 'to find / consider', french: 'trouver' },
    ] },
    { level: 'A1', unit: 4, id: 'a1-au-cafe', title: 'Reading Vocabulary: Au Café de la Paix', titleFR: 'Vocabulaire de lecture : Au Café de la Paix', description: 'Words from Au Café de la Paix', descriptionFR: 'Vocabulaire du texte Au Café de la Paix', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the waiter / server', french: 'le serveur' },
        { id: 2, english: 'free / available', french: 'libre' },
        { id: 3, english: 'the window', french: 'la fenêtre' },
        { id: 4, english: 'to want / wish (politely)', french: 'désirer' },
        { id: 5, english: 'I would like', french: 'je voudrais' },
        { id: 6, english: 'a coffee with milk', french: 'un café au lait' },
        { id: 7, english: 'a hot chocolate', french: 'un chocolat chaud' },
        { id: 8, english: 'the drinks / beverages', french: 'les boissons' },
        { id: 9, english: 'to taste / try', french: 'goûter' },
        { id: 10, english: 'delicious', french: 'délicieux' },
        { id: 11, english: 'of course', french: 'bien sûr' },
        { id: 12, english: 'outside', french: 'dehors' },
        { id: 13, english: 'the neighbourhood', french: 'le quartier' },
        { id: 14, english: 'the bill', french: 'l\'addition' },
        { id: 15, english: 'service included', french: 'service compris' },
    ] },
    { level: 'A1', unit: 4, id: 'a1-au-marche', title: 'Reading Vocabulary: Au Marché', titleFR: 'Vocabulaire de lecture : Au Marché', description: 'Words from Au Marché', descriptionFR: 'Vocabulaire du texte Au Marché', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the market', french: 'le marché' },
        { id: 2, english: 'vegetables', french: 'les légumes' },
        { id: 3, english: 'fruit', french: 'les fruits' },
        { id: 4, english: 'cheeses', french: 'les fromages' },
        { id: 5, english: 'the merchant / stallholder', french: 'le marchand' },
        { id: 6, english: 'tomatoes', french: 'des tomates' },
        { id: 7, english: 'How much is it?', french: 'C\'est combien ?' },
        { id: 8, english: 'a kilo', french: 'un kilo' },
        { id: 9, english: 'carrots', french: 'les carottes' },
        { id: 10, english: 'to give back / return', french: 'rendre' },
        { id: 11, english: 'change (money)', french: 'la monnaie' },
        { id: 12, english: 'have a good day', french: 'bonne journée' },
        { id: 13, english: 'to buy', french: 'acheter' },
        { id: 14, english: 'apples', french: 'des pommes' },
        { id: 15, english: 'to love / adore', french: 'adorer' },
    ] },
    { level: 'A1', unit: 4, id: 'a1-a-la-boulangerie', title: 'Reading Vocabulary: À la Boulangerie', titleFR: 'Vocabulaire de lecture : À la Boulangerie', description: 'Words from À la Boulangerie', descriptionFR: 'Vocabulaire du texte À la Boulangerie', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the bakery', french: 'la boulangerie' },
        { id: 2, english: 'near his home', french: 'près de chez lui' },
        { id: 3, english: 'already', french: 'déjà' },
        { id: 4, english: 'in front of', french: 'devant' },
        { id: 5, english: 'one\'s turn', french: 'son tour' },
        { id: 6, english: 'the baker (female)', french: 'la boulangère' },
        { id: 7, english: 'What would you like?', french: 'Qu\'est-ce que vous désirez ?' },
        { id: 8, english: 'a baguette', french: 'une baguette' },
        { id: 9, english: 'a croissant', french: 'un croissant' },
        { id: 10, english: 'please', french: 's\'il vous plaît' },
        { id: 11, english: 'that will be...', french: 'ce sera...' },
        { id: 12, english: 'to pay', french: 'payer' },
        { id: 13, english: 'a bag', french: 'un sac' },
        { id: 14, english: 'have a good day', french: 'bonne journée' },
        { id: 15, english: 'you too', french: 'à vous aussi' },
    ] },
    { level: 'A1', unit: 4, id: 'a1-au-restaurant', title: 'Reading Vocabulary: Au Restaurant', titleFR: 'Vocabulaire de lecture : Au Restaurant', description: 'Words from Au Restaurant', descriptionFR: 'Vocabulaire du texte Au Restaurant', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to have dinner', french: 'dîner' },
        { id: 2, english: 'a restaurant', french: 'un restaurant' },
        { id: 3, english: 'the menu', french: 'la carte' },
        { id: 4, english: 'a dish / meal', french: 'un plat' },
        { id: 5, english: 'a drink', french: 'une boisson' },
        { id: 6, english: 'a salad', french: 'une salade' },
        { id: 7, english: 'chicken', french: 'le poulet' },
        { id: 8, english: 'to choose', french: 'choisir' },
        { id: 9, english: 'fish', french: 'le poisson' },
        { id: 10, english: 'rice', french: 'le riz' },
        { id: 11, english: 'a bottle of water', french: 'une bouteille d\'eau' },
        { id: 12, english: 'after the meal', french: 'après le repas' },
        { id: 13, english: 'a dessert', french: 'un dessert' },
        { id: 14, english: 'ice cream', french: 'une glace' },
        { id: 15, english: 'to ask for the bill', french: 'demander l\'addition' },
    ] },
    { level: 'A1', unit: 5, id: 'a1-jaime-le-sport', title: 'Reading Vocabulary: J’aime le Sport', titleFR: 'Vocabulaire de lecture : J’aime le Sport', description: 'Words from J’aime le Sport', descriptionFR: 'Vocabulaire du texte J’aime le Sport', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'sport', french: 'le sport' },
        { id: 2, english: 'to play football', french: 'jouer au football' },
        { id: 3, english: 'Wednesday', french: 'le mercredi' },
        { id: 4, english: 'to go running', french: 'aller courir' },
        { id: 5, english: 'Sunday morning', french: 'le dimanche matin' },
        { id: 6, english: 'to prefer', french: 'préférer' },
        { id: 7, english: 'swimming', french: 'la natation' },
        { id: 8, english: 'the swimming pool', french: 'la piscine' },
        { id: 9, english: 'twice a week', french: 'deux fois par semaine' },
        { id: 10, english: 'rugby', french: 'le rugby' },
        { id: 11, english: 'television', french: 'la télévision' },
        { id: 12, english: 'in summer', french: 'en été' },
        { id: 13, english: 'to ride a bike', french: 'faire du vélo' },
        { id: 14, english: 'together', french: 'ensemble' },
        { id: 15, english: 'to spend time', french: 'passer du temps' },
    ] },
    { level: 'A1', unit: 5, id: 'a1-on-va-au-cinema', title: 'Reading Vocabulary: On Va au Cinéma ?', titleFR: 'Vocabulaire de lecture : On Va au Cinéma ?', description: 'Words from On Va au Cinéma ?', descriptionFR: 'Vocabulaire du texte On Va au Cinéma ?', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'Friday afternoon', french: 'vendredi après-midi' },
        { id: 2, english: 'to send', french: 'envoyer' },
        { id: 3, english: 'a message', french: 'un message' },
        { id: 4, english: 'What are you doing?', french: 'Tu fais quoi ?' },
        { id: 5, english: 'this evening / tonight', french: 'ce soir' },
        { id: 6, english: 'a film', french: 'un film' },
        { id: 7, english: 'the cinema', french: 'le cinéma' },
        { id: 8, english: 'Do you want to come?', french: 'Tu veux venir ?' },
        { id: 9, english: 'good idea!', french: 'bonne idée !' },
        { id: 10, english: 'to begin / start', french: 'commencer' },
        { id: 11, english: 'what time?', french: 'à quelle heure ?' },
        { id: 12, english: 'the times / schedule', french: 'les horaires' },
        { id: 13, english: 'a showing / screening', french: 'une séance' },
        { id: 14, english: 'to decide', french: 'décider' },
        { id: 15, english: 'to meet', french: 'se retrouver' },
    ] },
    { level: 'A1', unit: 5, id: 'a1-une-soiree-entre-amis', title: 'Reading Vocabulary: Une Soirée Entre Amis', titleFR: 'Vocabulaire de lecture : Une Soirée Entre Amis', description: 'Words from Une Soirée Entre Amis', descriptionFR: 'Vocabulaire du texte Une Soirée Entre Amis', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'an evening', french: 'une soirée' },
        { id: 2, english: 'to invite', french: 'inviter' },
        { id: 3, english: 'to arrive', french: 'arriver' },
        { id: 4, english: 'to bring', french: 'apporter' },
        { id: 5, english: 'drinks', french: 'des boissons' },
        { id: 6, english: 'a chocolate cake', french: 'un gâteau au chocolat' },
        { id: 7, english: 'a pizza', french: 'une pizza' },
        { id: 8, english: 'everyone', french: 'tout le monde' },
        { id: 9, english: 'to talk about', french: 'parler de' },
        { id: 10, english: 'holidays / vacation', french: 'les vacances' },
        { id: 11, english: 'a plan / project', french: 'un projet' },
        { id: 12, english: 'after dinner', french: 'après le dîner' },
        { id: 13, english: 'to play a game', french: 'jouer à un jeu' },
        { id: 14, english: 'to end', french: 'se terminer' },
        { id: 15, english: 'tired', french: 'fatigué / fatiguée' },
    ] },
    { level: 'A1', unit: 5, id: 'a1-tu-viens-samedi', title: 'Reading Vocabulary: Tu Viens Samedi ?', titleFR: 'Vocabulaire de lecture : Tu Viens Samedi ?', description: 'Words from Tu Viens Samedi ?', descriptionFR: 'Vocabulaire du texte Tu Viens Samedi ?', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to phone / call', french: 'téléphoner à' },
        { id: 2, english: 'a brother', french: 'un frère' },
        { id: 3, english: 'a small meal', french: 'un petit repas' },
        { id: 4, english: 'at home', french: 'à la maison' },
        { id: 5, english: 'Do you want to come?', french: 'Tu veux venir ?' },
        { id: 6, english: 'to ask', french: 'demander' },
        { id: 7, english: 'who', french: 'qui' },
        { id: 8, english: 'a cousin', french: 'un cousin / une cousine' },
        { id: 9, english: 'to suggest', french: 'proposer' },
        { id: 10, english: 'around noon', french: 'vers midi' },
        { id: 11, english: 'to accept', french: 'accepter' },
        { id: 12, english: 'to explain', french: 'expliquer' },
        { id: 13, english: 'to have to / must', french: 'devoir' },
        { id: 14, english: 'no problem', french: 'pas de problème' },
        { id: 15, english: 'to bring', french: 'apporter' },
    ] },
    { level: 'A1', unit: 6, id: 'a1-je-vais-au-travail', title: 'Reading Vocabulary: Je Vais au Travail', titleFR: 'Vocabulaire de lecture : Je Vais au Travail', description: 'Words from Je Vais au Travail', descriptionFR: 'Vocabulaire du texte Je Vais au Travail', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'every morning', french: 'chaque matin' },
        { id: 2, english: 'to leave', french: 'quitter' },
        { id: 3, english: 'an office', french: 'un bureau' },
        { id: 4, english: 'another', french: 'un autre / une autre' },
        { id: 5, english: 'the neighbourhood', french: 'le quartier' },
        { id: 6, english: 'to walk', french: 'marcher' },
        { id: 7, english: 'a bus stop', french: 'un arrêt de bus' },
        { id: 8, english: 'to take the bus', french: 'prendre le bus' },
        { id: 9, english: 'to get off', french: 'descendre' },
        { id: 10, english: 'the station', french: 'la gare' },
        { id: 11, english: 'a few minutes', french: 'quelques minutes' },
        { id: 12, english: 'when', french: 'quand' },
        { id: 13, english: 'the weather is nice', french: 'il fait beau' },
        { id: 14, english: 'by bike', french: 'à vélo' },
        { id: 15, english: 'longer', french: 'plus long' },
    ] },
    { level: 'A1', unit: 6, id: 'a1-ou-est-la-gare', title: 'Reading Vocabulary: Où Est la Gare ?', titleFR: 'Vocabulaire de lecture : Où Est la Gare ?', description: 'Words from Où Est la Gare ?', descriptionFR: 'Vocabulaire du texte Où Est la Gare ?', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'on holiday', french: 'en vacances' },
        { id: 2, english: 'to want', french: 'vouloir' },
        { id: 3, english: 'the station', french: 'la gare' },
        { id: 4, english: 'to know', french: 'connaître' },
        { id: 5, english: 'to ask for help', french: 'demander de l\'aide' },
        { id: 6, english: 'Excuse me', french: 'excusez-moi' },
        { id: 7, english: 'Where is...?', french: 'Où est... ?' },
        { id: 8, english: 'to continue straight ahead', french: 'continuer tout droit' },
        { id: 9, english: 'the traffic light', french: 'le feu' },
        { id: 10, english: 'to turn left', french: 'tourner à gauche' },
        { id: 11, english: 'opposite', french: 'en face de' },
        { id: 12, english: 'to thank', french: 'remercier' },
        { id: 13, english: 'to follow', french: 'suivre' },
        { id: 14, english: 'directions / instructions', french: 'les indications' },
        { id: 15, english: 'before', french: 'avant' },
    ] },
    { level: 'A1', unit: 6, id: 'a1-a-la-gare', title: 'Reading Vocabulary: À la Gare', titleFR: 'Vocabulaire de lecture : À la Gare', description: 'Words from À la Gare', descriptionFR: 'Vocabulaire du texte À la Gare', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the station', french: 'la gare' },
        { id: 2, english: 'to take the train', french: 'prendre le train' },
        { id: 3, english: 'a screen', french: 'un écran' },
        { id: 4, english: 'to find', french: 'trouver' },
        { id: 5, english: 'a train', french: 'un train' },
        { id: 6, english: 'a platform', french: 'un quai' },
        { id: 7, english: 'to leave / depart', french: 'partir' },
        { id: 8, english: 'to have time', french: 'avoir du temps' },
        { id: 9, english: 'to buy', french: 'acheter' },
        { id: 10, english: 'a bottle of water', french: 'une bouteille d\'eau' },
        { id: 11, english: 'a sandwich', french: 'un sandwich' },
        { id: 12, english: 'a carriage / coach', french: 'une voiture' },
        { id: 13, english: 'a seat / place', french: 'une place' },
        { id: 14, english: 'near the window', french: 'près de la fenêtre' },
        { id: 15, english: 'a few minutes later', french: 'quelques minutes plus tard' },
    ] },
    { level: 'A1', unit: 6, id: 'a1-un-week-end-a-lyon', title: 'Reading Vocabulary: Un Week-end à Lyon', titleFR: 'Vocabulaire de lecture : Un Week-end à Lyon', description: 'Words from Un Week-end à Lyon', descriptionFR: 'Vocabulaire du texte Un Week-end à Lyon', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to spend the weekend', french: 'passer le week-end' },
        { id: 2, english: 'to leave / depart', french: 'partir' },
        { id: 3, english: 'to arrive', french: 'arriver' },
        { id: 4, english: 'a hotel', french: 'un hôtel' },
        { id: 5, english: 'the city centre', french: 'le centre-ville' },
        { id: 6, english: 'to visit', french: 'visiter' },
        { id: 7, english: 'the old town', french: 'la vieille ville' },
        { id: 8, english: 'to have lunch', french: 'déjeuner' },
        { id: 9, english: 'to walk / stroll', french: 'se promener' },
        { id: 10, english: 'the river', french: 'la rivière' },
        { id: 11, english: 'to meet up with', french: 'retrouver' },
        { id: 12, english: 'Sunday morning', french: 'le dimanche matin' },
        { id: 13, english: 'the return train', french: 'le train de retour' },
        { id: 14, english: 'short', french: 'court / courte' },
        { id: 15, english: 'a programme / schedule', french: 'un programme' },
    ] },
    { level: 'A1', unit: 7, id: 'a1-une-journee-a-marseille', title: 'Reading Vocabulary: Une Journée à Marseille', titleFR: 'Vocabulaire de lecture : Une Journée à Marseille', description: 'Words from Une Journée à Marseille', descriptionFR: 'Vocabulaire du texte Une Journée à Marseille', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to spend the day', french: 'passer la journée' },
        { id: 2, english: 'to arrive', french: 'arriver' },
        { id: 3, english: 'the Old Port', french: 'le Vieux-Port' },
        { id: 4, english: 'near the water', french: 'près de l\'eau' },
        { id: 5, english: 'to stop', french: 's\'arrêter' },
        { id: 6, english: 'to order', french: 'commander' },
        { id: 7, english: 'then / afterwards', french: 'ensuite' },
        { id: 8, english: 'a street', french: 'une rue' },
        { id: 9, english: 'a small shop / boutique', french: 'une boutique' },
        { id: 10, english: 'after the meal', french: 'après le repas' },
        { id: 11, english: 'the sea', french: 'la mer' },
        { id: 12, english: 'to stay', french: 'rester' },
        { id: 13, english: 'most of', french: 'une grande partie de' },
        { id: 14, english: 'at the end of the day', french: 'en fin de journée' },
        { id: 15, english: 'tired', french: 'fatigué / fatiguée' },
    ] },
    { level: 'A1', unit: 7, id: 'a1-une-visite-chez-des-amis', title: 'Reading Vocabulary: Une Visite Chez des Amis', titleFR: 'Vocabulaire de lecture : Une Visite Chez des Amis', description: 'Words from Une Visite Chez des Amis', descriptionFR: 'Vocabulaire du texte Une Visite Chez des Amis', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to have lunch at someone\'s house', french: 'déjeuner chez quelqu\'un' },
        { id: 2, english: 'friends', french: 'des amis' },
        { id: 3, english: 'thirty minutes from', french: 'à trente minutes de' },
        { id: 4, english: 'to arrive', french: 'arriver' },
        { id: 5, english: 'to prepare the meal', french: 'préparer le repas' },
        { id: 6, english: 'to show', french: 'montrer' },
        { id: 7, english: 'a new dog', french: 'un nouveau chien' },
        { id: 8, english: 'everywhere', french: 'partout' },
        { id: 9, english: 'to play', french: 'jouer' },
        { id: 10, english: 'a terrace', french: 'une terrasse' },
        { id: 11, english: 'vegetables', french: 'les légumes' },
        { id: 12, english: 'a cake', french: 'un gâteau' },
        { id: 13, english: 'next holidays', french: 'les prochaines vacances' },
        { id: 14, english: 'to go back home', french: 'rentrer chez soi' },
        { id: 15, english: 'next month', french: 'le mois prochain' },
    ] },
    { level: 'A1', unit: 7, id: 'a1-mes-premieres-semaines-en-france', title: 'Reading Vocabulary: Mes Premières Semaines en France', titleFR: 'Vocabulaire de lecture : Mes Premières Semaines en France', description: 'Words from Mes Premières Semaines en France', descriptionFR: 'Vocabulaire du texte Mes Premières Semaines en France', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'to come from', french: 'venir de' },
        { id: 2, english: 'now', french: 'maintenant' },
        { id: 3, english: 'to study', french: 'étudier' },
        { id: 4, english: 'to share an apartment', french: 'partager un appartement' },
        { id: 5, english: 'a student', french: 'un étudiant / une étudiante' },
        { id: 6, english: 'a French class', french: 'un cours de français' },
        { id: 7, english: 'by tram', french: 'en tramway' },
        { id: 8, english: 'several', french: 'plusieurs' },
        { id: 9, english: 'a country', french: 'un pays' },
        { id: 10, english: 'after class', french: 'après les cours' },
        { id: 11, english: 'at first', french: 'au début' },
        { id: 12, english: 'difficult', french: 'difficile' },
        { id: 13, english: 'too fast', french: 'trop vite' },
        { id: 14, english: 'every day', french: 'chaque jour' },
        { id: 15, english: 'an experience', french: 'une expérience' },
    ] },
    { level: 'A1', unit: 7, id: 'a1-un-week-end-a-la-campagne', title: 'Reading Vocabulary: Un Week-end à la Campagne', titleFR: 'Vocabulaire de lecture : Un Week-end à la Campagne', description: 'Words from Un Week-end à la Campagne', descriptionFR: 'Vocabulaire du texte Un Week-end à la Campagne', icon: '📚', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'the countryside', french: 'la campagne' },
        { id: 2, english: 'to leave the city', french: 'quitter la ville' },
        { id: 3, english: 'to spend the weekend', french: 'passer le week-end' },
        { id: 4, english: 'the parents', french: 'les parents' },
        { id: 5, english: 'a big garden', french: 'un grand jardin' },
        { id: 6, english: 'a long breakfast', french: 'un long petit-déjeuner' },
        { id: 7, english: 'to go for a walk', french: 'faire une promenade' },
        { id: 8, english: 'a village', french: 'un village' },
        { id: 9, english: 'nearby / neighbouring', french: 'voisin / voisine' },
        { id: 10, english: 'to read', french: 'lire' },
        { id: 11, english: 'to play cards', french: 'jouer aux cartes' },
        { id: 12, english: 'to prepare dinner', french: 'préparer le dîner' },
        { id: 13, english: 'outside', french: 'dehors' },
        { id: 14, english: 'to enjoy / make the most of', french: 'profiter de' },
        { id: 15, english: 'the quiet / calm', french: 'le calme' },
    ] },
    { level: 'A1', unit: 1,  id: 'greetings-basics',    title: 'Greetings & Essentials',  titleFR: 'Salutations & Essentiels',   description: 'Essential phrases to start any conversation',                    descriptionFR: 'Expressions essentielles pour commencer une conversation',       icon: '👋', color: '#F59E0B', wordCount: 0, words: [
        { id: 1, english: 'hello / good morning', french: 'bonjour' },
        { id: 2, english: 'good evening', french: 'bonsoir' },
        { id: 3, english: 'good night', french: 'bonne nuit' },
        { id: 4, english: 'goodbye', french: 'au revoir' },
        { id: 5, english: 'hi / bye (informal)', french: 'salut' },
        { id: 6, english: 'thank you', french: 'merci' },
        { id: 7, english: 'please (formal)', french: 's\'il vous plaît' },
        { id: 8, english: 'please (informal)', french: 's\'il te plaît' },
        { id: 9, english: 'excuse me (formal)', french: 'excusez-moi' },
        { id: 10, english: 'sorry / excuse me', french: 'pardon' },
        { id: 11, english: 'pleased to meet you', french: 'enchanté(e)' },
        { id: 12, english: 'my name is...', french: 'je m\'appelle...' },
        { id: 13, english: 'I don\'t understand', french: 'je ne comprends pas' },
        { id: 14, english: 'could you repeat that?', french: 'pouvez-vous répéter ?' },
        { id: 15, english: 'I\'m doing well', french: 'je vais bien' },
        { id: 16, english: 'so-so / not bad', french: 'comme ci comme ça' },
        { id: 17, english: 'see you soon', french: 'à bientôt' },
        { id: 18, english: 'see you later (same day)', french: 'à tout à l\'heure' },
        { id: 19, english: 'welcome', french: 'bienvenue' },
        { id: 20, english: 'with pleasure / gladly', french: 'avec plaisir' },
    ] },
    { level: 'A1', unit: 2,  id: 'numbers-time',        title: 'Numbers & Time',          titleFR: 'Chiffres & Temps',           description: 'Tell the time and express when things happen',                   descriptionFR: "Dire l'heure et exprimer quand les choses se passent",           icon: '🕐', color: '#06B6D4', wordCount: 0, words: [
        { id: 1,  english: 'one',                                      french: 'un / une' },
        { id: 2,  english: 'two',                                      french: 'deux' },
        { id: 3,  english: 'three',                                    french: 'trois' },
        { id: 4,  english: 'four',                                     french: 'quatre' },
        { id: 5,  english: 'five',                                     french: 'cinq' },
        { id: 6,  english: 'six',                                      french: 'six' },
        { id: 7,  english: 'seven',                                    french: 'sept' },
        { id: 8,  english: 'eight',                                    french: 'huit' },
        { id: 9,  english: 'nine',                                     french: 'neuf' },
        { id: 10, english: 'ten',                                      french: 'dix' },
        { id: 11, english: 'eleven',                                   french: 'onze' },
        { id: 12, english: 'twelve',                                   french: 'douze' },
        { id: 13, english: 'twenty',                                   french: 'vingt' },
        { id: 14, english: 'thirty',                                   french: 'trente' },
        { id: 15, english: 'forty',                                    french: 'quarante' },
        { id: 16, english: 'fifty',                                    french: 'cinquante' },
        { id: 17, english: 'sixty',                                    french: 'soixante' },
        { id: 18, english: 'seventy (lit. sixty-ten)',                 french: 'soixante-dix' },
        { id: 19, english: 'eighty (lit. four-twenties)',              french: 'quatre-vingts' },
        { id: 20, english: 'one hundred',                              french: 'cent' },
    ] },
    { level: 'A1', unit: 3,  id: 'colors-descriptions', title: 'Colors & Descriptions',   titleFR: 'Couleurs & Descriptions',    description: 'Describe people, places and things',                             descriptionFR: 'Décrire des personnes, des lieux et des objets',                 icon: '🎨', color: '#EC4899', wordCount: 0, words: [
        { id: 1, english: 'red', french: 'rouge' },
        { id: 2, english: 'blue', french: 'bleu(e)' },
        { id: 3, english: 'green', french: 'vert(e)' },
        { id: 4, english: 'yellow', french: 'jaune' },
        { id: 5, english: 'white', french: 'blanc/blanche' },
        { id: 6, english: 'black', french: 'noir(e)' },
        { id: 7, english: 'grey', french: 'gris(e)' },
        { id: 8, english: 'pink', french: 'rose' },
        { id: 9, english: 'purple / violet', french: 'violet(te)' },
        { id: 10, english: 'brown', french: 'marron' },
        { id: 11, english: 'big / tall', french: 'grand(e)' },
        { id: 12, english: 'small / short', french: 'petit(e)' },
        { id: 13, english: 'beautiful / handsome', french: 'beau / belle' },
        { id: 14, english: 'ugly', french: 'laid(e)' },
        { id: 15, english: 'round', french: 'rond(e)' },
        { id: 16, english: 'square', french: 'carré(e)' },
        { id: 17, english: 'narrow', french: 'étroit(e)' },
        { id: 18, english: 'wide / broad', french: 'large' },
        { id: 19, english: 'light (in color) / bright', french: 'clair(e)' },
        { id: 20, english: 'dark (in color)', french: 'foncé(e)' },
    ] },
    { level: 'A1', unit: 3,  id: 'family-relationships',title: 'Family & Relationships',  titleFR: 'Famille & Relations',        description: 'Talk about the people in your life',                             descriptionFR: 'Parler des personnes de votre vie',                             icon: '👨‍👩‍👧‍👦', color: '#10B981', wordCount: 0, words: [
        { id: 1, english: 'the parents', french: 'les parents' },
        { id: 2, english: 'the father', french: 'le père' },
        { id: 3, english: 'the mother', french: 'la mère' },
        { id: 4, english: 'the brother', french: 'le frère' },
        { id: 5, english: 'the sister', french: 'la sœur' },
        { id: 6, english: 'the grandparents', french: 'les grands-parents' },
        { id: 7, english: 'the grandfather', french: 'le grand-père' },
        { id: 8, english: 'the grandmother', french: 'la grand-mère' },
        { id: 9, english: 'the son', french: 'le fils' },
        { id: 10, english: 'the daughter', french: 'la fille' },
        { id: 11, english: 'a friend', french: 'un(e) ami(e)' },
        { id: 12, english: 'a neighbour', french: 'un(e) voisin(e)' },
        { id: 13, english: 'a colleague', french: 'un(e) collègue' },
        { id: 14, english: 'the spouse / partner', french: 'le conjoint / la conjointe' },
        { id: 15, english: 'twins (masc. / fem.)', french: 'les jumeaux / les jumelles' },
        { id: 16, english: 'an only child', french: 'un enfant unique' },
        { id: 17, english: 'eldest (child)', french: 'aîné(e)' },
        { id: 18, english: 'youngest (child)', french: 'cadet(te)' },
        { id: 19, english: 'to raise a child', french: 'élever un enfant' },
        { id: 20, english: 'family ties / bonds', french: 'les liens familiaux' },
    ] },
    { level: 'A1', unit: 4,  id: 'food-drinks',         title: 'Food & Drinks',           titleFR: 'Nourriture & Boissons',      description: 'Eat, drink and order with confidence',                           descriptionFR: 'Manger, boire et commander avec assurance',                     icon: '🍷', color: '#EF4444', wordCount: 0, words: [
        { id: 1, english: 'the meal', french: 'le repas' },
        { id: 2, english: 'breakfast', french: 'le petit-déjeuner' },
        { id: 3, english: 'lunch', french: 'le déjeuner' },
        { id: 4, english: 'dinner', french: 'le dîner' },
        { id: 5, english: 'a starter / appetiser', french: 'une entrée' },
        { id: 6, english: 'a main course', french: 'un plat principal' },
        { id: 7, english: 'dessert', french: 'le dessert' },
        { id: 8, english: 'bread', french: 'le pain' },
        { id: 9, english: 'cheese', french: 'le fromage' },
        { id: 10, english: 'meat', french: 'la viande' },
        { id: 11, english: 'fish', french: 'le poisson' },
        { id: 12, english: 'vegetables', french: 'les légumes' },
        { id: 13, english: 'fruit', french: 'les fruits' },
        { id: 14, english: 'a drink / beverage', french: 'une boisson' },
        { id: 15, english: 'water', french: 'l\'eau' },
        { id: 16, english: 'wine', french: 'le vin' },
        { id: 17, english: 'to be hungry', french: 'avoir faim' },
        { id: 18, english: 'to be thirsty', french: 'avoir soif' },
        { id: 19, english: 'the tip / gratuity', french: 'le pourboire' },
        { id: 20, english: 'the bill (at a restaurant)', french: 'l\'addition' },
    ] },
    { level: 'A1', unit: 7,  id: 'body-health',         title: 'Body & Health',           titleFR: 'Corps & Santé',              description: 'Talk about your body and wellbeing',                             descriptionFR: 'Parler de votre corps et de votre bien-être',                   icon: '🏥', color: '#6366F1', wordCount: 0, words: [
        { id: 1, english: 'the head', french: 'la tête' },
        { id: 2, english: 'the face', french: 'le visage' },
        { id: 3, english: 'the eyes', french: 'les yeux' },
        { id: 4, english: 'the mouth', french: 'la bouche' },
        { id: 5, english: 'the ears', french: 'les oreilles' },
        { id: 6, english: 'the heart', french: 'le cœur' },
        { id: 7, english: 'the arms', french: 'les bras' },
        { id: 8, english: 'the legs', french: 'les jambes' },
        { id: 9, english: 'to have a pain in / to ache', french: 'avoir mal à' },
        { id: 10, english: 'pain / an ache', french: 'la douleur' },
        { id: 11, english: 'a fever', french: 'la fièvre' },
        { id: 12, english: 'a prescription', french: 'une ordonnance' },
        { id: 13, english: 'a medication / medicine', french: 'un médicament' },
        { id: 14, english: 'a doctor\'s appointment', french: 'une consultation' },
        { id: 15, english: 'to recover / to get better', french: 'se rétablir' },
        { id: 16, english: 'pregnant', french: 'enceinte' },
        { id: 17, english: 'exhausted / worn out', french: 'épuisé(e)' },
        { id: 18, english: 'in shape / fit and well', french: 'en forme' },
        { id: 19, english: 'an allergy', french: 'une allergie' },
        { id: 20, english: 'the emergency room / A&E', french: 'les urgences' },
    ] },
    { level: 'A1', unit: 3,  id: 'home-living',         title: 'Home & Living',           titleFR: 'Maison & Vie quotidienne',   description: 'Vocabulary for your home and daily living',                      descriptionFR: 'Vocabulaire pour la maison et la vie quotidienne',               icon: '🏠', color: '#84CC16', wordCount: 0, words: [
        { id: 1, english: 'a flat / apartment', french: 'un appartement' },
        { id: 2, english: 'a house', french: 'une maison' },
        { id: 3, english: 'the kitchen', french: 'la cuisine' },
        { id: 4, english: 'the bathroom', french: 'la salle de bains' },
        { id: 5, english: 'the living room', french: 'le salon' },
        { id: 6, english: 'the bedroom', french: 'la chambre' },
        { id: 7, english: 'furniture', french: 'les meubles' },
        { id: 8, english: 'a sofa / couch', french: 'un canapé' },
        { id: 9, english: 'a cupboard / wardrobe', french: 'un placard' },
        { id: 10, english: 'curtains', french: 'les rideaux' },
        { id: 11, english: 'to move in (to a home)', french: 'emménager' },
        { id: 12, english: 'to move out / move house', french: 'déménager' },
        { id: 13, english: 'the rent', french: 'le loyer' },
        { id: 14, english: 'utility bills / service charges', french: 'les charges' },
        { id: 15, english: 'a landlord / property owner', french: 'un propriétaire' },
        { id: 16, english: 'a tenant / renter', french: 'un locataire' },
        { id: 17, english: 'to renovate / to do up', french: 'rénover' },
        { id: 18, english: 'to maintain / to keep in good repair', french: 'entretenir' },
        { id: 19, english: 'to plug in / to connect (an appliance)', french: 'brancher' },
        { id: 20, english: 'the bill / invoice (electricity, phone, etc.)', french: 'la facture' },
    ] },
    { level: 'A1', unit: 6,  id: 'city-places',             title: 'City & Places',               titleFR: 'Ville & Lieux',                 description: 'Navigate urban spaces and talk about places',                descriptionFR: 'Naviguer les espaces urbains et parler des lieux',         icon: '🏙️', color: '#0EA5E9', wordCount: 0, words: [
        { id: 1,  english: 'the town hall / city hall',         french: 'la mairie' },
        { id: 2,  english: 'a pharmacy / chemist',              french: 'une pharmacie' },
        { id: 3,  english: 'a hospital',                        french: 'un hôpital' },
        { id: 4,  english: 'a church',                          french: 'une église' },
        { id: 5,  english: 'a museum',                          french: 'un musée' },
        { id: 6,  english: 'a market',                          french: 'un marché' },
        { id: 7,  english: 'a bank',                            french: 'une banque' },
        { id: 8,  english: 'a post office',                     french: 'la poste' },
        { id: 9,  english: 'a supermarket',                     french: 'un supermarché' },
        { id: 10, english: 'a school',                          french: 'une école' },
        { id: 11, english: 'a library',                         french: 'une bibliothèque' },
        { id: 12, english: 'a park',                            french: 'un parc' },
        { id: 13, english: 'a restaurant',                      french: 'un restaurant' },
        { id: 14, english: 'a hotel',                           french: 'un hôtel' },
        { id: 15, english: 'a cinema / movie theatre',          french: 'un cinéma' },
        { id: 16, english: 'a bakery',                          french: 'une boulangerie' },
        { id: 17, english: 'a bookshop / bookstore',            french: 'une librairie' },
        { id: 18, english: 'a swimming pool',                   french: 'une piscine' },
        { id: 19, english: 'a stadium',                         french: 'un stade' },
        { id: 20, english: 'a neighbourhood / district',        french: 'un quartier' },
    ] },
    { level: 'A1', unit: 2,  id: 'clothing-accessories',    title: 'Clothing & Accessories',      titleFR: 'Vêtements & Accessoires',       description: 'Fashion, clothing and personal style',                       descriptionFR: 'Mode, vêtements et style personnel',                       icon: '👗', color: '#F43F5E', wordCount: 0, words: [
        { id: 1,  english: 'clothes / clothing',              french: 'les vêtements' },
        { id: 2,  english: 'a shirt',                         french: 'une chemise' },
        { id: 3,  english: 'trousers / pants',                french: 'un pantalon' },
        { id: 4,  english: 'a dress',                         french: 'une robe' },
        { id: 5,  english: 'shoes',                           french: 'les chaussures' },
        { id: 6,  english: 'a coat',                          french: 'un manteau' },
        { id: 7,  english: 'a hat',                           french: 'un chapeau' },
        { id: 8,  english: 'a bag / handbag',                 french: 'un sac' },
        { id: 9,  english: 'a belt',                          french: 'une ceinture' },
        { id: 10, english: 'gloves',                          french: 'des gants' },
        { id: 11, english: 'a scarf',                         french: 'une écharpe' },
        { id: 12, english: 'socks',                           french: 'des chaussettes' },
        { id: 13, english: 'a jacket',                        french: 'une veste' },
        { id: 14, english: 'a jumper / sweater / pullover',   french: 'un pull' },
        { id: 15, english: 'a skirt',                         french: 'une jupe' },
        { id: 16, english: 'a raincoat',                      french: 'un imperméable' },
        { id: 17, english: 'glasses',                         french: 'des lunettes' },
        { id: 18, english: 'a watch',                         french: 'une montre' },
        { id: 19, english: 'a ring',                          french: 'une bague' },
        { id: 20, english: 'a necklace',                      french: 'un collier' },
    ] },
    { level: 'A1', unit: 2,  id: 'days-months',             title: 'Days & Months',               titleFR: 'Jours & Mois',                  description: 'Calendar vocabulary, days, months and dates',                descriptionFR: 'Vocabulaire du calendrier, jours, mois et dates',          icon: '📅', color: '#06B6D4', wordCount: 0, words: [
        { id: 1,  english: 'Monday',    french: 'lundi' },
        { id: 2,  english: 'Tuesday',   french: 'mardi' },
        { id: 3,  english: 'Wednesday', french: 'mercredi' },
        { id: 4,  english: 'Thursday',  french: 'jeudi' },
        { id: 5,  english: 'Friday',    french: 'vendredi' },
        { id: 6,  english: 'Saturday',  french: 'samedi' },
        { id: 7,  english: 'Sunday',    french: 'dimanche' },
        { id: 8,  english: 'January',   french: 'janvier' },
        { id: 9,  english: 'February',  french: 'février' },
        { id: 10, english: 'March',     french: 'mars' },
        { id: 11, english: 'April',     french: 'avril' },
        { id: 12, english: 'May',       french: 'mai' },
        { id: 13, english: 'June',      french: 'juin' },
        { id: 14, english: 'July',      french: 'juillet' },
        { id: 15, english: 'August',    french: 'août' },
        { id: 16, english: 'September', french: 'septembre' },
        { id: 17, english: 'October',   french: 'octobre' },
        { id: 18, english: 'November',  french: 'novembre' },
        { id: 19, english: 'December',  french: 'décembre' },
        { id: 20, english: 'a week',    french: 'une semaine' },
    ] },
    { level: 'A1', unit: 1,  id: 'nationalities',           title: 'Nationalities',               titleFR: 'Nationalités',                  description: 'Countries, nationalities and demonyms',                      descriptionFR: 'Pays, nationalités et gentilés',                           icon: '🌐', color: '#14B8A6', wordCount: 0, words: [
        { id: 1,  english: 'French',      french: 'français(e)' },
        { id: 2,  english: 'France',      french: 'la France' },
        { id: 3,  english: 'English / British', french: 'anglais(e) / britannique' },
        { id: 4,  english: 'the United Kingdom', french: 'le Royaume-Uni' },
        { id: 5,  english: 'American',    french: 'américain(e)' },
        { id: 6,  english: 'the United States', french: 'les États-Unis' },
        { id: 7,  english: 'Spanish',     french: 'espagnol(e)' },
        { id: 8,  english: 'Spain',       french: 'l\'Espagne' },
        { id: 9,  english: 'German',      french: 'allemand(e)' },
        { id: 10, english: 'Germany',     french: 'l\'Allemagne' },
        { id: 11, english: 'Italian',     french: 'italien(ne)' },
        { id: 12, english: 'Italy',       french: 'l\'Italie' },
        { id: 13, english: 'Belgian',     french: 'belge' },
        { id: 14, english: 'Belgium',     french: 'la Belgique' },
        { id: 15, english: 'Swiss',       french: 'suisse' },
        { id: 16, english: 'Switzerland', french: 'la Suisse' },
        { id: 17, english: 'Canadian',    french: 'canadien(ne)' },
        { id: 18, english: 'Canada',      french: 'le Canada' },
        { id: 19, english: 'Moroccan',    french: 'marocain(e)' },
        { id: 20, english: 'I\'m originally from…', french: 'Je suis originaire de…' },
    ] },
    { level: 'A1', unit: 7,  id: 'seasons-weather',         title: 'Seasons & Weather',           titleFR: 'Saisons & Météo',               description: 'Weather patterns and seasonal changes',                      descriptionFR: 'Conditions météorologiques et changements saisonniers',    icon: '🌤️', color: '#0284C7', wordCount: 0, words: [
        { id: 1,  english: 'spring',                french: 'le printemps' },
        { id: 2,  english: 'summer',                french: 'l\'été' },
        { id: 3,  english: 'autumn / fall',         french: 'l\'automne' },
        { id: 4,  english: 'winter',                french: 'l\'hiver' },
        { id: 5,  english: 'the sun / sunshine',    french: 'le soleil' },
        { id: 6,  english: 'rain',                  french: 'la pluie' },
        { id: 7,  english: 'snow',                  french: 'la neige' },
        { id: 8,  english: 'wind',                  french: 'le vent' },
        { id: 9,  english: 'a cloud',               french: 'un nuage' },
        { id: 10, english: 'a storm / thunderstorm',french: 'un orage' },
        { id: 11, english: 'heat',                  french: 'la chaleur' },
        { id: 12, english: 'cold',                  french: 'le froid' },
        { id: 13, english: 'fog / mist',            french: 'le brouillard' },
        { id: 14, english: 'a rainbow',             french: 'un arc-en-ciel' },
        { id: 15, english: 'temperature',           french: 'la température' },
        { id: 16, english: 'a degree',              french: 'un degré' },
        { id: 17, english: 'weather forecast',      french: 'la météo' },
        { id: 18, english: 'a season',              french: 'une saison' },
        { id: 19, english: 'clear / bright (sky)',  french: 'clair(e)' },
        { id: 20, english: 'overcast / cloudy',     french: 'couvert(e)' },
    ] },
    { level: 'A1', unit: 6,  id: 'transport-basics',        title: 'Transport Basics',            titleFR: 'Transport — Bases',             description: 'Everyday transport and getting around',                      descriptionFR: 'Transport quotidien et déplacements',                      icon: '🚌', color: '#16A34A', wordCount: 0, words: [
        { id: 1,  english: 'the underground / subway / metro',  french: 'le métro' },
        { id: 2,  english: 'a bus',                             french: 'un bus' },
        { id: 3,  english: 'a taxi / cab',                      french: 'un taxi' },
        { id: 4,  english: 'a car',                             french: 'une voiture' },
        { id: 5,  english: 'a bicycle / bike',                  french: 'un vélo' },
        { id: 6,  english: 'a train',                           french: 'un train' },
        { id: 7,  english: 'a plane / aeroplane',               french: 'un avion' },
        { id: 8,  english: 'a boat / ship',                     french: 'un bateau' },
        { id: 9,  english: 'a stop / bus stop',                 french: 'un arrêt' },
        { id: 10, english: 'a train station',                   french: 'une gare' },
        { id: 11, english: 'an airport',                        french: 'un aéroport' },
        { id: 12, english: 'a ticket (train / plane)',           french: 'un billet' },
        { id: 13, english: 'a ticket (metro / bus)',             french: 'un ticket' },
        { id: 14, english: 'a line (metro / bus route)',         french: 'une ligne' },
        { id: 15, english: 'a station (metro)',                  french: 'une station' },
        { id: 16, english: 'a platform / quay',                 french: 'un quai' },
        { id: 17, english: 'a driver',                          french: 'un conducteur' },
        { id: 18, english: 'a passenger',                       french: 'un passager' },
        { id: 19, english: 'a return ticket / round trip',      french: 'un aller-retour' },
        { id: 20, english: 'a journey / trip / commute',        french: 'un trajet' },
    ] },
];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsA1: VocabularyData = {

};
