import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

const giftReadingWords: VocabularyWord[] = [
    { id: 1, english: "a gift", french: "un cadeau" },
    { id: 2, english: "a birthday", french: "un anniversaire" },
    { id: 3, english: "a budget", french: "un budget" },
    { id: 4, english: "useful", french: "utile" },
    { id: 5, english: "a shop assistant (female)", french: "une vendeuse" },
    { id: 6, english: "a model / design", french: "un modèle" },
    { id: 7, english: "cheaper", french: "moins cher" },
    { id: 8, english: "a pocket", french: "une poche" },
    { id: 9, english: "a fastening / closure", french: "une fermeture" },
    { id: 10, english: "the checkout", french: "la caisse" },
    { id: 11, english: "a receipt", french: "le ticket de caisse" },
    { id: 12, english: "to exchange", french: "échanger" },

];

const dinnerReadingWords: VocabularyWord[] = [
    { id: 1, english: "free / available", french: "libre" },
    { id: 2, english: "an invitation", french: "une invitation" },
    { id: 3, english: "to bring", french: "apporter" },
    { id: 4, english: "a shopping list", french: "la liste des courses" },
    { id: 5, english: "a dish", french: "un plat" },
    { id: 6, english: "meat", french: "la viande" },
    { id: 7, english: "vegetarian", french: "végétarien" },
    { id: 8, english: "to tidy", french: "ranger" },
    { id: 9, english: "to set the table", french: "mettre la table" },
    { id: 10, english: "to be a little late", french: "avoir un peu de retard" },
    { id: 11, english: "guests", french: "les invités" },
    { id: 12, english: "a board game", french: "un jeu de société" },
];

export const modulesA2: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'A2', unit: 1,  id: 'work-professions',    title: 'Work & Professions',      titleFR: 'Travail & Professions',      description: 'Navigate the workplace in French',                               descriptionFR: 'Naviguer le monde du travail en français',                      icon: '💼', color: '#F97316', wordCount: 0, words: [
        { id: 1, english: 'a trade / occupation / job', french: 'un métier' },
        { id: 2, english: 'a job / employment', french: 'un emploi' },
        { id: 3, english: 'a position / post (at a company)', french: 'un poste' },
        { id: 4, english: 'a salary / wage', french: 'un salaire' },
        { id: 5, english: 'a job application', french: 'une candidature' },
        { id: 6, english: 'an interview (job)', french: 'un entretien' },
        { id: 7, english: 'a boss / employer', french: 'un(e) patron(ne)' },
        { id: 8, english: 'an employee', french: 'un(e) employé(e)' },
        { id: 9, english: 'to be unemployed', french: 'être au chômage' },
        { id: 10, english: 'a permanent contract', french: 'un contrat à durée indéterminée (CDI)' },
        { id: 11, english: 'a fixed-term contract', french: 'un contrat à durée déterminée (CDD)' },
        { id: 12, english: 'paid holiday / paid leave', french: 'les congés payés' },
        { id: 13, english: 'a promotion', french: 'une promotion' },
        { id: 14, english: 'to resign', french: 'démissionner' },
        { id: 15, english: 'to dismiss / to lay off', french: 'licencier' },
        { id: 16, english: 'a trade union', french: 'un syndicat' },
        { id: 17, english: 'overtime', french: 'les heures supplémentaires' },
        { id: 18, english: 'part-time', french: 'à mi-temps' },
        { id: 19, english: 'full-time', french: 'à plein temps' },
        { id: 20, english: 'remote work / working from home', french: 'télétravail' },
    ] },
    { level: 'A2', unit: 3,  id: 'weather-nature',      title: 'Weather & Nature',        titleFR: 'Météo & Nature',             description: 'Describe the world around you',                                  descriptionFR: 'Décrire le monde qui vous entoure',                             icon: '🌿', color: '#14B8A6', wordCount: 0, words: [
        { id: 1, english: 'the weather is nice / it\'s sunny', french: 'il fait beau' },
        { id: 2, english: 'it\'s raining', french: 'il pleut' },
        { id: 3, english: 'it\'s snowing', french: 'il neige' },
        { id: 4, english: 'a storm / thunderstorm', french: 'un orage' },
        { id: 5, english: 'a heatwave', french: 'la canicule' },
        { id: 6, english: 'drought', french: 'la sécheresse' },
        { id: 7, english: 'a flood', french: 'une inondation' },
        { id: 8, english: 'fog / mist', french: 'le brouillard' },
        { id: 9, english: 'a cold spell / cold wave', french: 'une vague de froid' },
        { id: 10, english: 'sunny / bright', french: 'ensoleillé(e)' },
        { id: 11, english: 'cloudy / overcast', french: 'nuageux(-euse)' },
        { id: 12, english: 'a forest', french: 'une forêt' },
        { id: 13, english: 'a mountain', french: 'une montagne' },
        { id: 14, english: 'a major river (flowing to the sea)', french: 'un fleuve' },
        { id: 15, english: 'a river / stream (tributary)', french: 'une rivière' },
        { id: 16, english: 'wildlife / fauna', french: 'la faune' },
        { id: 17, english: 'plant life / flora', french: 'la flore' },
        { id: 18, english: 'global warming / climate change', french: 'le réchauffement climatique' },
        { id: 19, english: 'sustainable', french: 'durable' },
        { id: 20, english: 'to protect the environment', french: 'protéger l\'environnement' },
    ] },
    { level: 'A2', unit: 4,  id: 'sports-hobbies',      title: 'Sports & Hobbies',        titleFR: 'Sports & Loisirs',           description: 'Talk about what you love doing',                                 descriptionFR: 'Parler de ce que vous aimez faire',                             icon: '⚽', color: '#8B5CF6', wordCount: 0, words: [
        { id: 1, english: 'to do sport / exercise', french: 'faire du sport' },
        { id: 2, english: 'to train / to practise', french: 's\'entraîner' },
        { id: 3, english: 'a match / game', french: 'un match' },
        { id: 4, english: 'to score a goal', french: 'marquer un but' },
        { id: 5, english: 'a tournament', french: 'un tournoi' },
        { id: 6, english: 'swimming', french: 'la natation' },
        { id: 7, english: 'hiking / trekking', french: 'la randonnée' },
        { id: 8, english: 'cycling', french: 'le cyclisme' },
        { id: 9, english: 'horse riding', french: 'l\'équitation' },
        { id: 10, english: 'martial arts', french: 'les arts martiaux' },
        { id: 11, english: 'a hobby / pastime', french: 'un passe-temps' },
        { id: 12, english: 'painting', french: 'la peinture' },
        { id: 13, english: 'photography', french: 'la photographie' },
        { id: 14, english: 'to volunteer', french: 'faire du bénévolat' },
        { id: 15, english: 'to play an instrument', french: 'jouer d\'un instrument' },
        { id: 16, english: 'to attend (an event)', french: 'assister à' },
        { id: 17, english: 'a competition', french: 'une compétition' },
        { id: 18, english: 'a champion', french: 'un champion / une championne' },
        { id: 19, english: 'to be a fan of', french: 'être fan de' },
        { id: 20, english: 'leisure activities / free-time pursuits', french: 'les loisirs' },
    ] },
    { level: 'A2', unit: 1,  id: 'school-education',    title: 'School & Education',      titleFR: 'École & Éducation',          description: 'Academic and learning vocabulary',                               descriptionFR: 'Vocabulaire académique et scolaire',                            icon: '📚', color: '#0EA5E9', wordCount: 0, words: [
        { id: 1, english: 'a school / educational establishment', french: 'un établissement scolaire' },
        { id: 2, english: 'a secondary school (ages 15-18)', french: 'un lycée' },
        { id: 3, english: 'a university', french: 'une université' },
        { id: 4, english: 'a school subject', french: 'une matière' },
        { id: 5, english: 'mathematics', french: 'les mathématiques' },
        { id: 6, english: 'science', french: 'les sciences' },
        { id: 7, english: 'history', french: 'l\'histoire' },
        { id: 8, english: 'modern foreign languages', french: 'les langues vivantes' },
        { id: 9, english: 'a lecture', french: 'un cours magistral' },
        { id: 10, english: 'a presentation / oral report', french: 'un exposé' },
        { id: 11, english: 'homework / an assignment', french: 'un devoir' },
        { id: 12, english: 'to write up / to draft (an essay, report)', french: 'rédiger' },
        { id: 13, english: 'to research / to gather information', french: 'se documenter' },
        { id: 14, english: 'to revise / to review (for an exam)', french: 'réviser' },
        { id: 15, english: 'to sit / take an exam', french: 'passer un examen' },
        { id: 16, english: 'to pass an exam', french: 'réussir un examen' },
        { id: 17, english: 'to fail an exam', french: 'échouer à un examen' },
        { id: 18, english: 'a degree / qualification / diploma', french: 'un diplôme' },
        { id: 19, english: 'a scholarship / study grant', french: 'une bourse d\'études' },
        { id: 20, english: 'learning / apprenticeship', french: 'l\'apprentissage' },
    ] },
    { level: 'A2', unit: 2,  id: 'shopping-money',      title: 'Shopping & Money',        titleFR: 'Shopping & Argent',          description: 'Buy, sell and manage finances',                                  descriptionFR: 'Acheter, vendre et gérer ses finances',                         icon: '🛍️', color: '#F43F5E', wordCount: 0, words: [
        { id: 1, english: 'to go shopping (for groceries)', french: 'faire des courses' },
        { id: 2, english: 'to go shopping (for clothes/fun)', french: 'faire du shopping' },
        { id: 3, english: 'a shop / store', french: 'un magasin' },
        { id: 4, english: 'a shop window / display', french: 'une vitrine' },
        { id: 5, english: 'the sales (seasonal discounts)', french: 'les soldes' },
        { id: 6, english: 'a special offer / deal', french: 'une promotion' },
        { id: 7, english: 'the price', french: 'le prix' },
        { id: 8, english: 'expensive', french: 'cher / chère' },
        { id: 9, english: 'cheap / inexpensive', french: 'bon marché' },
        { id: 10, english: 'to reimburse / to refund', french: 'rembourser' },
        { id: 11, english: 'a receipt', french: 'un reçu' },
        { id: 12, english: 'to pay in cash', french: 'payer en espèces' },
        { id: 13, english: 'to pay by card', french: 'payer par carte' },
        { id: 14, english: 'to save (money)', french: 'économiser' },
        { id: 15, english: 'to spend (money)', french: 'dépenser' },
        { id: 16, english: 'a budget', french: 'un budget' },
        { id: 17, english: 'indebtedness / debt', french: 'endettement' },
        { id: 18, english: 'a bank transfer', french: 'un virement bancaire' },
        { id: 19, english: 'the exchange rate', french: 'le taux de change' },
        { id: 20, english: 'on credit / on hire purchase', french: 'à crédit' },
    ] },
    { level: 'A2', unit: 2,  id: 'animals',                 title: 'Animals',                     titleFR: 'Animaux',                       description: 'Wildlife, pets and the animal kingdom',                      descriptionFR: 'Faune, animaux domestiques et règne animal',               icon: '🐾', color: '#10B981', wordCount: 0, words: [
        { id: 1,  english: 'a dog',                  french: 'un chien' },
        { id: 2,  english: 'a cat',                  french: 'un chat' },
        { id: 3,  english: 'a rabbit',               french: 'un lapin' },
        { id: 4,  english: 'a hamster',              french: 'un hamster' },
        { id: 5,  english: 'a (pet) fish',           french: 'un poisson' },
        { id: 6,  english: 'a bird',                 french: 'un oiseau' },
        { id: 7,  english: 'a cow',                  french: 'une vache' },
        { id: 8,  english: 'a horse',                french: 'un cheval' },
        { id: 9,  english: 'a pig',                  french: 'un cochon' },
        { id: 10, english: 'a sheep',                french: 'un mouton' },
        { id: 11, english: 'a hen / chicken',        french: 'une poule' },
        { id: 12, english: 'a lion',                 french: 'un lion' },
        { id: 13, english: 'a tiger',                french: 'un tigre' },
        { id: 14, english: 'an elephant',            french: 'un éléphant' },
        { id: 15, english: 'a monkey',               french: 'un singe' },
        { id: 16, english: 'a snake',                french: 'un serpent' },
        { id: 17, english: 'a bear',                 french: 'un ours' },
        { id: 18, english: 'a wolf',                 french: 'un loup' },
        { id: 19, english: 'a bee',                  french: 'une abeille' },
        { id: 20, english: 'a butterfly',            french: 'un papillon' },
    ] },
    { level: 'A2', unit: 5,  id: 'celebrations-events',     title: 'Celebrations & Events',       titleFR: 'Célébrations & Événements',     description: 'Holidays, ceremonies and special occasions',                 descriptionFR: 'Fêtes, cérémonies et occasions spéciales',                 icon: '🎉', color: '#F59E0B', wordCount: 0, words: [
        { id: 1,  english: 'a birthday',              french: 'un anniversaire' },
        { id: 2,  english: 'a wedding',               french: 'un mariage' },
        { id: 3,  english: 'a party / celebration',   french: 'une fête' },
        { id: 4,  english: 'a gift / present',        french: 'un cadeau' },
        { id: 5,  english: 'an invitation',           french: 'une invitation' },
        { id: 6,  english: 'a ceremony',              french: 'une cérémonie' },
        { id: 7,  english: 'a meeting / gathering',   french: 'une réunion' },
        { id: 8,  english: 'a concert',               french: 'un concert' },
        { id: 9,  english: 'an exhibition',           french: 'une exposition' },
        { id: 10, english: 'a show / performance',    french: 'un spectacle' },
        { id: 11, english: 'a ticket (event)',        french: 'un billet' },
        { id: 12, english: 'congratulations',         french: 'félicitations' },
        { id: 13, english: 'a guest',                 french: 'un(e) invité(e)' },
        { id: 14, english: 'a host',                  french: 'un(e) hôte' },
        { id: 15, english: 'a banquet / feast',       french: 'un banquet' },
        { id: 16, english: 'a toast (speech)',        french: 'un toast' },
        { id: 17, english: 'champagne',               french: 'le champagne' },
        { id: 18, english: 'a souvenir / memory',     french: 'un souvenir' },
        { id: 19, english: 'a tradition',             french: 'une tradition' },
        { id: 20, english: 'a programme',             french: 'un programme' },
    ] },
    { level: 'A2', unit: 2,  id: 'food-culture',            title: 'Food Culture',                titleFR: 'Culture culinaire',             description: 'French gastronomy, cuisine and food traditions',             descriptionFR: 'Gastronomie, cuisine et traditions alimentaires françaises',icon: '🥗', color: '#EF4444', wordCount: 0, words: [
        { id: 1,  english: 'a bakery',                      french: 'une boulangerie' },
        { id: 2,  english: 'a cake shop / patisserie',      french: 'une pâtisserie' },
        { id: 3,  english: 'a delicatessen',                french: 'une charcuterie' },
        { id: 4,  english: 'a cheese shop',                 french: 'une fromagerie' },
        { id: 5,  english: 'a grocer\'s / small food shop', french: 'une épicerie' },
        { id: 6,  english: 'a market',                      french: 'un marché' },
        { id: 7,  english: 'a recipe',                      french: 'une recette' },
        { id: 8,  english: 'an ingredient',                 french: 'un ingrédient' },
        { id: 9,  english: 'to cook',                       french: 'cuisiner' },
        { id: 10, english: 'pre-dinner drinks / aperitif',  french: 'l\'apéritif' },
        { id: 11, english: 'a starter / appetiser',         french: 'une entrée' },
        { id: 12, english: 'a main course',                 french: 'un plat principal' },
        { id: 13, english: 'dessert',                       french: 'le dessert' },
        { id: 14, english: 'a set menu',                    french: 'un menu' },
        { id: 15, english: 'a (à la carte) menu',           french: 'la carte' },
        { id: 16, english: 'a portion / serving',           french: 'une portion' },
        { id: 17, english: 'vegetarian',                    french: 'végétarien(ne)' },
        { id: 18, english: 'a regional speciality',         french: 'une spécialité' },
        { id: 19, english: 'terroir (local land and produce)', french: 'le terroir' },
        { id: 20, english: 'home-made',                     french: 'fait(e) maison' },
    ] },
    { level: 'A2', unit: 4,  id: 'health-doctor',           title: 'Health & Doctor',             titleFR: 'Santé & Médecin',               description: 'Medical vocabulary and doctor consultations',                descriptionFR: 'Vocabulaire médical et consultations chez le médecin',     icon: '🩺', color: '#DC2626', wordCount: 0, words: [
        { id: 1,  english: 'a doctor / GP',                 french: 'un médecin' },
        { id: 2,  english: 'a prescription',                french: 'une ordonnance' },
        { id: 3,  english: 'a medication / medicine',       french: 'un médicament' },
        { id: 4,  english: 'pain / an ache',                french: 'une douleur' },
        { id: 5,  english: 'a fever',                       french: 'la fièvre' },
        { id: 6,  english: 'a cold',                        french: 'un rhume' },
        { id: 7,  english: 'the flu / influenza',           french: 'la grippe' },
        { id: 8,  english: 'an allergy',                    french: 'une allergie' },
        { id: 9,  english: 'an injury / a wound',           french: 'une blessure' },
        { id: 10, english: 'A&E / emergency room',          french: 'les urgences' },
        { id: 11, english: 'a nurse',                       french: 'un(e) infirmier(-ière)' },
        { id: 12, english: 'an appointment',                french: 'un rendez-vous' },
        { id: 13, english: 'a symptom',                     french: 'un symptôme' },
        { id: 14, english: 'treatment',                     french: 'un traitement' },
        { id: 15, english: 'a tablet / pill',               french: 'un comprimé' },
        { id: 16, english: 'syrup / liquid medicine',       french: 'un sirop' },
        { id: 17, english: 'a plaster / bandage',           french: 'un pansement' },
        { id: 18, english: 'blood pressure',                french: 'la tension' },
        { id: 19, english: 'an X-ray / scan',               french: 'une radio' },
        { id: 20, english: 'an examination / check-up',     french: 'un examen' },
    ] },
    { level: 'A2', unit: 5,  id: 'personality-character',   title: 'Personality & Character',     titleFR: 'Personnalité & Caractère',      description: 'Describe personality traits and character',                  descriptionFR: 'Décrire les traits de personnalité et le caractère',       icon: '🧑', color: '#F97316', wordCount: 0, words: [
        { id: 1,  english: 'generous',     french: 'généreux(-euse)' },
        { id: 2,  english: 'shy / timid',  french: 'timide' },
        { id: 3,  english: 'brave / courageous', french: 'courageux(-euse)' },
        { id: 4,  english: 'patient',      french: 'patient(e)' },
        { id: 5,  english: 'curious',      french: 'curieux(-euse)' },
        { id: 6,  english: 'honest',       french: 'honnête' },
        { id: 7,  english: 'funny / amusing', french: 'drôle' },
        { id: 8,  english: 'serious',      french: 'sérieux(-euse)' },
        { id: 9,  english: 'creative',     french: 'créatif(-ive)' },
        { id: 10, english: 'ambitious',    french: 'ambitieux(-euse)' },
        { id: 11, english: 'lazy',         french: 'paresseux(-euse)' },
        { id: 12, english: 'chatty / talkative', french: 'bavard(e)' },
        { id: 13, english: 'discreet / reserved', french: 'discret(-ète)' },
        { id: 14, english: 'stubborn',     french: 'têtu(e)' },
        { id: 15, english: 'optimistic',   french: 'optimiste' },
        { id: 16, english: 'pessimistic',  french: 'pessimiste' },
        { id: 17, english: 'sociable',     french: 'sociable' },
        { id: 18, english: 'independent',  french: 'indépendant(e)' },
        { id: 19, english: 'sensitive',    french: 'sensible' },
        { id: 20, english: 'reliable / trustworthy', french: 'fiable' },
    ] },
    { level: 'A2', unit: 5,  id: 'seasons-activities',      title: 'Seasons & Activities',        titleFR: 'Saisons & Activités',           description: 'Seasonal vocabulary and leisure activities',                 descriptionFR: 'Vocabulaire saisonnier et activités de loisirs',           icon: '🍂', color: '#D97706', wordCount: 0, words: [
        { id: 1,  english: 'skiing',                        french: 'le ski' },
        { id: 2,  english: 'the beach',                     french: 'la plage' },
        { id: 3,  english: 'gardening',                     french: 'le jardinage' },
        { id: 4,  english: 'hiking / a hike',               french: 'la randonnée' },
        { id: 5,  english: 'a picnic',                      french: 'un pique-nique' },
        { id: 6,  english: 'swimming',                      french: 'la natation' },
        { id: 7,  english: 'cycling',                       french: 'le vélo' },
        { id: 8,  english: 'camping',                       french: 'le camping' },
        { id: 9,  english: 'Bastille Day (14 July)',         french: 'la fête nationale' },
        { id: 10, english: 'Christmas',                     french: 'Noël' },
        { id: 11, english: 'Easter',                        french: 'Pâques' },
        { id: 12, english: 'the grape harvest / vendanges', french: 'les vendanges' },
        { id: 13, english: 'back to school / September',    french: 'la rentrée' },
        { id: 14, english: 'school holidays',               french: 'les vacances scolaires' },
        { id: 15, english: 'a long weekend / bridge',       french: 'un pont' },
        { id: 16, english: 'a public holiday',              french: 'un jour férié' },
        { id: 17, english: 'the sales',                     french: 'les soldes' },
        { id: 18, english: 'a carnival',                    french: 'un carnaval' },
        { id: 19, english: 'Valentine\'s Day',              french: 'la Saint-Valentin' },
        { id: 20, english: 'Mother\'s Day',                 french: 'la fête des mères' },
    ] },
    { level: 'A2', unit: 3,  id: 'transport-travel',        title: 'Transport & Travel',          titleFR: 'Transport & Voyage',            description: 'Long-distance travel, airports and booking',                 descriptionFR: 'Voyages longue distance, aéroports et réservations',       icon: '✈️', color: '#2563EB', wordCount: 0, words: [
        { id: 1,  english: 'a ticket (train / plane)',       french: 'un billet' },
        { id: 2,  english: 'a booking / a reservation',      french: 'une réservation' },
        { id: 3,  english: 'a timetable / schedule',         french: 'un horaire' },
        { id: 4,  english: 'departure',                      french: 'le départ' },
        { id: 5,  english: 'arrival',                        french: 'l\'arrivée' },
        { id: 6,  english: 'a connection / transfer',        french: 'une correspondance' },
        { id: 7,  english: 'a delay',                        french: 'un retard' },
        { id: 8,  english: 'first class',                    french: 'la première classe' },
        { id: 9,  english: 'luggage / baggage',              french: 'les bagages' },
        { id: 10, english: 'a suitcase',                     french: 'une valise' },
        { id: 11, english: 'a passport',                     french: 'un passeport' },
        { id: 12, english: 'customs',                        french: 'la douane' },
        { id: 13, english: 'a flight',                       french: 'un vol' },
        { id: 14, english: 'boarding',                       french: 'l\'embarquement' },
        { id: 15, english: 'a stopover / layover',           french: 'une escale' },
        { id: 16, english: 'a seat',                         french: 'un siège' },
        { id: 17, english: 'a (train) carriage / car',       french: 'un wagon' },
        { id: 18, english: 'a ticket inspector / conductor', french: 'un contrôleur' },
        { id: 19, english: 'a cancellation',                 french: 'une annulation' },
        { id: 20, english: 'a refund',                       french: 'un remboursement' },
    ] },
    {
        level: 'A2', unit: 2, id: "a2-un-cadeau-pour-lucie",
        title: "Reading Vocabulary: Un cadeau pour Lucie",
        titleFR: "Vocabulaire de lecture : Un cadeau pour Lucie",
        description: "Words from the reading “Un cadeau pour Lucie”.",
        descriptionFR: "Vocabulaire du texte « Un cadeau pour Lucie ».",
        icon: '📚', color: '#2563EB', wordCount: 0, words: giftReadingWords,
    },
    {
        level: 'A2', unit: 4, id: "a2-un-diner-entre-amis",
        title: "Reading Vocabulary: Un dîner entre amis",
        titleFR: "Vocabulaire de lecture : Un dîner entre amis",
        description: "Words from the reading “Un dîner entre amis”.",
        descriptionFR: "Vocabulaire du texte « Un dîner entre amis ».",
        icon: '📚', color: '#2563EB', wordCount: 0, words: dinnerReadingWords,
    },

];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsA2: VocabularyData = {
    "a2-un-cadeau-pour-lucie": giftReadingWords,
    "a2-un-diner-entre-amis": dinnerReadingWords,
    'a2-une-journee-typique': [
        { id: 1, english: 'a student', french: 'une étudiante' },
        { id: 2, english: 'as usual', french: 'comme d\'habitude' },
        { id: 3, english: 'to take a shower', french: 'se doucher' },
        { id: 4, english: 'quickly', french: 'rapidement' },
        { id: 5, english: 'the news', french: 'les nouvelles' },
        { id: 6, english: 'the tram', french: 'le tram' },
        { id: 7, english: 'the university / faculty', french: 'la faculté' },
        { id: 8, english: 'to last', french: 'durer' },
        { id: 9, english: 'to explain', french: 'expliquer' },
        { id: 10, english: 'to concentrate', french: 'se concentrer' },
        { id: 11, english: 'to meet up with / to find again', french: 'retrouver' },
        { id: 12, english: 'an evening party / get-together', french: 'une soirée' },
        { id: 13, english: 'to invite', french: 'inviter' },
        { id: 14, english: 'the library', french: 'la bibliothèque' },
        { id: 15, english: 'a presentation / oral report', french: 'un exposé' },
    ],
    'a2-vacances-en-bretagne': [
        { id: 1, english: 'last summer', french: 'l\'été dernier' },
        { id: 2, english: 'to book / reserve', french: 'réserver' },
        { id: 3, english: 'a holiday cottage / gîte', french: 'un gîte' },
        { id: 4, english: 'the sea', french: 'la mer' },
        { id: 5, english: 'the journey / trip', french: 'le trajet' },
        { id: 6, english: 'to shine (the sun)', french: 'briller' },
        { id: 7, english: 'the beach', french: 'la plage' },
        { id: 8, english: 'to go for a swim / to bathe', french: 'se baigner' },
        { id: 9, english: 'the cliffs', french: 'les falaises' },
        { id: 10, english: 'the rocks', french: 'les rochers' },
        { id: 11, english: 'the fishing boats', french: 'des bateaux de pêche' },
        { id: 12, english: 'the crossing (by boat)', french: 'la traversée' },
        { id: 13, english: 'to rent / hire', french: 'louer' },
        { id: 14, english: 'hidden coves', french: 'des criques cachées' },
        { id: 15, english: 'seafood', french: 'les fruits de mer' },
    ],
    'a2-le-marche': [
        { id: 1, english: 'to go (to a place)', french: 'se rendre' },
        { id: 2, english: 'fresh produce', french: 'des produits frais' },
        { id: 3, english: 'local producers', french: 'les producteurs locaux' },
        { id: 4, english: 'to plan / to intend', french: 'prévoir' },
        { id: 5, english: 'seasonal vegetables', french: 'des légumes de saison' },
        { id: 6, english: 'the greengrocer / market gardener', french: 'le maraîcher' },
        { id: 7, english: 'the courgettes / zucchini', french: 'des courgettes' },
        { id: 8, english: 'the aubergines / eggplants', french: 'des aubergines' },
        { id: 9, english: 'the (bell) peppers', french: 'des poivrons' },
        { id: 10, english: 'the farm', french: 'la ferme' },
        { id: 11, english: 'organic', french: 'bio' },
        { id: 12, english: 'to pick / to harvest', french: 'cueillir' },
        { id: 13, english: 'olive oil', french: 'l\'huile d\'olive' },
        { id: 14, english: 'fresh herbs', french: 'des herbes fraîches' },
        { id: 15, english: 'a neighbour', french: 'une voisine' },
    ],
    'a2-une-lettre-damitie': [
        { id: 1, english: 'dear (to a woman)', french: 'chère' },
        { id: 2, english: 'I miss you', french: 'tu me manques' },
        { id: 3, english: 'since your departure', french: 'depuis ton départ' },
        { id: 4, english: 'a job / position', french: 'un poste' },
        { id: 5, english: 'to learn', french: 'apprendre' },
        { id: 6, english: 'the colleagues', french: 'les collègues' },
        { id: 7, english: 'the atmosphere / mood', french: 'l\'ambiance' },
        { id: 8, english: 'the city centre', french: 'le centre-ville' },
        { id: 9, english: 'an exhibition', french: 'une exposition' },
        { id: 10, english: 'to remind / to recall', french: 'rappeler' },
        { id: 11, english: 'to have a drink', french: 'prendre un verre' },
        { id: 12, english: 'a piece of news', french: 'une nouvelle' },
        { id: 13, english: 'then / next', french: 'puis' },
        { id: 14, english: 'to visit (someone)', french: 'rendre visite' },
        { id: 15, english: 'lots of love (closing)', french: 'grosses bises' },
    ],
    'a2-recette-francaise': [
        { id: 1, english: 'the apple tart', french: 'la tarte aux pommes' },
        { id: 2, english: 'appreciated / liked', french: 'apprécié' },
        { id: 3, english: 'the recipe', french: 'la recette' },
        { id: 4, english: 'to prepare / make', french: 'préparer' },
        { id: 5, english: 'the shortcrust pastry', french: 'la pâte brisée' },
        { id: 6, english: 'a tablespoon', french: 'une cuillère à soupe' },
        { id: 7, english: 'the sugar', french: 'le sucre' },
        { id: 8, english: 'the cinnamon', french: 'la cannelle' },
        { id: 9, english: 'the butter', french: 'le beurre' },
        { id: 10, english: 'to preheat', french: 'préchauffer' },
        { id: 11, english: 'the oven', french: 'le four' },
        { id: 12, english: 'to peel', french: 'éplucher' },
        { id: 13, english: 'thin slices', french: 'des fines lamelles' },
        { id: 14, english: 'a mould / baking tin', french: 'un moule' },
        { id: 15, english: 'to bake / cook', french: 'faire cuire' },
    ],
};
