import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

export const modulesB1: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'B1', unit: 1,  id: 'daily-life-advanced', title: 'Advanced Daily Life',     titleFR: 'Vie quotidienne avancée',    description: 'Everyday French at an advanced level',                           descriptionFR: 'Le français du quotidien à un niveau avancé',                   icon: '🏠', color: '#059669', wordCount: 0, words: [
        { id: 1, english: 'to complain / to gripe (about)', french: 'se plaindre (de)' },
        { id: 2, english: 'a misunderstanding / a mix-up', french: 'un quiproquo' },
        { id: 3, english: 'to manage / to get by on one\'s own', french: 'se débrouiller' },
        { id: 4, english: 'a lifestyle / a way of life', french: 'un mode de vie' },
        { id: 5, english: 'a habit / a routine (established over time)', french: 'une habitude' },
        { id: 6, english: 'a chore / an unwanted task', french: 'une corvée' },
        { id: 7, english: 'to get along well (with someone)', french: 's\'entendre (avec)' },
        { id: 8, english: 'to make ends meet / to get by financially', french: 'joindre les deux bouts' },
        { id: 9, english: 'to take advantage of / to make the most of', french: 'profiter de' },
        { id: 10, english: 'a setback / an unexpected hiccup', french: 'un contretemps' },
        { id: 11, english: 'a schedule / a timetable', french: 'un emploi du temps' },
        { id: 12, english: 'to sort out / to deal with (a matter)', french: 'régler' },
        { id: 13, english: 'an obligation / a commitment', french: 'une obligation' },
        { id: 14, english: 'frugal / thrifty', french: 'économe' },
        { id: 15, english: 'a household / a home (as a unit)', french: 'un foyer' },
        { id: 16, english: 'to fit in / to adapt to a new place', french: 's\'intégrer' },
        { id: 17, english: 'to put off / to postpone (a task)', french: 'remettre à plus tard' },
        { id: 18, english: 'a neighbourhood / a district', french: 'un quartier' },
        { id: 19, english: 'self-sufficient / autonomous', french: 'autonome' },
        { id: 20, english: 'to run errands / to do administrative tasks', french: 'faire des démarches' },
    ] },
    { level: 'B1', unit: 1,  id: 'emotions-psychology', title: 'Emotions & Psychology',   titleFR: 'Émotions & Psychologie',     description: 'Express feelings and mental states',                             descriptionFR: 'Exprimer ses émotions et états mentaux',                        icon: '💭', color: '#DC2626', wordCount: 0, words: [
        { id: 1, english: 'distrust / mistrust', french: 'la méfiance' },
        { id: 2, english: 'anguish / deep anxiety', french: 'l\'angoisse' },
        { id: 3, english: 'remorse / guilt after wrongdoing', french: 'le remords' },
        { id: 4, english: 'to mope / to brood / to languish', french: 'se morfondre' },
        { id: 5, english: 'fulfilled / flourishing (person)', french: 'épanoui(e)' },
        { id: 6, english: 'resentful / grudge-holding', french: 'rancunier(-ière)' },
        { id: 7, english: 'to overcome / to get over (a difficulty)', french: 'surmonter' },
        { id: 8, english: 'a grudge / a lasting resentment', french: 'une rancune' },
        { id: 9, english: 'empathy', french: 'l\'empathie' },
        { id: 10, english: 'overwhelmed / crushed (by grief or work)', french: 'accablé(e)' },
        { id: 11, english: 'to envy / to be jealous of', french: 'envier' },
        { id: 12, english: 'to reassure / to put someone\'s mind at ease', french: 'rassurer' },
        { id: 13, english: 'bitterness (emotional)', french: 'l\'amertume' },
        { id: 14, english: 'to be ashamed (of)', french: 'avoir honte (de)' },
        { id: 15, english: 'relief (from worry or pain)', french: 'le soulagement' },
        { id: 16, english: 'conflicted / torn (between two things)', french: 'tiraillé(e)' },
        { id: 17, english: 'to suppress / to repress (an emotion)', french: 'refouler' },
        { id: 18, english: 'melancholy / wistfulness', french: 'la mélancolie' },
        { id: 19, english: 'self-confidence / self-esteem', french: 'la confiance en soi' },
        { id: 20, english: 'vulnerable / emotionally fragile', french: 'vulnérable' },
    ] },
    { level: 'B1', unit: 3,  id: 'travel-culture',      title: 'Travel & Culture',        titleFR: 'Voyage & Culture',           description: 'Navigate travel and cultural topics',                            descriptionFR: 'Naviguer les sujets de voyage et de culture',                   icon: '✈️', color: '#2563EB', wordCount: 0, words: [
        { id: 1, english: 'heritage / cultural legacy', french: 'le patrimoine' },
        { id: 2, english: 'a stay / a trip (of several days)', french: 'un séjour' },
        { id: 3, english: 'to navigate / to find one\'s way around', french: 'se repérer' },
        { id: 4, english: 'the feeling of being abroad / of a change of scene', french: 'le dépaysement' },
        { id: 5, english: 'an itinerary / a travel plan', french: 'un itinéraire' },
        { id: 6, english: 'customs / traditions (of a people)', french: 'les us et coutumes' },
        { id: 7, english: 'a landmark / a point of reference', french: 'un repère' },
        { id: 8, english: 'to immerse oneself in (a culture)', french: 's\'immerger dans' },
        { id: 9, english: 'a layover / a stopover', french: 'une escale' },
        { id: 10, english: 'local gastronomy / regional cuisine', french: 'la gastronomie locale' },
        { id: 11, english: 'off the beaten track / away from tourist crowds', french: 'hors des sentiers battus' },
        { id: 12, english: 'jet lag', french: 'le décalage horaire' },
        { id: 13, english: 'a tour guide / a travel guide (person)', french: 'un guide touristique' },
        { id: 14, english: 'to blend in / to integrate into the local culture', french: 's\'intégrer à la culture locale' },
        { id: 15, english: 'the cost of living', french: 'le coût de la vie' },
        { id: 16, english: 'a cultural exchange', french: 'un échange culturel' },
        { id: 17, english: 'to get lost / to lose one\'s bearings', french: 'se perdre' },
        { id: 18, english: 'open-minded (about other cultures)', french: 'ouvert(e) d\'esprit' },
        { id: 19, english: 'a souvenir / a keepsake', french: 'un souvenir' },
        { id: 20, english: 'a must-see / an essential sight', french: 'un incontournable' },
    ] },
    { level: 'B1', unit: 4,  id: 'technology-media',    title: 'Technology & Media',      titleFR: 'Technologie & Médias',       description: 'The digital world in French',                                    descriptionFR: 'Le monde numérique en français',                                icon: '💻', color: '#A855F7', wordCount: 0, words: [
        { id: 1, english: 'a device / appliance', french: 'un appareil' },
        { id: 2, english: 'to download', french: 'télécharger' },
        { id: 3, english: 'to update (software)', french: 'mettre à jour' },
        { id: 4, english: 'an app / application', french: 'une application' },
        { id: 5, english: 'a social network', french: 'un réseau social' },
        { id: 6, english: 'a platform', french: 'une plateforme' },
        { id: 7, english: 'viral', french: 'viral(e)' },
        { id: 8, english: 'a notification', french: 'une notification' },
        { id: 9, english: 'cybersecurity', french: 'la cybersécurité' },
        { id: 10, english: 'a password', french: 'un mot de passe' },
        { id: 11, english: 'personal data', french: 'les données personnelles' },
        { id: 12, english: 'digital / the digital sphere', french: 'le numérique' },
        { id: 13, english: 'to stream live', french: 'diffuser en direct' },
        { id: 14, english: 'artificial intelligence', french: 'l\'intelligence artificielle' },
        { id: 15, english: 'automation', french: 'l\'automatisation' },
        { id: 16, english: 'an algorithm', french: 'un algorithme' },
        { id: 17, english: 'the cloud (computing)', french: 'le cloud' },
        { id: 18, english: 'a start-up', french: 'une start-up' },
        { id: 19, english: 'innovation', french: 'l\'innovation' },
        { id: 20, english: 'obsolete / outdated', french: 'obsolète' },
    ] },
    { level: 'B1', unit: 3,  id: 'art-culture',             title: 'Art & Culture',               titleFR: 'Art & Culture',                 description: 'Explore French art and cultural life',                       descriptionFR: 'Explorer l\'art et la vie culturelle française',            icon: '🎨', color: '#EC4899', wordCount: 0, words: [
        { id: 1,  english: 'a museum',                             french: 'un musée' },
        { id: 2,  english: 'an exhibition',                        french: 'une exposition' },
        { id: 3,  english: 'a painting / picture',                 french: 'un tableau' },
        { id: 4,  english: 'a sculpture',                          french: 'une sculpture' },
        { id: 5,  english: 'painting (as an art form)',            french: 'la peinture' },
        { id: 6,  english: 'an artist',                            french: 'un(e) artiste' },
        { id: 7,  english: 'a masterpiece',                        french: 'un chef-d\'œuvre' },
        { id: 8,  english: 'an art gallery',                       french: 'une galerie' },
        { id: 9,  english: 'a private view / opening night',       french: 'un vernissage' },
        { id: 10, english: 'a critic / review',                    french: 'une critique' },
        { id: 11, english: 'an artistic movement / style',         french: 'un courant artistique' },
        { id: 12, english: 'heritage / cultural legacy',           french: 'le patrimoine' },
        { id: 13, english: 'cinema / film',                        french: 'le cinéma' },
        { id: 14, english: 'a film director',                      french: 'un réalisateur / une réalisatrice' },
        { id: 15, english: 'a screenplay / script',                french: 'un scénario' },
        { id: 16, english: 'direction / staging (of a play)',      french: 'une mise en scène' },
        { id: 17, english: 'a festival',                           french: 'un festival' },
        { id: 18, english: 'a prize / award',                      french: 'un prix' },
        { id: 19, english: 'a concert',                            french: 'un concert' },
        { id: 20, english: 'a stage / performance space',          french: 'une scène' },
    ] },
    { level: 'B1', unit: 2,  id: 'environment-ecology',     title: 'Environment & Ecology',       titleFR: 'Environnement & Écologie',      description: 'Nature, ecology and environmental issues',                   descriptionFR: 'Nature, écologie et enjeux environnementaux',              icon: '🌍', color: '#059669', wordCount: 0, words: [
        { id: 1,  english: 'climate change',                      french: 'le réchauffement climatique' },
        { id: 2,  english: 'pollution',                            french: 'la pollution' },
        { id: 3,  english: 'renewable energy',                     french: 'l\'énergie renouvelable' },
        { id: 4,  english: 'biodiversity',                         french: 'la biodiversité' },
        { id: 5,  english: 'deforestation',                        french: 'la déforestation' },
        { id: 6,  english: 'recycling',                            french: 'le recyclage' },
        { id: 7,  english: 'carbon footprint',                     french: 'l\'empreinte carbone' },
        { id: 8,  english: 'sustainable development',              french: 'le développement durable' },
        { id: 9,  english: 'ecosystem',                            french: 'un écosystème' },
        { id: 10, english: 'endangered species',                   french: 'une espèce menacée' },
        { id: 11, english: 'the greenhouse effect',                french: 'l\'effet de serre' },
        { id: 12, english: 'fossil fuels',                         french: 'les énergies fossiles' },
        { id: 13, english: 'an oil spill',                         french: 'une marée noire' },
        { id: 14, english: 'waste / rubbish',                      french: 'les déchets' },
        { id: 15, english: 'composting',                           french: 'le compostage' },
        { id: 16, english: 'organic farming',                      french: 'l\'agriculture bio' },
        { id: 17, english: 'an NGO / non-governmental organisation', french: 'une ONG' },
        { id: 18, english: 'a demonstration / protest march',      french: 'une manifestation' },
        { id: 19, english: 'carbon balance / carbon accounting',   french: 'un bilan carbone' },
        { id: 20, english: 'energy transition',                    french: 'la transition énergétique' },
    ] },
    { level: 'B1', unit: 5,  id: 'health-lifestyle',        title: 'Health & Lifestyle',          titleFR: 'Santé & Mode de vie',           description: 'Wellbeing, fitness and healthy living',                      descriptionFR: 'Bien-être, forme physique et vie saine',                   icon: '🏃', color: '#16A34A', wordCount: 0, words: [
        { id: 1,  english: 'a balanced diet',                      french: 'une alimentation équilibrée' },
        { id: 2,  english: 'physical exercise',                    french: 'l\'exercice physique' },
        { id: 3,  english: 'sleep',                                french: 'le sommeil' },
        { id: 4,  english: 'stress',                               french: 'le stress' },
        { id: 5,  english: 'well-being / wellness',                french: 'le bien-être' },
        { id: 6,  english: 'meditation',                           french: 'la méditation' },
        { id: 7,  english: 'yoga',                                 french: 'le yoga' },
        { id: 8,  english: 'a sedentary lifestyle',                french: 'la sédentarité' },
        { id: 9,  english: 'addiction',                            french: 'une addiction' },
        { id: 10, english: 'prevention (of illness)',              french: 'la prévention' },
        { id: 11, english: 'hygiene',                              french: 'l\'hygiène' },
        { id: 12, english: 'screening / check-up',                 french: 'un dépistage' },
        { id: 13, english: 'vaccination',                          french: 'la vaccination' },
        { id: 14, english: 'a chronic illness',                    french: 'une maladie chronique' },
        { id: 15, english: 'remission (of a disease)',             french: 'une rémission' },
        { id: 16, english: 'recovery / cure',                      french: 'la guérison' },
        { id: 17, english: 'convalescence',                        french: 'la convalescence' },
        { id: 18, english: 'a diet / dietary regimen',             french: 'un régime' },
        { id: 19, english: 'smoking / tobacco use',                french: 'le tabagisme' },
        { id: 20, english: 'obesity',                              french: 'l\'obésité' },
    ] },
    { level: 'B1', unit: 4,  id: 'housing-urban',           title: 'Housing & Urban Life',        titleFR: 'Logement & Vie urbaine',        description: 'Housing, apartments and city living',                        descriptionFR: 'Logement, appartements et vie en ville',                   icon: '🏘️', color: '#84CC16', wordCount: 0, words: [
        { id: 1,  english: 'rent',                                 french: 'le loyer' },
        { id: 2,  english: 'a landlord / owner',                   french: 'un propriétaire' },
        { id: 3,  english: 'a tenant',                             french: 'un locataire' },
        { id: 4,  english: 'flat-sharing / house-sharing',         french: 'la colocation' },
        { id: 5,  english: 'service charges / utilities',          french: 'les charges' },
        { id: 6,  english: 'a neighbourhood / area',               french: 'un quartier' },
        { id: 7,  english: 'the suburbs',                          french: 'la banlieue' },
        { id: 8,  english: 'the city centre / downtown',           french: 'le centre-ville' },
        { id: 9,  english: 'social / council housing',             french: 'un logement social' },
        { id: 10, english: 'renovation / refurbishment',           french: 'une rénovation' },
        { id: 11, english: 'a residents\' association / building manager', french: 'un syndic' },
        { id: 12, english: 'a neighbourhood / neighbours (collective)', french: 'le voisinage' },
        { id: 13, english: 'noise',                                french: 'le bruit' },
        { id: 14, english: 'a lift / elevator',                    french: 'un ascenseur' },
        { id: 15, english: 'a cellar / basement',                  french: 'une cave' },
        { id: 16, english: 'an attic / loft',                      french: 'un grenier' },
        { id: 17, english: 'a car park / parking space',           french: 'un parking' },
        { id: 18, english: 'interior design / layout',             french: 'l\'aménagement' },
        { id: 19, english: 'moving house',                         french: 'un déménagement' },
        { id: 20, english: 'a property inventory / inspection report', french: 'un état des lieux' },
    ] },
    { level: 'B1', unit: 2,  id: 'media-news',              title: 'Media & News',                titleFR: 'Médias & Actualités',           description: 'Current affairs and news media vocabulary',                  descriptionFR: 'Actualités et vocabulaire des médias d\'information',      icon: '📡', color: '#0369A1', wordCount: 0, words: [
        { id: 1,  english: 'a newspaper',                          french: 'un journal' },
        { id: 2,  english: 'a (TV / radio) programme',             french: 'une émission' },
        { id: 3,  english: 'a (TV) channel',                       french: 'une chaîne' },
        { id: 4,  english: 'a presenter / host',                   french: 'un présentateur / une présentatrice' },
        { id: 5,  english: 'a news report / documentary',          french: 'un reportage' },
        { id: 6,  english: 'an interview',                         french: 'une interview' },
        { id: 7,  english: 'a poll / survey',                      french: 'un sondage' },
        { id: 8,  english: 'an article',                           french: 'un article' },
        { id: 9,  english: 'a section / column (in a paper)',      french: 'une rubrique' },
        { id: 10, english: 'a headline / title',                   french: 'un titre' },
        { id: 11, english: 'the front page',                       french: 'la une' },
        { id: 12, english: 'a news wire / dispatch',               french: 'une dépêche' },
        { id: 13, english: 'a press release',                      french: 'un communiqué de presse' },
        { id: 14, english: 'fake news / misinformation',           french: 'les fake news' },
        { id: 15, english: 'social media',                         french: 'les réseaux sociaux' },
        { id: 16, english: 'going viral',                          french: 'la viralité' },
        { id: 17, english: 'censorship',                           french: 'la censure' },
        { id: 18, english: 'freedom of the press',                 french: 'la liberté de la presse' },
        { id: 19, english: 'an editor / journalist',               french: 'un rédacteur / une rédactrice' },
        { id: 20, english: 'a subscription',                       french: 'un abonnement' },
    ] },
    { level: 'B1', unit: 4,  id: 'relationships-social',    title: 'Relationships & Social Life', titleFR: 'Relations & Vie sociale',       description: 'Social bonds, friendships and relationships',                descriptionFR: 'Liens sociaux, amitiés et relations',                      icon: '🤝', color: '#10B981', wordCount: 0, words: [
        { id: 1,  english: 'friendship',                           french: 'l\'amitié' },
        { id: 2,  english: 'trust',                                french: 'la confiance' },
        { id: 3,  english: 'a betrayal',                           french: 'une trahison' },
        { id: 4,  english: 'a reconciliation',                     french: 'une réconciliation' },
        { id: 5,  english: 'an argument / quarrel',                french: 'une dispute' },
        { id: 6,  english: 'support / backing',                    french: 'le soutien' },
        { id: 7,  english: 'jealousy',                             french: 'la jalousie' },
        { id: 8,  english: 'admiration',                           french: 'l\'admiration' },
        { id: 9,  english: 'respect',                              french: 'le respect' },
        { id: 10, english: 'closeness / complicity (between friends)', french: 'la complicité' },
        { id: 11, english: 'neighbourliness / being a good neighbour', french: 'le voisinage' },
        { id: 12, english: 'mutual aid / helping each other',      french: 'l\'entraide' },
        { id: 13, english: 'volunteering',                         french: 'le bénévolat' },
        { id: 14, english: 'a community',                          french: 'une communauté' },
        { id: 15, english: 'integration (into a community)',       french: 'l\'intégration' },
        { id: 16, english: 'diversity',                            french: 'la diversité' },
        { id: 17, english: 'a prejudice / bias',                   french: 'un préjugé' },
        { id: 18, english: 'solidarity',                           french: 'la solidarité' },
        { id: 19, english: 'empathy',                              french: 'l\'empathie' },
        { id: 20, english: 'tolerance',                            french: 'la tolérance' },
    ] },
];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsB1: VocabularyData = {
    'b1-une-histoire-de-famille': [
        { id: 1, english: 'a village', french: 'un village' },
        { id: 2, english: 'childhood', french: 'l\'enfance' },
        { id: 3, english: 'despite / in spite of', french: 'malgré' },
        { id: 4, english: 'a farmer', french: 'un agriculteur' },
        { id: 5, english: 'to work the land', french: 'travailler la terre' },
        { id: 6, english: 'the war', french: 'la guerre' },
        { id: 7, english: 'to break out (war)', french: 'éclater' },
        { id: 8, english: 'to remember', french: 'se souvenir' },
        { id: 9, english: 'the soldiers', french: 'les soldats' },
        { id: 10, english: 'gone to the front', french: 'parti au front' },
        { id: 11, english: 'to reassure', french: 'rassurer' },
        { id: 12, english: 'to move house', french: 'déménager' },
        { id: 13, english: 'a bookshop', french: 'une librairie' },
        { id: 14, english: 'to leaf through', french: 'feuilleter' },
        { id: 15, english: 'to pass away / to die', french: 'décéder' },
    ],
    'b1-le-travail-a-distance': [
        { id: 1, english: 'remote work / working from home', french: 'le télétravail' },
        { id: 2, english: 'to take hold / to establish itself', french: 's\'imposer' },
        { id: 3, english: 'companies / firms', french: 'les entreprises' },
        { id: 4, english: 'the employees', french: 'les salariés' },
        { id: 5, english: 'the supporters / advocates', french: 'les partisans' },
        { id: 6, english: 'to highlight / to emphasise', french: 'mettre en avant' },
        { id: 7, english: 'public transport', french: 'les transports en commun' },
        { id: 8, english: 'exhausting / tiring', french: 'épuisant' },
        { id: 9, english: 'gains in productivity', french: 'des gains de productivité' },
        { id: 10, english: 'to sacrifice', french: 'sacrifier' },
        { id: 11, english: 'to complain', french: 'se plaindre' },
        { id: 12, english: 'isolation', french: 'l\'isolement' },
        { id: 13, english: 'the boundaries', french: 'les frontières' },
        { id: 14, english: 'a balance', french: 'un équilibre' },
        { id: 15, english: 'a divide / rift', french: 'une fracture' },
    ],
    'b1-voyage-en-provence': [
        { id: 1, english: 'the lavender', french: 'la lavande' },
        { id: 2, english: 'the plateau', french: 'le plateau' },
        { id: 3, english: 'to stretch out / extend', french: 's\'étendre' },
        { id: 4, english: 'as far as the eye can see', french: 'à perte de vue' },
        { id: 5, english: 'intoxicating / heady', french: 'enivrant' },
        { id: 6, english: 'the heat', french: 'la chaleur' },
        { id: 7, english: 'a renovated sheepfold', french: 'une bergerie rénovée' },
        { id: 8, english: 'the owner / landlady', french: 'la propriétaire' },
        { id: 9, english: 'a welcome basket', french: 'un panier de bienvenue' },
        { id: 10, english: 'goat\'s cheese', french: 'le fromage de chèvre' },
        { id: 11, english: 'the (lavender at its) peak', french: 'le pic' },
        { id: 12, english: 'candied fruits', french: 'des fruits confits' },
        { id: 13, english: 'the spices', french: 'les épices' },
        { id: 14, english: 'a stew (Provençal beef)', french: 'une daube' },
        { id: 15, english: 'simmered / slow-cooked', french: 'mijoté' },
    ],
    'b1-interview-artiste': [
        { id: 1, english: 'to exhibit / display', french: 'exposer' },
        { id: 2, english: 'the paintings', french: 'les tableaux' },
        { id: 3, english: 'a gallery', french: 'une galerie' },
        { id: 4, english: 'the canvases', french: 'les toiles' },
        { id: 5, english: 'to blend / mix', french: 'mêler' },
        { id: 6, english: 'oil painting', french: 'la peinture à l\'huile' },
        { id: 7, english: 'a portrait', french: 'un portrait' },
        { id: 8, english: 'the studio / workshop', french: 'l\'atelier' },
        { id: 9, english: 'to grow up', french: 'grandir' },
        { id: 10, english: 'the attic / loft', french: 'le grenier' },
        { id: 11, english: 'to inspire', french: 'inspirer' },
        { id: 12, english: 'to capture / catch', french: 'capter' },
        { id: 13, english: 'a piece of advice', french: 'un conseil' },
        { id: 14, english: 'to please / to be liked', french: 'plaire' },
        { id: 15, english: 'disturbing / unsettling', french: 'dérangeant' },
    ],
    'b1-une-lettre-a-ami': [
        { id: 1, english: 'dear (to a man)', french: 'cher' },
        { id: 2, english: 'to settle / to move in', french: 's\'installer' },
        { id: 3, english: 'to confess / to admit', french: 'avouer' },
        { id: 4, english: 'lively / full of life', french: 'vivant' },
        { id: 5, english: 'time flies', french: 'le temps file' },
        { id: 6, english: 'to close down (a shop)', french: 'fermer' },
        { id: 7, english: 'to replace', french: 'remplacer' },
        { id: 8, english: 'to frequent / to go to often', french: 'fréquenter' },
        { id: 9, english: 'a flat-share / house-share', french: 'une colocation' },
        { id: 10, english: 'a hassle / a struggle', french: 'une galère' },
        { id: 11, english: 'a training course', french: 'une formation' },
        { id: 12, english: 'exhausting / tiring', french: 'épuisant' },
        { id: 13, english: 'the intention', french: 'l\'intention' },
        { id: 14, english: 'to suit / to be convenient', french: 'convenir' },
        { id: 15, english: 'fluently', french: 'couramment' },
    ],
    'b1-article-jeunesse': [
        { id: 1, english: 'the youth / young people', french: 'la jeunesse' },
        { id: 2, english: 'a report (document)', french: 'un rapport' },
        { id: 3, english: 'the values', french: 'les valeurs' },
        { id: 4, english: 'the concerns / worries', french: 'les préoccupations' },
        { id: 5, english: 'deeply / profoundly', french: 'profondément' },
        { id: 6, english: 'the relationship to work', french: 'le rapport au travail' },
        { id: 7, english: 'their elders', french: 'leurs aînés' },
        { id: 8, english: 'to value / to prize', french: 'valoriser' },
        { id: 9, english: 'personal fulfilment', french: 'l\'épanouissement personnel' },
        { id: 10, english: 'flexibility', french: 'la flexibilité' },
        { id: 11, english: 'aware / sensitised', french: 'sensibilisé' },
        { id: 12, english: 'climate change', french: 'le changement climatique' },
        { id: 13, english: 'consumer choices', french: 'des choix de consommation' },
        { id: 14, english: 'weakened / made fragile', french: 'fragilisé' },
        { id: 15, english: 'job insecurity / precariousness', french: 'la précarité' },
    ],
    'b1-temoignage-expatrie': [
        { id: 1, english: 'an attachment / a tie', french: 'une attache' },
        { id: 2, english: 'the desire for elsewhere', french: 'l\'envie d\'ailleurs' },
        { id: 3, english: 'to break / to crush', french: 'briser' },
        { id: 4, english: 'the wind', french: 'le vent' },
        { id: 5, english: 'a knife', french: 'un couteau' },
        { id: 6, english: 'crying / in tears', french: 'en pleurant' },
        { id: 7, english: 'to hold on / to endure', french: 'tenir' },
        { id: 8, english: 'the spring', french: 'le printemps' },
        { id: 9, english: 'human warmth', french: 'la chaleur humaine' },
        { id: 10, english: 'a country cottage / chalet', french: 'un chalet' },
        { id: 11, english: 'to laugh', french: 'rire' },
        { id: 12, english: 'a floating / shifting identity', french: 'une identité flottante' },
        { id: 13, english: 'to worry (someone)', french: 'inquiéter' },
        { id: 14, english: 'a richness / an asset', french: 'une richesse' },
        { id: 15, english: 'to live between two cultures', french: 'vivre entre deux cultures' },
    ],
};
