import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

export const modulesC1: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'C1', unit: 1,  id: 'idioms-expressions',  title: 'Idioms & Expressions',    titleFR: 'Idiomes & Expressions',      description: 'Figurative French that cannot be translated literally',           descriptionFR: 'Le français figuré qui ne se traduit pas littéralement',         icon: '🎭', color: '#9333EA', wordCount: 0, words: [
        { id: 1, english: 'to feel down / to be blue', french: 'avoir le cafard' },
        { id: 2, english: 'to stand someone up', french: 'poser un lapin (à quelqu\'un)' },
        { id: 3, english: 'to get on someone\'s nerves / to be a pain', french: 'casser les pieds (à quelqu\'un)' },
        { id: 4, english: 'to fall in love at first sight', french: 'avoir le coup de foudre' },
        { id: 5, english: 'to put one\'s foot in it / to blunder', french: 'mettre les pieds dans le plat' },
        { id: 6, english: 'to faint / to pass out', french: 'tomber dans les pommes' },
        { id: 7, english: 'to have bigger fish to fry (lit: other cats to whip)', french: 'avoir d\'autres chats à fouetter' },
        { id: 8, english: 'to grab a quick bite / to eat on the go', french: 'manger sur le pouce' },
        { id: 9, english: 'to have a lie-in / to sleep late', french: 'faire la grasse matinée' },
        { id: 10, english: 'to dodge the issue / to muddy the waters', french: 'noyer le poisson' },
        { id: 11, english: 'to beat around the bush', french: 'tourner autour du pot' },
        { id: 12, english: 'to have a lot on one\'s plate / a lot of work ahead', french: 'avoir du pain sur la planche' },
        { id: 13, english: 'to make ends meet more comfortably / to supplement one\'s income', french: 'mettre du beurre dans les épinards' },
        { id: 14, english: 'to worm something out of someone', french: 'tirer les vers du nez (à quelqu\'un)' },
        { id: 15, english: 'to have connections / to have pull', french: 'avoir le bras long' },
        { id: 16, english: 'to use every means available / to make the most of what one has', french: 'faire feu de tout bois' },
        { id: 17, english: 'to make a run for it / to scarper', french: 'prendre la poudre d\'escampette' },
        { id: 18, english: 'to have a quick tongue / to never be at a loss for words', french: 'ne pas avoir la langue dans sa poche' },
        { id: 19, english: 'don\'t count your chickens before they hatch', french: 'il ne faut pas vendre la peau de l\'ours avant de l\'avoir tué' },
        { id: 20, english: 'to have eyes bigger than one\'s stomach', french: 'avoir les yeux plus grands que le ventre' },
    ] },
    { level: 'C1', unit: 3,  id: 'faux-amis',           title: 'Faux Amis',               titleFR: 'Faux Amis',                  description: "False friends — words that look English but aren't",             descriptionFR: "Mots qui ressemblent à l'anglais mais ne le sont pas",           icon: '⚠️', color: '#DC2626', wordCount: 0, words: [
        { id: 1, english: 'currently / at the moment (NOT "actually")', french: 'actuellement' },
        { id: 2, english: 'possibly / if need be (NOT "eventually")', french: 'éventuellement' },
        { id: 3, english: 'sensitive / delicate (NOT "sensible")', french: 'sensible' },
        { id: 4, english: 'to claim / to assert (NOT "to pretend")', french: 'prétendre' },
        { id: 5, english: 'to be unaware of / not to know (NOT "to ignore deliberately")', french: 'ignorer' },
        { id: 6, english: 'to attend / to be present at (NOT "to assist")', french: 'assister à' },
        { id: 7, english: 'to disappoint (NOT "to deceive")', french: 'décevoir' },
        { id: 8, english: 'nice / friendly / likeable (NOT "sympathetic")', french: 'sympathique' },
        { id: 9, english: 'change / currency / coins (NOT "money" in general)', french: 'la monnaie' },
        { id: 10, english: 'a diary / planner (NOT "an agenda/plan")', french: 'un agenda' },
        { id: 11, english: 'an opportunity / a bargain (NOT just "an occasion")', french: 'une occasion' },
        { id: 12, english: 'a nickname (NOT "a surname")', french: 'un surnom' },
        { id: 13, english: 'reading (NOT "a lecture")', french: 'la lecture' },
        { id: 14, english: 'wide / broad (NOT "large")', french: 'large' },
        { id: 15, english: 'the cellar / basement (NOT "a cave")', french: 'la cave' },
        { id: 16, english: 'to injure / to hurt / to wound (NOT "to bless")', french: 'blesser' },
        { id: 17, english: 'a coach / long-distance bus (NOT "a car")', french: 'un car' },
        { id: 18, english: 'to stay / to remain (NOT "to rest")', french: 'rester' },
        { id: 19, english: 'a bookshop / bookstore (NOT "a library")', french: 'une librairie' },
        { id: 20, english: 'uninhabitable / unfit to live in (NOT "habitable" — a trap for English speakers!)', french: 'inhabitable' },
    ] },
    { level: 'C1', unit: 3,  id: 'literary-abstract',   title: 'Literary & Abstract',     titleFR: 'Littéraire & Abstrait',      description: 'Vocabulary from literature and elevated discourse',               descriptionFR: 'Vocabulaire littéraire et du discours soutenu',                  icon: '📜', color: '#6366F1', wordCount: 0, words: [
        { id: 1, english: 'the unspeakable / what cannot be put into words', french: 'l\'indicible' },
        { id: 2, english: 'chimerical / fantastical / illusory', french: 'chimérique' },
        { id: 3, english: 'ineffable / inexpressible (beyond words)', french: 'ineffable' },
        { id: 4, english: 'cryptic / sibylline / deliberately obscure', french: 'sibyllin(e)' },
        { id: 5, english: 'the quintessence / the purest essence', french: 'la quintessence' },
        { id: 6, english: 'irresolute / full of half-formed intentions / lacking follow-through', french: 'velléitaire' },
        { id: 7, english: 'the ephemeral / what is fleeting or short-lived', french: 'l\'éphémère' },
        { id: 8, english: 'unfathomable / bottomless / impenetrable', french: 'insondable' },
        { id: 9, english: 'incomplete / full of gaps / fragmentary', french: 'lacunaire' },
        { id: 10, english: 'dichotomy / a split into two opposing parts', french: 'la dichotomie' },
        { id: 11, english: 'harmful / deleterious / having a damaging effect', french: 'délétère' },
        { id: 12, english: 'striking / vivid / loaded with meaning', french: 'prégnant(e)' },
        { id: 13, english: 'incandescent / blazing / glowing with passion or emotion', french: 'incandescent(e)' },
        { id: 14, english: 'to blossom / to flourish / to come into one\'s own', french: 's\'épanouir' },
        { id: 15, english: 'ambivalence / having conflicting feelings simultaneously', french: 'l\'ambivalence' },
        { id: 16, english: 'deeply distressing / harrowing / fraught with anxiety', french: 'angoissant(e)' },
        { id: 17, english: 'perishable / transient / not lasting', french: 'périssable' },
        { id: 18, english: 'hubris / overweening pride leading to downfall', french: 'l\'hubris' },
        { id: 19, english: 'introspection / the examination of one\'s own thoughts and feelings', french: 'l\'introspection' },
        { id: 20, english: 'ostentatious / showy / done for effect', french: 'ostentatoire' },
    ] },
    { level: 'C1', unit: 5,  id: 'nuanced-adjectives',  title: 'Nuanced Adjectives',      titleFR: 'Adjectifs nuancés',          description: 'Precise adjectives for character and description',                descriptionFR: 'Adjectifs précis pour le caractère et la description',           icon: '🎯', color: '#0891B2', wordCount: 0, words: [
        { id: 1, english: 'trivial / harmless / innocuous / run-of-the-mill', french: 'anodin(e)' },
        { id: 2, english: 'ambiguous / equivocal / open to two interpretations', french: 'équivoque' },
        { id: 3, english: 'fallacious / specious / misleading', french: 'fallacieux(-euse)' },
        { id: 4, english: 'acerbic / sharp / cutting (of remarks or tone)', french: 'acerbe' },
        { id: 5, english: 'laconic / terse / using very few words', french: 'laconique' },
        { id: 6, english: 'vehement / impassioned / forceful', french: 'véhément(e)' },
        { id: 7, english: 'sly / underhand / devious', french: 'sournois(e)' },
        { id: 8, english: 'naive / guileless / innocently trusting', french: 'candide' },
        { id: 9, english: 'convoluted / over-elaborate / unnecessarily complex', french: 'alambiqué(e)' },
        { id: 10, english: 'prolix / verbose / excessively wordy', french: 'prolixe' },
        { id: 11, english: 'perspicacious / shrewd / having keen insight', french: 'perspicace' },
        { id: 12, english: 'circumspect / cautious / wary', french: 'circonspect(e)' },
        { id: 13, english: 'inept / absurd / utterly foolish', french: 'inepte' },
        { id: 14, english: 'fiery / impetuous / full of ardour', french: 'fougueux(-euse)' },
        { id: 15, english: 'fierce / wild / (also) intensely shy or unsociable', french: 'farouche' },
        { id: 16, english: 'unflappable / imperturbable / calmly unmoved', french: 'imperturbable' },
        { id: 17, english: 'quick to take offence / prickly / touchy', french: 'ombrageux(-euse)' },
        { id: 18, english: 'perfidious / treacherous / falsely loyal', french: 'perfide' },
        { id: 19, english: 'clear-headed / lucid / unsentimental about reality', french: 'lucide' },
        { id: 20, english: 'uncompromising / intransigent / unwilling to concede', french: 'intransigeant(e)' },
    ] },
    { level: 'C1', unit: 2,  id: 'law-administration',  title: 'Law & Administration',    titleFR: 'Droit & Administration',     description: 'Legal, judicial and administrative vocabulary',                   descriptionFR: 'Vocabulaire juridique et administratif',                         icon: '⚖️', color: '#475569', wordCount: 0, words: [
        { id: 1, english: 'a decree / an executive order', french: 'un décret' },
        { id: 2, english: 'an ordinance / a court order (also: a prescription)', french: 'une ordonnance' },
        { id: 3, english: 'case law / jurisprudence / legal precedent', french: 'la jurisprudence' },
        { id: 4, english: 'an appeal / a recourse / a legal remedy', french: 'un recours' },
        { id: 5, english: 'an official order / a by-law / an administrative decision', french: 'un arrêté' },
        { id: 6, english: 'a formal notice / a letter before action', french: 'la mise en demeure' },
        { id: 7, english: 'guardianship / trusteeship / (state) supervision', french: 'la tutelle' },
        { id: 8, english: 'to promulgate / to enact (a law)', french: 'promulguer' },
        { id: 9, english: 'an exemption / a waiver / a special dispensation', french: 'une dérogation' },
        { id: 10, english: 'contentious / disputed / subject to litigation', french: 'litigieux(-euse)' },
        { id: 11, english: 'harm / prejudice / loss or damage (legal)', french: 'un préjudice' },
        { id: 12, english: 'to plead / to argue (a case in court)', french: 'plaider' },
        { id: 13, english: 'a plea / the closing argument (in court)', french: 'la plaidoirie' },
        { id: 14, english: 'to reoffend / to relapse into criminal behaviour', french: 'récidiver' },
        { id: 15, english: 'an acquittal / a not-guilty verdict', french: 'un acquittement' },
        { id: 16, english: 'inadmissible / not admissible (evidence, claim)', french: 'irrecevable' },
        { id: 17, english: 'contentious / of or relating to legal disputes; (n.) disputes department', french: 'contentieux(-euse)' },
        { id: 18, english: 'the presumption of innocence', french: 'la présomption d\'innocence' },
        { id: 19, english: 'an injunction', french: 'une injonction' },
        { id: 20, english: 'customary law / common law', french: 'le droit coutumier' },
    ] },
    { level: 'C1', unit: 5,  id: 'human-condition',         title: 'The Human Condition',         titleFR: 'La Condition humaine',          description: 'Philosophy, ethics and the language of ideas',               descriptionFR: 'Philosophie, éthique et langage des idées',                icon: '🧠', color: '#4F46E5', wordCount: 0, words: [
        { id: 1, english: 'alienation / a sense of estrangement from oneself or society', french: 'l\'aliénation' },
        { id: 2, english: 'contingency / the fact that things could have been otherwise', french: 'la contingence' },
        { id: 3, english: 'free will', french: 'le libre arbitre' },
        { id: 4, english: 'determinism / the view that all events are causally determined', french: 'le déterminisme' },
        { id: 5, english: 'authenticity / being true to oneself', french: 'l\'authenticité' },
        { id: 6, english: 'transcendence / going beyond ordinary limits', french: 'la transcendance' },
        { id: 7, english: 'paradox / an apparently contradictory truth', french: 'le paradoxe' },
        { id: 8, english: 'ideology / a system of ideas underpinning a political stance', french: 'l\'idéologie' },
        { id: 9, english: 'the search for meaning / the quest for purpose', french: 'la quête de sens' },
        { id: 10, english: 'the absurd / the conflict between human need for meaning and a silent universe', french: 'l\'absurde' },
        { id: 11, english: 'to question oneself / to challenge one\'s own assumptions', french: 'se remettre en question' },
        { id: 12, english: 'the human condition', french: 'la condition humaine' },
        { id: 13, english: 'altruism / selfless concern for others', french: 'l\'altruisme' },
        { id: 14, english: 'duality / the state of having two opposite parts', french: 'la dualité' },
        { id: 15, english: 'relativism / the view that truth is not absolute', french: 'le relativisme' },
        { id: 16, english: 'epistemology / the branch of philosophy concerned with knowledge', french: 'l\'épistémologie' },
        { id: 17, english: 'phenomenology / the study of conscious experience', french: 'la phénoménologie' },
        { id: 18, english: 'nihilism / the rejection of all meaning and moral principles', french: 'le nihilisme' },
        { id: 19, english: 'immanence / existing within rather than beyond the world', french: 'l\'immanence' },
        { id: 20, english: 'existentialism / the philosophy emphasising individual freedom and responsibility', french: 'l\'existentialisme' },
    ] },
    { level: 'C1', unit: 4,  id: 'aesthetics-criticism',    title: 'Aesthetics & Criticism',      titleFR: 'Esthétique & Critique',         description: 'Language of artistic taste and critical analysis',           descriptionFR: 'Langage du goût artistique et de l\'analyse critique',     icon: '🖼️', color: '#9333EA', wordCount: 0, words: [
        { id: 1,  english: 'aesthetics',                                 french: 'l\'esthétique' },
        { id: 2,  english: 'a critique / a critical review',             french: 'une critique' },
        { id: 3,  english: 'a style / a register',                       french: 'un style' },
        { id: 4,  english: 'harmonious',                                 french: 'harmonieux(-euse)' },
        { id: 5,  english: 'to interpret / to construe',                 french: 'interpréter' },
        { id: 6,  english: 'sublime',                                    french: 'sublime' },
        { id: 7,  english: 'a motif / a recurring theme',                french: 'un motif' },
        { id: 8,  english: 'to depict / to portray',                     french: 'dépeindre' },
        { id: 9,  english: 'an allegory',                                french: 'une allégorie' },
        { id: 10, english: 'avant-garde',                                french: 'avant-gardiste' },
        { id: 11, english: 'to evoke / to conjure up',                   french: 'évoquer' },
        { id: 12, english: 'an oeuvre / a body of work',                 french: 'une œuvre' },
        { id: 13, english: 'to symbolize',                               french: 'symboliser' },
        { id: 14, english: 'austere / stark',                            french: 'austère' },
        { id: 15, english: 'a composition / an arrangement',             french: 'une composition' },
        { id: 16, english: 'to transcend / to go beyond',                french: 'transcender' },
        { id: 17, english: 'an artifact / a cultural object',            french: 'un artefact' },
        { id: 18, english: 'minimalist',                                 french: 'minimaliste' },
        { id: 19, english: 'to convey / to express (an idea)',           french: 'transmettre' },
        { id: 20, english: 'a paradigm / a model',                       french: 'un paradigme' },
    ] },
    { level: 'C1', unit: 4,  id: 'history-civilisation',    title: 'History & Civilisation',      titleFR: 'Histoire & Civilisation',       description: 'Key vocabulary for historical and civilisational topics',   descriptionFR: 'Vocabulaire clé pour les sujets historiques et civilisationnels', icon: '🏛️', color: '#78716C', wordCount: 0, words: [
        { id: 1,  english: 'civilization',                               french: 'la civilisation' },
        { id: 2,  english: 'an era / an age',                            french: 'une ère' },
        { id: 3,  english: 'an empire',                                  french: 'un empire' },
        { id: 4,  english: 'a dynasty',                                  french: 'une dynastie' },
        { id: 5,  english: 'a conquest',                                 french: 'une conquête' },
        { id: 6,  english: 'a revolution',                               french: 'une révolution' },
        { id: 7,  english: 'to colonize',                                french: 'coloniser' },
        { id: 8,  english: 'a legacy / an inheritance',                  french: 'un héritage' },
        { id: 9,  english: 'a chronicle / an account',                   french: 'une chronique' },
        { id: 10, english: 'feudal',                                     french: 'féodal(e)' },
        { id: 11, english: 'an archetype / a founding figure',           french: 'un archétype' },
        { id: 12, english: 'to decline / to fall into decay',            french: 'décliner' },
        { id: 13, english: 'sovereignty',                                french: 'la souveraineté' },
        { id: 14, english: 'an alliance',                                french: 'une alliance' },
        { id: 15, english: 'a schism / a split',                         french: 'un schisme' },
        { id: 16, english: 'a renaissance / a rebirth',                  french: 'une renaissance' },
        { id: 17, english: 'a treaty',                                   french: 'un traité' },
        { id: 18, english: 'to commemorate',                             french: 'commémorer' },
        { id: 19, english: 'an epoch / a period',                        french: 'une époque' },
        { id: 20, english: 'a monument / a landmark',                    french: 'un monument' },
    ] },
    { level: 'C1', unit: 1,  id: 'rhetoric-argumentation',  title: 'Rhetoric & Argumentation',    titleFR: 'Rhétorique & Argumentation',    description: 'The art of persuasion and structured argument',              descriptionFR: 'L\'art de la persuasion et de l\'argumentation structurée',icon: '🗣️', color: '#B45309', wordCount: 0, words: [
        { id: 1,  english: 'rhetoric',                                   french: 'la rhétorique' },
        { id: 2,  english: 'to argue / to make a case',                  french: 'argumenter' },
        { id: 3,  english: 'a thesis',                                   french: 'une thèse' },
        { id: 4,  english: 'a counter-argument',                         french: 'un contre-argument' },
        { id: 5,  english: 'persuasion',                                 french: 'la persuasion' },
        { id: 6,  english: 'a premise',                                  french: 'une prémisse' },
        { id: 7,  english: 'to refute / to disprove',                    french: 'réfuter' },
        { id: 8,  english: 'a fallacy / a sophism',                      french: 'un sophisme' },
        { id: 9,  english: 'concise',                                    french: 'concis(e)' },
        { id: 10, english: 'to assert / to claim',                       french: 'affirmer' },
        { id: 11, english: 'a nuance',                                   french: 'une nuance' },
        { id: 12, english: 'to elaborate / to develop (an idea)',         french: 'développer' },
        { id: 13, english: 'a stance / a position',                      french: 'une position' },
        { id: 14, english: 'to qualify / to nuance (a statement)',        french: 'nuancer' },
        { id: 15, english: 'irony',                                      french: 'l\'ironie' },
        { id: 16, english: 'an analogy',                                 french: 'une analogie' },
        { id: 17, english: 'to undermine / to weaken (an argument)',      french: 'saper' },
        { id: 18, english: 'coherent / consistent',                      french: 'cohérent(e)' },
        { id: 19, english: 'a postulate / an axiom',                     french: 'un postulat' },
        { id: 20, english: 'to demonstrate / to prove',                  french: 'démontrer' },
    ] },
    { level: 'C1', unit: 2,  id: 'science-philosophy',      title: 'Philosophy of Science',       titleFR: 'Philosophie des sciences',      description: 'Epistemology and the language of scientific thought',       descriptionFR: 'Épistémologie et langage de la pensée scientifique',       icon: '🔬', color: '#0F766E', wordCount: 0, words: [
        { id: 1,  english: 'epistemology / the theory of knowledge',     french: 'l\'épistémologie' },
        { id: 2,  english: 'empirical / based on observation',           french: 'empirique' },
        { id: 3,  english: 'a hypothesis',                               french: 'une hypothèse' },
        { id: 4,  english: 'to theorize / to formulate a theory',        french: 'théoriser' },
        { id: 5,  english: 'a paradox',                                  french: 'un paradoxe' },
        { id: 6,  english: 'consciousness / awareness',                  french: 'la conscience' },
        { id: 7,  english: 'ontology / the study of being',              french: 'l\'ontologie' },
        { id: 8,  english: 'pragmatic / practical',                      french: 'pragmatique' },
        { id: 9,  english: 'dialectic / a dialectical debate',           french: 'la dialectique' },
        { id: 10, english: 'rationalism',                                french: 'le rationalisme' },
        { id: 11, english: 'to falsify / to disprove (a theory)',        french: 'falsifier' },
        { id: 12, english: 'empiricism',                                 french: 'l\'empirisme' },
        { id: 13, english: 'a dogma',                                    french: 'un dogme' },
        { id: 14, english: 'phenomenology',                              french: 'la phénoménologie' },
        { id: 15, english: 'subjective',                                 french: 'subjectif(-ive)' },
        { id: 16, english: 'to abstract / to think abstractly',          french: 'abstraire' },
        { id: 17, english: 'a theorem',                                  french: 'un théorème' },
        { id: 18, english: 'axiomatic / self-evident',                   french: 'axiomatique' },
        { id: 19, english: 'determinism',                                french: 'le déterminisme' },
        { id: 20, english: 'a conjecture / an educated guess',           french: 'une conjecture' },
    ] },
];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsC1: VocabularyData = {
    'c1-discours-politique': [
        { id: 1, english: 'at a crossroads', french: 'à la croisée des chemins' },
        { id: 2, english: 'born from the ashes', french: 'né des cendres' },
        { id: 3, english: 'to embody', french: 'incarner' },
        { id: 4, english: 'lasting peace', french: 'une paix durable' },
        { id: 5, english: 'to lay bare / expose', french: 'mettre à nu' },
        { id: 6, english: 'structural tensions', french: 'les tensions structurelles' },
        { id: 7, english: 'supranational', french: 'supranational' },
        { id: 8, english: 'the rise of populisms', french: 'la montée des populismes' },
        { id: 9, english: 'distrust / mistrust', french: 'la défiance' },
        { id: 10, english: 'technocratic', french: 'technocratique' },
        { id: 11, english: 'disconnected / out of touch', french: 'déconnecté' },
        { id: 12, english: 'globalisation', french: 'la mondialisation' },
        { id: 13, english: 'a rift / fracture', french: 'une fracture' },
        { id: 14, english: 'to deepen (integration)', french: 'l\'approfondissement' },
        { id: 15, english: 'stagnation / immobility', french: 'l\'immobilisme' },
    ],
    'c1-article-philosophique': [
        { id: 1, english: 'human freedom', french: 'la liberté humaine' },
        { id: 2, english: 'determinisms', french: 'des déterminismes' },
        { id: 3, english: 'to escape (us) / to elude', french: 'échapper' },
        { id: 4, english: 'the foundations', french: 'les fondements' },
        { id: 5, english: 'morality', french: 'la morale' },
        { id: 6, english: 'individual responsibility', french: 'la responsabilité individuelle' },
        { id: 7, english: 'a causal chain', french: 'une chaîne causale' },
        { id: 8, english: 'unbroken / uninterrupted', french: 'ininterrompu' },
        { id: 9, english: 'irremediably', french: 'irrémédiablement' },
        { id: 10, english: 'a consoling fiction', french: 'une fiction consolatrice' },
        { id: 11, english: 'to deliberate', french: 'délibérer' },
        { id: 12, english: 'to hesitate', french: 'hésiter' },
        { id: 13, english: 'condemned to be free', french: 'condamné à être libre' },
        { id: 14, english: 'compatibilist', french: 'compatibiliste' },
        { id: 15, english: 'an external constraint', french: 'une contrainte extérieure' },
    ],
    'c1-moliere-extract': [
        { id: 1, english: 'enamoured of / deeply fond of', french: 'épris de' },
        { id: 2, english: 'sincerity', french: 'la sincérité' },
        { id: 3, english: 'accommodating / easy-going', french: 'accommodant' },
        { id: 4, english: 'to reproach / to criticise', french: 'reprocher' },
        { id: 5, english: 'to greet warmly', french: 'saluer chaleureusement' },
        { id: 6, english: 'to lavish / bestow', french: 'prodiguer' },
        { id: 7, english: 'social hypocrisy', french: 'l\'hypocrisie sociale' },
        { id: 8, english: 'moral corruption', french: 'la corruption morale' },
        { id: 9, english: 'propriety / decorum', french: 'la bienséance' },
        { id: 10, english: 'to disguise', french: 'déguiser' },
        { id: 11, english: 'cowardice', french: 'la lâcheté' },
        { id: 12, english: 'compromise / collusion', french: 'la compromission' },
        { id: 13, english: 'to settle / to decide (an issue)', french: 'trancher' },
        { id: 14, english: 'moral rigour', french: 'la rigueur morale' },
        { id: 15, english: 'unbearable', french: 'insupportable' },
    ],
    'c1-camus-etranger': [
        { id: 1, english: 'a telegram', french: 'un télégramme' },
        { id: 2, english: 'the care home / asylum', french: 'l\'asile' },
        { id: 3, english: 'deceased', french: 'décédée' },
        { id: 4, english: 'the burial / funeral', french: 'l\'enterrement' },
        { id: 5, english: 'the opening lines / incipit', french: 'l\'incipit' },
        { id: 6, english: 'a radical strangeness', french: 'une étrangeté radicale' },
        { id: 7, english: 'indifference', french: 'l\'indifférence' },
        { id: 8, english: 'cruelty', french: 'la cruauté' },
        { id: 9, english: 'an inability', french: 'une incapacité' },
        { id: 10, english: 'to assign (a role)', french: 'assigner' },
        { id: 11, english: 'sensory precision', french: 'une précision sensorielle' },
        { id: 12, english: 'blinding (light)', french: 'aveuglant' },
        { id: 13, english: 'cut off from', french: 'coupé de' },
        { id: 14, english: 'the dissociation', french: 'la dissociation' },
        { id: 15, english: 'the absurd', french: 'l\'absurde' },
    ],
    'c1-voltaire-candide': [
        { id: 1, english: 'naivety / innocence', french: 'la naïveté' },
        { id: 2, english: 'raised / brought up', french: 'élevé' },
        { id: 3, english: 'the castle', french: 'le château' },
        { id: 4, english: 'the tutor / preceptor', french: 'le précepteur' },
        { id: 5, english: 'the best of all possible worlds', french: 'le meilleur des mondes possibles' },
        { id: 6, english: 'a conviction / belief', french: 'une conviction' },
        { id: 7, english: 'a satire', french: 'une satire' },
        { id: 8, english: 'to be put to the test', french: 'être mis à l\'épreuve' },
        { id: 9, english: 'a philosophical tale', french: 'un conte philosophique' },
        { id: 10, english: 'far-fetched / fantastical', french: 'rocambolesque' },
        { id: 11, english: 'scathing / virulent', french: 'virulent' },
        { id: 12, english: 'slavery', french: 'l\'esclavage' },
        { id: 13, english: 'divine providence', french: 'la providence divine' },
        { id: 14, english: 'to cultivate one\'s garden', french: 'cultiver son jardin' },
        { id: 15, english: 'a resigned retreat', french: 'un repli résigné' },
    ],
    'c1-roman-contemporain': [
        { id: 1, english: 'memories of photos', french: 'des souvenirs de photos' },
        { id: 2, english: 'mental images', french: 'des images mentales' },
        { id: 3, english: 'to bring forth / to call up', french: 'faire surgir' },
        { id: 4, english: 'a procedure / technique', french: 'un procédé' },
        { id: 5, english: 'the very nature', french: 'la nature même' },
        { id: 6, english: 'fragmentary', french: 'fragmentaire' },
        { id: 7, english: 'the third person', french: 'la troisième personne' },
        { id: 8, english: 'to substitute', french: 'substituer' },
        { id: 9, english: 'modesty', french: 'la modestie' },
        { id: 10, english: 'an ambition', french: 'une ambition' },
        { id: 11, english: 'the mirror', french: 'le miroir' },
        { id: 12, english: 'an entire generation', french: 'une génération entière' },
        { id: 13, english: 'set phrases / fixed expressions', french: 'des formules figées' },
        { id: 14, english: 'a historical document', french: 'un document historique' },
        { id: 15, english: 'without daring to', french: 'sans oser' },
    ],
    'c1-essai-identite': [
        { id: 1, english: 'the identity', french: 'l\'identité' },
        { id: 2, english: 'the origins', french: 'les origines' },
        { id: 3, english: 'received identity', french: 'l\'identité reçue' },
        { id: 4, english: 'constructed identity', french: 'l\'identité construite' },
        { id: 5, english: 'to run through / to pervade', french: 'traverser' },
        { id: 6, english: 'essentialist', french: 'essentialiste' },
        { id: 7, english: 'a stable essence', french: 'une essence stable' },
        { id: 8, english: 'belonging / membership', french: 'l\'appartenance' },
        { id: 9, english: 'to fuel / to feed', french: 'alimenter' },
        { id: 10, english: 'solidarity', french: 'la solidarité' },
        { id: 11, english: 'dynamic and relational', french: 'dynamique et relationnelle' },
        { id: 12, english: 'to remain faithful to', french: 'rester fidèle à' },
        { id: 13, english: 'a commitment / promise', french: 'un engagement' },
        { id: 14, english: 'a given / a fixed fact', french: 'un donné' },
        { id: 15, english: 'to inhabit a history', french: 'habiter une histoire' },
    ],
    'c1-reportage-social': [
        { id: 1, english: 'a township / municipality', french: 'une commune' },
        { id: 2, english: 'a GP / general practitioner', french: 'un médecin généraliste' },
        { id: 3, english: 'to retire', french: 'prendre sa retraite' },
        { id: 4, english: 'to give up / forgo (care)', french: 'renoncer' },
        { id: 5, english: 'a medical desert', french: 'un désert médical' },
        { id: 6, english: 'rural areas', french: 'les zones rurales' },
        { id: 7, english: 'working-class suburbs', french: 'les banlieues populaires' },
        { id: 8, english: 'to worsen considerably', french: 's\'aggraver' },
        { id: 9, english: 'graduates', french: 'les diplômés' },
        { id: 10, english: 'a vocation / calling', french: 'une vocation' },
        { id: 11, english: 'the incentives', french: 'les incitations' },
        { id: 12, english: 'an underserved area', french: 'une zone sous-dotée' },
        { id: 13, english: 'a delay in diagnosis', french: 'un retard au diagnostic' },
        { id: 14, english: 'a territorial divide', french: 'une fracture territoriale' },
        { id: 15, english: 'telemedicine', french: 'la télémédecine' },
    ],
    'c1-article-presse-specialisee': [
        { id: 1, english: 'a ruling / a court decision', french: 'un arrêt' },
        { id: 2, english: 'to de-list / to de-reference', french: 'déréférencer' },
        { id: 3, english: 'the right to be forgotten', french: 'le droit à l\'oubli' },
        { id: 4, english: 'to open a Pandora\'s box', french: 'ouvrir une boîte de Pandore' },
        { id: 5, english: 'the implications', french: 'les implications' },
        { id: 6, english: 'an intuition', french: 'une intuition' },
        { id: 7, english: 'to define (someone) indefinitely', french: 'définir indéfiniment' },
        { id: 8, english: 'youthful mistakes', french: 'des erreurs de jeunesse' },
        { id: 9, english: 'search engines', french: 'les moteurs de recherche' },
        { id: 10, english: 'freedom of information', french: 'la liberté d\'information' },
        { id: 11, english: 'collective memory', french: 'la mémoire collective' },
        { id: 12, english: 'democratic transparency', french: 'la transparence démocratique' },
        { id: 13, english: 'to come into force', french: 'entrer en vigueur' },
        { id: 14, english: 'the erasure / deletion', french: 'l\'effacement' },
        { id: 15, english: 'a fragile balance', french: 'un équilibre fragile' },
    ],
};
