import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

export const modulesC2: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'C2', unit: 1,  id: 'abstract-thought',        title: 'Abstract Thought',            titleFR: 'Pensée abstraite',              description: 'Vocabulary for abstract reasoning and ideas',                descriptionFR: 'Vocabulaire pour le raisonnement abstrait et les idées',   icon: '💡', color: '#6366F1', wordCount: 0, words: [
        { id: 1,  english: 'teleology / the study of purpose and ends',         french: 'la téléologie' },
        { id: 2,  english: 'eschatology / the study of ultimate fate',          french: 'l\'eschatologie' },
        { id: 3,  english: 'synthesis / a higher unity of opposites',           french: 'la synthèse' },
        { id: 4,  english: 'antinomy / an irresolvable contradiction',          french: 'une antinomie' },
        { id: 5,  english: 'aporia / a philosophical impasse',                  french: 'une aporie' },
        { id: 6,  english: 'tautology / a needless repetition of an idea',      french: 'une tautologie' },
        { id: 7,  english: 'an axiom / a self-evident truth',                   french: 'un axiome' },
        { id: 8,  english: 'a corollary / a natural consequence',               french: 'un corollaire' },
        { id: 9,  english: 'induction / reasoning from specific to general',    french: 'l\'induction' },
        { id: 10, english: 'deduction / reasoning from general to specific',    french: 'la déduction' },
        { id: 11, english: 'abduction / inference to the best explanation',     french: 'l\'abduction' },
        { id: 12, english: 'falsifiability / the capacity to be disproved',     french: 'la falsifiabilité' },
        { id: 13, english: 'reductionism / reducing complex things to simpler parts', french: 'le réductionnisme' },
        { id: 14, english: 'holism / treating a system as a whole',             french: 'le holisme' },
        { id: 15, english: 'emergence / properties arising from complexity',    french: 'l\'émergence' },
        { id: 16, english: 'complexity (systems theory)',                        french: 'la complexité' },
        { id: 17, english: 'a thought experiment',                              french: 'une expérience de pensée' },
        { id: 18, english: 'transcendence / going beyond given limits',         french: 'la transcendance' },
        { id: 19, english: 'immanence / existing within the world',             french: 'l\'immanence' },
        { id: 20, english: 'a priori / known before experience',                french: 'a priori' },
    ] },
    { level: 'C2', unit: 2,  id: 'cultural-references',     title: 'Cultural References',         titleFR: 'Références culturelles',        description: 'Key cultural touchstones of the French-speaking world',     descriptionFR: 'Références culturelles clés du monde francophone',         icon: '🗼', color: '#2563EB', wordCount: 0, words: [
        { id: 1,  english: 'Cartesian / logical and methodically rational',      french: 'cartésien(ne)' },
        { id: 2,  english: 'the Enlightenment (intellectual movement)',          french: 'les Lumières' },
        { id: 3,  english: 'Haussmannization / Haussmann\'s urban renovation',  french: 'l\'haussmannisation' },
        { id: 4,  english: 'the Commune / the Paris Commune of 1871',           french: 'la Commune' },
        { id: 5,  english: 'May 68 / the student revolt of May 1968',           french: 'mai 68' },
        { id: 6,  english: 'the Veil law / the 1975 law legalizing abortion',   french: 'la loi Veil' },
        { id: 7,  english: 'the Thirty Glorious Years / France\'s postwar boom',french: 'les Trente Glorieuses' },
        { id: 8,  english: 'the cultural exception / France\'s cultural policy', french: 'l\'exception culturelle' },
        { id: 9,  english: 'the Grand Century / Louis XIV\'s reign',            french: 'le Grand Siècle' },
        { id: 10, english: 'the Encyclopedists / Diderot\'s circle',            french: 'les Encyclopédistes' },
        { id: 11, english: 'laïcité / French secular republicanism',            french: 'la laïcité' },
        { id: 12, english: 'la Francophonie / the French-speaking world',       french: 'la Francophonie' },
        { id: 13, english: 'the grandes écoles / elite French institutions',    french: 'les grandes écoles' },
        { id: 14, english: 'the Académie française / guardian of the French language', french: 'l\'Académie française' },
        { id: 15, english: 'the Fifth Republic / France\'s current political system', french: 'la Cinquième République' },
        { id: 16, english: 'the Jacobin tradition / centralism and universalism', french: 'la tradition jacobine' },
        { id: 17, english: 'the Occupation / France under Nazi occupation 1940–44', french: 'l\'Occupation' },
        { id: 18, english: 'the Resistance / the French Resistance movement',   french: 'la Résistance' },
        { id: 19, english: 'the Declaration of the Rights of Man (1789)',       french: 'la Déclaration des droits de l\'homme' },
        { id: 20, english: 'the Élysée Palace / the French president\'s residence', french: 'l\'Élysée' },
    ] },
    { level: 'C2', unit: 3,  id: 'literary-movements',      title: 'Literary Movements',          titleFR: 'Mouvements littéraires',        description: 'Vocabulary for major literary schools and movements',        descriptionFR: 'Vocabulaire des grandes écoles et mouvements littéraires', icon: '📖', color: '#4338CA', wordCount: 0, words: [
        { id: 1,  english: 'classicism / 17th-century order and harmony',       french: 'le classicisme' },
        { id: 2,  english: 'préciosité / refined 17th-century salon culture',   french: 'la préciosité' },
        { id: 3,  english: 'baroque / ornate and dramatic style',               french: 'le baroque' },
        { id: 4,  english: 'Romanticism / 19th-century emotion and nature',     french: 'le romantisme' },
        { id: 5,  english: 'Realism / faithful depiction of everyday life',     french: 'le réalisme' },
        { id: 6,  english: 'Naturalism / scientific approach to human life',    french: 'le naturalisme' },
        { id: 7,  english: 'Symbolism / suggestion over direct statement',      french: 'le symbolisme' },
        { id: 8,  english: 'Dadaism / anti-art movement of World War I',        french: 'le dadaïsme' },
        { id: 9,  english: 'Surrealism / unconscious and dreams in art',        french: 'le surréalisme' },
        { id: 10, english: 'Existentialism / freedom, anguish, and choice',     french: 'l\'existentialisme' },
        { id: 11, english: 'the nouveau roman / anti-traditional French novel', french: 'le nouveau roman' },
        { id: 12, english: 'OuLiPo / literature under formal constraints',      french: 'l\'OuLiPo' },
        { id: 13, english: 'négritude / Black cultural and political movement', french: 'la négritude' },
        { id: 14, english: 'autofiction / autobiographical fiction',            french: 'l\'autofiction' },
        { id: 15, english: 'the French detective novel',                        french: 'le roman policier' },
        { id: 16, english: 'Francophone literature',                            french: 'la littérature francophone' },
        { id: 17, english: 'a literary manifesto',                              french: 'un manifeste littéraire' },
        { id: 18, english: 'a literary movement / a school of thought',         french: 'un mouvement littéraire' },
        { id: 19, english: 'the avant-garde',                                   french: 'l\'avant-garde' },
        { id: 20, english: 'intertextuality / dialogue between texts',          french: 'l\'intertextualité' },
    ] },
    { level: 'C2', unit: 3,  id: 'nuanced-emotion',         title: 'Nuanced Emotions',            titleFR: 'Émotions nuancées',             description: 'Subtle and complex emotional vocabulary',                    descriptionFR: 'Vocabulaire émotionnel subtil et complexe',                icon: '💫', color: '#8B5CF6', wordCount: 0, words: [
        { id: 1,  english: 'melancholy / a pensive sadness',                    french: 'la mélancolie' },
        { id: 2,  english: 'nostalgia / a wistful longing for the past',        french: 'la nostalgie' },
        { id: 3,  english: 'spleen / Baudelairean ennui and existential boredom', french: 'le spleen' },
        { id: 4,  english: 'languor / a pleasant, dreamy weariness',            french: 'la langueur' },
        { id: 5,  english: 'disenchantment / a loss of idealism',               french: 'le désenchantement' },
        { id: 6,  english: 'dread / a deep, visceral fear',                     french: 'l\'effroi' },
        { id: 7,  english: 'stupefaction / complete astonishment',              french: 'la stupéfaction' },
        { id: 8,  english: 'serenity / a calm and peaceful state',              french: 'la sérénité' },
        { id: 9,  english: 'appeasement / a calming of tension',                french: 'l\'apaisement' },
        { id: 10, english: 'emotional upheaval / a devastating disruption',     french: 'le bouleversement' },
        { id: 11, english: 'exaltation / a heightened feeling of joy or pride', french: 'l\'exaltation' },
        { id: 12, english: 'rapture / an ecstatic delight',                     french: 'le ravissement' },
        { id: 13, english: 'pique / irritated disappointment',                  french: 'le dépit' },
        { id: 14, english: 'magnanimity / noble generosity of spirit',          french: 'la magnanimité' },
        { id: 15, english: 'contrition / deep remorse for wrongdoing',          french: 'la contrition' },
        { id: 16, english: 'deference / respectful submission to another',      french: 'la déférence' },
        { id: 17, english: 'veneration / deep reverence',                       french: 'la vénération' },
        { id: 18, english: 'poignancy / a bittersweet, deeply moving quality',  french: 'le déchirement' },
        { id: 19, english: 'foreboding / a sense of impending doom',            french: 'le pressentiment' },
        { id: 20, english: 'elation / a feeling of great happiness',            french: 'l\'allégresse' },
    ] },
    { level: 'C2', unit: 4,  id: 'philosophical-vocabulary',title: 'Philosophical Vocabulary',    titleFR: 'Vocabulaire philosophique',     description: 'Core terms from philosophy and critical thinking',           descriptionFR: 'Termes fondamentaux de la philosophie et de la pensée critique', icon: '🤔', color: '#7C3AED', wordCount: 0, words: [
        { id: 1,  english: 'hermeneutics / the theory of interpretation',       french: 'l\'herméneutique' },
        { id: 2,  english: 'Hegelian dialectic / thesis, antithesis, synthesis',french: 'la dialectique hégélienne' },
        { id: 3,  english: 'maieutics / the Socratic method of drawing out truth', french: 'la maïeutique' },
        { id: 4,  english: 'the cogito / Descartes\' "I think, therefore I am"', french: 'le cogito' },
        { id: 5,  english: 'tabula rasa / the mind as a blank slate at birth',  french: 'la tabula rasa' },
        { id: 6,  english: 'will to power / Nietzsche\'s drive for self-mastery', french: 'la volonté de puissance' },
        { id: 7,  english: 'élan vital / Bergson\'s life force',                french: 'l\'élan vital' },
        { id: 8,  english: 'bad faith / Sartrean self-deception',               french: 'la mauvaise foi' },
        { id: 9,  english: 'authenticity / being true to one\'s existence',     french: 'l\'authenticité' },
        { id: 10, english: 'finitude / the condition of being mortal and limited', french: 'la finitude' },
        { id: 11, english: 'intentionality / consciousness directed at an object', french: 'l\'intentionnalité' },
        { id: 12, english: 'deconstruction / Derrida\'s dismantling of binary oppositions', french: 'la déconstruction' },
        { id: 13, english: 'logocentrism / the privileging of speech over writing', french: 'le logocentrisme' },
        { id: 14, english: 'différance / Derrida\'s term for meaning\'s deferral', french: 'la différance' },
        { id: 15, english: 'alterity / otherness / the condition of being other', french: 'l\'altérité' },
        { id: 16, english: 'being-for-itself / Sartrean conscious existence',   french: 'l\'être-pour-soi' },
        { id: 17, english: 'being-in-itself / Sartrean non-conscious existence', french: 'l\'être-en-soi' },
        { id: 18, english: 'intersubjectivity / shared subjective experience',  french: 'l\'intersubjectivité' },
        { id: 19, english: 'phenomenology / study of conscious experience',     french: 'la phénoménologie' },
        { id: 20, english: 'a priori / known independently of experience',      french: 'a priori' },
    ] },
    { level: 'C2', unit: 2,  id: 'poetry-prosody',          title: 'Poetry & Prosody',            titleFR: 'Poésie & Prosodie',             description: 'The vocabulary of poetic form and verse',                    descriptionFR: 'Le vocabulaire de la forme poétique et du vers',           icon: '✍️', color: '#DB2777', wordCount: 0, words: [
        { id: 1,  english: 'an alexandrine / 12-syllable French verse line',    french: 'un alexandrin' },
        { id: 2,  english: 'a sonnet',                                          french: 'un sonnet' },
        { id: 3,  english: 'a tercet / a three-line stanza',                    french: 'un tercet' },
        { id: 4,  english: 'a quatrain / a four-line stanza',                   french: 'un quatrain' },
        { id: 5,  english: 'rhyme',                                             french: 'la rime' },
        { id: 6,  english: 'assonance / repeated vowel sounds',                 french: 'l\'assonance' },
        { id: 7,  english: 'alliteration / repeated consonant sounds',          french: 'l\'allitération' },
        { id: 8,  english: 'a caesura / a mid-line pause',                      french: 'une césure' },
        { id: 9,  english: 'enjambment / a run-on line',                        french: 'un enjambement' },
        { id: 10, english: 'anaphora / repetition at the start of lines',       french: 'une anaphore' },
        { id: 11, english: 'a chiasmus / an inverted parallel structure',       french: 'un chiasme' },
        { id: 12, english: 'an ellipsis / deliberate omission',                 french: 'une ellipse' },
        { id: 13, english: 'metonymy / naming by an associated attribute',      french: 'une métonymie' },
        { id: 14, english: 'synecdoche / part for whole or whole for part',     french: 'une synecdoque' },
        { id: 15, english: 'zeugma / linking two elements with one word',       french: 'un zeugme' },
        { id: 16, english: 'a prose poem',                                      french: 'un poème en prose' },
        { id: 17, english: 'free verse / verse without fixed metre',            french: 'le vers libre' },
        { id: 18, english: 'a stanza',                                          french: 'une strophe' },
        { id: 19, english: 'a couplet / a two-line stanza',                     french: 'un distique' },
        { id: 20, english: 'blank verse / unrhymed regular verse',              french: 'le vers blanc' },
    ] },
    { level: 'C2', unit: 4,  id: 'rhetoric-classical',      title: 'Classical Rhetoric',          titleFR: 'Rhétorique classique',          description: 'Figures of speech and classical rhetorical devices',        descriptionFR: 'Figures de style et procédés rhétoriques classiques',      icon: '📜', color: '#92400E', wordCount: 0, words: [
        { id: 1,  english: 'dispositio / the arrangement of arguments',         french: 'la dispositio' },
        { id: 2,  english: 'inventio / the finding of arguments',               french: 'l\'inventio' },
        { id: 3,  english: 'elocutio / style and word choice',                  french: 'l\'élocution' },
        { id: 4,  english: 'actio / delivery and physical performance',         french: 'l\'actio' },
        { id: 5,  english: 'memoria / the memorization of a speech',            french: 'la memoria' },
        { id: 6,  english: 'logos / argumentation based on logic',              french: 'le logos' },
        { id: 7,  english: 'ethos / credibility of the speaker',                french: 'l\'ethos' },
        { id: 8,  english: 'pathos / appeal to the emotions of the audience',   french: 'le pathos' },
        { id: 9,  english: 'epidictic / ceremonial rhetoric (praise/blame)',     french: 'l\'épidictique' },
        { id: 10, english: 'deliberative / political rhetoric (advise/dissuade)', french: 'le délibératif' },
        { id: 11, english: 'amplification / rhetorical intensification',        french: 'l\'amplification' },
        { id: 12, english: 'captatio benevolentiae / winning the audience\'s goodwill', french: 'la captatio benevolentiae' },
        { id: 13, english: 'a peroration / the closing section of a speech',   french: 'la péroraison' },
        { id: 14, english: 'an exordium / the opening section of a speech',    french: 'l\'exorde' },
        { id: 15, english: 'a narratio / the narrative portion of a speech',   french: 'la narratio' },
        { id: 16, english: 'confirmatio / the proof or argument section',       french: 'la confirmatio' },
        { id: 17, english: 'refutation / countering opposing arguments',        french: 'la réfutation' },
        { id: 18, english: 'concession / admitting the opponent\'s point',      french: 'la concession' },
        { id: 19, english: 'a rhetorical figure / a figure of speech',         french: 'une figure de rhétorique' },
        { id: 20, english: 'eloquence / the power of effective expression',    french: 'l\'éloquence' },
    ] },
    { level: 'C2', unit: 4,  id: 'specialized-register',    title: 'Specialized Register',        titleFR: 'Registre spécialisé',           description: 'Technical and domain-specific French vocabulary',            descriptionFR: 'Vocabulaire technique et spécifique à un domaine',         icon: '🎓', color: '#4F46E5', wordCount: 0, words: [
        { id: 1,  english: 'legal (register)',                                  french: 'juridique' },
        { id: 2,  english: 'medical (register)',                                french: 'médical(e)' },
        { id: 3,  english: 'scientific (register)',                             french: 'scientifique' },
        { id: 4,  english: 'diplomatic',                                        french: 'diplomatique' },
        { id: 5,  english: 'administrative',                                    french: 'administratif(-ive)' },
        { id: 6,  english: 'journalistic',                                      french: 'journalistique' },
        { id: 7,  english: 'academic',                                          french: 'académique' },
        { id: 8,  english: 'literary',                                          french: 'littéraire' },
        { id: 9,  english: 'colloquial / informal',                             french: 'familier(-ière)' },
        { id: 10, english: 'slang',                                             french: 'l\'argot' },
        { id: 11, english: 'verlan / French back-slang',                        french: 'le verlan' },
        { id: 12, english: 'Creole',                                            french: 'le créole' },
        { id: 13, english: 'Franglais / French mixed with English',             french: 'le franglais' },
        { id: 14, english: 'a neologism / a newly coined word',                 french: 'un néologisme' },
        { id: 15, english: 'a calque / a loan translation',                     french: 'un calque' },
        { id: 16, english: 'a loanword / a word borrowed from another language', french: 'un emprunt lexical' },
        { id: 17, english: 'purism / insistence on linguistic purity',          french: 'le purisme' },
        { id: 18, english: 'a linguistic norm / a standard of usage',           french: 'une norme linguistique' },
        { id: 19, english: 'usage / the way language is actually used',         french: 'l\'usage' },
        { id: 20, english: 'a register / a level of formality',                 french: 'un registre' },
    ] },
];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsC2: VocabularyData = {
    'c2-proust-extract': [
        { id: 1, english: 'against my habit / contrary to my custom', french: 'contre mon habitude' },
        { id: 2, english: 'to change one\'s mind', french: 'se raviser' },
        { id: 3, english: 'plump / chubby (cakes)', french: 'dodus' },
        { id: 4, english: 'to mould / to cast', french: 'mouler' },
        { id: 5, english: 'a scallop shell', french: 'une coquille de Saint-Jacques' },
        { id: 6, english: 'mechanically / absent-mindedly', french: 'machinalement' },
        { id: 7, english: 'overwhelmed / weighed down', french: 'accablé' },
        { id: 8, english: 'a spoonful', french: 'une cuillerée' },
        { id: 9, english: 'to soften / to grow soft', french: 's\'amollir' },
        { id: 10, english: 'the palate', french: 'le palais' },
        { id: 11, english: 'to shudder / to start', french: 'tressaillir' },
        { id: 12, english: 'the vicissitudes / ups and downs', french: 'les vicissitudes' },
        { id: 13, english: 'illusory brevity', french: 'la brièveté illusoire' },
        { id: 14, english: 'a precious essence', french: 'une essence précieuse' },
        { id: 15, english: 'involuntary memory', french: 'la mémoire involontaire' },
    ],
    'c2-hugo-les-miserables': [
        { id: 1, english: 'the prison / penal colony', french: 'le bagne' },
        { id: 2, english: 'to be sentenced / condemned', french: 'être condamné' },
        { id: 3, english: 'to steal', french: 'voler' },
        { id: 4, english: 'starving / famished', french: 'affamé' },
        { id: 5, english: 'freed / released', french: 'libéré' },
        { id: 6, english: 'to wander / roam', french: 'errer' },
        { id: 7, english: 'driven out / chased away', french: 'chassé' },
        { id: 8, english: 'the bishop', french: 'l\'évêque' },
        { id: 9, english: 'a guest', french: 'un hôte' },
        { id: 10, english: 'to give in to temptation', french: 'céder à une tentation' },
        { id: 11, english: 'the silver cutlery', french: 'les couverts en argent' },
        { id: 12, english: 'the police officers / gendarmes', french: 'les gendarmes' },
        { id: 13, english: 'unheard-of / extraordinary', french: 'inouï' },
        { id: 14, english: 'the candlesticks', french: 'les chandeliers' },
        { id: 15, english: 'a gesture of grace / mercy', french: 'un geste de grâce' },
    ],
    'c2-beauvoir-deuxieme-sexe': [
        { id: 1, english: 'one becomes (a woman)', french: 'on le devient' },
        { id: 2, english: 'a biological destiny', french: 'un destin biologique' },
        { id: 3, english: 'to take on / to assume (a form)', french: 'revêtir' },
        { id: 4, english: 'to develop / to work out', french: 'élaborer' },
        { id: 5, english: 'the mediation of others', french: 'la médiation d\'autrui' },
        { id: 6, english: 'the Other (philosophy)', french: 'un Autre' },
        { id: 7, english: 'femininity', french: 'la féminité' },
        { id: 8, english: 'a natural given', french: 'une donnée naturelle' },
        { id: 9, english: 'a social construction', french: 'une construction sociale' },
        { id: 10, english: 'injunctions / commands', french: 'des injonctions' },
        { id: 11, english: 'to shape / to fashion', french: 'façonner' },
        { id: 12, english: 'existence precedes essence', french: 'l\'existence précède l\'essence' },
        { id: 13, english: 'a fixed nature', french: 'une nature figée' },
        { id: 14, english: 'to confine / to lock into', french: 'enfermer' },
        { id: 15, english: 'power relations', french: 'des rapports de pouvoir' },
    ],
    'c2-sartre-huis-clos': [
        { id: 1, english: 'to stage / to put on (a play)', french: 'mettre en scène' },
        { id: 2, english: 'shut in / confined', french: 'enfermé' },
        { id: 3, english: 'for eternity', french: 'pour l\'éternité' },
        { id: 4, english: 'the harsh light', french: 'la lumière crue' },
        { id: 5, english: 'an executioner / torturer', french: 'un bourreau' },
        { id: 6, english: 'a line / a (theatrical) cue', french: 'une réplique' },
        { id: 7, english: 'hell is other people', french: 'l\'enfer, c\'est les autres' },
        { id: 8, english: 'misunderstood', french: 'mal compris' },
        { id: 9, english: 'the gaze of others', french: 'le regard d\'autrui' },
        { id: 10, english: 'to freeze / to fix (someone)', french: 'figer' },
        { id: 11, english: 'to dispossess of', french: 'déposséder de' },
        { id: 12, english: 'a coward', french: 'un lâche' },
        { id: 13, english: 'alienated', french: 'aliéné' },
        { id: 14, english: 'bad faith / self-deception', french: 'la mauvaise foi' },
        { id: 15, english: 'lucidly', french: 'lucidement' },
    ],
    'c2-balzac-goriot': [
        { id: 1, english: 'a boarding house', french: 'une pension' },
        { id: 2, english: 'to reflect faithfully', french: 'refléter fidèlement' },
        { id: 3, english: 'petty / mean', french: 'mesquin' },
        { id: 4, english: 'sordid', french: 'sordide' },
        { id: 5, english: 'worn out by use', french: 'mangé par l\'usage' },
        { id: 6, english: 'rancid / musty (smells)', french: 'rance' },
        { id: 7, english: 'a lodger / boarder', french: 'un pensionnaire' },
        { id: 8, english: 'titled (men)', french: 'titrés' },
        { id: 9, english: 'to settle debts', french: 'régler des dettes' },
        { id: 10, english: 'whims / caprices', french: 'des caprices' },
        { id: 11, english: 'a Christ-like figure', french: 'une figure christique' },
        { id: 12, english: 'to sacrifice oneself', french: 'se sacrifier' },
        { id: 13, english: 'ungrateful people', french: 'des ingrats' },
        { id: 14, english: 'governed / ruled (by)', french: 'régi' },
        { id: 15, english: 'ambition without illusions', french: 'l\'ambition sans illusions' },
    ],
    'c2-flaubert-bovary': [
        { id: 1, english: 'a convent', french: 'un couvent' },
        { id: 2, english: 'fed on / nourished by', french: 'nourrie de' },
        { id: 3, english: 'sentimental novels', french: 'des romans sentimentaux' },
        { id: 4, english: 'a country doctor', french: 'un médecin de campagne' },
        { id: 5, english: 'boredom / tedium', french: 'l\'ennui' },
        { id: 6, english: 'the irreducible gap', french: 'l\'écart irréductible' },
        { id: 7, english: 'free indirect speech', french: 'le style indirect libre' },
        { id: 8, english: 'direct speech', french: 'le discours direct' },
        { id: 9, english: 'to merge / to blend', french: 'fondre' },
        { id: 10, english: 'the narrator', french: 'le narrateur' },
        { id: 11, english: 'the stream of consciousness', french: 'le flux de conscience' },
        { id: 12, english: 'an ironic distance', french: 'une distance ironique' },
        { id: 13, english: 'to get carried away', french: 's\'emballer' },
        { id: 14, english: 'disenchanted', french: 'désenchanté' },
        { id: 15, english: 'the right word', french: 'le mot juste' },
    ],
    'c2-poesie-symboliste': [
        { id: 1, english: 'living pillars', french: 'de vivants piliers' },
        { id: 2, english: 'confused words', french: 'de confuses paroles' },
        { id: 3, english: 'forests of symbols', french: 'des forêts de symboles' },
        { id: 4, english: 'familiar glances', french: 'des regards familiers' },
        { id: 5, english: 'long echoes', french: 'de longs échos' },
        { id: 6, english: 'to blend together / to merge', french: 'se confondre' },
        { id: 7, english: 'a dark and deep unity', french: 'une ténébreuse et profonde unité' },
        { id: 8, english: 'the perfumes / scents', french: 'les parfums' },
        { id: 9, english: 'to answer / echo one another', french: 'se répondre' },
        { id: 10, english: 'a programme poem', french: 'un poème programme' },
        { id: 11, english: 'a system of signs', french: 'un système de signes' },
        { id: 12, english: 'to decipher', french: 'déchiffrer' },
        { id: 13, english: 'synaesthesia', french: 'la synesthésie' },
        { id: 14, english: 'a hidden unity', french: 'une unité cachée' },
        { id: 15, english: 'threatening / menacing', french: 'menaçant' },
    ],
    'c2-essay-contemporary': [
        { id: 1, english: 'to be bored', french: 's\'ennuyer' },
        { id: 2, english: 'constant notifications', french: 'des notifications permanentes' },
        { id: 3, english: 'uninterrupted', french: 'ininterrompu' },
        { id: 4, english: 'to disappear / to vanish', french: 'disparaître' },
        { id: 5, english: 'to transform itself', french: 'se transformer' },
        { id: 6, english: 'classic boredom', french: 'l\'ennui classique' },
        { id: 7, english: 'a void / emptiness', french: 'un vide' },
        { id: 8, english: 'an absence of stimulation', french: 'une absence de stimulation' },
        { id: 9, english: 'fruitful / fertile', french: 'fécond' },
        { id: 10, english: 'daydreaming / reverie', french: 'la rêverie' },
        { id: 11, english: 'saturation', french: 'la saturation' },
        { id: 12, english: 'the society of fatigue', french: 'la société de la fatigue' },
        { id: 13, english: 'to wear oneself out / to exhaust oneself', french: 's\'épuiser' },
        { id: 14, english: 'contemplative inactivity', french: 'l\'inactivité contemplative' },
        { id: 15, english: 'hyperconnected', french: 'hyperconnecté' },
    ],
    'c2-discours-academique': [
        { id: 1, english: 'to put forward / to propose', french: 'proposer' },
        { id: 2, english: 'a lesson / a lecture', french: 'une leçon' },
        { id: 3, english: 'transmitted knowledge', french: 'un savoir transmis' },
        { id: 4, english: 'to maintain / to keep up (a relationship)', french: 'entretenir' },
        { id: 5, english: 'born from / arising from', french: 'issu de' },
        { id: 6, english: 'in its original form', french: 'dans sa forme originelle' },
        { id: 7, english: 'a disputation / structured debate', french: 'une dispute' },
        { id: 8, english: 'the rigorous testing (of theses)', french: 'l\'épreuve rigoureuse' },
        { id: 9, english: 'to cast doubt / to question', french: 'mettre en doute' },
        { id: 10, english: 'received assumptions', french: 'les évidences reçues' },
        { id: 11, english: 'fundamentally critical', french: 'fondamentalement critique' },
        { id: 12, english: 'lazy scepticism', french: 'le scepticisme paresseux' },
        { id: 13, english: 'the presuppositions', french: 'les présupposés' },
        { id: 14, english: 'thankless / unrewarding', french: 'ingrat' },
        { id: 15, english: 'to harden into dogma', french: 'se pétrifier en dogme' },
    ],
    'c2-news-analysis': [
        { id: 1, english: 'an editorial', french: 'un éditorial' },
        { id: 2, english: 'to strive to / to endeavour to', french: 's\'efforcer de' },
        { id: 3, english: 'to interpret', french: 'interpréter' },
        { id: 4, english: 'a column / chronicle', french: 'une chronique' },
        { id: 5, english: 'the editorial line', french: 'la ligne éditoriale' },
        { id: 6, english: 'an institutional position', french: 'une position institutionnelle' },
        { id: 7, english: 'thematic', french: 'thématique' },
        { id: 8, english: 'the thesis defended', french: 'la thèse défendue' },
        { id: 9, english: 'concessions', french: 'des concessions' },
        { id: 10, english: 'stylistic devices', french: 'des procédés stylistiques' },
        { id: 11, english: 'a rhetorical question', french: 'une question rhétorique' },
        { id: 12, english: 'ideological', french: 'idéologique' },
        { id: 13, english: 'to naturalise / to make seem natural', french: 'naturaliser' },
        { id: 14, english: 'critical reading', french: 'la lecture critique' },
        { id: 15, english: 'a civic skill', french: 'une compétence civique' },
    ],
};
