import type { PhraseCategory } from '../../../types/lectures/phrases';

export const phrasesA1: PhraseCategory[] = [
    {
        level: 'A1', unit: 1,
        id: 'everyday-conversation',
        title: 'Everyday Conversation',
        titleFR: 'Conversation quotidienne',
        description: 'Essential phrases for daily interactions',
        descriptionFR: 'Expressions essentielles pour les interactions du quotidien',
        icon: '💬',
        color: '#2563EB',
        phrases: [
            { id: 1, french: 'Ça fait longtemps !', english: 'It\'s been a while! / Long time no see!' },
            { id: 2, french: 'Comment ça se passe ?', english: 'How\'s it going? / How are things?' },
            { id: 3, french: 'Ça marche !', english: 'Works for me! / Sure!' },
            { id: 4, french: 'C\'est pas grave.', english: 'It\'s no big deal. / Don\'t worry about it.', note: 'Very common informal reassurance' },
            { id: 5, french: 'On verra.', english: 'We\'ll see.' },
            { id: 6, french: 'À ta place, je...', english: 'If I were you, I would...' },
            { id: 7, french: 'Je n\'en reviens pas !', english: 'I can\'t believe it! / I\'m amazed!' },
            { id: 8, french: 'Tu plaisantes ?', english: 'Are you joking? / Are you serious?' },
            { id: 9, french: 'Sans blague ?', english: 'No kidding? / Really?' },
            { id: 10, french: 'Ça me dit quelque chose.', english: 'That rings a bell. / That sounds familiar.' },
            { id: 11, french: 'Je m\'en fiche.', english: 'I don\'t care. / I couldn\'t care less.', note: 'Informal; stronger version: je m\'en fous' },
            { id: 12, french: 'Ça dépend.', english: 'It depends.' },
            { id: 13, french: 'Franchement...', english: 'Honestly... / Frankly...' },
            { id: 14, french: 'En tout cas...', english: 'In any case... / Anyway...' },
            { id: 15, french: 'Il ne faut pas exagérer !', english: 'Don\'t exaggerate! / Let\'s not go overboard!' },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'at-the-restaurant',
        title: 'At the Restaurant',
        titleFR: 'Au restaurant',
        description: 'Order confidently and navigate dining out',
        descriptionFR: 'Commandez avec assurance et naviguez dans un restaurant',
        icon: '🍽️',
        color: '#EA580C',
        phrases: [
            { id: 1, french: 'Une table pour deux, s\'il vous plaît.', english: 'A table for two, please.' },
            { id: 2, french: 'Avez-vous une réservation ?', english: 'Do you have a reservation?' },
            { id: 3, french: 'Je voudrais voir la carte, s\'il vous plaît.', english: 'I\'d like to see the menu, please.' },
            { id: 4, french: 'Qu\'est-ce que vous recommandez ?', english: 'What do you recommend?' },
            { id: 5, french: 'Je suis allergique à...', english: 'I\'m allergic to...' },
            { id: 6, french: 'Je vais prendre le plat du jour.', english: 'I\'ll have the dish of the day.' },
            { id: 7, french: 'C\'est inclus dans le menu ?', english: 'Is it included in the set menu?' },
            { id: 8, french: 'La cuisson, s\'il vous plaît ?', english: 'How would you like it cooked?', note: 'said by the server for steak' },
            { id: 9, french: 'Saignant / à point / bien cuit.', english: 'Rare / medium / well done.' },
            { id: 10, french: 'L\'addition, s\'il vous plaît.', english: 'The bill, please.' },
            { id: 11, french: 'Le service est compris ?', english: 'Is service included?' },
            { id: 12, french: 'C\'était délicieux, merci.', english: 'It was delicious, thank you.' },
            { id: 13, french: 'On partage ?', english: 'Shall we split the bill?' },
            { id: 14, french: 'Je vous offre.', english: 'It\'s on me. / I\'m treating you.' },
            { id: 15, french: 'Encore un peu de vin ?', english: 'A little more wine?' },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'getting-around',
        title: 'Getting Around',
        titleFR: 'Se déplacer',
        description: 'Navigate transport and ask for directions',
        descriptionFR: 'Transports et demander son chemin',
        icon: '🗺️',
        color: '#059669',
        phrases: [
            { id: 1, french: 'Où se trouve la station de métro la plus proche ?', english: 'Where is the nearest metro station?' },
            { id: 2, french: 'Je cherche la rue...', english: 'I\'m looking for... street.' },
            { id: 3, french: 'C\'est loin d\'ici ?', english: 'Is it far from here?' },
            { id: 4, french: 'À pied, ça prend combien de temps ?', english: 'How long does it take on foot?' },
            { id: 5, french: 'Prenez la première à gauche / droite.', english: 'Take the first left / right.' },
            { id: 6, french: 'Continuez tout droit.', english: 'Carry straight on.' },
            { id: 7, french: 'C\'est au bout de la rue.', english: 'It\'s at the end of the street.' },
            { id: 8, french: 'Je voudrais un billet pour...', english: 'I\'d like a ticket to...' },
            { id: 9, french: 'À quelle heure part le prochain train ?', english: 'What time does the next train leave?' },
            { id: 10, french: 'Est-ce que ce bus s\'arrête à... ?', english: 'Does this bus stop at...?' },
            { id: 11, french: 'J\'ai raté mon train.', english: 'I missed my train.' },
            { id: 12, french: 'Le vol est à l\'heure ?', english: 'Is the flight on time?' },
            { id: 13, french: 'Pouvez-vous appeler un taxi ?', english: 'Could you call a taxi?' },
            { id: 14, french: 'Je suis perdu(e).', english: 'I\'m lost.' },
            { id: 15, french: 'Déposez-moi ici, s\'il vous plaît.', english: 'Drop me off here, please.' },
        ],
    },
    {
        level: 'A1', unit: 1,
        id: 'introducing-yourself',
        title: 'Introducing Yourself',
        titleFR: 'Se présenter',
        description: 'Introduce yourself and get to know others',
        descriptionFR: 'Présentez-vous et faites connaissance',
        icon: '👋',
        color: '#4338CA',
        phrases: [
            { id: 1,  french: 'Je m\'appelle…',                         english: 'My name is…' },
            { id: 2,  french: 'J\'ai X ans.',                           english: 'I am X years old.' },
            { id: 3,  french: 'Je suis de…',                           english: 'I\'m from…' },
            { id: 4,  french: 'J\'habite à…',                          english: 'I live in…' },
            { id: 5,  french: 'Je parle français.',                     english: 'I speak French.' },
            { id: 6,  french: 'Je suis étudiant(e) / professeur.',      english: 'I\'m a student / teacher.' },
            { id: 7,  french: 'Enchanté(e).',                           english: 'Pleased to meet you.' },
            { id: 8,  french: 'Comment vous appelez-vous ?',            english: 'What is your name?' },
            { id: 9,  french: 'Vous parlez anglais ?',                  english: 'Do you speak English?' },
            { id: 10, french: 'Je ne comprends pas.',                   english: 'I don\'t understand.' },
            { id: 11, french: 'Pouvez-vous répéter ?',                  english: 'Could you repeat that?' },
            { id: 12, french: 'Plus lentement, s\'il vous plaît.',      english: 'More slowly, please.' },
            { id: 13, french: 'D\'où venez-vous ?',                     english: 'Where are you from?' },
            { id: 14, french: 'Je suis britannique / irlandais(e).',    english: 'I\'m British / Irish.' },
            { id: 15, french: 'Ravi(e) de vous rencontrer.',            english: 'Delighted to meet you.' },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'at-the-cafe',
        title: 'At the Café',
        titleFR: 'Au café',
        description: 'Order drinks and snacks, ask for the bill, and chat with the waiter',
        descriptionFR: 'Commander des boissons, demander l\'addition et échanger avec le serveur',
        icon: '☕',
        color: '#92400E',
        phrases: [
            { id: 1,  french: 'Un café, s\'il vous plaît.',              english: 'A coffee, please.',                      note: 'The default order — un café = an espresso in France' },
            { id: 2,  french: 'Je voudrais…',                            english: 'I would like…',                          note: 'Polite way to order; more formal than je veux' },
            { id: 3,  french: 'Je prends…',                              english: 'I\'ll have…',                            note: 'Casual alternative to je voudrais' },
            { id: 4,  french: 'Vous avez une table pour deux ?',         english: 'Do you have a table for two?'                                                               },
            { id: 5,  french: 'La carte, s\'il vous plaît.',             english: 'The menu, please.'                                                                          },
            { id: 6,  french: 'Qu\'est-ce que vous recommandez ?',       english: 'What do you recommend?'                                                                     },
            { id: 7,  french: 'En terrasse ou à l\'intérieur ?',         english: 'On the terrace or inside?',              note: 'The waiter asks you this' },
            { id: 8,  french: 'Avec du lait ?',                          english: 'With milk?'                                                                                  },
            { id: 9,  french: 'Sans sucre, s\'il vous plaît.',           english: 'Without sugar, please.'                                                                     },
            { id: 10, french: 'C\'est délicieux !',                      english: 'It\'s delicious!'                                                                           },
            { id: 11, french: 'C\'est combien ?',                        english: 'How much is it?'                                                                            },
            { id: 12, french: 'L\'addition, s\'il vous plaît.',          english: 'The bill, please.',                      note: 'Never ask for la facture in a café — that\'s for professional invoices' },
            { id: 13, french: 'Service compris ?',                       english: 'Is service included?'                                                                       },
            { id: 14, french: 'Vous acceptez les cartes ?',              english: 'Do you accept cards?'                                                                       },
            { id: 15, french: 'Merci, au revoir !',                      english: 'Thank you, goodbye!'                                                                        },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'asking-directions',
        title: 'Asking for Directions',
        titleFR: 'Demander son chemin',
        description: 'Find your way around a French city — ask for directions and understand the answers',
        descriptionFR: 'Orientez-vous dans une ville française — demandez et comprenez les indications',
        icon: '🗺️',
        color: '#0891B2',
        phrases: [
            { id: 1,  french: 'Pardon, où est… ?',                          english: 'Excuse me, where is… ?',                     note: 'Always start with Pardon — it\'s the polite opener' },
            { id: 2,  french: 'Je suis perdu(e).',                          english: 'I\'m lost.',                                  note: 'Add -e if you\'re female: perdue' },
            { id: 3,  french: 'Pouvez-vous m\'aider ?',                     english: 'Can you help me?'                                                                              },
            { id: 4,  french: 'C\'est loin d\'ici ?',                       english: 'Is it far from here?'                                                                         },
            { id: 5,  french: 'C\'est à combien de minutes à pied ?',       english: 'How many minutes on foot?'                                                                    },
            { id: 6,  french: 'Tournez à gauche.',                          english: 'Turn left.'                                                                                    },
            { id: 7,  french: 'Tournez à droite.',                          english: 'Turn right.'                                                                                   },
            { id: 8,  french: 'Allez tout droit.',                          english: 'Go straight ahead.'                                                                           },
            { id: 9,  french: 'Prenez la première rue à gauche.',           english: 'Take the first street on the left.'                                                           },
            { id: 10, french: 'Au feu rouge, tournez à droite.',            english: 'At the traffic lights, turn right.'                                                           },
            { id: 11, french: 'Au rond-point, prenez la deuxième sortie.',  english: 'At the roundabout, take the second exit.'                                                    },
            { id: 12, french: 'C\'est en face de la mairie.',               english: 'It\'s opposite the town hall.',               note: 'en face de = opposite / facing' },
            { id: 13, french: 'C\'est à côté de la pharmacie.',             english: 'It\'s next to the pharmacy.',                 note: 'à côté de = next to' },
            { id: 14, french: 'C\'est à deux kilomètres d\'ici.',           english: 'It\'s two kilometres from here.'                                                              },
            { id: 15, french: 'Il y a un bus qui va là-bas ?',              english: 'Is there a bus that goes there?'                                                              },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'shopping-basics',
        title: 'Shopping Basics',
        titleFR: 'Faire les courses',
        description: 'Buy clothes, ask for prices, and handle transactions in French shops',
        descriptionFR: 'Acheter des vêtements, demander les prix et gérer les achats dans les magasins',
        icon: '🛍️',
        color: '#7C3AED',
        phrases: [
            { id: 1,  french: 'Je cherche…',                                english: 'I\'m looking for…'                                                                            },
            { id: 2,  french: 'Vous avez ça en taille M ?',                 english: 'Do you have this in size M?',                note: 'Replace M with S, L, XL as needed' },
            { id: 3,  french: 'C\'est combien ?',                           english: 'How much is it?'                                                                              },
            { id: 4,  french: 'C\'est trop cher.',                          english: 'It\'s too expensive.'                                                                         },
            { id: 5,  french: 'C\'est ma taille.',                          english: 'It\'s my size.'                                                                              },
            { id: 6,  french: 'Ça ne me va pas.',                           english: 'It doesn\'t suit me / it doesn\'t fit me.'                                                   },
            { id: 7,  french: 'Je vais le prendre.',                        english: 'I\'ll take it. (masc. item)',                note: 'Use la for feminine items: je vais la prendre' },
            { id: 8,  french: 'Vous acceptez les cartes bancaires ?',       english: 'Do you accept bank cards?'                                                                    },
            { id: 9,  french: 'Un sac, s\'il vous plaît.',                  english: 'A bag, please.'                                                                               },
            { id: 10, french: 'Avez-vous un reçu ?',                        english: 'Do you have a receipt?'                                                                       },
            { id: 11, french: 'C\'est en solde ?',                          english: 'Is it on sale?',                             note: 'Les soldes = the sales (seasonal)' },
            { id: 12, french: 'Il y a une remise ?',                        english: 'Is there a discount?'                                                                         },
            { id: 13, french: 'C\'est en promotion.',                       english: 'It\'s on special offer.'                                                                      },
            { id: 14, english: 'Do you have change?',                       french: 'Avez-vous de la monnaie ?'                                                                     },
            { id: 15, french: 'C\'est parfait, merci !',                    english: 'It\'s perfect, thank you!'                                                                    },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'daily-routine',
        title: 'Daily Routine',
        titleFR: 'La routine quotidienne',
        description: 'Describe your day, habits, and schedule',
        descriptionFR: 'Décrire sa journée, ses habitudes et son emploi du temps',
        icon: '📅',
        color: '#059669',
        phrases: [
            { id: 1,  french: 'Je me lève à sept heures.',          english: 'I get up at seven o\'clock.' },
            { id: 2,  french: 'Je prends mon petit-déjeuner.',       english: 'I have breakfast.' },
            { id: 3,  french: 'Je vais au travail en métro.',        english: 'I go to work by metro.' },
            { id: 4,  french: 'Je commence à neuf heures.',          english: 'I start at nine o\'clock.' },
            { id: 5,  french: 'Je rentre chez moi à dix-huit heures.', english: 'I get home at six o\'clock.' },
            { id: 6,  french: 'Le week-end, je fais du sport.',      english: 'At the weekend, I do sport.' },
            { id: 7,  french: 'D\'habitude, je prépare le dîner.',   english: 'Usually, I make dinner.', note: 'D\'habitude = usually, triggers imparfait in the past' },
            { id: 8,  french: 'Parfois je mange au restaurant.',     english: 'Sometimes I eat at a restaurant.' },
            { id: 9,  french: 'Je n\'ai pas le temps de regarder la télé.', english: 'I don\'t have time to watch TV.' },
            { id: 10, french: 'Qu\'est-ce que tu fais ce soir ?',   english: 'What are you doing tonight?' },
            { id: 11, french: 'On se retrouve à quelle heure ?',     english: 'What time shall we meet?' },
            { id: 12, french: 'Je dois finir ce travail d\'abord.',  english: 'I need to finish this work first.' },
            { id: 13, french: 'Je me couche vers onze heures.',      english: 'I go to bed around eleven o\'clock.' },
            { id: 14, french: 'Ça m\'arrive souvent.',               english: 'That happens to me often.' },
            { id: 15, french: 'Ma journée est bien chargée.',        english: 'My day is very busy.' },
        ],
    },
    {
        level: 'A1', unit: 3,
        id: 'classroom-survival',
        title: 'Classroom Survival',
        titleFR: 'Survie en classe',
        description: 'Essential phrases for the language classroom',
        descriptionFR: 'Phrases essentielles pour la salle de classe',
        icon: '🏫',
        color: '#059669',
        phrases: [
            { id: 1,  french: 'Je ne comprends pas.',                       english: 'I don\'t understand.' },
            { id: 2,  french: 'Pouvez-vous répéter ?',                      english: 'Could you repeat that?' },
            { id: 3,  french: 'Comment dit-on… en français ?',              english: 'How do you say… in French?' },
            { id: 4,  french: 'Qu\'est-ce que ça veut dire ?',              english: 'What does that mean?' },
            { id: 5,  french: 'Comment ça s\'écrit ?',                      english: 'How do you spell that?' },
            { id: 6,  french: 'Je n\'entends pas bien.',                    english: 'I can\'t hear properly.' },
            { id: 7,  french: 'Pouvez-vous parler plus lentement ?',        english: 'Could you speak more slowly?' },
            { id: 8,  french: 'Est-ce que c\'est correct ?',                english: 'Is that correct?' },
            { id: 9,  french: 'Encore une fois, s\'il vous plaît.',         english: 'Once more, please.' },
            { id: 10, french: 'J\'ai une question.',                        english: 'I have a question.' },
            { id: 11, french: 'Je ne sais pas.',                            english: 'I don\'t know.' },
            { id: 12, french: 'Peut-on traduire ?',                         english: 'Can we translate?' },
            { id: 13, french: 'Pouvez-vous l\'écrire au tableau ?',         english: 'Could you write it on the board?' },
            { id: 14, french: 'Merci pour votre patience.',                 english: 'Thank you for your patience.' },
            { id: 15, french: 'Je comprends maintenant.',                   english: 'I understand now.' },
        ],
    },
];
