import type { PhraseCategory } from '../../../types/lectures/phrases';

export const phrasesB1: PhraseCategory[] = [
    {
        level: 'B1', unit: 3,
        id: 'expressing-opinions',
        title: 'Expressing Opinions',
        titleFR: 'Exprimer ses opinions',
        description: 'Share your views, agree, and disagree in French',
        descriptionFR: 'Partagez vos idées, approuvez et désapprouvez',
        icon: '💭',
        color: '#7C3AED',
        phrases: [
            { id: 1, french: 'À mon avis...', english: 'In my opinion...' },
            { id: 2, french: 'Selon moi...', english: 'According to me... / As I see it...' },
            { id: 3, french: 'Je trouve que...', english: 'I find that... / I think that...' },
            { id: 4, french: 'Je suis (tout à fait) d\'accord.', english: 'I (completely) agree.' },
            { id: 5, french: 'Je ne suis pas du tout d\'accord.', english: 'I completely disagree.' },
            { id: 6, french: 'C\'est discutable.', english: 'That\'s debatable. / You could argue either way.' },
            { id: 7, french: 'Dans une certaine mesure...', english: 'To a certain extent...' },
            { id: 8, french: 'Il faut nuancer.', english: 'We need to be nuanced. / It\'s more complicated than that.' },
            { id: 9, french: 'D\'un côté... de l\'autre...', english: 'On one hand... on the other...' },
            { id: 10, french: 'Cela dit...', english: 'That said... / Having said that...' },
            { id: 11, french: 'Je n\'avais pas pensé à ça.', english: 'I hadn\'t thought of that.' },
            { id: 12, french: 'Tu as un point.', english: 'You have a point. / That\'s a fair point.' },
            { id: 13, french: 'Je ne suis pas convaincu(e).', english: 'I\'m not convinced.' },
            { id: 14, french: 'C\'est une question de perspective.', english: 'It\'s a matter of perspective.' },
            { id: 15, french: 'En définitive...', english: 'Ultimately... / When all is said and done...' },
        ],
    },
    {
        level: 'B1', unit: 3,
        id: 'at-the-museum-event',
        title: 'At the Museum / Event',
        titleFR: 'Au musée / à un événement',
        description: 'Navigate cultural venues and events in French',
        descriptionFR: 'Se repérer dans les musées et événements culturels',
        icon: '🎨',
        color: '#0891B2',
        phrases: [
            { id: 1,  french: 'Combien coûte l\'entrée ?',                       english: 'How much is the entry / admission?' },
            { id: 2,  french: 'Y a-t-il des audioguides ?',                      english: 'Are there audio guides?' },
            { id: 3,  french: 'À quelle heure ferme le musée ?',                 english: 'What time does the museum close?' },
            { id: 4,  french: 'Cette œuvre date de…',                            english: 'This work dates from…' },
            { id: 5,  french: 'Je ne connais pas cet artiste.',                  english: 'I don\'t know this artist.' },
            { id: 6,  french: 'C\'est magnifique !',                             english: 'It\'s magnificent / beautiful!' },
            { id: 7,  french: 'Ça me fait penser à…',                            english: 'It reminds me of… / It makes me think of…' },
            { id: 8,  french: 'Y a-t-il une boutique ?',                         english: 'Is there a gift shop?' },
            { id: 9,  french: 'Vous faites des visites guidées ?',               english: 'Do you offer guided tours?' },
            { id: 10, french: 'Je voudrais un catalogue.',                       english: 'I\'d like a catalogue.' },
            { id: 11, french: 'Où se trouve l\'exposition temporaire ?',         english: 'Where is the temporary exhibition?' },
            { id: 12, french: 'Il est interdit de photographier.',               english: 'Photography is not allowed.' },
            { id: 13, french: 'Puis-je laisser mon manteau à la consigne ?',    english: 'Can I leave my coat in the cloakroom?' },
            { id: 14, french: 'La file d\'attente est longue.',                  english: 'The queue is long.' },
            { id: 15, french: 'Merci pour cette visite, c\'était enrichissant.', english: 'Thank you for this visit, it was enriching.' },
        ],
    },
    {
        level: 'B1', unit: 3,
        id: 'talking-about-work',
        title: 'Talking About Work',
        titleFR: 'Parler du travail',
        description: 'Discuss your job, workplace and professional life in French',
        descriptionFR: 'Parler de son travail, de son lieu de travail et de sa vie professionnelle',
        icon: '💼',
        color: '#0891B2',
        phrases: [
            { id: 1,  french: 'Je travaille dans…',                              english: 'I work in…' },
            { id: 2,  french: 'Mon poste consiste à…',                           english: 'My role involves…' },
            { id: 3,  french: 'J\'ai une réunion à…',                            english: 'I have a meeting at…' },
            { id: 4,  french: 'Je suis en télétravail.',                         english: 'I\'m working from home.' },
            { id: 5,  french: 'Mon responsable s\'appelle…',                     english: 'My manager\'s name is…' },
            { id: 6,  french: 'On cherche quelqu\'un pour…',                     english: 'We\'re looking for someone to…' },
            { id: 7,  french: 'Je postule à un emploi.',                         english: 'I\'m applying for a job.' },
            { id: 8,  french: 'J\'ai passé un entretien.',                       english: 'I had / went for an interview.' },
            { id: 9,  french: 'J\'ai été embauché(e).',                          english: 'I was hired / taken on.' },
            { id: 10, french: 'Je donne ma démission.',                          english: 'I\'m handing in my notice.' },
            { id: 11, french: 'Les horaires sont flexibles.',                    english: 'The hours are flexible.' },
            { id: 12, french: 'Je suis en congé.',                               english: 'I\'m on leave / holiday.' },
            { id: 13, french: 'On a une échéance vendredi.',                     english: 'We have a deadline on Friday.' },
            { id: 14, french: 'Je collabore avec…',                             english: 'I work / collaborate with…' },
            { id: 15, french: 'C\'est un environnement dynamique.',              english: 'It\'s a dynamic environment.' },
        ],
    },
    {
        level: 'B1', unit: 3,
        id: 'health-lifestyle-phrases',
        title: 'Health & Lifestyle',
        titleFR: 'Santé & mode de vie',
        description: 'Talk about your health habits and lifestyle in French',
        descriptionFR: 'Parler de ses habitudes de santé et de son mode de vie',
        icon: '🌿',
        color: '#0891B2',
        phrases: [
            { id: 1,  french: 'Je fais du sport trois fois par semaine.',        english: 'I exercise three times a week.' },
            { id: 2,  french: 'J\'essaie de bien manger.',                       english: 'I try to eat well.' },
            { id: 3,  french: 'Je dors huit heures par nuit.',                   english: 'I sleep eight hours a night.' },
            { id: 4,  french: 'Je suis stressé(e) en ce moment.',               english: 'I\'m stressed at the moment.' },
            { id: 5,  french: 'Ça fait du bien de se détendre.',                english: 'It\'s good to relax.' },
            { id: 6,  french: 'J\'ai arrêté de fumer.',                         english: 'I quit smoking.' },
            { id: 7,  french: 'Je suis végétarien(ne).',                        english: 'I\'m vegetarian.' },
            { id: 8,  french: 'J\'ai une intolérance au lactose.',              english: 'I\'m lactose intolerant.' },
            { id: 9,  french: 'Il faut faire attention à sa santé.',            english: 'You have to take care of your health.' },
            { id: 10, french: 'Mon médecin m\'a conseillé de…',                english: 'My doctor advised me to…' },
            { id: 11, french: 'Je pratique la méditation.',                     english: 'I practise meditation.' },
            { id: 12, french: 'Je me sens en pleine forme.',                    english: 'I feel in great shape.' },
            { id: 13, french: 'J\'ai besoin de me ressourcer.',                 english: 'I need to recharge / take a break.' },
            { id: 14, french: 'Le sport me libère l\'esprit.',                  english: 'Exercise clears my mind.' },
            { id: 15, french: 'La santé, c\'est la richesse.',                  english: 'Health is wealth.' },
        ],
    },
    {
        level: 'B1', unit: 3,
        id: 'customer-service',
        title: 'Customer Service & Complaints',
        titleFR: 'Service client & réclamations',
        description: 'Handle complaints, returns, and customer service interactions in French',
        descriptionFR: 'Gérer les réclamations, les retours et les interactions avec le service client',
        icon: '🛎️',
        color: '#DC2626',
        phrases: [
            { id: 1,  french: 'Je voudrais faire une réclamation.',                    english: 'I would like to make a complaint.' },
            { id: 2,  french: 'Ce produit est défectueux.',                           english: 'This product is defective.' },
            { id: 3,  french: 'Je voudrais être remboursé(e).',                       english: 'I would like a refund.' },
            { id: 4,  french: 'Puis-je parler au responsable ?',                      english: 'Can I speak to the manager?' },
            { id: 5,  french: 'J\'ai perdu mon ticket de caisse.',                    english: 'I have lost my receipt.' },
            { id: 6,  french: 'Cela ne correspond pas à ce que j\'ai commandé.',      english: 'This is not what I ordered.' },
            { id: 7,  french: 'Le colis n\'est jamais arrivé.',                       english: 'The parcel never arrived.' },
            { id: 8,  french: 'Je souhaite échanger cet article.',                    english: 'I would like to exchange this item.' },
            { id: 9,  french: 'Pouvez-vous vérifier ma commande ?',                   english: 'Can you check my order?' },
            { id: 10, french: 'Le service était décevant.',                           english: 'The service was disappointing.' },
            { id: 11, french: 'J\'attends une réponse depuis une semaine.',           english: 'I have been waiting for a response for a week.' },
            { id: 12, french: 'Voici mon numéro de commande.',                        english: 'Here is my order number.' },
            { id: 13, french: 'Je suis très insatisfait(e) de cet achat.',            english: 'I am very dissatisfied with this purchase.' },
            { id: 14, french: 'Pouvez-vous m\'envoyer un bon de retour ?',            english: 'Can you send me a return label?' },
            { id: 15, french: 'Je compte déposer une plainte formelle.',              english: 'I intend to make a formal complaint.' },
        ],
    },
    {
        level: 'B1', unit: 3,
        id: 'describing-your-home',
        title: 'Describing Your Home',
        titleFR: 'Décrire son logement',
        description: 'Talk about where you live and what your home is like',
        descriptionFR: 'Parler de l\'endroit où vous vivez et de votre logement',
        icon: '🏠',
        color: '#7C3AED',
        phrases: [
            { id: 1,  french: 'J\'habite dans un appartement / une maison.',      english: 'I live in a flat / a house.' },
            { id: 2,  french: 'Mon appartement est au troisième étage.',          english: 'My flat is on the third floor.' },
            { id: 3,  french: 'Il y a trois pièces.',                             english: 'There are three rooms.' },
            { id: 4,  french: 'Ma chambre est grande / petite.',                  english: 'My bedroom is big / small.' },
            { id: 5,  french: 'Le salon est au rez-de-chaussée.',                 english: 'The living room is on the ground floor.' },
            { id: 6,  french: 'La cuisine est moderne.',                          english: 'The kitchen is modern.' },
            { id: 7,  french: 'Il y a un jardin derrière la maison.',             english: 'There is a garden behind the house.' },
            { id: 8,  french: 'Mon bureau est à côté de la chambre.',             english: 'My study is next to the bedroom.' },
            { id: 9,  french: 'La salle de bains est en face de la cuisine.',     english: 'The bathroom is opposite the kitchen.' },
            { id: 10, french: 'Il n\'y a pas de garage.',                         english: 'There is no garage.' },
            { id: 11, french: 'Nous avons un balcon.',                            english: 'We have a balcony.' },
            { id: 12, french: 'C\'est un quartier calme.',                        english: 'It\'s a quiet neighbourhood.' },
            { id: 13, french: 'L\'appartement est bien situé.',                   english: 'The flat is well located.' },
            { id: 14, french: 'J\'habite au centre-ville / en banlieue.',         english: 'I live in the city centre / in the suburbs.' },
            { id: 15, french: 'C\'est lumineux et spacieux.',                     english: 'It\'s bright and spacious.' },
        ],
    },
];
