import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

export const modulesA1: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'A1', unit: 1, "id":"greetings-basics","title":"Salutations & Essentiels","titleFR":"Salutations & Essentiels","description":"Expressions essentielles pour commencer une conversation","descriptionFR":"Expressions essentielles pour commencer une conversation","icon":"👋","color":"#F59E0B","wordCount":0, words: [
        { id: 1, english: 'hello / good morning', french: 'bonjour' },
        { id: 2, english: 'good evening', french: 'bonsoir' },
        { id: 3, english: 'good night', french: 'bonne nuit' },
        { id: 4, english: 'goodbye', french: 'au revoir' },
        { id: 5, english: 'hi / bye (informal)', french: 'salut' },
        { id: 6, english: 'thank you', french: 'merci' },
        { id: 7, english: 'please (formal)', french: 's\'il vous plaît' },
        { id: 8, english: 'please (informal)', french: 's\'il te plaît' },
        { id: 9, english: 'excuse me (formal)', french: 'excusez-moi' },
        { id: 10, english: 'sorry / excuse me', french: 'pardon' },
        { id: 11, english: 'pleased to meet you', french: 'enchanté(e)' },
        { id: 12, english: 'my name is...', french: 'je m\'appelle...' },
        { id: 13, english: 'I don\'t understand', french: 'je ne comprends pas' },
        { id: 14, english: 'could you repeat that?', french: 'pouvez-vous répéter ?' },
        { id: 15, english: 'I\'m doing well', french: 'je vais bien' },
        { id: 16, english: 'so-so / not bad', french: 'comme ci comme ça' },
        { id: 17, english: 'see you soon', french: 'à bientôt' },
        { id: 18, english: 'see you later (same day)', french: 'à tout à l\'heure' },
        { id: 19, english: 'welcome', french: 'bienvenue' },
        { id: 20, english: 'with pleasure / gladly', french: 'avec plaisir' },
    ] },
    { level: 'A1', unit: 1, "id":"numbers-time","title":"Chiffres & Temps","titleFR":"Chiffres & Temps","description":"Dire l'heure et exprimer quand les choses se passent","descriptionFR":"Dire l'heure et exprimer quand les choses se passent","icon":"🕐","color":"#06B6D4","wordCount":0, words: [
        { id: 1,  english: 'one',                                      french: 'un / une' },
        { id: 2,  english: 'two',                                      french: 'deux' },
        { id: 3,  english: 'three',                                    french: 'trois' },
        { id: 4,  english: 'four',                                     french: 'quatre' },
        { id: 5,  english: 'five',                                     french: 'cinq' },
        { id: 6,  english: 'six',                                      french: 'six' },
        { id: 7,  english: 'seven',                                    french: 'sept' },
        { id: 8,  english: 'eight',                                    french: 'huit' },
        { id: 9,  english: 'nine',                                     french: 'neuf' },
        { id: 10, english: 'ten',                                      french: 'dix' },
        { id: 11, english: 'eleven',                                   french: 'onze' },
        { id: 12, english: 'twelve',                                   french: 'douze' },
        { id: 13, english: 'twenty',                                   french: 'vingt' },
        { id: 14, english: 'thirty',                                   french: 'trente' },
        { id: 15, english: 'forty',                                    french: 'quarante' },
        { id: 16, english: 'fifty',                                    french: 'cinquante' },
        { id: 17, english: 'sixty',                                    french: 'soixante' },
        { id: 18, english: 'seventy (lit. sixty-ten)',                 french: 'soixante-dix' },
        { id: 19, english: 'eighty (lit. four-twenties)',              french: 'quatre-vingts' },
        { id: 20, english: 'one hundred',                              french: 'cent' },
    ] },
    { level: 'A1', unit: 1, "id":"colors-descriptions","title":"Couleurs & Descriptions","titleFR":"Couleurs & Descriptions","description":"Décrire des personnes, des lieux et des objets","descriptionFR":"Décrire des personnes, des lieux et des objets","icon":"🎨","color":"#EC4899","wordCount":0, words: [
        { id: 1, english: 'red', french: 'rouge' },
        { id: 2, english: 'blue', french: 'bleu(e)' },
        { id: 3, english: 'green', french: 'vert(e)' },
        { id: 4, english: 'yellow', french: 'jaune' },
        { id: 5, english: 'white', french: 'blanc/blanche' },
        { id: 6, english: 'black', french: 'noir(e)' },
        { id: 7, english: 'grey', french: 'gris(e)' },
        { id: 8, english: 'pink', french: 'rose' },
        { id: 9, english: 'purple / violet', french: 'violet(te)' },
        { id: 10, english: 'brown', french: 'marron' },
        { id: 11, english: 'big / tall', french: 'grand(e)' },
        { id: 12, english: 'small / short', french: 'petit(e)' },
        { id: 13, english: 'beautiful / handsome', french: 'beau / belle' },
        { id: 14, english: 'ugly', french: 'laid(e)' },
        { id: 15, english: 'round', french: 'rond(e)' },
        { id: 16, english: 'square', french: 'carré(e)' },
        { id: 17, english: 'narrow', french: 'étroit(e)' },
        { id: 18, english: 'wide / broad', french: 'large' },
        { id: 19, english: 'light (in color) / bright', french: 'clair(e)' },
        { id: 20, english: 'dark (in color)', french: 'foncé(e)' },
    ] },
    { level: 'A1', unit: 1, "id":"family-relationships","title":"Famille & Relations","titleFR":"Famille & Relations","description":"Parler des personnes de votre vie","descriptionFR":"Parler des personnes de votre vie","icon":"👨‍👩‍👧‍👦","color":"#10B981","wordCount":0, words: [
        { id: 1, english: 'the parents', french: 'les parents' },
        { id: 2, english: 'the father', french: 'le père' },
        { id: 3, english: 'the mother', french: 'la mère' },
        { id: 4, english: 'the brother', french: 'le frère' },
        { id: 5, english: 'the sister', french: 'la sœur' },
        { id: 6, english: 'the grandparents', french: 'les grands-parents' },
        { id: 7, english: 'the grandfather', french: 'le grand-père' },
        { id: 8, english: 'the grandmother', french: 'la grand-mère' },
        { id: 9, english: 'the son', french: 'le fils' },
        { id: 10, english: 'the daughter', french: 'la fille' },
        { id: 11, english: 'a friend', french: 'un(e) ami(e)' },
        { id: 12, english: 'a neighbour', french: 'un(e) voisin(e)' },
        { id: 13, english: 'a colleague', french: 'un(e) collègue' },
        { id: 14, english: 'the spouse / partner', french: 'le conjoint / la conjointe' },
        { id: 15, english: 'twins (masc. / fem.)', french: 'les jumeaux / les jumelles' },
        { id: 16, english: 'an only child', french: 'un enfant unique' },
        { id: 17, english: 'eldest (child)', french: 'aîné(e)' },
        { id: 18, english: 'youngest (child)', french: 'cadet(te)' },
        { id: 19, english: 'to raise a child', french: 'élever un enfant' },
        { id: 20, english: 'family ties / bonds', french: 'les liens familiaux' },
    ] },
    { level: 'A1', unit: 3, "id":"food-drinks","title":"Nourriture & Boissons","titleFR":"Nourriture & Boissons","description":"Manger, boire et commander avec assurance","descriptionFR":"Manger, boire et commander avec assurance","icon":"🍷","color":"#EF4444","wordCount":0, words: [
        { id: 1, english: 'the meal', french: 'le repas' },
        { id: 2, english: 'breakfast', french: 'le petit-déjeuner' },
        { id: 3, english: 'lunch', french: 'le déjeuner' },
        { id: 4, english: 'dinner', french: 'le dîner' },
        { id: 5, english: 'a starter / appetiser', french: 'une entrée' },
        { id: 6, english: 'a main course', french: 'un plat principal' },
        { id: 7, english: 'dessert', french: 'le dessert' },
        { id: 8, english: 'bread', french: 'le pain' },
        { id: 9, english: 'cheese', french: 'le fromage' },
        { id: 10, english: 'meat', french: 'la viande' },
        { id: 11, english: 'fish', french: 'le poisson' },
        { id: 12, english: 'vegetables', french: 'les légumes' },
        { id: 13, english: 'fruit', french: 'les fruits' },
        { id: 14, english: 'a drink / beverage', french: 'une boisson' },
        { id: 15, english: 'water', french: 'l\'eau' },
        { id: 16, english: 'wine', french: 'le vin' },
        { id: 17, english: 'to be hungry', french: 'avoir faim' },
        { id: 18, english: 'to be thirsty', french: 'avoir soif' },
        { id: 19, english: 'the tip / gratuity', french: 'le pourboire' },
        { id: 20, english: 'the bill (at a restaurant)', french: 'l\'addition' },
    ] },
    { level: 'A1', unit: 3, "id":"body-health","title":"Corps & Santé","titleFR":"Corps & Santé","description":"Parler de votre corps et de votre bien-être","descriptionFR":"Parler de votre corps et de votre bien-être","icon":"🏥","color":"#6366F1","wordCount":0, words: [
        { id: 1, english: 'the head', french: 'la tête' },
        { id: 2, english: 'the face', french: 'le visage' },
        { id: 3, english: 'the eyes', french: 'les yeux' },
        { id: 4, english: 'the mouth', french: 'la bouche' },
        { id: 5, english: 'the ears', french: 'les oreilles' },
        { id: 6, english: 'the heart', french: 'le cœur' },
        { id: 7, english: 'the arms', french: 'les bras' },
        { id: 8, english: 'the legs', french: 'les jambes' },
        { id: 9, english: 'to have a pain in / to ache', french: 'avoir mal à' },
        { id: 10, english: 'pain / an ache', french: 'la douleur' },
        { id: 11, english: 'a fever', french: 'la fièvre' },
        { id: 12, english: 'a prescription', french: 'une ordonnance' },
        { id: 13, english: 'a medication / medicine', french: 'un médicament' },
        { id: 14, english: 'a doctor\'s appointment', french: 'une consultation' },
        { id: 15, english: 'to recover / to get better', french: 'se rétablir' },
        { id: 16, english: 'pregnant', french: 'enceinte' },
        { id: 17, english: 'exhausted / worn out', french: 'épuisé(e)' },
        { id: 18, english: 'in shape / fit and well', french: 'en forme' },
        { id: 19, english: 'an allergy', french: 'une allergie' },
        { id: 20, english: 'the emergency room / A&E', french: 'les urgences' },
    ] },
    { level: 'A1', unit: 3, "id":"home-living","title":"Maison & Vie quotidienne","titleFR":"Maison & Vie quotidienne","description":"Vocabulaire pour la maison et la vie quotidienne","descriptionFR":"Vocabulaire pour la maison et la vie quotidienne","icon":"🏠","color":"#84CC16","wordCount":0, words: [
        { id: 1, english: 'a flat / apartment', french: 'un appartement' },
        { id: 2, english: 'a house', french: 'une maison' },
        { id: 3, english: 'the kitchen', french: 'la cuisine' },
        { id: 4, english: 'the bathroom', french: 'la salle de bains' },
        { id: 5, english: 'the living room', french: 'le salon' },
        { id: 6, english: 'the bedroom', french: 'la chambre' },
        { id: 7, english: 'furniture', french: 'les meubles' },
        { id: 8, english: 'a sofa / couch', french: 'un canapé' },
        { id: 9, english: 'a cupboard / wardrobe', french: 'un placard' },
        { id: 10, english: 'curtains', french: 'les rideaux' },
        { id: 11, english: 'to move in (to a home)', french: 'emménager' },
        { id: 12, english: 'to move out / move house', french: 'déménager' },
        { id: 13, english: 'the rent', french: 'le loyer' },
        { id: 14, english: 'utility bills / service charges', french: 'les charges' },
        { id: 15, english: 'a landlord / property owner', french: 'un propriétaire' },
        { id: 16, english: 'a tenant / renter', french: 'un locataire' },
        { id: 17, english: 'to renovate / to do up', french: 'rénover' },
        { id: 18, english: 'to maintain / to keep in good repair', french: 'entretenir' },
        { id: 19, english: 'to plug in / to connect (an appliance)', french: 'brancher' },
        { id: 20, english: 'the bill / invoice (electricity, phone, etc.)', french: 'la facture' },
    ] },
    { level: 'A1', unit: 3, "id":"city-places","title":"Ville & Lieux","titleFR":"Ville & Lieux","description":"Naviguer les espaces urbains et parler des lieux","descriptionFR":"Naviguer les espaces urbains et parler des lieux","icon":"🏙️","color":"#0EA5E9","wordCount":0, words: [
        { id: 1,  english: 'the town hall / city hall',         french: 'la mairie' },
        { id: 2,  english: 'a pharmacy / chemist',              french: 'une pharmacie' },
        { id: 3,  english: 'a hospital',                        french: 'un hôpital' },
        { id: 4,  english: 'a church',                          french: 'une église' },
        { id: 5,  english: 'a museum',                          french: 'un musée' },
        { id: 6,  english: 'a market',                          french: 'un marché' },
        { id: 7,  english: 'a bank',                            french: 'une banque' },
        { id: 8,  english: 'a post office',                     french: 'la poste' },
        { id: 9,  english: 'a supermarket',                     french: 'un supermarché' },
        { id: 10, english: 'a school',                          french: 'une école' },
        { id: 11, english: 'a library',                         french: 'une bibliothèque' },
        { id: 12, english: 'a park',                            french: 'un parc' },
        { id: 13, english: 'a restaurant',                      french: 'un restaurant' },
        { id: 14, english: 'a hotel',                           french: 'un hôtel' },
        { id: 15, english: 'a cinema / movie theatre',          french: 'un cinéma' },
        { id: 16, english: 'a bakery',                          french: 'une boulangerie' },
        { id: 17, english: 'a bookshop / bookstore',            french: 'une librairie' },
        { id: 18, english: 'a swimming pool',                   french: 'une piscine' },
        { id: 19, english: 'a stadium',                         french: 'un stade' },
        { id: 20, english: 'a neighbourhood / district',        french: 'un quartier' },
    ] },
    { level: 'A1', unit: 3, "id":"clothing-accessories","title":"Vêtements & Accessoires","titleFR":"Vêtements & Accessoires","description":"Mode, vêtements et style personnel","descriptionFR":"Mode, vêtements et style personnel","icon":"👗","color":"#F43F5E","wordCount":0, words: [
        { id: 1,  english: 'clothes / clothing',              french: 'les vêtements' },
        { id: 2,  english: 'a shirt',                         french: 'une chemise' },
        { id: 3,  english: 'trousers / pants',                french: 'un pantalon' },
        { id: 4,  english: 'a dress',                         french: 'une robe' },
        { id: 5,  english: 'shoes',                           french: 'les chaussures' },
        { id: 6,  english: 'a coat',                          french: 'un manteau' },
        { id: 7,  english: 'a hat',                           french: 'un chapeau' },
        { id: 8,  english: 'a bag / handbag',                 french: 'un sac' },
        { id: 9,  english: 'a belt',                          french: 'une ceinture' },
        { id: 10, english: 'gloves',                          french: 'des gants' },
        { id: 11, english: 'a scarf',                         french: 'une écharpe' },
        { id: 12, english: 'socks',                           french: 'des chaussettes' },
        { id: 13, english: 'a jacket',                        french: 'une veste' },
        { id: 14, english: 'a jumper / sweater / pullover',   french: 'un pull' },
        { id: 15, english: 'a skirt',                         french: 'une jupe' },
        { id: 16, english: 'a raincoat',                      french: 'un imperméable' },
        { id: 17, english: 'glasses',                         french: 'des lunettes' },
        { id: 18, english: 'a watch',                         french: 'une montre' },
        { id: 19, english: 'a ring',                          french: 'une bague' },
        { id: 20, english: 'a necklace',                      french: 'un collier' },
    ] },
    { level: 'A1', unit: 1, "id":"days-months","title":"Jours & Mois","titleFR":"Jours & Mois","description":"Vocabulaire du calendrier, jours, mois et dates","descriptionFR":"Vocabulaire du calendrier, jours, mois et dates","icon":"📅","color":"#06B6D4","wordCount":0, words: [
        { id: 1,  english: 'Monday',    french: 'lundi' },
        { id: 2,  english: 'Tuesday',   french: 'mardi' },
        { id: 3,  english: 'Wednesday', french: 'mercredi' },
        { id: 4,  english: 'Thursday',  french: 'jeudi' },
        { id: 5,  english: 'Friday',    french: 'vendredi' },
        { id: 6,  english: 'Saturday',  french: 'samedi' },
        { id: 7,  english: 'Sunday',    french: 'dimanche' },
        { id: 8,  english: 'January',   french: 'janvier' },
        { id: 9,  english: 'February',  french: 'février' },
        { id: 10, english: 'March',     french: 'mars' },
        { id: 11, english: 'April',     french: 'avril' },
        { id: 12, english: 'May',       french: 'mai' },
        { id: 13, english: 'June',      french: 'juin' },
        { id: 14, english: 'July',      french: 'juillet' },
        { id: 15, english: 'August',    french: 'août' },
        { id: 16, english: 'September', french: 'septembre' },
        { id: 17, english: 'October',   french: 'octobre' },
        { id: 18, english: 'November',  french: 'novembre' },
        { id: 19, english: 'December',  french: 'décembre' },
        { id: 20, english: 'a week',    french: 'une semaine' },
    ] },
    { level: 'A1', unit: 1, "id":"nationalities","title":"Nationalités","titleFR":"Nationalités","description":"Pays, nationalités et gentilés","descriptionFR":"Pays, nationalités et gentilés","icon":"🌐","color":"#14B8A6","wordCount":0, words: [
        { id: 1,  english: 'French',      french: 'français(e)' },
        { id: 2,  english: 'France',      french: 'la France' },
        { id: 3,  english: 'English / British', french: 'anglais(e) / britannique' },
        { id: 4,  english: 'the United Kingdom', french: 'le Royaume-Uni' },
        { id: 5,  english: 'American',    french: 'américain(e)' },
        { id: 6,  english: 'the United States', french: 'les États-Unis' },
        { id: 7,  english: 'Spanish',     french: 'espagnol(e)' },
        { id: 8,  english: 'Spain',       french: 'l\'Espagne' },
        { id: 9,  english: 'German',      french: 'allemand(e)' },
        { id: 10, english: 'Germany',     french: 'l\'Allemagne' },
        { id: 11, english: 'Italian',     french: 'italien(ne)' },
        { id: 12, english: 'Italy',       french: 'l\'Italie' },
        { id: 13, english: 'Belgian',     french: 'belge' },
        { id: 14, english: 'Belgium',     french: 'la Belgique' },
        { id: 15, english: 'Swiss',       french: 'suisse' },
        { id: 16, english: 'Switzerland', french: 'la Suisse' },
        { id: 17, english: 'Canadian',    french: 'canadien(ne)' },
        { id: 18, english: 'Canada',      french: 'le Canada' },
        { id: 19, english: 'Moroccan',    french: 'marocain(e)' },
        { id: 20, english: 'I\'m originally from…', french: 'Je suis originaire de…' },
    ] },
    { level: 'A1', unit: 3, "id":"seasons-weather","title":"Saisons & Météo","titleFR":"Saisons & Météo","description":"Conditions météorologiques et changements saisonniers","descriptionFR":"Conditions météorologiques et changements saisonniers","icon":"🌤️","color":"#0284C7","wordCount":0, words: [
        { id: 1,  english: 'spring',                french: 'le printemps' },
        { id: 2,  english: 'summer',                french: 'l\'été' },
        { id: 3,  english: 'autumn / fall',         french: 'l\'automne' },
        { id: 4,  english: 'winter',                french: 'l\'hiver' },
        { id: 5,  english: 'the sun / sunshine',    french: 'le soleil' },
        { id: 6,  english: 'rain',                  french: 'la pluie' },
        { id: 7,  english: 'snow',                  french: 'la neige' },
        { id: 8,  english: 'wind',                  french: 'le vent' },
        { id: 9,  english: 'a cloud',               french: 'un nuage' },
        { id: 10, english: 'a storm / thunderstorm',french: 'un orage' },
        { id: 11, english: 'heat',                  french: 'la chaleur' },
        { id: 12, english: 'cold',                  french: 'le froid' },
        { id: 13, english: 'fog / mist',            french: 'le brouillard' },
        { id: 14, english: 'a rainbow',             french: 'un arc-en-ciel' },
        { id: 15, english: 'temperature',           french: 'la température' },
        { id: 16, english: 'a degree',              french: 'un degré' },
        { id: 17, english: 'weather forecast',      french: 'la météo' },
        { id: 18, english: 'a season',              french: 'une saison' },
        { id: 19, english: 'clear / bright (sky)',  french: 'clair(e)' },
        { id: 20, english: 'overcast / cloudy',     french: 'couvert(e)' },
    ] },
    { level: 'A1', unit: 3, "id":"transport-basics","title":"Transport — Bases","titleFR":"Transport — Bases","description":"Transport quotidien et déplacements","descriptionFR":"Transport quotidien et déplacements","icon":"🚌","color":"#16A34A","wordCount":0, words: [
        { id: 1,  english: 'the underground / subway / metro',  french: 'le métro' },
        { id: 2,  english: 'a bus',                             french: 'un bus' },
        { id: 3,  english: 'a taxi / cab',                      french: 'un taxi' },
        { id: 4,  english: 'a car',                             french: 'une voiture' },
        { id: 5,  english: 'a bicycle / bike',                  french: 'un vélo' },
        { id: 6,  english: 'a train',                           french: 'un train' },
        { id: 7,  english: 'a plane / aeroplane',               french: 'un avion' },
        { id: 8,  english: 'a boat / ship',                     french: 'un bateau' },
        { id: 9,  english: 'a stop / bus stop',                 french: 'un arrêt' },
        { id: 10, english: 'a train station',                   french: 'une gare' },
        { id: 11, english: 'an airport',                        french: 'un aéroport' },
        { id: 12, english: 'a ticket (train / plane)',           french: 'un billet' },
        { id: 13, english: 'a ticket (metro / bus)',             french: 'un ticket' },
        { id: 14, english: 'a line (metro / bus route)',         french: 'une ligne' },
        { id: 15, english: 'a station (metro)',                  french: 'une station' },
        { id: 16, english: 'a platform / quay',                 french: 'un quai' },
        { id: 17, english: 'a driver',                          french: 'un conducteur' },
        { id: 18, english: 'a passenger',                       french: 'un passager' },
        { id: 19, english: 'a return ticket / round trip',      french: 'un aller-retour' },
        { id: 20, english: 'a journey / trip / commute',        french: 'un trajet' },
    ] },
];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsA1: VocabularyData = {
    'a1-au-cafe': [
        { id: 1, english: 'the waiter / server', french: 'le serveur' },
        { id: 2, english: 'a free / available (table)', french: 'libre' },
        { id: 3, english: 'the window', french: 'la fenêtre' },
        { id: 4, english: 'to wish / to want (politely)', french: 'désirer' },
        { id: 5, english: 'I would like', french: 'je voudrais' },
        { id: 6, english: 'a coffee with milk', french: 'un café au lait' },
        { id: 7, english: 'a hot chocolate', french: 'un chocolat chaud' },
        { id: 8, english: 'the drinks / beverages', french: 'les boissons' },
        { id: 9, english: 'to taste / to try (food)', french: 'goûter' },
        { id: 10, english: 'delicious', french: 'délicieux' },
        { id: 11, english: 'of course', french: 'bien sûr' },
        { id: 12, english: 'outside', french: 'dehors' },
        { id: 13, english: 'the neighbourhood / district', french: 'le quartier' },
        { id: 14, english: 'the bill (at a restaurant)', french: 'l\'addition' },
        { id: 15, english: 'service included', french: 'service compris' },
    ],
    'a1-la-famille-martin': [
        { id: 1, english: 'the husband', french: 'le mari' },
        { id: 2, english: 'a doctor', french: 'un médecin' },
        { id: 3, english: 'the hospital', french: 'l\'hôpital' },
        { id: 4, english: 'kind / nice', french: 'gentil' },
        { id: 5, english: 'the children', french: 'les enfants' },
        { id: 6, english: 'the son', french: 'le fils' },
        { id: 7, english: 'the daughter', french: 'la fille' },
        { id: 8, english: 'to draw', french: 'dessiner' },
        { id: 9, english: 'to sing', french: 'chanter' },
        { id: 10, english: 'the flat / apartment', french: 'l\'appartement' },
        { id: 11, english: 'comfortable', french: 'confortable' },
        { id: 12, english: 'the bedrooms', french: 'les chambres' },
        { id: 13, english: 'the living room', french: 'le salon' },
        { id: 14, english: 'a garden', french: 'un jardin' },
        { id: 15, english: 'a walk / stroll', french: 'une promenade' },
    ],
    'a1-une-journee-typique': [
        { id: 1, english: 'the secondary school (ages 11-15)', french: 'le collège' },
        { id: 2, english: 'to get up', french: 'se lever' },
        { id: 3, english: 'to take a shower', french: 'prendre une douche' },
        { id: 4, english: 'to get dressed', french: 's\'habiller' },
        { id: 5, english: 'breakfast', french: 'le petit-déjeuner' },
        { id: 6, english: 'the bread', french: 'le pain' },
        { id: 7, english: 'the butter', french: 'le beurre' },
        { id: 8, english: 'orange juice', french: 'le jus d\'orange' },
        { id: 9, english: 'the bus', french: 'le bus' },
        { id: 10, english: 'the classes / lessons', french: 'les cours' },
        { id: 11, english: 'the school canteen', french: 'la cantine' },
        { id: 12, english: 'the afternoon', french: 'l\'après-midi' },
        { id: 13, english: 'to come home / go back home', french: 'rentrer' },
        { id: 14, english: 'the homework', french: 'les devoirs' },
        { id: 15, english: 'to go to bed', french: 'se coucher' },
    ],
    'a1-au-marche': [
        { id: 1, english: 'the market', french: 'le marché' },
        { id: 2, english: 'the vegetables', french: 'les légumes' },
        { id: 3, english: 'the fruits', french: 'les fruits' },
        { id: 4, english: 'the cheeses', french: 'les fromages' },
        { id: 5, english: 'the merchant / stallholder', french: 'le marchand' },
        { id: 6, english: 'the tomatoes', french: 'des tomates' },
        { id: 7, english: 'How much is it?', french: 'C\'est combien ?' },
        { id: 8, english: 'the kilo', french: 'le kilo' },
        { id: 9, english: 'the carrots', french: 'les carottes' },
        { id: 10, english: 'to give back / to return (change)', french: 'rendre' },
        { id: 11, english: 'the change (coins)', french: 'la monnaie' },
        { id: 12, english: 'have a good day', french: 'bonne journée' },
        { id: 13, english: 'to buy', french: 'acheter' },
        { id: 14, english: 'the apples', french: 'des pommes' },
        { id: 15, english: 'to love / adore', french: 'adorer' },
    ],
    'a1en-first-day': [
        { id: 1, english: 'first day', french: 'le premier jour' },
        { id: 2, english: 'nervous', french: 'nerveux / nerveuse' },
        { id: 3, english: 'children', french: 'les enfants' },
        { id: 4, english: 'classroom', french: 'la salle de classe' },
        { id: 5, english: 'teacher', french: 'le professeur / la maîtresse' },
        { id: 6, english: 'nice', french: 'gentil(le)' },
        { id: 7, english: 'desk', french: 'le bureau / le pupitre' },
        { id: 8, english: 'to welcome', french: 'accueillir' },
        { id: 9, english: 'the alphabet', french: 'l\'alphabet' },
        { id: 10, english: 'lunchtime', french: 'l\'heure du déjeuner' },
        { id: 11, english: 'sandwich', french: 'le sandwich' },
        { id: 12, english: 'friendly', french: 'sympathique / amical(e)' },
        { id: 13, english: 'football', french: 'le football' },
        { id: 14, english: 'friends', french: 'les amis' },
    ],
    'a1en-my-city': [
        { id: 1, english: 'city', french: 'la ville' },
        { id: 2, english: 'park', french: 'le parc' },
        { id: 3, english: 'trees', french: 'les arbres' },
        { id: 4, english: 'lake', french: 'le lac' },
        { id: 5, english: 'to walk (a dog)', french: 'promener' },
        { id: 6, english: 'city centre', french: 'le centre-ville' },
        { id: 7, english: 'shops', french: 'les magasins' },
        { id: 8, english: 'market', french: 'le marché' },
        { id: 9, english: 'cinema', french: 'le cinéma' },
        { id: 10, english: 'train station', french: 'la gare' },
        { id: 11, english: 'to travel', french: 'voyager' },
        { id: 12, english: 'neighbours', french: 'les voisins' },
        { id: 13, english: 'fresh bread', french: 'le pain frais' },
        { id: 14, english: 'vegetables', french: 'les légumes' },
    ],
    'a1en-my-family': [
        { id: 1, english: 'family', french: 'la famille' },
        { id: 2, english: 'house', french: 'la maison' },
        { id: 3, english: 'cat', french: 'le chat' },
        { id: 4, english: 'father', french: 'le père' },
        { id: 5, english: 'doctor', french: 'le médecin' },
        { id: 6, english: 'hospital', french: 'l\'hôpital' },
        { id: 7, english: 'mother', french: 'la mère' },
        { id: 8, english: 'teacher', french: 'le professeur' },
        { id: 9, english: 'to teach', french: 'enseigner' },
        { id: 10, english: 'kind', french: 'gentil(le)' },
        { id: 11, english: 'brother', french: 'le frère' },
        { id: 12, english: 'sister', french: 'la sœur' },
        { id: 13, english: 'to play together', french: 'jouer ensemble' },
        { id: 14, english: 'happy', french: 'heureux / heureuse' },
    ],
    'a1en-my-day': [
        { id: 1, english: 'to get up', french: 'se lever' },
        { id: 2, english: 'to wash', french: 'se laver' },
        { id: 3, english: 'to brush one\'s teeth', french: 'se brosser les dents' },
        { id: 4, english: 'to get dressed', french: 's\'habiller' },
        { id: 5, english: 'breakfast', french: 'le petit-déjeuner' },
        { id: 6, english: 'milk', french: 'le lait' },
        { id: 7, english: 'lessons', french: 'les cours' },
        { id: 8, english: 'art', french: 'le dessin / les arts plastiques' },
        { id: 9, english: 'canteen', french: 'la cantine' },
        { id: 10, english: 'homework', french: 'les devoirs' },
        { id: 11, english: 'outside', french: 'dehors' },
        { id: 12, english: 'dinner', french: 'le dîner' },
        { id: 13, english: 'to go to bed', french: 'se coucher' },
        { id: 14, english: 'tired', french: 'fatigué(e)' },
    ],
    'a1en-the-park': [
        { id: 1, english: 'to shine (sun)', french: 'briller' },
        { id: 2, english: 'park', french: 'le parc' },
        { id: 3, english: 'trees', french: 'les arbres' },
        { id: 4, english: 'flowers', french: 'les fleurs' },
        { id: 5, english: 'grass', french: 'l\'herbe' },
        { id: 6, english: 'to ride a bike', french: 'faire du vélo' },
        { id: 7, english: 'bench', french: 'le banc' },
        { id: 8, english: 'dog', french: 'le chien' },
        { id: 9, english: 'picnic', french: 'le pique-nique' },
        { id: 10, english: 'fruit', french: 'les fruits' },
        { id: 11, english: 'to feed', french: 'nourrir / donner à manger' },
        { id: 12, english: 'ducks', french: 'les canards' },
        { id: 13, english: 'lake', french: 'le lac' },
        { id: 14, english: 'wonderful', french: 'merveilleux / merveilleuse' },
    ],
    'a1en-my-pet': [
        { id: 1, english: 'pet', french: 'l\'animal de compagnie' },
        { id: 2, english: 'dog', french: 'le chien' },
        { id: 3, english: 'brown', french: 'marron / brun(e)' },
        { id: 4, english: 'strong', french: 'fort(e)' },
        { id: 5, english: 'to give', french: 'donner' },
        { id: 6, english: 'quickly', french: 'vite / rapidement' },
        { id: 7, english: 'to go for a walk', french: 'aller se promener' },
        { id: 8, english: 'ball', french: 'la balle / le ballon' },
        { id: 9, english: 'fast', french: 'rapide' },
        { id: 10, english: 'in the evening', french: 'le soir' },
        { id: 11, english: 'to sleep', french: 'dormir' },
        { id: 12, english: 'best friend', french: 'le meilleur ami' },
        { id: 13, english: 'sad', french: 'triste' },
        { id: 14, english: 'to stay', french: 'rester' },
    ],
    'a1en-birthday-party': [
        { id: 1, english: 'birthday', french: 'l\'anniversaire' },
        { id: 2, english: 'cake', french: 'le gâteau' },
        { id: 3, english: 'chocolate', french: 'le chocolat' },
        { id: 4, english: 'candles', french: 'les bougies' },
        { id: 5, english: 'excited', french: 'excité(e) / impatient(e)' },
        { id: 6, english: 'to bring', french: 'apporter' },
        { id: 7, english: 'presents', french: 'les cadeaux' },
        { id: 8, english: 'games', french: 'les jeux' },
        { id: 9, english: 'garden', french: 'le jardin' },
        { id: 10, english: 'ice cream', french: 'la glace' },
        { id: 11, english: 'delicious', french: 'délicieux / délicieuse' },
        { id: 12, english: 'to open', french: 'ouvrir' },
        { id: 13, english: 'toy car', french: 'la petite voiture' },
        { id: 14, english: 'wonderful', french: 'merveilleux / merveilleuse' },
    ],
    'a1en-at-the-zoo': [
        { id: 1, english: 'zoo', french: 'le zoo' },
        { id: 2, english: 'animals', french: 'les animaux' },
        { id: 3, english: 'lions', french: 'les lions' },
        { id: 4, english: 'yellow', french: 'jaune' },
        { id: 5, english: 'elephants', french: 'les éléphants' },
        { id: 6, english: 'grey', french: 'gris(e)' },
        { id: 7, english: 'strong', french: 'fort(e)' },
        { id: 8, english: 'monkeys', french: 'les singes' },
        { id: 9, english: 'funny', french: 'drôle / amusant(e)' },
        { id: 10, english: 'to jump', french: 'sauter' },
        { id: 11, english: 'birds', french: 'les oiseaux' },
        { id: 12, english: 'colours', french: 'les couleurs' },
        { id: 13, english: 'in the afternoon', french: 'l\'après-midi' },
        { id: 14, english: 'tired', french: 'fatigué(e)' },
    ],
    'a1en-a-rainy-day': [
        { id: 1, english: 'to rain', french: 'pleuvoir' },
        { id: 2, english: 'sky', french: 'le ciel' },
        { id: 3, english: 'grey', french: 'gris(e)' },
        { id: 4, english: 'outside', french: 'dehors' },
        { id: 5, english: 'sad', french: 'triste' },
        { id: 6, english: 'idea', french: 'l\'idée' },
        { id: 7, english: 'to draw', french: 'dessiner' },
        { id: 8, english: 'pencils', french: 'les crayons' },
        { id: 9, english: 'hot chocolate', french: 'le chocolat chaud' },
        { id: 10, english: 'warm', french: 'chaud(e)' },
        { id: 11, english: 'sweet', french: 'sucré(e)' },
        { id: 12, english: 'film', french: 'le film' },
        { id: 13, english: 'to laugh', french: 'rire' },
        { id: 14, english: 'to stop', french: 's\'arrêter' },
    ],
    'a1en-my-school': [
        { id: 1, english: 'school', french: 'l\'école' },
        { id: 2, english: 'town centre', french: 'le centre-ville' },
        { id: 3, english: 'building', french: 'le bâtiment' },
        { id: 4, english: 'classrooms', french: 'les salles de classe' },
        { id: 5, english: 'floor (storey)', french: 'l\'étage' },
        { id: 6, english: 'lessons', french: 'les cours' },
        { id: 7, english: 'favourite subject', french: 'la matière préférée' },
        { id: 8, english: 'to paint', french: 'peindre' },
        { id: 9, english: 'sport', french: 'le sport' },
        { id: 10, english: 'gym', french: 'le gymnase' },
        { id: 11, english: 'kind', french: 'gentil(le)' },
        { id: 12, english: 'break time', french: 'la récréation' },
        { id: 13, english: 'playground', french: 'la cour de récréation' },
        { id: 14, english: 'classmates', french: 'les camarades de classe' },
    ],
};
