import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

export const modulesA2: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'A2', unit: 1, "id":"work-professions","title":"Travail & Professions","titleFR":"Travail & Professions","description":"Naviguer le monde du travail en français","descriptionFR":"Naviguer le monde du travail en français","icon":"💼","color":"#F97316","wordCount":0, words: [
        { id: 1, english: 'a trade / occupation / job', french: 'un métier' },
        { id: 2, english: 'a job / employment', french: 'un emploi' },
        { id: 3, english: 'a position / post (at a company)', french: 'un poste' },
        { id: 4, english: 'a salary / wage', french: 'un salaire' },
        { id: 5, english: 'a job application', french: 'une candidature' },
        { id: 6, english: 'an interview (job)', french: 'un entretien' },
        { id: 7, english: 'a boss / employer', french: 'un(e) patron(ne)' },
        { id: 8, english: 'an employee', french: 'un(e) employé(e)' },
        { id: 9, english: 'to be unemployed', french: 'être au chômage' },
        { id: 10, english: 'a permanent contract', french: 'un contrat à durée indéterminée (CDI)' },
        { id: 11, english: 'a fixed-term contract', french: 'un contrat à durée déterminée (CDD)' },
        { id: 12, english: 'paid holiday / paid leave', french: 'les congés payés' },
        { id: 13, english: 'a promotion', french: 'une promotion' },
        { id: 14, english: 'to resign', french: 'démissionner' },
        { id: 15, english: 'to dismiss / to lay off', french: 'licencier' },
        { id: 16, english: 'a trade union', french: 'un syndicat' },
        { id: 17, english: 'overtime', french: 'les heures supplémentaires' },
        { id: 18, english: 'part-time', french: 'à mi-temps' },
        { id: 19, english: 'full-time', french: 'à plein temps' },
        { id: 20, english: 'remote work / working from home', french: 'télétravail' },
    ] },
    { level: 'A2', unit: 1, "id":"weather-nature","title":"Météo & Nature","titleFR":"Météo & Nature","description":"Décrire le monde qui vous entoure","descriptionFR":"Décrire le monde qui vous entoure","icon":"🌿","color":"#14B8A6","wordCount":0, words: [
        { id: 1, english: 'the weather is nice / it\'s sunny', french: 'il fait beau' },
        { id: 2, english: 'it\'s raining', french: 'il pleut' },
        { id: 3, english: 'it\'s snowing', french: 'il neige' },
        { id: 4, english: 'a storm / thunderstorm', french: 'un orage' },
        { id: 5, english: 'a heatwave', french: 'la canicule' },
        { id: 6, english: 'drought', french: 'la sécheresse' },
        { id: 7, english: 'a flood', french: 'une inondation' },
        { id: 8, english: 'fog / mist', french: 'le brouillard' },
        { id: 9, english: 'a cold spell / cold wave', french: 'une vague de froid' },
        { id: 10, english: 'sunny / bright', french: 'ensoleillé(e)' },
        { id: 11, english: 'cloudy / overcast', french: 'nuageux(-euse)' },
        { id: 12, english: 'a forest', french: 'une forêt' },
        { id: 13, english: 'a mountain', french: 'une montagne' },
        { id: 14, english: 'a major river (flowing to the sea)', french: 'un fleuve' },
        { id: 15, english: 'a river / stream (tributary)', french: 'une rivière' },
        { id: 16, english: 'wildlife / fauna', french: 'la faune' },
        { id: 17, english: 'plant life / flora', french: 'la flore' },
        { id: 18, english: 'global warming / climate change', french: 'le réchauffement climatique' },
        { id: 19, english: 'sustainable', french: 'durable' },
        { id: 20, english: 'to protect the environment', french: 'protéger l\'environnement' },
    ] },
    { level: 'A2', unit: 1, "id":"sports-hobbies","title":"Sports & Loisirs","titleFR":"Sports & Loisirs","description":"Parler de ce que vous aimez faire","descriptionFR":"Parler de ce que vous aimez faire","icon":"⚽","color":"#8B5CF6","wordCount":0, words: [
        { id: 1, english: 'to do sport / exercise', french: 'faire du sport' },
        { id: 2, english: 'to train / to practise', french: 's\'entraîner' },
        { id: 3, english: 'a match / game', french: 'un match' },
        { id: 4, english: 'to score a goal', french: 'marquer un but' },
        { id: 5, english: 'a tournament', french: 'un tournoi' },
        { id: 6, english: 'swimming', french: 'la natation' },
        { id: 7, english: 'hiking / trekking', french: 'la randonnée' },
        { id: 8, english: 'cycling', french: 'le cyclisme' },
        { id: 9, english: 'horse riding', french: 'l\'équitation' },
        { id: 10, english: 'martial arts', french: 'les arts martiaux' },
        { id: 11, english: 'a hobby / pastime', french: 'un passe-temps' },
        { id: 12, english: 'painting', french: 'la peinture' },
        { id: 13, english: 'photography', french: 'la photographie' },
        { id: 14, english: 'to volunteer', french: 'faire du bénévolat' },
        { id: 15, english: 'to play an instrument', french: 'jouer d\'un instrument' },
        { id: 16, english: 'to attend (an event)', french: 'assister à' },
        { id: 17, english: 'a competition', french: 'une compétition' },
        { id: 18, english: 'a champion', french: 'un champion / une championne' },
        { id: 19, english: 'to be a fan of', french: 'être fan de' },
        { id: 20, english: 'leisure activities / free-time pursuits', french: 'les loisirs' },
    ] },
    { level: 'A2', unit: 1, "id":"school-education","title":"École & Éducation","titleFR":"École & Éducation","description":"Vocabulaire académique et scolaire","descriptionFR":"Vocabulaire académique et scolaire","icon":"📚","color":"#0EA5E9","wordCount":0, words: [
        { id: 1, english: 'a school / educational establishment', french: 'un établissement scolaire' },
        { id: 2, english: 'a secondary school (ages 15-18)', french: 'un lycée' },
        { id: 3, english: 'a university', french: 'une université' },
        { id: 4, english: 'a school subject', french: 'une matière' },
        { id: 5, english: 'mathematics', french: 'les mathématiques' },
        { id: 6, english: 'science', french: 'les sciences' },
        { id: 7, english: 'history', french: 'l\'histoire' },
        { id: 8, english: 'modern foreign languages', french: 'les langues vivantes' },
        { id: 9, english: 'a lecture', french: 'un cours magistral' },
        { id: 10, english: 'a presentation / oral report', french: 'un exposé' },
        { id: 11, english: 'homework / an assignment', french: 'un devoir' },
        { id: 12, english: 'to write up / to draft (an essay, report)', french: 'rédiger' },
        { id: 13, english: 'to research / to gather information', french: 'se documenter' },
        { id: 14, english: 'to revise / to review (for an exam)', french: 'réviser' },
        { id: 15, english: 'to sit / take an exam', french: 'passer un examen' },
        { id: 16, english: 'to pass an exam', french: 'réussir un examen' },
        { id: 17, english: 'to fail an exam', french: 'échouer à un examen' },
        { id: 18, english: 'a degree / qualification / diploma', french: 'un diplôme' },
        { id: 19, english: 'a scholarship / study grant', french: 'une bourse d\'études' },
        { id: 20, english: 'learning / apprenticeship', french: 'l\'apprentissage' },
    ] },
    { level: 'A2', unit: 3, "id":"shopping-money","title":"Shopping & Argent","titleFR":"Shopping & Argent","description":"Acheter, vendre et gérer ses finances","descriptionFR":"Acheter, vendre et gérer ses finances","icon":"🛍️","color":"#F43F5E","wordCount":0, words: [
        { id: 1, english: 'to go shopping (for groceries)', french: 'faire des courses' },
        { id: 2, english: 'to go shopping (for clothes/fun)', french: 'faire du shopping' },
        { id: 3, english: 'a shop / store', french: 'un magasin' },
        { id: 4, english: 'a shop window / display', french: 'une vitrine' },
        { id: 5, english: 'the sales (seasonal discounts)', french: 'les soldes' },
        { id: 6, english: 'a special offer / deal', french: 'une promotion' },
        { id: 7, english: 'the price', french: 'le prix' },
        { id: 8, english: 'expensive', french: 'cher / chère' },
        { id: 9, english: 'cheap / inexpensive', french: 'bon marché' },
        { id: 10, english: 'to reimburse / to refund', french: 'rembourser' },
        { id: 11, english: 'a receipt', french: 'un reçu' },
        { id: 12, english: 'to pay in cash', french: 'payer en espèces' },
        { id: 13, english: 'to pay by card', french: 'payer par carte' },
        { id: 14, english: 'to save (money)', french: 'économiser' },
        { id: 15, english: 'to spend (money)', french: 'dépenser' },
        { id: 16, english: 'a budget', french: 'un budget' },
        { id: 17, english: 'indebtedness / debt', french: 'endettement' },
        { id: 18, english: 'a bank transfer', french: 'un virement bancaire' },
        { id: 19, english: 'the exchange rate', french: 'le taux de change' },
        { id: 20, english: 'on credit / on hire purchase', french: 'à crédit' },
    ] },
    { level: 'A2', unit: 3, "id":"animals","title":"Animaux","titleFR":"Animaux","description":"Faune, animaux domestiques et règne animal","descriptionFR":"Faune, animaux domestiques et règne animal","icon":"🐾","color":"#10B981","wordCount":0, words: [
        { id: 1,  english: 'a dog',                  french: 'un chien' },
        { id: 2,  english: 'a cat',                  french: 'un chat' },
        { id: 3,  english: 'a rabbit',               french: 'un lapin' },
        { id: 4,  english: 'a hamster',              french: 'un hamster' },
        { id: 5,  english: 'a (pet) fish',           french: 'un poisson' },
        { id: 6,  english: 'a bird',                 french: 'un oiseau' },
        { id: 7,  english: 'a cow',                  french: 'une vache' },
        { id: 8,  english: 'a horse',                french: 'un cheval' },
        { id: 9,  english: 'a pig',                  french: 'un cochon' },
        { id: 10, english: 'a sheep',                french: 'un mouton' },
        { id: 11, english: 'a hen / chicken',        french: 'une poule' },
        { id: 12, english: 'a lion',                 french: 'un lion' },
        { id: 13, english: 'a tiger',                french: 'un tigre' },
        { id: 14, english: 'an elephant',            french: 'un éléphant' },
        { id: 15, english: 'a monkey',               french: 'un singe' },
        { id: 16, english: 'a snake',                french: 'un serpent' },
        { id: 17, english: 'a bear',                 french: 'un ours' },
        { id: 18, english: 'a wolf',                 french: 'un loup' },
        { id: 19, english: 'a bee',                  french: 'une abeille' },
        { id: 20, english: 'a butterfly',            french: 'un papillon' },
    ] },
    { level: 'A2', unit: 1, "id":"celebrations-events","title":"Célébrations & Événements","titleFR":"Célébrations & Événements","description":"Fêtes, cérémonies et occasions spéciales","descriptionFR":"Fêtes, cérémonies et occasions spéciales","icon":"🎉","color":"#F59E0B","wordCount":0, words: [
        { id: 1,  english: 'a birthday',              french: 'un anniversaire' },
        { id: 2,  english: 'a wedding',               french: 'un mariage' },
        { id: 3,  english: 'a party / celebration',   french: 'une fête' },
        { id: 4,  english: 'a gift / present',        french: 'un cadeau' },
        { id: 5,  english: 'an invitation',           french: 'une invitation' },
        { id: 6,  english: 'a ceremony',              french: 'une cérémonie' },
        { id: 7,  english: 'a meeting / gathering',   french: 'une réunion' },
        { id: 8,  english: 'a concert',               french: 'un concert' },
        { id: 9,  english: 'an exhibition',           french: 'une exposition' },
        { id: 10, english: 'a show / performance',    french: 'un spectacle' },
        { id: 11, english: 'a ticket (event)',        french: 'un billet' },
        { id: 12, english: 'congratulations',         french: 'félicitations' },
        { id: 13, english: 'a guest',                 french: 'un(e) invité(e)' },
        { id: 14, english: 'a host',                  french: 'un(e) hôte' },
        { id: 15, english: 'a banquet / feast',       french: 'un banquet' },
        { id: 16, english: 'a toast (speech)',        french: 'un toast' },
        { id: 17, english: 'champagne',               french: 'le champagne' },
        { id: 18, english: 'a souvenir / memory',     french: 'un souvenir' },
        { id: 19, english: 'a tradition',             french: 'une tradition' },
        { id: 20, english: 'a programme',             french: 'un programme' },
    ] },
    { level: 'A2', unit: 1, "id":"food-culture","title":"Culture culinaire","titleFR":"Culture culinaire","description":"Gastronomie, cuisine et traditions alimentaires françaises","descriptionFR":"Gastronomie, cuisine et traditions alimentaires françaises","icon":"🥗","color":"#EF4444","wordCount":0, words: [
        { id: 1,  english: 'a bakery',                      french: 'une boulangerie' },
        { id: 2,  english: 'a cake shop / patisserie',      french: 'une pâtisserie' },
        { id: 3,  english: 'a delicatessen',                french: 'une charcuterie' },
        { id: 4,  english: 'a cheese shop',                 french: 'une fromagerie' },
        { id: 5,  english: 'a grocer\'s / small food shop', french: 'une épicerie' },
        { id: 6,  english: 'a market',                      french: 'un marché' },
        { id: 7,  english: 'a recipe',                      french: 'une recette' },
        { id: 8,  english: 'an ingredient',                 french: 'un ingrédient' },
        { id: 9,  english: 'to cook',                       french: 'cuisiner' },
        { id: 10, english: 'pre-dinner drinks / aperitif',  french: 'l\'apéritif' },
        { id: 11, english: 'a starter / appetiser',         french: 'une entrée' },
        { id: 12, english: 'a main course',                 french: 'un plat principal' },
        { id: 13, english: 'dessert',                       french: 'le dessert' },
        { id: 14, english: 'a set menu',                    french: 'un menu' },
        { id: 15, english: 'a (à la carte) menu',           french: 'la carte' },
        { id: 16, english: 'a portion / serving',           french: 'une portion' },
        { id: 17, english: 'vegetarian',                    french: 'végétarien(ne)' },
        { id: 18, english: 'a regional speciality',         french: 'une spécialité' },
        { id: 19, english: 'terroir (local land and produce)', french: 'le terroir' },
        { id: 20, english: 'home-made',                     french: 'fait(e) maison' },
    ] },
    { level: 'A2', unit: 3, "id":"health-doctor","title":"Santé & Médecin","titleFR":"Santé & Médecin","description":"Vocabulaire médical et consultations chez le médecin","descriptionFR":"Vocabulaire médical et consultations chez le médecin","icon":"🩺","color":"#DC2626","wordCount":0, words: [
        { id: 1,  english: 'a doctor / GP',                 french: 'un médecin' },
        { id: 2,  english: 'a prescription',                french: 'une ordonnance' },
        { id: 3,  english: 'a medication / medicine',       french: 'un médicament' },
        { id: 4,  english: 'pain / an ache',                french: 'une douleur' },
        { id: 5,  english: 'a fever',                       french: 'la fièvre' },
        { id: 6,  english: 'a cold',                        french: 'un rhume' },
        { id: 7,  english: 'the flu / influenza',           french: 'la grippe' },
        { id: 8,  english: 'an allergy',                    french: 'une allergie' },
        { id: 9,  english: 'an injury / a wound',           french: 'une blessure' },
        { id: 10, english: 'A&E / emergency room',          french: 'les urgences' },
        { id: 11, english: 'a nurse',                       french: 'un(e) infirmier(-ière)' },
        { id: 12, english: 'an appointment',                french: 'un rendez-vous' },
        { id: 13, english: 'a symptom',                     french: 'un symptôme' },
        { id: 14, english: 'treatment',                     french: 'un traitement' },
        { id: 15, english: 'a tablet / pill',               french: 'un comprimé' },
        { id: 16, english: 'syrup / liquid medicine',       french: 'un sirop' },
        { id: 17, english: 'a plaster / bandage',           french: 'un pansement' },
        { id: 18, english: 'blood pressure',                french: 'la tension' },
        { id: 19, english: 'an X-ray / scan',               french: 'une radio' },
        { id: 20, english: 'an examination / check-up',     french: 'un examen' },
    ] },
    { level: 'A2', unit: 1, "id":"personality-character","title":"Personnalité & Caractère","titleFR":"Personnalité & Caractère","description":"Décrire les traits de personnalité et le caractère","descriptionFR":"Décrire les traits de personnalité et le caractère","icon":"🧑","color":"#F97316","wordCount":0, words: [
        { id: 1,  english: 'generous',     french: 'généreux(-euse)' },
        { id: 2,  english: 'shy / timid',  french: 'timide' },
        { id: 3,  english: 'brave / courageous', french: 'courageux(-euse)' },
        { id: 4,  english: 'patient',      french: 'patient(e)' },
        { id: 5,  english: 'curious',      french: 'curieux(-euse)' },
        { id: 6,  english: 'honest',       french: 'honnête' },
        { id: 7,  english: 'funny / amusing', french: 'drôle' },
        { id: 8,  english: 'serious',      french: 'sérieux(-euse)' },
        { id: 9,  english: 'creative',     french: 'créatif(-ive)' },
        { id: 10, english: 'ambitious',    french: 'ambitieux(-euse)' },
        { id: 11, english: 'lazy',         french: 'paresseux(-euse)' },
        { id: 12, english: 'chatty / talkative', french: 'bavard(e)' },
        { id: 13, english: 'discreet / reserved', french: 'discret(-ète)' },
        { id: 14, english: 'stubborn',     french: 'têtu(e)' },
        { id: 15, english: 'optimistic',   french: 'optimiste' },
        { id: 16, english: 'pessimistic',  french: 'pessimiste' },
        { id: 17, english: 'sociable',     french: 'sociable' },
        { id: 18, english: 'independent',  french: 'indépendant(e)' },
        { id: 19, english: 'sensitive',    french: 'sensible' },
        { id: 20, english: 'reliable / trustworthy', french: 'fiable' },
    ] },
    { level: 'A2', unit: 1, "id":"seasons-activities","title":"Saisons & Activités","titleFR":"Saisons & Activités","description":"Vocabulaire saisonnier et activités de loisirs","descriptionFR":"Vocabulaire saisonnier et activités de loisirs","icon":"🍂","color":"#D97706","wordCount":0, words: [
        { id: 1,  english: 'skiing',                        french: 'le ski' },
        { id: 2,  english: 'the beach',                     french: 'la plage' },
        { id: 3,  english: 'gardening',                     french: 'le jardinage' },
        { id: 4,  english: 'hiking / a hike',               french: 'la randonnée' },
        { id: 5,  english: 'a picnic',                      french: 'un pique-nique' },
        { id: 6,  english: 'swimming',                      french: 'la natation' },
        { id: 7,  english: 'cycling',                       french: 'le vélo' },
        { id: 8,  english: 'camping',                       french: 'le camping' },
        { id: 9,  english: 'Bastille Day (14 July)',         french: 'la fête nationale' },
        { id: 10, english: 'Christmas',                     french: 'Noël' },
        { id: 11, english: 'Easter',                        french: 'Pâques' },
        { id: 12, english: 'the grape harvest / vendanges', french: 'les vendanges' },
        { id: 13, english: 'back to school / September',    french: 'la rentrée' },
        { id: 14, english: 'school holidays',               french: 'les vacances scolaires' },
        { id: 15, english: 'a long weekend / bridge',       french: 'un pont' },
        { id: 16, english: 'a public holiday',              french: 'un jour férié' },
        { id: 17, english: 'the sales',                     french: 'les soldes' },
        { id: 18, english: 'a carnival',                    french: 'un carnaval' },
        { id: 19, english: 'Valentine\'s Day',              french: 'la Saint-Valentin' },
        { id: 20, english: 'Mother\'s Day',                 french: 'la fête des mères' },
    ] },
    { level: 'A2', unit: 3, "id":"transport-travel","title":"Transport & Voyage","titleFR":"Transport & Voyage","description":"Voyages longue distance, aéroports et réservations","descriptionFR":"Voyages longue distance, aéroports et réservations","icon":"✈️","color":"#2563EB","wordCount":0, words: [
        { id: 1,  english: 'a ticket (train / plane)',       french: 'un billet' },
        { id: 2,  english: 'a booking / a reservation',      french: 'une réservation' },
        { id: 3,  english: 'a timetable / schedule',         french: 'un horaire' },
        { id: 4,  english: 'departure',                      french: 'le départ' },
        { id: 5,  english: 'arrival',                        french: 'l\'arrivée' },
        { id: 6,  english: 'a connection / transfer',        french: 'une correspondance' },
        { id: 7,  english: 'a delay',                        french: 'un retard' },
        { id: 8,  english: 'first class',                    french: 'la première classe' },
        { id: 9,  english: 'luggage / baggage',              french: 'les bagages' },
        { id: 10, english: 'a suitcase',                     french: 'une valise' },
        { id: 11, english: 'a passport',                     french: 'un passeport' },
        { id: 12, english: 'customs',                        french: 'la douane' },
        { id: 13, english: 'a flight',                       french: 'un vol' },
        { id: 14, english: 'boarding',                       french: 'l\'embarquement' },
        { id: 15, english: 'a stopover / layover',           french: 'une escale' },
        { id: 16, english: 'a seat',                         french: 'un siège' },
        { id: 17, english: 'a (train) carriage / car',       french: 'un wagon' },
        { id: 18, english: 'a ticket inspector / conductor', french: 'un contrôleur' },
        { id: 19, english: 'a cancellation',                 french: 'une annulation' },
        { id: 20, english: 'a refund',                       french: 'un remboursement' },
    ] },
];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsA2: VocabularyData = {
    'a2-une-journee-typique': [
        { id: 1, english: 'a student', french: 'une étudiante' },
        { id: 2, english: 'as usual', french: 'comme d\'habitude' },
        { id: 3, english: 'to take a shower', french: 'se doucher' },
        { id: 4, english: 'quickly', french: 'rapidement' },
        { id: 5, english: 'the news', french: 'les nouvelles' },
        { id: 6, english: 'the tram', french: 'le tram' },
        { id: 7, english: 'the university / faculty', french: 'la faculté' },
        { id: 8, english: 'to last', french: 'durer' },
        { id: 9, english: 'to explain', french: 'expliquer' },
        { id: 10, english: 'to concentrate', french: 'se concentrer' },
        { id: 11, english: 'to meet up with / to find again', french: 'retrouver' },
        { id: 12, english: 'an evening party / get-together', french: 'une soirée' },
        { id: 13, english: 'to invite', french: 'inviter' },
        { id: 14, english: 'the library', french: 'la bibliothèque' },
        { id: 15, english: 'a presentation / oral report', french: 'un exposé' },
    ],
    'a2-vacances-en-bretagne': [
        { id: 1, english: 'last summer', french: 'l\'été dernier' },
        { id: 2, english: 'to book / reserve', french: 'réserver' },
        { id: 3, english: 'a holiday cottage / gîte', french: 'un gîte' },
        { id: 4, english: 'the sea', french: 'la mer' },
        { id: 5, english: 'the journey / trip', french: 'le trajet' },
        { id: 6, english: 'to shine (the sun)', french: 'briller' },
        { id: 7, english: 'the beach', french: 'la plage' },
        { id: 8, english: 'to go for a swim / to bathe', french: 'se baigner' },
        { id: 9, english: 'the cliffs', french: 'les falaises' },
        { id: 10, english: 'the rocks', french: 'les rochers' },
        { id: 11, english: 'the fishing boats', french: 'des bateaux de pêche' },
        { id: 12, english: 'the crossing (by boat)', french: 'la traversée' },
        { id: 13, english: 'to rent / hire', french: 'louer' },
        { id: 14, english: 'hidden coves', french: 'des criques cachées' },
        { id: 15, english: 'seafood', french: 'les fruits de mer' },
    ],
    'a2-le-marche': [
        { id: 1, english: 'to go (to a place)', french: 'se rendre' },
        { id: 2, english: 'fresh produce', french: 'des produits frais' },
        { id: 3, english: 'local producers', french: 'les producteurs locaux' },
        { id: 4, english: 'to plan / to intend', french: 'prévoir' },
        { id: 5, english: 'seasonal vegetables', french: 'des légumes de saison' },
        { id: 6, english: 'the greengrocer / market gardener', french: 'le maraîcher' },
        { id: 7, english: 'the courgettes / zucchini', french: 'des courgettes' },
        { id: 8, english: 'the aubergines / eggplants', french: 'des aubergines' },
        { id: 9, english: 'the (bell) peppers', french: 'des poivrons' },
        { id: 10, english: 'the farm', french: 'la ferme' },
        { id: 11, english: 'organic', french: 'bio' },
        { id: 12, english: 'to pick / to harvest', french: 'cueillir' },
        { id: 13, english: 'olive oil', french: 'l\'huile d\'olive' },
        { id: 14, english: 'fresh herbs', french: 'des herbes fraîches' },
        { id: 15, english: 'a neighbour', french: 'une voisine' },
    ],
    'a2-une-lettre-damitie': [
        { id: 1, english: 'dear (to a woman)', french: 'chère' },
        { id: 2, english: 'I miss you', french: 'tu me manques' },
        { id: 3, english: 'since your departure', french: 'depuis ton départ' },
        { id: 4, english: 'a job / position', french: 'un poste' },
        { id: 5, english: 'to learn', french: 'apprendre' },
        { id: 6, english: 'the colleagues', french: 'les collègues' },
        { id: 7, english: 'the atmosphere / mood', french: 'l\'ambiance' },
        { id: 8, english: 'the city centre', french: 'le centre-ville' },
        { id: 9, english: 'an exhibition', french: 'une exposition' },
        { id: 10, english: 'to remind / to recall', french: 'rappeler' },
        { id: 11, english: 'to have a drink', french: 'prendre un verre' },
        { id: 12, english: 'a piece of news', french: 'une nouvelle' },
        { id: 13, english: 'then / next', french: 'puis' },
        { id: 14, english: 'to visit (someone)', french: 'rendre visite' },
        { id: 15, english: 'lots of love (closing)', french: 'grosses bises' },
    ],
    'a2-recette-francaise': [
        { id: 1, english: 'the apple tart', french: 'la tarte aux pommes' },
        { id: 2, english: 'appreciated / liked', french: 'apprécié' },
        { id: 3, english: 'the recipe', french: 'la recette' },
        { id: 4, english: 'to prepare / make', french: 'préparer' },
        { id: 5, english: 'the shortcrust pastry', french: 'la pâte brisée' },
        { id: 6, english: 'a tablespoon', french: 'une cuillère à soupe' },
        { id: 7, english: 'the sugar', french: 'le sucre' },
        { id: 8, english: 'the cinnamon', french: 'la cannelle' },
        { id: 9, english: 'the butter', french: 'le beurre' },
        { id: 10, english: 'to preheat', french: 'préchauffer' },
        { id: 11, english: 'the oven', french: 'le four' },
        { id: 12, english: 'to peel', french: 'éplucher' },
        { id: 13, english: 'thin slices', french: 'des fines lamelles' },
        { id: 14, english: 'a mould / baking tin', french: 'un moule' },
        { id: 15, english: 'to bake / cook', french: 'faire cuire' },
    ],
    'a2en-weekend-trip': [
        { id: 1, english: 'weekend', french: 'le week-end' },
        { id: 2, english: 'to travel by train', french: 'voyager en train' },
        { id: 3, english: 'sights', french: 'les sites touristiques' },
        { id: 4, english: 'to arrive', french: 'arriver' },
        { id: 5, english: 'to queue', french: 'faire la queue' },
        { id: 6, english: 'worth it', french: 'qui en vaut la peine' },
        { id: 7, english: 'spectacular', french: 'spectaculaire' },
        { id: 8, english: 'bridge', french: 'le pont' },
        { id: 9, english: 'hungry', french: 'avoir faim' },
        { id: 10, english: 'art gallery', french: 'la galerie d\'art' },
        { id: 11, english: 'boat trip', french: 'la promenade en bateau' },
        { id: 12, english: 'to set (sun)', french: 'se coucher' },
        { id: 13, english: 'to explore', french: 'explorer' },
        { id: 14, english: 'a jar of honey', french: 'un pot de miel' },
        { id: 15, english: 'to agree', french: 'être d\'accord' },
    ],
    'a2en-job-interview': [
        { id: 1, english: 'to look for a job', french: 'chercher un emploi' },
        { id: 2, english: 'marketing company', french: 'l\'entreprise de marketing' },
        { id: 3, english: 'to invite', french: 'inviter / convier' },
        { id: 4, english: 'interview', french: 'l\'entretien' },
        { id: 5, english: 'excited', french: 'enthousiaste / excité(e)' },
        { id: 6, english: 'nervous', french: 'nerveux / nerveuse' },
        { id: 7, english: 'to prepare', french: 'se préparer' },
        { id: 8, english: 'suit', french: 'le costume / le tailleur' },
        { id: 9, english: 'to practise', french: 's\'entraîner' },
        { id: 10, english: 'rested', french: 'reposé(e)' },
        { id: 11, english: 'manager', french: 'le / la responsable' },
        { id: 12, english: 'experience', french: 'l\'expérience' },
        { id: 13, english: 'strengths', french: 'les points forts' },
        { id: 14, english: 'to offer (a job)', french: 'proposer / offrir' },
        { id: 15, english: 'challenge', french: 'le défi' },
    ],
    'a2en-shopping-trip': [
        { id: 1, english: 'to go shopping', french: 'faire des courses / du shopping' },
        { id: 2, english: 'clothes', french: 'les vêtements' },
        { id: 3, english: 'busy', french: 'animé(e) / bondé(e)' },
        { id: 4, english: 'sale', french: 'les soldes' },
        { id: 5, english: 'cheaper', french: 'moins cher' },
        { id: 6, english: 'to try on', french: 'essayer' },
        { id: 7, english: 'dress', french: 'la robe' },
        { id: 8, english: 'expensive', french: 'cher / chère' },
        { id: 9, english: 'to fit', french: 'aller (à quelqu\'un)' },
        { id: 10, english: 'a pair of jeans', french: 'un jean' },
        { id: 11, english: 'to order', french: 'commander' },
        { id: 12, english: 'orange juice', french: 'le jus d\'orange' },
        { id: 13, english: 'holidays', french: 'les vacances' },
        { id: 14, english: 'to spend (money)', french: 'dépenser' },
        { id: 15, english: 'to laugh', french: 'rire' },
    ],
    'a2en-holiday-plans': [
        { id: 1, english: 'to plan', french: 'planifier / organiser' },
        { id: 2, english: 'to relax', french: 'se détendre' },
        { id: 3, english: 'quiet', french: 'calme / tranquille' },
        { id: 4, english: 'to decide', french: 'décider' },
        { id: 5, english: 'website', french: 'le site web' },
        { id: 6, english: 'mountains', french: 'les montagnes' },
        { id: 7, english: 'fresh air', french: 'l\'air frais' },
        { id: 8, english: 'beach', french: 'la plage' },
        { id: 9, english: 'to swim', french: 'nager' },
        { id: 10, english: 'village', french: 'le village' },
        { id: 11, english: 'coast', french: 'la côte' },
        { id: 12, english: 'walking paths', french: 'les sentiers de randonnée' },
        { id: 13, english: 'reviews', french: 'les avis / les critiques' },
        { id: 14, english: 'to book', french: 'réserver' },
        { id: 15, english: 'to pack', french: 'faire ses valises' },
    ],
    'a2en-new-flatmate': [
        { id: 1, english: 'to move', french: 'déménager' },
        { id: 2, english: 'university', french: 'l\'université' },
        { id: 3, english: 'student halls', french: 'la résidence universitaire' },
        { id: 4, english: 'expensive', french: 'cher / chère' },
        { id: 5, english: 'to share a flat', french: 'partager un appartement' },
        { id: 6, english: 'advert', french: 'l\'annonce' },
        { id: 7, english: 'campus', french: 'le campus' },
        { id: 8, english: 'to arrange', french: 'organiser / convenir de' },
        { id: 9, english: 'bright', french: 'lumineux / lumineuse' },
        { id: 10, english: 'comfortable', french: 'confortable' },
        { id: 11, english: 'flatmates', french: 'les colocataires' },
        { id: 12, english: 'engineering', french: 'l\'ingénierie' },
        { id: 13, english: 'welcoming', french: 'accueillant(e)' },
        { id: 14, english: 'shy', french: 'timide' },
        { id: 15, english: 'glad', french: 'content(e) / ravi(e)' },
    ],
    'a2en-lost-in-town': [
        { id: 1, english: 'worried', french: 'inquiet / inquiète' },
        { id: 2, english: 'battery', french: 'la batterie' },
        { id: 3, english: 'to die (battery)', french: 'se décharger / tomber en panne' },
        { id: 4, english: 'to ask for help', french: 'demander de l\'aide' },
        { id: 5, english: 'bench', french: 'le banc' },
        { id: 6, english: 'newspaper', french: 'le journal' },
        { id: 7, english: 'Excuse me', french: 'Excusez-moi' },
        { id: 8, english: 'to go straight on', french: 'aller tout droit' },
        { id: 9, english: 'to turn left', french: 'tourner à gauche' },
        { id: 10, english: 'traffic light', french: 'le feu de circulation' },
        { id: 11, english: 'directions', french: 'les indications' },
        { id: 12, english: 'corner', french: 'le coin' },
        { id: 13, english: 'relieved', french: 'soulagé(e)' },
        { id: 14, english: 'strangers', french: 'les inconnus' },
        { id: 15, english: 'to discover', french: 'découvrir' },
    ],
    'a2en-cooking-dinner': [
        { id: 1, english: 'to invite', french: 'inviter' },
        { id: 2, english: 'to cook', french: 'cuisiner' },
        { id: 3, english: 'meal', french: 'le repas' },
        { id: 4, english: 'recipes', french: 'les recettes' },
        { id: 5, english: 'tomato sauce', french: 'la sauce tomate' },
        { id: 6, english: 'salad', french: 'la salade' },
        { id: 7, english: 'ingredients', french: 'les ingrédients' },
        { id: 8, english: 'garlic', french: 'l\'ail' },
        { id: 9, english: 'onions', french: 'les oignons' },
        { id: 10, english: 'guests', french: 'les invités' },
        { id: 11, english: 'to burn', french: 'brûler' },
        { id: 12, english: 'to taste', french: 'goûter' },
        { id: 13, english: 'to smell wonderful', french: 'sentir merveilleusement bon' },
        { id: 14, english: 'proud', french: 'fier / fière' },
        { id: 15, english: 'success', french: 'le succès / la réussite' },
    ],
    'a2en-the-concert': [
        { id: 1, english: 'band', french: 'le groupe (de musique)' },
        { id: 2, english: 'ticket', french: 'le billet' },
        { id: 3, english: 'stage', french: 'la scène' },
        { id: 4, english: 'stadium', french: 'le stade' },
        { id: 5, english: 'enormous', french: 'énorme' },
        { id: 6, english: 'atmosphere', french: 'l\'ambiance' },
        { id: 7, english: 'electric (atmosphere)', french: 'électrique / survolté(e)' },
        { id: 8, english: 'crowd', french: 'la foule' },
        { id: 9, english: 'to cheer', french: 'acclamer' },
        { id: 10, english: 'to sing along', french: 'chanter en chœur' },
        { id: 11, english: 'unforgettable', french: 'inoubliable' },
        { id: 12, english: 'fan', french: 'le / la fan' },
        { id: 13, english: 'to hum', french: 'fredonner' },
        { id: 14, english: 'to remember', french: 'se souvenir' },
        { id: 15, english: 'to enjoy', french: 'apprécier / aimer' },
    ],
    'a2en-moving-house': [
        { id: 1, english: 'to move house', french: 'déménager' },
        { id: 2, english: 'flat', french: 'l\'appartement' },
        { id: 3, english: 'to grow older', french: 'grandir / vieillir' },
        { id: 4, english: 'neighbourhood', french: 'le quartier' },
        { id: 5, english: 'to pack', french: 'emballer / faire les cartons' },
        { id: 6, english: 'belongings', french: 'les affaires / les biens' },
        { id: 7, english: 'boxes', french: 'les cartons' },
        { id: 8, english: 'removal van', french: 'le camion de déménagement' },
        { id: 9, english: 'furniture', french: 'les meubles' },
        { id: 10, english: 'to unpack', french: 'déballer' },
        { id: 11, english: 'neighbours', french: 'les voisins' },
        { id: 12, english: 'homemade', french: 'fait(e) maison' },
        { id: 13, english: 'laughter', french: 'les rires' },
        { id: 14, english: 'memories', french: 'les souvenirs' },
        { id: 15, english: 'decision', french: 'la décision' },
    ],
    'a2en-summer-job': [
        { id: 1, english: 'summer holidays', french: 'les vacances d\'été' },
        { id: 2, english: 'to earn money', french: 'gagner de l\'argent' },
        { id: 3, english: 'to gain experience', french: 'acquérir de l\'expérience' },
        { id: 4, english: 'waiter', french: 'le serveur' },
        { id: 5, english: 'orders', french: 'les commandes' },
        { id: 6, english: 'trays', french: 'les plateaux' },
        { id: 7, english: 'polite', french: 'poli(e)' },
        { id: 8, english: 'rude', french: 'impoli(e) / grossier(-ière)' },
        { id: 9, english: 'embarrassed', french: 'gêné(e) / embarrassé(e)' },
        { id: 10, english: 'patient', french: 'patient(e)' },
        { id: 11, english: 'confident', french: 'sûr(e) de soi / confiant(e)' },
        { id: 12, english: 'under pressure', french: 'sous pression' },
        { id: 13, english: 'colleagues', french: 'les collègues' },
        { id: 14, english: 'teamwork', french: 'le travail d\'équipe' },
        { id: 15, english: 'pride', french: 'la fierté' },
    ],
};
