import type { VocabularyModule, VocabularyData, VocabularyWord } from '../../../types/vocabulary';

export const modulesB2: (VocabularyModule & { words: VocabularyWord[] })[] = [
    { level: 'B2', unit: 1, "id":"travel-culture","title":"Voyage & Culture","titleFR":"Voyage & Culture","description":"Naviguer les sujets de voyage et de culture","descriptionFR":"Naviguer les sujets de voyage et de culture","icon":"✈️","color":"#2563EB","wordCount":0, words: [
        { id: 1, english: 'heritage / cultural legacy', french: 'le patrimoine' },
        { id: 2, english: 'a stay / a trip (of several days)', french: 'un séjour' },
        { id: 3, english: 'to navigate / to find one\'s way around', french: 'se repérer' },
        { id: 4, english: 'the feeling of being abroad / of a change of scene', french: 'le dépaysement' },
        { id: 5, english: 'an itinerary / a travel plan', french: 'un itinéraire' },
        { id: 6, english: 'customs / traditions (of a people)', french: 'les us et coutumes' },
        { id: 7, english: 'a landmark / a point of reference', french: 'un repère' },
        { id: 8, english: 'to immerse oneself in (a culture)', french: 's\'immerger dans' },
        { id: 9, english: 'a layover / a stopover', french: 'une escale' },
        { id: 10, english: 'local gastronomy / regional cuisine', french: 'la gastronomie locale' },
        { id: 11, english: 'off the beaten track / away from tourist crowds', french: 'hors des sentiers battus' },
        { id: 12, english: 'jet lag', french: 'le décalage horaire' },
        { id: 13, english: 'a tour guide / a travel guide (person)', french: 'un guide touristique' },
        { id: 14, english: 'to blend in / to integrate into the local culture', french: 's\'intégrer à la culture locale' },
        { id: 15, english: 'the cost of living', french: 'le coût de la vie' },
        { id: 16, english: 'a cultural exchange', french: 'un échange culturel' },
        { id: 17, english: 'to get lost / to lose one\'s bearings', french: 'se perdre' },
        { id: 18, english: 'open-minded (about other cultures)', french: 'ouvert(e) d\'esprit' },
        { id: 19, english: 'a souvenir / a keepsake', french: 'un souvenir' },
        { id: 20, english: 'a must-see / an essential sight', french: 'un incontournable' },
    ] },
    { level: 'B2', unit: 1, "id":"politics-society","title":"Politique & Société","titleFR":"Politique & Société","description":"Vocabulaire civique et social avancé","descriptionFR":"Vocabulaire civique et social avancé","icon":"🏛️","color":"#475569","wordCount":0, words: [
        { id: 1, english: 'democracy', french: 'la démocratie' },
        { id: 2, english: 'a citizen', french: 'un citoyen / une citoyenne' },
        { id: 3, english: 'citizenship', french: 'la citoyenneté' },
        { id: 4, english: 'the right to vote / suffrage', french: 'le droit de vote' },
        { id: 5, english: 'an election', french: 'une élection' },
        { id: 6, english: 'a ballot / a vote / a poll', french: 'un scrutin' },
        { id: 7, english: 'secularism / the separation of church and state', french: 'la laïcité' },
        { id: 8, english: 'equal opportunity / equality of chances', french: 'l\'égalité des chances' },
        { id: 9, english: 'a demonstration / a protest', french: 'une manifestation' },
        { id: 10, english: 'to demand / to claim (a right)', french: 'revendiquer' },
        { id: 11, english: 'solidarity', french: 'la solidarité' },
        { id: 12, english: 'social exclusion', french: 'l\'exclusion sociale' },
        { id: 13, english: 'the social divide', french: 'la fracture sociale' },
        { id: 14, english: 'volunteering / voluntary work', french: 'le bénévolat' },
        { id: 15, english: 'a non-profit association / a charity', french: 'une association' },
        { id: 16, english: 'lobbying', french: 'le lobbying' },
        { id: 17, english: 'corruption', french: 'la corruption' },
        { id: 18, english: 'transparency / openness', french: 'la transparence' },
        { id: 19, english: 'a debate', french: 'un débat' },
        { id: 20, english: 'a reform', french: 'une réforme' },
    ] },
    { level: 'B2', unit: 1, "id":"business-economy","title":"Affaires & Économie","titleFR":"Affaires & Économie","description":"Le français professionnel et économique","descriptionFR":"Le français professionnel et économique","icon":"📈","color":"#78716C","wordCount":0, words: [
        { id: 1, english: 'a company / business', french: 'une entreprise' },
        { id: 2, english: 'a public limited company (PLC)', french: 'une société anonyme (SA)' },
        { id: 3, english: 'a small and medium-sized enterprise (SME)', french: 'une PME' },
        { id: 4, english: 'turnover / revenue', french: 'le chiffre d\'affaires' },
        { id: 5, english: 'profit', french: 'le bénéfice' },
        { id: 6, english: 'loss', french: 'la perte' },
        { id: 7, english: 'to invest', french: 'investir' },
        { id: 8, english: 'a share (stock)', french: 'une action' },
        { id: 9, english: 'the stock market', french: 'la bourse' },
        { id: 10, english: 'competition (in business)', french: 'la concurrence' },
        { id: 11, english: 'a market', french: 'un marché' },
        { id: 12, english: 'demand', french: 'la demande' },
        { id: 13, english: 'supply / offer', french: 'l\'offre' },
        { id: 14, english: 'a merger', french: 'une fusion' },
        { id: 15, english: 'a takeover / buyout', french: 'un rachat' },
        { id: 16, english: 'globalisation', french: 'la mondialisation' },
        { id: 17, english: 'a subsidiary / branch company', french: 'une filiale' },
        { id: 18, english: 'the balance sheet', french: 'le bilan' },
        { id: 19, english: 'a debt', french: 'une dette' },
        { id: 20, english: 'economic growth', french: 'la croissance économique' },
    ] },
    { level: 'B2', unit: 3, "id":"arts-and-criticism","title":"Arts & Critique littéraire","titleFR":"Arts & Critique littéraire","description":"Vocabulaire pour analyser et critiquer les œuvres d'art","descriptionFR":"Vocabulaire pour analyser et critiquer les œuvres d'art","icon":"📝","color":"#7C3AED","wordCount":0, words: [
        { id: 1,  english: 'a masterpiece',                         french: 'un chef-d\'œuvre' },
        { id: 2,  english: 'direction / staging (of a play)',       french: 'une mise en scène' },
        { id: 3,  english: 'an interpretation / a performance',     french: 'une interprétation' },
        { id: 4,  english: 'a register (literary or stylistic)',    french: 'un registre' },
        { id: 5,  english: 'tone / tonality',                       french: 'la tonalité' },
        { id: 6,  english: 'a narrative',                           french: 'un récit' },
        { id: 7,  english: 'a plot',                                french: 'une intrigue' },
        { id: 8,  english: 'a dénouement / resolution',             french: 'un dénouement' },
        { id: 9,  english: 'a character',                           french: 'un personnage' },
        { id: 10, english: 'a narrator',                            french: 'un narrateur / une narratrice' },
        { id: 11, english: 'a point of view / narrative perspective', french: 'un point de vue' },
        { id: 12, english: 'symbolism',                             french: 'le symbolisme' },
        { id: 13, english: 'an allegory',                           french: 'une allégorie' },
        { id: 14, english: 'irony',                                 french: 'l\'ironie' },
        { id: 15, english: 'satire',                                french: 'la satire' },
        { id: 16, english: 'commitment / political engagement (artistic)', french: 'l\'engagement' },
        { id: 17, english: 'realism (literary movement)',           french: 'le réalisme' },
        { id: 18, english: 'fiction',                               french: 'la fiction' },
        { id: 19, english: 'a genre',                               french: 'un genre' },
        { id: 20, english: 'an adaptation (of a work)',             french: 'une adaptation' },
    ] },
    { level: 'B2', unit: 1, "id":"law-justice","title":"Droit & Justice","titleFR":"Droit & Justice","description":"Systèmes juridiques, tribunaux et vocabulaire judiciaire","descriptionFR":"Systèmes juridiques, tribunaux et vocabulaire judiciaire","icon":"⚖️","color":"#475569","wordCount":0, words: [
        { id: 1,  english: 'a court (of law)',                      french: 'un tribunal' },
        { id: 2,  english: 'a trial',                               french: 'un procès' },
        { id: 3,  english: 'a judgement / ruling',                  french: 'un jugement' },
        { id: 4,  english: 'a verdict',                             french: 'un verdict' },
        { id: 5,  english: 'a sentence / penalty',                  french: 'une peine' },
        { id: 6,  english: 'an acquittal',                          french: 'un acquittement' },
        { id: 7,  english: 'a conviction',                          french: 'une condamnation' },
        { id: 8,  english: 'an appeal (legal)',                     french: 'un appel' },
        { id: 9,  english: 'case law / legal precedent',            french: 'la jurisprudence' },
        { id: 10, english: 'a lawyer / counsel',                    french: 'un(e) avocat(e)' },
        { id: 11, english: 'the plaintiff / complainant',           french: 'le/la plaignant(e)' },
        { id: 12, english: 'the defendant',                         french: 'le/la défendeur(-euse)' },
        { id: 13, english: 'a witness',                             french: 'un(e) témoin' },
        { id: 14, english: 'evidence / proof',                      french: 'une preuve' },
        { id: 15, english: 'presumption of innocence',              french: 'la présomption d\'innocence' },
        { id: 16, english: 'police custody',                        french: 'la garde à vue' },
        { id: 17, english: 'parole / conditional release',          french: 'la liberté conditionnelle' },
        { id: 18, english: 'amnesty',                               french: 'l\'amnistie' },
        { id: 19, english: 'extradition',                           french: 'l\'extradition' },
        { id: 20, english: 'international law',                     french: 'le droit international' },
    ] },
    { level: 'B2', unit: 3, "id":"media-journalism","title":"Médias & Journalisme","titleFR":"Médias & Journalisme","description":"Presse, médias audiovisuels et langage journalistique","descriptionFR":"Presse, médias audiovisuels et langage journalistique","icon":"📰","color":"#0284C7","wordCount":0, words: [
        { id: 1,  english: 'an editorial board / the newsroom',    french: 'la rédaction' },
        { id: 2,  english: 'editorial line / editorial stance',     french: 'la ligne éditoriale' },
        { id: 3,  english: 'a press release',                       french: 'un communiqué de presse' },
        { id: 4,  english: 'a news agency',                         french: 'une agence de presse' },
        { id: 5,  english: 'a freelance journalist',                french: 'un(e) pigiste' },
        { id: 6,  english: 'a scoop / exclusive story',             french: 'un scoop' },
        { id: 7,  english: 'investigative journalism',              french: 'le journalisme d\'investigation' },
        { id: 8,  english: 'a position / a stance (editorial)',     french: 'une prise de position' },
        { id: 9,  english: 'press ethics / media ethics',           french: 'la déontologie' },
        { id: 10, english: 'objectivity',                           french: 'l\'objectivité' },
        { id: 11, english: 'propaganda',                            french: 'la propagande' },
        { id: 12, english: 'disinformation / misinformation',       french: 'la désinformation' },
        { id: 13, english: 'a (journalistic) source',               french: 'une source' },
        { id: 14, english: 'source confidentiality',                french: 'la confidentialité des sources' },
        { id: 15, english: 'freedom of expression',                 french: 'la liberté d\'expression' },
        { id: 16, english: 'media pluralism',                       french: 'le pluralisme' },
        { id: 17, english: 'circulation (of a newspaper)',          french: 'le tirage' },
        { id: 18, english: 'readership',                            french: 'le lectorat' },
        { id: 19, english: 'digital (media)',                       french: 'le numérique' },
        { id: 20, english: 'a podcast',                             french: 'un podcast' },
    ] },
    { level: 'B2', unit: 1, "id":"philosophy-ethics","title":"Philosophie & Éthique","titleFR":"Philosophie & Éthique","description":"Philosophie morale et discours éthique","descriptionFR":"Philosophie morale et discours éthique","icon":"⚗️","color":"#6D28D9","wordCount":0, words: [
        { id: 1,  english: 'morality',                              french: 'la morale' },
        { id: 2,  english: 'ethics',                                french: 'l\'éthique' },
        { id: 3,  english: 'virtue',                                french: 'la vertu' },
        { id: 4,  english: 'freedom / liberty',                     french: 'la liberté' },
        { id: 5,  english: 'determinism',                           french: 'le déterminisme' },
        { id: 6,  english: 'responsibility',                        french: 'la responsabilité' },
        { id: 7,  english: 'consciousness',                         french: 'la conscience' },
        { id: 8,  english: 'identity',                              french: 'l\'identité' },
        { id: 9,  english: 'altruism',                              french: 'l\'altruisme' },
        { id: 10, english: 'utilitarianism',                        french: 'l\'utilitarisme' },
        { id: 11, english: 'relativism',                            french: 'le relativisme' },
        { id: 12, english: 'the absurd (philosophy)',               french: 'l\'absurde' },
        { id: 13, english: 'existentialism',                        french: 'l\'existentialisme' },
        { id: 14, english: 'dialectics',                            french: 'la dialectique' },
        { id: 15, english: 'rhetoric',                              french: 'la rhétorique' },
        { id: 16, english: 'a paradox',                             french: 'un paradoxe' },
        { id: 17, english: 'deontology / duty-based ethics',        french: 'la déontologie' },
        { id: 18, english: 'humanism',                              french: 'l\'humanisme' },
        { id: 19, english: 'nihilism',                              french: 'le nihilisme' },
        { id: 20, english: 'transcendence',                         french: 'la transcendance' },
    ] },
    { level: 'B2', unit: 1, "id":"science-technology","title":"Science & Technologie","titleFR":"Science & Technologie","description":"Concepts scientifiques et technologie moderne","descriptionFR":"Concepts scientifiques et technologie moderne","icon":"🧬","color":"#0891B2","wordCount":0, words: [
        { id: 1,  english: 'artificial intelligence',               french: 'l\'intelligence artificielle' },
        { id: 2,  english: 'an algorithm',                          french: 'un algorithme' },
        { id: 3,  english: 'biotechnology',                         french: 'la biotechnologie' },
        { id: 4,  english: 'nanotechnology',                        french: 'la nanotechnologie' },
        { id: 5,  english: 'nuclear energy',                        french: 'l\'énergie nucléaire' },
        { id: 6,  english: 'space exploration',                     french: 'l\'exploration spatiale' },
        { id: 7,  english: 'genetics',                              french: 'la génétique' },
        { id: 8,  english: 'a clone',                               french: 'un clone' },
        { id: 9,  english: 'a transplant / organ transplantation',  french: 'une transplantation' },
        { id: 10, english: 'robotics',                              french: 'la robotique' },
        { id: 11, english: 'virtual reality',                       french: 'la réalité virtuelle' },
        { id: 12, english: 'big data',                              french: 'le big data' },
        { id: 13, english: 'cybersecurity',                         french: 'la cybersécurité' },
        { id: 14, english: 'a start-up',                            french: 'une start-up' },
        { id: 15, english: 'innovation',                            french: 'l\'innovation' },
        { id: 16, english: 'a patent',                              french: 'un brevet' },
        { id: 17, english: 'fundamental / basic research',          french: 'la recherche fondamentale' },
        { id: 18, english: 'experimentation',                       french: 'l\'expérimentation' },
        { id: 19, english: 'a hypothesis',                          french: 'une hypothèse' },
        { id: 20, english: 'a paradigm',                            french: 'un paradigme' },
    ] },
    { level: 'B2', unit: 3, "id":"urban-society","title":"Société urbaine","titleFR":"Société urbaine","description":"Vie urbaine, structures sociales et enjeux de la ville","descriptionFR":"Vie urbaine, structures sociales et enjeux de la ville","icon":"🌆","color":"#6366F1","wordCount":0, words: [
        { id: 1,  english: 'urbanisation',                          french: 'l\'urbanisation' },
        { id: 2,  english: 'gentrification',                        french: 'la gentrification' },
        { id: 3,  english: 'social diversity / mixed communities',  french: 'la mixité sociale' },
        { id: 4,  english: 'segregation',                           french: 'la ségrégation' },
        { id: 5,  english: 'social cohesion',                       french: 'la cohésion sociale' },
        { id: 6,  english: 'immigration',                           french: 'l\'immigration' },
        { id: 7,  english: 'integration',                           french: 'l\'intégration' },
        { id: 8,  english: 'communitarianism',                      french: 'le communautarisme' },
        { id: 9,  english: 'secularism / laïcité',                  french: 'la laïcité' },
        { id: 10, english: 'discrimination',                        french: 'la discrimination' },
        { id: 11, english: 'equal opportunity',                     french: 'l\'égalité des chances' },
        { id: 12, english: 'social mobility / the social ladder',   french: 'l\'ascenseur social' },
        { id: 13, english: 'precariousness / vulnerability',        french: 'la précarité' },
        { id: 14, english: 'social exclusion',                      french: 'l\'exclusion' },
        { id: 15, english: 'inclusion',                             french: 'l\'inclusion' },
        { id: 16, english: 'the suburbs',                           french: 'la banlieue' },
        { id: 17, english: 'urban regeneration',                    french: 'la réhabilitation urbaine' },
        { id: 18, english: 'a priority neighbourhood (policy zone)', french: 'un quartier prioritaire' },
        { id: 19, english: 'living together / social harmony',      french: 'le vivre-ensemble' },
        { id: 20, english: 'citizenship',                           french: 'la citoyenneté' },
    ] },
];

// Word lists attached to readings that are not standalone vocabulary modules.
export const readingWordsB2: VocabularyData = {
    'b2-article-education': [
        { id: 1, english: 'to pride oneself / to boast', french: 'se targuer' },
        { id: 2, english: 'egalitarian', french: 'égalitaire' },
        { id: 3, english: 'free of charge / free provision', french: 'la gratuité' },
        { id: 4, english: 'by competitive exam', french: 'sur concours' },
        { id: 5, english: 'to aspire to', french: 'aspirer à' },
        { id: 6, english: 'socio-economic background', french: 'l\'origine socio-économique' },
        { id: 7, english: 'academic success', french: 'la réussite scolaire' },
        { id: 8, english: 'well-off / affluent', french: 'aisé' },
        { id: 9, english: 'working-class background', french: 'un milieu ouvrier' },
        { id: 10, english: 'preparatory classes', french: 'les classes préparatoires' },
        { id: 11, english: 'inequalities', french: 'les inégalités' },
        { id: 12, english: 'glaring / blatant', french: 'criant' },
        { id: 13, english: 'social mixing / diversity', french: 'la mixité' },
        { id: 14, english: 'equal opportunity', french: 'l\'égalité des chances' },
        { id: 15, english: 'to determine / to shape', french: 'déterminer' },
    ],
    'b2-debat-ecologie': [
        { id: 1, english: 'electricity', french: 'l\'électricité' },
        { id: 2, english: 'nuclear power', french: 'le nucléaire' },
        { id: 3, english: 'carbon footprint / balance', french: 'le bilan carbone' },
        { id: 4, english: 'low-carbon / decarbonised', french: 'décarboné' },
        { id: 5, english: 'climate emergency', french: 'l\'urgence climatique' },
        { id: 6, english: 'received ideas / common assumptions', french: 'les idées reçues' },
        { id: 7, english: 'radioactive waste', french: 'des déchets radioactifs' },
        { id: 8, english: 'a power plant', french: 'une centrale' },
        { id: 9, english: 'renewable energy', french: 'les énergies renouvelables' },
        { id: 10, english: 'wind power', french: 'l\'éolien' },
        { id: 11, english: 'intermittent', french: 'intermittent' },
        { id: 12, english: 'storage capacity', french: 'la capacité de stockage' },
        { id: 13, english: 'to emit', french: 'émettre' },
        { id: 14, english: 'the real stake / issue', french: 'le vrai enjeu' },
        { id: 15, english: 'a balanced mix', french: 'un mix équilibré' },
    ],
    'b2-chronique-societale': [
        { id: 1, english: 'to grow up', french: 'grandir' },
        { id: 2, english: 'to share', french: 'partager' },
        { id: 3, english: 'the platforms', french: 'les plateformes' },
        { id: 4, english: 'to reconfigure / reshape', french: 'reconfigurer' },
        { id: 5, english: 'a (psychological) cost', french: 'un coût psychologique' },
        { id: 6, english: 'a correlation', french: 'une corrélation' },
        { id: 7, english: 'depressive symptoms', french: 'des symptômes dépressifs' },
        { id: 8, english: 'social comparison', french: 'la comparaison sociale' },
        { id: 9, english: 'idealised bodies', french: 'des corps idéalisés' },
        { id: 10, english: 'to erode / wear away', french: 'éroder' },
        { id: 11, english: 'self-esteem', french: 'l\'estime de soi' },
        { id: 12, english: 'spared', french: 'épargné' },
        { id: 13, english: 'to qualify / to nuance', french: 'nuancer' },
        { id: 14, english: 'caring / kindly (communities)', french: 'bienveillant' },
        { id: 15, english: 'excessive / unregulated use', french: 'un usage excessif' },
    ],
    'b2-nouvelles-francophones': [
        { id: 1, english: 'to recognise', french: 'reconnaître' },
        { id: 2, english: 'the bougainvilleas', french: 'les bougainvilliers' },
        { id: 3, english: 'to invade / overrun', french: 'envahir' },
        { id: 4, english: 'the façade / front', french: 'la façade' },
        { id: 5, english: 'the wrought-iron gate', french: 'la grille en fer forgé' },
        { id: 6, english: 'repainted', french: 'repeinte' },
        { id: 7, english: 'to be surprised / astonished', french: 's\'étonner' },
        { id: 8, english: 'the kapok / silk-cotton tree', french: 'le fromager' },
        { id: 9, english: 'to give shade to', french: 'ombrager' },
        { id: 10, english: 'the courtyard', french: 'la cour' },
        { id: 11, english: 'to grow bent / stooped', french: 'courber' },
        { id: 12, english: 'a stranger / foreigner', french: 'un étranger' },
        { id: 13, english: 'without bitterness', french: 'sans amertume' },
        { id: 14, english: 'to shake (one\'s head)', french: 'secouer' },
        { id: 15, english: 'to come undone / to unravel', french: 'se dénouer' },
    ],
    'b2-lettre-ouverte': [
        { id: 1, english: 'the inhabitants / residents', french: 'les habitants' },
        { id: 2, english: 'to bring to your attention', french: 'porter à votre connaissance' },
        { id: 3, english: 'urban renovation', french: 'la rénovation urbaine' },
        { id: 4, english: 'the necessity / need', french: 'la nécessité' },
        { id: 5, english: 'social cohesion', french: 'la cohésion sociale' },
        { id: 6, english: 'profitability', french: 'la rentabilité' },
        { id: 7, english: 'social housing', french: 'les logements sociaux' },
        { id: 8, english: 'the demolition', french: 'la démolition' },
        { id: 9, english: 'the rehousing', french: 'le relogement' },
        { id: 10, english: 'to expel / to evict', french: 'expulser' },
        { id: 11, english: 'gentrification', french: 'la gentrification' },
        { id: 12, english: 'vulnerable populations', french: 'les populations fragiles' },
        { id: 13, english: 'to request urgently', french: 'demander instamment' },
        { id: 14, english: 'the steering committee', french: 'le comité de pilotage' },
        { id: 15, english: 'citizens\' engagement', french: 'l\'engagement citoyen' },
    ],
    'b2-interview-intellectuel': [
        { id: 1, english: 'to publish', french: 'publier' },
        { id: 2, english: 'an essay (book)', french: 'un essai' },
        { id: 3, english: 'uncertainty', french: 'l\'incertitude' },
        { id: 4, english: 'information overload', french: 'la surinformation' },
        { id: 5, english: 'widespread', french: 'répandu' },
        { id: 6, english: 'a contradiction', french: 'une contradiction' },
        { id: 7, english: 'fruitful / fertile', french: 'fécond' },
        { id: 8, english: 'a civic virtue', french: 'une vertu civique' },
        { id: 9, english: 'sceptical doubt', french: 'le doute sceptique' },
        { id: 10, english: 'a breeding ground (for)', french: 'un terreau' },
        { id: 11, english: 'manipulation', french: 'la manipulation' },
        { id: 12, english: 'critical doubt', french: 'le doute critique' },
        { id: 13, english: 'to argue rigorously', french: 'argumenter rigoureusement' },
        { id: 14, english: 'a fallacy / sophism', french: 'un sophisme' },
        { id: 15, english: 'demagoguery', french: 'la démagogie' },
    ],
    'b2-article-scientifique-vulgarise': [
        { id: 1, english: 'an algorithm', french: 'un algorithme' },
        { id: 2, english: 'to detect', french: 'détecter' },
        { id: 3, english: 'a mammogram', french: 'une mammographie' },
        { id: 4, english: 'accuracy / precision', french: 'la précision' },
        { id: 5, english: 'experienced', french: 'expérimenté' },
        { id: 6, english: 'the foreseeable future', french: 'un avenir prévisible' },
        { id: 7, english: 'more nuanced', french: 'plus nuancé' },
        { id: 8, english: 'pattern recognition', french: 'la reconnaissance de patterns' },
        { id: 9, english: 'to surpass / to outdo', french: 'surpasser' },
        { id: 10, english: 'a human relationship', french: 'une relation humaine' },
        { id: 11, english: 'to contextualise', french: 'contextualiser' },
        { id: 12, english: 'the anxiety', french: 'l\'anxiété' },
        { id: 13, english: 'ethical judgements', french: 'des jugements éthiques' },
        { id: 14, english: 'a collaboration', french: 'une collaboration' },
        { id: 15, english: 'to the detriment of', french: 'au détriment de' },
    ],
    'b2en-digital-education': [
        { id: 1, english: 'to alter', french: 'modifier / transformer' },
        { id: 2, english: 'landscape', french: 'le paysage' },
        { id: 3, english: 'advocates', french: 'les partisans / les défenseurs' },
        { id: 4, english: 'to democratise', french: 'démocratiser' },
        { id: 5, english: 'to undermine', french: 'saper / compromettre' },
        { id: 6, english: 'remote learning', french: 'l\'apprentissage à distance' },
        { id: 7, english: 'inequalities', french: 'les inégalités' },
        { id: 8, english: 'to adapt', french: 's\'adapter' },
        { id: 9, english: 'round-the-clock', french: 'permanent(e) / 24 h sur 24' },
        { id: 10, english: 'facilitator', french: 'le facilitateur / l\'animateur' },
        { id: 11, english: 'mentorship', french: 'le mentorat' },
        { id: 12, english: 'cognitive', french: 'cognitif / cognitive' },
        { id: 13, english: 'sophisticated', french: 'sophistiqué(e) / perfectionné(e)' },
        { id: 14, english: 'serendipitous', french: 'fortuit(e) / heureux(-euse) par hasard' },
        { id: 15, english: 'integration', french: 'l\'intégration' },
    ],
    'b2en-cultural-identity': [
        { id: 1, english: 'globalisation', french: 'la mondialisation' },
        { id: 2, english: 'interconnectedness', french: 'l\'interconnexion' },
        { id: 3, english: 'cultural identity', french: 'l\'identité culturelle' },
        { id: 4, english: 'cosmopolitan', french: 'cosmopolite' },
        { id: 5, english: 'to belong', french: 'appartenir' },
        { id: 6, english: 'to dissolve', french: 'se dissoudre / s\'estomper' },
        { id: 7, english: 'to displace', french: 'supplanter / évincer' },
        { id: 8, english: 'convergence', french: 'la convergence' },
        { id: 9, english: 'endangered', french: 'menacé(e) / en danger' },
        { id: 10, english: 'homogenisation', french: 'l\'homogénéisation' },
        { id: 11, english: 'heritage', french: 'le patrimoine / l\'héritage' },
        { id: 12, english: 'hybridisation', french: 'l\'hybridation' },
        { id: 13, english: 'to marginalise', french: 'marginaliser' },
        { id: 14, english: 'diversity', french: 'la diversité' },
        { id: 15, english: 'fluidity', french: 'la fluidité' },
    ],
    'b2en-ai-everyday': [
        { id: 1, english: 'artificial intelligence', french: 'l\'intelligence artificielle' },
        { id: 2, english: 'virtual assistant', french: 'l\'assistant virtuel' },
        { id: 3, english: 'recommendations', french: 'les recommandations' },
        { id: 4, english: 'to rely on', french: 'compter sur / dépendre de' },
        { id: 5, english: 'to analyse', french: 'analyser' },
        { id: 6, english: 'to detect (diseases)', french: 'détecter' },
        { id: 7, english: 'convenience', french: 'la commodité / la praticité' },
        { id: 8, english: 'unprecedented', french: 'sans précédent' },
        { id: 9, english: 'algorithms', french: 'les algorithmes' },
        { id: 10, english: 'fairness', french: 'l\'équité' },
        { id: 11, english: 'privacy', french: 'la vie privée' },
        { id: 12, english: 'accountability', french: 'la responsabilité' },
        { id: 13, english: 'biases', french: 'les biais' },
        { id: 14, english: 'to automate', french: 'automatiser' },
        { id: 15, english: 'to harness', french: 'exploiter / maîtriser' },
    ],
    'b2en-work-life-balance': [
        { id: 1, english: 'work-life balance', french: 'l\'équilibre vie professionnelle-vie privée' },
        { id: 2, english: 'equilibrium', french: 'l\'équilibre' },
        { id: 3, english: 'to question', french: 'remettre en question' },
        { id: 4, english: 'boundary', french: 'la frontière / la limite' },
        { id: 5, english: 'blurred', french: 'flou(e) / estompé(e)' },
        { id: 6, english: 'expectation', french: 'l\'attente' },
        { id: 7, english: 'to seep into', french: 's\'infiltrer dans / empiéter sur' },
        { id: 8, english: 'integration', french: 'l\'intégration' },
        { id: 9, english: 'harmoniously', french: 'harmonieusement' },
        { id: 10, english: 'priorities', french: 'les priorités' },
        { id: 11, english: 'to invade', french: 'envahir' },
        { id: 12, english: 'burnout', french: 'l\'épuisement professionnel' },
        { id: 13, english: 'the right to disconnect', french: 'le droit à la déconnexion' },
        { id: 14, english: 'productivity', french: 'la productivité' },
        { id: 15, english: 'under strain', french: 'sous tension / mis à mal' },
    ],
    'b2en-misinformation': [
        { id: 1, english: 'misinformation', french: 'la désinformation' },
        { id: 2, english: 'connectivity', french: 'la connectivité' },
        { id: 3, english: 'misleading', french: 'trompeur / trompeuse' },
        { id: 4, english: 'false claim', french: 'une affirmation fausse' },
        { id: 5, english: 'well-meaning', french: 'bien intentionné(e)' },
        { id: 6, english: 'sensational', french: 'sensationnaliste' },
        { id: 7, english: 'to provoke', french: 'provoquer / susciter' },
        { id: 8, english: 'consequences', french: 'les conséquences' },
        { id: 9, english: 'to undermine trust', french: 'saper la confiance' },
        { id: 10, english: 'fact-checking', french: 'la vérification des faits' },
        { id: 11, english: 'censorship', french: 'la censure' },
        { id: 12, english: 'free speech', french: 'la liberté d\'expression' },
        { id: 13, english: 'to think critically', french: 'penser de manière critique' },
        { id: 14, english: 'sceptical', french: 'sceptique' },
        { id: 15, english: 'manipulation', french: 'la manipulation' },
    ],
    'b2en-urban-nature': [
        { id: 1, english: 'opposites', french: 'les opposés / les contraires' },
        { id: 2, english: 'concrete', french: 'le béton' },
        { id: 3, english: 'commerce', french: 'le commerce' },
        { id: 4, english: 'urban planners', french: 'les urbanistes' },
        { id: 5, english: 'to reconcile', french: 'concilier / réconcilier' },
        { id: 6, english: 'green spaces', french: 'les espaces verts' },
        { id: 7, english: 'rainfall', french: 'les précipitations / la pluie' },
        { id: 8, english: 'disused', french: 'désaffecté(e)' },
        { id: 9, english: 'elevated parks', french: 'les parcs surélevés' },
        { id: 10, english: 'vegetation', french: 'la végétation' },
        { id: 11, english: 'dense', french: 'dense' },
        { id: 12, english: 'property prices', french: 'les prix de l\'immobilier' },
        { id: 13, english: 'green gentrification', french: 'la gentrification verte' },
        { id: 14, english: 'climate crisis', french: 'la crise climatique' },
        { id: 15, english: 'necessity', french: 'la nécessité' },
    ],
    'b2en-space-exploration': [
        { id: 1, english: 'space exploration', french: 'l\'exploration spatiale' },
        { id: 2, english: 'domain', french: 'le domaine' },
        { id: 3, english: 'prestige', french: 'le prestige' },
        { id: 4, english: 'entrepreneurs', french: 'les entrepreneurs' },
        { id: 5, english: 'orbit', french: 'l\'orbite' },
        { id: 6, english: 'reusable rockets', french: 'les fusées réutilisables' },
        { id: 7, english: 'launch', french: 'le lancement' },
        { id: 8, english: 'satellite', french: 'le satellite' },
        { id: 9, english: 'space tourism', french: 'le tourisme spatial' },
        { id: 10, english: 'permanent presence', french: 'une présence permanente' },
        { id: 11, english: 'astronauts', french: 'les astronautes' },
        { id: 12, english: 'asteroids', french: 'les astéroïdes' },
        { id: 13, english: 'debris', french: 'les débris' },
        { id: 14, english: 'cosmos', french: 'le cosmos' },
        { id: 15, english: 'spacefaring', french: 'voyageant dans l\'espace' },
    ],
    'b2en-future-of-money': [
        { id: 1, english: 'invention', french: 'l\'invention' },
        { id: 2, english: 'to evolve', french: 'évoluer' },
        { id: 3, english: 'precious metals', french: 'les métaux précieux' },
        { id: 4, english: 'banknotes', french: 'les billets de banque' },
        { id: 5, english: 'to exchange', french: 'échanger' },
        { id: 6, english: 'cash', french: 'l\'argent liquide' },
        { id: 7, english: 'contactless card', french: 'la carte sans contact' },
        { id: 8, english: 'convenience', french: 'la commodité' },
        { id: 9, english: 'cryptocurrencies', french: 'les cryptomonnaies' },
        { id: 10, english: 'unstable', french: 'instable' },
        { id: 11, english: 'cashless society', french: 'la société sans argent liquide' },
        { id: 12, english: 'to exclude', french: 'exclure' },
        { id: 13, english: 'spending habits', french: 'les habitudes de dépense' },
        { id: 14, english: 'financial data', french: 'les données financières' },
        { id: 15, english: 'secure', french: 'sécurisé(e)' },
    ],
    'b2en-overtourism': [
        { id: 1, english: 'budget airlines', french: 'les compagnies à bas coût' },
        { id: 2, english: 'booking', french: 'la réservation' },
        { id: 3, english: 'destinations', french: 'les destinations' },
        { id: 4, english: 'overtourism', french: 'le surtourisme' },
        { id: 5, english: 'crowded', french: 'bondé(e) / surpeuplé(e)' },
        { id: 6, english: 'residents', french: 'les habitants' },
        { id: 7, english: 'holiday rentals', french: 'les locations de vacances' },
        { id: 8, english: 'fragile', french: 'fragile' },
        { id: 9, english: 'monuments', french: 'les monuments' },
        { id: 10, english: 'income', french: 'les revenus' },
        { id: 11, english: 'to outweigh', french: 'l\'emporter sur / dépasser' },
        { id: 12, english: 'tourist taxes', french: 'les taxes touristiques' },
        { id: 13, english: 'to relieve pressure', french: 'soulager la pression' },
        { id: 14, english: 'sustainable', french: 'durable' },
        { id: 15, english: 'responsibly', french: 'de manière responsable' },
    ],
    'b2en-genetic-ethics': [
        { id: 1, english: 'genetics', french: 'la génétique' },
        { id: 2, english: 'to edit (genes)', french: 'modifier / éditer' },
        { id: 3, english: 'genetic code', french: 'le code génétique' },
        { id: 4, english: 'precision', french: 'la précision' },
        { id: 5, english: 'ethical dilemmas', french: 'les dilemmes éthiques' },
        { id: 6, english: 'gene editing', french: 'l\'édition génétique' },
        { id: 7, english: 'inherited diseases', french: 'les maladies héréditaires' },
        { id: 8, english: 'incurable', french: 'incurable' },
        { id: 9, english: 'to draw the line', french: 'fixer la limite' },
        { id: 10, english: 'divide', french: 'le fossé / l\'écart' },
        { id: 11, english: 'unintended consequences', french: 'les conséquences imprévues' },
        { id: 12, english: 'evolution', french: 'l\'évolution' },
        { id: 13, english: 'to reverse', french: 'inverser / annuler' },
        { id: 14, english: 'caution', french: 'la prudence' },
        { id: 15, english: 'wisdom', french: 'la sagesse' },
    ],
};
