import type { HelperVerbFR, VerbEntry, VerbGroup } from '../../../types/verbs';

export const verbGroupA2: VerbGroup = { id: 'a2', title: 'A2 — Everyday French', titleFR: 'A2 — Français du quotidien', description: 'Expand your verb range for real-world situations', descriptionFR: 'Élargissez votre répertoire pour les situations réelles', icon: '📗', color: '#059669' };

export const verbsA2: VerbEntry[] = [
        {
        level: 'A2', unit: 5,
            id: 'voyager', infinitive: 'voyager', translation: 'to travel', type: '-ER', color: '#059669',
            rows: [
            { sujet: 'je' , present: 'voyage' , passeCompose: 'ai voyagé' , imparfait: 'voyageais' , futurSimple: 'voyagerai' , conditionnelPresent: 'voyagerais' , subjonctifPresent: 'voyage' , plusQueParfait: 'avais voyagé' , futurAnterieur: 'aurai voyagé' , conditionnelPasse: 'aurais voyagé' , subjonctifPasse: 'aie voyagé' , passeSimple: 'voyageai' , subjonctifImparfait: 'voyageasse' , subjonctifPlusQueParfait: 'eusse voyagé' , passeAnterieur: 'eus voyagé' },
            { sujet: 'tu' , present: 'voyages' , passeCompose: 'as voyagé' , imparfait: 'voyageais' , futurSimple: 'voyageras' , conditionnelPresent: 'voyagerais' , subjonctifPresent: 'voyages' , plusQueParfait: 'avais voyagé' , futurAnterieur: 'auras voyagé' , conditionnelPasse: 'aurais voyagé' , subjonctifPasse: 'aies voyagé' , passeSimple: 'voyageas' , subjonctifImparfait: 'voyageasses' , subjonctifPlusQueParfait: 'eusses voyagé' , passeAnterieur: 'eus voyagé' },
            { sujet: 'il/elle' , present: 'voyage' , passeCompose: 'a voyagé' , imparfait: 'voyageait' , futurSimple: 'voyagera' , conditionnelPresent: 'voyagerait' , subjonctifPresent: 'voyage' , plusQueParfait: 'avait voyagé' , futurAnterieur: 'aura voyagé' , conditionnelPasse: 'aurait voyagé' , subjonctifPasse: 'ait voyagé' , passeSimple: 'voyagea' , subjonctifImparfait: 'voyageât' , subjonctifPlusQueParfait: 'eût voyagé' , passeAnterieur: 'eut voyagé' },
            { sujet: 'nous' , present: 'voyageons' , passeCompose: 'avons voyagé' , imparfait: 'voyagions' , futurSimple: 'voyagerons' , conditionnelPresent: 'voyagerions' , subjonctifPresent: 'voyagions' , plusQueParfait: 'avions voyagé' , futurAnterieur: 'aurons voyagé' , conditionnelPasse: 'aurions voyagé' , subjonctifPasse: 'ayons voyagé' , passeSimple: 'voyageâmes' , subjonctifImparfait: 'voyageassions' , subjonctifPlusQueParfait: 'eussions voyagé' , passeAnterieur: 'eûmes voyagé' },
            { sujet: 'vous' , present: 'voyagez' , passeCompose: 'avez voyagé' , imparfait: 'voyagiez' , futurSimple: 'voyagerez' , conditionnelPresent: 'voyageriez' , subjonctifPresent: 'voyagiez' , plusQueParfait: 'aviez voyagé' , futurAnterieur: 'aurez voyagé' , conditionnelPasse: 'auriez voyagé' , subjonctifPasse: 'ayez voyagé' , passeSimple: 'voyageâtes' , subjonctifImparfait: 'voyageassiez' , subjonctifPlusQueParfait: 'eussiez voyagé' , passeAnterieur: 'eûtes voyagé' },
            { sujet: 'ils/elles' , present: 'voyagent' , passeCompose: 'ont voyagé' , imparfait: 'voyageaient' , futurSimple: 'voyageront' , conditionnelPresent: 'voyageraient' , subjonctifPresent: 'voyagent' , plusQueParfait: 'avaient voyagé' , futurAnterieur: 'auront voyagé' , conditionnelPasse: 'auraient voyagé' , subjonctifPasse: 'aient voyagé' , passeSimple: 'voyagèrent' , subjonctifImparfait: 'voyageassent' , subjonctifPlusQueParfait: 'eussent voyagé' , passeAnterieur: 'eurent voyagé' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'nager', infinitive: 'nager', translation: 'to swim', type: '-ER', color: '#059669',
            rows: [
            { sujet: 'je' , present: 'nage' , passeCompose: 'ai nagé' , imparfait: 'nageais' , futurSimple: 'nagerai' , conditionnelPresent: 'nagerais' , subjonctifPresent: 'nage' , plusQueParfait: 'avais nagé' , futurAnterieur: 'aurai nagé' , conditionnelPasse: 'aurais nagé' , subjonctifPasse: 'aie nagé' , passeSimple: 'nageai' , subjonctifImparfait: 'nageasse' , subjonctifPlusQueParfait: 'eusse nagé' , passeAnterieur: 'eus nagé' },
            { sujet: 'tu' , present: 'nages' , passeCompose: 'as nagé' , imparfait: 'nageais' , futurSimple: 'nageras' , conditionnelPresent: 'nagerais' , subjonctifPresent: 'nages' , plusQueParfait: 'avais nagé' , futurAnterieur: 'auras nagé' , conditionnelPasse: 'aurais nagé' , subjonctifPasse: 'aies nagé' , passeSimple: 'nageas' , subjonctifImparfait: 'nageasses' , subjonctifPlusQueParfait: 'eusses nagé' , passeAnterieur: 'eus nagé' },
            { sujet: 'il/elle' , present: 'nage' , passeCompose: 'a nagé' , imparfait: 'nageait' , futurSimple: 'nagera' , conditionnelPresent: 'nagerait' , subjonctifPresent: 'nage' , plusQueParfait: 'avait nagé' , futurAnterieur: 'aura nagé' , conditionnelPasse: 'aurait nagé' , subjonctifPasse: 'ait nagé' , passeSimple: 'nagea' , subjonctifImparfait: 'nageât' , subjonctifPlusQueParfait: 'eût nagé' , passeAnterieur: 'eut nagé' },
            { sujet: 'nous' , present: 'nageons' , passeCompose: 'avons nagé' , imparfait: 'nagions' , futurSimple: 'nagerons' , conditionnelPresent: 'nagerions' , subjonctifPresent: 'nagions' , plusQueParfait: 'avions nagé' , futurAnterieur: 'aurons nagé' , conditionnelPasse: 'aurions nagé' , subjonctifPasse: 'ayons nagé' , passeSimple: 'nageâmes' , subjonctifImparfait: 'nageassions' , subjonctifPlusQueParfait: 'eussions nagé' , passeAnterieur: 'eûmes nagé' },
            { sujet: 'vous' , present: 'nagez' , passeCompose: 'avez nagé' , imparfait: 'nagiez' , futurSimple: 'nagerez' , conditionnelPresent: 'nageriez' , subjonctifPresent: 'nagiez' , plusQueParfait: 'aviez nagé' , futurAnterieur: 'aurez nagé' , conditionnelPasse: 'auriez nagé' , subjonctifPasse: 'ayez nagé' , passeSimple: 'nageâtes' , subjonctifImparfait: 'nageassiez' , subjonctifPlusQueParfait: 'eussiez nagé' , passeAnterieur: 'eûtes nagé' },
            { sujet: 'ils/elles' , present: 'nagent' , passeCompose: 'ont nagé' , imparfait: 'nageaient' , futurSimple: 'nageront' , conditionnelPresent: 'nageraient' , subjonctifPresent: 'nagent' , plusQueParfait: 'avaient nagé' , futurAnterieur: 'auront nagé' , conditionnelPasse: 'auraient nagé' , subjonctifPasse: 'aient nagé' , passeSimple: 'nagèrent' , subjonctifImparfait: 'nageassent' , subjonctifPlusQueParfait: 'eussent nagé' , passeAnterieur: 'eurent nagé' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'danser', infinitive: 'danser', translation: 'to dance', type: '-ER', color: '#059669',
            rows: [
            { sujet: 'je' , present: 'danse' , passeCompose: 'ai dansé' , imparfait: 'dansais' , futurSimple: 'danserai' , conditionnelPresent: 'danserais' , subjonctifPresent: 'danse' , plusQueParfait: 'avais dansé' , futurAnterieur: 'aurai dansé' , conditionnelPasse: 'aurais dansé' , subjonctifPasse: 'aie dansé' , passeSimple: 'dansai' , subjonctifImparfait: 'dansasse' , subjonctifPlusQueParfait: 'eusse dansé' , passeAnterieur: 'eus dansé' },
            { sujet: 'tu' , present: 'danses' , passeCompose: 'as dansé' , imparfait: 'dansais' , futurSimple: 'danseras' , conditionnelPresent: 'danserais' , subjonctifPresent: 'danses' , plusQueParfait: 'avais dansé' , futurAnterieur: 'auras dansé' , conditionnelPasse: 'aurais dansé' , subjonctifPasse: 'aies dansé' , passeSimple: 'dansas' , subjonctifImparfait: 'dansasses' , subjonctifPlusQueParfait: 'eusses dansé' , passeAnterieur: 'eus dansé' },
            { sujet: 'il/elle' , present: 'danse' , passeCompose: 'a dansé' , imparfait: 'dansait' , futurSimple: 'dansera' , conditionnelPresent: 'danserait' , subjonctifPresent: 'danse' , plusQueParfait: 'avait dansé' , futurAnterieur: 'aura dansé' , conditionnelPasse: 'aurait dansé' , subjonctifPasse: 'ait dansé' , passeSimple: 'dansa' , subjonctifImparfait: 'dansât' , subjonctifPlusQueParfait: 'eût dansé' , passeAnterieur: 'eut dansé' },
            { sujet: 'nous' , present: 'dansons' , passeCompose: 'avons dansé' , imparfait: 'dansions' , futurSimple: 'danserons' , conditionnelPresent: 'danserions' , subjonctifPresent: 'dansions' , plusQueParfait: 'avions dansé' , futurAnterieur: 'aurons dansé' , conditionnelPasse: 'aurions dansé' , subjonctifPasse: 'ayons dansé' , passeSimple: 'dansâmes' , subjonctifImparfait: 'dansassions' , subjonctifPlusQueParfait: 'eussions dansé' , passeAnterieur: 'eûmes dansé' },
            { sujet: 'vous' , present: 'dansez' , passeCompose: 'avez dansé' , imparfait: 'dansiez' , futurSimple: 'danserez' , conditionnelPresent: 'danseriez' , subjonctifPresent: 'dansiez' , plusQueParfait: 'aviez dansé' , futurAnterieur: 'aurez dansé' , conditionnelPasse: 'auriez dansé' , subjonctifPasse: 'ayez dansé' , passeSimple: 'dansâtes' , subjonctifImparfait: 'dansassiez' , subjonctifPlusQueParfait: 'eussiez dansé' , passeAnterieur: 'eûtes dansé' },
            { sujet: 'ils/elles' , present: 'dansent' , passeCompose: 'ont dansé' , imparfait: 'dansaient' , futurSimple: 'danseront' , conditionnelPresent: 'danseraient' , subjonctifPresent: 'dansent' , plusQueParfait: 'avaient dansé' , futurAnterieur: 'auront dansé' , conditionnelPasse: 'auraient dansé' , subjonctifPasse: 'aient dansé' , passeSimple: 'dansèrent' , subjonctifImparfait: 'dansassent' , subjonctifPlusQueParfait: 'eussent dansé' , passeAnterieur: 'eurent dansé' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'chercher', infinitive: 'chercher', translation: 'to look for / search', type: '-ER', color: '#059669',
            rows: [
            { sujet: 'je' , present: 'cherche' , passeCompose: 'ai cherché' , imparfait: 'cherchais' , futurSimple: 'chercherai' , conditionnelPresent: 'chercherais' , subjonctifPresent: 'cherche' , plusQueParfait: 'avais cherché' , futurAnterieur: 'aurai cherché' , conditionnelPasse: 'aurais cherché' , subjonctifPasse: 'aie cherché' , passeSimple: 'cherchai' , subjonctifImparfait: 'cherchasse' , subjonctifPlusQueParfait: 'eusse cherché' , passeAnterieur: 'eus cherché' },
            { sujet: 'tu' , present: 'cherches' , passeCompose: 'as cherché' , imparfait: 'cherchais' , futurSimple: 'chercheras' , conditionnelPresent: 'chercherais' , subjonctifPresent: 'cherches' , plusQueParfait: 'avais cherché' , futurAnterieur: 'auras cherché' , conditionnelPasse: 'aurais cherché' , subjonctifPasse: 'aies cherché' , passeSimple: 'cherchas' , subjonctifImparfait: 'cherchasses' , subjonctifPlusQueParfait: 'eusses cherché' , passeAnterieur: 'eus cherché' },
            { sujet: 'il/elle' , present: 'cherche' , passeCompose: 'a cherché' , imparfait: 'cherchait' , futurSimple: 'cherchera' , conditionnelPresent: 'chercherait' , subjonctifPresent: 'cherche' , plusQueParfait: 'avait cherché' , futurAnterieur: 'aura cherché' , conditionnelPasse: 'aurait cherché' , subjonctifPasse: 'ait cherché' , passeSimple: 'chercha' , subjonctifImparfait: 'cherchât' , subjonctifPlusQueParfait: 'eût cherché' , passeAnterieur: 'eut cherché' },
            { sujet: 'nous' , present: 'cherchons' , passeCompose: 'avons cherché' , imparfait: 'cherchions' , futurSimple: 'chercherons' , conditionnelPresent: 'chercherions' , subjonctifPresent: 'cherchions' , plusQueParfait: 'avions cherché' , futurAnterieur: 'aurons cherché' , conditionnelPasse: 'aurions cherché' , subjonctifPasse: 'ayons cherché' , passeSimple: 'cherchâmes' , subjonctifImparfait: 'cherchassions' , subjonctifPlusQueParfait: 'eussions cherché' , passeAnterieur: 'eûmes cherché' },
            { sujet: 'vous' , present: 'cherchez' , passeCompose: 'avez cherché' , imparfait: 'cherchiez' , futurSimple: 'chercherez' , conditionnelPresent: 'chercheriez' , subjonctifPresent: 'cherchiez' , plusQueParfait: 'aviez cherché' , futurAnterieur: 'aurez cherché' , conditionnelPasse: 'auriez cherché' , subjonctifPasse: 'ayez cherché' , passeSimple: 'cherchâtes' , subjonctifImparfait: 'cherchassiez' , subjonctifPlusQueParfait: 'eussiez cherché' , passeAnterieur: 'eûtes cherché' },
            { sujet: 'ils/elles' , present: 'cherchent' , passeCompose: 'ont cherché' , imparfait: 'cherchaient' , futurSimple: 'chercheront' , conditionnelPresent: 'chercheraient' , subjonctifPresent: 'cherchent' , plusQueParfait: 'avaient cherché' , futurAnterieur: 'auront cherché' , conditionnelPasse: 'auraient cherché' , subjonctifPasse: 'aient cherché' , passeSimple: 'cherchèrent' , subjonctifImparfait: 'cherchassent' , subjonctifPlusQueParfait: 'eussent cherché' , passeAnterieur: 'eurent cherché' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'tomber', infinitive: 'tomber', translation: 'to fall', type: '-ER', color: '#059669',
            rows: [
            { sujet: 'je' , present: 'tombe' , passeCompose: 'suis tombé(e)' , imparfait: 'tombais' , futurSimple: 'tomberai' , conditionnelPresent: 'tomberais' , subjonctifPresent: 'tombe' , plusQueParfait: 'étais tombé(e)' , futurAnterieur: 'serai tombé(e)' , conditionnelPasse: 'serais tombé(e)' , subjonctifPasse: 'sois tombé(e)' , passeSimple: 'tombai' , subjonctifImparfait: 'tombasse' , subjonctifPlusQueParfait: 'fusse tombé(e)' , passeAnterieur: 'fus tombé(e)' },
            { sujet: 'tu' , present: 'tombes' , passeCompose: 'es tombé(e)' , imparfait: 'tombais' , futurSimple: 'tomberas' , conditionnelPresent: 'tomberais' , subjonctifPresent: 'tombes' , plusQueParfait: 'étais tombé(e)' , futurAnterieur: 'seras tombé(e)' , conditionnelPasse: 'serais tombé(e)' , subjonctifPasse: 'sois tombé(e)' , passeSimple: 'tombas' , subjonctifImparfait: 'tombasses' , subjonctifPlusQueParfait: 'fusses tombé(e)' , passeAnterieur: 'fus tombé(e)' },
            { sujet: 'il/elle' , present: 'tombe' , passeCompose: 'est tombé(e)' , imparfait: 'tombait' , futurSimple: 'tombera' , conditionnelPresent: 'tomberait' , subjonctifPresent: 'tombe' , plusQueParfait: 'était tombé(e)' , futurAnterieur: 'sera tombé(e)' , conditionnelPasse: 'serait tombé(e)' , subjonctifPasse: 'soit tombé(e)' , passeSimple: 'tomba' , subjonctifImparfait: 'tombât' , subjonctifPlusQueParfait: 'fût tombé(e)' , passeAnterieur: 'fut tombé(e)' },
            { sujet: 'nous' , present: 'tombons' , passeCompose: 'sommes tombé(e)' , imparfait: 'tombions' , futurSimple: 'tomberons' , conditionnelPresent: 'tomberions' , subjonctifPresent: 'tombions' , plusQueParfait: 'étions tombé(e)' , futurAnterieur: 'serons tombé(e)' , conditionnelPasse: 'serions tombé(e)' , subjonctifPasse: 'soyons tombé(e)' , passeSimple: 'tombâmes' , subjonctifImparfait: 'tombassions' , subjonctifPlusQueParfait: 'fussions tombé(e)' , passeAnterieur: 'fûmes tombé(e)' },
            { sujet: 'vous' , present: 'tombez' , passeCompose: 'êtes tombé(e)' , imparfait: 'tombiez' , futurSimple: 'tomberez' , conditionnelPresent: 'tomberiez' , subjonctifPresent: 'tombiez' , plusQueParfait: 'étiez tombé(e)' , futurAnterieur: 'serez tombé(e)' , conditionnelPasse: 'seriez tombé(e)' , subjonctifPasse: 'soyez tombé(e)' , passeSimple: 'tombâtes' , subjonctifImparfait: 'tombassiez' , subjonctifPlusQueParfait: 'fussiez tombé(e)' , passeAnterieur: 'fûtes tombé(e)' },
            { sujet: 'ils/elles' , present: 'tombent' , passeCompose: 'sont tombé(e)' , imparfait: 'tombaient' , futurSimple: 'tomberont' , conditionnelPresent: 'tomberaient' , subjonctifPresent: 'tombent' , plusQueParfait: 'étaient tombé(e)' , futurAnterieur: 'seront tombé(e)' , conditionnelPasse: 'seraient tombé(e)' , subjonctifPasse: 'soient tombé(e)' , passeSimple: 'tombèrent' , subjonctifImparfait: 'tombassent' , subjonctifPlusQueParfait: 'fussent tombé(e)' , passeAnterieur: 'furent tombé(e)' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'choisir', infinitive: 'choisir', translation: 'to choose', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'choisis' , passeCompose: 'ai choisi' , imparfait: 'choisissais' , futurSimple: 'choisirai' , conditionnelPresent: 'choisirais' , subjonctifPresent: 'choisisse' , plusQueParfait: 'avais choisi' , futurAnterieur: 'aurai choisi' , conditionnelPasse: 'aurais choisi' , subjonctifPasse: 'aie choisi' , passeSimple: 'choisis' , subjonctifImparfait: 'choisisse' , subjonctifPlusQueParfait: 'eusse choisi' , passeAnterieur: 'eus choisi' },
            { sujet: 'tu' , present: 'choisis' , passeCompose: 'as choisi' , imparfait: 'choisissais' , futurSimple: 'choisiras' , conditionnelPresent: 'choisirais' , subjonctifPresent: 'choisisses' , plusQueParfait: 'avais choisi' , futurAnterieur: 'auras choisi' , conditionnelPasse: 'aurais choisi' , subjonctifPasse: 'aies choisi' , passeSimple: 'choisis' , subjonctifImparfait: 'choisisses' , subjonctifPlusQueParfait: 'eusses choisi' , passeAnterieur: 'eus choisi' },
            { sujet: 'il/elle' , present: 'choisit' , passeCompose: 'a choisi' , imparfait: 'choisissait' , futurSimple: 'choisira' , conditionnelPresent: 'choisirait' , subjonctifPresent: 'choisisse' , plusQueParfait: 'avait choisi' , futurAnterieur: 'aura choisi' , conditionnelPasse: 'aurait choisi' , subjonctifPasse: 'ait choisi' , passeSimple: 'choisit' , subjonctifImparfait: 'choisît' , subjonctifPlusQueParfait: 'eût choisi' , passeAnterieur: 'eut choisi' },
            { sujet: 'nous' , present: 'choisissons' , passeCompose: 'avons choisi' , imparfait: 'choisissions' , futurSimple: 'choisirons' , conditionnelPresent: 'choisirions' , subjonctifPresent: 'choisissions' , plusQueParfait: 'avions choisi' , futurAnterieur: 'aurons choisi' , conditionnelPasse: 'aurions choisi' , subjonctifPasse: 'ayons choisi' , passeSimple: 'choisîmes' , subjonctifImparfait: 'choisissions' , subjonctifPlusQueParfait: 'eussions choisi' , passeAnterieur: 'eûmes choisi' },
            { sujet: 'vous' , present: 'choisissez' , passeCompose: 'avez choisi' , imparfait: 'choisissiez' , futurSimple: 'choisirez' , conditionnelPresent: 'choisiriez' , subjonctifPresent: 'choisissiez' , plusQueParfait: 'aviez choisi' , futurAnterieur: 'aurez choisi' , conditionnelPasse: 'auriez choisi' , subjonctifPasse: 'ayez choisi' , passeSimple: 'choisîtes' , subjonctifImparfait: 'choisissiez' , subjonctifPlusQueParfait: 'eussiez choisi' , passeAnterieur: 'eûtes choisi' },
            { sujet: 'ils/elles' , present: 'choisissent' , passeCompose: 'ont choisi' , imparfait: 'choisissaient' , futurSimple: 'choisiront' , conditionnelPresent: 'choisiraient' , subjonctifPresent: 'choisissent' , plusQueParfait: 'avaient choisi' , futurAnterieur: 'auront choisi' , conditionnelPasse: 'auraient choisi' , subjonctifPasse: 'aient choisi' , passeSimple: 'choisirent' , subjonctifImparfait: 'choisissent' , subjonctifPlusQueParfait: 'eussent choisi' , passeAnterieur: 'eurent choisi' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'grandir', infinitive: 'grandir', translation: 'to grow', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'grandis' , passeCompose: 'ai grandi' , imparfait: 'grandissais' , futurSimple: 'grandirai' , conditionnelPresent: 'grandirais' , subjonctifPresent: 'grandisse' , plusQueParfait: 'avais grandi' , futurAnterieur: 'aurai grandi' , conditionnelPasse: 'aurais grandi' , subjonctifPasse: 'aie grandi' , passeSimple: 'grandis' , subjonctifImparfait: 'grandisse' , subjonctifPlusQueParfait: 'eusse grandi' , passeAnterieur: 'eus grandi' },
            { sujet: 'tu' , present: 'grandis' , passeCompose: 'as grandi' , imparfait: 'grandissais' , futurSimple: 'grandiras' , conditionnelPresent: 'grandirais' , subjonctifPresent: 'grandisses' , plusQueParfait: 'avais grandi' , futurAnterieur: 'auras grandi' , conditionnelPasse: 'aurais grandi' , subjonctifPasse: 'aies grandi' , passeSimple: 'grandis' , subjonctifImparfait: 'grandisses' , subjonctifPlusQueParfait: 'eusses grandi' , passeAnterieur: 'eus grandi' },
            { sujet: 'il/elle' , present: 'grandit' , passeCompose: 'a grandi' , imparfait: 'grandissait' , futurSimple: 'grandira' , conditionnelPresent: 'grandirait' , subjonctifPresent: 'grandisse' , plusQueParfait: 'avait grandi' , futurAnterieur: 'aura grandi' , conditionnelPasse: 'aurait grandi' , subjonctifPasse: 'ait grandi' , passeSimple: 'grandit' , subjonctifImparfait: 'grandît' , subjonctifPlusQueParfait: 'eût grandi' , passeAnterieur: 'eut grandi' },
            { sujet: 'nous' , present: 'grandissons' , passeCompose: 'avons grandi' , imparfait: 'grandissions' , futurSimple: 'grandirons' , conditionnelPresent: 'grandirions' , subjonctifPresent: 'grandissions' , plusQueParfait: 'avions grandi' , futurAnterieur: 'aurons grandi' , conditionnelPasse: 'aurions grandi' , subjonctifPasse: 'ayons grandi' , passeSimple: 'grandîmes' , subjonctifImparfait: 'grandissions' , subjonctifPlusQueParfait: 'eussions grandi' , passeAnterieur: 'eûmes grandi' },
            { sujet: 'vous' , present: 'grandissez' , passeCompose: 'avez grandi' , imparfait: 'grandissiez' , futurSimple: 'grandirez' , conditionnelPresent: 'grandiriez' , subjonctifPresent: 'grandissiez' , plusQueParfait: 'aviez grandi' , futurAnterieur: 'aurez grandi' , conditionnelPasse: 'auriez grandi' , subjonctifPasse: 'ayez grandi' , passeSimple: 'grandîtes' , subjonctifImparfait: 'grandissiez' , subjonctifPlusQueParfait: 'eussiez grandi' , passeAnterieur: 'eûtes grandi' },
            { sujet: 'ils/elles' , present: 'grandissent' , passeCompose: 'ont grandi' , imparfait: 'grandissaient' , futurSimple: 'grandiront' , conditionnelPresent: 'grandiraient' , subjonctifPresent: 'grandissent' , plusQueParfait: 'avaient grandi' , futurAnterieur: 'auront grandi' , conditionnelPasse: 'auraient grandi' , subjonctifPasse: 'aient grandi' , passeSimple: 'grandirent' , subjonctifImparfait: 'grandissent' , subjonctifPlusQueParfait: 'eussent grandi' , passeAnterieur: 'eurent grandi' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'reussir', infinitive: 'réussir', translation: 'to succeed', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'réussis' , passeCompose: 'ai réussi' , imparfait: 'réussissais' , futurSimple: 'réussirai' , conditionnelPresent: 'réussirais' , subjonctifPresent: 'réussisse' , plusQueParfait: 'avais réussi' , futurAnterieur: 'aurai réussi' , conditionnelPasse: 'aurais réussi' , subjonctifPasse: 'aie réussi' , passeSimple: 'réussis' , subjonctifImparfait: 'réussisse' , subjonctifPlusQueParfait: 'eusse réussi' , passeAnterieur: 'eus réussi' },
            { sujet: 'tu' , present: 'réussis' , passeCompose: 'as réussi' , imparfait: 'réussissais' , futurSimple: 'réussiras' , conditionnelPresent: 'réussirais' , subjonctifPresent: 'réussisses' , plusQueParfait: 'avais réussi' , futurAnterieur: 'auras réussi' , conditionnelPasse: 'aurais réussi' , subjonctifPasse: 'aies réussi' , passeSimple: 'réussis' , subjonctifImparfait: 'réussisses' , subjonctifPlusQueParfait: 'eusses réussi' , passeAnterieur: 'eus réussi' },
            { sujet: 'il/elle' , present: 'réussit' , passeCompose: 'a réussi' , imparfait: 'réussissait' , futurSimple: 'réussira' , conditionnelPresent: 'réussirait' , subjonctifPresent: 'réussisse' , plusQueParfait: 'avait réussi' , futurAnterieur: 'aura réussi' , conditionnelPasse: 'aurait réussi' , subjonctifPasse: 'ait réussi' , passeSimple: 'réussit' , subjonctifImparfait: 'réussît' , subjonctifPlusQueParfait: 'eût réussi' , passeAnterieur: 'eut réussi' },
            { sujet: 'nous' , present: 'réussissons' , passeCompose: 'avons réussi' , imparfait: 'réussissions' , futurSimple: 'réussirons' , conditionnelPresent: 'réussirions' , subjonctifPresent: 'réussissions' , plusQueParfait: 'avions réussi' , futurAnterieur: 'aurons réussi' , conditionnelPasse: 'aurions réussi' , subjonctifPasse: 'ayons réussi' , passeSimple: 'réussîmes' , subjonctifImparfait: 'réussissions' , subjonctifPlusQueParfait: 'eussions réussi' , passeAnterieur: 'eûmes réussi' },
            { sujet: 'vous' , present: 'réussissez' , passeCompose: 'avez réussi' , imparfait: 'réussissiez' , futurSimple: 'réussirez' , conditionnelPresent: 'réussiriez' , subjonctifPresent: 'réussissiez' , plusQueParfait: 'aviez réussi' , futurAnterieur: 'aurez réussi' , conditionnelPasse: 'auriez réussi' , subjonctifPasse: 'ayez réussi' , passeSimple: 'réussîtes' , subjonctifImparfait: 'réussissiez' , subjonctifPlusQueParfait: 'eussiez réussi' , passeAnterieur: 'eûtes réussi' },
            { sujet: 'ils/elles' , present: 'réussissent' , passeCompose: 'ont réussi' , imparfait: 'réussissaient' , futurSimple: 'réussiront' , conditionnelPresent: 'réussiraient' , subjonctifPresent: 'réussissent' , plusQueParfait: 'avaient réussi' , futurAnterieur: 'auront réussi' , conditionnelPasse: 'auraient réussi' , subjonctifPasse: 'aient réussi' , passeSimple: 'réussirent' , subjonctifImparfait: 'réussissent' , subjonctifPlusQueParfait: 'eussent réussi' , passeAnterieur: 'eurent réussi' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'attendre', infinitive: 'attendre', translation: 'to wait', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'attends' , passeCompose: 'ai attendu' , imparfait: 'attendais' , futurSimple: 'attendrai' , conditionnelPresent: 'attendrais' , subjonctifPresent: 'attende' , plusQueParfait: 'avais attendu' , futurAnterieur: 'aurai attendu' , conditionnelPasse: 'aurais attendu' , subjonctifPasse: 'aie attendu' , passeSimple: 'attendis' , subjonctifImparfait: 'attendisse' , subjonctifPlusQueParfait: 'eusse attendu' , passeAnterieur: 'eus attendu' },
            { sujet: 'tu' , present: 'attends' , passeCompose: 'as attendu' , imparfait: 'attendais' , futurSimple: 'attendras' , conditionnelPresent: 'attendrais' , subjonctifPresent: 'attendes' , plusQueParfait: 'avais attendu' , futurAnterieur: 'auras attendu' , conditionnelPasse: 'aurais attendu' , subjonctifPasse: 'aies attendu' , passeSimple: 'attendis' , subjonctifImparfait: 'attendisses' , subjonctifPlusQueParfait: 'eusses attendu' , passeAnterieur: 'eus attendu' },
            { sujet: 'il/elle' , present: 'attend' , passeCompose: 'a attendu' , imparfait: 'attendait' , futurSimple: 'attendra' , conditionnelPresent: 'attendrait' , subjonctifPresent: 'attende' , plusQueParfait: 'avait attendu' , futurAnterieur: 'aura attendu' , conditionnelPasse: 'aurait attendu' , subjonctifPasse: 'ait attendu' , passeSimple: 'attendit' , subjonctifImparfait: 'attendît' , subjonctifPlusQueParfait: 'eût attendu' , passeAnterieur: 'eut attendu' },
            { sujet: 'nous' , present: 'attendons' , passeCompose: 'avons attendu' , imparfait: 'attendions' , futurSimple: 'attendrons' , conditionnelPresent: 'attendrions' , subjonctifPresent: 'attendions' , plusQueParfait: 'avions attendu' , futurAnterieur: 'aurons attendu' , conditionnelPasse: 'aurions attendu' , subjonctifPasse: 'ayons attendu' , passeSimple: 'attendîmes' , subjonctifImparfait: 'attendissions' , subjonctifPlusQueParfait: 'eussions attendu' , passeAnterieur: 'eûmes attendu' },
            { sujet: 'vous' , present: 'attendez' , passeCompose: 'avez attendu' , imparfait: 'attendiez' , futurSimple: 'attendrez' , conditionnelPresent: 'attendriez' , subjonctifPresent: 'attendiez' , plusQueParfait: 'aviez attendu' , futurAnterieur: 'aurez attendu' , conditionnelPasse: 'auriez attendu' , subjonctifPasse: 'ayez attendu' , passeSimple: 'attendîtes' , subjonctifImparfait: 'attendissiez' , subjonctifPlusQueParfait: 'eussiez attendu' , passeAnterieur: 'eûtes attendu' },
            { sujet: 'ils/elles' , present: 'attendent' , passeCompose: 'ont attendu' , imparfait: 'attendaient' , futurSimple: 'attendront' , conditionnelPresent: 'attendraient' , subjonctifPresent: 'attendent' , plusQueParfait: 'avaient attendu' , futurAnterieur: 'auront attendu' , conditionnelPasse: 'auraient attendu' , subjonctifPasse: 'aient attendu' , passeSimple: 'attendirent' , subjonctifImparfait: 'attendissent' , subjonctifPlusQueParfait: 'eussent attendu' , passeAnterieur: 'eurent attendu' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'repondre', infinitive: 'répondre', translation: 'to answer', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'réponds' , passeCompose: 'ai répondu' , imparfait: 'répondais' , futurSimple: 'répondrai' , conditionnelPresent: 'répondrais' , subjonctifPresent: 'réponde' , plusQueParfait: 'avais répondu' , futurAnterieur: 'aurai répondu' , conditionnelPasse: 'aurais répondu' , subjonctifPasse: 'aie répondu' , passeSimple: 'répondis' , subjonctifImparfait: 'répondisse' , subjonctifPlusQueParfait: 'eusse répondu' , passeAnterieur: 'eus répondu' },
            { sujet: 'tu' , present: 'réponds' , passeCompose: 'as répondu' , imparfait: 'répondais' , futurSimple: 'répondras' , conditionnelPresent: 'répondrais' , subjonctifPresent: 'répondes' , plusQueParfait: 'avais répondu' , futurAnterieur: 'auras répondu' , conditionnelPasse: 'aurais répondu' , subjonctifPasse: 'aies répondu' , passeSimple: 'répondis' , subjonctifImparfait: 'répondisses' , subjonctifPlusQueParfait: 'eusses répondu' , passeAnterieur: 'eus répondu' },
            { sujet: 'il/elle' , present: 'répond' , passeCompose: 'a répondu' , imparfait: 'répondait' , futurSimple: 'répondra' , conditionnelPresent: 'répondrait' , subjonctifPresent: 'réponde' , plusQueParfait: 'avait répondu' , futurAnterieur: 'aura répondu' , conditionnelPasse: 'aurait répondu' , subjonctifPasse: 'ait répondu' , passeSimple: 'répondit' , subjonctifImparfait: 'répondît' , subjonctifPlusQueParfait: 'eût répondu' , passeAnterieur: 'eut répondu' },
            { sujet: 'nous' , present: 'répondons' , passeCompose: 'avons répondu' , imparfait: 'répondions' , futurSimple: 'répondrons' , conditionnelPresent: 'répondrions' , subjonctifPresent: 'répondions' , plusQueParfait: 'avions répondu' , futurAnterieur: 'aurons répondu' , conditionnelPasse: 'aurions répondu' , subjonctifPasse: 'ayons répondu' , passeSimple: 'répondîmes' , subjonctifImparfait: 'répondissions' , subjonctifPlusQueParfait: 'eussions répondu' , passeAnterieur: 'eûmes répondu' },
            { sujet: 'vous' , present: 'répondez' , passeCompose: 'avez répondu' , imparfait: 'répondiez' , futurSimple: 'répondrez' , conditionnelPresent: 'répondriez' , subjonctifPresent: 'répondiez' , plusQueParfait: 'aviez répondu' , futurAnterieur: 'aurez répondu' , conditionnelPasse: 'auriez répondu' , subjonctifPasse: 'ayez répondu' , passeSimple: 'répondîtes' , subjonctifImparfait: 'répondissiez' , subjonctifPlusQueParfait: 'eussiez répondu' , passeAnterieur: 'eûtes répondu' },
            { sujet: 'ils/elles' , present: 'répondent' , passeCompose: 'ont répondu' , imparfait: 'répondaient' , futurSimple: 'répondront' , conditionnelPresent: 'répondraient' , subjonctifPresent: 'répondent' , plusQueParfait: 'avaient répondu' , futurAnterieur: 'auront répondu' , conditionnelPasse: 'auraient répondu' , subjonctifPasse: 'aient répondu' , passeSimple: 'répondirent' , subjonctifImparfait: 'répondissent' , subjonctifPlusQueParfait: 'eussent répondu' , passeAnterieur: 'eurent répondu' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'entendre', infinitive: 'entendre', translation: 'to hear', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'entends' , passeCompose: 'ai entendu' , imparfait: 'entendais' , futurSimple: 'entendrai' , conditionnelPresent: 'entendrais' , subjonctifPresent: 'entende' , plusQueParfait: 'avais entendu' , futurAnterieur: 'aurai entendu' , conditionnelPasse: 'aurais entendu' , subjonctifPasse: 'aie entendu' , passeSimple: 'entendis' , subjonctifImparfait: 'entendisse' , subjonctifPlusQueParfait: 'eusse entendu' , passeAnterieur: 'eus entendu' },
            { sujet: 'tu' , present: 'entends' , passeCompose: 'as entendu' , imparfait: 'entendais' , futurSimple: 'entendras' , conditionnelPresent: 'entendrais' , subjonctifPresent: 'entendes' , plusQueParfait: 'avais entendu' , futurAnterieur: 'auras entendu' , conditionnelPasse: 'aurais entendu' , subjonctifPasse: 'aies entendu' , passeSimple: 'entendis' , subjonctifImparfait: 'entendisses' , subjonctifPlusQueParfait: 'eusses entendu' , passeAnterieur: 'eus entendu' },
            { sujet: 'il/elle' , present: 'entend' , passeCompose: 'a entendu' , imparfait: 'entendait' , futurSimple: 'entendra' , conditionnelPresent: 'entendrait' , subjonctifPresent: 'entende' , plusQueParfait: 'avait entendu' , futurAnterieur: 'aura entendu' , conditionnelPasse: 'aurait entendu' , subjonctifPasse: 'ait entendu' , passeSimple: 'entendit' , subjonctifImparfait: 'entendît' , subjonctifPlusQueParfait: 'eût entendu' , passeAnterieur: 'eut entendu' },
            { sujet: 'nous' , present: 'entendons' , passeCompose: 'avons entendu' , imparfait: 'entendions' , futurSimple: 'entendrons' , conditionnelPresent: 'entendrions' , subjonctifPresent: 'entendions' , plusQueParfait: 'avions entendu' , futurAnterieur: 'aurons entendu' , conditionnelPasse: 'aurions entendu' , subjonctifPasse: 'ayons entendu' , passeSimple: 'entendîmes' , subjonctifImparfait: 'entendissions' , subjonctifPlusQueParfait: 'eussions entendu' , passeAnterieur: 'eûmes entendu' },
            { sujet: 'vous' , present: 'entendez' , passeCompose: 'avez entendu' , imparfait: 'entendiez' , futurSimple: 'entendrez' , conditionnelPresent: 'entendriez' , subjonctifPresent: 'entendiez' , plusQueParfait: 'aviez entendu' , futurAnterieur: 'aurez entendu' , conditionnelPasse: 'auriez entendu' , subjonctifPasse: 'ayez entendu' , passeSimple: 'entendîtes' , subjonctifImparfait: 'entendissiez' , subjonctifPlusQueParfait: 'eussiez entendu' , passeAnterieur: 'eûtes entendu' },
            { sujet: 'ils/elles' , present: 'entendent' , passeCompose: 'ont entendu' , imparfait: 'entendaient' , futurSimple: 'entendront' , conditionnelPresent: 'entendraient' , subjonctifPresent: 'entendent' , plusQueParfait: 'avaient entendu' , futurAnterieur: 'auront entendu' , conditionnelPasse: 'auraient entendu' , subjonctifPasse: 'aient entendu' , passeSimple: 'entendirent' , subjonctifImparfait: 'entendissent' , subjonctifPlusQueParfait: 'eussent entendu' , passeAnterieur: 'eurent entendu' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'partir', infinitive: 'partir', translation: 'to leave', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'pars' , passeCompose: 'suis parti(e)' , imparfait: 'partais' , futurSimple: 'partirai' , conditionnelPresent: 'partirais' , subjonctifPresent: 'parte' , plusQueParfait: 'étais parti(e)' , futurAnterieur: 'serai parti(e)' , conditionnelPasse: 'serais parti(e)' , subjonctifPasse: 'sois parti(e)' , passeSimple: 'partis' , subjonctifImparfait: 'partisse' , subjonctifPlusQueParfait: 'fusse parti(e)' , passeAnterieur: 'fus parti(e)' },
            { sujet: 'tu' , present: 'pars' , passeCompose: 'es parti(e)' , imparfait: 'partais' , futurSimple: 'partiras' , conditionnelPresent: 'partirais' , subjonctifPresent: 'partes' , plusQueParfait: 'étais parti(e)' , futurAnterieur: 'seras parti(e)' , conditionnelPasse: 'serais parti(e)' , subjonctifPasse: 'sois parti(e)' , passeSimple: 'partis' , subjonctifImparfait: 'partisses' , subjonctifPlusQueParfait: 'fusses parti(e)' , passeAnterieur: 'fus parti(e)' },
            { sujet: 'il/elle' , present: 'part' , passeCompose: 'est parti(e)' , imparfait: 'partait' , futurSimple: 'partira' , conditionnelPresent: 'partirait' , subjonctifPresent: 'parte' , plusQueParfait: 'était parti(e)' , futurAnterieur: 'sera parti(e)' , conditionnelPasse: 'serait parti(e)' , subjonctifPasse: 'soit parti(e)' , passeSimple: 'partit' , subjonctifImparfait: 'partît' , subjonctifPlusQueParfait: 'fût parti(e)' , passeAnterieur: 'fut parti(e)' },
            { sujet: 'nous' , present: 'partons' , passeCompose: 'sommes parti(e)' , imparfait: 'partions' , futurSimple: 'partirons' , conditionnelPresent: 'partirions' , subjonctifPresent: 'partions' , plusQueParfait: 'étions parti(e)' , futurAnterieur: 'serons parti(e)' , conditionnelPasse: 'serions parti(e)' , subjonctifPasse: 'soyons parti(e)' , passeSimple: 'partîmes' , subjonctifImparfait: 'partissions' , subjonctifPlusQueParfait: 'fussions parti(e)' , passeAnterieur: 'fûmes parti(e)' },
            { sujet: 'vous' , present: 'partez' , passeCompose: 'êtes parti(e)' , imparfait: 'partiez' , futurSimple: 'partirez' , conditionnelPresent: 'partiriez' , subjonctifPresent: 'partiez' , plusQueParfait: 'étiez parti(e)' , futurAnterieur: 'serez parti(e)' , conditionnelPasse: 'seriez parti(e)' , subjonctifPasse: 'soyez parti(e)' , passeSimple: 'partîtes' , subjonctifImparfait: 'partissiez' , subjonctifPlusQueParfait: 'fussiez parti(e)' , passeAnterieur: 'fûtes parti(e)' },
            { sujet: 'ils/elles' , present: 'partent' , passeCompose: 'sont parti(e)' , imparfait: 'partaient' , futurSimple: 'partiront' , conditionnelPresent: 'partiraient' , subjonctifPresent: 'partent' , plusQueParfait: 'étaient parti(e)' , futurAnterieur: 'seront parti(e)' , conditionnelPasse: 'seraient parti(e)' , subjonctifPasse: 'soient parti(e)' , passeSimple: 'partirent' , subjonctifImparfait: 'partissent' , subjonctifPlusQueParfait: 'fussent parti(e)' , passeAnterieur: 'furent parti(e)' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'mettre', infinitive: 'mettre', translation: 'to put', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'mets' , passeCompose: 'ai mis' , imparfait: 'mettais' , futurSimple: 'mettrai' , conditionnelPresent: 'mettrais' , subjonctifPresent: 'mette' , plusQueParfait: 'avais mis' , futurAnterieur: 'aurai mis' , conditionnelPasse: 'aurais mis' , subjonctifPasse: 'aie mis' , passeSimple: 'mis' , subjonctifImparfait: 'misse' , subjonctifPlusQueParfait: 'eusse mis' , passeAnterieur: 'eus mis' },
            { sujet: 'tu' , present: 'mets' , passeCompose: 'as mis' , imparfait: 'mettais' , futurSimple: 'mettras' , conditionnelPresent: 'mettrais' , subjonctifPresent: 'mettes' , plusQueParfait: 'avais mis' , futurAnterieur: 'auras mis' , conditionnelPasse: 'aurais mis' , subjonctifPasse: 'aies mis' , passeSimple: 'mis' , subjonctifImparfait: 'misses' , subjonctifPlusQueParfait: 'eusses mis' , passeAnterieur: 'eus mis' },
            { sujet: 'il/elle' , present: 'met' , passeCompose: 'a mis' , imparfait: 'mettait' , futurSimple: 'mettra' , conditionnelPresent: 'mettrait' , subjonctifPresent: 'mette' , plusQueParfait: 'avait mis' , futurAnterieur: 'aura mis' , conditionnelPasse: 'aurait mis' , subjonctifPasse: 'ait mis' , passeSimple: 'mit' , subjonctifImparfait: 'mît' , subjonctifPlusQueParfait: 'eût mis' , passeAnterieur: 'eut mis' },
            { sujet: 'nous' , present: 'mettons' , passeCompose: 'avons mis' , imparfait: 'mettions' , futurSimple: 'mettrons' , conditionnelPresent: 'mettrions' , subjonctifPresent: 'mettions' , plusQueParfait: 'avions mis' , futurAnterieur: 'aurons mis' , conditionnelPasse: 'aurions mis' , subjonctifPasse: 'ayons mis' , passeSimple: 'mîmes' , subjonctifImparfait: 'missions' , subjonctifPlusQueParfait: 'eussions mis' , passeAnterieur: 'eûmes mis' },
            { sujet: 'vous' , present: 'mettez' , passeCompose: 'avez mis' , imparfait: 'mettiez' , futurSimple: 'mettrez' , conditionnelPresent: 'mettriez' , subjonctifPresent: 'mettiez' , plusQueParfait: 'aviez mis' , futurAnterieur: 'aurez mis' , conditionnelPasse: 'auriez mis' , subjonctifPasse: 'ayez mis' , passeSimple: 'mîtes' , subjonctifImparfait: 'missiez' , subjonctifPlusQueParfait: 'eussiez mis' , passeAnterieur: 'eûtes mis' },
            { sujet: 'ils/elles' , present: 'mettent' , passeCompose: 'ont mis' , imparfait: 'mettaient' , futurSimple: 'mettront' , conditionnelPresent: 'mettraient' , subjonctifPresent: 'mettent' , plusQueParfait: 'avaient mis' , futurAnterieur: 'auront mis' , conditionnelPasse: 'auraient mis' , subjonctifPasse: 'aient mis' , passeSimple: 'mirent' , subjonctifImparfait: 'missent' , subjonctifPlusQueParfait: 'eussent mis' , passeAnterieur: 'eurent mis' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'dire', infinitive: 'dire', translation: 'to say', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'dis' , passeCompose: 'ai dit' , imparfait: 'disais' , futurSimple: 'dirai' , conditionnelPresent: 'dirais' , subjonctifPresent: 'dise' , plusQueParfait: 'avais dit' , futurAnterieur: 'aurai dit' , conditionnelPasse: 'aurais dit' , subjonctifPasse: 'aie dit' , passeSimple: 'dis' , subjonctifImparfait: 'disse' , subjonctifPlusQueParfait: 'eusse dit' , passeAnterieur: 'eus dit' },
            { sujet: 'tu' , present: 'dis' , passeCompose: 'as dit' , imparfait: 'disais' , futurSimple: 'diras' , conditionnelPresent: 'dirais' , subjonctifPresent: 'dises' , plusQueParfait: 'avais dit' , futurAnterieur: 'auras dit' , conditionnelPasse: 'aurais dit' , subjonctifPasse: 'aies dit' , passeSimple: 'dis' , subjonctifImparfait: 'disses' , subjonctifPlusQueParfait: 'eusses dit' , passeAnterieur: 'eus dit' },
            { sujet: 'il/elle' , present: 'dit' , passeCompose: 'a dit' , imparfait: 'disait' , futurSimple: 'dira' , conditionnelPresent: 'dirait' , subjonctifPresent: 'dise' , plusQueParfait: 'avait dit' , futurAnterieur: 'aura dit' , conditionnelPasse: 'aurait dit' , subjonctifPasse: 'ait dit' , passeSimple: 'dit' , subjonctifImparfait: 'dît' , subjonctifPlusQueParfait: 'eût dit' , passeAnterieur: 'eut dit' },
            { sujet: 'nous' , present: 'disons' , passeCompose: 'avons dit' , imparfait: 'disions' , futurSimple: 'dirons' , conditionnelPresent: 'dirions' , subjonctifPresent: 'disions' , plusQueParfait: 'avions dit' , futurAnterieur: 'aurons dit' , conditionnelPasse: 'aurions dit' , subjonctifPasse: 'ayons dit' , passeSimple: 'dîmes' , subjonctifImparfait: 'dissions' , subjonctifPlusQueParfait: 'eussions dit' , passeAnterieur: 'eûmes dit' },
            { sujet: 'vous' , present: 'dites' , passeCompose: 'avez dit' , imparfait: 'disiez' , futurSimple: 'direz' , conditionnelPresent: 'diriez' , subjonctifPresent: 'disiez' , plusQueParfait: 'aviez dit' , futurAnterieur: 'aurez dit' , conditionnelPasse: 'auriez dit' , subjonctifPasse: 'ayez dit' , passeSimple: 'dîtes' , subjonctifImparfait: 'dissiez' , subjonctifPlusQueParfait: 'eussiez dit' , passeAnterieur: 'eûtes dit' },
            { sujet: 'ils/elles' , present: 'disent' , passeCompose: 'ont dit' , imparfait: 'disaient' , futurSimple: 'diront' , conditionnelPresent: 'diraient' , subjonctifPresent: 'disent' , plusQueParfait: 'avaient dit' , futurAnterieur: 'auront dit' , conditionnelPasse: 'auraient dit' , subjonctifPasse: 'aient dit' , passeSimple: 'dirent' , subjonctifImparfait: 'dissent' , subjonctifPlusQueParfait: 'eussent dit' , passeAnterieur: 'eurent dit' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'voir', infinitive: 'voir', translation: 'to see', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'vois' , passeCompose: 'ai vu' , imparfait: 'voyais' , futurSimple: 'verrai' , conditionnelPresent: 'verrais' , subjonctifPresent: 'voie' , plusQueParfait: 'avais vu' , futurAnterieur: 'aurai vu' , conditionnelPasse: 'aurais vu' , subjonctifPasse: 'aie vu' , passeSimple: 'vis' , subjonctifImparfait: 'visse' , subjonctifPlusQueParfait: 'eusse vu' , passeAnterieur: 'eus vu' },
            { sujet: 'tu' , present: 'vois' , passeCompose: 'as vu' , imparfait: 'voyais' , futurSimple: 'verras' , conditionnelPresent: 'verrais' , subjonctifPresent: 'voies' , plusQueParfait: 'avais vu' , futurAnterieur: 'auras vu' , conditionnelPasse: 'aurais vu' , subjonctifPasse: 'aies vu' , passeSimple: 'vis' , subjonctifImparfait: 'visses' , subjonctifPlusQueParfait: 'eusses vu' , passeAnterieur: 'eus vu' },
            { sujet: 'il/elle' , present: 'voit' , passeCompose: 'a vu' , imparfait: 'voyait' , futurSimple: 'verra' , conditionnelPresent: 'verrait' , subjonctifPresent: 'voie' , plusQueParfait: 'avait vu' , futurAnterieur: 'aura vu' , conditionnelPasse: 'aurait vu' , subjonctifPasse: 'ait vu' , passeSimple: 'vit' , subjonctifImparfait: 'vît' , subjonctifPlusQueParfait: 'eût vu' , passeAnterieur: 'eut vu' },
            { sujet: 'nous' , present: 'voyons' , passeCompose: 'avons vu' , imparfait: 'voyions' , futurSimple: 'verrons' , conditionnelPresent: 'verrions' , subjonctifPresent: 'voyions' , plusQueParfait: 'avions vu' , futurAnterieur: 'aurons vu' , conditionnelPasse: 'aurions vu' , subjonctifPasse: 'ayons vu' , passeSimple: 'vîmes' , subjonctifImparfait: 'vissions' , subjonctifPlusQueParfait: 'eussions vu' , passeAnterieur: 'eûmes vu' },
            { sujet: 'vous' , present: 'voyez' , passeCompose: 'avez vu' , imparfait: 'voyiez' , futurSimple: 'verrez' , conditionnelPresent: 'verriez' , subjonctifPresent: 'voyiez' , plusQueParfait: 'aviez vu' , futurAnterieur: 'aurez vu' , conditionnelPasse: 'auriez vu' , subjonctifPasse: 'ayez vu' , passeSimple: 'vîtes' , subjonctifImparfait: 'vissiez' , subjonctifPlusQueParfait: 'eussiez vu' , passeAnterieur: 'eûtes vu' },
            { sujet: 'ils/elles' , present: 'voient' , passeCompose: 'ont vu' , imparfait: 'voyaient' , futurSimple: 'verront' , conditionnelPresent: 'verraient' , subjonctifPresent: 'voient' , plusQueParfait: 'avaient vu' , futurAnterieur: 'auront vu' , conditionnelPasse: 'auraient vu' , subjonctifPasse: 'aient vu' , passeSimple: 'virent' , subjonctifImparfait: 'vissent' , subjonctifPlusQueParfait: 'eussent vu' , passeAnterieur: 'eurent vu' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'sortir', infinitive: 'sortir', translation: 'to go out / to leave', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'sors' , passeCompose: 'suis sorti(e)' , imparfait: 'sortais' , futurSimple: 'sortirai' , conditionnelPresent: 'sortirais' , subjonctifPresent: 'sorte' , plusQueParfait: 'étais sorti(e)' , futurAnterieur: 'serai sorti(e)' , conditionnelPasse: 'serais sorti(e)' , subjonctifPasse: 'sois sorti(e)' , passeSimple: 'sortis' , subjonctifImparfait: 'sortisse' , subjonctifPlusQueParfait: 'fusse sorti(e)' , passeAnterieur: 'fus sorti(e)' },
            { sujet: 'tu' , present: 'sors' , passeCompose: 'es sorti(e)' , imparfait: 'sortais' , futurSimple: 'sortiras' , conditionnelPresent: 'sortirais' , subjonctifPresent: 'sortes' , plusQueParfait: 'étais sorti(e)' , futurAnterieur: 'seras sorti(e)' , conditionnelPasse: 'serais sorti(e)' , subjonctifPasse: 'sois sorti(e)' , passeSimple: 'sortis' , subjonctifImparfait: 'sortisses' , subjonctifPlusQueParfait: 'fusses sorti(e)' , passeAnterieur: 'fus sorti(e)' },
            { sujet: 'il/elle' , present: 'sort' , passeCompose: 'est sorti(e)' , imparfait: 'sortait' , futurSimple: 'sortira' , conditionnelPresent: 'sortirait' , subjonctifPresent: 'sorte' , plusQueParfait: 'était sorti(e)' , futurAnterieur: 'sera sorti(e)' , conditionnelPasse: 'serait sorti(e)' , subjonctifPasse: 'soit sorti(e)' , passeSimple: 'sortit' , subjonctifImparfait: 'sortît' , subjonctifPlusQueParfait: 'fût sorti(e)' , passeAnterieur: 'fut sorti(e)' },
            { sujet: 'nous' , present: 'sortons' , passeCompose: 'sommes sorti(e)' , imparfait: 'sortions' , futurSimple: 'sortirons' , conditionnelPresent: 'sortirions' , subjonctifPresent: 'sortions' , plusQueParfait: 'étions sorti(e)' , futurAnterieur: 'serons sorti(e)' , conditionnelPasse: 'serions sorti(e)' , subjonctifPasse: 'soyons sorti(e)' , passeSimple: 'sortîmes' , subjonctifImparfait: 'sortissions' , subjonctifPlusQueParfait: 'fussions sorti(e)' , passeAnterieur: 'fûmes sorti(e)' },
            { sujet: 'vous' , present: 'sortez' , passeCompose: 'êtes sorti(e)' , imparfait: 'sortiez' , futurSimple: 'sortirez' , conditionnelPresent: 'sortiriez' , subjonctifPresent: 'sortiez' , plusQueParfait: 'étiez sorti(e)' , futurAnterieur: 'serez sorti(e)' , conditionnelPasse: 'seriez sorti(e)' , subjonctifPasse: 'soyez sorti(e)' , passeSimple: 'sortîtes' , subjonctifImparfait: 'sortissiez' , subjonctifPlusQueParfait: 'fussiez sorti(e)' , passeAnterieur: 'fûtes sorti(e)' },
            { sujet: 'ils/elles' , present: 'sortent' , passeCompose: 'sont sorti(e)' , imparfait: 'sortaient' , futurSimple: 'sortiront' , conditionnelPresent: 'sortiraient' , subjonctifPresent: 'sortent' , plusQueParfait: 'étaient sorti(e)' , futurAnterieur: 'seront sorti(e)' , conditionnelPasse: 'seraient sorti(e)' , subjonctifPasse: 'soient sorti(e)' , passeSimple: 'sortirent' , subjonctifImparfait: 'sortissent' , subjonctifPlusQueParfait: 'fussent sorti(e)' , passeAnterieur: 'furent sorti(e)' },
            ],
        },
        {
        level: 'A2', unit: 5,
            id: 'croire', infinitive: 'croire', translation: 'to believe / to think', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'crois' , passeCompose: 'ai cru' , imparfait: 'croyais' , futurSimple: 'croirai' , conditionnelPresent: 'croirais' , subjonctifPresent: 'croie' , plusQueParfait: 'avais cru' , futurAnterieur: 'aurai cru' , conditionnelPasse: 'aurais cru' , subjonctifPasse: 'aie cru' , passeSimple: 'crus' , subjonctifImparfait: 'crusse' , subjonctifPlusQueParfait: 'eusse cru' , passeAnterieur: 'eus cru' },
            { sujet: 'tu' , present: 'crois' , passeCompose: 'as cru' , imparfait: 'croyais' , futurSimple: 'croiras' , conditionnelPresent: 'croirais' , subjonctifPresent: 'croies' , plusQueParfait: 'avais cru' , futurAnterieur: 'auras cru' , conditionnelPasse: 'aurais cru' , subjonctifPasse: 'aies cru' , passeSimple: 'crus' , subjonctifImparfait: 'crusses' , subjonctifPlusQueParfait: 'eusses cru' , passeAnterieur: 'eus cru' },
            { sujet: 'il/elle' , present: 'croit' , passeCompose: 'a cru' , imparfait: 'croyait' , futurSimple: 'croira' , conditionnelPresent: 'croirait' , subjonctifPresent: 'croie' , plusQueParfait: 'avait cru' , futurAnterieur: 'aura cru' , conditionnelPasse: 'aurait cru' , subjonctifPasse: 'ait cru' , passeSimple: 'crut' , subjonctifImparfait: 'crût' , subjonctifPlusQueParfait: 'eût cru' , passeAnterieur: 'eut cru' },
            { sujet: 'nous' , present: 'croyons' , passeCompose: 'avons cru' , imparfait: 'croyions' , futurSimple: 'croirons' , conditionnelPresent: 'croirions' , subjonctifPresent: 'croyions' , plusQueParfait: 'avions cru' , futurAnterieur: 'aurons cru' , conditionnelPasse: 'aurions cru' , subjonctifPasse: 'ayons cru' , passeSimple: 'crûmes' , subjonctifImparfait: 'crussions' , subjonctifPlusQueParfait: 'eussions cru' , passeAnterieur: 'eûmes cru' },
            { sujet: 'vous' , present: 'croyez' , passeCompose: 'avez cru' , imparfait: 'croyiez' , futurSimple: 'croirez' , conditionnelPresent: 'croiriez' , subjonctifPresent: 'croyiez' , plusQueParfait: 'aviez cru' , futurAnterieur: 'aurez cru' , conditionnelPasse: 'auriez cru' , subjonctifPasse: 'ayez cru' , passeSimple: 'crûtes' , subjonctifImparfait: 'crussiez' , subjonctifPlusQueParfait: 'eussiez cru' , passeAnterieur: 'eûtes cru' },
            { sujet: 'ils/elles' , present: 'croient' , passeCompose: 'ont cru' , imparfait: 'croyaient' , futurSimple: 'croiront' , conditionnelPresent: 'croiraient' , subjonctifPresent: 'croient' , plusQueParfait: 'avaient cru' , futurAnterieur: 'auront cru' , conditionnelPasse: 'auraient cru' , subjonctifPasse: 'aient cru' , passeSimple: 'crurent' , subjonctifImparfait: 'crussent' , subjonctifPlusQueParfait: 'eussent cru' , passeAnterieur: 'eurent cru' },
            ],
        },
    ];

export const helpersA2: Record<string, HelperVerbFR> = {

};
