import type { HelperVerbFR, VerbEntry, VerbGroup } from '../../../types/verbs';

export const verbGroupB1: VerbGroup = { id: 'b1', title: 'B1 — Building Fluency', titleFR: 'B1 — Construction de la fluidité', description: 'Master complex verbs and irregular patterns', descriptionFR: 'Maîtrisez les verbes complexes et les irrégularités', icon: '📘', color: '#0891B2' };

export const verbsB1: VerbEntry[] = [
        {
        level: 'B1', unit: 5,
            id: 'obeir', infinitive: 'obéir', translation: 'to obey', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'obéis' , passeCompose: 'ai obéi' , imparfait: 'obéissais' , futurSimple: 'obéirai' , conditionnelPresent: 'obéirais' , subjonctifPresent: 'obéisse' , plusQueParfait: 'avais obéi' , futurAnterieur: 'aurai obéi' , conditionnelPasse: 'aurais obéi' , subjonctifPasse: 'aie obéi' , passeSimple: 'obéis' , subjonctifImparfait: 'obéisse' , subjonctifPlusQueParfait: 'eusse obéi' , passeAnterieur: 'eus obéi' },
            { sujet: 'tu' , present: 'obéis' , passeCompose: 'as obéi' , imparfait: 'obéissais' , futurSimple: 'obéiras' , conditionnelPresent: 'obéirais' , subjonctifPresent: 'obéisses' , plusQueParfait: 'avais obéi' , futurAnterieur: 'auras obéi' , conditionnelPasse: 'aurais obéi' , subjonctifPasse: 'aies obéi' , passeSimple: 'obéis' , subjonctifImparfait: 'obéisses' , subjonctifPlusQueParfait: 'eusses obéi' , passeAnterieur: 'eus obéi' },
            { sujet: 'il/elle' , present: 'obéit' , passeCompose: 'a obéi' , imparfait: 'obéissait' , futurSimple: 'obéira' , conditionnelPresent: 'obéirait' , subjonctifPresent: 'obéisse' , plusQueParfait: 'avait obéi' , futurAnterieur: 'aura obéi' , conditionnelPasse: 'aurait obéi' , subjonctifPasse: 'ait obéi' , passeSimple: 'obéit' , subjonctifImparfait: 'obéît' , subjonctifPlusQueParfait: 'eût obéi' , passeAnterieur: 'eut obéi' },
            { sujet: 'nous' , present: 'obéissons' , passeCompose: 'avons obéi' , imparfait: 'obéissions' , futurSimple: 'obéirons' , conditionnelPresent: 'obéirions' , subjonctifPresent: 'obéissions' , plusQueParfait: 'avions obéi' , futurAnterieur: 'aurons obéi' , conditionnelPasse: 'aurions obéi' , subjonctifPasse: 'ayons obéi' , passeSimple: 'obéîmes' , subjonctifImparfait: 'obéissions' , subjonctifPlusQueParfait: 'eussions obéi' , passeAnterieur: 'eûmes obéi' },
            { sujet: 'vous' , present: 'obéissez' , passeCompose: 'avez obéi' , imparfait: 'obéissiez' , futurSimple: 'obéirez' , conditionnelPresent: 'obéiriez' , subjonctifPresent: 'obéissiez' , plusQueParfait: 'aviez obéi' , futurAnterieur: 'aurez obéi' , conditionnelPasse: 'auriez obéi' , subjonctifPasse: 'ayez obéi' , passeSimple: 'obéîtes' , subjonctifImparfait: 'obéissiez' , subjonctifPlusQueParfait: 'eussiez obéi' , passeAnterieur: 'eûtes obéi' },
            { sujet: 'ils/elles' , present: 'obéissent' , passeCompose: 'ont obéi' , imparfait: 'obéissaient' , futurSimple: 'obéiront' , conditionnelPresent: 'obéiraient' , subjonctifPresent: 'obéissent' , plusQueParfait: 'avaient obéi' , futurAnterieur: 'auront obéi' , conditionnelPasse: 'auraient obéi' , subjonctifPasse: 'aient obéi' , passeSimple: 'obéirent' , subjonctifImparfait: 'obéissent' , subjonctifPlusQueParfait: 'eussent obéi' , passeAnterieur: 'eurent obéi' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'rougir', infinitive: 'rougir', translation: 'to blush / to turn red', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'rougis' , passeCompose: 'ai rougi' , imparfait: 'rougissais' , futurSimple: 'rougirai' , conditionnelPresent: 'rougirais' , subjonctifPresent: 'rougisse' , plusQueParfait: 'avais rougi' , futurAnterieur: 'aurai rougi' , conditionnelPasse: 'aurais rougi' , subjonctifPasse: 'aie rougi' , passeSimple: 'rougis' , subjonctifImparfait: 'rougisse' , subjonctifPlusQueParfait: 'eusse rougi' , passeAnterieur: 'eus rougi' },
            { sujet: 'tu' , present: 'rougis' , passeCompose: 'as rougi' , imparfait: 'rougissais' , futurSimple: 'rougiras' , conditionnelPresent: 'rougirais' , subjonctifPresent: 'rougisses' , plusQueParfait: 'avais rougi' , futurAnterieur: 'auras rougi' , conditionnelPasse: 'aurais rougi' , subjonctifPasse: 'aies rougi' , passeSimple: 'rougis' , subjonctifImparfait: 'rougisses' , subjonctifPlusQueParfait: 'eusses rougi' , passeAnterieur: 'eus rougi' },
            { sujet: 'il/elle' , present: 'rougit' , passeCompose: 'a rougi' , imparfait: 'rougissait' , futurSimple: 'rougira' , conditionnelPresent: 'rougirait' , subjonctifPresent: 'rougisse' , plusQueParfait: 'avait rougi' , futurAnterieur: 'aura rougi' , conditionnelPasse: 'aurait rougi' , subjonctifPasse: 'ait rougi' , passeSimple: 'rougit' , subjonctifImparfait: 'rougît' , subjonctifPlusQueParfait: 'eût rougi' , passeAnterieur: 'eut rougi' },
            { sujet: 'nous' , present: 'rougissons' , passeCompose: 'avons rougi' , imparfait: 'rougissions' , futurSimple: 'rougirons' , conditionnelPresent: 'rougirions' , subjonctifPresent: 'rougissions' , plusQueParfait: 'avions rougi' , futurAnterieur: 'aurons rougi' , conditionnelPasse: 'aurions rougi' , subjonctifPasse: 'ayons rougi' , passeSimple: 'rougîmes' , subjonctifImparfait: 'rougissions' , subjonctifPlusQueParfait: 'eussions rougi' , passeAnterieur: 'eûmes rougi' },
            { sujet: 'vous' , present: 'rougissez' , passeCompose: 'avez rougi' , imparfait: 'rougissiez' , futurSimple: 'rougirez' , conditionnelPresent: 'rougiriez' , subjonctifPresent: 'rougissiez' , plusQueParfait: 'aviez rougi' , futurAnterieur: 'aurez rougi' , conditionnelPasse: 'auriez rougi' , subjonctifPasse: 'ayez rougi' , passeSimple: 'rougîtes' , subjonctifImparfait: 'rougissiez' , subjonctifPlusQueParfait: 'eussiez rougi' , passeAnterieur: 'eûtes rougi' },
            { sujet: 'ils/elles' , present: 'rougissent' , passeCompose: 'ont rougi' , imparfait: 'rougissaient' , futurSimple: 'rougiront' , conditionnelPresent: 'rougiraient' , subjonctifPresent: 'rougissent' , plusQueParfait: 'avaient rougi' , futurAnterieur: 'auront rougi' , conditionnelPasse: 'auraient rougi' , subjonctifPasse: 'aient rougi' , passeSimple: 'rougirent' , subjonctifImparfait: 'rougissent' , subjonctifPlusQueParfait: 'eussent rougi' , passeAnterieur: 'eurent rougi' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'reflechir', infinitive: 'réfléchir', translation: 'to think / to reflect', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'réfléchis' , passeCompose: 'ai réfléchi' , imparfait: 'réfléchissais' , futurSimple: 'réfléchirai' , conditionnelPresent: 'réfléchirais' , subjonctifPresent: 'réfléchisse' , plusQueParfait: 'avais réfléchi' , futurAnterieur: 'aurai réfléchi' , conditionnelPasse: 'aurais réfléchi' , subjonctifPasse: 'aie réfléchi' , passeSimple: 'réfléchis' , subjonctifImparfait: 'réfléchisse' , subjonctifPlusQueParfait: 'eusse réfléchi' , passeAnterieur: 'eus réfléchi' },
            { sujet: 'tu' , present: 'réfléchis' , passeCompose: 'as réfléchi' , imparfait: 'réfléchissais' , futurSimple: 'réfléchiras' , conditionnelPresent: 'réfléchirais' , subjonctifPresent: 'réfléchisses' , plusQueParfait: 'avais réfléchi' , futurAnterieur: 'auras réfléchi' , conditionnelPasse: 'aurais réfléchi' , subjonctifPasse: 'aies réfléchi' , passeSimple: 'réfléchis' , subjonctifImparfait: 'réfléchisses' , subjonctifPlusQueParfait: 'eusses réfléchi' , passeAnterieur: 'eus réfléchi' },
            { sujet: 'il/elle' , present: 'réfléchit' , passeCompose: 'a réfléchi' , imparfait: 'réfléchissait' , futurSimple: 'réfléchira' , conditionnelPresent: 'réfléchirait' , subjonctifPresent: 'réfléchisse' , plusQueParfait: 'avait réfléchi' , futurAnterieur: 'aura réfléchi' , conditionnelPasse: 'aurait réfléchi' , subjonctifPasse: 'ait réfléchi' , passeSimple: 'réfléchit' , subjonctifImparfait: 'réfléchît' , subjonctifPlusQueParfait: 'eût réfléchi' , passeAnterieur: 'eut réfléchi' },
            { sujet: 'nous' , present: 'réfléchissons' , passeCompose: 'avons réfléchi' , imparfait: 'réfléchissions' , futurSimple: 'réfléchirons' , conditionnelPresent: 'réfléchirions' , subjonctifPresent: 'réfléchissions' , plusQueParfait: 'avions réfléchi' , futurAnterieur: 'aurons réfléchi' , conditionnelPasse: 'aurions réfléchi' , subjonctifPasse: 'ayons réfléchi' , passeSimple: 'réfléchîmes' , subjonctifImparfait: 'réfléchissions' , subjonctifPlusQueParfait: 'eussions réfléchi' , passeAnterieur: 'eûmes réfléchi' },
            { sujet: 'vous' , present: 'réfléchissez' , passeCompose: 'avez réfléchi' , imparfait: 'réfléchissiez' , futurSimple: 'réfléchirez' , conditionnelPresent: 'réfléchiriez' , subjonctifPresent: 'réfléchissiez' , plusQueParfait: 'aviez réfléchi' , futurAnterieur: 'aurez réfléchi' , conditionnelPasse: 'auriez réfléchi' , subjonctifPasse: 'ayez réfléchi' , passeSimple: 'réfléchîtes' , subjonctifImparfait: 'réfléchissiez' , subjonctifPlusQueParfait: 'eussiez réfléchi' , passeAnterieur: 'eûtes réfléchi' },
            { sujet: 'ils/elles' , present: 'réfléchissent' , passeCompose: 'ont réfléchi' , imparfait: 'réfléchissaient' , futurSimple: 'réfléchiront' , conditionnelPresent: 'réfléchiraient' , subjonctifPresent: 'réfléchissent' , plusQueParfait: 'avaient réfléchi' , futurAnterieur: 'auront réfléchi' , conditionnelPasse: 'auraient réfléchi' , subjonctifPasse: 'aient réfléchi' , passeSimple: 'réfléchirent' , subjonctifImparfait: 'réfléchissent' , subjonctifPlusQueParfait: 'eussent réfléchi' , passeAnterieur: 'eurent réfléchi' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'remplir', infinitive: 'remplir', translation: 'to fill', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'remplis' , passeCompose: 'ai rempli' , imparfait: 'remplissais' , futurSimple: 'remplirai' , conditionnelPresent: 'remplirais' , subjonctifPresent: 'remplisse' , plusQueParfait: 'avais rempli' , futurAnterieur: 'aurai rempli' , conditionnelPasse: 'aurais rempli' , subjonctifPasse: 'aie rempli' , passeSimple: 'remplis' , subjonctifImparfait: 'remplisse' , subjonctifPlusQueParfait: 'eusse rempli' , passeAnterieur: 'eus rempli' },
            { sujet: 'tu' , present: 'remplis' , passeCompose: 'as rempli' , imparfait: 'remplissais' , futurSimple: 'rempliras' , conditionnelPresent: 'remplirais' , subjonctifPresent: 'remplisses' , plusQueParfait: 'avais rempli' , futurAnterieur: 'auras rempli' , conditionnelPasse: 'aurais rempli' , subjonctifPasse: 'aies rempli' , passeSimple: 'remplis' , subjonctifImparfait: 'remplisses' , subjonctifPlusQueParfait: 'eusses rempli' , passeAnterieur: 'eus rempli' },
            { sujet: 'il/elle' , present: 'remplit' , passeCompose: 'a rempli' , imparfait: 'remplissait' , futurSimple: 'remplira' , conditionnelPresent: 'remplirait' , subjonctifPresent: 'remplisse' , plusQueParfait: 'avait rempli' , futurAnterieur: 'aura rempli' , conditionnelPasse: 'aurait rempli' , subjonctifPasse: 'ait rempli' , passeSimple: 'remplit' , subjonctifImparfait: 'remplît' , subjonctifPlusQueParfait: 'eût rempli' , passeAnterieur: 'eut rempli' },
            { sujet: 'nous' , present: 'remplissons' , passeCompose: 'avons rempli' , imparfait: 'remplissions' , futurSimple: 'remplirons' , conditionnelPresent: 'remplirions' , subjonctifPresent: 'remplissions' , plusQueParfait: 'avions rempli' , futurAnterieur: 'aurons rempli' , conditionnelPasse: 'aurions rempli' , subjonctifPasse: 'ayons rempli' , passeSimple: 'remplîmes' , subjonctifImparfait: 'remplissions' , subjonctifPlusQueParfait: 'eussions rempli' , passeAnterieur: 'eûmes rempli' },
            { sujet: 'vous' , present: 'remplissez' , passeCompose: 'avez rempli' , imparfait: 'remplissiez' , futurSimple: 'remplirez' , conditionnelPresent: 'rempliriez' , subjonctifPresent: 'remplissiez' , plusQueParfait: 'aviez rempli' , futurAnterieur: 'aurez rempli' , conditionnelPasse: 'auriez rempli' , subjonctifPasse: 'ayez rempli' , passeSimple: 'remplîtes' , subjonctifImparfait: 'remplissiez' , subjonctifPlusQueParfait: 'eussiez rempli' , passeAnterieur: 'eûtes rempli' },
            { sujet: 'ils/elles' , present: 'remplissent' , passeCompose: 'ont rempli' , imparfait: 'remplissaient' , futurSimple: 'rempliront' , conditionnelPresent: 'rempliraient' , subjonctifPresent: 'remplissent' , plusQueParfait: 'avaient rempli' , futurAnterieur: 'auront rempli' , conditionnelPasse: 'auraient rempli' , subjonctifPasse: 'aient rempli' , passeSimple: 'remplirent' , subjonctifImparfait: 'remplissent' , subjonctifPlusQueParfait: 'eussent rempli' , passeAnterieur: 'eurent rempli' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'batir', infinitive: 'bâtir', translation: 'to build', type: '-IR', color: '#0891B2',
            rows: [
            { sujet: 'je' , present: 'bâtis' , passeCompose: 'ai bâti' , imparfait: 'bâtissais' , futurSimple: 'bâtirai' , conditionnelPresent: 'bâtirais' , subjonctifPresent: 'bâtisse' , plusQueParfait: 'avais bâti' , futurAnterieur: 'aurai bâti' , conditionnelPasse: 'aurais bâti' , subjonctifPasse: 'aie bâti' , passeSimple: 'bâtis' , subjonctifImparfait: 'bâtisse' , subjonctifPlusQueParfait: 'eusse bâti' , passeAnterieur: 'eus bâti' },
            { sujet: 'tu' , present: 'bâtis' , passeCompose: 'as bâti' , imparfait: 'bâtissais' , futurSimple: 'bâtiras' , conditionnelPresent: 'bâtirais' , subjonctifPresent: 'bâtisses' , plusQueParfait: 'avais bâti' , futurAnterieur: 'auras bâti' , conditionnelPasse: 'aurais bâti' , subjonctifPasse: 'aies bâti' , passeSimple: 'bâtis' , subjonctifImparfait: 'bâtisses' , subjonctifPlusQueParfait: 'eusses bâti' , passeAnterieur: 'eus bâti' },
            { sujet: 'il/elle' , present: 'bâtit' , passeCompose: 'a bâti' , imparfait: 'bâtissait' , futurSimple: 'bâtira' , conditionnelPresent: 'bâtirait' , subjonctifPresent: 'bâtisse' , plusQueParfait: 'avait bâti' , futurAnterieur: 'aura bâti' , conditionnelPasse: 'aurait bâti' , subjonctifPasse: 'ait bâti' , passeSimple: 'bâtit' , subjonctifImparfait: 'bâtît' , subjonctifPlusQueParfait: 'eût bâti' , passeAnterieur: 'eut bâti' },
            { sujet: 'nous' , present: 'bâtissons' , passeCompose: 'avons bâti' , imparfait: 'bâtissions' , futurSimple: 'bâtirons' , conditionnelPresent: 'bâtirions' , subjonctifPresent: 'bâtissions' , plusQueParfait: 'avions bâti' , futurAnterieur: 'aurons bâti' , conditionnelPasse: 'aurions bâti' , subjonctifPasse: 'ayons bâti' , passeSimple: 'bâtîmes' , subjonctifImparfait: 'bâtissions' , subjonctifPlusQueParfait: 'eussions bâti' , passeAnterieur: 'eûmes bâti' },
            { sujet: 'vous' , present: 'bâtissez' , passeCompose: 'avez bâti' , imparfait: 'bâtissiez' , futurSimple: 'bâtirez' , conditionnelPresent: 'bâtiriez' , subjonctifPresent: 'bâtissiez' , plusQueParfait: 'aviez bâti' , futurAnterieur: 'aurez bâti' , conditionnelPasse: 'auriez bâti' , subjonctifPasse: 'ayez bâti' , passeSimple: 'bâtîtes' , subjonctifImparfait: 'bâtissiez' , subjonctifPlusQueParfait: 'eussiez bâti' , passeAnterieur: 'eûtes bâti' },
            { sujet: 'ils/elles' , present: 'bâtissent' , passeCompose: 'ont bâti' , imparfait: 'bâtissaient' , futurSimple: 'bâtiront' , conditionnelPresent: 'bâtiraient' , subjonctifPresent: 'bâtissent' , plusQueParfait: 'avaient bâti' , futurAnterieur: 'auront bâti' , conditionnelPasse: 'auraient bâti' , subjonctifPasse: 'aient bâti' , passeSimple: 'bâtirent' , subjonctifImparfait: 'bâtissent' , subjonctifPlusQueParfait: 'eussent bâti' , passeAnterieur: 'eurent bâti' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'perdre', infinitive: 'perdre', translation: 'to lose', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'perds' , passeCompose: 'ai perdu' , imparfait: 'perdais' , futurSimple: 'perdrai' , conditionnelPresent: 'perdrais' , subjonctifPresent: 'perde' , plusQueParfait: 'avais perdu' , futurAnterieur: 'aurai perdu' , conditionnelPasse: 'aurais perdu' , subjonctifPasse: 'aie perdu' , passeSimple: 'perdis' , subjonctifImparfait: 'perdisse' , subjonctifPlusQueParfait: 'eusse perdu' , passeAnterieur: 'eus perdu' },
            { sujet: 'tu' , present: 'perds' , passeCompose: 'as perdu' , imparfait: 'perdais' , futurSimple: 'perdras' , conditionnelPresent: 'perdrais' , subjonctifPresent: 'perdes' , plusQueParfait: 'avais perdu' , futurAnterieur: 'auras perdu' , conditionnelPasse: 'aurais perdu' , subjonctifPasse: 'aies perdu' , passeSimple: 'perdis' , subjonctifImparfait: 'perdisses' , subjonctifPlusQueParfait: 'eusses perdu' , passeAnterieur: 'eus perdu' },
            { sujet: 'il/elle' , present: 'perd' , passeCompose: 'a perdu' , imparfait: 'perdait' , futurSimple: 'perdra' , conditionnelPresent: 'perdrait' , subjonctifPresent: 'perde' , plusQueParfait: 'avait perdu' , futurAnterieur: 'aura perdu' , conditionnelPasse: 'aurait perdu' , subjonctifPasse: 'ait perdu' , passeSimple: 'perdit' , subjonctifImparfait: 'perdît' , subjonctifPlusQueParfait: 'eût perdu' , passeAnterieur: 'eut perdu' },
            { sujet: 'nous' , present: 'perdons' , passeCompose: 'avons perdu' , imparfait: 'perdions' , futurSimple: 'perdrons' , conditionnelPresent: 'perdrions' , subjonctifPresent: 'perdions' , plusQueParfait: 'avions perdu' , futurAnterieur: 'aurons perdu' , conditionnelPasse: 'aurions perdu' , subjonctifPasse: 'ayons perdu' , passeSimple: 'perdîmes' , subjonctifImparfait: 'perdissions' , subjonctifPlusQueParfait: 'eussions perdu' , passeAnterieur: 'eûmes perdu' },
            { sujet: 'vous' , present: 'perdez' , passeCompose: 'avez perdu' , imparfait: 'perdiez' , futurSimple: 'perdrez' , conditionnelPresent: 'perdriez' , subjonctifPresent: 'perdiez' , plusQueParfait: 'aviez perdu' , futurAnterieur: 'aurez perdu' , conditionnelPasse: 'auriez perdu' , subjonctifPasse: 'ayez perdu' , passeSimple: 'perdîtes' , subjonctifImparfait: 'perdissiez' , subjonctifPlusQueParfait: 'eussiez perdu' , passeAnterieur: 'eûtes perdu' },
            { sujet: 'ils/elles' , present: 'perdent' , passeCompose: 'ont perdu' , imparfait: 'perdaient' , futurSimple: 'perdront' , conditionnelPresent: 'perdraient' , subjonctifPresent: 'perdent' , plusQueParfait: 'avaient perdu' , futurAnterieur: 'auront perdu' , conditionnelPasse: 'auraient perdu' , subjonctifPasse: 'aient perdu' , passeSimple: 'perdirent' , subjonctifImparfait: 'perdissent' , subjonctifPlusQueParfait: 'eussent perdu' , passeAnterieur: 'eurent perdu' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'descendre', infinitive: 'descendre', translation: 'to go down / to come down', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'descends' , passeCompose: 'suis descendu(e)' , imparfait: 'descendais' , futurSimple: 'descendrai' , conditionnelPresent: 'descendrais' , subjonctifPresent: 'descende' , plusQueParfait: 'étais descendu(e)' , futurAnterieur: 'serai descendu(e)' , conditionnelPasse: 'serais descendu(e)' , subjonctifPasse: 'sois descendu(e)' , passeSimple: 'descendis' , subjonctifImparfait: 'descendisse' , subjonctifPlusQueParfait: 'fusse descendu(e)' , passeAnterieur: 'fus descendu(e)' },
            { sujet: 'tu' , present: 'descends' , passeCompose: 'es descendu(e)' , imparfait: 'descendais' , futurSimple: 'descendras' , conditionnelPresent: 'descendrais' , subjonctifPresent: 'descendes' , plusQueParfait: 'étais descendu(e)' , futurAnterieur: 'seras descendu(e)' , conditionnelPasse: 'serais descendu(e)' , subjonctifPasse: 'sois descendu(e)' , passeSimple: 'descendis' , subjonctifImparfait: 'descendisses' , subjonctifPlusQueParfait: 'fusses descendu(e)' , passeAnterieur: 'fus descendu(e)' },
            { sujet: 'il/elle' , present: 'descend' , passeCompose: 'est descendu(e)' , imparfait: 'descendait' , futurSimple: 'descendra' , conditionnelPresent: 'descendrait' , subjonctifPresent: 'descende' , plusQueParfait: 'était descendu(e)' , futurAnterieur: 'sera descendu(e)' , conditionnelPasse: 'serait descendu(e)' , subjonctifPasse: 'soit descendu(e)' , passeSimple: 'descendit' , subjonctifImparfait: 'descendît' , subjonctifPlusQueParfait: 'fût descendu(e)' , passeAnterieur: 'fut descendu(e)' },
            { sujet: 'nous' , present: 'descendons' , passeCompose: 'sommes descendu(e)' , imparfait: 'descendions' , futurSimple: 'descendrons' , conditionnelPresent: 'descendrions' , subjonctifPresent: 'descendions' , plusQueParfait: 'étions descendu(e)' , futurAnterieur: 'serons descendu(e)' , conditionnelPasse: 'serions descendu(e)' , subjonctifPasse: 'soyons descendu(e)' , passeSimple: 'descendîmes' , subjonctifImparfait: 'descendissions' , subjonctifPlusQueParfait: 'fussions descendu(e)' , passeAnterieur: 'fûmes descendu(e)' },
            { sujet: 'vous' , present: 'descendez' , passeCompose: 'êtes descendu(e)' , imparfait: 'descendiez' , futurSimple: 'descendrez' , conditionnelPresent: 'descendriez' , subjonctifPresent: 'descendiez' , plusQueParfait: 'étiez descendu(e)' , futurAnterieur: 'serez descendu(e)' , conditionnelPasse: 'seriez descendu(e)' , subjonctifPasse: 'soyez descendu(e)' , passeSimple: 'descendîtes' , subjonctifImparfait: 'descendissiez' , subjonctifPlusQueParfait: 'fussiez descendu(e)' , passeAnterieur: 'fûtes descendu(e)' },
            { sujet: 'ils/elles' , present: 'descendent' , passeCompose: 'sont descendu(e)' , imparfait: 'descendaient' , futurSimple: 'descendront' , conditionnelPresent: 'descendraient' , subjonctifPresent: 'descendent' , plusQueParfait: 'étaient descendu(e)' , futurAnterieur: 'seront descendu(e)' , conditionnelPasse: 'seraient descendu(e)' , subjonctifPasse: 'soient descendu(e)' , passeSimple: 'descendirent' , subjonctifImparfait: 'descendissent' , subjonctifPlusQueParfait: 'fussent descendu(e)' , passeAnterieur: 'furent descendu(e)' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'rendre', infinitive: 'rendre', translation: 'to give back / to return', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'rends' , passeCompose: 'ai rendu' , imparfait: 'rendais' , futurSimple: 'rendrai' , conditionnelPresent: 'rendrais' , subjonctifPresent: 'rende' , plusQueParfait: 'avais rendu' , futurAnterieur: 'aurai rendu' , conditionnelPasse: 'aurais rendu' , subjonctifPasse: 'aie rendu' , passeSimple: 'rendis' , subjonctifImparfait: 'rendisse' , subjonctifPlusQueParfait: 'eusse rendu' , passeAnterieur: 'eus rendu' },
            { sujet: 'tu' , present: 'rends' , passeCompose: 'as rendu' , imparfait: 'rendais' , futurSimple: 'rendras' , conditionnelPresent: 'rendrais' , subjonctifPresent: 'rendes' , plusQueParfait: 'avais rendu' , futurAnterieur: 'auras rendu' , conditionnelPasse: 'aurais rendu' , subjonctifPasse: 'aies rendu' , passeSimple: 'rendis' , subjonctifImparfait: 'rendisses' , subjonctifPlusQueParfait: 'eusses rendu' , passeAnterieur: 'eus rendu' },
            { sujet: 'il/elle' , present: 'rend' , passeCompose: 'a rendu' , imparfait: 'rendait' , futurSimple: 'rendra' , conditionnelPresent: 'rendrait' , subjonctifPresent: 'rende' , plusQueParfait: 'avait rendu' , futurAnterieur: 'aura rendu' , conditionnelPasse: 'aurait rendu' , subjonctifPasse: 'ait rendu' , passeSimple: 'rendit' , subjonctifImparfait: 'rendît' , subjonctifPlusQueParfait: 'eût rendu' , passeAnterieur: 'eut rendu' },
            { sujet: 'nous' , present: 'rendons' , passeCompose: 'avons rendu' , imparfait: 'rendions' , futurSimple: 'rendrons' , conditionnelPresent: 'rendrions' , subjonctifPresent: 'rendions' , plusQueParfait: 'avions rendu' , futurAnterieur: 'aurons rendu' , conditionnelPasse: 'aurions rendu' , subjonctifPasse: 'ayons rendu' , passeSimple: 'rendîmes' , subjonctifImparfait: 'rendissions' , subjonctifPlusQueParfait: 'eussions rendu' , passeAnterieur: 'eûmes rendu' },
            { sujet: 'vous' , present: 'rendez' , passeCompose: 'avez rendu' , imparfait: 'rendiez' , futurSimple: 'rendrez' , conditionnelPresent: 'rendriez' , subjonctifPresent: 'rendiez' , plusQueParfait: 'aviez rendu' , futurAnterieur: 'aurez rendu' , conditionnelPasse: 'auriez rendu' , subjonctifPasse: 'ayez rendu' , passeSimple: 'rendîtes' , subjonctifImparfait: 'rendissiez' , subjonctifPlusQueParfait: 'eussiez rendu' , passeAnterieur: 'eûtes rendu' },
            { sujet: 'ils/elles' , present: 'rendent' , passeCompose: 'ont rendu' , imparfait: 'rendaient' , futurSimple: 'rendront' , conditionnelPresent: 'rendraient' , subjonctifPresent: 'rendent' , plusQueParfait: 'avaient rendu' , futurAnterieur: 'auront rendu' , conditionnelPasse: 'auraient rendu' , subjonctifPasse: 'aient rendu' , passeSimple: 'rendirent' , subjonctifImparfait: 'rendissent' , subjonctifPlusQueParfait: 'eussent rendu' , passeAnterieur: 'eurent rendu' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'savoir', infinitive: 'savoir', translation: 'to know', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'sais' , passeCompose: 'ai su' , imparfait: 'savais' , futurSimple: 'saurai' , conditionnelPresent: 'saurais' , subjonctifPresent: 'sache' , plusQueParfait: 'avais su' , futurAnterieur: 'aurai su' , conditionnelPasse: 'aurais su' , subjonctifPasse: 'aie su' , passeSimple: 'sus' , subjonctifImparfait: 'susse' , subjonctifPlusQueParfait: 'eusse su' , passeAnterieur: 'eus su' },
            { sujet: 'tu' , present: 'sais' , passeCompose: 'as su' , imparfait: 'savais' , futurSimple: 'sauras' , conditionnelPresent: 'saurais' , subjonctifPresent: 'saches' , plusQueParfait: 'avais su' , futurAnterieur: 'auras su' , conditionnelPasse: 'aurais su' , subjonctifPasse: 'aies su' , passeSimple: 'sus' , subjonctifImparfait: 'susses' , subjonctifPlusQueParfait: 'eusses su' , passeAnterieur: 'eus su' },
            { sujet: 'il/elle' , present: 'sait' , passeCompose: 'a su' , imparfait: 'savait' , futurSimple: 'saura' , conditionnelPresent: 'saurait' , subjonctifPresent: 'sache' , plusQueParfait: 'avait su' , futurAnterieur: 'aura su' , conditionnelPasse: 'aurait su' , subjonctifPasse: 'ait su' , passeSimple: 'sut' , subjonctifImparfait: 'sût' , subjonctifPlusQueParfait: 'eût su' , passeAnterieur: 'eut su' },
            { sujet: 'nous' , present: 'savons' , passeCompose: 'avons su' , imparfait: 'savions' , futurSimple: 'saurons' , conditionnelPresent: 'saurions' , subjonctifPresent: 'sachions' , plusQueParfait: 'avions su' , futurAnterieur: 'aurons su' , conditionnelPasse: 'aurions su' , subjonctifPasse: 'ayons su' , passeSimple: 'sûmes' , subjonctifImparfait: 'sussions' , subjonctifPlusQueParfait: 'eussions su' , passeAnterieur: 'eûmes su' },
            { sujet: 'vous' , present: 'savez' , passeCompose: 'avez su' , imparfait: 'saviez' , futurSimple: 'saurez' , conditionnelPresent: 'sauriez' , subjonctifPresent: 'sachiez' , plusQueParfait: 'aviez su' , futurAnterieur: 'aurez su' , conditionnelPasse: 'auriez su' , subjonctifPasse: 'ayez su' , passeSimple: 'sûtes' , subjonctifImparfait: 'sussiez' , subjonctifPlusQueParfait: 'eussiez su' , passeAnterieur: 'eûtes su' },
            { sujet: 'ils/elles' , present: 'savent' , passeCompose: 'ont su' , imparfait: 'savaient' , futurSimple: 'sauront' , conditionnelPresent: 'sauraient' , subjonctifPresent: 'sachent' , plusQueParfait: 'avaient su' , futurAnterieur: 'auront su' , conditionnelPasse: 'auraient su' , subjonctifPasse: 'aient su' , passeSimple: 'surent' , subjonctifImparfait: 'sussent' , subjonctifPlusQueParfait: 'eussent su' , passeAnterieur: 'eurent su' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'lire', infinitive: 'lire', translation: 'to read', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'lis' , passeCompose: 'ai lu' , imparfait: 'lisais' , futurSimple: 'lirai' , conditionnelPresent: 'lirais' , subjonctifPresent: 'lise' , plusQueParfait: 'avais lu' , futurAnterieur: 'aurai lu' , conditionnelPasse: 'aurais lu' , subjonctifPasse: 'aie lu' , passeSimple: 'lus' , subjonctifImparfait: 'lusse' , subjonctifPlusQueParfait: 'eusse lu' , passeAnterieur: 'eus lu' },
            { sujet: 'tu' , present: 'lis' , passeCompose: 'as lu' , imparfait: 'lisais' , futurSimple: 'liras' , conditionnelPresent: 'lirais' , subjonctifPresent: 'lises' , plusQueParfait: 'avais lu' , futurAnterieur: 'auras lu' , conditionnelPasse: 'aurais lu' , subjonctifPasse: 'aies lu' , passeSimple: 'lus' , subjonctifImparfait: 'lusses' , subjonctifPlusQueParfait: 'eusses lu' , passeAnterieur: 'eus lu' },
            { sujet: 'il/elle' , present: 'lit' , passeCompose: 'a lu' , imparfait: 'lisait' , futurSimple: 'lira' , conditionnelPresent: 'lirait' , subjonctifPresent: 'lise' , plusQueParfait: 'avait lu' , futurAnterieur: 'aura lu' , conditionnelPasse: 'aurait lu' , subjonctifPasse: 'ait lu' , passeSimple: 'lut' , subjonctifImparfait: 'lût' , subjonctifPlusQueParfait: 'eût lu' , passeAnterieur: 'eut lu' },
            { sujet: 'nous' , present: 'lisons' , passeCompose: 'avons lu' , imparfait: 'lisions' , futurSimple: 'lirons' , conditionnelPresent: 'lirions' , subjonctifPresent: 'lisions' , plusQueParfait: 'avions lu' , futurAnterieur: 'aurons lu' , conditionnelPasse: 'aurions lu' , subjonctifPasse: 'ayons lu' , passeSimple: 'lûmes' , subjonctifImparfait: 'lussions' , subjonctifPlusQueParfait: 'eussions lu' , passeAnterieur: 'eûmes lu' },
            { sujet: 'vous' , present: 'lisez' , passeCompose: 'avez lu' , imparfait: 'lisiez' , futurSimple: 'lirez' , conditionnelPresent: 'liriez' , subjonctifPresent: 'lisiez' , plusQueParfait: 'aviez lu' , futurAnterieur: 'aurez lu' , conditionnelPasse: 'auriez lu' , subjonctifPasse: 'ayez lu' , passeSimple: 'lûtes' , subjonctifImparfait: 'lussiez' , subjonctifPlusQueParfait: 'eussiez lu' , passeAnterieur: 'eûtes lu' },
            { sujet: 'ils/elles' , present: 'lisent' , passeCompose: 'ont lu' , imparfait: 'lisaient' , futurSimple: 'liront' , conditionnelPresent: 'liraient' , subjonctifPresent: 'lisent' , plusQueParfait: 'avaient lu' , futurAnterieur: 'auront lu' , conditionnelPasse: 'auraient lu' , subjonctifPasse: 'aient lu' , passeSimple: 'lurent' , subjonctifImparfait: 'lussent' , subjonctifPlusQueParfait: 'eussent lu' , passeAnterieur: 'eurent lu' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'ecrire', infinitive: 'écrire', translation: 'to write', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'écris' , passeCompose: 'ai écrit' , imparfait: 'écrivais' , futurSimple: 'écrirai' , conditionnelPresent: 'écrirais' , subjonctifPresent: 'écrive' , plusQueParfait: 'avais écrit' , futurAnterieur: 'aurai écrit' , conditionnelPasse: 'aurais écrit' , subjonctifPasse: 'aie écrit' , passeSimple: 'écrivis' , subjonctifImparfait: 'écrivisse' , subjonctifPlusQueParfait: 'eusse écrit' , passeAnterieur: 'eus écrit' },
            { sujet: 'tu' , present: 'écris' , passeCompose: 'as écrit' , imparfait: 'écrivais' , futurSimple: 'écriras' , conditionnelPresent: 'écrirais' , subjonctifPresent: 'écrives' , plusQueParfait: 'avais écrit' , futurAnterieur: 'auras écrit' , conditionnelPasse: 'aurais écrit' , subjonctifPasse: 'aies écrit' , passeSimple: 'écrivis' , subjonctifImparfait: 'écrivisses' , subjonctifPlusQueParfait: 'eusses écrit' , passeAnterieur: 'eus écrit' },
            { sujet: 'il/elle' , present: 'écrit' , passeCompose: 'a écrit' , imparfait: 'écrivait' , futurSimple: 'écrira' , conditionnelPresent: 'écrirait' , subjonctifPresent: 'écrive' , plusQueParfait: 'avait écrit' , futurAnterieur: 'aura écrit' , conditionnelPasse: 'aurait écrit' , subjonctifPasse: 'ait écrit' , passeSimple: 'écrivit' , subjonctifImparfait: 'écrivît' , subjonctifPlusQueParfait: 'eût écrit' , passeAnterieur: 'eut écrit' },
            { sujet: 'nous' , present: 'écrivons' , passeCompose: 'avons écrit' , imparfait: 'écrivions' , futurSimple: 'écrirons' , conditionnelPresent: 'écririons' , subjonctifPresent: 'écrivions' , plusQueParfait: 'avions écrit' , futurAnterieur: 'aurons écrit' , conditionnelPasse: 'aurions écrit' , subjonctifPasse: 'ayons écrit' , passeSimple: 'écrivîmes' , subjonctifImparfait: 'écrivissions' , subjonctifPlusQueParfait: 'eussions écrit' , passeAnterieur: 'eûmes écrit' },
            { sujet: 'vous' , present: 'écrivez' , passeCompose: 'avez écrit' , imparfait: 'écriviez' , futurSimple: 'écrirez' , conditionnelPresent: 'écririez' , subjonctifPresent: 'écriviez' , plusQueParfait: 'aviez écrit' , futurAnterieur: 'aurez écrit' , conditionnelPasse: 'auriez écrit' , subjonctifPasse: 'ayez écrit' , passeSimple: 'écrivîtes' , subjonctifImparfait: 'écrivissiez' , subjonctifPlusQueParfait: 'eussiez écrit' , passeAnterieur: 'eûtes écrit' },
            { sujet: 'ils/elles' , present: 'écrivent' , passeCompose: 'ont écrit' , imparfait: 'écrivaient' , futurSimple: 'écriront' , conditionnelPresent: 'écriraient' , subjonctifPresent: 'écrivent' , plusQueParfait: 'avaient écrit' , futurAnterieur: 'auront écrit' , conditionnelPasse: 'auraient écrit' , subjonctifPasse: 'aient écrit' , passeSimple: 'écrivirent' , subjonctifImparfait: 'écrivissent' , subjonctifPlusQueParfait: 'eussent écrit' , passeAnterieur: 'eurent écrit' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'connaitre', infinitive: 'connaître', translation: 'to know / be acquainted with', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'connais' , passeCompose: 'ai connu' , imparfait: 'connaissais' , futurSimple: 'connaîtrai' , conditionnelPresent: 'connaîtrais' , subjonctifPresent: 'connaisse' , plusQueParfait: 'avais connu' , futurAnterieur: 'aurai connu' , conditionnelPasse: 'aurais connu' , subjonctifPasse: 'aie connu' , passeSimple: 'connus' , subjonctifImparfait: 'connusse' , subjonctifPlusQueParfait: 'eusse connu' , passeAnterieur: 'eus connu' },
            { sujet: 'tu' , present: 'connais' , passeCompose: 'as connu' , imparfait: 'connaissais' , futurSimple: 'connaîtras' , conditionnelPresent: 'connaîtrais' , subjonctifPresent: 'connaisses' , plusQueParfait: 'avais connu' , futurAnterieur: 'auras connu' , conditionnelPasse: 'aurais connu' , subjonctifPasse: 'aies connu' , passeSimple: 'connus' , subjonctifImparfait: 'connusses' , subjonctifPlusQueParfait: 'eusses connu' , passeAnterieur: 'eus connu' },
            { sujet: 'il/elle' , present: 'connaît' , passeCompose: 'a connu' , imparfait: 'connaissait' , futurSimple: 'connaîtra' , conditionnelPresent: 'connaîtrait' , subjonctifPresent: 'connaisse' , plusQueParfait: 'avait connu' , futurAnterieur: 'aura connu' , conditionnelPasse: 'aurait connu' , subjonctifPasse: 'ait connu' , passeSimple: 'connut' , subjonctifImparfait: 'connût' , subjonctifPlusQueParfait: 'eût connu' , passeAnterieur: 'eut connu' },
            { sujet: 'nous' , present: 'connaissons' , passeCompose: 'avons connu' , imparfait: 'connaissions' , futurSimple: 'connaîtrons' , conditionnelPresent: 'connaîtrions' , subjonctifPresent: 'connaissions' , plusQueParfait: 'avions connu' , futurAnterieur: 'aurons connu' , conditionnelPasse: 'aurions connu' , subjonctifPasse: 'ayons connu' , passeSimple: 'connûmes' , subjonctifImparfait: 'connussions' , subjonctifPlusQueParfait: 'eussions connu' , passeAnterieur: 'eûmes connu' },
            { sujet: 'vous' , present: 'connaissez' , passeCompose: 'avez connu' , imparfait: 'connaissiez' , futurSimple: 'connaîtrez' , conditionnelPresent: 'connaîtriez' , subjonctifPresent: 'connaissiez' , plusQueParfait: 'aviez connu' , futurAnterieur: 'aurez connu' , conditionnelPasse: 'auriez connu' , subjonctifPasse: 'ayez connu' , passeSimple: 'connûtes' , subjonctifImparfait: 'connussiez' , subjonctifPlusQueParfait: 'eussiez connu' , passeAnterieur: 'eûtes connu' },
            { sujet: 'ils/elles' , present: 'connaissent' , passeCompose: 'ont connu' , imparfait: 'connaissaient' , futurSimple: 'connaîtront' , conditionnelPresent: 'connaîtraient' , subjonctifPresent: 'connaissent' , plusQueParfait: 'avaient connu' , futurAnterieur: 'auront connu' , conditionnelPasse: 'auraient connu' , subjonctifPasse: 'aient connu' , passeSimple: 'connurent' , subjonctifImparfait: 'connussent' , subjonctifPlusQueParfait: 'eussent connu' , passeAnterieur: 'eurent connu' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'boire', infinitive: 'boire', translation: 'to drink', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'bois' , passeCompose: 'ai bu' , imparfait: 'buvais' , futurSimple: 'boirai' , conditionnelPresent: 'boirais' , subjonctifPresent: 'boive' , plusQueParfait: 'avais bu' , futurAnterieur: 'aurai bu' , conditionnelPasse: 'aurais bu' , subjonctifPasse: 'aie bu' , passeSimple: 'bus' , subjonctifImparfait: 'busse' , subjonctifPlusQueParfait: 'eusse bu' , passeAnterieur: 'eus bu' },
            { sujet: 'tu' , present: 'bois' , passeCompose: 'as bu' , imparfait: 'buvais' , futurSimple: 'boiras' , conditionnelPresent: 'boirais' , subjonctifPresent: 'boives' , plusQueParfait: 'avais bu' , futurAnterieur: 'auras bu' , conditionnelPasse: 'aurais bu' , subjonctifPasse: 'aies bu' , passeSimple: 'bus' , subjonctifImparfait: 'busses' , subjonctifPlusQueParfait: 'eusses bu' , passeAnterieur: 'eus bu' },
            { sujet: 'il/elle' , present: 'boit' , passeCompose: 'a bu' , imparfait: 'buvait' , futurSimple: 'boira' , conditionnelPresent: 'boirait' , subjonctifPresent: 'boive' , plusQueParfait: 'avait bu' , futurAnterieur: 'aura bu' , conditionnelPasse: 'aurait bu' , subjonctifPasse: 'ait bu' , passeSimple: 'but' , subjonctifImparfait: 'bût' , subjonctifPlusQueParfait: 'eût bu' , passeAnterieur: 'eut bu' },
            { sujet: 'nous' , present: 'buvons' , passeCompose: 'avons bu' , imparfait: 'buvions' , futurSimple: 'boirons' , conditionnelPresent: 'boirions' , subjonctifPresent: 'buvions' , plusQueParfait: 'avions bu' , futurAnterieur: 'aurons bu' , conditionnelPasse: 'aurions bu' , subjonctifPasse: 'ayons bu' , passeSimple: 'bûmes' , subjonctifImparfait: 'bussions' , subjonctifPlusQueParfait: 'eussions bu' , passeAnterieur: 'eûmes bu' },
            { sujet: 'vous' , present: 'buvez' , passeCompose: 'avez bu' , imparfait: 'buviez' , futurSimple: 'boirez' , conditionnelPresent: 'boiriez' , subjonctifPresent: 'buviez' , plusQueParfait: 'aviez bu' , futurAnterieur: 'aurez bu' , conditionnelPasse: 'auriez bu' , subjonctifPasse: 'ayez bu' , passeSimple: 'bûtes' , subjonctifImparfait: 'bussiez' , subjonctifPlusQueParfait: 'eussiez bu' , passeAnterieur: 'eûtes bu' },
            { sujet: 'ils/elles' , present: 'boivent' , passeCompose: 'ont bu' , imparfait: 'buvaient' , futurSimple: 'boiront' , conditionnelPresent: 'boiraient' , subjonctifPresent: 'boivent' , plusQueParfait: 'avaient bu' , futurAnterieur: 'auront bu' , conditionnelPasse: 'auraient bu' , subjonctifPasse: 'aient bu' , passeSimple: 'burent' , subjonctifImparfait: 'bussent' , subjonctifPlusQueParfait: 'eussent bu' , passeAnterieur: 'eurent bu' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'tenir', infinitive: 'tenir', translation: 'to hold / to keep', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'tiens' , passeCompose: 'ai tenu' , imparfait: 'tenais' , futurSimple: 'tiendrai' , conditionnelPresent: 'tiendrais' , subjonctifPresent: 'tienne' , plusQueParfait: 'avais tenu' , futurAnterieur: 'aurai tenu' , conditionnelPasse: 'aurais tenu' , subjonctifPasse: 'aie tenu' , passeSimple: 'tins' , subjonctifImparfait: 'tinsse' , subjonctifPlusQueParfait: 'eusse tenu' , passeAnterieur: 'eus tenu' },
            { sujet: 'tu' , present: 'tiens' , passeCompose: 'as tenu' , imparfait: 'tenais' , futurSimple: 'tiendras' , conditionnelPresent: 'tiendrais' , subjonctifPresent: 'tiennes' , plusQueParfait: 'avais tenu' , futurAnterieur: 'auras tenu' , conditionnelPasse: 'aurais tenu' , subjonctifPasse: 'aies tenu' , passeSimple: 'tins' , subjonctifImparfait: 'tinsses' , subjonctifPlusQueParfait: 'eusses tenu' , passeAnterieur: 'eus tenu' },
            { sujet: 'il/elle' , present: 'tient' , passeCompose: 'a tenu' , imparfait: 'tenait' , futurSimple: 'tiendra' , conditionnelPresent: 'tiendrait' , subjonctifPresent: 'tienne' , plusQueParfait: 'avait tenu' , futurAnterieur: 'aura tenu' , conditionnelPasse: 'aurait tenu' , subjonctifPasse: 'ait tenu' , passeSimple: 'tint' , subjonctifImparfait: 'tînt' , subjonctifPlusQueParfait: 'eût tenu' , passeAnterieur: 'eut tenu' },
            { sujet: 'nous' , present: 'tenons' , passeCompose: 'avons tenu' , imparfait: 'tenions' , futurSimple: 'tiendrons' , conditionnelPresent: 'tiendrions' , subjonctifPresent: 'tenions' , plusQueParfait: 'avions tenu' , futurAnterieur: 'aurons tenu' , conditionnelPasse: 'aurions tenu' , subjonctifPasse: 'ayons tenu' , passeSimple: 'tînmes' , subjonctifImparfait: 'tinssions' , subjonctifPlusQueParfait: 'eussions tenu' , passeAnterieur: 'eûmes tenu' },
            { sujet: 'vous' , present: 'tenez' , passeCompose: 'avez tenu' , imparfait: 'teniez' , futurSimple: 'tiendrez' , conditionnelPresent: 'tiendriez' , subjonctifPresent: 'teniez' , plusQueParfait: 'aviez tenu' , futurAnterieur: 'aurez tenu' , conditionnelPasse: 'auriez tenu' , subjonctifPasse: 'ayez tenu' , passeSimple: 'tîntes' , subjonctifImparfait: 'tinssiez' , subjonctifPlusQueParfait: 'eussiez tenu' , passeAnterieur: 'eûtes tenu' },
            { sujet: 'ils/elles' , present: 'tiennent' , passeCompose: 'ont tenu' , imparfait: 'tenaient' , futurSimple: 'tiendront' , conditionnelPresent: 'tiendraient' , subjonctifPresent: 'tiennent' , plusQueParfait: 'avaient tenu' , futurAnterieur: 'auront tenu' , conditionnelPasse: 'auraient tenu' , subjonctifPasse: 'aient tenu' , passeSimple: 'tinrent' , subjonctifImparfait: 'tinssent' , subjonctifPlusQueParfait: 'eussent tenu' , passeAnterieur: 'eurent tenu' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'ouvrir', infinitive: 'ouvrir', translation: 'to open', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'ouvre' , passeCompose: 'ai ouvert' , imparfait: 'ouvrais' , futurSimple: 'ouvrirai' , conditionnelPresent: 'ouvrirais' , subjonctifPresent: 'ouvre' , plusQueParfait: 'avais ouvert' , futurAnterieur: 'aurai ouvert' , conditionnelPasse: 'aurais ouvert' , subjonctifPasse: 'aie ouvert' , passeSimple: 'ouvris' , subjonctifImparfait: 'ouvrisse' , subjonctifPlusQueParfait: 'eusse ouvert' , passeAnterieur: 'eus ouvert' },
            { sujet: 'tu' , present: 'ouvres' , passeCompose: 'as ouvert' , imparfait: 'ouvrais' , futurSimple: 'ouvriras' , conditionnelPresent: 'ouvrirais' , subjonctifPresent: 'ouvres' , plusQueParfait: 'avais ouvert' , futurAnterieur: 'auras ouvert' , conditionnelPasse: 'aurais ouvert' , subjonctifPasse: 'aies ouvert' , passeSimple: 'ouvris' , subjonctifImparfait: 'ouvrisses' , subjonctifPlusQueParfait: 'eusses ouvert' , passeAnterieur: 'eus ouvert' },
            { sujet: 'il/elle' , present: 'ouvre' , passeCompose: 'a ouvert' , imparfait: 'ouvrait' , futurSimple: 'ouvrira' , conditionnelPresent: 'ouvrirait' , subjonctifPresent: 'ouvre' , plusQueParfait: 'avait ouvert' , futurAnterieur: 'aura ouvert' , conditionnelPasse: 'aurait ouvert' , subjonctifPasse: 'ait ouvert' , passeSimple: 'ouvrit' , subjonctifImparfait: 'ouvrît' , subjonctifPlusQueParfait: 'eût ouvert' , passeAnterieur: 'eut ouvert' },
            { sujet: 'nous' , present: 'ouvrons' , passeCompose: 'avons ouvert' , imparfait: 'ouvrions' , futurSimple: 'ouvrirons' , conditionnelPresent: 'ouvririons' , subjonctifPresent: 'ouvrions' , plusQueParfait: 'avions ouvert' , futurAnterieur: 'aurons ouvert' , conditionnelPasse: 'aurions ouvert' , subjonctifPasse: 'ayons ouvert' , passeSimple: 'ouvrîmes' , subjonctifImparfait: 'ouvrissions' , subjonctifPlusQueParfait: 'eussions ouvert' , passeAnterieur: 'eûmes ouvert' },
            { sujet: 'vous' , present: 'ouvrez' , passeCompose: 'avez ouvert' , imparfait: 'ouvriez' , futurSimple: 'ouvrirez' , conditionnelPresent: 'ouvririez' , subjonctifPresent: 'ouvriez' , plusQueParfait: 'aviez ouvert' , futurAnterieur: 'aurez ouvert' , conditionnelPasse: 'auriez ouvert' , subjonctifPasse: 'ayez ouvert' , passeSimple: 'ouvrîtes' , subjonctifImparfait: 'ouvrissiez' , subjonctifPlusQueParfait: 'eussiez ouvert' , passeAnterieur: 'eûtes ouvert' },
            { sujet: 'ils/elles' , present: 'ouvrent' , passeCompose: 'ont ouvert' , imparfait: 'ouvraient' , futurSimple: 'ouvriront' , conditionnelPresent: 'ouvriraient' , subjonctifPresent: 'ouvrent' , plusQueParfait: 'avaient ouvert' , futurAnterieur: 'auront ouvert' , conditionnelPasse: 'auraient ouvert' , subjonctifPasse: 'aient ouvert' , passeSimple: 'ouvrirent' , subjonctifImparfait: 'ouvrissent' , subjonctifPlusQueParfait: 'eussent ouvert' , passeAnterieur: 'eurent ouvert' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'courir', infinitive: 'courir', translation: 'to run', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'cours' , passeCompose: 'ai couru' , imparfait: 'courais' , futurSimple: 'courrai' , conditionnelPresent: 'courrais' , subjonctifPresent: 'coure' , plusQueParfait: 'avais couru' , futurAnterieur: 'aurai couru' , conditionnelPasse: 'aurais couru' , subjonctifPasse: 'aie couru' , passeSimple: 'courus' , subjonctifImparfait: 'courusse' , subjonctifPlusQueParfait: 'eusse couru' , passeAnterieur: 'eus couru' },
            { sujet: 'tu' , present: 'cours' , passeCompose: 'as couru' , imparfait: 'courais' , futurSimple: 'courras' , conditionnelPresent: 'courrais' , subjonctifPresent: 'coures' , plusQueParfait: 'avais couru' , futurAnterieur: 'auras couru' , conditionnelPasse: 'aurais couru' , subjonctifPasse: 'aies couru' , passeSimple: 'courus' , subjonctifImparfait: 'courusses' , subjonctifPlusQueParfait: 'eusses couru' , passeAnterieur: 'eus couru' },
            { sujet: 'il/elle' , present: 'court' , passeCompose: 'a couru' , imparfait: 'courait' , futurSimple: 'courra' , conditionnelPresent: 'courrait' , subjonctifPresent: 'coure' , plusQueParfait: 'avait couru' , futurAnterieur: 'aura couru' , conditionnelPasse: 'aurait couru' , subjonctifPasse: 'ait couru' , passeSimple: 'courut' , subjonctifImparfait: 'courût' , subjonctifPlusQueParfait: 'eût couru' , passeAnterieur: 'eut couru' },
            { sujet: 'nous' , present: 'courons' , passeCompose: 'avons couru' , imparfait: 'courions' , futurSimple: 'courrons' , conditionnelPresent: 'courrions' , subjonctifPresent: 'courions' , plusQueParfait: 'avions couru' , futurAnterieur: 'aurons couru' , conditionnelPasse: 'aurions couru' , subjonctifPasse: 'ayons couru' , passeSimple: 'courûmes' , subjonctifImparfait: 'courussions' , subjonctifPlusQueParfait: 'eussions couru' , passeAnterieur: 'eûmes couru' },
            { sujet: 'vous' , present: 'courez' , passeCompose: 'avez couru' , imparfait: 'couriez' , futurSimple: 'courrez' , conditionnelPresent: 'courriez' , subjonctifPresent: 'couriez' , plusQueParfait: 'aviez couru' , futurAnterieur: 'aurez couru' , conditionnelPasse: 'auriez couru' , subjonctifPasse: 'ayez couru' , passeSimple: 'courûtes' , subjonctifImparfait: 'courussiez' , subjonctifPlusQueParfait: 'eussiez couru' , passeAnterieur: 'eûtes couru' },
            { sujet: 'ils/elles' , present: 'courent' , passeCompose: 'ont couru' , imparfait: 'couraient' , futurSimple: 'courront' , conditionnelPresent: 'courraient' , subjonctifPresent: 'courent' , plusQueParfait: 'avaient couru' , futurAnterieur: 'auront couru' , conditionnelPasse: 'auraient couru' , subjonctifPasse: 'aient couru' , passeSimple: 'coururent' , subjonctifImparfait: 'courussent' , subjonctifPlusQueParfait: 'eussent couru' , passeAnterieur: 'eurent couru' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'vivre', infinitive: 'vivre', translation: 'to live', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'vis' , passeCompose: 'ai vécu' , imparfait: 'vivais' , futurSimple: 'vivrai' , conditionnelPresent: 'vivrais' , subjonctifPresent: 'vive' , plusQueParfait: 'avais vécu' , futurAnterieur: 'aurai vécu' , conditionnelPasse: 'aurais vécu' , subjonctifPasse: 'aie vécu' , passeSimple: 'vécus' , subjonctifImparfait: 'vécusse' , subjonctifPlusQueParfait: 'eusse vécu' , passeAnterieur: 'eus vécu' },
            { sujet: 'tu' , present: 'vis' , passeCompose: 'as vécu' , imparfait: 'vivais' , futurSimple: 'vivras' , conditionnelPresent: 'vivrais' , subjonctifPresent: 'vives' , plusQueParfait: 'avais vécu' , futurAnterieur: 'auras vécu' , conditionnelPasse: 'aurais vécu' , subjonctifPasse: 'aies vécu' , passeSimple: 'vécus' , subjonctifImparfait: 'vécusses' , subjonctifPlusQueParfait: 'eusses vécu' , passeAnterieur: 'eus vécu' },
            { sujet: 'il/elle' , present: 'vit' , passeCompose: 'a vécu' , imparfait: 'vivait' , futurSimple: 'vivra' , conditionnelPresent: 'vivrait' , subjonctifPresent: 'vive' , plusQueParfait: 'avait vécu' , futurAnterieur: 'aura vécu' , conditionnelPasse: 'aurait vécu' , subjonctifPasse: 'ait vécu' , passeSimple: 'vécut' , subjonctifImparfait: 'vécût' , subjonctifPlusQueParfait: 'eût vécu' , passeAnterieur: 'eut vécu' },
            { sujet: 'nous' , present: 'vivons' , passeCompose: 'avons vécu' , imparfait: 'vivions' , futurSimple: 'vivrons' , conditionnelPresent: 'vivrions' , subjonctifPresent: 'vivions' , plusQueParfait: 'avions vécu' , futurAnterieur: 'aurons vécu' , conditionnelPasse: 'aurions vécu' , subjonctifPasse: 'ayons vécu' , passeSimple: 'vécûmes' , subjonctifImparfait: 'vécussions' , subjonctifPlusQueParfait: 'eussions vécu' , passeAnterieur: 'eûmes vécu' },
            { sujet: 'vous' , present: 'vivez' , passeCompose: 'avez vécu' , imparfait: 'viviez' , futurSimple: 'vivrez' , conditionnelPresent: 'vivriez' , subjonctifPresent: 'viviez' , plusQueParfait: 'aviez vécu' , futurAnterieur: 'aurez vécu' , conditionnelPasse: 'auriez vécu' , subjonctifPasse: 'ayez vécu' , passeSimple: 'vécûtes' , subjonctifImparfait: 'vécussiez' , subjonctifPlusQueParfait: 'eussiez vécu' , passeAnterieur: 'eûtes vécu' },
            { sujet: 'ils/elles' , present: 'vivent' , passeCompose: 'ont vécu' , imparfait: 'vivaient' , futurSimple: 'vivront' , conditionnelPresent: 'vivraient' , subjonctifPresent: 'vivent' , plusQueParfait: 'avaient vécu' , futurAnterieur: 'auront vécu' , conditionnelPasse: 'auraient vécu' , subjonctifPasse: 'aient vécu' , passeSimple: 'vécurent' , subjonctifImparfait: 'vécussent' , subjonctifPlusQueParfait: 'eussent vécu' , passeAnterieur: 'eurent vécu' },
            ],
        },
        {
        level: 'B1', unit: 5,
            id: 'recevoir', infinitive: 'recevoir', translation: 'to receive', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'reçois' , passeCompose: 'ai reçu' , imparfait: 'recevais' , futurSimple: 'recevrai' , conditionnelPresent: 'recevrais' , subjonctifPresent: 'reçoive' , plusQueParfait: 'avais reçu' , futurAnterieur: 'aurai reçu' , conditionnelPasse: 'aurais reçu' , subjonctifPasse: 'aie reçu' , passeSimple: 'reçus' , subjonctifImparfait: 'reçusse' , subjonctifPlusQueParfait: 'eusse reçu' , passeAnterieur: 'eus reçu' },
            { sujet: 'tu' , present: 'reçois' , passeCompose: 'as reçu' , imparfait: 'recevais' , futurSimple: 'recevras' , conditionnelPresent: 'recevrais' , subjonctifPresent: 'reçoives' , plusQueParfait: 'avais reçu' , futurAnterieur: 'auras reçu' , conditionnelPasse: 'aurais reçu' , subjonctifPasse: 'aies reçu' , passeSimple: 'reçus' , subjonctifImparfait: 'reçusses' , subjonctifPlusQueParfait: 'eusses reçu' , passeAnterieur: 'eus reçu' },
            { sujet: 'il/elle' , present: 'reçoit' , passeCompose: 'a reçu' , imparfait: 'recevait' , futurSimple: 'recevra' , conditionnelPresent: 'recevrait' , subjonctifPresent: 'reçoive' , plusQueParfait: 'avait reçu' , futurAnterieur: 'aura reçu' , conditionnelPasse: 'aurait reçu' , subjonctifPasse: 'ait reçu' , passeSimple: 'reçut' , subjonctifImparfait: 'reçût' , subjonctifPlusQueParfait: 'eût reçu' , passeAnterieur: 'eut reçu' },
            { sujet: 'nous' , present: 'recevons' , passeCompose: 'avons reçu' , imparfait: 'recevions' , futurSimple: 'recevrons' , conditionnelPresent: 'recevrions' , subjonctifPresent: 'recevions' , plusQueParfait: 'avions reçu' , futurAnterieur: 'aurons reçu' , conditionnelPasse: 'aurions reçu' , subjonctifPasse: 'ayons reçu' , passeSimple: 'reçûmes' , subjonctifImparfait: 'reçussions' , subjonctifPlusQueParfait: 'eussions reçu' , passeAnterieur: 'eûmes reçu' },
            { sujet: 'vous' , present: 'recevez' , passeCompose: 'avez reçu' , imparfait: 'receviez' , futurSimple: 'recevrez' , conditionnelPresent: 'recevriez' , subjonctifPresent: 'receviez' , plusQueParfait: 'aviez reçu' , futurAnterieur: 'aurez reçu' , conditionnelPasse: 'auriez reçu' , subjonctifPasse: 'ayez reçu' , passeSimple: 'reçûtes' , subjonctifImparfait: 'reçussiez' , subjonctifPlusQueParfait: 'eussiez reçu' , passeAnterieur: 'eûtes reçu' },
            { sujet: 'ils/elles' , present: 'reçoivent' , passeCompose: 'ont reçu' , imparfait: 'recevaient' , futurSimple: 'recevront' , conditionnelPresent: 'recevraient' , subjonctifPresent: 'reçoivent' , plusQueParfait: 'avaient reçu' , futurAnterieur: 'auront reçu' , conditionnelPasse: 'auraient reçu' , subjonctifPasse: 'aient reçu' , passeSimple: 'reçurent' , subjonctifImparfait: 'reçussent' , subjonctifPlusQueParfait: 'eussent reçu' , passeAnterieur: 'eurent reçu' },
            ],
        },
    ];

export const helpersB1: Record<string, HelperVerbFR> = {

};
