import type { HelperVerbFR, VerbEntry, VerbGroup } from '../../../types/verbs';

export const verbGroupB2: VerbGroup = { id: 'b2', title: 'B2 — Upper Intermediate', titleFR: 'B2 — Intermédiaire supérieur', description: 'Advanced irregular verbs for near-fluent speakers', descriptionFR: 'Verbes irréguliers avancés pour un niveau quasi courant', icon: '📙', color: '#D97706' };

export const verbsB2: VerbEntry[] = [
        {
        level: 'B2', unit: 5,
            id: 'conduire', infinitive: 'conduire', translation: 'to drive', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'conduis' , passeCompose: 'ai conduit' , imparfait: 'conduisais' , futurSimple: 'conduirai' , conditionnelPresent: 'conduirais' , subjonctifPresent: 'conduise' , plusQueParfait: 'avais conduit' , futurAnterieur: 'aurai conduit' , conditionnelPasse: 'aurais conduit' , subjonctifPasse: 'aie conduit' , passeSimple: 'conduisis' , subjonctifImparfait: 'conduisisse' , subjonctifPlusQueParfait: 'eusse conduit' , passeAnterieur: 'eus conduit' },
            { sujet: 'tu' , present: 'conduis' , passeCompose: 'as conduit' , imparfait: 'conduisais' , futurSimple: 'conduiras' , conditionnelPresent: 'conduirais' , subjonctifPresent: 'conduises' , plusQueParfait: 'avais conduit' , futurAnterieur: 'auras conduit' , conditionnelPasse: 'aurais conduit' , subjonctifPasse: 'aies conduit' , passeSimple: 'conduisis' , subjonctifImparfait: 'conduisisses' , subjonctifPlusQueParfait: 'eusses conduit' , passeAnterieur: 'eus conduit' },
            { sujet: 'il/elle' , present: 'conduit' , passeCompose: 'a conduit' , imparfait: 'conduisait' , futurSimple: 'conduira' , conditionnelPresent: 'conduirait' , subjonctifPresent: 'conduise' , plusQueParfait: 'avait conduit' , futurAnterieur: 'aura conduit' , conditionnelPasse: 'aurait conduit' , subjonctifPasse: 'ait conduit' , passeSimple: 'conduisit' , subjonctifImparfait: 'conduisît' , subjonctifPlusQueParfait: 'eût conduit' , passeAnterieur: 'eut conduit' },
            { sujet: 'nous' , present: 'conduisons' , passeCompose: 'avons conduit' , imparfait: 'conduisions' , futurSimple: 'conduirons' , conditionnelPresent: 'conduirions' , subjonctifPresent: 'conduisions' , plusQueParfait: 'avions conduit' , futurAnterieur: 'aurons conduit' , conditionnelPasse: 'aurions conduit' , subjonctifPasse: 'ayons conduit' , passeSimple: 'conduisîmes' , subjonctifImparfait: 'conduisissions' , subjonctifPlusQueParfait: 'eussions conduit' , passeAnterieur: 'eûmes conduit' },
            { sujet: 'vous' , present: 'conduisez' , passeCompose: 'avez conduit' , imparfait: 'conduisiez' , futurSimple: 'conduirez' , conditionnelPresent: 'conduiriez' , subjonctifPresent: 'conduisiez' , plusQueParfait: 'aviez conduit' , futurAnterieur: 'aurez conduit' , conditionnelPasse: 'auriez conduit' , subjonctifPasse: 'ayez conduit' , passeSimple: 'conduisîtes' , subjonctifImparfait: 'conduisissiez' , subjonctifPlusQueParfait: 'eussiez conduit' , passeAnterieur: 'eûtes conduit' },
            { sujet: 'ils/elles' , present: 'conduisent' , passeCompose: 'ont conduit' , imparfait: 'conduisaient' , futurSimple: 'conduiront' , conditionnelPresent: 'conduiraient' , subjonctifPresent: 'conduisent' , plusQueParfait: 'avaient conduit' , futurAnterieur: 'auront conduit' , conditionnelPasse: 'auraient conduit' , subjonctifPasse: 'aient conduit' , passeSimple: 'conduisirent' , subjonctifImparfait: 'conduisissent' , subjonctifPlusQueParfait: 'eussent conduit' , passeAnterieur: 'eurent conduit' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'craindre', infinitive: 'craindre', translation: 'to fear', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'crains' , passeCompose: 'ai craint' , imparfait: 'craignais' , futurSimple: 'craindrai' , conditionnelPresent: 'craindrais' , subjonctifPresent: 'craigne' , plusQueParfait: 'avais craint' , futurAnterieur: 'aurai craint' , conditionnelPasse: 'aurais craint' , subjonctifPasse: 'aie craint' , passeSimple: 'craignis' , subjonctifImparfait: 'craignisse' , subjonctifPlusQueParfait: 'eusse craint' , passeAnterieur: 'eus craint' },
            { sujet: 'tu' , present: 'crains' , passeCompose: 'as craint' , imparfait: 'craignais' , futurSimple: 'craindras' , conditionnelPresent: 'craindrais' , subjonctifPresent: 'craignes' , plusQueParfait: 'avais craint' , futurAnterieur: 'auras craint' , conditionnelPasse: 'aurais craint' , subjonctifPasse: 'aies craint' , passeSimple: 'craignis' , subjonctifImparfait: 'craignisses' , subjonctifPlusQueParfait: 'eusses craint' , passeAnterieur: 'eus craint' },
            { sujet: 'il/elle' , present: 'craint' , passeCompose: 'a craint' , imparfait: 'craignait' , futurSimple: 'craindra' , conditionnelPresent: 'craindrait' , subjonctifPresent: 'craigne' , plusQueParfait: 'avait craint' , futurAnterieur: 'aura craint' , conditionnelPasse: 'aurait craint' , subjonctifPasse: 'ait craint' , passeSimple: 'craignit' , subjonctifImparfait: 'craignît' , subjonctifPlusQueParfait: 'eût craint' , passeAnterieur: 'eut craint' },
            { sujet: 'nous' , present: 'craignons' , passeCompose: 'avons craint' , imparfait: 'craignions' , futurSimple: 'craindrons' , conditionnelPresent: 'craindrions' , subjonctifPresent: 'craignions' , plusQueParfait: 'avions craint' , futurAnterieur: 'aurons craint' , conditionnelPasse: 'aurions craint' , subjonctifPasse: 'ayons craint' , passeSimple: 'craignîmes' , subjonctifImparfait: 'craignissions' , subjonctifPlusQueParfait: 'eussions craint' , passeAnterieur: 'eûmes craint' },
            { sujet: 'vous' , present: 'craignez' , passeCompose: 'avez craint' , imparfait: 'craigniez' , futurSimple: 'craindrez' , conditionnelPresent: 'craindriez' , subjonctifPresent: 'craigniez' , plusQueParfait: 'aviez craint' , futurAnterieur: 'aurez craint' , conditionnelPasse: 'auriez craint' , subjonctifPasse: 'ayez craint' , passeSimple: 'craignîtes' , subjonctifImparfait: 'craignissiez' , subjonctifPlusQueParfait: 'eussiez craint' , passeAnterieur: 'eûtes craint' },
            { sujet: 'ils/elles' , present: 'craignent' , passeCompose: 'ont craint' , imparfait: 'craignaient' , futurSimple: 'craindront' , conditionnelPresent: 'craindraient' , subjonctifPresent: 'craignent' , plusQueParfait: 'avaient craint' , futurAnterieur: 'auront craint' , conditionnelPasse: 'auraient craint' , subjonctifPasse: 'aient craint' , passeSimple: 'craignirent' , subjonctifImparfait: 'craignissent' , subjonctifPlusQueParfait: 'eussent craint' , passeAnterieur: 'eurent craint' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'naitre', infinitive: 'naître', translation: 'to be born', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'nais' , passeCompose: 'suis né(e)' , imparfait: 'naissais' , futurSimple: 'naîtrai' , conditionnelPresent: 'naîtrais' , subjonctifPresent: 'naisse' , plusQueParfait: 'étais né(e)' , futurAnterieur: 'serai né(e)' , conditionnelPasse: 'serais né(e)' , subjonctifPasse: 'sois né(e)' , passeSimple: 'naquis' , subjonctifImparfait: 'naquisse' , subjonctifPlusQueParfait: 'fusse né(e)' , passeAnterieur: 'fus né(e)' },
            { sujet: 'tu' , present: 'nais' , passeCompose: 'es né(e)' , imparfait: 'naissais' , futurSimple: 'naîtras' , conditionnelPresent: 'naîtrais' , subjonctifPresent: 'naisses' , plusQueParfait: 'étais né(e)' , futurAnterieur: 'seras né(e)' , conditionnelPasse: 'serais né(e)' , subjonctifPasse: 'sois né(e)' , passeSimple: 'naquis' , subjonctifImparfait: 'naquisses' , subjonctifPlusQueParfait: 'fusses né(e)' , passeAnterieur: 'fus né(e)' },
            { sujet: 'il/elle' , present: 'naît' , passeCompose: 'est né(e)' , imparfait: 'naissait' , futurSimple: 'naîtra' , conditionnelPresent: 'naîtrait' , subjonctifPresent: 'naisse' , plusQueParfait: 'était né(e)' , futurAnterieur: 'sera né(e)' , conditionnelPasse: 'serait né(e)' , subjonctifPasse: 'soit né(e)' , passeSimple: 'naquit' , subjonctifImparfait: 'naquît' , subjonctifPlusQueParfait: 'fût né(e)' , passeAnterieur: 'fut né(e)' },
            { sujet: 'nous' , present: 'naissons' , passeCompose: 'sommes né(e)s' , imparfait: 'naissions' , futurSimple: 'naîtrons' , conditionnelPresent: 'naîtrions' , subjonctifPresent: 'naissions' , plusQueParfait: 'étions né(e)s' , futurAnterieur: 'serons né(e)s' , conditionnelPasse: 'serions né(e)s' , subjonctifPasse: 'soyons né(e)s' , passeSimple: 'naquîmes' , subjonctifImparfait: 'naquissions' , subjonctifPlusQueParfait: 'fussions né(e)s' , passeAnterieur: 'fûmes né(e)s' },
            { sujet: 'vous' , present: 'naissez' , passeCompose: 'êtes né(e)s' , imparfait: 'naissiez' , futurSimple: 'naîtrez' , conditionnelPresent: 'naîtriez' , subjonctifPresent: 'naissiez' , plusQueParfait: 'étiez né(e)s' , futurAnterieur: 'serez né(e)s' , conditionnelPasse: 'seriez né(e)s' , subjonctifPasse: 'soyez né(e)s' , passeSimple: 'naquîtes' , subjonctifImparfait: 'naquissiez' , subjonctifPlusQueParfait: 'fussiez né(e)s' , passeAnterieur: 'fûtes né(e)s' },
            { sujet: 'ils/elles' , present: 'naissent' , passeCompose: 'sont né(e)s' , imparfait: 'naissaient' , futurSimple: 'naîtront' , conditionnelPresent: 'naîtraient' , subjonctifPresent: 'naissent' , plusQueParfait: 'étaient né(e)s' , futurAnterieur: 'seront né(e)s' , conditionnelPasse: 'seraient né(e)s' , subjonctifPasse: 'soient né(e)s' , passeSimple: 'naquirent' , subjonctifImparfait: 'naquissent' , subjonctifPlusQueParfait: 'fussent né(e)s' , passeAnterieur: 'furent né(e)s' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'plaire', infinitive: 'plaire', translation: 'to please', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'plais' , passeCompose: 'ai plu' , imparfait: 'plaisais' , futurSimple: 'plairai' , conditionnelPresent: 'plairais' , subjonctifPresent: 'plaise' , plusQueParfait: 'avais plu' , futurAnterieur: 'aurai plu' , conditionnelPasse: 'aurais plu' , subjonctifPasse: 'aie plu' , passeSimple: 'plus' , subjonctifImparfait: 'plusse' , subjonctifPlusQueParfait: 'eusse plu' , passeAnterieur: 'eus plu' },
            { sujet: 'tu' , present: 'plais' , passeCompose: 'as plu' , imparfait: 'plaisais' , futurSimple: 'plairas' , conditionnelPresent: 'plairais' , subjonctifPresent: 'plaises' , plusQueParfait: 'avais plu' , futurAnterieur: 'auras plu' , conditionnelPasse: 'aurais plu' , subjonctifPasse: 'aies plu' , passeSimple: 'plus' , subjonctifImparfait: 'plusses' , subjonctifPlusQueParfait: 'eusses plu' , passeAnterieur: 'eus plu' },
            { sujet: 'il/elle' , present: 'plaît' , passeCompose: 'a plu' , imparfait: 'plaisait' , futurSimple: 'plaira' , conditionnelPresent: 'plairait' , subjonctifPresent: 'plaise' , plusQueParfait: 'avait plu' , futurAnterieur: 'aura plu' , conditionnelPasse: 'aurait plu' , subjonctifPasse: 'ait plu' , passeSimple: 'plut' , subjonctifImparfait: 'plût' , subjonctifPlusQueParfait: 'eût plu' , passeAnterieur: 'eut plu' },
            { sujet: 'nous' , present: 'plaisons' , passeCompose: 'avons plu' , imparfait: 'plaisions' , futurSimple: 'plairons' , conditionnelPresent: 'plairions' , subjonctifPresent: 'plaisions' , plusQueParfait: 'avions plu' , futurAnterieur: 'aurons plu' , conditionnelPasse: 'aurions plu' , subjonctifPasse: 'ayons plu' , passeSimple: 'plûmes' , subjonctifImparfait: 'plussions' , subjonctifPlusQueParfait: 'eussions plu' , passeAnterieur: 'eûmes plu' },
            { sujet: 'vous' , present: 'plaisez' , passeCompose: 'avez plu' , imparfait: 'plaisiez' , futurSimple: 'plairez' , conditionnelPresent: 'plairiez' , subjonctifPresent: 'plaisiez' , plusQueParfait: 'aviez plu' , futurAnterieur: 'aurez plu' , conditionnelPasse: 'auriez plu' , subjonctifPasse: 'ayez plu' , passeSimple: 'plûtes' , subjonctifImparfait: 'plussiez' , subjonctifPlusQueParfait: 'eussiez plu' , passeAnterieur: 'eûtes plu' },
            { sujet: 'ils/elles' , present: 'plaisent' , passeCompose: 'ont plu' , imparfait: 'plaisaient' , futurSimple: 'plairont' , conditionnelPresent: 'plairaient' , subjonctifPresent: 'plaisent' , plusQueParfait: 'avaient plu' , futurAnterieur: 'auront plu' , conditionnelPasse: 'auraient plu' , subjonctifPasse: 'aient plu' , passeSimple: 'plurent' , subjonctifImparfait: 'plussent' , subjonctifPlusQueParfait: 'eussent plu' , passeAnterieur: 'eurent plu' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'rire', infinitive: 'rire', translation: 'to laugh', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'ris' , passeCompose: 'ai ri' , imparfait: 'riais' , futurSimple: 'rirai' , conditionnelPresent: 'rirais' , subjonctifPresent: 'rie' , plusQueParfait: 'avais ri' , futurAnterieur: 'aurai ri' , conditionnelPasse: 'aurais ri' , subjonctifPasse: 'aie ri' , passeSimple: 'ris' , subjonctifImparfait: 'risse' , subjonctifPlusQueParfait: 'eusse ri' , passeAnterieur: 'eus ri' },
            { sujet: 'tu' , present: 'ris' , passeCompose: 'as ri' , imparfait: 'riais' , futurSimple: 'riras' , conditionnelPresent: 'rirais' , subjonctifPresent: 'ries' , plusQueParfait: 'avais ri' , futurAnterieur: 'auras ri' , conditionnelPasse: 'aurais ri' , subjonctifPasse: 'aies ri' , passeSimple: 'ris' , subjonctifImparfait: 'risses' , subjonctifPlusQueParfait: 'eusses ri' , passeAnterieur: 'eus ri' },
            { sujet: 'il/elle' , present: 'rit' , passeCompose: 'a ri' , imparfait: 'riait' , futurSimple: 'rira' , conditionnelPresent: 'rirait' , subjonctifPresent: 'rie' , plusQueParfait: 'avait ri' , futurAnterieur: 'aura ri' , conditionnelPasse: 'aurait ri' , subjonctifPasse: 'ait ri' , passeSimple: 'rit' , subjonctifImparfait: 'rît' , subjonctifPlusQueParfait: 'eût ri' , passeAnterieur: 'eut ri' },
            { sujet: 'nous' , present: 'rions' , passeCompose: 'avons ri' , imparfait: 'riions' , futurSimple: 'rirons' , conditionnelPresent: 'ririons' , subjonctifPresent: 'riions' , plusQueParfait: 'avions ri' , futurAnterieur: 'aurons ri' , conditionnelPasse: 'aurions ri' , subjonctifPasse: 'ayons ri' , passeSimple: 'rîmes' , subjonctifImparfait: 'rissions' , subjonctifPlusQueParfait: 'eussions ri' , passeAnterieur: 'eûmes ri' },
            { sujet: 'vous' , present: 'riez' , passeCompose: 'avez ri' , imparfait: 'riiez' , futurSimple: 'rirez' , conditionnelPresent: 'ririez' , subjonctifPresent: 'riiez' , plusQueParfait: 'aviez ri' , futurAnterieur: 'aurez ri' , conditionnelPasse: 'auriez ri' , subjonctifPasse: 'ayez ri' , passeSimple: 'rîtes' , subjonctifImparfait: 'rissiez' , subjonctifPlusQueParfait: 'eussiez ri' , passeAnterieur: 'eûtes ri' },
            { sujet: 'ils/elles' , present: 'rient' , passeCompose: 'ont ri' , imparfait: 'riaient' , futurSimple: 'riront' , conditionnelPresent: 'riraient' , subjonctifPresent: 'rient' , plusQueParfait: 'avaient ri' , futurAnterieur: 'auront ri' , conditionnelPasse: 'auraient ri' , subjonctifPasse: 'aient ri' , passeSimple: 'rirent' , subjonctifImparfait: 'rissent' , subjonctifPlusQueParfait: 'eussent ri' , passeAnterieur: 'eurent ri' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'suivre', infinitive: 'suivre', translation: 'to follow', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'suis' , passeCompose: 'ai suivi' , imparfait: 'suivais' , futurSimple: 'suivrai' , conditionnelPresent: 'suivrais' , subjonctifPresent: 'suive' , plusQueParfait: 'avais suivi' , futurAnterieur: 'aurai suivi' , conditionnelPasse: 'aurais suivi' , subjonctifPasse: 'aie suivi' , passeSimple: 'suivis' , subjonctifImparfait: 'suivisse' , subjonctifPlusQueParfait: 'eusse suivi' , passeAnterieur: 'eus suivi' },
            { sujet: 'tu' , present: 'suis' , passeCompose: 'as suivi' , imparfait: 'suivais' , futurSimple: 'suivras' , conditionnelPresent: 'suivrais' , subjonctifPresent: 'suives' , plusQueParfait: 'avais suivi' , futurAnterieur: 'auras suivi' , conditionnelPasse: 'aurais suivi' , subjonctifPasse: 'aies suivi' , passeSimple: 'suivis' , subjonctifImparfait: 'suivisses' , subjonctifPlusQueParfait: 'eusses suivi' , passeAnterieur: 'eus suivi' },
            { sujet: 'il/elle' , present: 'suit' , passeCompose: 'a suivi' , imparfait: 'suivait' , futurSimple: 'suivra' , conditionnelPresent: 'suivrait' , subjonctifPresent: 'suive' , plusQueParfait: 'avait suivi' , futurAnterieur: 'aura suivi' , conditionnelPasse: 'aurait suivi' , subjonctifPasse: 'ait suivi' , passeSimple: 'suivit' , subjonctifImparfait: 'suivît' , subjonctifPlusQueParfait: 'eût suivi' , passeAnterieur: 'eut suivi' },
            { sujet: 'nous' , present: 'suivons' , passeCompose: 'avons suivi' , imparfait: 'suivions' , futurSimple: 'suivrons' , conditionnelPresent: 'suivrions' , subjonctifPresent: 'suivions' , plusQueParfait: 'avions suivi' , futurAnterieur: 'aurons suivi' , conditionnelPasse: 'aurions suivi' , subjonctifPasse: 'ayons suivi' , passeSimple: 'suivîmes' , subjonctifImparfait: 'suivissions' , subjonctifPlusQueParfait: 'eussions suivi' , passeAnterieur: 'eûmes suivi' },
            { sujet: 'vous' , present: 'suivez' , passeCompose: 'avez suivi' , imparfait: 'suiviez' , futurSimple: 'suivrez' , conditionnelPresent: 'suivriez' , subjonctifPresent: 'suiviez' , plusQueParfait: 'aviez suivi' , futurAnterieur: 'aurez suivi' , conditionnelPasse: 'auriez suivi' , subjonctifPasse: 'ayez suivi' , passeSimple: 'suivîtes' , subjonctifImparfait: 'suivissiez' , subjonctifPlusQueParfait: 'eussiez suivi' , passeAnterieur: 'eûtes suivi' },
            { sujet: 'ils/elles' , present: 'suivent' , passeCompose: 'ont suivi' , imparfait: 'suivaient' , futurSimple: 'suivront' , conditionnelPresent: 'suivraient' , subjonctifPresent: 'suivent' , plusQueParfait: 'avaient suivi' , futurAnterieur: 'auront suivi' , conditionnelPasse: 'auraient suivi' , subjonctifPasse: 'aient suivi' , passeSimple: 'suivirent' , subjonctifImparfait: 'suivissent' , subjonctifPlusQueParfait: 'eussent suivi' , passeAnterieur: 'eurent suivi' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'mourir', infinitive: 'mourir', translation: 'to die', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'meurs' , passeCompose: 'suis mort(e)' , imparfait: 'mourais' , futurSimple: 'mourrai' , conditionnelPresent: 'mourrais' , subjonctifPresent: 'meure' , plusQueParfait: 'étais mort(e)' , futurAnterieur: 'serai mort(e)' , conditionnelPasse: 'serais mort(e)' , subjonctifPasse: 'sois mort(e)' , passeSimple: 'mourus' , subjonctifImparfait: 'mourusse' , subjonctifPlusQueParfait: 'fusse mort(e)' , passeAnterieur: 'fus mort(e)' },
            { sujet: 'tu' , present: 'meurs' , passeCompose: 'es mort(e)' , imparfait: 'mourais' , futurSimple: 'mourras' , conditionnelPresent: 'mourrais' , subjonctifPresent: 'meures' , plusQueParfait: 'étais mort(e)' , futurAnterieur: 'seras mort(e)' , conditionnelPasse: 'serais mort(e)' , subjonctifPasse: 'sois mort(e)' , passeSimple: 'mourus' , subjonctifImparfait: 'mourusses' , subjonctifPlusQueParfait: 'fusses mort(e)' , passeAnterieur: 'fus mort(e)' },
            { sujet: 'il/elle' , present: 'meurt' , passeCompose: 'est mort(e)' , imparfait: 'mourait' , futurSimple: 'mourra' , conditionnelPresent: 'mourrait' , subjonctifPresent: 'meure' , plusQueParfait: 'était mort(e)' , futurAnterieur: 'sera mort(e)' , conditionnelPasse: 'serait mort(e)' , subjonctifPasse: 'soit mort(e)' , passeSimple: 'mourut' , subjonctifImparfait: 'mourût' , subjonctifPlusQueParfait: 'fût mort(e)' , passeAnterieur: 'fut mort(e)' },
            { sujet: 'nous' , present: 'mourons' , passeCompose: 'sommes mort(e)s' , imparfait: 'mourions' , futurSimple: 'mourrons' , conditionnelPresent: 'mourrions' , subjonctifPresent: 'mourions' , plusQueParfait: 'étions mort(e)s' , futurAnterieur: 'serons mort(e)s' , conditionnelPasse: 'serions mort(e)s' , subjonctifPasse: 'soyons mort(e)s' , passeSimple: 'mourûmes' , subjonctifImparfait: 'mourussions' , subjonctifPlusQueParfait: 'fussions mort(e)s' , passeAnterieur: 'fûmes mort(e)s' },
            { sujet: 'vous' , present: 'mourez' , passeCompose: 'êtes mort(e)s' , imparfait: 'mouriez' , futurSimple: 'mourrez' , conditionnelPresent: 'mourriez' , subjonctifPresent: 'mouriez' , plusQueParfait: 'étiez mort(e)s' , futurAnterieur: 'serez mort(e)s' , conditionnelPasse: 'seriez mort(e)s' , subjonctifPasse: 'soyez mort(e)s' , passeSimple: 'mourûtes' , subjonctifImparfait: 'mourussiez' , subjonctifPlusQueParfait: 'fussiez mort(e)s' , passeAnterieur: 'fûtes mort(e)s' },
            { sujet: 'ils/elles' , present: 'meurent' , passeCompose: 'sont mort(e)s' , imparfait: 'mouraient' , futurSimple: 'mourront' , conditionnelPresent: 'mourraient' , subjonctifPresent: 'meurent' , plusQueParfait: 'étaient mort(e)s' , futurAnterieur: 'seront mort(e)s' , conditionnelPasse: 'seraient mort(e)s' , subjonctifPasse: 'soient mort(e)s' , passeSimple: 'moururent' , subjonctifImparfait: 'mourussent' , subjonctifPlusQueParfait: 'fussent mort(e)s' , passeAnterieur: 'furent mort(e)s' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'resoudre', infinitive: 'résoudre', translation: 'to resolve / solve', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'résous' , passeCompose: 'ai résolu' , imparfait: 'résolvais' , futurSimple: 'résoudrai' , conditionnelPresent: 'résoudrais' , subjonctifPresent: 'résolve' , plusQueParfait: 'avais résolu' , futurAnterieur: 'aurai résolu' , conditionnelPasse: 'aurais résolu' , subjonctifPasse: 'aie résolu' , passeSimple: 'résolus' , subjonctifImparfait: 'résolusse' , subjonctifPlusQueParfait: 'eusse résolu' , passeAnterieur: 'eus résolu' },
            { sujet: 'tu' , present: 'résous' , passeCompose: 'as résolu' , imparfait: 'résolvais' , futurSimple: 'résoudras' , conditionnelPresent: 'résoudrais' , subjonctifPresent: 'résolves' , plusQueParfait: 'avais résolu' , futurAnterieur: 'auras résolu' , conditionnelPasse: 'aurais résolu' , subjonctifPasse: 'aies résolu' , passeSimple: 'résolus' , subjonctifImparfait: 'résolusses' , subjonctifPlusQueParfait: 'eusses résolu' , passeAnterieur: 'eus résolu' },
            { sujet: 'il/elle' , present: 'résout' , passeCompose: 'a résolu' , imparfait: 'résolvait' , futurSimple: 'résoudra' , conditionnelPresent: 'résoudrait' , subjonctifPresent: 'résolve' , plusQueParfait: 'avait résolu' , futurAnterieur: 'aura résolu' , conditionnelPasse: 'aurait résolu' , subjonctifPasse: 'ait résolu' , passeSimple: 'résolut' , subjonctifImparfait: 'résolût' , subjonctifPlusQueParfait: 'eût résolu' , passeAnterieur: 'eut résolu' },
            { sujet: 'nous' , present: 'résolvons' , passeCompose: 'avons résolu' , imparfait: 'résolvions' , futurSimple: 'résoudrons' , conditionnelPresent: 'résoudrions' , subjonctifPresent: 'résolvions' , plusQueParfait: 'avions résolu' , futurAnterieur: 'aurons résolu' , conditionnelPasse: 'aurions résolu' , subjonctifPasse: 'ayons résolu' , passeSimple: 'résolûmes' , subjonctifImparfait: 'résolussions' , subjonctifPlusQueParfait: 'eussions résolu' , passeAnterieur: 'eûmes résolu' },
            { sujet: 'vous' , present: 'résolvez' , passeCompose: 'avez résolu' , imparfait: 'résolviez' , futurSimple: 'résoudrez' , conditionnelPresent: 'résoudriez' , subjonctifPresent: 'résolviez' , plusQueParfait: 'aviez résolu' , futurAnterieur: 'aurez résolu' , conditionnelPasse: 'auriez résolu' , subjonctifPasse: 'ayez résolu' , passeSimple: 'résolûtes' , subjonctifImparfait: 'résolussiez' , subjonctifPlusQueParfait: 'eussiez résolu' , passeAnterieur: 'eûtes résolu' },
            { sujet: 'ils/elles' , present: 'résolvent' , passeCompose: 'ont résolu' , imparfait: 'résolvaient' , futurSimple: 'résoudront' , conditionnelPresent: 'résoudraient' , subjonctifPresent: 'résolvent' , plusQueParfait: 'avaient résolu' , futurAnterieur: 'auront résolu' , conditionnelPasse: 'auraient résolu' , subjonctifPasse: 'aient résolu' , passeSimple: 'résolurent' , subjonctifImparfait: 'résolussent' , subjonctifPlusQueParfait: 'eussent résolu' , passeAnterieur: 'eurent résolu' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'coudre', infinitive: 'coudre', translation: 'to sew', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'couds' , passeCompose: 'ai cousu' , imparfait: 'cousais' , futurSimple: 'coudrai' , conditionnelPresent: 'coudrais' , subjonctifPresent: 'couse' , plusQueParfait: 'avais cousu' , futurAnterieur: 'aurai cousu' , conditionnelPasse: 'aurais cousu' , subjonctifPasse: 'aie cousu' , passeSimple: 'cousis' , subjonctifImparfait: 'cousisse' , subjonctifPlusQueParfait: 'eusse cousu' , passeAnterieur: 'eus cousu' },
            { sujet: 'tu' , present: 'couds' , passeCompose: 'as cousu' , imparfait: 'cousais' , futurSimple: 'coudras' , conditionnelPresent: 'coudrais' , subjonctifPresent: 'couses' , plusQueParfait: 'avais cousu' , futurAnterieur: 'auras cousu' , conditionnelPasse: 'aurais cousu' , subjonctifPasse: 'aies cousu' , passeSimple: 'cousis' , subjonctifImparfait: 'cousisses' , subjonctifPlusQueParfait: 'eusses cousu' , passeAnterieur: 'eus cousu' },
            { sujet: 'il/elle' , present: 'coud' , passeCompose: 'a cousu' , imparfait: 'cousait' , futurSimple: 'coudra' , conditionnelPresent: 'coudrait' , subjonctifPresent: 'couse' , plusQueParfait: 'avait cousu' , futurAnterieur: 'aura cousu' , conditionnelPasse: 'aurait cousu' , subjonctifPasse: 'ait cousu' , passeSimple: 'cousit' , subjonctifImparfait: 'cousît' , subjonctifPlusQueParfait: 'eût cousu' , passeAnterieur: 'eut cousu' },
            { sujet: 'nous' , present: 'cousons' , passeCompose: 'avons cousu' , imparfait: 'cousions' , futurSimple: 'coudrons' , conditionnelPresent: 'coudrions' , subjonctifPresent: 'cousions' , plusQueParfait: 'avions cousu' , futurAnterieur: 'aurons cousu' , conditionnelPasse: 'aurions cousu' , subjonctifPasse: 'ayons cousu' , passeSimple: 'cousîmes' , subjonctifImparfait: 'cousissions' , subjonctifPlusQueParfait: 'eussions cousu' , passeAnterieur: 'eûmes cousu' },
            { sujet: 'vous' , present: 'cousez' , passeCompose: 'avez cousu' , imparfait: 'cousiez' , futurSimple: 'coudrez' , conditionnelPresent: 'coudriez' , subjonctifPresent: 'cousiez' , plusQueParfait: 'aviez cousu' , futurAnterieur: 'aurez cousu' , conditionnelPasse: 'auriez cousu' , subjonctifPasse: 'ayez cousu' , passeSimple: 'cousîtes' , subjonctifImparfait: 'cousissiez' , subjonctifPlusQueParfait: 'eussiez cousu' , passeAnterieur: 'eûtes cousu' },
            { sujet: 'ils/elles' , present: 'cousent' , passeCompose: 'ont cousu' , imparfait: 'cousaient' , futurSimple: 'coudront' , conditionnelPresent: 'coudraient' , subjonctifPresent: 'cousent' , plusQueParfait: 'avaient cousu' , futurAnterieur: 'auront cousu' , conditionnelPasse: 'auraient cousu' , subjonctifPasse: 'aient cousu' , passeSimple: 'cousirent' , subjonctifImparfait: 'cousissent' , subjonctifPlusQueParfait: 'eussent cousu' , passeAnterieur: 'eurent cousu' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'moudre', infinitive: 'moudre', translation: 'to grind', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'mouds' , passeCompose: 'ai moulu' , imparfait: 'moulais' , futurSimple: 'moudrai' , conditionnelPresent: 'moudrais' , subjonctifPresent: 'moule' , plusQueParfait: 'avais moulu' , futurAnterieur: 'aurai moulu' , conditionnelPasse: 'aurais moulu' , subjonctifPasse: 'aie moulu' , passeSimple: 'moulus' , subjonctifImparfait: 'moulusse' , subjonctifPlusQueParfait: 'eusse moulu' , passeAnterieur: 'eus moulu' },
            { sujet: 'tu' , present: 'mouds' , passeCompose: 'as moulu' , imparfait: 'moulais' , futurSimple: 'moudras' , conditionnelPresent: 'moudrais' , subjonctifPresent: 'moules' , plusQueParfait: 'avais moulu' , futurAnterieur: 'auras moulu' , conditionnelPasse: 'aurais moulu' , subjonctifPasse: 'aies moulu' , passeSimple: 'moulus' , subjonctifImparfait: 'moulusses' , subjonctifPlusQueParfait: 'eusses moulu' , passeAnterieur: 'eus moulu' },
            { sujet: 'il/elle' , present: 'moud' , passeCompose: 'a moulu' , imparfait: 'moulait' , futurSimple: 'moudra' , conditionnelPresent: 'moudrait' , subjonctifPresent: 'moule' , plusQueParfait: 'avait moulu' , futurAnterieur: 'aura moulu' , conditionnelPasse: 'aurait moulu' , subjonctifPasse: 'ait moulu' , passeSimple: 'moulut' , subjonctifImparfait: 'moulût' , subjonctifPlusQueParfait: 'eût moulu' , passeAnterieur: 'eut moulu' },
            { sujet: 'nous' , present: 'moulons' , passeCompose: 'avons moulu' , imparfait: 'moulions' , futurSimple: 'moudrons' , conditionnelPresent: 'moudrions' , subjonctifPresent: 'moulions' , plusQueParfait: 'avions moulu' , futurAnterieur: 'aurons moulu' , conditionnelPasse: 'aurions moulu' , subjonctifPasse: 'ayons moulu' , passeSimple: 'moulûmes' , subjonctifImparfait: 'moulussions' , subjonctifPlusQueParfait: 'eussions moulu' , passeAnterieur: 'eûmes moulu' },
            { sujet: 'vous' , present: 'moulez' , passeCompose: 'avez moulu' , imparfait: 'mouliez' , futurSimple: 'moudrez' , conditionnelPresent: 'moudriez' , subjonctifPresent: 'mouliez' , plusQueParfait: 'aviez moulu' , futurAnterieur: 'aurez moulu' , conditionnelPasse: 'auriez moulu' , subjonctifPasse: 'ayez moulu' , passeSimple: 'moulûtes' , subjonctifImparfait: 'moulussiez' , subjonctifPlusQueParfait: 'eussiez moulu' , passeAnterieur: 'eûtes moulu' },
            { sujet: 'ils/elles' , present: 'moulent' , passeCompose: 'ont moulu' , imparfait: 'moulaient' , futurSimple: 'moudront' , conditionnelPresent: 'moudraient' , subjonctifPresent: 'moulent' , plusQueParfait: 'avaient moulu' , futurAnterieur: 'auront moulu' , conditionnelPasse: 'auraient moulu' , subjonctifPasse: 'aient moulu' , passeSimple: 'moulurent' , subjonctifImparfait: 'moulussent' , subjonctifPlusQueParfait: 'eussent moulu' , passeAnterieur: 'eurent moulu' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'envoyer', infinitive: 'envoyer', translation: 'to send', type: '-ER', color: '#059669',
            rows: [
            { sujet: 'je' , present: 'envoie' , passeCompose: 'ai envoyé' , imparfait: 'envoyais' , futurSimple: 'enverrai' , conditionnelPresent: 'enverrais' , subjonctifPresent: 'envoie' , plusQueParfait: 'avais envoyé' , futurAnterieur: 'aurai envoyé' , conditionnelPasse: 'aurais envoyé' , subjonctifPasse: 'aie envoyé' , passeSimple: 'envoyai' , subjonctifImparfait: 'envoyasse' , subjonctifPlusQueParfait: 'eusse envoyé' , passeAnterieur: 'eus envoyé' },
            { sujet: 'tu' , present: 'envoies' , passeCompose: 'as envoyé' , imparfait: 'envoyais' , futurSimple: 'enverras' , conditionnelPresent: 'enverrais' , subjonctifPresent: 'envoies' , plusQueParfait: 'avais envoyé' , futurAnterieur: 'auras envoyé' , conditionnelPasse: 'aurais envoyé' , subjonctifPasse: 'aies envoyé' , passeSimple: 'envoyas' , subjonctifImparfait: 'envoyasses' , subjonctifPlusQueParfait: 'eusses envoyé' , passeAnterieur: 'eus envoyé' },
            { sujet: 'il/elle' , present: 'envoie' , passeCompose: 'a envoyé' , imparfait: 'envoyait' , futurSimple: 'enverra' , conditionnelPresent: 'enverrait' , subjonctifPresent: 'envoie' , plusQueParfait: 'avait envoyé' , futurAnterieur: 'aura envoyé' , conditionnelPasse: 'aurait envoyé' , subjonctifPasse: 'ait envoyé' , passeSimple: 'envoya' , subjonctifImparfait: 'envoyât' , subjonctifPlusQueParfait: 'eût envoyé' , passeAnterieur: 'eut envoyé' },
            { sujet: 'nous' , present: 'envoyons' , passeCompose: 'avons envoyé' , imparfait: 'envoyions' , futurSimple: 'enverrons' , conditionnelPresent: 'enverrions' , subjonctifPresent: 'envoyions' , plusQueParfait: 'avions envoyé' , futurAnterieur: 'aurons envoyé' , conditionnelPasse: 'aurions envoyé' , subjonctifPasse: 'ayons envoyé' , passeSimple: 'envoyâmes' , subjonctifImparfait: 'envoyassions' , subjonctifPlusQueParfait: 'eussions envoyé' , passeAnterieur: 'eûmes envoyé' },
            { sujet: 'vous' , present: 'envoyez' , passeCompose: 'avez envoyé' , imparfait: 'envoyiez' , futurSimple: 'enverrez' , conditionnelPresent: 'enverriez' , subjonctifPresent: 'envoyiez' , plusQueParfait: 'aviez envoyé' , futurAnterieur: 'aurez envoyé' , conditionnelPasse: 'auriez envoyé' , subjonctifPasse: 'ayez envoyé' , passeSimple: 'envoyâtes' , subjonctifImparfait: 'envoyassiez' , subjonctifPlusQueParfait: 'eussiez envoyé' , passeAnterieur: 'eûtes envoyé' },
            { sujet: 'ils/elles' , present: 'envoient' , passeCompose: 'ont envoyé' , imparfait: 'envoyaient' , futurSimple: 'enverront' , conditionnelPresent: 'enverraient' , subjonctifPresent: 'envoient' , plusQueParfait: 'avaient envoyé' , futurAnterieur: 'auront envoyé' , conditionnelPasse: 'auraient envoyé' , subjonctifPasse: 'aient envoyé' , passeSimple: 'envoyèrent' , subjonctifImparfait: 'envoyassent' , subjonctifPlusQueParfait: 'eussent envoyé' , passeAnterieur: 'eurent envoyé' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'mordre', infinitive: 'mordre', translation: 'to bite', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'mords' , passeCompose: 'ai mordu' , imparfait: 'mordais' , futurSimple: 'mordrai' , conditionnelPresent: 'mordrais' , subjonctifPresent: 'morde' , plusQueParfait: 'avais mordu' , futurAnterieur: 'aurai mordu' , conditionnelPasse: 'aurais mordu' , subjonctifPasse: 'aie mordu' , passeSimple: 'mordis' , subjonctifImparfait: 'mordisse' , subjonctifPlusQueParfait: 'eusse mordu' , passeAnterieur: 'eus mordu' },
            { sujet: 'tu' , present: 'mords' , passeCompose: 'as mordu' , imparfait: 'mordais' , futurSimple: 'mordras' , conditionnelPresent: 'mordrais' , subjonctifPresent: 'mordes' , plusQueParfait: 'avais mordu' , futurAnterieur: 'auras mordu' , conditionnelPasse: 'aurais mordu' , subjonctifPasse: 'aies mordu' , passeSimple: 'mordis' , subjonctifImparfait: 'mordisses' , subjonctifPlusQueParfait: 'eusses mordu' , passeAnterieur: 'eus mordu' },
            { sujet: 'il/elle' , present: 'mord' , passeCompose: 'a mordu' , imparfait: 'mordait' , futurSimple: 'mordra' , conditionnelPresent: 'mordrait' , subjonctifPresent: 'morde' , plusQueParfait: 'avait mordu' , futurAnterieur: 'aura mordu' , conditionnelPasse: 'aurait mordu' , subjonctifPasse: 'ait mordu' , passeSimple: 'mordit' , subjonctifImparfait: 'mordît' , subjonctifPlusQueParfait: 'eût mordu' , passeAnterieur: 'eut mordu' },
            { sujet: 'nous' , present: 'mordons' , passeCompose: 'avons mordu' , imparfait: 'mordions' , futurSimple: 'mordrons' , conditionnelPresent: 'mordrions' , subjonctifPresent: 'mordions' , plusQueParfait: 'avions mordu' , futurAnterieur: 'aurons mordu' , conditionnelPasse: 'aurions mordu' , subjonctifPasse: 'ayons mordu' , passeSimple: 'mordîmes' , subjonctifImparfait: 'mordissions' , subjonctifPlusQueParfait: 'eussions mordu' , passeAnterieur: 'eûmes mordu' },
            { sujet: 'vous' , present: 'mordez' , passeCompose: 'avez mordu' , imparfait: 'mordiez' , futurSimple: 'mordrez' , conditionnelPresent: 'mordriez' , subjonctifPresent: 'mordiez' , plusQueParfait: 'aviez mordu' , futurAnterieur: 'aurez mordu' , conditionnelPasse: 'auriez mordu' , subjonctifPasse: 'ayez mordu' , passeSimple: 'mordîtes' , subjonctifImparfait: 'mordissiez' , subjonctifPlusQueParfait: 'eussiez mordu' , passeAnterieur: 'eûtes mordu' },
            { sujet: 'ils/elles' , present: 'mordent' , passeCompose: 'ont mordu' , imparfait: 'mordaient' , futurSimple: 'mordront' , conditionnelPresent: 'mordraient' , subjonctifPresent: 'mordent' , plusQueParfait: 'avaient mordu' , futurAnterieur: 'auront mordu' , conditionnelPasse: 'auraient mordu' , subjonctifPasse: 'aient mordu' , passeSimple: 'mordirent' , subjonctifImparfait: 'mordissent' , subjonctifPlusQueParfait: 'eussent mordu' , passeAnterieur: 'eurent mordu' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'tordre', infinitive: 'tordre', translation: 'to twist', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'tords' , passeCompose: 'ai tordu' , imparfait: 'tordais' , futurSimple: 'tordrai' , conditionnelPresent: 'tordrais' , subjonctifPresent: 'torde' , plusQueParfait: 'avais tordu' , futurAnterieur: 'aurai tordu' , conditionnelPasse: 'aurais tordu' , subjonctifPasse: 'aie tordu' , passeSimple: 'tordis' , subjonctifImparfait: 'tordisse' , subjonctifPlusQueParfait: 'eusse tordu' , passeAnterieur: 'eus tordu' },
            { sujet: 'tu' , present: 'tords' , passeCompose: 'as tordu' , imparfait: 'tordais' , futurSimple: 'tordras' , conditionnelPresent: 'tordrais' , subjonctifPresent: 'tordes' , plusQueParfait: 'avais tordu' , futurAnterieur: 'auras tordu' , conditionnelPasse: 'aurais tordu' , subjonctifPasse: 'aies tordu' , passeSimple: 'tordis' , subjonctifImparfait: 'tordisses' , subjonctifPlusQueParfait: 'eusses tordu' , passeAnterieur: 'eus tordu' },
            { sujet: 'il/elle' , present: 'tord' , passeCompose: 'a tordu' , imparfait: 'tordait' , futurSimple: 'tordra' , conditionnelPresent: 'tordrait' , subjonctifPresent: 'torde' , plusQueParfait: 'avait tordu' , futurAnterieur: 'aura tordu' , conditionnelPasse: 'aurait tordu' , subjonctifPasse: 'ait tordu' , passeSimple: 'tordit' , subjonctifImparfait: 'tordît' , subjonctifPlusQueParfait: 'eût tordu' , passeAnterieur: 'eut tordu' },
            { sujet: 'nous' , present: 'tordons' , passeCompose: 'avons tordu' , imparfait: 'tordions' , futurSimple: 'tordrons' , conditionnelPresent: 'tordrions' , subjonctifPresent: 'tordions' , plusQueParfait: 'avions tordu' , futurAnterieur: 'aurons tordu' , conditionnelPasse: 'aurions tordu' , subjonctifPasse: 'ayons tordu' , passeSimple: 'tordîmes' , subjonctifImparfait: 'tordissions' , subjonctifPlusQueParfait: 'eussions tordu' , passeAnterieur: 'eûmes tordu' },
            { sujet: 'vous' , present: 'tordez' , passeCompose: 'avez tordu' , imparfait: 'tordiez' , futurSimple: 'tordrez' , conditionnelPresent: 'tordriez' , subjonctifPresent: 'tordiez' , plusQueParfait: 'aviez tordu' , futurAnterieur: 'aurez tordu' , conditionnelPasse: 'auriez tordu' , subjonctifPasse: 'ayez tordu' , passeSimple: 'tordîtes' , subjonctifImparfait: 'tordissiez' , subjonctifPlusQueParfait: 'eussiez tordu' , passeAnterieur: 'eûtes tordu' },
            { sujet: 'ils/elles' , present: 'tordent' , passeCompose: 'ont tordu' , imparfait: 'tordaient' , futurSimple: 'tordront' , conditionnelPresent: 'tordraient' , subjonctifPresent: 'tordent' , plusQueParfait: 'avaient tordu' , futurAnterieur: 'auront tordu' , conditionnelPasse: 'auraient tordu' , subjonctifPasse: 'aient tordu' , passeSimple: 'tordirent' , subjonctifImparfait: 'tordissent' , subjonctifPlusQueParfait: 'eussent tordu' , passeAnterieur: 'eurent tordu' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'fondre', infinitive: 'fondre', translation: 'to melt / dissolve', type: '-RE', color: '#D97706',
            rows: [
            { sujet: 'je' , present: 'fonds' , passeCompose: 'ai fondu' , imparfait: 'fondais' , futurSimple: 'fondrai' , conditionnelPresent: 'fondrais' , subjonctifPresent: 'fonde' , plusQueParfait: 'avais fondu' , futurAnterieur: 'aurai fondu' , conditionnelPasse: 'aurais fondu' , subjonctifPasse: 'aie fondu' , passeSimple: 'fondis' , subjonctifImparfait: 'fondisse' , subjonctifPlusQueParfait: 'eusse fondu' , passeAnterieur: 'eus fondu' },
            { sujet: 'tu' , present: 'fonds' , passeCompose: 'as fondu' , imparfait: 'fondais' , futurSimple: 'fondras' , conditionnelPresent: 'fondrais' , subjonctifPresent: 'fondes' , plusQueParfait: 'avais fondu' , futurAnterieur: 'auras fondu' , conditionnelPasse: 'aurais fondu' , subjonctifPasse: 'aies fondu' , passeSimple: 'fondis' , subjonctifImparfait: 'fondisses' , subjonctifPlusQueParfait: 'eusses fondu' , passeAnterieur: 'eus fondu' },
            { sujet: 'il/elle' , present: 'fond' , passeCompose: 'a fondu' , imparfait: 'fondait' , futurSimple: 'fondra' , conditionnelPresent: 'fondrait' , subjonctifPresent: 'fonde' , plusQueParfait: 'avait fondu' , futurAnterieur: 'aura fondu' , conditionnelPasse: 'aurait fondu' , subjonctifPasse: 'ait fondu' , passeSimple: 'fondit' , subjonctifImparfait: 'fondît' , subjonctifPlusQueParfait: 'eût fondu' , passeAnterieur: 'eut fondu' },
            { sujet: 'nous' , present: 'fondons' , passeCompose: 'avons fondu' , imparfait: 'fondions' , futurSimple: 'fondrons' , conditionnelPresent: 'fondrions' , subjonctifPresent: 'fondions' , plusQueParfait: 'avions fondu' , futurAnterieur: 'aurons fondu' , conditionnelPasse: 'aurions fondu' , subjonctifPasse: 'ayons fondu' , passeSimple: 'fondîmes' , subjonctifImparfait: 'fondissions' , subjonctifPlusQueParfait: 'eussions fondu' , passeAnterieur: 'eûmes fondu' },
            { sujet: 'vous' , present: 'fondez' , passeCompose: 'avez fondu' , imparfait: 'fondiez' , futurSimple: 'fondrez' , conditionnelPresent: 'fondriez' , subjonctifPresent: 'fondiez' , plusQueParfait: 'aviez fondu' , futurAnterieur: 'aurez fondu' , conditionnelPasse: 'auriez fondu' , subjonctifPasse: 'ayez fondu' , passeSimple: 'fondîtes' , subjonctifImparfait: 'fondissiez' , subjonctifPlusQueParfait: 'eussiez fondu' , passeAnterieur: 'eûtes fondu' },
            { sujet: 'ils/elles' , present: 'fondent' , passeCompose: 'ont fondu' , imparfait: 'fondaient' , futurSimple: 'fondront' , conditionnelPresent: 'fondraient' , subjonctifPresent: 'fondent' , plusQueParfait: 'avaient fondu' , futurAnterieur: 'auront fondu' , conditionnelPasse: 'auraient fondu' , subjonctifPasse: 'aient fondu' , passeSimple: 'fondirent' , subjonctifImparfait: 'fondissent' , subjonctifPlusQueParfait: 'eussent fondu' , passeAnterieur: 'eurent fondu' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'peindre', infinitive: 'peindre', translation: 'to paint', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'peins' , passeCompose: 'ai peint' , imparfait: 'peignais' , futurSimple: 'peindrai' , conditionnelPresent: 'peindrais' , subjonctifPresent: 'peigne' , plusQueParfait: 'avais peint' , futurAnterieur: 'aurai peint' , conditionnelPasse: 'aurais peint' , subjonctifPasse: 'aie peint' , passeSimple: 'peignis' , subjonctifImparfait: 'peignisse' , subjonctifPlusQueParfait: 'eusse peint' , passeAnterieur: 'eus peint' },
            { sujet: 'tu' , present: 'peins' , passeCompose: 'as peint' , imparfait: 'peignais' , futurSimple: 'peindras' , conditionnelPresent: 'peindrais' , subjonctifPresent: 'peignes' , plusQueParfait: 'avais peint' , futurAnterieur: 'auras peint' , conditionnelPasse: 'aurais peint' , subjonctifPasse: 'aies peint' , passeSimple: 'peignis' , subjonctifImparfait: 'peignisses' , subjonctifPlusQueParfait: 'eusses peint' , passeAnterieur: 'eus peint' },
            { sujet: 'il/elle' , present: 'peint' , passeCompose: 'a peint' , imparfait: 'peignait' , futurSimple: 'peindra' , conditionnelPresent: 'peindrait' , subjonctifPresent: 'peigne' , plusQueParfait: 'avait peint' , futurAnterieur: 'aura peint' , conditionnelPasse: 'aurait peint' , subjonctifPasse: 'ait peint' , passeSimple: 'peignit' , subjonctifImparfait: 'peignît' , subjonctifPlusQueParfait: 'eût peint' , passeAnterieur: 'eut peint' },
            { sujet: 'nous' , present: 'peignons' , passeCompose: 'avons peint' , imparfait: 'peignions' , futurSimple: 'peindrons' , conditionnelPresent: 'peindrions' , subjonctifPresent: 'peignions' , plusQueParfait: 'avions peint' , futurAnterieur: 'aurons peint' , conditionnelPasse: 'aurions peint' , subjonctifPasse: 'ayons peint' , passeSimple: 'peignîmes' , subjonctifImparfait: 'peignissions' , subjonctifPlusQueParfait: 'eussions peint' , passeAnterieur: 'eûmes peint' },
            { sujet: 'vous' , present: 'peignez' , passeCompose: 'avez peint' , imparfait: 'peigniez' , futurSimple: 'peindrez' , conditionnelPresent: 'peindriez' , subjonctifPresent: 'peigniez' , plusQueParfait: 'aviez peint' , futurAnterieur: 'aurez peint' , conditionnelPasse: 'auriez peint' , subjonctifPasse: 'ayez peint' , passeSimple: 'peignîtes' , subjonctifImparfait: 'peignissiez' , subjonctifPlusQueParfait: 'eussiez peint' , passeAnterieur: 'eûtes peint' },
            { sujet: 'ils/elles' , present: 'peignent' , passeCompose: 'ont peint' , imparfait: 'peignaient' , futurSimple: 'peindront' , conditionnelPresent: 'peindraient' , subjonctifPresent: 'peignent' , plusQueParfait: 'avaient peint' , futurAnterieur: 'auront peint' , conditionnelPasse: 'auraient peint' , subjonctifPasse: 'aient peint' , passeSimple: 'peignirent' , subjonctifImparfait: 'peignissent' , subjonctifPlusQueParfait: 'eussent peint' , passeAnterieur: 'eurent peint' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'rejoindre', infinitive: 'rejoindre', translation: 'to rejoin / catch up with', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'rejoins' , passeCompose: 'ai rejoint' , imparfait: 'rejoignais' , futurSimple: 'rejoindrai' , conditionnelPresent: 'rejoindrais' , subjonctifPresent: 'rejoigne' , plusQueParfait: 'avais rejoint' , futurAnterieur: 'aurai rejoint' , conditionnelPasse: 'aurais rejoint' , subjonctifPasse: 'aie rejoint' , passeSimple: 'rejoignis' , subjonctifImparfait: 'rejoignisse' , subjonctifPlusQueParfait: 'eusse rejoint' , passeAnterieur: 'eus rejoint' },
            { sujet: 'tu' , present: 'rejoins' , passeCompose: 'as rejoint' , imparfait: 'rejoignais' , futurSimple: 'rejoindras' , conditionnelPresent: 'rejoindrais' , subjonctifPresent: 'rejoignes' , plusQueParfait: 'avais rejoint' , futurAnterieur: 'auras rejoint' , conditionnelPasse: 'aurais rejoint' , subjonctifPasse: 'aies rejoint' , passeSimple: 'rejoignis' , subjonctifImparfait: 'rejoignisses' , subjonctifPlusQueParfait: 'eusses rejoint' , passeAnterieur: 'eus rejoint' },
            { sujet: 'il/elle' , present: 'rejoint' , passeCompose: 'a rejoint' , imparfait: 'rejoignait' , futurSimple: 'rejoindra' , conditionnelPresent: 'rejoindrait' , subjonctifPresent: 'rejoigne' , plusQueParfait: 'avait rejoint' , futurAnterieur: 'aura rejoint' , conditionnelPasse: 'aurait rejoint' , subjonctifPasse: 'ait rejoint' , passeSimple: 'rejoignit' , subjonctifImparfait: 'rejoignît' , subjonctifPlusQueParfait: 'eût rejoint' , passeAnterieur: 'eut rejoint' },
            { sujet: 'nous' , present: 'rejoignons' , passeCompose: 'avons rejoint' , imparfait: 'rejoignions' , futurSimple: 'rejoindrons' , conditionnelPresent: 'rejoindrions' , subjonctifPresent: 'rejoignions' , plusQueParfait: 'avions rejoint' , futurAnterieur: 'aurons rejoint' , conditionnelPasse: 'aurions rejoint' , subjonctifPasse: 'ayons rejoint' , passeSimple: 'rejoignîmes' , subjonctifImparfait: 'rejoignissions' , subjonctifPlusQueParfait: 'eussions rejoint' , passeAnterieur: 'eûmes rejoint' },
            { sujet: 'vous' , present: 'rejoignez' , passeCompose: 'avez rejoint' , imparfait: 'rejoigniez' , futurSimple: 'rejoindrez' , conditionnelPresent: 'rejoindriez' , subjonctifPresent: 'rejoigniez' , plusQueParfait: 'aviez rejoint' , futurAnterieur: 'aurez rejoint' , conditionnelPasse: 'auriez rejoint' , subjonctifPasse: 'ayez rejoint' , passeSimple: 'rejoignîtes' , subjonctifImparfait: 'rejoignissiez' , subjonctifPlusQueParfait: 'eussiez rejoint' , passeAnterieur: 'eûtes rejoint' },
            { sujet: 'ils/elles' , present: 'rejoignent' , passeCompose: 'ont rejoint' , imparfait: 'rejoignaient' , futurSimple: 'rejoindront' , conditionnelPresent: 'rejoindraient' , subjonctifPresent: 'rejoignent' , plusQueParfait: 'avaient rejoint' , futurAnterieur: 'auront rejoint' , conditionnelPasse: 'auraient rejoint' , subjonctifPasse: 'aient rejoint' , passeSimple: 'rejoignirent' , subjonctifImparfait: 'rejoignissent' , subjonctifPlusQueParfait: 'eussent rejoint' , passeAnterieur: 'eurent rejoint' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'construire', infinitive: 'construire', translation: 'to build / construct', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'construis' , passeCompose: 'ai construit' , imparfait: 'construisais' , futurSimple: 'construirai' , conditionnelPresent: 'construirais' , subjonctifPresent: 'construise' , plusQueParfait: 'avais construit' , futurAnterieur: 'aurai construit' , conditionnelPasse: 'aurais construit' , subjonctifPasse: 'aie construit' , passeSimple: 'construisis' , subjonctifImparfait: 'construisisse' , subjonctifPlusQueParfait: 'eusse construit' , passeAnterieur: 'eus construit' },
            { sujet: 'tu' , present: 'construis' , passeCompose: 'as construit' , imparfait: 'construisais' , futurSimple: 'construiras' , conditionnelPresent: 'construirais' , subjonctifPresent: 'construises' , plusQueParfait: 'avais construit' , futurAnterieur: 'auras construit' , conditionnelPasse: 'aurais construit' , subjonctifPasse: 'aies construit' , passeSimple: 'construisis' , subjonctifImparfait: 'construisisses' , subjonctifPlusQueParfait: 'eusses construit' , passeAnterieur: 'eus construit' },
            { sujet: 'il/elle' , present: 'construit' , passeCompose: 'a construit' , imparfait: 'construisait' , futurSimple: 'construira' , conditionnelPresent: 'construirait' , subjonctifPresent: 'construise' , plusQueParfait: 'avait construit' , futurAnterieur: 'aura construit' , conditionnelPasse: 'aurait construit' , subjonctifPasse: 'ait construit' , passeSimple: 'construisit' , subjonctifImparfait: 'construisît' , subjonctifPlusQueParfait: 'eût construit' , passeAnterieur: 'eut construit' },
            { sujet: 'nous' , present: 'construisons' , passeCompose: 'avons construit' , imparfait: 'construisions' , futurSimple: 'construirons' , conditionnelPresent: 'construirions' , subjonctifPresent: 'construisions' , plusQueParfait: 'avions construit' , futurAnterieur: 'aurons construit' , conditionnelPasse: 'aurions construit' , subjonctifPasse: 'ayons construit' , passeSimple: 'construisîmes' , subjonctifImparfait: 'construisissions' , subjonctifPlusQueParfait: 'eussions construit' , passeAnterieur: 'eûmes construit' },
            { sujet: 'vous' , present: 'construisez' , passeCompose: 'avez construit' , imparfait: 'construisiez' , futurSimple: 'construirez' , conditionnelPresent: 'construiriez' , subjonctifPresent: 'construisiez' , plusQueParfait: 'aviez construit' , futurAnterieur: 'aurez construit' , conditionnelPasse: 'auriez construit' , subjonctifPasse: 'ayez construit' , passeSimple: 'construisîtes' , subjonctifImparfait: 'construisissiez' , subjonctifPlusQueParfait: 'eussiez construit' , passeAnterieur: 'eûtes construit' },
            { sujet: 'ils/elles' , present: 'construisent' , passeCompose: 'ont construit' , imparfait: 'construisaient' , futurSimple: 'construiront' , conditionnelPresent: 'construiraient' , subjonctifPresent: 'construisent' , plusQueParfait: 'avaient construit' , futurAnterieur: 'auront construit' , conditionnelPasse: 'auraient construit' , subjonctifPasse: 'aient construit' , passeSimple: 'construisirent' , subjonctifImparfait: 'construisissent' , subjonctifPlusQueParfait: 'eussent construit' , passeAnterieur: 'eurent construit' },
            ],
        },
        {
        level: 'B2', unit: 5,
            id: 'absoudre', infinitive: 'absoudre', translation: 'to absolve', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'absous' , passeCompose: 'ai absous' , imparfait: 'absolvais' , futurSimple: 'absoudrai' , conditionnelPresent: 'absoudrais' , subjonctifPresent: 'absolve' , plusQueParfait: 'avais absous' , futurAnterieur: 'aurai absous' , conditionnelPasse: 'aurais absous' , subjonctifPasse: 'aie absous' , passeSimple: 'absolus' , subjonctifImparfait: 'absolusse' , subjonctifPlusQueParfait: 'eusse absous' , passeAnterieur: 'eus absous' },
            { sujet: 'tu' , present: 'absous' , passeCompose: 'as absous' , imparfait: 'absolvais' , futurSimple: 'absoudras' , conditionnelPresent: 'absoudrais' , subjonctifPresent: 'absolves' , plusQueParfait: 'avais absous' , futurAnterieur: 'auras absous' , conditionnelPasse: 'aurais absous' , subjonctifPasse: 'aies absous' , passeSimple: 'absolus' , subjonctifImparfait: 'absolusses' , subjonctifPlusQueParfait: 'eusses absous' , passeAnterieur: 'eus absous' },
            { sujet: 'il/elle' , present: 'absout' , passeCompose: 'a absous' , imparfait: 'absolvait' , futurSimple: 'absoudra' , conditionnelPresent: 'absoudrait' , subjonctifPresent: 'absolve' , plusQueParfait: 'avait absous' , futurAnterieur: 'aura absous' , conditionnelPasse: 'aurait absous' , subjonctifPasse: 'ait absous' , passeSimple: 'absolut' , subjonctifImparfait: 'absolût' , subjonctifPlusQueParfait: 'eût absous' , passeAnterieur: 'eut absous' },
            { sujet: 'nous' , present: 'absolvons' , passeCompose: 'avons absous' , imparfait: 'absolvions' , futurSimple: 'absoudrons' , conditionnelPresent: 'absoudrions' , subjonctifPresent: 'absolvions' , plusQueParfait: 'avions absous' , futurAnterieur: 'aurons absous' , conditionnelPasse: 'aurions absous' , subjonctifPasse: 'ayons absous' , passeSimple: 'absolûmes' , subjonctifImparfait: 'absolussions' , subjonctifPlusQueParfait: 'eussions absous' , passeAnterieur: 'eûmes absous' },
            { sujet: 'vous' , present: 'absolvez' , passeCompose: 'avez absous' , imparfait: 'absolviez' , futurSimple: 'absoudrez' , conditionnelPresent: 'absoudriez' , subjonctifPresent: 'absolviez' , plusQueParfait: 'aviez absous' , futurAnterieur: 'aurez absous' , conditionnelPasse: 'auriez absous' , subjonctifPasse: 'ayez absous' , passeSimple: 'absolûtes' , subjonctifImparfait: 'absolussiez' , subjonctifPlusQueParfait: 'eussiez absous' , passeAnterieur: 'eûtes absous' },
            { sujet: 'ils/elles' , present: 'absolvent' , passeCompose: 'ont absous' , imparfait: 'absolvaient' , futurSimple: 'absoudront' , conditionnelPresent: 'absoudraient' , subjonctifPresent: 'absolvent' , plusQueParfait: 'avaient absous' , futurAnterieur: 'auront absous' , conditionnelPasse: 'auraient absous' , subjonctifPasse: 'aient absous' , passeSimple: 'absolurent' , subjonctifImparfait: 'absolussent' , subjonctifPlusQueParfait: 'eussent absous' , passeAnterieur: 'eurent absous' },
            ],
        },
    ];

export const helpersB2: Record<string, HelperVerbFR> = {

};
