import type { HelperVerbFR, VerbEntry, VerbGroup } from '../../../types/verbs';

export const verbGroupC1: VerbGroup = { id: 'c1', title: 'C1 — Advanced', titleFR: 'C1 — Avancé', description: 'Rare and literary verbs for full mastery', descriptionFR: 'Verbes rares et littéraires pour une maîtrise totale', icon: '🔥', color: '#BE185D' };

export const verbsC1: VerbEntry[] = [
        {
        level: 'C1', unit: 5,
            id: 'vaincre', infinitive: 'vaincre', translation: 'to defeat / overcome', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'vaincs' , passeCompose: 'ai vaincu' , imparfait: 'vainquais' , futurSimple: 'vaincrai' , conditionnelPresent: 'vaincrais' , subjonctifPresent: 'vainque' , plusQueParfait: 'avais vaincu' , futurAnterieur: 'aurai vaincu' , conditionnelPasse: 'aurais vaincu' , subjonctifPasse: 'aie vaincu' , passeSimple: 'vainquis' , subjonctifImparfait: 'vainquisse' , subjonctifPlusQueParfait: 'eusse vaincu' , passeAnterieur: 'eus vaincu' },
            { sujet: 'tu' , present: 'vaincs' , passeCompose: 'as vaincu' , imparfait: 'vainquais' , futurSimple: 'vaincras' , conditionnelPresent: 'vaincrais' , subjonctifPresent: 'vainques' , plusQueParfait: 'avais vaincu' , futurAnterieur: 'auras vaincu' , conditionnelPasse: 'aurais vaincu' , subjonctifPasse: 'aies vaincu' , passeSimple: 'vainquis' , subjonctifImparfait: 'vainquisses' , subjonctifPlusQueParfait: 'eusses vaincu' , passeAnterieur: 'eus vaincu' },
            { sujet: 'il/elle' , present: 'vainc' , passeCompose: 'a vaincu' , imparfait: 'vainquait' , futurSimple: 'vaincra' , conditionnelPresent: 'vaincrait' , subjonctifPresent: 'vainque' , plusQueParfait: 'avait vaincu' , futurAnterieur: 'aura vaincu' , conditionnelPasse: 'aurait vaincu' , subjonctifPasse: 'ait vaincu' , passeSimple: 'vainquit' , subjonctifImparfait: 'vainquît' , subjonctifPlusQueParfait: 'eût vaincu' , passeAnterieur: 'eut vaincu' },
            { sujet: 'nous' , present: 'vainquons' , passeCompose: 'avons vaincu' , imparfait: 'vainquions' , futurSimple: 'vaincrons' , conditionnelPresent: 'vaincrions' , subjonctifPresent: 'vainquions' , plusQueParfait: 'avions vaincu' , futurAnterieur: 'aurons vaincu' , conditionnelPasse: 'aurions vaincu' , subjonctifPasse: 'ayons vaincu' , passeSimple: 'vainquîmes' , subjonctifImparfait: 'vainquissions' , subjonctifPlusQueParfait: 'eussions vaincu' , passeAnterieur: 'eûmes vaincu' },
            { sujet: 'vous' , present: 'vainquez' , passeCompose: 'avez vaincu' , imparfait: 'vainquiez' , futurSimple: 'vaincrez' , conditionnelPresent: 'vaincriez' , subjonctifPresent: 'vainquiez' , plusQueParfait: 'aviez vaincu' , futurAnterieur: 'aurez vaincu' , conditionnelPasse: 'auriez vaincu' , subjonctifPasse: 'ayez vaincu' , passeSimple: 'vainquîtes' , subjonctifImparfait: 'vainquissiez' , subjonctifPlusQueParfait: 'eussiez vaincu' , passeAnterieur: 'eûtes vaincu' },
            { sujet: 'ils/elles' , present: 'vainquent' , passeCompose: 'ont vaincu' , imparfait: 'vainquaient' , futurSimple: 'vaincront' , conditionnelPresent: 'vaincraient' , subjonctifPresent: 'vainquent' , plusQueParfait: 'avaient vaincu' , futurAnterieur: 'auront vaincu' , conditionnelPasse: 'auraient vaincu' , subjonctifPasse: 'aient vaincu' , passeSimple: 'vainquirent' , subjonctifImparfait: 'vainquissent' , subjonctifPlusQueParfait: 'eussent vaincu' , passeAnterieur: 'eurent vaincu' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'valoir', infinitive: 'valoir', translation: 'to be worth', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'vaux' , passeCompose: 'ai valu' , imparfait: 'valais' , futurSimple: 'vaudrai' , conditionnelPresent: 'vaudrais' , subjonctifPresent: 'vaille' , plusQueParfait: 'avais valu' , futurAnterieur: 'aurai valu' , conditionnelPasse: 'aurais valu' , subjonctifPasse: 'aie valu' , passeSimple: 'valus' , subjonctifImparfait: 'valusse' , subjonctifPlusQueParfait: 'eusse valu' , passeAnterieur: 'eus valu' },
            { sujet: 'tu' , present: 'vaux' , passeCompose: 'as valu' , imparfait: 'valais' , futurSimple: 'vaudras' , conditionnelPresent: 'vaudrais' , subjonctifPresent: 'vailles' , plusQueParfait: 'avais valu' , futurAnterieur: 'auras valu' , conditionnelPasse: 'aurais valu' , subjonctifPasse: 'aies valu' , passeSimple: 'valus' , subjonctifImparfait: 'valusses' , subjonctifPlusQueParfait: 'eusses valu' , passeAnterieur: 'eus valu' },
            { sujet: 'il/elle' , present: 'vaut' , passeCompose: 'a valu' , imparfait: 'valait' , futurSimple: 'vaudra' , conditionnelPresent: 'vaudrait' , subjonctifPresent: 'vaille' , plusQueParfait: 'avait valu' , futurAnterieur: 'aura valu' , conditionnelPasse: 'aurait valu' , subjonctifPasse: 'ait valu' , passeSimple: 'valut' , subjonctifImparfait: 'valût' , subjonctifPlusQueParfait: 'eût valu' , passeAnterieur: 'eut valu' },
            { sujet: 'nous' , present: 'valons' , passeCompose: 'avons valu' , imparfait: 'valions' , futurSimple: 'vaudrons' , conditionnelPresent: 'vaudrions' , subjonctifPresent: 'valions' , plusQueParfait: 'avions valu' , futurAnterieur: 'aurons valu' , conditionnelPasse: 'aurions valu' , subjonctifPasse: 'ayons valu' , passeSimple: 'valûmes' , subjonctifImparfait: 'valussions' , subjonctifPlusQueParfait: 'eussions valu' , passeAnterieur: 'eûmes valu' },
            { sujet: 'vous' , present: 'valez' , passeCompose: 'avez valu' , imparfait: 'valiez' , futurSimple: 'vaudrez' , conditionnelPresent: 'vaudriez' , subjonctifPresent: 'valiez' , plusQueParfait: 'aviez valu' , futurAnterieur: 'aurez valu' , conditionnelPasse: 'auriez valu' , subjonctifPasse: 'ayez valu' , passeSimple: 'valûtes' , subjonctifImparfait: 'valussiez' , subjonctifPlusQueParfait: 'eussiez valu' , passeAnterieur: 'eûtes valu' },
            { sujet: 'ils/elles' , present: 'valent' , passeCompose: 'ont valu' , imparfait: 'valaient' , futurSimple: 'vaudront' , conditionnelPresent: 'vaudraient' , subjonctifPresent: 'vaillent' , plusQueParfait: 'avaient valu' , futurAnterieur: 'auront valu' , conditionnelPasse: 'auraient valu' , subjonctifPasse: 'aient valu' , passeSimple: 'valurent' , subjonctifImparfait: 'valussent' , subjonctifPlusQueParfait: 'eussent valu' , passeAnterieur: 'eurent valu' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'joindre', infinitive: 'joindre', translation: 'to join / to reach', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'joins' , passeCompose: 'ai joint' , imparfait: 'joignais' , futurSimple: 'joindrai' , conditionnelPresent: 'joindrais' , subjonctifPresent: 'joigne' , plusQueParfait: 'avais joint' , futurAnterieur: 'aurai joint' , conditionnelPasse: 'aurais joint' , subjonctifPasse: 'aie joint' , passeSimple: 'joignis' , subjonctifImparfait: 'joignisse' , subjonctifPlusQueParfait: 'eusse joint' , passeAnterieur: 'eus joint' },
            { sujet: 'tu' , present: 'joins' , passeCompose: 'as joint' , imparfait: 'joignais' , futurSimple: 'joindras' , conditionnelPresent: 'joindrais' , subjonctifPresent: 'joignes' , plusQueParfait: 'avais joint' , futurAnterieur: 'auras joint' , conditionnelPasse: 'aurais joint' , subjonctifPasse: 'aies joint' , passeSimple: 'joignis' , subjonctifImparfait: 'joignisses' , subjonctifPlusQueParfait: 'eusses joint' , passeAnterieur: 'eus joint' },
            { sujet: 'il/elle' , present: 'joint' , passeCompose: 'a joint' , imparfait: 'joignait' , futurSimple: 'joindra' , conditionnelPresent: 'joindrait' , subjonctifPresent: 'joigne' , plusQueParfait: 'avait joint' , futurAnterieur: 'aura joint' , conditionnelPasse: 'aurait joint' , subjonctifPasse: 'ait joint' , passeSimple: 'joignit' , subjonctifImparfait: 'joignît' , subjonctifPlusQueParfait: 'eût joint' , passeAnterieur: 'eut joint' },
            { sujet: 'nous' , present: 'joignons' , passeCompose: 'avons joint' , imparfait: 'joignions' , futurSimple: 'joindrons' , conditionnelPresent: 'joindrions' , subjonctifPresent: 'joignions' , plusQueParfait: 'avions joint' , futurAnterieur: 'aurons joint' , conditionnelPasse: 'aurions joint' , subjonctifPasse: 'ayons joint' , passeSimple: 'joignîmes' , subjonctifImparfait: 'joignissions' , subjonctifPlusQueParfait: 'eussions joint' , passeAnterieur: 'eûmes joint' },
            { sujet: 'vous' , present: 'joignez' , passeCompose: 'avez joint' , imparfait: 'joigniez' , futurSimple: 'joindrez' , conditionnelPresent: 'joindriez' , subjonctifPresent: 'joigniez' , plusQueParfait: 'aviez joint' , futurAnterieur: 'aurez joint' , conditionnelPasse: 'auriez joint' , subjonctifPasse: 'ayez joint' , passeSimple: 'joignîtes' , subjonctifImparfait: 'joignissiez' , subjonctifPlusQueParfait: 'eussiez joint' , passeAnterieur: 'eûtes joint' },
            { sujet: 'ils/elles' , present: 'joignent' , passeCompose: 'ont joint' , imparfait: 'joignaient' , futurSimple: 'joindront' , conditionnelPresent: 'joindraient' , subjonctifPresent: 'joignent' , plusQueParfait: 'avaient joint' , futurAnterieur: 'auront joint' , conditionnelPasse: 'auraient joint' , subjonctifPasse: 'aient joint' , passeSimple: 'joignirent' , subjonctifImparfait: 'joignissent' , subjonctifPlusQueParfait: 'eussent joint' , passeAnterieur: 'eurent joint' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'battre', infinitive: 'battre', translation: 'to beat', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'bats' , passeCompose: 'ai battu' , imparfait: 'battais' , futurSimple: 'battrai' , conditionnelPresent: 'battrais' , subjonctifPresent: 'batte' , plusQueParfait: 'avais battu' , futurAnterieur: 'aurai battu' , conditionnelPasse: 'aurais battu' , subjonctifPasse: 'aie battu' , passeSimple: 'battis' , subjonctifImparfait: 'battisse' , subjonctifPlusQueParfait: 'eusse battu' , passeAnterieur: 'eus battu' },
            { sujet: 'tu' , present: 'bats' , passeCompose: 'as battu' , imparfait: 'battais' , futurSimple: 'battras' , conditionnelPresent: 'battrais' , subjonctifPresent: 'battes' , plusQueParfait: 'avais battu' , futurAnterieur: 'auras battu' , conditionnelPasse: 'aurais battu' , subjonctifPasse: 'aies battu' , passeSimple: 'battis' , subjonctifImparfait: 'battisses' , subjonctifPlusQueParfait: 'eusses battu' , passeAnterieur: 'eus battu' },
            { sujet: 'il/elle' , present: 'bat' , passeCompose: 'a battu' , imparfait: 'battait' , futurSimple: 'battra' , conditionnelPresent: 'battrait' , subjonctifPresent: 'batte' , plusQueParfait: 'avait battu' , futurAnterieur: 'aura battu' , conditionnelPasse: 'aurait battu' , subjonctifPasse: 'ait battu' , passeSimple: 'battit' , subjonctifImparfait: 'battît' , subjonctifPlusQueParfait: 'eût battu' , passeAnterieur: 'eut battu' },
            { sujet: 'nous' , present: 'battons' , passeCompose: 'avons battu' , imparfait: 'battions' , futurSimple: 'battrons' , conditionnelPresent: 'battrions' , subjonctifPresent: 'battions' , plusQueParfait: 'avions battu' , futurAnterieur: 'aurons battu' , conditionnelPasse: 'aurions battu' , subjonctifPasse: 'ayons battu' , passeSimple: 'battîmes' , subjonctifImparfait: 'battissions' , subjonctifPlusQueParfait: 'eussions battu' , passeAnterieur: 'eûmes battu' },
            { sujet: 'vous' , present: 'battez' , passeCompose: 'avez battu' , imparfait: 'battiez' , futurSimple: 'battrez' , conditionnelPresent: 'battriez' , subjonctifPresent: 'battiez' , plusQueParfait: 'aviez battu' , futurAnterieur: 'aurez battu' , conditionnelPasse: 'auriez battu' , subjonctifPasse: 'ayez battu' , passeSimple: 'battîtes' , subjonctifImparfait: 'battissiez' , subjonctifPlusQueParfait: 'eussiez battu' , passeAnterieur: 'eûtes battu' },
            { sujet: 'ils/elles' , present: 'battent' , passeCompose: 'ont battu' , imparfait: 'battaient' , futurSimple: 'battront' , conditionnelPresent: 'battraient' , subjonctifPresent: 'battent' , plusQueParfait: 'avaient battu' , futurAnterieur: 'auront battu' , conditionnelPasse: 'auraient battu' , subjonctifPasse: 'aient battu' , passeSimple: 'battirent' , subjonctifImparfait: 'battissent' , subjonctifPlusQueParfait: 'eussent battu' , passeAnterieur: 'eurent battu' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'acquerir', infinitive: 'acquérir', translation: 'to acquire', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'acquiers' , passeCompose: 'ai acquis' , imparfait: 'acquérais' , futurSimple: 'acquerrai' , conditionnelPresent: 'acquerrais' , subjonctifPresent: 'acquière' , plusQueParfait: 'avais acquis' , futurAnterieur: 'aurai acquis' , conditionnelPasse: 'aurais acquis' , subjonctifPasse: 'aie acquis' , passeSimple: 'acquis' , subjonctifImparfait: 'acquisse' , subjonctifPlusQueParfait: 'eusse acquis' , passeAnterieur: 'eus acquis' },
            { sujet: 'tu' , present: 'acquiers' , passeCompose: 'as acquis' , imparfait: 'acquérais' , futurSimple: 'acquerras' , conditionnelPresent: 'acquerrais' , subjonctifPresent: 'acquières' , plusQueParfait: 'avais acquis' , futurAnterieur: 'auras acquis' , conditionnelPasse: 'aurais acquis' , subjonctifPasse: 'aies acquis' , passeSimple: 'acquis' , subjonctifImparfait: 'acquisses' , subjonctifPlusQueParfait: 'eusses acquis' , passeAnterieur: 'eus acquis' },
            { sujet: 'il/elle' , present: 'acquiert' , passeCompose: 'a acquis' , imparfait: 'acquérait' , futurSimple: 'acquerra' , conditionnelPresent: 'acquerrait' , subjonctifPresent: 'acquière' , plusQueParfait: 'avait acquis' , futurAnterieur: 'aura acquis' , conditionnelPasse: 'aurait acquis' , subjonctifPasse: 'ait acquis' , passeSimple: 'acquit' , subjonctifImparfait: 'acquît' , subjonctifPlusQueParfait: 'eût acquis' , passeAnterieur: 'eut acquis' },
            { sujet: 'nous' , present: 'acquérons' , passeCompose: 'avons acquis' , imparfait: 'acquérions' , futurSimple: 'acquerrons' , conditionnelPresent: 'acquerrions' , subjonctifPresent: 'acquérions' , plusQueParfait: 'avions acquis' , futurAnterieur: 'aurons acquis' , conditionnelPasse: 'aurions acquis' , subjonctifPasse: 'ayons acquis' , passeSimple: 'acquîmes' , subjonctifImparfait: 'acquissions' , subjonctifPlusQueParfait: 'eussions acquis' , passeAnterieur: 'eûmes acquis' },
            { sujet: 'vous' , present: 'acquérez' , passeCompose: 'avez acquis' , imparfait: 'acquériez' , futurSimple: 'acquerrez' , conditionnelPresent: 'acquerriez' , subjonctifPresent: 'acquériez' , plusQueParfait: 'aviez acquis' , futurAnterieur: 'aurez acquis' , conditionnelPasse: 'auriez acquis' , subjonctifPasse: 'ayez acquis' , passeSimple: 'acquîtes' , subjonctifImparfait: 'acquissiez' , subjonctifPlusQueParfait: 'eussiez acquis' , passeAnterieur: 'eûtes acquis' },
            { sujet: 'ils/elles' , present: 'acquièrent' , passeCompose: 'ont acquis' , imparfait: 'acquéraient' , futurSimple: 'acquerront' , conditionnelPresent: 'acquerraient' , subjonctifPresent: 'acquièrent' , plusQueParfait: 'avaient acquis' , futurAnterieur: 'auront acquis' , conditionnelPasse: 'auraient acquis' , subjonctifPasse: 'aient acquis' , passeSimple: 'acquirent' , subjonctifImparfait: 'acquissent' , subjonctifPlusQueParfait: 'eussent acquis' , passeAnterieur: 'eurent acquis' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'fuir', infinitive: 'fuir', translation: 'to flee / to escape', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'fuis' , passeCompose: 'ai fui' , imparfait: 'fuyais' , futurSimple: 'fuirai' , conditionnelPresent: 'fuirais' , subjonctifPresent: 'fuie' , plusQueParfait: 'avais fui' , futurAnterieur: 'aurai fui' , conditionnelPasse: 'aurais fui' , subjonctifPasse: 'aie fui' , passeSimple: 'fuis' , subjonctifImparfait: 'fuisse' , subjonctifPlusQueParfait: 'eusse fui' , passeAnterieur: 'eus fui' },
            { sujet: 'tu' , present: 'fuis' , passeCompose: 'as fui' , imparfait: 'fuyais' , futurSimple: 'fuiras' , conditionnelPresent: 'fuirais' , subjonctifPresent: 'fuies' , plusQueParfait: 'avais fui' , futurAnterieur: 'auras fui' , conditionnelPasse: 'aurais fui' , subjonctifPasse: 'aies fui' , passeSimple: 'fuis' , subjonctifImparfait: 'fuisses' , subjonctifPlusQueParfait: 'eusses fui' , passeAnterieur: 'eus fui' },
            { sujet: 'il/elle' , present: 'fuit' , passeCompose: 'a fui' , imparfait: 'fuyait' , futurSimple: 'fuira' , conditionnelPresent: 'fuirait' , subjonctifPresent: 'fuie' , plusQueParfait: 'avait fui' , futurAnterieur: 'aura fui' , conditionnelPasse: 'aurait fui' , subjonctifPasse: 'ait fui' , passeSimple: 'fuit' , subjonctifImparfait: 'fuît' , subjonctifPlusQueParfait: 'eût fui' , passeAnterieur: 'eut fui' },
            { sujet: 'nous' , present: 'fuyons' , passeCompose: 'avons fui' , imparfait: 'fuyions' , futurSimple: 'fuirons' , conditionnelPresent: 'fuirions' , subjonctifPresent: 'fuyions' , plusQueParfait: 'avions fui' , futurAnterieur: 'aurons fui' , conditionnelPasse: 'aurions fui' , subjonctifPasse: 'ayons fui' , passeSimple: 'fuîmes' , subjonctifImparfait: 'fuissions' , subjonctifPlusQueParfait: 'eussions fui' , passeAnterieur: 'eûmes fui' },
            { sujet: 'vous' , present: 'fuyez' , passeCompose: 'avez fui' , imparfait: 'fuyiez' , futurSimple: 'fuirez' , conditionnelPresent: 'fuiriez' , subjonctifPresent: 'fuyiez' , plusQueParfait: 'aviez fui' , futurAnterieur: 'aurez fui' , conditionnelPasse: 'auriez fui' , subjonctifPasse: 'ayez fui' , passeSimple: 'fuîtes' , subjonctifImparfait: 'fuissiez' , subjonctifPlusQueParfait: 'eussiez fui' , passeAnterieur: 'eûtes fui' },
            { sujet: 'ils/elles' , present: 'fuient' , passeCompose: 'ont fui' , imparfait: 'fuyaient' , futurSimple: 'fuiront' , conditionnelPresent: 'fuiraient' , subjonctifPresent: 'fuient' , plusQueParfait: 'avaient fui' , futurAnterieur: 'auront fui' , conditionnelPasse: 'auraient fui' , subjonctifPasse: 'aient fui' , passeSimple: 'fuirent' , subjonctifImparfait: 'fuissent' , subjonctifPlusQueParfait: 'eussent fui' , passeAnterieur: 'eurent fui' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'nuire', infinitive: 'nuire', translation: 'to harm', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'nuis' , passeCompose: 'ai nui' , imparfait: 'nuisais' , futurSimple: 'nuirai' , conditionnelPresent: 'nuirais' , subjonctifPresent: 'nuise' , plusQueParfait: 'avais nui' , futurAnterieur: 'aurai nui' , conditionnelPasse: 'aurais nui' , subjonctifPasse: 'aie nui' , passeSimple: 'nuisis' , subjonctifImparfait: 'nuisisse' , subjonctifPlusQueParfait: 'eusse nui' , passeAnterieur: 'eus nui' },
            { sujet: 'tu' , present: 'nuis' , passeCompose: 'as nui' , imparfait: 'nuisais' , futurSimple: 'nuiras' , conditionnelPresent: 'nuirais' , subjonctifPresent: 'nuises' , plusQueParfait: 'avais nui' , futurAnterieur: 'auras nui' , conditionnelPasse: 'aurais nui' , subjonctifPasse: 'aies nui' , passeSimple: 'nuisis' , subjonctifImparfait: 'nuisisses' , subjonctifPlusQueParfait: 'eusses nui' , passeAnterieur: 'eus nui' },
            { sujet: 'il/elle' , present: 'nuit' , passeCompose: 'a nui' , imparfait: 'nuisait' , futurSimple: 'nuira' , conditionnelPresent: 'nuirait' , subjonctifPresent: 'nuise' , plusQueParfait: 'avait nui' , futurAnterieur: 'aura nui' , conditionnelPasse: 'aurait nui' , subjonctifPasse: 'ait nui' , passeSimple: 'nuisit' , subjonctifImparfait: 'nuisît' , subjonctifPlusQueParfait: 'eût nui' , passeAnterieur: 'eut nui' },
            { sujet: 'nous' , present: 'nuisons' , passeCompose: 'avons nui' , imparfait: 'nuisions' , futurSimple: 'nuirons' , conditionnelPresent: 'nuirions' , subjonctifPresent: 'nuisions' , plusQueParfait: 'avions nui' , futurAnterieur: 'aurons nui' , conditionnelPasse: 'aurions nui' , subjonctifPasse: 'ayons nui' , passeSimple: 'nuisîmes' , subjonctifImparfait: 'nuisissions' , subjonctifPlusQueParfait: 'eussions nui' , passeAnterieur: 'eûmes nui' },
            { sujet: 'vous' , present: 'nuisez' , passeCompose: 'avez nui' , imparfait: 'nuisiez' , futurSimple: 'nuirez' , conditionnelPresent: 'nuiriez' , subjonctifPresent: 'nuisiez' , plusQueParfait: 'aviez nui' , futurAnterieur: 'aurez nui' , conditionnelPasse: 'auriez nui' , subjonctifPasse: 'ayez nui' , passeSimple: 'nuisîtes' , subjonctifImparfait: 'nuisissiez' , subjonctifPlusQueParfait: 'eussiez nui' , passeAnterieur: 'eûtes nui' },
            { sujet: 'ils/elles' , present: 'nuisent' , passeCompose: 'ont nui' , imparfait: 'nuisaient' , futurSimple: 'nuiront' , conditionnelPresent: 'nuiraient' , subjonctifPresent: 'nuisent' , plusQueParfait: 'avaient nui' , futurAnterieur: 'auront nui' , conditionnelPasse: 'auraient nui' , subjonctifPasse: 'aient nui' , passeSimple: 'nuisirent' , subjonctifImparfait: 'nuisissent' , subjonctifPlusQueParfait: 'eussent nui' , passeAnterieur: 'eurent nui' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'luire', infinitive: 'luire', translation: 'to shine / gleam', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'luis' , passeCompose: 'ai lui' , imparfait: 'luisais' , futurSimple: 'luirai' , conditionnelPresent: 'luirais' , subjonctifPresent: 'luise' , plusQueParfait: 'avais lui' , futurAnterieur: 'aurai lui' , conditionnelPasse: 'aurais lui' , subjonctifPasse: 'aie lui' , passeSimple: 'luisis' , subjonctifImparfait: 'luisisse' , subjonctifPlusQueParfait: 'eusse lui' , passeAnterieur: 'eus lui' },
            { sujet: 'tu' , present: 'luis' , passeCompose: 'as lui' , imparfait: 'luisais' , futurSimple: 'luiras' , conditionnelPresent: 'luirais' , subjonctifPresent: 'luises' , plusQueParfait: 'avais lui' , futurAnterieur: 'auras lui' , conditionnelPasse: 'aurais lui' , subjonctifPasse: 'aies lui' , passeSimple: 'luisis' , subjonctifImparfait: 'luisisses' , subjonctifPlusQueParfait: 'eusses lui' , passeAnterieur: 'eus lui' },
            { sujet: 'il/elle' , present: 'luit' , passeCompose: 'a lui' , imparfait: 'luisait' , futurSimple: 'luira' , conditionnelPresent: 'luirait' , subjonctifPresent: 'luise' , plusQueParfait: 'avait lui' , futurAnterieur: 'aura lui' , conditionnelPasse: 'aurait lui' , subjonctifPasse: 'ait lui' , passeSimple: 'luisit' , subjonctifImparfait: 'luisît' , subjonctifPlusQueParfait: 'eût lui' , passeAnterieur: 'eut lui' },
            { sujet: 'nous' , present: 'luisons' , passeCompose: 'avons lui' , imparfait: 'luisions' , futurSimple: 'luirons' , conditionnelPresent: 'luirions' , subjonctifPresent: 'luisions' , plusQueParfait: 'avions lui' , futurAnterieur: 'aurons lui' , conditionnelPasse: 'aurions lui' , subjonctifPasse: 'ayons lui' , passeSimple: 'luisîmes' , subjonctifImparfait: 'luisissions' , subjonctifPlusQueParfait: 'eussions lui' , passeAnterieur: 'eûmes lui' },
            { sujet: 'vous' , present: 'luisez' , passeCompose: 'avez lui' , imparfait: 'luisiez' , futurSimple: 'luirez' , conditionnelPresent: 'luiriez' , subjonctifPresent: 'luisiez' , plusQueParfait: 'aviez lui' , futurAnterieur: 'aurez lui' , conditionnelPasse: 'auriez lui' , subjonctifPasse: 'ayez lui' , passeSimple: 'luisîtes' , subjonctifImparfait: 'luisissiez' , subjonctifPlusQueParfait: 'eussiez lui' , passeAnterieur: 'eûtes lui' },
            { sujet: 'ils/elles' , present: 'luisent' , passeCompose: 'ont lui' , imparfait: 'luisaient' , futurSimple: 'luiront' , conditionnelPresent: 'luiraient' , subjonctifPresent: 'luisent' , plusQueParfait: 'avaient lui' , futurAnterieur: 'auront lui' , conditionnelPasse: 'auraient lui' , subjonctifPasse: 'aient lui' , passeSimple: 'luisirent' , subjonctifImparfait: 'luisissent' , subjonctifPlusQueParfait: 'eussent lui' , passeAnterieur: 'eurent lui' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'clore', infinitive: 'clore', translation: 'to close / end', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'clos' , passeCompose: 'ai clos' , imparfait: 'closais' , futurSimple: 'clorai' , conditionnelPresent: 'clorais' , subjonctifPresent: 'close' , plusQueParfait: 'avais clos' , futurAnterieur: 'aurai clos' , conditionnelPasse: 'aurais clos' , subjonctifPasse: 'aie clos' , passeSimple: 'closis' , subjonctifImparfait: 'closisse' , subjonctifPlusQueParfait: 'eusse clos' , passeAnterieur: 'eus clos' },
            { sujet: 'tu' , present: 'clos' , passeCompose: 'as clos' , imparfait: 'closais' , futurSimple: 'cloras' , conditionnelPresent: 'clorais' , subjonctifPresent: 'closes' , plusQueParfait: 'avais clos' , futurAnterieur: 'auras clos' , conditionnelPasse: 'aurais clos' , subjonctifPasse: 'aies clos' , passeSimple: 'closis' , subjonctifImparfait: 'closisses' , subjonctifPlusQueParfait: 'eusses clos' , passeAnterieur: 'eus clos' },
            { sujet: 'il/elle' , present: 'clôt' , passeCompose: 'a clos' , imparfait: 'closait' , futurSimple: 'clora' , conditionnelPresent: 'clorait' , subjonctifPresent: 'close' , plusQueParfait: 'avait clos' , futurAnterieur: 'aura clos' , conditionnelPasse: 'aurait clos' , subjonctifPasse: 'ait clos' , passeSimple: 'closit' , subjonctifImparfait: 'closît' , subjonctifPlusQueParfait: 'eût clos' , passeAnterieur: 'eut clos' },
            { sujet: 'nous' , present: 'closons' , passeCompose: 'avons clos' , imparfait: 'closions' , futurSimple: 'clorons' , conditionnelPresent: 'clorions' , subjonctifPresent: 'closions' , plusQueParfait: 'avions clos' , futurAnterieur: 'aurons clos' , conditionnelPasse: 'aurions clos' , subjonctifPasse: 'ayons clos' , passeSimple: 'closîmes' , subjonctifImparfait: 'closissions' , subjonctifPlusQueParfait: 'eussions clos' , passeAnterieur: 'eûmes clos' },
            { sujet: 'vous' , present: 'closez' , passeCompose: 'avez clos' , imparfait: 'closiez' , futurSimple: 'clorez' , conditionnelPresent: 'cloriez' , subjonctifPresent: 'closiez' , plusQueParfait: 'aviez clos' , futurAnterieur: 'aurez clos' , conditionnelPasse: 'auriez clos' , subjonctifPasse: 'ayez clos' , passeSimple: 'closîtes' , subjonctifImparfait: 'closissiez' , subjonctifPlusQueParfait: 'eussiez clos' , passeAnterieur: 'eûtes clos' },
            { sujet: 'ils/elles' , present: 'closent' , passeCompose: 'ont clos' , imparfait: 'closaient' , futurSimple: 'cloront' , conditionnelPresent: 'cloraient' , subjonctifPresent: 'closent' , plusQueParfait: 'avaient clos' , futurAnterieur: 'auront clos' , conditionnelPasse: 'auraient clos' , subjonctifPasse: 'aient clos' , passeSimple: 'closirent' , subjonctifImparfait: 'closissent' , subjonctifPlusQueParfait: 'eussent clos' , passeAnterieur: 'eurent clos' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'traire', infinitive: 'traire', translation: 'to milk', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'trais' , passeCompose: 'ai trait' , imparfait: 'trayais' , futurSimple: 'trairai' , conditionnelPresent: 'trairais' , subjonctifPresent: 'traie' , plusQueParfait: 'avais trait' , futurAnterieur: 'aurai trait' , conditionnelPasse: 'aurais trait' , subjonctifPasse: 'aie trait' , passeSimple: 'trayis' , subjonctifImparfait: 'trayisse' , subjonctifPlusQueParfait: 'eusse trait' , passeAnterieur: 'eus trait' },
            { sujet: 'tu' , present: 'trais' , passeCompose: 'as trait' , imparfait: 'trayais' , futurSimple: 'trairas' , conditionnelPresent: 'trairais' , subjonctifPresent: 'traies' , plusQueParfait: 'avais trait' , futurAnterieur: 'auras trait' , conditionnelPasse: 'aurais trait' , subjonctifPasse: 'aies trait' , passeSimple: 'trayis' , subjonctifImparfait: 'trayisses' , subjonctifPlusQueParfait: 'eusses trait' , passeAnterieur: 'eus trait' },
            { sujet: 'il/elle' , present: 'trait' , passeCompose: 'a trait' , imparfait: 'trayait' , futurSimple: 'traira' , conditionnelPresent: 'trairait' , subjonctifPresent: 'traie' , plusQueParfait: 'avait trait' , futurAnterieur: 'aura trait' , conditionnelPasse: 'aurait trait' , subjonctifPasse: 'ait trait' , passeSimple: 'trayit' , subjonctifImparfait: 'trayît' , subjonctifPlusQueParfait: 'eût trait' , passeAnterieur: 'eut trait' },
            { sujet: 'nous' , present: 'trayons' , passeCompose: 'avons trait' , imparfait: 'trayions' , futurSimple: 'trairons' , conditionnelPresent: 'trairions' , subjonctifPresent: 'trayions' , plusQueParfait: 'avions trait' , futurAnterieur: 'aurons trait' , conditionnelPasse: 'aurions trait' , subjonctifPasse: 'ayons trait' , passeSimple: 'trayîmes' , subjonctifImparfait: 'trayissions' , subjonctifPlusQueParfait: 'eussions trait' , passeAnterieur: 'eûmes trait' },
            { sujet: 'vous' , present: 'trayez' , passeCompose: 'avez trait' , imparfait: 'trayiez' , futurSimple: 'trairez' , conditionnelPresent: 'trairiez' , subjonctifPresent: 'trayiez' , plusQueParfait: 'aviez trait' , futurAnterieur: 'aurez trait' , conditionnelPasse: 'auriez trait' , subjonctifPasse: 'ayez trait' , passeSimple: 'trayîtes' , subjonctifImparfait: 'trayissiez' , subjonctifPlusQueParfait: 'eussiez trait' , passeAnterieur: 'eûtes trait' },
            { sujet: 'ils/elles' , present: 'traient' , passeCompose: 'ont trait' , imparfait: 'trayaient' , futurSimple: 'trairont' , conditionnelPresent: 'trairaient' , subjonctifPresent: 'traient' , plusQueParfait: 'avaient trait' , futurAnterieur: 'auront trait' , conditionnelPasse: 'auraient trait' , subjonctifPasse: 'aient trait' , passeSimple: 'trayirent' , subjonctifImparfait: 'trayissent' , subjonctifPlusQueParfait: 'eussent trait' , passeAnterieur: 'eurent trait' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'extraire', infinitive: 'extraire', translation: 'to extract', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'extrais' , passeCompose: 'ai extrait' , imparfait: 'extrayais' , futurSimple: 'extrairai' , conditionnelPresent: 'extrairais' , subjonctifPresent: 'extraie' , plusQueParfait: 'avais extrait' , futurAnterieur: 'aurai extrait' , conditionnelPasse: 'aurais extrait' , subjonctifPasse: 'aie extrait' , passeSimple: 'extrayis' , subjonctifImparfait: 'extrayisse' , subjonctifPlusQueParfait: 'eusse extrait' , passeAnterieur: 'eus extrait' },
            { sujet: 'tu' , present: 'extrais' , passeCompose: 'as extrait' , imparfait: 'extrayais' , futurSimple: 'extrairas' , conditionnelPresent: 'extrairais' , subjonctifPresent: 'extraies' , plusQueParfait: 'avais extrait' , futurAnterieur: 'auras extrait' , conditionnelPasse: 'aurais extrait' , subjonctifPasse: 'aies extrait' , passeSimple: 'extrayis' , subjonctifImparfait: 'extrayisses' , subjonctifPlusQueParfait: 'eusses extrait' , passeAnterieur: 'eus extrait' },
            { sujet: 'il/elle' , present: 'extrait' , passeCompose: 'a extrait' , imparfait: 'extrayait' , futurSimple: 'extraira' , conditionnelPresent: 'extrairait' , subjonctifPresent: 'extraie' , plusQueParfait: 'avait extrait' , futurAnterieur: 'aura extrait' , conditionnelPasse: 'aurait extrait' , subjonctifPasse: 'ait extrait' , passeSimple: 'extrayit' , subjonctifImparfait: 'extrayît' , subjonctifPlusQueParfait: 'eût extrait' , passeAnterieur: 'eut extrait' },
            { sujet: 'nous' , present: 'extrayons' , passeCompose: 'avons extrait' , imparfait: 'extrayions' , futurSimple: 'extrairons' , conditionnelPresent: 'extrairions' , subjonctifPresent: 'extrayions' , plusQueParfait: 'avions extrait' , futurAnterieur: 'aurons extrait' , conditionnelPasse: 'aurions extrait' , subjonctifPasse: 'ayons extrait' , passeSimple: 'extrayîmes' , subjonctifImparfait: 'extrayissions' , subjonctifPlusQueParfait: 'eussions extrait' , passeAnterieur: 'eûmes extrait' },
            { sujet: 'vous' , present: 'extrayez' , passeCompose: 'avez extrait' , imparfait: 'extrayiez' , futurSimple: 'extrairez' , conditionnelPresent: 'extrairiez' , subjonctifPresent: 'extrayiez' , plusQueParfait: 'aviez extrait' , futurAnterieur: 'aurez extrait' , conditionnelPasse: 'auriez extrait' , subjonctifPasse: 'ayez extrait' , passeSimple: 'extrayîtes' , subjonctifImparfait: 'extrayissiez' , subjonctifPlusQueParfait: 'eussiez extrait' , passeAnterieur: 'eûtes extrait' },
            { sujet: 'ils/elles' , present: 'extraient' , passeCompose: 'ont extrait' , imparfait: 'extrayaient' , futurSimple: 'extrairont' , conditionnelPresent: 'extrairaient' , subjonctifPresent: 'extraient' , plusQueParfait: 'avaient extrait' , futurAnterieur: 'auront extrait' , conditionnelPasse: 'auraient extrait' , subjonctifPasse: 'aient extrait' , passeSimple: 'extrayirent' , subjonctifImparfait: 'extrayissent' , subjonctifPlusQueParfait: 'eussent extrait' , passeAnterieur: 'eurent extrait' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'souffrir', infinitive: 'souffrir', translation: 'to suffer', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'souffre' , passeCompose: 'ai souffert' , imparfait: 'souffrais' , futurSimple: 'souffrirai' , conditionnelPresent: 'souffrirais' , subjonctifPresent: 'souffre' , plusQueParfait: 'avais souffert' , futurAnterieur: 'aurai souffert' , conditionnelPasse: 'aurais souffert' , subjonctifPasse: 'aie souffert' , passeSimple: 'souffris' , subjonctifImparfait: 'souffrisse' , subjonctifPlusQueParfait: 'eusse souffert' , passeAnterieur: 'eus souffert' },
            { sujet: 'tu' , present: 'souffres' , passeCompose: 'as souffert' , imparfait: 'souffrais' , futurSimple: 'souffriras' , conditionnelPresent: 'souffrirais' , subjonctifPresent: 'souffres' , plusQueParfait: 'avais souffert' , futurAnterieur: 'auras souffert' , conditionnelPasse: 'aurais souffert' , subjonctifPasse: 'aies souffert' , passeSimple: 'souffris' , subjonctifImparfait: 'souffrisses' , subjonctifPlusQueParfait: 'eusses souffert' , passeAnterieur: 'eus souffert' },
            { sujet: 'il/elle' , present: 'souffre' , passeCompose: 'a souffert' , imparfait: 'souffrait' , futurSimple: 'souffrira' , conditionnelPresent: 'souffrirait' , subjonctifPresent: 'souffre' , plusQueParfait: 'avait souffert' , futurAnterieur: 'aura souffert' , conditionnelPasse: 'aurait souffert' , subjonctifPasse: 'ait souffert' , passeSimple: 'souffrit' , subjonctifImparfait: 'souffrît' , subjonctifPlusQueParfait: 'eût souffert' , passeAnterieur: 'eut souffert' },
            { sujet: 'nous' , present: 'souffrons' , passeCompose: 'avons souffert' , imparfait: 'souffrions' , futurSimple: 'souffrirons' , conditionnelPresent: 'souffririons' , subjonctifPresent: 'souffrions' , plusQueParfait: 'avions souffert' , futurAnterieur: 'aurons souffert' , conditionnelPasse: 'aurions souffert' , subjonctifPasse: 'ayons souffert' , passeSimple: 'souffrîmes' , subjonctifImparfait: 'souffrissions' , subjonctifPlusQueParfait: 'eussions souffert' , passeAnterieur: 'eûmes souffert' },
            { sujet: 'vous' , present: 'souffrez' , passeCompose: 'avez souffert' , imparfait: 'souffriez' , futurSimple: 'souffrirez' , conditionnelPresent: 'souffririez' , subjonctifPresent: 'souffriez' , plusQueParfait: 'aviez souffert' , futurAnterieur: 'aurez souffert' , conditionnelPasse: 'auriez souffert' , subjonctifPasse: 'ayez souffert' , passeSimple: 'souffrîtes' , subjonctifImparfait: 'souffrissiez' , subjonctifPlusQueParfait: 'eussiez souffert' , passeAnterieur: 'eûtes souffert' },
            { sujet: 'ils/elles' , present: 'souffrent' , passeCompose: 'ont souffert' , imparfait: 'souffraient' , futurSimple: 'souffriront' , conditionnelPresent: 'souffriraient' , subjonctifPresent: 'souffrent' , plusQueParfait: 'avaient souffert' , futurAnterieur: 'auront souffert' , conditionnelPasse: 'auraient souffert' , subjonctifPasse: 'aient souffert' , passeSimple: 'souffrirent' , subjonctifImparfait: 'souffrissent' , subjonctifPlusQueParfait: 'eussent souffert' , passeAnterieur: 'eurent souffert' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'offrir', infinitive: 'offrir', translation: 'to offer', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'offre' , passeCompose: 'ai offert' , imparfait: 'offrais' , futurSimple: 'offrirai' , conditionnelPresent: 'offrirais' , subjonctifPresent: 'offre' , plusQueParfait: 'avais offert' , futurAnterieur: 'aurai offert' , conditionnelPasse: 'aurais offert' , subjonctifPasse: 'aie offert' , passeSimple: 'offris' , subjonctifImparfait: 'offrisse' , subjonctifPlusQueParfait: 'eusse offert' , passeAnterieur: 'eus offert' },
            { sujet: 'tu' , present: 'offres' , passeCompose: 'as offert' , imparfait: 'offrais' , futurSimple: 'offriras' , conditionnelPresent: 'offrirais' , subjonctifPresent: 'offres' , plusQueParfait: 'avais offert' , futurAnterieur: 'auras offert' , conditionnelPasse: 'aurais offert' , subjonctifPasse: 'aies offert' , passeSimple: 'offris' , subjonctifImparfait: 'offrisses' , subjonctifPlusQueParfait: 'eusses offert' , passeAnterieur: 'eus offert' },
            { sujet: 'il/elle' , present: 'offre' , passeCompose: 'a offert' , imparfait: 'offrait' , futurSimple: 'offrira' , conditionnelPresent: 'offrirait' , subjonctifPresent: 'offre' , plusQueParfait: 'avait offert' , futurAnterieur: 'aura offert' , conditionnelPasse: 'aurait offert' , subjonctifPasse: 'ait offert' , passeSimple: 'offrit' , subjonctifImparfait: 'offrît' , subjonctifPlusQueParfait: 'eût offert' , passeAnterieur: 'eut offert' },
            { sujet: 'nous' , present: 'offrons' , passeCompose: 'avons offert' , imparfait: 'offrions' , futurSimple: 'offrirons' , conditionnelPresent: 'offririons' , subjonctifPresent: 'offrions' , plusQueParfait: 'avions offert' , futurAnterieur: 'aurons offert' , conditionnelPasse: 'aurions offert' , subjonctifPasse: 'ayons offert' , passeSimple: 'offrîmes' , subjonctifImparfait: 'offrissions' , subjonctifPlusQueParfait: 'eussions offert' , passeAnterieur: 'eûmes offert' },
            { sujet: 'vous' , present: 'offrez' , passeCompose: 'avez offert' , imparfait: 'offriez' , futurSimple: 'offrirez' , conditionnelPresent: 'offririez' , subjonctifPresent: 'offriez' , plusQueParfait: 'aviez offert' , futurAnterieur: 'aurez offert' , conditionnelPasse: 'auriez offert' , subjonctifPasse: 'ayez offert' , passeSimple: 'offrîtes' , subjonctifImparfait: 'offrissiez' , subjonctifPlusQueParfait: 'eussiez offert' , passeAnterieur: 'eûtes offert' },
            { sujet: 'ils/elles' , present: 'offrent' , passeCompose: 'ont offert' , imparfait: 'offraient' , futurSimple: 'offriront' , conditionnelPresent: 'offriraient' , subjonctifPresent: 'offrent' , plusQueParfait: 'avaient offert' , futurAnterieur: 'auront offert' , conditionnelPasse: 'auraient offert' , subjonctifPasse: 'aient offert' , passeSimple: 'offrirent' , subjonctifImparfait: 'offrissent' , subjonctifPlusQueParfait: 'eussent offert' , passeAnterieur: 'eurent offert' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'cueillir', infinitive: 'cueillir', translation: 'to pick / gather', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'cueille' , passeCompose: 'ai cueilli' , imparfait: 'cueillais' , futurSimple: 'cueillerai' , conditionnelPresent: 'cueillerais' , subjonctifPresent: 'cueille' , plusQueParfait: 'avais cueilli' , futurAnterieur: 'aurai cueilli' , conditionnelPasse: 'aurais cueilli' , subjonctifPasse: 'aie cueilli' , passeSimple: 'cueillis' , subjonctifImparfait: 'cueillisse' , subjonctifPlusQueParfait: 'eusse cueilli' , passeAnterieur: 'eus cueilli' },
            { sujet: 'tu' , present: 'cueilles' , passeCompose: 'as cueilli' , imparfait: 'cueillais' , futurSimple: 'cueilleras' , conditionnelPresent: 'cueillerais' , subjonctifPresent: 'cueilles' , plusQueParfait: 'avais cueilli' , futurAnterieur: 'auras cueilli' , conditionnelPasse: 'aurais cueilli' , subjonctifPasse: 'aies cueilli' , passeSimple: 'cueillis' , subjonctifImparfait: 'cueillisses' , subjonctifPlusQueParfait: 'eusses cueilli' , passeAnterieur: 'eus cueilli' },
            { sujet: 'il/elle' , present: 'cueille' , passeCompose: 'a cueilli' , imparfait: 'cueillait' , futurSimple: 'cueillera' , conditionnelPresent: 'cueillerait' , subjonctifPresent: 'cueille' , plusQueParfait: 'avait cueilli' , futurAnterieur: 'aura cueilli' , conditionnelPasse: 'aurait cueilli' , subjonctifPasse: 'ait cueilli' , passeSimple: 'cueillit' , subjonctifImparfait: 'cueillît' , subjonctifPlusQueParfait: 'eût cueilli' , passeAnterieur: 'eut cueilli' },
            { sujet: 'nous' , present: 'cueillons' , passeCompose: 'avons cueilli' , imparfait: 'cueillions' , futurSimple: 'cueillerons' , conditionnelPresent: 'cueillerions' , subjonctifPresent: 'cueillions' , plusQueParfait: 'avions cueilli' , futurAnterieur: 'aurons cueilli' , conditionnelPasse: 'aurions cueilli' , subjonctifPasse: 'ayons cueilli' , passeSimple: 'cueillîmes' , subjonctifImparfait: 'cueillissions' , subjonctifPlusQueParfait: 'eussions cueilli' , passeAnterieur: 'eûmes cueilli' },
            { sujet: 'vous' , present: 'cueillez' , passeCompose: 'avez cueilli' , imparfait: 'cueilliez' , futurSimple: 'cueillerez' , conditionnelPresent: 'cueilleriez' , subjonctifPresent: 'cueilliez' , plusQueParfait: 'aviez cueilli' , futurAnterieur: 'aurez cueilli' , conditionnelPasse: 'auriez cueilli' , subjonctifPasse: 'ayez cueilli' , passeSimple: 'cueillîtes' , subjonctifImparfait: 'cueillissiez' , subjonctifPlusQueParfait: 'eussiez cueilli' , passeAnterieur: 'eûtes cueilli' },
            { sujet: 'ils/elles' , present: 'cueillent' , passeCompose: 'ont cueilli' , imparfait: 'cueillaient' , futurSimple: 'cueilleront' , conditionnelPresent: 'cueilleraient' , subjonctifPresent: 'cueillent' , plusQueParfait: 'avaient cueilli' , futurAnterieur: 'auront cueilli' , conditionnelPasse: 'auraient cueilli' , subjonctifPasse: 'aient cueilli' , passeSimple: 'cueillirent' , subjonctifImparfait: 'cueillissent' , subjonctifPlusQueParfait: 'eussent cueilli' , passeAnterieur: 'eurent cueilli' },
            ],
        },
        {
        level: 'C1', unit: 5,
            id: 'assaillir', infinitive: 'assaillir', translation: 'to assail / attack', type: 'Irregular', color: '#DC2626',
            rows: [
            { sujet: 'je' , present: 'assaille' , passeCompose: 'ai assailli' , imparfait: 'assaillais' , futurSimple: 'assaillirai' , conditionnelPresent: 'assaillirais' , subjonctifPresent: 'assaille' , plusQueParfait: 'avais assailli' , futurAnterieur: 'aurai assailli' , conditionnelPasse: 'aurais assailli' , subjonctifPasse: 'aie assailli' , passeSimple: 'assaillis' , subjonctifImparfait: 'assaillisse' , subjonctifPlusQueParfait: 'eusse assailli' , passeAnterieur: 'eus assailli' },
            { sujet: 'tu' , present: 'assailles' , passeCompose: 'as assailli' , imparfait: 'assaillais' , futurSimple: 'assailliras' , conditionnelPresent: 'assaillirais' , subjonctifPresent: 'assailles' , plusQueParfait: 'avais assailli' , futurAnterieur: 'auras assailli' , conditionnelPasse: 'aurais assailli' , subjonctifPasse: 'aies assailli' , passeSimple: 'assaillis' , subjonctifImparfait: 'assaillisses' , subjonctifPlusQueParfait: 'eusses assailli' , passeAnterieur: 'eus assailli' },
            { sujet: 'il/elle' , present: 'assaille' , passeCompose: 'a assailli' , imparfait: 'assaillait' , futurSimple: 'assaillira' , conditionnelPresent: 'assaillirait' , subjonctifPresent: 'assaille' , plusQueParfait: 'avait assailli' , futurAnterieur: 'aura assailli' , conditionnelPasse: 'aurait assailli' , subjonctifPasse: 'ait assailli' , passeSimple: 'assaillit' , subjonctifImparfait: 'assaillît' , subjonctifPlusQueParfait: 'eût assailli' , passeAnterieur: 'eut assailli' },
            { sujet: 'nous' , present: 'assaillons' , passeCompose: 'avons assailli' , imparfait: 'assaillions' , futurSimple: 'assaillirons' , conditionnelPresent: 'assaillirions' , subjonctifPresent: 'assaillions' , plusQueParfait: 'avions assailli' , futurAnterieur: 'aurons assailli' , conditionnelPasse: 'aurions assailli' , subjonctifPasse: 'ayons assailli' , passeSimple: 'assaillîmes' , subjonctifImparfait: 'assaillissions' , subjonctifPlusQueParfait: 'eussions assailli' , passeAnterieur: 'eûmes assailli' },
            { sujet: 'vous' , present: 'assaillez' , passeCompose: 'avez assailli' , imparfait: 'assailliez' , futurSimple: 'assaillirez' , conditionnelPresent: 'assailliriez' , subjonctifPresent: 'assailliez' , plusQueParfait: 'aviez assailli' , futurAnterieur: 'aurez assailli' , conditionnelPasse: 'auriez assailli' , subjonctifPasse: 'ayez assailli' , passeSimple: 'assaillîtes' , subjonctifImparfait: 'assaillissiez' , subjonctifPlusQueParfait: 'eussiez assailli' , passeAnterieur: 'eûtes assailli' },
            { sujet: 'ils/elles' , present: 'assaillent' , passeCompose: 'ont assailli' , imparfait: 'assaillaient' , futurSimple: 'assailliront' , conditionnelPresent: 'assailliraient' , subjonctifPresent: 'assaillent' , plusQueParfait: 'avaient assailli' , futurAnterieur: 'auront assailli' , conditionnelPasse: 'auraient assailli' , subjonctifPasse: 'aient assailli' , passeSimple: 'assaillirent' , subjonctifImparfait: 'assaillissent' , subjonctifPlusQueParfait: 'eussent assailli' , passeAnterieur: 'eurent assailli' },
            ],
        },
    ];

export const helpersC1: Record<string, HelperVerbFR> = {

};
