import type { HelperVerbFR, VerbEntry, VerbGroup } from '../../../types/verbs';

export const verbGroupC2: VerbGroup = { id: 'c2', title: 'C2 — Mastery', titleFR: 'C2 — Maîtrise', description: 'Rare, literary and archaic verbs for complete mastery', descriptionFR: 'Verbes rares, littéraires et archaïques pour une maîtrise totale', icon: '👑', color: '#6D28D9' };

export const verbsC2: VerbEntry[] = [
        {
        level: 'C2', unit: 5,
            id: 'dissoudre', infinitive: 'dissoudre', translation: 'to dissolve', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'dissous' , passeCompose: 'ai dissous' , imparfait: 'dissolvais' , futurSimple: 'dissoudrai' , conditionnelPresent: 'dissoudrais' , subjonctifPresent: 'dissolve' , plusQueParfait: 'avais dissous' , futurAnterieur: 'aurai dissous' , conditionnelPasse: 'aurais dissous' , subjonctifPasse: 'aie dissous' , passeSimple: 'dissolus' , subjonctifImparfait: 'dissolusse' , subjonctifPlusQueParfait: 'eusse dissous' , passeAnterieur: 'eus dissous' },
            { sujet: 'tu' , present: 'dissous' , passeCompose: 'as dissous' , imparfait: 'dissolvais' , futurSimple: 'dissoudras' , conditionnelPresent: 'dissoudrais' , subjonctifPresent: 'dissolves' , plusQueParfait: 'avais dissous' , futurAnterieur: 'auras dissous' , conditionnelPasse: 'aurais dissous' , subjonctifPasse: 'aies dissous' , passeSimple: 'dissolus' , subjonctifImparfait: 'dissolusses' , subjonctifPlusQueParfait: 'eusses dissous' , passeAnterieur: 'eus dissous' },
            { sujet: 'il/elle' , present: 'dissout' , passeCompose: 'a dissous' , imparfait: 'dissolvait' , futurSimple: 'dissoudra' , conditionnelPresent: 'dissoudrait' , subjonctifPresent: 'dissolve' , plusQueParfait: 'avait dissous' , futurAnterieur: 'aura dissous' , conditionnelPasse: 'aurait dissous' , subjonctifPasse: 'ait dissous' , passeSimple: 'dissolut' , subjonctifImparfait: 'dissolût' , subjonctifPlusQueParfait: 'eût dissous' , passeAnterieur: 'eut dissous' },
            { sujet: 'nous' , present: 'dissolvons' , passeCompose: 'avons dissous' , imparfait: 'dissolvions' , futurSimple: 'dissoudrons' , conditionnelPresent: 'dissoudrions' , subjonctifPresent: 'dissolvions' , plusQueParfait: 'avions dissous' , futurAnterieur: 'aurons dissous' , conditionnelPasse: 'aurions dissous' , subjonctifPasse: 'ayons dissous' , passeSimple: 'dissolûmes' , subjonctifImparfait: 'dissolussions' , subjonctifPlusQueParfait: 'eussions dissous' , passeAnterieur: 'eûmes dissous' },
            { sujet: 'vous' , present: 'dissolvez' , passeCompose: 'avez dissous' , imparfait: 'dissolviez' , futurSimple: 'dissoudrez' , conditionnelPresent: 'dissoudriez' , subjonctifPresent: 'dissolviez' , plusQueParfait: 'aviez dissous' , futurAnterieur: 'aurez dissous' , conditionnelPasse: 'auriez dissous' , subjonctifPasse: 'ayez dissous' , passeSimple: 'dissolûtes' , subjonctifImparfait: 'dissolussiez' , subjonctifPlusQueParfait: 'eussiez dissous' , passeAnterieur: 'eûtes dissous' },
            { sujet: 'ils/elles' , present: 'dissolvent' , passeCompose: 'ont dissous' , imparfait: 'dissolvaient' , futurSimple: 'dissoudront' , conditionnelPresent: 'dissoudraient' , subjonctifPresent: 'dissolvent' , plusQueParfait: 'avaient dissous' , futurAnterieur: 'auront dissous' , conditionnelPasse: 'auraient dissous' , subjonctifPasse: 'aient dissous' , passeSimple: 'dissolurent' , subjonctifImparfait: 'dissolussent' , subjonctifPlusQueParfait: 'eussent dissous' , passeAnterieur: 'eurent dissous' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'contredire', infinitive: 'contredire', translation: 'to contradict', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'contredis' , passeCompose: 'ai contredit' , imparfait: 'contredisais' , futurSimple: 'contredirai' , conditionnelPresent: 'contredirais' , subjonctifPresent: 'contredise' , plusQueParfait: 'avais contredit' , futurAnterieur: 'aurai contredit' , conditionnelPasse: 'aurais contredit' , subjonctifPasse: 'aie contredit' , passeSimple: 'contredis' , subjonctifImparfait: 'contredisse' , subjonctifPlusQueParfait: 'eusse contredit' , passeAnterieur: 'eus contredit' },
            { sujet: 'tu' , present: 'contredis' , passeCompose: 'as contredit' , imparfait: 'contredisais' , futurSimple: 'contrediras' , conditionnelPresent: 'contredirais' , subjonctifPresent: 'contredises' , plusQueParfait: 'avais contredit' , futurAnterieur: 'auras contredit' , conditionnelPasse: 'aurais contredit' , subjonctifPasse: 'aies contredit' , passeSimple: 'contredis' , subjonctifImparfait: 'contredisses' , subjonctifPlusQueParfait: 'eusses contredit' , passeAnterieur: 'eus contredit' },
            { sujet: 'il/elle' , present: 'contredit' , passeCompose: 'a contredit' , imparfait: 'contredisait' , futurSimple: 'contredira' , conditionnelPresent: 'contredirait' , subjonctifPresent: 'contredise' , plusQueParfait: 'avait contredit' , futurAnterieur: 'aura contredit' , conditionnelPasse: 'aurait contredit' , subjonctifPasse: 'ait contredit' , passeSimple: 'contredit' , subjonctifImparfait: 'contredît' , subjonctifPlusQueParfait: 'eût contredit' , passeAnterieur: 'eut contredit' },
            { sujet: 'nous' , present: 'contredisons' , passeCompose: 'avons contredit' , imparfait: 'contredisions' , futurSimple: 'contredirons' , conditionnelPresent: 'contredirions' , subjonctifPresent: 'contredisions' , plusQueParfait: 'avions contredit' , futurAnterieur: 'aurons contredit' , conditionnelPasse: 'aurions contredit' , subjonctifPasse: 'ayons contredit' , passeSimple: 'contredîmes' , subjonctifImparfait: 'contredissions' , subjonctifPlusQueParfait: 'eussions contredit' , passeAnterieur: 'eûmes contredit' },
            { sujet: 'vous' , present: 'contredisez' , passeCompose: 'avez contredit' , imparfait: 'contredisiez' , futurSimple: 'contredirez' , conditionnelPresent: 'contrediriez' , subjonctifPresent: 'contredisiez' , plusQueParfait: 'aviez contredit' , futurAnterieur: 'aurez contredit' , conditionnelPasse: 'auriez contredit' , subjonctifPasse: 'ayez contredit' , passeSimple: 'contredîtes' , subjonctifImparfait: 'contredissiez' , subjonctifPlusQueParfait: 'eussiez contredit' , passeAnterieur: 'eûtes contredit' },
            { sujet: 'ils/elles' , present: 'contredisent' , passeCompose: 'ont contredit' , imparfait: 'contredisaient' , futurSimple: 'contrediront' , conditionnelPresent: 'contrediraient' , subjonctifPresent: 'contredisent' , plusQueParfait: 'avaient contredit' , futurAnterieur: 'auront contredit' , conditionnelPasse: 'auraient contredit' , subjonctifPasse: 'aient contredit' , passeSimple: 'contredirent' , subjonctifImparfait: 'contredissent' , subjonctifPlusQueParfait: 'eussent contredit' , passeAnterieur: 'eurent contredit' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'maudire', infinitive: 'maudire', translation: 'to curse', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'maudis' , passeCompose: 'ai maudit' , imparfait: 'maudissais' , futurSimple: 'maudirai' , conditionnelPresent: 'maudirais' , subjonctifPresent: 'maudisse' , plusQueParfait: 'avais maudit' , futurAnterieur: 'aurai maudit' , conditionnelPasse: 'aurais maudit' , subjonctifPasse: 'aie maudit' , passeSimple: 'maudis' , subjonctifImparfait: 'maudisse' , subjonctifPlusQueParfait: 'eusse maudit' , passeAnterieur: 'eus maudit' },
            { sujet: 'tu' , present: 'maudis' , passeCompose: 'as maudit' , imparfait: 'maudissais' , futurSimple: 'maudiras' , conditionnelPresent: 'maudirais' , subjonctifPresent: 'maudisses' , plusQueParfait: 'avais maudit' , futurAnterieur: 'auras maudit' , conditionnelPasse: 'aurais maudit' , subjonctifPasse: 'aies maudit' , passeSimple: 'maudis' , subjonctifImparfait: 'maudisses' , subjonctifPlusQueParfait: 'eusses maudit' , passeAnterieur: 'eus maudit' },
            { sujet: 'il/elle' , present: 'maudit' , passeCompose: 'a maudit' , imparfait: 'maudissait' , futurSimple: 'maudira' , conditionnelPresent: 'maudirait' , subjonctifPresent: 'maudisse' , plusQueParfait: 'avait maudit' , futurAnterieur: 'aura maudit' , conditionnelPasse: 'aurait maudit' , subjonctifPasse: 'ait maudit' , passeSimple: 'maudit' , subjonctifImparfait: 'maudît' , subjonctifPlusQueParfait: 'eût maudit' , passeAnterieur: 'eut maudit' },
            { sujet: 'nous' , present: 'maudissons' , passeCompose: 'avons maudit' , imparfait: 'maudissions' , futurSimple: 'maudirons' , conditionnelPresent: 'maudirions' , subjonctifPresent: 'maudissions' , plusQueParfait: 'avions maudit' , futurAnterieur: 'aurons maudit' , conditionnelPasse: 'aurions maudit' , subjonctifPasse: 'ayons maudit' , passeSimple: 'maudîmes' , subjonctifImparfait: 'maudissions' , subjonctifPlusQueParfait: 'eussions maudit' , passeAnterieur: 'eûmes maudit' },
            { sujet: 'vous' , present: 'maudissez' , passeCompose: 'avez maudit' , imparfait: 'maudissiez' , futurSimple: 'maudirez' , conditionnelPresent: 'maudiriez' , subjonctifPresent: 'maudissiez' , plusQueParfait: 'aviez maudit' , futurAnterieur: 'aurez maudit' , conditionnelPasse: 'auriez maudit' , subjonctifPasse: 'ayez maudit' , passeSimple: 'maudîtes' , subjonctifImparfait: 'maudissiez' , subjonctifPlusQueParfait: 'eussiez maudit' , passeAnterieur: 'eûtes maudit' },
            { sujet: 'ils/elles' , present: 'maudissent' , passeCompose: 'ont maudit' , imparfait: 'maudissaient' , futurSimple: 'maudiront' , conditionnelPresent: 'maudiraient' , subjonctifPresent: 'maudissent' , plusQueParfait: 'avaient maudit' , futurAnterieur: 'auront maudit' , conditionnelPasse: 'auraient maudit' , subjonctifPasse: 'aient maudit' , passeSimple: 'maudirent' , subjonctifImparfait: 'maudissent' , subjonctifPlusQueParfait: 'eussent maudit' , passeAnterieur: 'eurent maudit' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'feindre', infinitive: 'feindre', translation: 'to pretend / feign', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'feins' , passeCompose: 'ai feint' , imparfait: 'feignais' , futurSimple: 'feindrai' , conditionnelPresent: 'feindrais' , subjonctifPresent: 'feigne' , plusQueParfait: 'avais feint' , futurAnterieur: 'aurai feint' , conditionnelPasse: 'aurais feint' , subjonctifPasse: 'aie feint' , passeSimple: 'feignis' , subjonctifImparfait: 'feignisse' , subjonctifPlusQueParfait: 'eusse feint' , passeAnterieur: 'eus feint' },
            { sujet: 'tu' , present: 'feins' , passeCompose: 'as feint' , imparfait: 'feignais' , futurSimple: 'feindras' , conditionnelPresent: 'feindrais' , subjonctifPresent: 'feignes' , plusQueParfait: 'avais feint' , futurAnterieur: 'auras feint' , conditionnelPasse: 'aurais feint' , subjonctifPasse: 'aies feint' , passeSimple: 'feignis' , subjonctifImparfait: 'feignisses' , subjonctifPlusQueParfait: 'eusses feint' , passeAnterieur: 'eus feint' },
            { sujet: 'il/elle' , present: 'feint' , passeCompose: 'a feint' , imparfait: 'feignait' , futurSimple: 'feindra' , conditionnelPresent: 'feindrait' , subjonctifPresent: 'feigne' , plusQueParfait: 'avait feint' , futurAnterieur: 'aura feint' , conditionnelPasse: 'aurait feint' , subjonctifPasse: 'ait feint' , passeSimple: 'feignit' , subjonctifImparfait: 'feignît' , subjonctifPlusQueParfait: 'eût feint' , passeAnterieur: 'eut feint' },
            { sujet: 'nous' , present: 'feignons' , passeCompose: 'avons feint' , imparfait: 'feignions' , futurSimple: 'feindrons' , conditionnelPresent: 'feindrions' , subjonctifPresent: 'feignions' , plusQueParfait: 'avions feint' , futurAnterieur: 'aurons feint' , conditionnelPasse: 'aurions feint' , subjonctifPasse: 'ayons feint' , passeSimple: 'feignîmes' , subjonctifImparfait: 'feignissions' , subjonctifPlusQueParfait: 'eussions feint' , passeAnterieur: 'eûmes feint' },
            { sujet: 'vous' , present: 'feignez' , passeCompose: 'avez feint' , imparfait: 'feigniez' , futurSimple: 'feindrez' , conditionnelPresent: 'feindriez' , subjonctifPresent: 'feigniez' , plusQueParfait: 'aviez feint' , futurAnterieur: 'aurez feint' , conditionnelPasse: 'auriez feint' , subjonctifPasse: 'ayez feint' , passeSimple: 'feignîtes' , subjonctifImparfait: 'feignissiez' , subjonctifPlusQueParfait: 'eussiez feint' , passeAnterieur: 'eûtes feint' },
            { sujet: 'ils/elles' , present: 'feignent' , passeCompose: 'ont feint' , imparfait: 'feignaient' , futurSimple: 'feindront' , conditionnelPresent: 'feindraient' , subjonctifPresent: 'feignent' , plusQueParfait: 'avaient feint' , futurAnterieur: 'auront feint' , conditionnelPasse: 'auraient feint' , subjonctifPasse: 'aient feint' , passeSimple: 'feignirent' , subjonctifImparfait: 'feignissent' , subjonctifPlusQueParfait: 'eussent feint' , passeAnterieur: 'eurent feint' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'ceindre', infinitive: 'ceindre', translation: 'to gird / surround', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'ceins' , passeCompose: 'ai ceint' , imparfait: 'ceignais' , futurSimple: 'ceindrai' , conditionnelPresent: 'ceindrais' , subjonctifPresent: 'ceigne' , plusQueParfait: 'avais ceint' , futurAnterieur: 'aurai ceint' , conditionnelPasse: 'aurais ceint' , subjonctifPasse: 'aie ceint' , passeSimple: 'ceignis' , subjonctifImparfait: 'ceignisse' , subjonctifPlusQueParfait: 'eusse ceint' , passeAnterieur: 'eus ceint' },
            { sujet: 'tu' , present: 'ceins' , passeCompose: 'as ceint' , imparfait: 'ceignais' , futurSimple: 'ceindras' , conditionnelPresent: 'ceindrais' , subjonctifPresent: 'ceignes' , plusQueParfait: 'avais ceint' , futurAnterieur: 'auras ceint' , conditionnelPasse: 'aurais ceint' , subjonctifPasse: 'aies ceint' , passeSimple: 'ceignis' , subjonctifImparfait: 'ceignisses' , subjonctifPlusQueParfait: 'eusses ceint' , passeAnterieur: 'eus ceint' },
            { sujet: 'il/elle' , present: 'ceint' , passeCompose: 'a ceint' , imparfait: 'ceignait' , futurSimple: 'ceindra' , conditionnelPresent: 'ceindrait' , subjonctifPresent: 'ceigne' , plusQueParfait: 'avait ceint' , futurAnterieur: 'aura ceint' , conditionnelPasse: 'aurait ceint' , subjonctifPasse: 'ait ceint' , passeSimple: 'ceignit' , subjonctifImparfait: 'ceignît' , subjonctifPlusQueParfait: 'eût ceint' , passeAnterieur: 'eut ceint' },
            { sujet: 'nous' , present: 'ceignons' , passeCompose: 'avons ceint' , imparfait: 'ceignions' , futurSimple: 'ceindrons' , conditionnelPresent: 'ceindrions' , subjonctifPresent: 'ceignions' , plusQueParfait: 'avions ceint' , futurAnterieur: 'aurons ceint' , conditionnelPasse: 'aurions ceint' , subjonctifPasse: 'ayons ceint' , passeSimple: 'ceignîmes' , subjonctifImparfait: 'ceignissions' , subjonctifPlusQueParfait: 'eussions ceint' , passeAnterieur: 'eûmes ceint' },
            { sujet: 'vous' , present: 'ceignez' , passeCompose: 'avez ceint' , imparfait: 'ceigniez' , futurSimple: 'ceindrez' , conditionnelPresent: 'ceindriez' , subjonctifPresent: 'ceigniez' , plusQueParfait: 'aviez ceint' , futurAnterieur: 'aurez ceint' , conditionnelPasse: 'auriez ceint' , subjonctifPasse: 'ayez ceint' , passeSimple: 'ceignîtes' , subjonctifImparfait: 'ceignissiez' , subjonctifPlusQueParfait: 'eussiez ceint' , passeAnterieur: 'eûtes ceint' },
            { sujet: 'ils/elles' , present: 'ceignent' , passeCompose: 'ont ceint' , imparfait: 'ceignaient' , futurSimple: 'ceindront' , conditionnelPresent: 'ceindraient' , subjonctifPresent: 'ceignent' , plusQueParfait: 'avaient ceint' , futurAnterieur: 'auront ceint' , conditionnelPasse: 'auraient ceint' , subjonctifPasse: 'aient ceint' , passeSimple: 'ceignirent' , subjonctifImparfait: 'ceignissent' , subjonctifPlusQueParfait: 'eussent ceint' , passeAnterieur: 'eurent ceint' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'choir', infinitive: 'choir', translation: 'to fall (archaic)', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'chois' , passeCompose: 'suis chu(e)' , imparfait: 'choyais' , futurSimple: 'choirai' , conditionnelPresent: 'choirais' , subjonctifPresent: 'choie' , plusQueParfait: 'étais chu(e)' , futurAnterieur: 'serai chu(e)' , conditionnelPasse: 'serais chu(e)' , subjonctifPasse: 'sois chu(e)' , passeSimple: 'chus' , subjonctifImparfait: 'chusse' , subjonctifPlusQueParfait: 'fusse chu(e)' , passeAnterieur: 'fus chu(e)' },
            { sujet: 'tu' , present: 'chois' , passeCompose: 'es chu(e)' , imparfait: 'choyais' , futurSimple: 'choiras' , conditionnelPresent: 'choirais' , subjonctifPresent: 'choies' , plusQueParfait: 'étais chu(e)' , futurAnterieur: 'seras chu(e)' , conditionnelPasse: 'serais chu(e)' , subjonctifPasse: 'sois chu(e)' , passeSimple: 'chus' , subjonctifImparfait: 'chusses' , subjonctifPlusQueParfait: 'fusses chu(e)' , passeAnterieur: 'fus chu(e)' },
            { sujet: 'il/elle' , present: 'choit' , passeCompose: 'est chu(e)' , imparfait: 'choyait' , futurSimple: 'choira' , conditionnelPresent: 'choirait' , subjonctifPresent: 'choie' , plusQueParfait: 'était chu(e)' , futurAnterieur: 'sera chu(e)' , conditionnelPasse: 'serait chu(e)' , subjonctifPasse: 'soit chu(e)' , passeSimple: 'chut' , subjonctifImparfait: 'chût' , subjonctifPlusQueParfait: 'fût chu(e)' , passeAnterieur: 'fut chu(e)' },
            { sujet: 'nous' , present: 'choyons' , passeCompose: 'sommes chu(e)s' , imparfait: 'choyions' , futurSimple: 'choirons' , conditionnelPresent: 'choirions' , subjonctifPresent: 'choyions' , plusQueParfait: 'étions chu(e)s' , futurAnterieur: 'serons chu(e)s' , conditionnelPasse: 'serions chu(e)s' , subjonctifPasse: 'soyons chu(e)s' , passeSimple: 'chûmes' , subjonctifImparfait: 'chussions' , subjonctifPlusQueParfait: 'fussions chu(e)s' , passeAnterieur: 'fûmes chu(e)s' },
            { sujet: 'vous' , present: 'choyez' , passeCompose: 'êtes chu(e)s' , imparfait: 'choyiez' , futurSimple: 'choirez' , conditionnelPresent: 'choiriez' , subjonctifPresent: 'choyiez' , plusQueParfait: 'étiez chu(e)s' , futurAnterieur: 'serez chu(e)s' , conditionnelPasse: 'seriez chu(e)s' , subjonctifPasse: 'soyez chu(e)s' , passeSimple: 'chûtes' , subjonctifImparfait: 'chussiez' , subjonctifPlusQueParfait: 'fussiez chu(e)s' , passeAnterieur: 'fûtes chu(e)s' },
            { sujet: 'ils/elles' , present: 'choient' , passeCompose: 'sont chu(e)s' , imparfait: 'choyaient' , futurSimple: 'choiront' , conditionnelPresent: 'choiraient' , subjonctifPresent: 'choient' , plusQueParfait: 'étaient chu(e)s' , futurAnterieur: 'seront chu(e)s' , conditionnelPasse: 'seraient chu(e)s' , subjonctifPasse: 'soient chu(e)s' , passeSimple: 'churent' , subjonctifImparfait: 'chussent' , subjonctifPlusQueParfait: 'fussent chu(e)s' , passeAnterieur: 'furent chu(e)s' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'faillir', infinitive: 'faillir', translation: 'to almost do / fail', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'faillis' , passeCompose: 'ai failli' , imparfait: 'faillissais' , futurSimple: 'faillirai' , conditionnelPresent: 'faillirais' , subjonctifPresent: 'faillisse' , plusQueParfait: 'avais failli' , futurAnterieur: 'aurai failli' , conditionnelPasse: 'aurais failli' , subjonctifPasse: 'aie failli' , passeSimple: 'faillis' , subjonctifImparfait: 'faillisse' , subjonctifPlusQueParfait: 'eusse failli' , passeAnterieur: 'eus failli' },
            { sujet: 'tu' , present: 'faillis' , passeCompose: 'as failli' , imparfait: 'faillissais' , futurSimple: 'failliras' , conditionnelPresent: 'faillirais' , subjonctifPresent: 'faillisses' , plusQueParfait: 'avais failli' , futurAnterieur: 'auras failli' , conditionnelPasse: 'aurais failli' , subjonctifPasse: 'aies failli' , passeSimple: 'faillis' , subjonctifImparfait: 'faillisses' , subjonctifPlusQueParfait: 'eusses failli' , passeAnterieur: 'eus failli' },
            { sujet: 'il/elle' , present: 'faillit' , passeCompose: 'a failli' , imparfait: 'faillissait' , futurSimple: 'faillira' , conditionnelPresent: 'faillirait' , subjonctifPresent: 'faillisse' , plusQueParfait: 'avait failli' , futurAnterieur: 'aura failli' , conditionnelPasse: 'aurait failli' , subjonctifPasse: 'ait failli' , passeSimple: 'faillit' , subjonctifImparfait: 'faillît' , subjonctifPlusQueParfait: 'eût failli' , passeAnterieur: 'eut failli' },
            { sujet: 'nous' , present: 'faillissons' , passeCompose: 'avons failli' , imparfait: 'faillissions' , futurSimple: 'faillirons' , conditionnelPresent: 'faillirions' , subjonctifPresent: 'faillissions' , plusQueParfait: 'avions failli' , futurAnterieur: 'aurons failli' , conditionnelPasse: 'aurions failli' , subjonctifPasse: 'ayons failli' , passeSimple: 'faillîmes' , subjonctifImparfait: 'faillissions' , subjonctifPlusQueParfait: 'eussions failli' , passeAnterieur: 'eûmes failli' },
            { sujet: 'vous' , present: 'faillissez' , passeCompose: 'avez failli' , imparfait: 'faillissiez' , futurSimple: 'faillirez' , conditionnelPresent: 'failliriez' , subjonctifPresent: 'faillissiez' , plusQueParfait: 'aviez failli' , futurAnterieur: 'aurez failli' , conditionnelPasse: 'auriez failli' , subjonctifPasse: 'ayez failli' , passeSimple: 'faillîtes' , subjonctifImparfait: 'faillissiez' , subjonctifPlusQueParfait: 'eussiez failli' , passeAnterieur: 'eûtes failli' },
            { sujet: 'ils/elles' , present: 'faillissent' , passeCompose: 'ont failli' , imparfait: 'faillissaient' , futurSimple: 'failliront' , conditionnelPresent: 'failliraient' , subjonctifPresent: 'faillissent' , plusQueParfait: 'avaient failli' , futurAnterieur: 'auront failli' , conditionnelPasse: 'auraient failli' , subjonctifPasse: 'aient failli' , passeSimple: 'faillirent' , subjonctifImparfait: 'faillissent' , subjonctifPlusQueParfait: 'eussent failli' , passeAnterieur: 'eurent failli' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'ouir', infinitive: 'ouïr', translation: 'to hear (archaic)', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'ois' , passeCompose: 'ai ouï' , imparfait: 'oyais' , futurSimple: 'ouïrai' , conditionnelPresent: 'ouïrais' , subjonctifPresent: 'oie' , plusQueParfait: 'avais ouï' , futurAnterieur: 'aurai ouï' , conditionnelPasse: 'aurais ouï' , subjonctifPasse: 'aie ouï' , passeSimple: 'ouïis' , subjonctifImparfait: 'ouïisse' , subjonctifPlusQueParfait: 'eusse ouï' , passeAnterieur: 'eus ouï' },
            { sujet: 'tu' , present: 'ois' , passeCompose: 'as ouï' , imparfait: 'oyais' , futurSimple: 'ouïras' , conditionnelPresent: 'ouïrais' , subjonctifPresent: 'oies' , plusQueParfait: 'avais ouï' , futurAnterieur: 'auras ouï' , conditionnelPasse: 'aurais ouï' , subjonctifPasse: 'aies ouï' , passeSimple: 'ouïis' , subjonctifImparfait: 'ouïisses' , subjonctifPlusQueParfait: 'eusses ouï' , passeAnterieur: 'eus ouï' },
            { sujet: 'il/elle' , present: 'oit' , passeCompose: 'a ouï' , imparfait: 'oyait' , futurSimple: 'ouïra' , conditionnelPresent: 'ouïrait' , subjonctifPresent: 'oie' , plusQueParfait: 'avait ouï' , futurAnterieur: 'aura ouï' , conditionnelPasse: 'aurait ouï' , subjonctifPasse: 'ait ouï' , passeSimple: 'ouïit' , subjonctifImparfait: 'ouïît' , subjonctifPlusQueParfait: 'eût ouï' , passeAnterieur: 'eut ouï' },
            { sujet: 'nous' , present: 'oyons' , passeCompose: 'avons ouï' , imparfait: 'oyions' , futurSimple: 'ouïrons' , conditionnelPresent: 'ouïrions' , subjonctifPresent: 'oyions' , plusQueParfait: 'avions ouï' , futurAnterieur: 'aurons ouï' , conditionnelPasse: 'aurions ouï' , subjonctifPasse: 'ayons ouï' , passeSimple: 'ouïîmes' , subjonctifImparfait: 'ouïissions' , subjonctifPlusQueParfait: 'eussions ouï' , passeAnterieur: 'eûmes ouï' },
            { sujet: 'vous' , present: 'oyez' , passeCompose: 'avez ouï' , imparfait: 'oyiez' , futurSimple: 'ouïrez' , conditionnelPresent: 'ouïriez' , subjonctifPresent: 'oyiez' , plusQueParfait: 'aviez ouï' , futurAnterieur: 'aurez ouï' , conditionnelPasse: 'auriez ouï' , subjonctifPasse: 'ayez ouï' , passeSimple: 'ouïîtes' , subjonctifImparfait: 'ouïissiez' , subjonctifPlusQueParfait: 'eussiez ouï' , passeAnterieur: 'eûtes ouï' },
            { sujet: 'ils/elles' , present: 'oient' , passeCompose: 'ont ouï' , imparfait: 'oyaient' , futurSimple: 'ouïront' , conditionnelPresent: 'ouïraient' , subjonctifPresent: 'oient' , plusQueParfait: 'avaient ouï' , futurAnterieur: 'auront ouï' , conditionnelPasse: 'auraient ouï' , subjonctifPasse: 'aient ouï' , passeSimple: 'ouïirent' , subjonctifImparfait: 'ouïissent' , subjonctifPlusQueParfait: 'eussent ouï' , passeAnterieur: 'eurent ouï' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'paitre', infinitive: 'paître', translation: 'to graze', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'pais' , passeCompose: '—' , imparfait: 'paissais' , futurSimple: 'paîtrai' , conditionnelPresent: 'paîtrais' , subjonctifPresent: 'paisse' , plusQueParfait: '—' , futurAnterieur: '—' , conditionnelPasse: '—' , subjonctifPasse: '—' , passeSimple: '—' , subjonctifImparfait: '—' , subjonctifPlusQueParfait: '—' , passeAnterieur: '—' },
            { sujet: 'tu' , present: 'pais' , passeCompose: '—' , imparfait: 'paissais' , futurSimple: 'paîtras' , conditionnelPresent: 'paîtrais' , subjonctifPresent: 'paisses' , plusQueParfait: '—' , futurAnterieur: '—' , conditionnelPasse: '—' , subjonctifPasse: '—' , passeSimple: '—' , subjonctifImparfait: '—' , subjonctifPlusQueParfait: '—' , passeAnterieur: '—' },
            { sujet: 'il/elle' , present: 'paît' , passeCompose: '—' , imparfait: 'paissait' , futurSimple: 'paîtra' , conditionnelPresent: 'paîtrait' , subjonctifPresent: 'paisse' , plusQueParfait: '—' , futurAnterieur: '—' , conditionnelPasse: '—' , subjonctifPasse: '—' , passeSimple: '—' , subjonctifImparfait: '—' , subjonctifPlusQueParfait: '—' , passeAnterieur: '—' },
            { sujet: 'nous' , present: 'paissons' , passeCompose: '—' , imparfait: 'paissions' , futurSimple: 'paîtrons' , conditionnelPresent: 'paîtrions' , subjonctifPresent: 'paissions' , plusQueParfait: '—' , futurAnterieur: '—' , conditionnelPasse: '—' , subjonctifPasse: '—' , passeSimple: '—' , subjonctifImparfait: '—' , subjonctifPlusQueParfait: '—' , passeAnterieur: '—' },
            { sujet: 'vous' , present: 'paissez' , passeCompose: '—' , imparfait: 'paissiez' , futurSimple: 'paîtrez' , conditionnelPresent: 'paîtriez' , subjonctifPresent: 'paissiez' , plusQueParfait: '—' , futurAnterieur: '—' , conditionnelPasse: '—' , subjonctifPasse: '—' , passeSimple: '—' , subjonctifImparfait: '—' , subjonctifPlusQueParfait: '—' , passeAnterieur: '—' },
            { sujet: 'ils/elles' , present: 'paissent' , passeCompose: '—' , imparfait: 'paissaient' , futurSimple: 'paîtront' , conditionnelPresent: 'paîtraient' , subjonctifPresent: 'paissent' , plusQueParfait: '—' , futurAnterieur: '—' , conditionnelPasse: '—' , subjonctifPasse: '—' , passeSimple: '—' , subjonctifImparfait: '—' , subjonctifPlusQueParfait: '—' , passeAnterieur: '—' },
            ],
        },
        {
        level: 'C2', unit: 5,
            id: 'poindre', infinitive: 'poindre', translation: 'to dawn / appear', type: 'Irregular', color: '#6D28D9',
            rows: [
            { sujet: 'je' , present: 'poinds' , passeCompose: 'ai point' , imparfait: 'poignais' , futurSimple: 'poindrai' , conditionnelPresent: 'poindrais' , subjonctifPresent: 'poigne' , plusQueParfait: 'avais point' , futurAnterieur: 'aurai point' , conditionnelPasse: 'aurais point' , subjonctifPasse: 'aie point' , passeSimple: 'poignis' , subjonctifImparfait: 'poignisse' , subjonctifPlusQueParfait: 'eusse point' , passeAnterieur: 'eus point' },
            { sujet: 'tu' , present: 'poinds' , passeCompose: 'as point' , imparfait: 'poignais' , futurSimple: 'poindras' , conditionnelPresent: 'poindrais' , subjonctifPresent: 'poignes' , plusQueParfait: 'avais point' , futurAnterieur: 'auras point' , conditionnelPasse: 'aurais point' , subjonctifPasse: 'aies point' , passeSimple: 'poignis' , subjonctifImparfait: 'poignisses' , subjonctifPlusQueParfait: 'eusses point' , passeAnterieur: 'eus point' },
            { sujet: 'il/elle' , present: 'point' , passeCompose: 'a point' , imparfait: 'poignait' , futurSimple: 'poindra' , conditionnelPresent: 'poindrait' , subjonctifPresent: 'poigne' , plusQueParfait: 'avait point' , futurAnterieur: 'aura point' , conditionnelPasse: 'aurait point' , subjonctifPasse: 'ait point' , passeSimple: 'poignit' , subjonctifImparfait: 'poignît' , subjonctifPlusQueParfait: 'eût point' , passeAnterieur: 'eut point' },
            { sujet: 'nous' , present: 'poignons' , passeCompose: 'avons point' , imparfait: 'poignions' , futurSimple: 'poindrons' , conditionnelPresent: 'poindrions' , subjonctifPresent: 'poignions' , plusQueParfait: 'avions point' , futurAnterieur: 'aurons point' , conditionnelPasse: 'aurions point' , subjonctifPasse: 'ayons point' , passeSimple: 'poignîmes' , subjonctifImparfait: 'poignissions' , subjonctifPlusQueParfait: 'eussions point' , passeAnterieur: 'eûmes point' },
            { sujet: 'vous' , present: 'poignez' , passeCompose: 'avez point' , imparfait: 'poigniez' , futurSimple: 'poindrez' , conditionnelPresent: 'poindriez' , subjonctifPresent: 'poigniez' , plusQueParfait: 'aviez point' , futurAnterieur: 'aurez point' , conditionnelPasse: 'auriez point' , subjonctifPasse: 'ayez point' , passeSimple: 'poignîtes' , subjonctifImparfait: 'poignissiez' , subjonctifPlusQueParfait: 'eussiez point' , passeAnterieur: 'eûtes point' },
            { sujet: 'ils/elles' , present: 'poignent' , passeCompose: 'ont point' , imparfait: 'poignaient' , futurSimple: 'poindront' , conditionnelPresent: 'poindraient' , subjonctifPresent: 'poignent' , plusQueParfait: 'avaient point' , futurAnterieur: 'auront point' , conditionnelPasse: 'auraient point' , subjonctifPasse: 'aient point' , passeSimple: 'poignirent' , subjonctifImparfait: 'poignissent' , subjonctifPlusQueParfait: 'eussent point' , passeAnterieur: 'eurent point' },
            ],
        },
    ];

export const helpersC2: Record<string, HelperVerbFR> = {

};
