import type { ReadingPassage } from '../../../types/lectures/reading';

export const readingB2: ReadingPassage[] = [
    {
        level: 'B2', unit: 1,
        moduleId: 'b2en-digital-education',
        title: 'Education in the Digital Age',
        source: 'Original article — Level B2',
        paragraphs: [
            'Technology has fundamentally altered the landscape of education over the past two decades. From interactive whiteboards in primary schools to AI-powered tutoring platforms at university level, the tools available to teachers and learners have never been more varied or more powerful. Advocates argue that this digital transformation is democratising access to knowledge; critics warn that it risks undermining the very qualities that make education meaningful.',
            'The COVID-19 pandemic served as an involuntary global experiment in remote learning. Schools and universities were forced to migrate online almost overnight, exposing both the possibilities and the limitations of digital education. On the one hand, platforms such as Zoom and Google Classroom allowed lessons to continue across borders; on the other, significant inequalities emerged between students who had reliable internet access and those who did not.',
            'Artificial intelligence is now adding another dimension to this debate. Personalised learning software can adapt to each student\'s pace and identify gaps in understanding with remarkable precision. Some institutions have begun using AI to provide round-the-clock tutoring support, raising questions about the future role of human teachers. Will the teacher of tomorrow be primarily a facilitator, guiding students through a landscape of digital resources, rather than a direct transmitter of knowledge?',
            'There are legitimate concerns on the other side of this argument. Research consistently shows that social interaction, debate and the mentorship of experienced educators play a crucial role in cognitive and emotional development. A screen, however sophisticated, cannot replicate the nuanced feedback of a skilled teacher, nor the serendipitous moment when a student\'s curiosity is ignited by an unexpected classroom discussion.',
            'The most persuasive vision of education in the digital age is not a binary choice between screens and chalkboards, but a thoughtful integration of both. Technology should enhance human teaching, not replace it. Achieving that balance will require not just investment in devices and infrastructure, but sustained reflection on what education is ultimately for.',
        ],
    },
    {
        level: 'B2', unit: 3,
        moduleId: 'b2en-cultural-identity',
        title: 'Cultural Identity in a Globalised World',
        source: 'Original article — Level B2',
        paragraphs: [
            'Globalisation has brought undeniable benefits: greater interconnectedness, the spread of ideas, and access to cultures and products from every corner of the world. Yet it has also triggered a profound and sometimes anxious conversation about cultural identity. As the world becomes more cosmopolitan, many communities are asking: what does it mean to belong somewhere, and what happens to that sense of belonging when the boundaries between cultures begin to dissolve?',
            'The concern is not new. Throughout history, dominant cultures have absorbed or displaced smaller ones. What is distinctive about the contemporary moment is the speed and scale of this process. A teenager in Lagos, Bogotá or Warsaw can consume the same music, films and fashion as their counterpart in New York or London. This cultural convergence creates a sense of shared global experience — but it can also make local traditions, languages and customs feel endangered.',
            'Yet the picture is more complex than a simple story of cultural homogenisation. Research in anthropology and sociology suggests that people rarely abandon their cultural heritage entirely in favour of a global identity. Instead, they engage in what scholars call "hybridisation" — blending influences from multiple sources to create something new and distinctly their own. The French chef who incorporates Japanese techniques, the Brazilian musician who fuses samba with electronic beats, or the second-generation immigrant who navigates fluidly between two worlds: these are not examples of cultural loss, but of cultural creativity.',
            'The greatest risk, perhaps, is not that cultures will disappear, but that only certain voices will be amplified by globalisation while others are systematically marginalised. When the majority of global media, technology platforms and economic power is concentrated in a handful of countries, the flow of cultural influence is rarely equal. Protecting cultural diversity therefore requires deliberate policies: supporting minority languages, funding local arts and media, and ensuring that the global digital space reflects the full breadth of human experience.',
            'In the end, cultural identity has always been dynamic rather than fixed. It is shaped by history, geography and contact with others. Embracing this fluidity, while remaining attentive to the power imbalances that shape it, may be the most honest and productive response to the challenge globalisation poses.',
        ],
    },
    {
        level: 'B2', unit: 2,
        moduleId: 'b2en-ai-everyday',
        title: 'Artificial Intelligence in Everyday Life',
        source: 'Original article — Level B2',
        paragraphs: [
            'Artificial intelligence, once the stuff of science fiction, has quietly become part of our everyday routines. When we ask a virtual assistant about the weather, receive film recommendations from a streaming service, or unlock our phones with our faces, we are relying on technologies that would have seemed almost magical only a generation ago.',
            'The benefits of this revolution are considerable. AI systems can analyse vast amounts of data far more quickly than any human, helping doctors to detect diseases earlier, enabling scientists to model the climate, and allowing businesses to operate more efficiently. For ordinary users, AI offers convenience, personalisation and access to information on an unprecedented scale.',
            'Yet these advances raise serious questions. As algorithms make more of the decisions that shape our lives — from the news we see to the loans we are offered — concerns about fairness, privacy and accountability have grown. If a machine makes a mistake, or reflects the biases hidden in its data, who is responsible? And how much of our personal information are we willing to surrender for the sake of convenience?',
            'Perhaps the most pressing question concerns the future of work. While AI is likely to create new industries and opportunities, it may also automate millions of existing jobs, from driving to accountancy. Societies will need to think carefully about how to retrain workers and share the benefits of this technology fairly.',
            'Ultimately, artificial intelligence is neither a miracle nor a menace, but a powerful tool whose effects depend on how we choose to use it. The challenge for our generation is to harness its enormous potential while remaining alert to its risks — to ensure that the technology serves humanity, rather than the other way around.',
        ],
    },
    {
        level: 'B2', unit: 2,
        moduleId: 'b2en-work-life-balance',
        title: 'Rethinking Work-Life Balance',
        source: 'Original article — Level B2',
        paragraphs: [
            'For decades, the idea of "work-life balance" has dominated conversations about how we should organise our lives. The phrase suggests a simple division: work on one side, life on the other, with the goal of keeping the two in equilibrium. Recently, however, many people have begun to question whether this way of thinking still makes sense.',
            'One problem is that the boundary between work and personal life has become increasingly blurred. With smartphones and laptops, employees can be reached at any hour, and the expectation to respond quickly can follow them home. For many, work no longer stops when they leave the office; it seeps into evenings, weekends and even holidays.',
            'Some experts argue that we should abandon the idea of "balance" altogether and speak instead of "integration". Rather than trying to keep work and life rigidly separate, they suggest, we should look for ways to blend them more harmoniously — working flexibly when it suits us, and making space for personal priorities during the working day.',
            'Others worry that this approach simply allows work to invade every corner of our existence. They point to the rising rates of burnout and stress, and call for stronger boundaries: the right to disconnect, shorter working weeks, and a culture that values rest as much as productivity. Some countries have even passed laws protecting employees from out-of-hours emails.',
            'There is no single answer that suits everyone, for the ideal arrangement depends on individual circumstances and values. What is clear, however, is that the traditional model is under strain. As technology continues to reshape the way we work, finding a sustainable relationship between our jobs and the rest of our lives will remain one of the central challenges of modern society.',
        ],
    },
    {
        level: 'B2', unit: 3,
        moduleId: 'b2en-misinformation',
        title: 'The Challenge of Misinformation',
        source: 'Original article — Level B2',
        paragraphs: [
            'We live in an age of unprecedented access to information. With a few taps on a screen, we can read the news from across the globe, consult experts and share our opinions with millions. Yet this same connectivity has given rise to one of the defining problems of our time: the rapid spread of false and misleading information.',
            'Misinformation is not a new phenomenon, but social media has transformed its scale and speed. A false claim can now travel around the world in minutes, shared by well-meaning people who have no idea that it is untrue. Studies suggest that sensational and emotional stories spread faster than accurate ones, precisely because they provoke strong reactions.',
            'The consequences can be severe. False information about health, for instance, can discourage people from seeking proper treatment, while political misinformation can undermine trust in democratic institutions. When citizens can no longer agree on basic facts, meaningful public debate becomes almost impossible, and society grows more divided.',
            'Tackling this problem is far from straightforward. Technology companies have introduced fact-checking labels and removed some false content, but critics argue that they have not done enough, and that heavy-handed censorship raises its own dangers. Governments, too, must tread carefully, for the line between fighting misinformation and restricting free speech is a delicate one.',
            'Perhaps the most powerful defence is education. By teaching people to think critically, to check their sources and to be sceptical of information that seems designed to provoke outrage, we can build a society that is more resistant to manipulation. In the end, the responsibility lies not only with platforms and governments, but with each of us.',
        ],
    },
    {
        level: 'B2', unit: 3,
        moduleId: 'b2en-urban-nature',
        title: 'Bringing Nature Back to Cities',
        source: 'Original article — Level B2',
        paragraphs: [
            'For most of human history, cities and nature were seen as opposites. The city was a place of concrete, commerce and crowds; nature was something that existed beyond its walls, in the countryside. Today, however, urban planners and citizens alike are increasingly convinced that the two can, and must, be reconciled.',
            'The reasons are both practical and profound. As more than half of the world\'s population now lives in urban areas, the quality of city life has become a matter of enormous importance. Research has repeatedly shown that access to green spaces reduces stress, encourages physical activity and even improves mental health. Trees and plants also clean the air, lower temperatures and help cities cope with heavy rainfall.',
            'Around the world, innovative projects are putting these ideas into practice. Some cities have transformed disused railway lines into elevated parks, while others have planted "urban forests" or installed gardens on the roofs of buildings. A few ambitious schemes have even covered entire tower blocks in vegetation, creating green oases in the heart of dense neighbourhoods.',
            'Such projects are not without their critics. Some argue that the money would be better spent on housing or public transport, while others worry that "greening" can drive up property prices and force out poorer residents — a phenomenon sometimes called "green gentrification". These concerns deserve serious attention if the benefits of urban nature are to be shared by all.',
            'Nevertheless, the direction of travel seems clear. As the climate crisis intensifies and cities continue to grow, bringing nature back into the urban environment is no longer a luxury but a necessity. The cities of the future, it seems, may be greener, cooler and altogether more pleasant places to live.',
        ],
    },
    {
        level: 'B2', unit: 2,
        moduleId: 'b2en-space-exploration',
        title: 'The New Age of Space Exploration',
        source: 'Original article — Level B2',
        paragraphs: [
            'For much of the twentieth century, space exploration was the exclusive domain of a handful of powerful governments, locked in a fierce competition for prestige. Today, the landscape has changed dramatically. Private companies, backed by ambitious entrepreneurs, have entered the field, transforming the economics and the ambitions of space travel.',
            'The most visible consequence has been a sharp fall in the cost of reaching orbit. Reusable rockets, once considered impossible, now return safely to Earth to be used again, dramatically reducing the price of each launch. This has opened space to a far wider range of activities, from satellite networks providing global internet access to the early stages of space tourism.',
            'Alongside these commercial ventures, the old dream of human exploration has been revived. Space agencies are once again planning missions to the Moon, this time with the goal of establishing a permanent presence, and they speak seriously of sending astronauts to Mars within a few decades. Such missions would represent the greatest journeys in human history.',
            'Yet this new age raises difficult questions. Who owns the resources of the Moon or the asteroids? Should vast sums be spent on space while urgent problems remain unsolved on Earth? And how can we prevent the orbit around our planet from filling with dangerous debris? As humanity reaches further into the cosmos, these issues will demand thoughtful answers.',
            'Whatever the challenges, the renewed enthusiasm for exploration reflects something deep in human nature: the desire to push beyond known limits and to discover what lies beyond the horizon. The coming decades may well determine whether humanity becomes, for the first time, a truly spacefaring species.',
        ],
    },
    {
        level: 'B2', unit: 2,
        moduleId: 'b2en-future-of-money',
        title: 'The Changing Face of Money',
        source: 'Original article — Level B2',
        paragraphs: [
            'Money is one of humanity\'s oldest and most powerful inventions, yet the form it takes is constantly evolving. From shells and precious metals to paper notes and plastic cards, each generation has reshaped the way we store and exchange value. Today, we may be living through the most significant transformation of all: the gradual disappearance of physical cash.',
            'In many countries, coins and banknotes are used less and less. A growing number of transactions are carried out instantly with a smartphone or a contactless card. For consumers, this offers obvious convenience, while for businesses it can mean lower costs and greater security. In some societies, it is now possible to go for weeks without ever touching physical money.',
            'At the same time, entirely new forms of money have emerged. Cryptocurrencies, which exist only in digital form and are controlled by no single government, have attracted both enthusiastic supporters and fierce critics. Some see them as the future of finance; others warn that they are unstable, frequently used for crime, and harmful to the environment because of the energy they consume.',
            'These developments bring real risks alongside their benefits. A cashless society could exclude elderly or poorer people who lack access to technology, and it gives banks and companies an unprecedented record of our spending habits. The question of who controls our financial data, and how it is used, is becoming increasingly urgent.',
            'It is impossible to say exactly what money will look like in fifty years. What seems certain, however, is that the comfortable familiarity of notes and coins is fading. As money becomes ever more digital, societies will need to ensure that the systems they build are fair, secure and open to all.',
        ],
    },
    {
        level: 'B2', unit: 3,
        moduleId: 'b2en-overtourism',
        title: 'The Problem of Overtourism',
        source: 'Original article — Level B2',
        paragraphs: [
            'Travel has never been easier or cheaper than it is today. Budget airlines, online booking and social media have inspired millions of people to explore the world. Yet this explosion in tourism, while bringing undeniable benefits, has created a serious problem in many of the world\'s most beautiful destinations: a phenomenon now widely known as "overtourism".',
            'The effects can be seen in famous cities and natural wonders alike. Historic streets become so crowded that residents struggle to go about their daily lives. House prices rise as flats are converted into holiday rentals, forcing local people out of their own neighbourhoods. Fragile landscapes and ancient monuments suffer damage that may take centuries to repair, if it can be repaired at all.',
            'For the communities affected, the situation is deeply complicated. Tourism brings vital income and employment, and few places would wish to lose it entirely. Yet when visitor numbers grow beyond a certain point, the costs begin to outweigh the benefits, and the very qualities that attracted tourists in the first place start to disappear.',
            'In response, some destinations have begun to take action. A number of cities have introduced tourist taxes, limited the number of visitors to popular sites, or restricted the growth of holiday rentals. Others are working to attract visitors to less famous areas, spreading the benefits more evenly and relieving pressure on the most crowded places.',
            'Ultimately, the challenge is to find a form of tourism that is sustainable for both visitors and hosts. This will require a change of attitude from travellers, who must learn to explore more responsibly, as well as careful planning by governments. Done well, tourism can enrich the world; done badly, it risks destroying the very treasures it seeks to celebrate.',
        ],
    },
    {
        level: 'B2', unit: 3,
        moduleId: 'b2en-genetic-ethics',
        title: 'The Ethics of Genetic Engineering',
        source: 'Original article — Level B2',
        paragraphs: [
            'Few areas of science advance as rapidly, or raise as many difficult questions, as genetics. In recent years, powerful new tools have given researchers the ability to edit the genetic code of living things with remarkable precision. The potential applications, from curing inherited diseases to increasing food production, are extraordinary — and so are the ethical dilemmas they create.',
            'The medical possibilities are perhaps the most exciting. Scientists hope that gene editing could one day eliminate devastating conditions that have caused suffering for generations. By correcting a single faulty gene, it may become possible to treat illnesses that were previously considered incurable, transforming countless lives in the process.',
            'Yet the same technology raises profound concerns. If we can edit genes to prevent disease, where do we draw the line? Should parents be allowed to choose the height, appearance or intelligence of their children? Critics warn of a future in which genetic advantages can be bought, deepening the divide between rich and poor and reviving dangerous ideas about "improving" the human race.',
            'There is also the question of unintended consequences. The natural world is the product of billions of years of evolution, and our understanding of it, however advanced, remains incomplete. Changes that seem beneficial today could have unexpected effects on future generations or on the wider environment — effects that, once introduced, might be impossible to reverse.',
            'For these reasons, many scientists themselves are calling for caution and clear international rules. The challenge for society is not simply what we are able to do, but what we ought to do. As our power over the very building blocks of life continues to grow, the wisdom with which we use that power will matter more than ever.',
        ],
    },
];
