import type { Course } from '../../../types/courses';

export const courseA1: Course = {
        level: 'A1',
        title: 'Les Bases',
        description: 'Construisez votre premier vocabulaire anglais et maîtrisez les règles de grammaire essentielles.',
        color: 'var(--course-a1)',
        textColor: 'var(--level-a1-text)',
        units: [
            { number: 1, title: 'Premiers Mots' },
            { number: 2, title: 'Grammaire Fondamentale' },
            { number: 3, title: 'Vie Quotidienne' },
        ],
        steps: [
            // Unit 1 — Premiers Mots
            { id: 'a1en-greetings',       title: 'Salutations & Essentiels',     module: 'vocabulary', type: 'vocabulary', contentId: 'greetings-basics',       path: '/vocabulary/greetings-basics',         unit: 1 },
            { id: 'a1en-numbers',         title: 'Les Chiffres (1–100)',          module: 'vocabulary', type: 'vocabulary', contentId: 'numbers-time',            path: '/vocabulary/numbers-time',             unit: 1 },
            { id: 'a1en-days-months',     title: 'Jours & Mois',                  module: 'vocabulary', type: 'vocabulary', contentId: 'days-months',             path: '/vocabulary/days-months',              unit: 1 },
            { id: 'a1en-colors',          title: 'Couleurs & Descriptions',       module: 'vocabulary', type: 'vocabulary', contentId: 'colors-descriptions',     path: '/vocabulary/colors-descriptions',      unit: 1 },
            { id: 'a1en-family',          title: 'Famille & Relations',           module: 'vocabulary', type: 'vocabulary', contentId: 'family-relationships',    path: '/vocabulary/family-relationships',     unit: 1 },
            { id: 'a1en-nationalities',   title: 'Nationalités & Pays',           module: 'vocabulary', type: 'vocabulary', contentId: 'nationalities',           path: '/vocabulary/nationalities',            unit: 1 },
            { id: 'a1en-phrases-intro',   title: 'Se présenter',                  module: 'lectures', type: 'phrases',    contentId: 'introducing-yourself',    path: '/lectures/phrases/introducing-yourself', unit: 1 },
            { id: 'a1en-phrases-conv',    title: 'Conversation quotidienne',      module: 'lectures', type: 'phrases',    contentId: 'everyday-conversation',   path: '/lectures/phrases/everyday-conversation', unit: 1 },
            // Unit 2 — Grammaire Fondamentale
            { id: 'a1en-articles',        title: 'Les Articles en Anglais',       module: 'lectures', type: 'grammar',    contentId: 'en-articles',             path: '/lectures/grammar/en-articles',        unit: 2 },
            { id: 'a1en-present',         title: 'Le Présent Simple et Continu',  module: 'lectures', type: 'grammar',    contentId: 'en-present-simple',       path: '/lectures/grammar/en-present-simple',  unit: 2 },
            { id: 'a1en-plurals',         title: 'Pluriels & Dénombrables',       module: 'lectures', type: 'grammar',    contentId: 'en-plurals-nouns',        path: '/lectures/grammar/en-plurals-nouns',   unit: 2 },
            { id: 'a1en-questions',       title: 'Poser des Questions',           module: 'lectures', type: 'grammar',    contentId: 'en-questions',            path: '/lectures/grammar/en-questions',       unit: 2 },
            { id: 'a1en-negation',        title: 'La Négation',                   module: 'lectures', type: 'grammar',    contentId: 'en-negation',             path: '/lectures/grammar/en-negation',        unit: 2 },
            { id: 'a1en-can',             title: 'Can / Can\'t',                  module: 'lectures', type: 'grammar',    contentId: 'en-can-modals',           path: '/lectures/grammar/en-can-modals',      unit: 2 },
            { id: 'a1en-tobe',            title: 'Verbe : to be',                 module: 'verbs', type: 'verbs',      contentId: 'to-be',                   path: '/verbs/to-be/table',                   unit: 2 },
            { id: 'a1en-tohave',          title: 'Verbe : to have',               module: 'verbs', type: 'verbs',      contentId: 'to-have',                 path: '/verbs/to-have/table',                 unit: 2 },
            // Unit 3 — Vie Quotidienne
            { id: 'a1en-food',            title: 'Nourriture & Boissons',         module: 'vocabulary', type: 'vocabulary', contentId: 'food-drinks',             path: '/vocabulary/food-drinks',              unit: 3 },
            { id: 'a1en-body',            title: 'Corps & Santé',                 module: 'vocabulary', type: 'vocabulary', contentId: 'body-health',             path: '/vocabulary/body-health',              unit: 3 },
            { id: 'a1en-home',            title: 'Maison & Logement',             module: 'vocabulary', type: 'vocabulary', contentId: 'home-living',             path: '/vocabulary/home-living',              unit: 3 },
            { id: 'a1en-clothing',        title: 'Vêtements & Accessoires',       module: 'vocabulary', type: 'vocabulary', contentId: 'clothing-accessories',    path: '/vocabulary/clothing-accessories',     unit: 3 },
            { id: 'a1en-transport',       title: 'Transport & Déplacements',      module: 'vocabulary', type: 'vocabulary', contentId: 'transport-basics',        path: '/vocabulary/transport-basics',         unit: 3 },
            { id: 'a1en-city',            title: 'Lieux de la Ville',             module: 'vocabulary', type: 'vocabulary', contentId: 'city-places',             path: '/vocabulary/city-places',              unit: 3 },
            { id: 'a1en-seasons',         title: 'Saisons & Météo',               module: 'vocabulary', type: 'vocabulary', contentId: 'seasons-weather',         path: '/vocabulary/seasons-weather',          unit: 3 },
            { id: 'a1en-phrases-cafe',    title: 'Au café',                       module: 'lectures', type: 'phrases',    contentId: 'at-the-cafe',             path: '/lectures/phrases/at-the-cafe',        unit: 3 },
            { id: 'a1en-phrases-rest',    title: 'Au restaurant',                 module: 'lectures', type: 'phrases',    contentId: 'at-the-restaurant',       path: '/lectures/phrases/at-the-restaurant',  unit: 3 },
            { id: 'a1en-phrases-shop',    title: 'Faire ses courses',             module: 'lectures', type: 'phrases',    contentId: 'shopping-basics',         path: '/lectures/phrases/shopping-basics',    unit: 3 },
            { id: 'a1en-phrases-daily',   title: 'Routine quotidienne',           module: 'lectures', type: 'phrases',    contentId: 'daily-routine',           path: '/lectures/phrases/daily-routine',      unit: 3 },
            { id: 'a1en-phrases-dir',     title: 'Demander son chemin',           module: 'lectures', type: 'phrases',    contentId: 'asking-directions',       path: '/lectures/phrases/asking-directions',  unit: 3 },
            { id: 'a1en-phrases-around',  title: 'Se déplacer',                   module: 'lectures', type: 'phrases',    contentId: 'getting-around',          path: '/lectures/phrases/getting-around',     unit: 3 },
            { id: 'a1en-phrases-class',   title: 'Phrases de classe',             module: 'lectures', type: 'phrases',    contentId: 'classroom-survival',      path: '/lectures/phrases/classroom-survival', unit: 3 },
            { id: 'a1en-reading-school',  title: 'Lecture : First Day at School', module: 'lectures', type: 'reading',    contentId: 'a1en-first-day',          path: '/lectures/reading/a1en-first-day',     unit: 3 },
            { id: 'a1en-reading-city',    title: 'Lecture : My City',             module: 'lectures', type: 'reading',    contentId: 'a1en-my-city',            path: '/lectures/reading/a1en-my-city',       unit: 3 },
            { id: 'a1en-reading-family',  title: 'Lecture : My Family',           module: 'lectures', type: 'reading',    contentId: 'a1en-my-family',          path: '/lectures/reading/a1en-my-family',     unit: 3 },
            { id: 'a1en-reading-day',     title: 'Lecture : My Day',              module: 'lectures', type: 'reading',    contentId: 'a1en-my-day',             path: '/lectures/reading/a1en-my-day',        unit: 3 },
            { id: 'a1en-reading-park',    title: 'Lecture : A Day at the Park',   module: 'lectures', type: 'reading',    contentId: 'a1en-the-park',           path: '/lectures/reading/a1en-the-park',      unit: 3 },
            { id: 'a1en-reading-pet',     title: 'Lecture : My Pet',              module: 'lectures', type: 'reading',    contentId: 'a1en-my-pet',             path: '/lectures/reading/a1en-my-pet',        unit: 3 },
            { id: 'a1en-reading-birthday',title: 'Lecture : My Birthday Party',   module: 'lectures', type: 'reading',    contentId: 'a1en-birthday-party',     path: '/lectures/reading/a1en-birthday-party', unit: 3 },
            { id: 'a1en-reading-zoo',     title: 'Lecture : A Visit to the Zoo',  module: 'lectures', type: 'reading',    contentId: 'a1en-at-the-zoo',         path: '/lectures/reading/a1en-at-the-zoo',    unit: 3 },
            { id: 'a1en-reading-rainy',   title: 'Lecture : A Rainy Day',         module: 'lectures', type: 'reading',    contentId: 'a1en-a-rainy-day',        path: '/lectures/reading/a1en-a-rainy-day',   unit: 3 },
            { id: 'a1en-reading-myschool',title: 'Lecture : My School',           module: 'lectures', type: 'reading',    contentId: 'a1en-my-school',          path: '/lectures/reading/a1en-my-school',     unit: 3 },
        ],
    };
