import type { Course } from '../../../types/courses';

export const courseA2: Course = {
        level: 'A2',
        title: "L'Anglais du Quotidien",
        description: 'Élargissez votre vocabulaire et maîtrisez les temps du passé et du futur.',
        color: 'var(--course-a2)',
        textColor: 'var(--level-a2-text)',
        units: [
            { number: 1, title: 'Monde & Personnes' },
            { number: 2, title: 'Passé & Futur' },
            { number: 3, title: 'Interactions Sociales' },
            { number: 4, title: 'FINAL EXAM', kind: 'final-exam' },
        ],
        steps: [
            // Unit 1 — Monde & Personnes
            { id: 'a2en-work',            title: 'Travail & Professions',        module: 'vocabulary', type: 'vocabulary', contentId: 'work-professions',        path: '/vocabulary/work-professions',         unit: 1 },
            { id: 'a2en-school',          title: 'École & Éducation',            module: 'vocabulary', type: 'vocabulary', contentId: 'school-education',        path: '/vocabulary/school-education',         unit: 1 },
            { id: 'a2en-weather',         title: 'Météo & Nature',               module: 'vocabulary', type: 'vocabulary', contentId: 'weather-nature',          path: '/vocabulary/weather-nature',           unit: 1 },
            { id: 'a2en-sports',          title: 'Sports & Loisirs',             module: 'vocabulary', type: 'vocabulary', contentId: 'sports-hobbies',          path: '/vocabulary/sports-hobbies',           unit: 1 },
            { id: 'a2en-food-culture',    title: 'Culture culinaire',            module: 'vocabulary', type: 'vocabulary', contentId: 'food-culture',            path: '/vocabulary/food-culture',             unit: 1 },
            { id: 'a2en-personality',     title: 'Personnalité & Caractère',     module: 'vocabulary', type: 'vocabulary', contentId: 'personality-character',   path: '/vocabulary/personality-character',    unit: 1 },
            { id: 'a2en-celebrations',    title: 'Fêtes & Événements',           module: 'vocabulary', type: 'vocabulary', contentId: 'celebrations-events',     path: '/vocabulary/celebrations-events',      unit: 1 },
            { id: 'a2en-seasons-act',     title: 'Saisons & Activités',          module: 'vocabulary', type: 'vocabulary', contentId: 'seasons-activities',      path: '/vocabulary/seasons-activities',       unit: 1 },
            { id: 'a2-exam-1', title: 'Examen de l’unité 1', module: 'exams', type: 'exams', contentId: 'a2-exam-1', path: '/exams/1', unit: 1, available: false, isDemo: false },
            // Unit 2 — Passé & Futur
            { id: 'a2en-past',            title: 'Les Temps du Passé',           module: 'lectures', type: 'grammar',    contentId: 'en-past-tenses',          path: '/lectures/grammar/en-past-tenses',     unit: 2 },
            { id: 'a2en-present-perf',    title: 'Le Present Perfect',           module: 'lectures', type: 'grammar',    contentId: 'en-present-perfect',      path: '/lectures/grammar/en-present-perfect', unit: 2 },
            { id: 'a2en-future',          title: 'Le Futur en Anglais',          module: 'lectures', type: 'grammar',    contentId: 'en-future',               path: '/lectures/grammar/en-future',          unit: 2 },
            { id: 'a2en-comparatives',    title: 'Comparatifs & Superlatifs',    module: 'lectures', type: 'grammar',    contentId: 'en-comparatives',         path: '/lectures/grammar/en-comparatives',    unit: 2 },
            { id: 'a2en-todo',            title: 'Verbe : to do',                module: 'verbs', type: 'verbs',      contentId: 'to-do',                   path: '/verbs/to-do/table',                   unit: 2 },
            { id: 'a2en-reading-london',  title: 'Lecture : A Weekend in London',module: 'lectures', type: 'reading',    contentId: 'a2en-weekend-trip',       path: '/lectures/reading/a2en-weekend-trip',  unit: 2 },
            { id: 'a2-exam-2', title: 'Examen de l’unité 2', module: 'exams', type: 'exams', contentId: 'a2-exam-2', path: '/exams/2', unit: 2, available: false, isDemo: false },
            // Unit 3 — Interactions Sociales
            { id: 'a2en-shopping',        title: 'Shopping & Argent',            module: 'vocabulary', type: 'vocabulary', contentId: 'shopping-money',          path: '/vocabulary/shopping-money',           unit: 3 },
            { id: 'a2en-animals',         title: 'Les Animaux',                  module: 'vocabulary', type: 'vocabulary', contentId: 'animals',                 path: '/vocabulary/animals',                  unit: 3 },
            { id: 'a2en-health',          title: 'Santé & Médecin',              module: 'vocabulary', type: 'vocabulary', contentId: 'health-doctor',           path: '/vocabulary/health-doctor',            unit: 3 },
            { id: 'a2en-transport-travel',title: 'Voyages & Transport',          module: 'vocabulary', type: 'vocabulary', contentId: 'transport-travel',        path: '/vocabulary/transport-travel',         unit: 3 },
            { id: 'a2en-modal-verbs',     title: 'Les Verbes Modaux',            module: 'lectures', type: 'grammar',    contentId: 'en-modal-verbs',          path: '/lectures/grammar/en-modal-verbs',     unit: 3 },
            { id: 'a2en-verb-patterns',   title: 'Gérondif vs Infinitif',        module: 'lectures', type: 'grammar',    contentId: 'en-verb-patterns',        path: '/lectures/grammar/en-verb-patterns',   unit: 3 },
            { id: 'a2en-on-phone',        title: 'Au Téléphone',                 module: 'lectures', type: 'phrases',    contentId: 'on-the-phone',            path: '/lectures/phrases/on-the-phone',       unit: 3 },
            { id: 'a2en-phrases-feel',    title: 'Exprimer ses sentiments',      module: 'lectures', type: 'phrases',    contentId: 'expressing-feelings',     path: '/lectures/phrases/expressing-feelings', unit: 3 },
            { id: 'a2en-phrases-disagree',title: 'Exprimer un désaccord',        module: 'lectures', type: 'phrases',    contentId: 'expressing-disagreement', path: '/lectures/phrases/expressing-disagreement', unit: 3 },
            { id: 'a2en-phrases-hotel',   title: "À l'hôtel",                    module: 'lectures', type: 'phrases',    contentId: 'at-the-hotel',            path: '/lectures/phrases/at-the-hotel',       unit: 3 },
            { id: 'a2en-phrases-doctor',  title: 'Chez le médecin',              module: 'lectures', type: 'phrases',    contentId: 'at-the-doctor',           path: '/lectures/phrases/at-the-doctor',      unit: 3 },
            { id: 'a2en-phrases-plans',   title: 'Prendre des rendez-vous',      module: 'lectures', type: 'phrases',    contentId: 'making-plans',            path: '/lectures/phrases/making-plans',       unit: 3 },
            { id: 'a2en-phrases-market',  title: 'Au marché',                    module: 'lectures', type: 'phrases',    contentId: 'at-the-market',           path: '/lectures/phrases/at-the-market',      unit: 3 },
            { id: 'a2en-phrases-postcard',title: 'Écrire une carte postale',     module: 'lectures', type: 'phrases',    contentId: 'writing-a-postcard',      path: '/lectures/phrases/writing-a-postcard', unit: 3 },
            { id: 'a2en-phrases-health',  title: 'Parler de sa santé',           module: 'lectures', type: 'phrases',    contentId: 'talking-about-health',    path: '/lectures/phrases/talking-about-health', unit: 3 },
            { id: 'a2en-reading-job',     title: "Lecture : Sophie's Interview", module: 'lectures', type: 'reading',    contentId: 'a2en-job-interview',      path: '/lectures/reading/a2en-job-interview', unit: 3 },
            { id: 'a2en-reading-shopping', title: 'Lecture : A Shopping Trip',    module: 'lectures', type: 'reading',    contentId: 'a2en-shopping-trip',      path: '/lectures/reading/a2en-shopping-trip', unit: 3 },
            { id: 'a2en-reading-holiday', title: 'Lecture : Planning a Holiday',  module: 'lectures', type: 'reading',    contentId: 'a2en-holiday-plans',      path: '/lectures/reading/a2en-holiday-plans', unit: 3 },
            { id: 'a2en-reading-flatmate',title: 'Lecture : A New Flatmate',      module: 'lectures', type: 'reading',    contentId: 'a2en-new-flatmate',       path: '/lectures/reading/a2en-new-flatmate',  unit: 3 },
            { id: 'a2en-reading-lost',    title: 'Lecture : Lost in a New Town',  module: 'lectures', type: 'reading',    contentId: 'a2en-lost-in-town',       path: '/lectures/reading/a2en-lost-in-town',  unit: 3 },
            { id: 'a2en-reading-cooking', title: 'Lecture : Cooking for Friends', module: 'lectures', type: 'reading',    contentId: 'a2en-cooking-dinner',     path: '/lectures/reading/a2en-cooking-dinner', unit: 3 },
            { id: 'a2en-reading-concert', title: 'Lecture : The Concert',         module: 'lectures', type: 'reading',    contentId: 'a2en-the-concert',        path: '/lectures/reading/a2en-the-concert',   unit: 3 },
            { id: 'a2en-reading-moving',  title: 'Lecture : Moving House',        module: 'lectures', type: 'reading',    contentId: 'a2en-moving-house',       path: '/lectures/reading/a2en-moving-house',  unit: 3 },
            { id: 'a2en-reading-summer',  title: 'Lecture : My First Summer Job', module: 'lectures', type: 'reading',    contentId: 'a2en-summer-job',         path: '/lectures/reading/a2en-summer-job',    unit: 3 },
            { id: 'a2-exam-3', title: 'Examen de l’unité 3', module: 'exams', type: 'exams', contentId: 'a2-exam-3', path: '/exams/3', unit: 3, available: false, isDemo: false },
            // Level exam
            { id: 'a2-exam-final', title: 'Examen final A2', module: 'exams', type: 'exams', contentId: 'a2-exam-final', path: '/exams/final', unit: 4, available: false, isDemo: false },
        ],
    };
