import type { GrammarLesson } from '../../../types/lectures/grammar';

export const grammarA1: GrammarLesson[] = [
    {
        unit: 1,
        id: 'articles',
        title: 'Articles',
        level: 'A1',
        description: 'Definite and indefinite articles — the building blocks of French nouns',
        icon: '📖',
        color: '#2563EB',
        sections: [
            {
                title: 'Definite Articles',
                explanation: 'Use le (masc. singular), la (fem. singular), l\' (before vowel/h), les (plural) to refer to specific nouns or nouns in general.',
                examples: [
                    { french: 'le chat', english: 'the cat' },
                    { french: 'la maison', english: 'the house' },
                    { french: 'l\'école', english: 'the school' },
                    { french: 'les enfants', english: 'the children (or children in general)' },
                    { french: 'J\'aime le chocolat.', english: 'I love chocolate.' },
                ],
            },
            {
                title: 'Indefinite Articles',
                explanation: 'Use un (masc. singular), une (fem. singular), des (plural) for non-specific nouns — equivalent to \'a\', \'an\', \'some\'.',
                examples: [
                    { french: 'un livre', english: 'a book' },
                    { french: 'une idée', english: 'an idea' },
                    { french: 'des amis', english: '(some) friends' },
                    { french: 'J\'ai un chien.', english: 'I have a dog.' },
                ],
            },
            {
                title: 'Contracted Articles (du, au, aux)',
                explanation: 'de + le → du; de + les → des; à + le → au; à + les → aux. La and l\' do not contract.',
                examples: [
                    { french: 'Je parle du problème.', english: 'I\'m talking about the problem.' },
                    { french: 'Il va au cinéma.', english: 'He\'s going to the cinema.' },
                    { french: 'Elle parle aux enfants.', english: 'She\'s speaking to the children.' },
                    { french: 'Il vient de la gare.', english: 'He\'s coming from the station.' },
                ],
            },
        ],
        exercises: [
            { sentence: "Je voudrais ___ café, s'il vous plaît.", answer: 'un', hint: 'indefinite article, masculine singular' },
            { sentence: "___ enfants aiment le chocolat.", answer: 'Les', hint: 'definite article, plural' },
            { sentence: "Elle a ___ idée brillante.", answer: 'une', hint: 'indefinite article, feminine singular' },
            { sentence: "Il va ___ cinéma ce soir.", answer: 'au', hint: 'à + le → contraction' },
            { sentence: "Je parle ___ problème avec elle.", answer: 'du', hint: 'de + le → contraction' },
            { sentence: "___ école est fermée aujourd'hui.", answer: "L'", hint: "definite article before a vowel" },
        ],
    },
    {
        unit: 1,
        id: 'noun-gender',
        title: 'Noun Gender & Number',
        level: 'A1',
        description: 'Every French noun is masculine or feminine — learn the key patterns',
        icon: '⚖️',
        color: '#059669',
        sections: [
            {
                title: 'Grammatical Gender',
                explanation: 'All French nouns have a gender (masculine or feminine). There are patterns but many must be memorised. Tip: learn each noun with its article.',
                examples: [
                    { french: 'le soleil (masc.)', english: 'the sun' },
                    { french: 'la lune (fem.)', english: 'the moon' },
                    { french: 'le problème (masc.)', english: 'the problem' },
                    { french: 'la décision (fem.)', english: 'the decision' },
                    { french: 'un homme, une femme', english: 'a man, a woman' },
                ],
            },
            {
                title: 'Common Masculine Endings',
                explanation: 'Nouns ending in -age, -ment, -eau, -isme, -oir are usually masculine.',
                examples: [
                    { french: 'le voyage', english: 'the journey' },
                    { french: 'le gouvernement', english: 'the government' },
                    { french: 'le bureau', english: 'the desk/office' },
                    { french: 'le réalisme', english: 'realism' },
                ],
            },
            {
                title: 'Common Feminine Endings',
                explanation: 'Nouns ending in -tion, -sion, -té, -ée, -ure, -ance, -ence are usually feminine.',
                examples: [
                    { french: 'la nation', english: 'the nation' },
                    { french: 'la liberté', english: 'freedom' },
                    { french: 'la durée', english: 'the duration' },
                    { french: 'la patience', english: 'patience' },
                ],
            },
            {
                title: 'Forming the Plural',
                explanation: 'Most nouns add -s to form the plural (silent). Nouns ending in -eau add -x; nouns ending in -al change to -aux.',
                examples: [
                    { french: 'un chat → des chats', english: 'a cat → cats' },
                    { french: 'un bureau → des bureaux', english: 'a desk → desks' },
                    { french: 'un journal → des journaux', english: 'a newspaper → newspapers' },
                    { french: 'un œil → des yeux (irregular)', english: 'an eye → eyes' },
                ],
            },
        ],
        exercises: [
            { sentence: "C'est ___ voyage inoubliable.", answer: 'un', hint: 'indefinite article, masculine (voyage ends in -age)' },
            { sentence: "___ liberté est un droit fondamental.", answer: 'La', hint: 'definite article, feminine (liberté ends in -té)' },
            { sentence: "Il a acheté un journal. Les ___ sont sur la table.", answer: 'journaux', hint: '-al → -aux in the plural' },
            { sentence: "Le ___ (desk) est en bois.", answer: 'bureau', hint: 'masculine noun ending in -eau' },
            { sentence: "La ___ (decision) a été prise.", answer: 'décision', hint: 'feminine noun ending in -ion' },
            { sentence: "Un bureau → des ___.", answer: 'bureaux', hint: '-eau nouns add -x in the plural' },
        ],
    },
    {
        unit: 2,
        id: 'telling-time',
        title: 'Telling the Time',
        level: 'A1',
        description: 'Ask and say what time it is — hours, half-hours, and quarter-hours',
        icon: '🕐',
        color: '#D97706',
        sections: [
            {
                title: 'Asking and Saying the Time',
                explanation: 'Use "Quelle heure est-il ?" or "Il est quelle heure ?" to ask the time. Answer with "Il est… heure(s)."',
                examples: [
                    { french: 'Quelle heure est-il ?',       english: 'What time is it?' },
                    { french: 'Il est quelle heure ?',        english: 'What time is it? (informal)' },
                    { french: 'Il est trois heures.',         english: 'It\'s three o\'clock.' },
                    { french: 'Il est midi.',                 english: 'It\'s noon.' },
                    { french: 'Il est minuit.',               english: 'It\'s midnight.' },
                ],
            },
            {
                title: 'Quarter and Half Hours',
                explanation: 'Add "et quart" (quarter past), "et demie" (half past), or "moins le quart" (quarter to) after the hour.',
                examples: [
                    { french: 'Il est deux heures et quart.',      english: 'It\'s quarter past two.' },
                    { french: 'Il est cinq heures et demie.',      english: 'It\'s half past five.' },
                    { french: 'Il est huit heures moins le quart.', english: 'It\'s quarter to eight.' },
                    { french: 'Il est onze heures moins dix.',     english: 'It\'s ten to eleven.' },
                    { french: 'Il est une heure et quart.',        english: 'It\'s quarter past one.', note: 'Note: une heure, not un heure' },
                ],
            },
            {
                title: 'Morning, Afternoon and Evening',
                explanation: 'Add "du matin", "de l\'après-midi", or "du soir" to specify AM or PM. French also uses 24-hour time in official contexts.',
                examples: [
                    { french: 'Il est neuf heures du matin.',          english: 'It\'s nine in the morning.' },
                    { french: 'Il est trois heures de l\'après-midi.', english: 'It\'s three in the afternoon.' },
                    { french: 'Il est huit heures du soir.',            english: 'It\'s eight in the evening.' },
                    { french: 'Le train part à quatorze heures.',       english: 'The train leaves at 14:00 (2pm).', note: '24-hour clock used for timetables' },
                ],
            },
            {
                title: 'Useful Time Expressions',
                explanation: 'A few extra expressions for talking about time.',
                examples: [
                    { french: 'À quelle heure… ?',           english: 'At what time…?' },
                    { french: 'vers deux heures',             english: 'around two o\'clock' },
                    { french: 'Il est trois heures pile.',    english: 'It\'s exactly three o\'clock.' },
                    { french: 'à l\'heure',                  english: 'on time' },
                    { french: 'en retard / en avance',        english: 'late / early' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Il est ___ heures et quart. (9)', answer: 'neuf',   hint: 'spell out the number in French' },
            { sentence: 'Il est deux heures et ___.',       answer: 'demie', hint: 'half past' },
            { sentence: '___ heure est-il ?',               answer: 'Quelle', hint: 'asking the time' },
            { sentence: 'Il est minuit ___ cinq.',          answer: 'et',    hint: 'five past midnight — use et before small minutes' },
            { sentence: 'Il est onze heures ___ le quart.', answer: 'moins', hint: 'quarter to eleven' },
            { sentence: 'Le rendez-vous est ___ quinze heures. (at)', answer: 'à', hint: 'preposition for "at a time"' },
        ],
    },
    {
        unit: 3,
        id: 'possessive-adjectives',
        title: 'Possessive Adjectives',
        level: 'A1',
        description: 'Express ownership — my, your, his, her, our, their in French',
        icon: '🏷️',
        color: '#7C3AED',
        sections: [
            {
                title: 'Singular Possessors: mon / ton / son',
                explanation: 'For one possessor, use mon/ma/mes (my), ton/ta/tes (your), son/sa/ses (his/her/its). The ending agrees with the noun, not the possessor — son can mean his or her depending on context.',
                examples: [
                    { french: 'mon frère, ma sœur, mes parents',      english: 'my brother, my sister, my parents' },
                    { french: 'ton appartement, ta voiture, tes amis', english: 'your flat, your car, your friends' },
                    { french: 'son chien, sa maison, ses enfants',     english: 'his/her dog, his/her house, his/her children' },
                    { french: 'C\'est son livre à elle.',              english: 'It\'s her book.', note: 'Add à lui / à elle to clarify gender of possessor' },
                ],
            },
            {
                title: 'Plural Possessors: notre / votre / leur',
                explanation: 'For multiple possessors, use notre/nos (our), votre/vos (your plural/formal), leur/leurs (their). Notre and votre have one form for masc./fem. singular, nos/vos for plural.',
                examples: [
                    { french: 'notre maison, nos enfants',         english: 'our house, our children' },
                    { french: 'votre appartement, vos clés',       english: 'your flat, your keys (formal/plural)' },
                    { french: 'leur jardin, leurs affaires',       english: 'their garden, their things' },
                    { french: 'C\'est notre professeur.',          english: 'He\'s/She\'s our teacher.' },
                ],
            },
            {
                title: 'mon Before Feminine Nouns Starting with a Vowel',
                explanation: 'When a feminine noun starts with a vowel or silent h, use mon/ton/son instead of ma/ta/sa to avoid the awkward vowel clash.',
                examples: [
                    { french: 'mon amie (not ma amie)',     english: 'my friend (fem.)', note: 'amie starts with a vowel' },
                    { french: 'ton école (not ta école)',   english: 'your school' },
                    { french: 'son histoire (not sa histoire)', english: 'his/her story', note: 'histoire starts with silent h' },
                    { french: 'mon adresse',                english: 'my address' },
                ],
            },
        ],
        exercises: [
            { sentence: '___ livre est sur la table. (my, masc.)',          answer: 'Mon',   hint: 'masculine singular noun' },
            { sentence: 'C\'est ___ maison. (her)',                         answer: 'sa',    hint: 'maison is feminine' },
            { sentence: '___ amie s\'appelle Claire. (my)',                 answer: 'Mon',   hint: 'feminine noun starting with a vowel' },
            { sentence: 'Nous avons perdu ___ clés. (our)',                 answer: 'nos',   hint: 'plural noun, plural possessor' },
            { sentence: 'Ils ont vendu ___ appartement. (their)',           answer: 'leur',  hint: 'singular noun, plural possessor' },
            { sentence: 'Est-ce que c\'est ___ stylo ? (your, informal)',   answer: 'ton',   hint: 'masculine singular, informal' },
        ],
    },
    {
        unit: 3,
        id: 'prepositions-place',
        title: 'Prepositions of Place',
        level: 'A1',
        description: 'Describe where things are — in, on, under, in front of, next to…',
        icon: '📍',
        color: '#0891B2',
        sections: [
            {
                title: 'Simple Prepositions',
                explanation: 'These single-word prepositions describe basic location. They are followed directly by the noun.',
                examples: [
                    { french: 'Le chat est dans la boîte.',       english: 'The cat is in the box.' },
                    { french: 'Le livre est sur la table.',        english: 'The book is on the table.' },
                    { french: 'Les chaussures sont sous le lit.',  english: 'The shoes are under the bed.' },
                    { french: 'La voiture est devant la maison.',  english: 'The car is in front of the house.' },
                    { french: 'Le jardin est derrière la maison.', english: 'The garden is behind the house.' },
                ],
            },
            {
                title: 'Compound Prepositions',
                explanation: 'These multi-word prepositions are followed by de, which contracts with le → du and les → des.',
                examples: [
                    { french: 'La boulangerie est à côté de la banque.',   english: 'The bakery is next to the bank.' },
                    { french: 'La poste est en face de l\'hôtel.',         english: 'The post office is opposite the hotel.' },
                    { french: 'J\'habite près du parc.',                   english: 'I live near the park.', note: 'près de + le = près du' },
                    { french: 'La gare est loin du centre-ville.',         english: 'The station is far from the town centre.' },
                    { french: 'Le café est entre la banque et la pharmacie.', english: 'The café is between the bank and the pharmacy.' },
                ],
            },
            {
                title: 'Using il y a to Describe a Room',
                explanation: '"Il y a" (there is / there are) + a preposition is the key pattern for describing the layout of a room or home.',
                examples: [
                    { french: 'Il y a un bureau dans ma chambre.',            english: 'There is a desk in my bedroom.' },
                    { french: 'Il n\'y a pas de garage.',                     english: 'There is no garage.' },
                    { french: 'La télévision est en face du canapé.',         english: 'The television is opposite the sofa.' },
                    { french: 'Mon appartement est au-dessus du restaurant.', english: 'My flat is above the restaurant.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Le stylo est ___ la trousse. (in)',             answer: 'dans',         hint: 'inside something' },
            { sentence: 'La pharmacie est ___ ___ cinéma. (next to the)', answer: 'à côté du',   hint: 'à côté de + le = à côté du' },
            { sentence: 'Les enfants jouent ___ le jardin. (behind)',    answer: 'derrière',     hint: 'simple preposition, no de' },
            { sentence: 'Il habite ___ ___ école. (near the)',           answer: 'près de l\'',  hint: 'près de + l\' before a vowel' },
            { sentence: 'Le chat dort ___ la chaise. (under)',           answer: 'sous',         hint: 'simple preposition' },
            { sentence: 'La boulangerie est ___ la banque et la poste. (between)', answer: 'entre', hint: 'entre is followed by two nouns joined by et' },
        ],
    },
    {
        unit: 3,
        id: 'adjective-basics',
        title: 'Adjective Agreement & Position',
        level: 'A1',
        description: 'Make adjectives agree with their nouns and place them correctly',
        icon: '✏️',
        color: '#DC2626',
        sections: [
            {
                title: 'Gender and Number Agreement',
                explanation: 'French adjectives must match the gender (masc./fem.) and number (sing./pl.) of the noun they describe. The basic rule: add -e for feminine, -s for plural, -es for feminine plural.',
                examples: [
                    { french: 'un livre intéressant / une histoire intéressante', english: 'an interesting book / an interesting story' },
                    { french: 'des livres intéressants / des histoires intéressantes', english: 'interesting books / interesting stories' },
                    { french: 'un appartement grand / une maison grande',          english: 'a big flat / a big house' },
                    { french: 'Il est français. / Elle est française.',            english: 'He is French. / She is French.', note: '-ais → -aise for nationalities' },
                ],
            },
            {
                title: 'Position: BANGS Rule',
                explanation: 'Most adjectives come AFTER the noun. The main exceptions come BEFORE: Beauty (beau/joli), Age (vieux/jeune/nouveau), Number (premier/dernier), Goodness (bon/mauvais), Size (grand/petit/gros). Remember: BANGS.',
                examples: [
                    { french: 'une belle maison',       english: 'a beautiful house', note: 'Beauty → before' },
                    { french: 'un vieux quartier',      english: 'an old neighbourhood', note: 'Age → before' },
                    { french: 'un bon repas',           english: 'a good meal', note: 'Goodness → before' },
                    { french: 'une petite chambre',     english: 'a small bedroom', note: 'Size → before' },
                    { french: 'une voiture rouge',      english: 'a red car', note: 'Colour → after' },
                    { french: 'un homme intelligent',   english: 'an intelligent man', note: 'Most adjectives → after' },
                ],
            },
            {
                title: 'Irregular Forms Before Vowels',
                explanation: 'Beau, vieux, and nouveau change form before a masculine noun starting with a vowel or silent h.',
                examples: [
                    { french: 'un beau jardin / un bel appartement',         english: 'a beautiful garden / a beautiful flat' },
                    { french: 'un vieux château / un vieil homme',           english: 'an old castle / an old man' },
                    { french: 'un nouveau film / un nouvel an',              english: 'a new film / a new year' },
                    { french: 'une belle / vieille / nouvelle (fem. same)',  english: 'fem. forms: belle, vieille, nouvelle — no change before vowels' },
                ],
            },
        ],
        exercises: [
            { sentence: 'C\'est une maison ___ (beautiful, fem.)',                  answer: 'belle',          hint: 'beau → belle in the feminine' },
            { sentence: 'J\'ai un ___ appartement. (new, before vowel)',            answer: 'nouvel',         hint: 'nouveau → nouvel before a vowel' },
            { sentence: 'Elle a les yeux ___ (green, masc. pl.)',                  answer: 'verts',          hint: 'vert → verts in the masculine plural' },
            { sentence: 'C\'est une idée ___. (good, fem.)',                        answer: 'bonne',          hint: 'bon → bonne in the feminine' },
            { sentence: 'Nous habitons dans un ___ quartier. (old, masc. sing.)',   answer: 'vieux',          hint: 'no vowel follows, so use vieux not vieil' },
            { sentence: 'Il porte une chemise ___. (white, fem.)',                  answer: 'blanche',        hint: 'blanc → blanche in the feminine' },
        ],
    },
    {
        unit: 2,
        id: 'present-tense-er',
        title: 'Present Tense: -ER Verbs',
        level: 'A1',
        description: 'Conjugate regular -ER verbs in the present tense — the most common verb pattern in French',
        icon: '🔄',
        color: '#0891B2',
        sections: [
            {
                title: 'The -ER Paradigm',
                explanation: 'To conjugate a regular -ER verb, drop the -er ending and add: -e, -es, -e, -ons, -ez, -ent. These endings are the same for all regular -ER verbs.',
                examples: [
                    { french: 'parler → je parle, tu parles, il/elle parle', english: 'to speak → I speak, you speak, he/she speaks' },
                    { french: 'nous parlons, vous parlez, ils/elles parlent', english: 'we speak, you speak, they speak', note: 'The -ent ending is silent' },
                    { french: 'aimer → j\'aime, tu aimes, il aime', english: 'to like/love → I like, you like, he likes' },
                    { french: 'travailler → nous travaillons, vous travaillez', english: 'to work → we work, you work' },
                ],
            },
            {
                title: 'Common -ER Verbs',
                explanation: 'Most French verbs are -ER verbs. Here are the most useful ones at A1 level.',
                examples: [
                    { french: 'parler — to speak', english: 'Je parle français. — I speak French.' },
                    { french: 'aimer — to like / to love', english: 'Elle aime le chocolat. — She likes chocolate.' },
                    { french: 'habiter — to live (somewhere)', english: 'Nous habitons à Paris. — We live in Paris.' },
                    { french: 'travailler — to work', english: 'Il travaille beaucoup. — He works a lot.' },
                    { french: 'manger — to eat', english: 'Vous mangez bien. — You eat well.' },
                    { french: 'écouter — to listen', english: 'Ils écoutent la radio. — They listen to the radio.' },
                ],
            },
            {
                title: 'Spelling-change Verbs',
                explanation: 'Two subtypes have a spelling change in the nous form only: -ger verbs add an e before -ons (nous mangeons), and -cer verbs change c to ç before -ons (nous commençons). All other forms are regular.',
                examples: [
                    { french: 'manger: je mange, nous mangeons', english: 'to eat: I eat, we eat', note: '-ger verbs: add e before -ons to keep the soft g sound' },
                    { french: 'commencer: je commence, nous commençons', english: 'to start: I start, we start', note: '-cer verbs: c → ç before -ons to keep the soft c sound' },
                    { french: 'voyager: nous voyageons', english: 'to travel: we travel' },
                    { french: 'lancer: nous lançons', english: 'to throw: we throw' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Elle ___ le français à l\'université. (parler)',                answer: 'parle',       hint: '3rd person singular: drop -er, add -e' },
            { sentence: 'Nous ___ dans le 11e arrondissement. (habiter)',                answer: 'habitons',    hint: '1st person plural: drop -er, add -ons' },
            { sentence: 'Vous ___ la musique classique ? (aimer)',                       answer: 'aimez',       hint: '2nd person plural: drop -er, add -ez' },
            { sentence: 'Ils ___ ensemble dans un bureau. (travailler)',                 answer: 'travaillent', hint: '3rd person plural: drop -er, add -ent (silent)' },
            { sentence: 'Nous ___ au restaurant ce soir. (manger — spelling change)',    answer: 'mangeons',    hint: '-ger verb: add e before -ons → mangeons' },
            { sentence: 'Nous ___ à apprendre le français. (commencer — spelling change)', answer: 'commençons', hint: '-cer verb: c → ç before -ons → commençons' },
        ],
    },
    {
        unit: 3,
        id: 'demonstrative-adjectives',
        title: 'Demonstrative Adjectives',
        level: 'A1',
        description: 'Point to specific things using ce, cet, cette, ces — this, that, these, those',
        icon: '👉',
        color: '#D97706',
        sections: [
            {
                title: 'The Four Forms',
                explanation: 'French has one set of demonstrative adjectives for both "this/that" and "these/those". The form depends on the gender and number of the noun: ce (masc. sing.), cet (masc. sing. before vowel/silent h), cette (fem. sing.), ces (all plurals).',
                examples: [
                    { french: 'ce livre',          english: 'this / that book',        note: 'masc. singular — starts with a consonant' },
                    { french: 'cet hôtel',         english: 'this / that hotel',       note: 'masc. singular — starts with h (silent)' },
                    { french: 'cet avion',         english: 'this / that plane',       note: 'masc. singular — starts with a vowel' },
                    { french: 'cette maison',      english: 'this / that house',       note: 'fem. singular' },
                    { french: 'ces enfants',       english: 'these / those children',  note: 'plural — same for masc. and fem.' },
                ],
            },
            {
                title: 'When to Use cet',
                explanation: 'Use cet (not ce) before any masculine singular noun that starts with a vowel (a, e, i, o, u) or a silent h. This avoids the clash of two vowel sounds. The feminine form cette is used before all feminine nouns regardless of their first letter.',
                examples: [
                    { french: 'ce restaurant — cet hôtel',    english: 'this restaurant — this hotel',    note: 'restaurant starts with r (consonant) → ce; hôtel starts with h (silent) → cet' },
                    { french: 'ce bus — cet aéroport',        english: 'this bus — this airport',         note: 'bus → ce; aéroport starts with vowel → cet' },
                    { french: 'cette pharmacie',              english: 'this pharmacy',                    note: 'fem. → always cette, never cet' },
                    { french: 'cette école',                  english: 'this school',                     note: 'fem. — even before a vowel, it stays cette' },
                ],
            },
            {
                title: 'Using -ci and -là for Precision',
                explanation: 'Add -ci (here) or -là (there) after the noun to distinguish between "this one here" and "that one there". This is optional but useful in shops or when pointing.',
                examples: [
                    { french: 'ce livre-ci',    english: 'this book (here)',        note: '-ci = near the speaker' },
                    { french: 'ce livre-là',    english: 'that book (over there)',  note: '-là = farther away' },
                    { french: 'Je prends cette veste-ci.',   english: 'I\'ll take this jacket (this one here).' },
                    { french: 'Cet hôtel-là est trop cher.', english: 'That hotel (over there) is too expensive.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je voudrais ___ billet, s\'il vous plaît. (this ticket — masc. consonant)',    answer: 'ce',    hint: 'billet is masc. and starts with b (consonant) → ce' },
            { sentence: '___ arrêt est loin ? (this stop — masc. starts with vowel)',                   answer: 'Cet',   hint: 'arrêt is masc. and starts with a vowel → cet' },
            { sentence: 'Je n\'aime pas ___ rue. (this street — fem.)',                                 answer: 'cette', hint: 'rue is feminine → cette' },
            { sentence: '___ hôpital est à gauche. (this hospital — starts with silent h)',             answer: 'Cet',   hint: 'hôpital is masc. with silent h → cet' },
            { sentence: '___ chaussures sont trop petites. (these shoes — plural)',                     answer: 'Ces',   hint: 'plural → always ces' },
            { sentence: 'Tu prends ___ veste-ci ou ___ manteau-là ? (this jacket / that coat)',         answer: 'cette / ce', hint: 'veste is fem. → cette; manteau is masc. consonant → ce' },
        ],
    },
    {
        unit: 1,
        id: 'stress-pronouns',
        title: 'Stress Pronouns',
        level: 'A1',
        description: 'Use moi, toi, lui, elle, nous, vous, eux, elles for emphasis, after prepositions, and with c\'est',
        icon: '👤',
        color: '#7C3AED',
        sections: [
            {
                title: 'The Eight Stress Pronouns',
                explanation: 'Stress pronouns (also called disjunctive pronouns) are separate forms used when a pronoun stands alone or after a preposition. They differ from subject pronouns: je → moi, tu → toi, il → lui, elle → elle, nous → nous, vous → vous, ils → eux, elles → elles.',
                examples: [
                    { french: 'moi — me / I (stressed)',  english: 'Moi, j\'aime le café. — Me, I like coffee.' },
                    { french: 'toi — you (stressed)',      english: 'Et toi ? — And you?' },
                    { french: 'lui — him',                 english: 'C\'est lui. — It\'s him.' },
                    { french: 'elle — her',                english: 'C\'est elle. — It\'s her.' },
                    { french: 'eux — them (masc.)',        english: 'C\'est pour eux. — It\'s for them.' },
                    { french: 'elles — them (fem.)',       english: 'C\'est pour elles. — It\'s for them.' },
                ],
            },
            {
                title: 'After Prepositions',
                explanation: 'After any preposition (avec, pour, chez, sans, de, à, etc.) you must use a stress pronoun, never a subject pronoun.',
                examples: [
                    { french: 'avec moi',    english: 'with me',    note: 'NOT avec je' },
                    { french: 'chez elle',   english: 'at her place / at hers' },
                    { french: 'sans lui',    english: 'without him' },
                    { french: 'pour nous',   english: 'for us' },
                    { french: 'Tu viens avec moi ?', english: 'Are you coming with me?' },
                ],
            },
            {
                title: 'C\'est + stress pronoun and emphasis',
                explanation: 'Use stress pronouns after c\'est to identify people. Also use them to emphasise the subject — place the stress pronoun before or after the clause.',
                examples: [
                    { french: 'C\'est moi.',      english: 'It\'s me.' },
                    { french: 'C\'est lui le professeur.', english: 'He\'s the teacher.' },
                    { french: 'Moi, je parle français.', english: 'As for me, I speak French.', note: 'The subject je is repeated; moi adds emphasis' },
                    { french: 'Elle, elle aime le chocolat.', english: 'She, she likes chocolate.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Tu viens avec ___ ? (me)',                        answer: 'moi',  hint: 'after a preposition, use stress pronoun: moi' },
            { sentence: 'C\'est ___ le directeur. (him)',                  answer: 'lui',  hint: 'c\'est + stress pronoun: lui = him' },
            { sentence: 'Ce cadeau est pour ___. (her)',                   answer: 'elle', hint: 'after pour, use stress pronoun: elle' },
            { sentence: '___, j\'adore la musique. (emphatic I)',          answer: 'Moi',  hint: 'emphatic subject: Moi, je…' },
            { sentence: 'Nous allons chez ___. (them, masc.)',             answer: 'eux',  hint: 'chez + stress pronoun: eux for masculine they' },
            { sentence: 'Elle arrive avant ___. (us)',                     answer: 'nous', hint: 'avant + stress pronoun: nous' },
        ],
    },
    {
        unit: 4,
        id: 'partitive-articles',
        title: 'Partitive Articles',
        level: 'A1',
        description: 'Use du, de la, de l\', des to talk about indefinite quantities of uncountable things',
        icon: '🥐',
        color: '#92400E',
        sections: [
            {
                title: 'What are partitive articles?',
                explanation: 'Partitive articles express an unspecified quantity of something uncountable — equivalent to "some" in English (often omitted). Use du before masculine nouns, de la before feminine nouns, de l\' before any noun starting with a vowel or silent h, and des before plural nouns.',
                examples: [
                    { french: 'du café',       english: 'some coffee',   note: 'café is masculine → du' },
                    { french: 'de la soupe',   english: 'some soup',     note: 'soupe is feminine → de la' },
                    { french: 'de l\'eau',     english: 'some water',    note: 'eau starts with a vowel → de l\'' },
                    { french: 'des légumes',   english: 'some vegetables', note: 'plural → des' },
                ],
            },
            {
                title: 'Partitive in everyday contexts',
                explanation: 'Partitive articles are used constantly when ordering food, shopping, and describing what you eat or drink. They answer the question "what do you want?" when the quantity is not specified.',
                examples: [
                    { french: 'Je voudrais du pain et du beurre.',    english: 'I would like some bread and butter.' },
                    { french: 'Elle mange de la viande.',             english: 'She eats meat (some meat).' },
                    { french: 'Nous buvons de l\'eau.',               english: 'We drink water.' },
                    { french: 'Il mange des fruits le matin.',        english: 'He eats fruit in the morning.' },
                    { french: 'Tu veux du fromage ?',                 english: 'Do you want some cheese?' },
                ],
            },
            {
                title: 'Negation: partitive → de',
                explanation: 'After a negation (ne...pas), all partitive and indefinite articles (du, de la, de l\', un, une, des) are replaced by de (or d\' before a vowel). This is one of the most important rules in French.',
                examples: [
                    { french: 'J\'ai du café. → Je n\'ai pas de café.',       english: 'I have coffee. → I don\'t have coffee.' },
                    { french: 'Elle mange de la viande. → Elle ne mange pas de viande.', english: 'She doesn\'t eat meat.' },
                    { french: 'Il boit de l\'eau. → Il ne boit pas d\'eau.', english: 'He doesn\'t drink water.' },
                    { french: 'Il y a des croissants. → Il n\'y a pas de croissants.', english: 'There are no croissants.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je voudrais ___ café, s\'il vous plaît. (masc.)',      answer: 'du',    hint: 'café is masculine → du' },
            { sentence: 'Elle boit ___ eau minérale. (vowel)',                  answer: 'de l\'', hint: 'eau starts with a vowel → de l\'' },
            { sentence: 'Nous mangeons ___ pain grillé le matin. (masc.)',      answer: 'du',    hint: 'pain is masculine → du' },
            { sentence: 'Il n\'y a pas ___ fromage dans le frigo. (negation)',  answer: 'de',    hint: 'after negation, du/de la/des → de' },
            { sentence: 'Tu veux ___ soupe ? (fem.)',                           answer: 'de la', hint: 'soupe is feminine → de la' },
            { sentence: 'Je ne mange pas ___ viande. (negation)',               answer: 'de',    hint: 'after negation, de la → de' },
        ],
    },
    {
        unit: 5,
        id: 'vouloir-pouvoir-devoir',
        title: 'Modal Verbs: vouloir, pouvoir, devoir',
        level: 'A1',
        description: 'Express wants, abilities, and obligations with the three essential French modal verbs',
        icon: '⚡',
        color: '#B45309',
        sections: [
            {
                title: 'Vouloir — to want',
                explanation: 'Vouloir is irregular. Learn the full present tense. Je voudrais (conditional) is softer and more polite than je veux — use it when ordering or making requests.',
                examples: [
                    { french: 'je veux, tu veux, il/elle veut',         english: 'I want, you want, he/she wants' },
                    { french: 'nous voulons, vous voulez, ils/elles veulent', english: 'we want, you want, they want' },
                    { french: 'Je veux un café.',                        english: 'I want a coffee.' },
                    { french: 'Je voudrais un café, s\'il vous plaît.', english: 'I would like a coffee, please.', note: 'Voudrais = conditional; always use this when ordering' },
                    { french: 'Qu\'est-ce que tu veux faire ?',         english: 'What do you want to do?' },
                ],
            },
            {
                title: 'Pouvoir — to be able to / can',
                explanation: 'Pouvoir is irregular. It expresses ability or possibility. Always followed by an infinitive.',
                examples: [
                    { french: 'je peux, tu peux, il/elle peut',         english: 'I can, you can, he/she can' },
                    { french: 'nous pouvons, vous pouvez, ils/elles peuvent', english: 'we can, you can, they can' },
                    { french: 'Je peux venir demain.',                  english: 'I can come tomorrow.' },
                    { french: 'Pouvez-vous répéter ?',                  english: 'Could you repeat that?', note: 'Inversion of pouvoir: very common in polite questions' },
                    { french: 'Est-ce qu\'on peut entrer ?',            english: 'Can we come in?' },
                ],
            },
            {
                title: 'Devoir — to have to / must',
                explanation: 'Devoir is irregular. It expresses obligation or necessity. Always followed by an infinitive.',
                examples: [
                    { french: 'je dois, tu dois, il/elle doit',         english: 'I must, you must, he/she must' },
                    { french: 'nous devons, vous devez, ils/elles doivent', english: 'we must, you must, they must' },
                    { french: 'Je dois partir maintenant.',             english: 'I have to leave now.' },
                    { french: 'Tu dois étudier ce soir.',               english: 'You must study tonight.' },
                    { french: 'On doit prendre le métro.',              english: 'We have to take the metro.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je ___ un croissant et un café. (vouloir, polite)',        answer: 'voudrais',  hint: 'polite form: je voudrais (conditional)' },
            { sentence: 'Il ne ___ pas venir ce soir. (pouvoir)',                   answer: 'peut',      hint: 'pouvoir: il/elle → peut' },
            { sentence: 'Nous ___ finir ce projet avant vendredi. (devoir)',        answer: 'devons',    hint: 'devoir: nous → devons' },
            { sentence: '___ -vous m\'aider ? (pouvoir, inversion)',                answer: 'Pouvez',    hint: 'inversion for polite question: Pouvez-vous' },
            { sentence: 'Qu\'est-ce que tu ___ faire ce week-end ? (vouloir)',      answer: 'veux',      hint: 'vouloir: tu → veux' },
            { sentence: 'Elles ___ prendre le bus numéro 12. (devoir)',             answer: 'doivent',   hint: 'devoir: ils/elles → doivent' },
        ],
    },
    {
        unit: 5,
        id: 'futur-proche',
        title: 'Le Futur Proche',
        level: 'A1',
        description: 'Express what is going to happen using aller + infinitive — the main future tense at A1',
        icon: '🔮',
        color: '#0891B2',
        sections: [
            {
                title: 'Formation: aller + infinitive',
                explanation: 'The futur proche (near future) is formed with the present tense of aller + an infinitive. It is the standard way to talk about future plans and intentions at A1–A2 level.',
                examples: [
                    { french: 'je vais, tu vas, il/elle va + infinitive',           english: 'I\'m going to, you\'re going to, he\'s going to…' },
                    { french: 'nous allons, vous allez, ils/elles vont + infinitive', english: 'we\'re going to, you\'re going to, they\'re going to…' },
                    { french: 'Je vais manger.',    english: 'I\'m going to eat.' },
                    { french: 'Tu vas partir ?',    english: 'Are you going to leave?' },
                    { french: 'Il va pleuvoir.',    english: 'It\'s going to rain.' },
                ],
            },
            {
                title: 'Common uses',
                explanation: 'Use the futur proche for imminent events, plans, and predictions. It is much more common in spoken French than the futur simple (je mangerai).',
                examples: [
                    { french: 'Nous allons visiter Paris demain.',              english: 'We\'re going to visit Paris tomorrow.' },
                    { french: 'Elle va prendre le train de huit heures.',       english: 'She\'s going to take the eight o\'clock train.' },
                    { french: 'Ils vont arriver dans dix minutes.',             english: 'They\'re going to arrive in ten minutes.' },
                    { french: 'Qu\'est-ce que vous allez faire ce week-end ?', english: 'What are you going to do this weekend?' },
                ],
            },
            {
                title: 'Negation and questions',
                explanation: 'To negate the futur proche, place ne...pas around aller (not the infinitive). For questions, apply the usual question rules to aller.',
                examples: [
                    { french: 'Je ne vais pas venir.',          english: 'I\'m not going to come.', note: 'ne...pas wraps aller only' },
                    { french: 'Elle ne va pas manger ce soir.', english: 'She\'s not going to eat tonight.' },
                    { french: 'Tu vas sortir ce soir ?',        english: 'Are you going out tonight?', note: 'intonation question' },
                    { french: 'Est-ce qu\'il va réussir ?',     english: 'Is he going to succeed?' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Nous ___ visiter le musée demain. (aller + visiter)',          answer: 'allons',   hint: 'futur proche: nous allons + infinitif' },
            { sentence: 'Elle ___ prendre un taxi. (aller + prendre)',                  answer: 'va',       hint: 'futur proche: elle va + infinitif' },
            { sentence: 'Je ne ___ pas venir à la fête. (aller, négation)',             answer: 'vais',     hint: 'négation: je ne vais pas + infinitif' },
            { sentence: 'Ils ___ arriver dans cinq minutes. (aller + arriver)',         answer: 'vont',     hint: 'futur proche: ils vont + infinitif' },
            { sentence: 'Qu\'est-ce que tu ___ faire ce soir ? (aller)',                answer: 'vas',      hint: 'futur proche: tu vas + infinitif' },
            { sentence: 'Il ne ___ pas pleuvoir aujourd\'hui. (aller, négation)',       answer: 'va',       hint: 'négation: il ne va pas + infinitif' },
        ],
    },
    {
        unit: 2,
        id: 'present-tense-ir-re',
        title: 'Present Tense: -IR and -RE Verbs',
        level: 'A1',
        description: 'Conjugate regular -IR and -RE verbs — the two other main verb families in French',
        icon: '🔁',
        color: '#059669',
        sections: [
            {
                title: 'Regular -IR Verbs',
                explanation: 'To conjugate a regular -IR verb, drop the -ir ending and add: -is, -is, -it, -issons, -issez, -issent. Note the -iss- inserted in the plural forms.',
                examples: [
                    { french: 'finir → je finis, tu finis, il/elle finit', english: 'to finish → I finish, you finish, he/she finishes' },
                    { french: 'nous finissons, vous finissez, ils/elles finissent', english: 'we finish, you finish, they finish', note: '-iss- appears in all plural forms' },
                    { french: 'choisir → je choisis, tu choisis, il choisit', english: 'to choose → I choose, you choose, he chooses' },
                    { french: 'nous choisissons, vous choisissez, ils choisissent', english: 'we choose, you choose, they choose' },
                ],
            },
            {
                title: 'Common -IR Verbs',
                explanation: 'These are the most useful regular -IR verbs at A1 level.',
                examples: [
                    { french: 'finir — to finish', english: 'Je finis mon travail. — I finish my work.' },
                    { french: 'choisir — to choose', english: 'Elle choisit une robe rouge. — She chooses a red dress.' },
                    { french: 'remplir — to fill', english: 'Il remplit le verre d\'eau. — He fills the glass with water.' },
                    { french: 'réussir — to succeed / to pass', english: 'Nous réussissons l\'examen. — We pass the exam.' },
                    { french: 'grandir — to grow up', english: 'Les enfants grandissent vite. — Children grow up fast.' },
                ],
            },
            {
                title: 'Regular -RE Verbs',
                explanation: 'To conjugate a regular -RE verb, drop the -re ending and add: -s, -s, — (nothing), -ons, -ez, -ent. The il/elle/on form has no ending added.',
                examples: [
                    { french: 'vendre → je vends, tu vends, il/elle vend', english: 'to sell → I sell, you sell, he/she sells', note: 'il/elle form: drop -re, add nothing' },
                    { french: 'nous vendons, vous vendez, ils/elles vendent', english: 'we sell, you sell, they sell' },
                    { french: 'attendre → j\'attends, tu attends, il attend', english: 'to wait → I wait, you wait, he waits' },
                    { french: 'nous attendons, vous attendez, ils attendent', english: 'we wait, you wait, they wait' },
                ],
            },
            {
                title: 'Common -RE Verbs',
                explanation: 'These are the most useful regular -RE verbs at A1 level.',
                examples: [
                    { french: 'vendre — to sell', english: 'Il vend des légumes au marché. — He sells vegetables at the market.' },
                    { french: 'attendre — to wait (for)', english: 'J\'attends le bus. — I\'m waiting for the bus.', note: 'No preposition needed in French: attendre qqch directly' },
                    { french: 'répondre — to answer', english: 'Elle répond à la question. — She answers the question.' },
                    { french: 'entendre — to hear', english: 'Nous entendons la musique. — We can hear the music.' },
                    { french: 'perdre — to lose', english: 'Tu perds toujours tes clés ! — You always lose your keys!' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Elle ___ son café avant de partir. (finir)',                      answer: 'finit',      hint: '-IR: 3rd person singular → drop -ir, add -it' },
            { sentence: 'Nous ___ un film ce soir. (choisir)',                             answer: 'choisissons', hint: '-IR plural: drop -ir, add -issons' },
            { sentence: 'Ils ___ leurs affaires sur le marché. (vendre)',                  answer: 'vendent',    hint: '-RE plural: drop -re, add -ent' },
            { sentence: 'J\'___ le bus depuis vingt minutes. (attendre)',                  answer: 'attends',    hint: '-RE 1st person singular: drop -re, add -s' },
            { sentence: 'Vous ___ bien à l\'école ? (réussir)',                            answer: 'réussissez', hint: '-IR 2nd person plural: drop -ir, add -issez' },
            { sentence: 'Il ___ toujours ses clés. (perdre)',                              answer: 'perd',       hint: '-RE 3rd person singular: drop -re, add nothing' },
        ],
    },
    {
        unit: 2,
        id: 'negation',
        title: 'Negation',
        level: 'A1',
        description: 'How to make sentences negative in French',
        icon: '🚫',
        color: '#DC2626',
        sections: [
            {
                title: 'Basic Negation: ne...pas',
                explanation: 'Wrap the conjugated verb with ne (n\' before a vowel) ... pas to negate it.',
                examples: [
                    { french: 'Je ne parle pas.', english: 'I don\'t speak.' },
                    { french: 'Elle n\'aime pas le café.', english: 'She doesn\'t like coffee.' },
                    { french: 'Nous ne sommes pas prêts.', english: 'We aren\'t ready.' },
                    { french: 'Il ne comprend pas.', english: 'He doesn\'t understand.' },
                    { french: 'Ce n\'est pas vrai.', english: 'It\'s not true.' },
                ],
            },
            {
                title: 'Other Negative Expressions',
                explanation: 'Replace pas with other words to express different negatives.',
                examples: [
                    { french: 'ne...jamais → never: Je ne fume jamais.', english: 'I never smoke.' },
                    { french: 'ne...rien → nothing: Il ne sait rien.', english: 'He knows nothing.' },
                    { french: 'ne...personne → nobody: Elle ne voit personne.', english: 'She sees nobody.' },
                    { french: 'ne...plus → no longer / not anymore: Il ne travaille plus ici.', english: 'He no longer works here.' },
                    { french: 'ne...que → only: Je n\'ai que dix euros.', english: 'I only have ten euros.' },
                    { french: 'ne...ni...ni → neither...nor: Il ne parle ni anglais ni espagnol.', english: 'He speaks neither English nor Spanish.' },
                ],
            },
            {
                title: 'Negation with Infinitives',
                explanation: 'When negating an infinitive, both ne and pas go before the infinitive.',
                examples: [
                    { french: 'Essaie de ne pas crier.', english: 'Try not to shout.' },
                    { french: 'Il a décidé de ne pas partir.', english: 'He decided not to leave.' },
                    { french: 'C\'est important de ne pas oublier.', english: 'It\'s important not to forget.' },
                ],
            },
        ],
        exercises: [
            { sentence: "Je ___ parle pas anglais.", answer: 'ne', hint: 'first part of ne…pas' },
            { sentence: "Elle n'aime ___ le café.", answer: 'pas', hint: 'second part of ne…pas' },
            { sentence: "Il ne fume ___.", answer: 'jamais', hint: 'ne…jamais = never' },
            { sentence: "Je n'ai ___ dix euros.", answer: 'que', hint: 'ne…que = only' },
            { sentence: "Essaie de ne ___ crier.", answer: 'pas', hint: 'negating an infinitive: ne pas before it' },
            { sentence: "Il ne sait ___.", answer: 'rien', hint: 'ne…rien = nothing' },
        ],
    },
    {
        unit: 5,
        id: 'questions',
        title: 'Asking Questions',
        level: 'A1',
        description: 'Three ways to form questions and the key question words',
        icon: '❓',
        color: '#D97706',
        sections: [
            {
                title: 'Intonation',
                explanation: 'The simplest method: raise your voice at the end of an affirmative sentence.',
                examples: [
                    { french: 'Tu parles français ?', english: 'You speak French?' },
                    { french: 'Il est là ?', english: 'Is he there?' },
                    { french: 'C\'est bon ?', english: 'Is it good?' },
                ],
            },
            {
                title: 'Est-ce que',
                explanation: 'Add est-ce que before the subject + verb. Works with any subject without inversion.',
                examples: [
                    { french: 'Est-ce que tu parles français ?', english: 'Do you speak French?' },
                    { french: 'Est-ce qu\'il est là ?', english: 'Is he there?' },
                    { french: 'Est-ce que vous avez une réservation ?', english: 'Do you have a reservation?' },
                    { french: 'Est-ce qu\'elle travaille ici ?', english: 'Does she work here?' },
                ],
            },
            {
                title: 'Inversion',
                explanation: 'Invert the verb and subject pronoun, linked by a hyphen. Add -t- between vowels.',
                examples: [
                    { french: 'Parles-tu français ?', english: 'Do you speak French?' },
                    { french: 'Est-il là ?', english: 'Is he there?' },
                    { french: 'A-t-il une voiture ?', english: 'Does he have a car?' },
                    { french: 'Comprend-elle la situation ?', english: 'Does she understand the situation?' },
                ],
            },
            {
                title: 'Question Words',
                explanation: 'Use interrogative words with any question method.',
                examples: [
                    { french: 'Qui ?', english: 'Who?' },
                    { french: 'Quoi ?', english: 'What? (informal)' },
                    { french: 'Que / Qu\'est-ce que ?', english: 'What?' },
                    { french: 'Où ?', english: 'Where?' },
                    { french: 'Quand ?', english: 'When?' },
                    { french: 'Comment ?', english: 'How?' },
                    { french: 'Pourquoi ?', english: 'Why?' },
                    { french: 'Combien ?', english: 'How much / many?' },
                ],
            },
        ],
        exercises: [
            { sentence: "___ est-ce que tu parles français ?", answer: 'Est-ce que', hint: 'formal question opener, no inversion needed' },
            { sentence: "Parles-___ français ?", answer: 'tu', hint: 'inversion: verb-subject pronoun' },
            { sentence: "___ vas-tu ?", answer: 'Où', hint: 'question word for place' },
            { sentence: "___ est-ce que tu arrives ?", answer: 'Quand', hint: 'question word for time' },
            { sentence: "A-t-il ___ voiture ?", answer: 'une', hint: 'indefinite article, feminine' },
            { sentence: "___ parles-tu ?", answer: 'Comment', hint: 'question word for manner/how' },
        ],
    },
];
