import type { GrammarLesson } from '../../../types/lectures/grammar';

export const grammarA2: GrammarLesson[] = [
    {
        unit: 1,
        id: 'imparfait-intro',
        title: 'L\'Imparfait — Introduction',
        level: 'A2',
        description: 'Describe habitual past actions, background scenes, and states of mind using the imperfect tense',
        icon: '🕰️',
        color: '#059669',
        sections: [
            {
                title: 'Formation',
                explanation: 'Take the nous form of the present tense, drop -ons, and add the imparfait endings: -ais, -ais, -ait, -ions, -iez, -aient. The only exception is être: the stem is ét- (j\'étais, tu étais…). All other verbs are regular.',
                examples: [
                    { french: 'parler: nous parlons → parl- → je parlais, tu parlais, il parlait', english: 'I was speaking / I used to speak' },
                    { french: 'nous parlions, vous parliez, ils parlaient', english: 'we used to speak, you used to speak, they used to speak' },
                    { french: 'finir: nous finissons → finiss- → je finissais', english: 'I used to finish' },
                    { french: 'être → ét- → j\'étais, tu étais, il était', english: 'I was, you were, he was', note: 'Irregular stem only — endings are the same' },
                ],
            },
            {
                title: 'When to use the imparfait',
                explanation: 'Use the imparfait for: (1) habitual or repeated past actions — things you used to do; (2) background descriptions — what was happening; (3) states of mind or feelings in the past; (4) descriptions of people, places, and things in the past.',
                examples: [
                    { french: 'Quand j\'étais petit, je jouais au football tous les jours.', english: 'When I was young, I used to play football every day.', note: 'Habitual action' },
                    { french: 'Il faisait beau et les oiseaux chantaient.', english: 'The weather was nice and the birds were singing.', note: 'Background description' },
                    { french: 'Elle était fatiguée et elle voulait rentrer.', english: 'She was tired and she wanted to go home.', note: 'State / feeling' },
                    { french: 'La maison était grande et le jardin était magnifique.', english: 'The house was big and the garden was magnificent.', note: 'Description' },
                ],
            },
            {
                title: 'Signal words for the imparfait',
                explanation: 'Certain time expressions almost always signal the imparfait because they imply habitual or ongoing past situations.',
                examples: [
                    { french: 'tous les jours / chaque semaine', english: 'every day / every week' },
                    { french: 'souvent / toujours / d\'habitude', english: 'often / always / usually' },
                    { french: 'autrefois / quand j\'étais enfant', english: 'in the past / when I was a child' },
                    { french: 'pendant que / tandis que', english: 'while / whilst' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Quand il ___ petit, il aimait les trains. (être)',          answer: 'était',      hint: 'être → ét- + ait (3rd sing.)' },
            { sentence: 'Nous ___ au parc tous les dimanches. (aller)',              answer: 'allions',    hint: 'aller: nous allons → all- + ions' },
            { sentence: 'Elle ___ dans une grande maison à Lyon. (habiter)',         answer: 'habitait',   hint: 'habiter: nous habitons → habit- + ait' },
            { sentence: 'Vous ___ souvent au cinéma le week-end ? (aller)',          answer: 'alliez',     hint: 'aller: all- + iez (2nd plural)' },
            { sentence: 'Ils ___ fatigués après le voyage. (être)',                  answer: 'étaient',    hint: 'être → ét- + aient (3rd plural)' },
            { sentence: 'Je ___ du café chaque matin avant d\'aller travailler. (boire)', answer: 'buvais', hint: 'boire: nous buvons → buv- + ais' },
        ],
    },
    {
        unit: 1,
        id: 'passe-compose-vs-imparfait',
        title: 'Passé Composé vs Imparfait',
        level: 'A2',
        description: 'Master the core A2 challenge: when to use each past tense in the same story',
        icon: '⚖️',
        color: '#D97706',
        sections: [
            {
                title: 'The core distinction',
                explanation: 'Both tenses refer to the past, but they play different roles. The passé composé narrates completed events — what happened, what someone did. The imparfait provides background — what was happening, what things were like. In a story, the passé composé moves the plot forward; the imparfait sets the scene.',
                examples: [
                    { french: 'Il pleuvait (imparfait) quand je suis sorti (passé composé).', english: 'It was raining when I went out.', note: 'Rain = background; going out = event' },
                    { french: 'Elle lisait (imp.) quand le téléphone a sonné (PC).', english: 'She was reading when the phone rang.', note: 'Reading = ongoing background; rang = single event' },
                    { french: 'J\'habitais (imp.) à Paris quand j\'ai rencontré (PC) Marie.', english: 'I was living in Paris when I met Marie.' },
                ],
            },
            {
                title: 'Trigger word lists',
                explanation: 'Signal words help you choose the right tense. Words implying a single completed action → passé composé. Words implying habit, duration, or background → imparfait.',
                examples: [
                    { french: 'PC: soudain, tout à coup, un jour, puis, ensuite, finalement', english: 'suddenly, all of a sudden, one day, then, afterwards, finally' },
                    { french: 'IMP: tous les jours, souvent, d\'habitude, autrefois, chaque, pendant que', english: 'every day, often, usually, in the past, each, while' },
                    { french: 'PC: Elle a soudain crié.', english: 'She suddenly cried out.' },
                    { french: 'IMP: D\'habitude, elle criait rarement.', english: 'She rarely cried out usually.' },
                ],
            },
            {
                title: 'Describing vs narrating',
                explanation: 'A useful test: can you replace the verb with "was [verb]-ing"? If yes → imparfait. Can you replace it with "happened once and completed"? If yes → passé composé.',
                examples: [
                    { french: 'La ville était (imp.) belle. → The city was beautiful.', english: 'Description → imparfait' },
                    { french: 'Nous avons visité (PC) la ville. → We visited the city.', english: 'Event → passé composé' },
                    { french: 'Il faisait (imp.) froid. Nous avons décidé (PC) de rester.', english: 'It was cold (background). We decided to stay (event).' },
                    { french: 'Elle portait (imp.) une robe rouge quand il l\'a vue (PC).', english: 'She was wearing a red dress when he saw her.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Il ___ (pleuvoir, IMP) quand nous ___ (sortir, PC).',    answer: 'pleuvait / sommes sortis', hint: 'pleuvoir: IMP background; sortir: PC single event with être' },
            { sentence: 'D\'habitude, elle ___ (prendre, IMP) le bus.',            answer: 'prenait',     hint: 'D\'habitude signals IMP habit: prendre → pren- + ait' },
            { sentence: 'Soudain, il ___ (tomber, PC).',                           answer: 'est tombé',   hint: 'Soudain signals PC; tomber uses être in PC' },
            { sentence: 'Nous ___ (habiter, IMP) à Nice quand je ___ (trouver, PC) ce travail.', answer: 'habitions / ai trouvé', hint: 'IMP for ongoing living; PC for the single event of finding' },
            { sentence: 'Autrefois, les gens ___ (écrire, IMP) des lettres.',      answer: 'écrivaient',  hint: 'Autrefois signals IMP habit: écrire → écriv- + aient' },
            { sentence: 'Tout à coup, la lumière ___ (s\'éteindre, PC).',          answer: 's\'est éteinte', hint: 'Tout à coup signals PC; reflexive with être, fem. agreement' },
        ],
    },
    {
        unit: 5,
        id: 'reflexive-verbs-basics',
        title: 'Reflexive Verbs — Basics',
        level: 'A2',
        description: 'Express daily routine actions using reflexive verbs in the present tense and passé composé',
        icon: '🔄',
        color: '#0891B2',
        sections: [
            {
                title: 'What are reflexive verbs?',
                explanation: 'Reflexive verbs have a reflexive pronoun (me, te, se, nous, vous, se) between the subject and the verb. The pronoun shows the action reflects back on the subject. They are very common for daily routine verbs in French.',
                examples: [
                    { french: 'je me lève, tu te lèves, il/elle se lève', english: 'I get up, you get up, he/she gets up' },
                    { french: 'nous nous levons, vous vous levez, ils/elles se lèvent', english: 'we get up, you get up, they get up' },
                    { french: 'se réveiller — to wake up', english: 'Je me réveille à sept heures. — I wake up at seven.' },
                    { french: 's\'habiller — to get dressed', english: 'Elle s\'habille rapidement. — She gets dressed quickly.' },
                ],
            },
            {
                title: 'Common daily routine reflexive verbs',
                explanation: 'These verbs describe the morning and evening routine — essential for A2 conversation and DELF writing tasks.',
                examples: [
                    { french: 'se lever — to get up', english: 'Je me lève à sept heures.' },
                    { french: 'se laver — to wash', english: 'Il se lave les mains.' },
                    { french: 's\'habiller — to get dressed', english: 'Nous nous habillons vite.' },
                    { french: 'se coucher — to go to bed', english: 'Elle se couche à dix heures.' },
                    { french: 'se brosser les dents — to brush one\'s teeth', english: 'Je me brosse les dents après le repas.' },
                ],
            },
            {
                title: 'Reflexive verbs in the passé composé',
                explanation: 'All reflexive verbs use être in the passé composé. The past participle agrees with the subject in gender and number (add -e for feminine, -s for plural, -es for feminine plural).',
                examples: [
                    { french: 'Je me suis levé(e) à huit heures.', english: 'I got up at eight o\'clock.', note: 'Add -e if feminine: levée' },
                    { french: 'Elle s\'est habillée en cinq minutes.', english: 'She got dressed in five minutes.', note: 'Feminine subject → habillée' },
                    { french: 'Ils se sont couchés tard.', english: 'They went to bed late.', note: 'Masculine plural → couchés' },
                    { french: 'Nous nous sommes réveillés à l\'aube.', english: 'We woke up at dawn.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je ___ à sept heures chaque matin. (se lever)',                 answer: 'me lève',          hint: 'se lever present: je me lève' },
            { sentence: 'Elle ___ les dents après le petit-déjeuner. (se brosser)',      answer: 'se brosse',        hint: 'se brosser present: elle se brosse' },
            { sentence: 'Nous ___ vite parce qu\'on est en retard. (s\'habiller)',       answer: 'nous habillons',   hint: 'present: nous nous habillons' },
            { sentence: 'Il ___ à minuit hier soir. (se coucher, passé composé)',        answer: 's\'est couché',    hint: 'PC with être: il s\'est couché' },
            { sentence: 'Elles ___ tôt ce matin. (se réveiller, passé composé)',        answer: 'se sont réveillées', hint: 'PC être, fem. plural: se sont réveillées' },
            { sentence: 'À quelle heure tu ___ d\'habitude ? (se lever)',               answer: 'te lèves',         hint: 'present: tu te lèves' },
        ],
    },
    {
        unit: 2,
        id: 'comparatives-superlatives',
        title: 'Comparatives & Superlatives',
        level: 'A2',
        description: 'Compare people, places, and things using plus, moins, aussi, and le plus / le moins',
        icon: '📊',
        color: '#7C3AED',
        sections: [
            {
                title: 'Comparatives',
                explanation: 'To compare using adjectives or adverbs: plus…que (more…than), moins…que (less…than), aussi…que (as…as). The adjective must still agree with the noun it describes.',
                examples: [
                    { french: 'Paris est plus grand que Lyon.',         english: 'Paris is bigger than Lyon.' },
                    { french: 'Ce livre est moins cher que l\'autre.',  english: 'This book is less expensive than the other one.' },
                    { french: 'Elle est aussi intelligente que lui.',   english: 'She is as intelligent as him.' },
                    { french: 'Il parle plus vite que moi.',            english: 'He speaks faster than me.', note: 'vite is an adverb — no agreement' },
                ],
            },
            {
                title: 'Superlatives',
                explanation: 'To express the most or least: le/la/les plus + adjective (the most) or le/la/les moins + adjective (the least). The article agrees with the noun. The adjective still agrees and keeps its usual position.',
                examples: [
                    { french: 'C\'est le restaurant le plus cher de la ville.', english: 'It\'s the most expensive restaurant in town.', note: 'de = in / of after superlatives' },
                    { french: 'Elle est la plus rapide de l\'équipe.',           english: 'She is the fastest in the team.' },
                    { french: 'C\'est le moins beau tableau.',                  english: 'It\'s the least beautiful painting.' },
                    { french: 'C\'est la ville la moins polluée.',              english: 'It\'s the least polluted city.' },
                ],
            },
            {
                title: 'Irregular comparatives: bon / bien, mauvais / mal',
                explanation: 'Bon (good) and bien (well) have irregular comparative and superlative forms. Avoid plus bon and plus bien — they are incorrect.',
                examples: [
                    { french: 'bon → meilleur(e) — better / best',       english: 'Ce vin est meilleur que l\'autre. — This wine is better than the other.', note: 'NOT plus bon' },
                    { french: 'le/la meilleur(e) — the best',            english: 'C\'est le meilleur restaurant. — It\'s the best restaurant.' },
                    { french: 'bien → mieux — better (adverb)',           english: 'Il parle mieux que moi. — He speaks better than me.', note: 'NOT plus bien' },
                    { french: 'mauvais → pire — worse; le pire — the worst', english: 'C\'est pire qu\'avant. — It\'s worse than before.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Lyon est ___ grand ___ Marseille. (smaller than)',                  answer: 'moins / que',     hint: 'moins…que = less…than' },
            { sentence: 'C\'est le film ___ intéressant de l\'année. (most)',                answer: 'le plus',         hint: 'superlative: le plus + adjective' },
            { sentence: 'Ce fromage est ___ ___ l\'autre. (better than — use bon form)',     answer: 'meilleur que',    hint: 'bon → meilleur, NOT plus bon' },
            { sentence: 'Elle court ___ vite ___ son frère. (as fast as)',                   answer: 'aussi / que',     hint: 'aussi…que = as…as' },
            { sentence: 'C\'est la ___ solution. (worst — use mauvais form)',                answer: 'pire',            hint: 'mauvais → pire; la pire solution' },
            { sentence: 'Il travaille ___ ___ moi. (better — use bien form)',                answer: 'mieux que',       hint: 'bien → mieux (adverb), NOT plus bien' },
        ],
    },
    {
        unit: 3,
        id: 'futur-simple-intro',
        title: 'Le Futur Simple',
        level: 'A2',
        description: 'Express future plans, predictions, and promises using the simple future tense',
        icon: '🚀',
        color: '#DC2626',
        sections: [
            {
                title: 'Formation: regular verbs',
                explanation: 'For most verbs, add the futur endings to the infinitive: -ai, -as, -a, -ons, -ez, -ont. For -RE verbs, drop the final -e before adding the endings. The endings are the same for all verbs.',
                examples: [
                    { french: 'parler → je parlerai, tu parleras, il/elle parlera', english: 'I will speak, you will speak, he/she will speak' },
                    { french: 'nous parlerons, vous parlerez, ils/elles parleront', english: 'we will speak, you will speak, they will speak' },
                    { french: 'finir → je finirai, tu finiras, il finira', english: 'I will finish, you will finish, he will finish' },
                    { french: 'vendre → je vendrai (drop -e)', english: 'I will sell', note: '-RE verbs: remove the e before adding endings' },
                ],
            },
            {
                title: 'Irregular stems',
                explanation: 'Some very common verbs have irregular stems in the futur simple. The endings are always the same. These must be memorised.',
                examples: [
                    { french: 'être → ser- : je serai', english: 'I will be' },
                    { french: 'avoir → aur- : j\'aurai', english: 'I will have' },
                    { french: 'aller → ir- : j\'irai', english: 'I will go' },
                    { french: 'faire → fer- : je ferai', english: 'I will do / make' },
                    { french: 'pouvoir → pourr- : je pourrai', english: 'I will be able to' },
                    { french: 'venir → viendr- : je viendrai', english: 'I will come' },
                ],
            },
            {
                title: 'Futur simple vs futur proche',
                explanation: 'Both express the future. The futur proche (aller + infinitive) is used for imminent plans and intentions. The futur simple is used for more distant predictions, promises, and formal contexts — and is required in writing tasks.',
                examples: [
                    { french: 'Je vais partir dans cinq minutes. (futur proche)', english: 'I\'m going to leave in five minutes.', note: 'Imminent, personal plan' },
                    { french: 'L\'année prochaine, j\'irai en France. (futur simple)', english: 'Next year, I will go to France.', note: 'More distant future, written register' },
                    { french: 'Un jour, tu seras médecin. (futur simple)', english: 'One day, you will be a doctor.', note: 'Prediction / promise' },
                ],
            },
        ],
        exercises: [
            { sentence: 'L\'année prochaine, nous ___ en Italie. (aller, futur simple)',     answer: 'irons',      hint: 'aller irregular stem: ir- + ons' },
            { sentence: 'Il ___ médecin quand il sera grand. (être, futur simple)',          answer: 'sera',       hint: 'être irregular stem: ser- + a' },
            { sentence: 'Tu ___ l\'examen si tu travailles bien. (réussir, futur simple)',   answer: 'réussiras',  hint: 'réussir regular: réussir + as' },
            { sentence: 'Nous ___ le dîner ensemble demain. (préparer, futur simple)',       answer: 'préparerons',hint: 'préparer regular: préparer + ons' },
            { sentence: 'Elle ___ plus de temps libre le week-end prochain. (avoir)',        answer: 'aura',       hint: 'avoir irregular stem: aur- + a' },
            { sentence: 'Ils ___ à la réunion sans faute. (venir, futur simple)',            answer: 'viendront',  hint: 'venir irregular stem: viendr- + ont' },
        ],
    },
    {
        unit: 3,
        id: 'direct-object-pronouns',
        title: 'Direct Object Pronouns',
        level: 'A2',
        description: 'Replace direct object nouns with le, la, l\', les to avoid repetition',
        icon: '🔁',
        color: '#059669',
        sections: [
            {
                title: 'The four direct object pronouns',
                explanation: 'Direct object pronouns replace nouns that receive the action of the verb directly (no preposition between verb and noun). They agree with the noun they replace: le (masc. sing.), la (fem. sing.), l\' (before vowel/h), les (plural).',
                examples: [
                    { french: 'Je mange le gâteau. → Je le mange.', english: 'I eat the cake. → I eat it.', note: 'le replaces masc. sing. noun' },
                    { french: 'Il regarde la télé. → Il la regarde.', english: 'He watches TV. → He watches it.', note: 'la replaces fem. sing. noun' },
                    { french: 'Elle aime les films. → Elle les aime.', english: 'She likes films. → She likes them.', note: 'les replaces plural noun' },
                    { french: 'Tu comprends l\'explication ? → Tu la comprends ?', english: 'Do you understand the explanation?', note: 'la before consonant sound even after l\'' },
                ],
            },
            {
                title: 'Position: before the verb',
                explanation: 'The direct object pronoun comes immediately before the conjugated verb. In the passé composé, it goes before the auxiliary (avoir/être). In a verb + infinitive structure, it goes before the infinitive.',
                examples: [
                    { french: 'Je le mange. (present)',         english: 'I eat it.', note: 'before conjugated verb' },
                    { french: 'Je l\'ai mangé. (passé composé)', english: 'I ate it.', note: 'before avoir' },
                    { french: 'Je vais le manger. (futur proche)', english: 'I\'m going to eat it.', note: 'before infinitive' },
                    { french: 'Je veux le lire. (verb + infinitive)', english: 'I want to read it.', note: 'before the infinitive, not veux' },
                ],
            },
            {
                title: 'Agreement in the passé composé',
                explanation: 'When a direct object pronoun precedes the passé composé, the past participle agrees with the pronoun in gender and number. This is one of the most tested agreement rules in French.',
                examples: [
                    { french: 'La lettre ? Je l\'ai écrite.', english: 'The letter? I wrote it.', note: 'la (fem.) → écrite (fem.)' },
                    { french: 'Les livres ? Il les a lus.', english: 'The books? He read them.', note: 'les (masc. pl.) → lus' },
                    { french: 'La robe ? Elle l\'a achetée.', english: 'The dress? She bought it.', note: 'la (fem. sing.) → achetée' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je mange la pomme. → Je ___ mange.',                           answer: 'la',       hint: 'pomme is feminine singular → la' },
            { sentence: 'Il regarde les films. → Il ___ regarde.',                       answer: 'les',      hint: 'films is plural → les' },
            { sentence: 'Elle a lu le livre. → Elle ___ a lu.',                          answer: 'l\'',      hint: 'livre is masc. sing. before past participle starting with vowel → l\'' },
            { sentence: 'Tu veux manger la tarte ? → Tu veux ___ manger ?',             answer: 'la',       hint: 'before the infinitive; tarte is feminine → la' },
            { sentence: 'Ils ont pris les billets. → Ils ___ ont pris.',                 answer: 'les',      hint: 'billets is plural → les; before auxiliary' },
            { sentence: 'La lettre ? Je ___ ai ___. (écrire, fem. agreement)',           answer: 'l\' / écrite', hint: 'l\' before vowel; fem. → écrite' },
        ],
    },
    {
        unit: 4,
        id: 'indirect-object-pronouns',
        title: 'Indirect Object Pronouns',
        level: 'A2',
        description: 'Use lui and leur to replace indirect objects (people you speak to, give things to, etc.)',
        icon: '💬',
        color: '#D97706',
        sections: [
            {
                title: 'Lui and leur',
                explanation: 'Indirect object pronouns replace nouns introduced by à that refer to people. Lui replaces à + a singular person (male or female); leur replaces à + plural people. Unlike direct object pronouns, they never change for gender.',
                examples: [
                    { french: 'Je parle à Marie. → Je lui parle.',          english: 'I speak to Marie. → I speak to her.' },
                    { french: 'Il écrit à son père. → Il lui écrit.',        english: 'He writes to his father. → He writes to him.' },
                    { french: 'Nous téléphonons aux enfants. → Nous leur téléphonons.', english: 'We phone the children. → We phone them.' },
                    { french: 'Elle donne le livre à ses amis. → Elle leur donne le livre.', english: 'She gives the book to her friends. → She gives them the book.' },
                ],
            },
            {
                title: 'Common verbs taking indirect objects (à + person)',
                explanation: 'These verbs always take an indirect object. Learn them as a group so you know when to use lui/leur.',
                examples: [
                    { french: 'parler à, écrire à, téléphoner à, répondre à', english: 'to speak to, write to, phone, answer' },
                    { french: 'donner à, offrir à, envoyer à, montrer à', english: 'to give to, offer to, send to, show to' },
                    { french: 'demander à, dire à, expliquer à, poser une question à', english: 'to ask, tell, explain to, ask a question to' },
                    { french: 'Je lui ai dit la vérité.', english: 'I told him/her the truth.' },
                ],
            },
            {
                title: 'Position and passé composé',
                explanation: 'Indirect object pronouns follow the same placement rules as direct object pronouns: before the conjugated verb, before the auxiliary in passé composé, before the infinitive. However, there is NO agreement of the past participle with indirect objects.',
                examples: [
                    { french: 'Je lui téléphone. (present)',                  english: 'I phone him/her.' },
                    { french: 'Je lui ai téléphoné. (passé composé)',         english: 'I phoned him/her.', note: 'no agreement — indirect object' },
                    { french: 'Je vais lui écrire. (futur proche)',           english: 'I\'m going to write to him/her.' },
                    { french: 'Il leur a expliqué le problème.',              english: 'He explained the problem to them.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je parle à ma mère. → Je ___ parle.',                           answer: 'lui',   hint: 'à + singular person → lui' },
            { sentence: 'Elle écrit à ses parents. → Elle ___ écrit.',                   answer: 'leur',  hint: 'à + plural → leur' },
            { sentence: 'Il a dit la vérité à son ami. → Il ___ a dit la vérité.',       answer: 'lui',   hint: 'singular → lui; no past participle agreement with indirect object' },
            { sentence: 'Nous allons téléphoner aux enfants. → Nous allons ___ téléphoner.', answer: 'leur', hint: 'plural → leur; before infinitive' },
            { sentence: 'Tu as répondu à tes collègues ? → Tu ___ as répondu ?',         answer: 'leur',  hint: 'collègues = plural → leur' },
            { sentence: 'Elle va expliquer le problème à Paul. → Elle va ___ expliquer le problème.', answer: 'lui', hint: 'singular → lui; before infinitive' },
        ],
    },
    {
        unit: 4,
        id: 'depuis-pendant',
        title: 'Depuis, Pendant, Il y a, Dans',
        level: 'A2',
        description: 'Express duration, elapsed time, and time frames using the four key time prepositions',
        icon: '⏱️',
        color: '#0891B2',
        sections: [
            {
                title: 'Depuis + present — ongoing duration',
                explanation: 'Depuis + present tense expresses an action that started in the past and is still going on. English uses "have been doing for". This is one of the most common errors for English speakers — do not use the past tense with depuis.',
                examples: [
                    { french: 'J\'habite ici depuis trois ans.', english: 'I have been living here for three years.', note: 'Present tense with depuis — NOT j\'ai habité' },
                    { french: 'Elle étudie le français depuis six mois.', english: 'She has been studying French for six months.' },
                    { french: 'Depuis quand est-ce que tu travailles ici ?', english: 'How long have you been working here?' },
                ],
            },
            {
                title: 'Pendant — completed duration',
                explanation: 'Pendant + past tense expresses a completed duration — something that went on for a specific period but is now over. It translates as "for" in English.',
                examples: [
                    { french: 'J\'ai habité à Paris pendant deux ans.', english: 'I lived in Paris for two years.', note: 'Passé composé — action is completed' },
                    { french: 'Elle a travaillé ici pendant dix ans.', english: 'She worked here for ten years.' },
                    { french: 'Pendant les vacances, nous avons beaucoup voyagé.', english: 'During the holidays, we travelled a lot.' },
                ],
            },
            {
                title: 'Il y a (ago) and dans (in / in...\'s time)',
                explanation: 'Il y a + past tense = "ago". Dans + present/future = "in [time]\'s time". Both refer to points in time, not durations.',
                examples: [
                    { french: 'Je suis arrivé il y a deux jours.', english: 'I arrived two days ago.' },
                    { french: 'Il a appelé il y a une heure.', english: 'He called an hour ago.' },
                    { french: 'Elle arrivera dans une heure.', english: 'She will arrive in an hour.', note: 'dans = in [time]\'s time (future)' },
                    { french: 'Le train part dans dix minutes.', english: 'The train leaves in ten minutes.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Elle apprend le piano ___ cinq ans. (ongoing)',                  answer: 'depuis',   hint: 'ongoing → depuis + present tense' },
            { sentence: 'J\'ai travaillé ici ___ deux ans, puis j\'ai changé. (completed)', answer: 'pendant', hint: 'completed duration → pendant + past tense' },
            { sentence: 'Il est parti ___ une heure. (ago)',                               answer: 'il y a',   hint: 'ago → il y a + past tense' },
            { sentence: 'Le médecin arrive ___ vingt minutes. (in)',                       answer: 'dans',     hint: 'in [time]\'s time (future) → dans' },
            { sentence: '___ combien de temps tu habites ici ? (how long — ongoing)',      answer: 'Depuis',   hint: 'how long + ongoing → depuis' },
            { sentence: 'Nous avons visité Rome ___ une semaine. (completed)',             answer: 'pendant',  hint: 'completed trip duration → pendant' },
        ],
    },
    {
        unit: 2,
        id: 'adjective-agreement',
        title: 'Adjective Agreement',
        level: 'A2',
        description: 'Adjectives must agree in gender and number with the noun they describe',
        icon: '🔤',
        color: '#7C3AED',
        sections: [
            {
                title: 'Basic Agreement',
                explanation: 'Add -e for feminine, -s for masculine plural, -es for feminine plural. The -e is usually silent but changes pronunciation of a preceding consonant.',
                examples: [
                    { french: 'un homme grand', english: 'a tall man' },
                    { french: 'une femme grande', english: 'a tall woman' },
                    { french: 'des hommes grands', english: 'tall men' },
                    { french: 'des femmes grandes', english: 'tall women' },
                    { french: 'C\'est un livre intéressant.', english: 'It\'s an interesting book.' },
                ],
            },
            {
                title: 'Irregular Feminine Forms',
                explanation: 'Many adjectives have irregular feminine forms. Common patterns: -eux/-euse, -if/-ive, -el/-elle, -en/-enne, -er/-ère.',
                examples: [
                    { french: 'heureux / heureuse', english: 'happy' },
                    { french: 'actif / active', english: 'active' },
                    { french: 'naturel / naturelle', english: 'natural' },
                    { french: 'ancien / ancienne', english: 'former / old' },
                    { french: 'premier / première', english: 'first' },
                    { french: 'beau / belle / beaux / belles', english: 'beautiful' },
                ],
            },
            {
                title: 'Adjective Placement',
                explanation: 'Most adjectives come AFTER the noun. A small group of short, common adjectives (BAGS: Beauty, Age, Goodness, Size) come BEFORE.',
                examples: [
                    { french: 'une voiture rouge', english: 'a red car (colour → after)' },
                    { french: 'une vieille maison', english: 'an old house (age → before)' },
                    { french: 'un grand homme', english: 'a great man (before)' },
                    { french: 'un homme grand', english: 'a tall man (physical size → after)' },
                    { french: 'une belle journée', english: 'a beautiful day (beauty → before)' },
                    { french: 'un livre nouveau', english: 'a new book (after, when it means \'brand-new\')' },
                ],
            },
        ],
        exercises: [
            { sentence: "C'est une femme ___. (grand)", answer: 'grande', hint: 'add -e for feminine' },
            { sentence: "Il est ___. (heureux, masculine)", answer: 'heureux', hint: '-eux stays for masculine' },
            { sentence: "Elle est ___. (heureux, feminine)", answer: 'heureuse', hint: '-eux → -euse for feminine' },
            { sentence: "C'est une ___ maison. (vieux, feminine, before noun)", answer: 'vieille', hint: 'beau/belle/vieux/vieille — age adjective before noun' },
            { sentence: "Elle a une voiture ___. (rouge)", answer: 'rouge', hint: 'colour adjectives go after the noun, no agreement change' },
            { sentence: "C'est un livre ___. (intéressant, masculine)", answer: 'intéressant', hint: 'regular adjective, masculine form' },
        ],
    },
    {
        unit: 1,
        id: 'passe-compose',
        title: 'Passé Composé',
        level: 'A2',
        description: 'The most common past tense — used for completed actions',
        icon: '⏪',
        color: '#EA580C',
        sections: [
            {
                title: 'Formation with avoir',
                explanation: 'Most verbs form the passé composé with avoir + past participle. -ER verbs: -é. -IR verbs: -i. -RE verbs: -u.',
                examples: [
                    { french: 'parler → j\'ai parlé', english: 'I spoke' },
                    { french: 'finir → il a fini', english: 'he finished' },
                    { french: 'vendre → nous avons vendu', english: 'we sold' },
                    { french: 'voir → elle a vu', english: 'she saw' },
                    { french: 'faire → tu as fait', english: 'you did' },
                ],
            },
            {
                title: 'Formation with être',
                explanation: '16 verbs of motion/state use être + past participle (DR & MRS VANDERTRAMP). The participle agrees with the subject.',
                examples: [
                    { french: 'aller → je suis allé(e)', english: 'I went' },
                    { french: 'venir → il est venu', english: 'he came' },
                    { french: 'partir → elle est partie', english: 'she left' },
                    { french: 'arriver → nous sommes arrivé(e)s', english: 'we arrived' },
                    { french: 'naître → il est né', english: 'he was born' },
                    { french: 'mourir → elle est morte', english: 'she died' },
                ],
            },
            {
                title: 'Reflexive Verbs',
                explanation: 'All reflexive (pronominal) verbs use être. The participle agrees with the subject.',
                examples: [
                    { french: 'se lever → elle s\'est levée', english: 'she got up' },
                    { french: 'se coucher → ils se sont couchés', english: 'they went to bed' },
                    { french: 'se marier → nous nous sommes mariés', english: 'we got married' },
                ],
            },
            {
                title: 'Irregular Past Participles',
                explanation: 'Key irregular past participles to memorise.',
                examples: [
                    { french: 'être → été', english: 'been' },
                    { french: 'avoir → eu', english: 'had' },
                    { french: 'faire → fait', english: 'done / made' },
                    { french: 'prendre → pris', english: 'taken' },
                    { french: 'mettre → mis', english: 'put' },
                    { french: 'dire → dit', english: 'said' },
                    { french: 'écrire → écrit', english: 'written' },
                    { french: 'ouvrir → ouvert', english: 'opened' },
                ],
            },
        ],
        exercises: [
            { sentence: "Hier, j'___ parlé avec elle.", answer: 'ai', hint: 'avoir, passé composé, je' },
            { sentence: "Il ___ allé au marché.", answer: 'est', hint: 'aller uses être in passé composé' },
            { sentence: "Nous avons ___. (vendre)", answer: 'vendu', hint: '-RE verbs: past participle → -u' },
            { sentence: "Elle s'est ___. (lever, feminine subject)", answer: 'levée', hint: 'reflexive verb with être; participle agrees with subject' },
            { sentence: "Tu as ___ ce film ? (voir)", answer: 'vu', hint: 'voir → vu (irregular past participle)' },
            { sentence: "Ils ont ___ la porte. (ouvrir)", answer: 'ouvert', hint: 'ouvrir → ouvert (irregular past participle)' },
        ],
    },
    {
        unit: 2,
        id: 'imperative-mood',
        title: 'The Imperative Mood',
        level: 'A2',
        description: 'Give commands, instructions, and advice — essential for recipes, directions, and polite requests',
        icon: '📢',
        color: '#EA580C',
        sections: [
            {
                title: 'Forming the Imperative (tu / vous / nous)',
                explanation: 'The imperative uses the present-tense verb form without a subject pronoun. For -ER verbs (and aller), drop the final -s from the tu form: tu parles → Parle ! For -IR and -RE verbs, the tu form keeps the -s: tu finis → Finis ! The vous and nous forms are identical to the present tense. Negation wraps the verb: ne + verb + pas.',
                examples: [
                    { french: 'Parle ! / Parlez ! / Parlons !', english: 'Speak! (tu / vous / nous)' },
                    { french: 'Finis tes devoirs !', english: 'Finish your homework!' },
                    { french: 'Attendez, s\'il vous plaît.', english: 'Wait, please.' },
                    { french: 'Ne parle pas si vite !', english: 'Don\'t speak so fast!' },
                    { french: 'Allons-y !', english: 'Let\'s go!' },
                ],
            },
            {
                title: 'Irregular Imperatives',
                explanation: 'Four verbs have entirely irregular imperative forms: être → sois / soyez / soyons; avoir → aie / ayez / ayons; savoir → sache / sachez / sachons; vouloir → veuille / veuillez (veuillez is common in formal writing meaning "please"). All other verbs follow the regular pattern.',
                examples: [
                    { french: 'Sois patient !', english: 'Be patient!' },
                    { french: 'Soyez les bienvenus !', english: 'Welcome! (formal)' },
                    { french: 'N\'aie pas peur.', english: 'Don\'t be afraid.' },
                    { french: 'Veuillez patienter.', english: 'Please hold / Please wait. (formal)' },
                ],
            },
            {
                title: 'Reflexive Verbs & Pronouns in the Imperative',
                explanation: 'With reflexive verbs in the affirmative imperative, the reflexive pronoun follows the verb joined by a hyphen. Te becomes toi: Lève-toi ! In the negative, the pronoun stays before the verb: Ne te lève pas. Object pronouns also follow the verb in affirmative commands: Dis-le-moi.',
                examples: [
                    { french: 'Lève-toi ! / Ne te lève pas.', english: 'Get up! / Don\'t get up.' },
                    { french: 'Dépêchez-vous !', english: 'Hurry up!' },
                    { french: 'Dis-le-moi.', english: 'Tell it to me.' },
                    { french: 'Ne le faites pas maintenant.', english: 'Don\'t do it now.' },
                ],
            },
        ],
        exercises: [
            { sentence: '___ tes devoirs avant de regarder la télé. (faire, tu)', answer: 'Fais', hint: 'faire → fais (irregular -ER-style tu form); drop the -s' },
            { sentence: 'Ne ___ pas dans le couloir. (courir, vous)', answer: 'courez', hint: 'negative imperative: ne + present-tense form (vous) + pas' },
            { sentence: '___ courageux ! (être, tu)', answer: 'Sois', hint: 'être is irregular: sois / soyez / soyons' },
            { sentence: 'N\'___ pas peur. (avoir, tu)', answer: 'aie', hint: 'avoir is irregular in imperative: aie / ayez / ayons' },
            { sentence: '___ -toi ! (dépêcher, tu)', answer: 'Dépêche', hint: 'reflexive: dépêcher → Dépêche + -toi (te → toi after verb)' },
            { sentence: 'Ne ___ pas la porte. (ouvrir, vous)', answer: 'ouvrez', hint: 'negative imperative vous: ne + ouvrez + pas' },
        ],
    },
    {
        unit: 4,
        id: 'conditionnel-intro',
        title: 'Polite Conditionals',
        level: 'A2',
        description: 'Use je voudrais, ce serait, and il faudrait for polite requests and everyday hypothetical statements',
        icon: '🤝',
        color: '#7C3AED',
        sections: [
            {
                title: 'Je voudrais — the polite request',
                explanation: 'The conditionnel présent is formed with the futur stem (same as futur simple) + imparfait endings: -ais, -ais, -ait, -ions, -iez, -aient. The most essential A2 use is vouloir → voudr- to make polite requests. Je veux can sound blunt; je voudrais is softer and expected in shops, restaurants, and formal situations.',
                examples: [
                    { french: 'Je voudrais un café, s\'il vous plaît.', english: 'I would like a coffee, please.' },
                    { french: 'Tu voudrais venir avec nous ?', english: 'Would you like to come with us?' },
                    { french: 'Je voudrais réserver une table pour ce soir.', english: 'I\'d like to book a table for tonight.' },
                    { french: 'Vous voudriez autre chose ?', english: 'Would you like anything else?' },
                ],
            },
            {
                title: 'Ce serait / Ça serait — it would be',
                explanation: 'être → ser- + conditional endings. Ce serait / ça serait means "it/that would be". Use it to react to suggestions, make polite assessments, or soften statements. It is extremely high-frequency in everyday conversation.',
                examples: [
                    { french: 'Ce serait super !', english: 'That would be great!' },
                    { french: 'Ce serait dommage de rater ça.', english: 'It would be a shame to miss that.' },
                    { french: 'Ce serait plus simple de prendre le bus.', english: 'It would be simpler to take the bus.' },
                    { french: 'Ça serait bien qu\'on se voie bientôt.', english: 'It would be nice if we could see each other soon.' },
                ],
            },
            {
                title: 'Il faudrait & on pourrait — suggestions',
                explanation: 'falloir → faudr- gives il faudrait (one should / it would be necessary to). pouvoir → pourr- gives on pourrait (we could / one could) and pourriez-vous (could you — very polite). These are the go-to forms for giving advice or making polite suggestions.',
                examples: [
                    { french: 'Il faudrait partir maintenant.', english: 'We should leave now.' },
                    { french: 'Il faudrait appeler avant de venir.', english: 'You should call before coming.' },
                    { french: 'On pourrait essayer ce restaurant.', english: 'We could try this restaurant.' },
                    { french: 'Pourriez-vous parler plus lentement ?', english: 'Could you speak more slowly?' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je ___ un verre d\'eau, s\'il vous plaît. (vouloir)', answer: 'voudrais', hint: 'vouloir → voudr- + -ais (je form)' },
            { sentence: '___ super de partir en vacances ensemble ! (être — ce)', answer: 'Ce serait', hint: 'être → ser- + -ait; ce serait = it/that would be' },
            { sentence: 'Il ___ appeler avant de venir. (falloir)', answer: 'faudrait', hint: 'falloir → faudr- + -ait; only used with il' },
            { sentence: 'On ___ prendre le métro plutôt que le bus. (pouvoir)', answer: 'pourrait', hint: 'pouvoir → pourr- + -ait (on = 3rd singular)' },
            { sentence: '___ -vous nous aider, s\'il vous plaît ? (pouvoir)', answer: 'Pourriez', hint: 'pourr- + -iez (vous form) = could you…?' },
            { sentence: '___ dommage de ne pas y aller. (être — ce)', answer: 'Ce serait', hint: 'ce serait = that would be; ser- + -ait' },
        ],
    },
    {
        unit: 5,
        id: 'adverbs-ment',
        title: 'Adverbs — Formation & Placement',
        level: 'A2',
        description: 'Form adverbs from adjectives using -ment and place them correctly in simple and compound tenses',
        icon: '⚡',
        color: '#059669',
        sections: [
            {
                title: 'Forming Adverbs from Adjectives',
                explanation: 'Most French adverbs of manner are formed by adding -ment to the feminine form of an adjective: lent → lente → lentement. If the masculine adjective already ends in a vowel, add -ment directly: facile → facilement. Adjectives ending in -ant give -amment; adjectives ending in -ent give -emment (both pronounced [-amɑ̃]).',
                examples: [
                    { french: 'lent → lente → lentement', english: 'slow → slowly' },
                    { french: 'heureux → heureuse → heureusement', english: 'happy → happily / fortunately' },
                    { french: 'facile → facilement', english: 'easy → easily (ends in vowel)' },
                    { french: 'courant → couramment', english: 'fluent → fluently (-ant → -amment)' },
                    { french: 'évident → évidemment', english: 'obvious → obviously (-ent → -emment)' },
                ],
            },
            {
                title: 'Common Irregular Adverbs',
                explanation: 'Several very frequent adverbs are not formed by -ment and must be memorised: bien (well), mal (badly), vite (quickly), tôt (early), tard (late). These are among the most used words in French and appear in both formal and informal speech.',
                examples: [
                    { french: 'Il parle bien français.', english: 'He speaks French well.' },
                    { french: 'Elle a mal dormi.', english: 'She slept badly.' },
                    { french: 'Vas-y vite !', english: 'Go quickly!' },
                    { french: 'Il se lève tôt.', english: 'He gets up early.' },
                ],
            },
            {
                title: 'Placement Rules',
                explanation: 'In simple tenses, adverbs of manner follow the conjugated verb directly: Elle parle lentement. In compound tenses (passé composé), short frequent adverbs (bien, mal, vite, souvent, déjà, encore, toujours) go between the auxiliary and the past participle. Longer -ment adverbs typically follow the past participle.',
                examples: [
                    { french: 'Elle parle lentement.', english: 'She speaks slowly. (after verb, simple tense)' },
                    { french: 'Il a bien travaillé.', english: 'He worked well. (bien between aux. and p.p.)' },
                    { french: 'Elle a vite compris.', english: 'She understood quickly. (short adverb before p.p.)' },
                    { french: 'Il a répondu poliment.', english: 'He answered politely. (long adverb after p.p.)' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Elle parle ___. (lent → adverbe)', answer: 'lentement', hint: 'lent → lente → lentement' },
            { sentence: 'Il joue ___. (heureux → adverbe)', answer: 'heureusement', hint: 'heureux → heureuse → heureusement' },
            { sentence: 'Il parle le français ___. (courant → adverbe)', answer: 'couramment', hint: '-ant → -amment: courant → couramment' },
            { sentence: 'C\'est ___ la bonne réponse. (évident → adverbe)', answer: 'évidemment', hint: '-ent → -emment: évident → évidemment' },
            { sentence: 'Elle a ___ répondu. (bien — place correctly in passé composé)', answer: 'bien', hint: 'bien goes between a and répondu in the passé composé' },
            { sentence: 'Il a travaillé ___. (sérieux → adverbe)', answer: 'sérieusement', hint: 'sérieux → sérieuse → sérieusement; long adverb follows p.p.' },
        ],
    },
    {
        unit: 5,
        id: 'reflexive-verbs',
        title: 'Reflexive Verbs',
        level: 'A2',
        description: 'Pronominal verbs where the subject acts on itself',
        icon: '🔄',
        color: '#16A34A',
        sections: [
            {
                title: 'What are Reflexive Verbs?',
                explanation: 'Reflexive verbs are preceded by a reflexive pronoun (me, te, se, nous, vous, se) that refers back to the subject.',
                examples: [
                    { french: 'je me lève', english: 'I get up (lit. I raise myself)' },
                    { french: 'tu te laves', english: 'you wash yourself' },
                    { french: 'il se rase', english: 'he shaves' },
                    { french: 'nous nous habillons', english: 'we get dressed' },
                    { french: 'ils se disputent', english: 'they argue' },
                ],
            },
            {
                title: 'Common Reflexive Verbs',
                explanation: 'Many daily-routine verbs are reflexive in French.',
                examples: [
                    { french: 'se réveiller', english: 'to wake up' },
                    { french: 'se lever', english: 'to get up' },
                    { french: 'se coucher', english: 'to go to bed' },
                    { french: 'se doucher', english: 'to shower' },
                    { french: 's\'habiller', english: 'to get dressed' },
                    { french: 'se rappeler', english: 'to remember' },
                    { french: 's\'ennuyer', english: 'to get bored' },
                    { french: 'se sentir', english: 'to feel' },
                ],
            },
            {
                title: 'Reflexive Verbs in the Passé Composé',
                explanation: 'All reflexive verbs use être in compound tenses. The past participle agrees with the subject.',
                examples: [
                    { french: 'Elle s\'est levée tôt.', english: 'She got up early.' },
                    { french: 'Ils se sont rencontrés à Paris.', english: 'They met in Paris.' },
                    { french: 'Nous nous sommes disputés.', english: 'We argued.' },
                    { french: 'Tu t\'es trompé(e).', english: 'You were mistaken.' },
                ],
            },
            {
                title: 'Reciprocal Use',
                explanation: 'Reflexive pronouns can also express mutual action (\'each other\').',
                examples: [
                    { french: 'Ils s\'aiment.', english: 'They love each other.' },
                    { french: 'Nous nous téléphonons souvent.', english: 'We call each other often.' },
                    { french: 'Elles se regardent.', english: 'They look at each other.' },
                ],
            },
        ],
        exercises: [
            { sentence: "Je ___ lève à sept heures.", answer: 'me', hint: 'reflexive pronoun for je' },
            { sentence: "Tu ___ laves les mains.", answer: 'te', hint: 'reflexive pronoun for tu' },
            { sentence: "Nous ___ habillons vite.", answer: 'nous', hint: 'reflexive pronoun for nous' },
            { sentence: "Elle s'est ___ tôt. (lever, feminine)", answer: 'levée', hint: 'reflexive + être; participle agrees with feminine subject' },
            { sentence: "Ils ___ sont rencontrés à Paris.", answer: 'se', hint: 'reflexive pronoun for ils, before être in passé composé' },
            { sentence: "Ils ___. (s\'aimer — they love each other)", answer: "s'aiment", hint: 'reciprocal use of reflexive verb' },
        ],
    },
];
