import type { GrammarLesson } from '../../../types/lectures/grammar';

export const grammarB1: GrammarLesson[] = [
    {
        unit: 1,
        id: 'plus-que-parfait',
        title: 'Le Plus-que-parfait',
        level: 'B1',
        description: 'The past-perfect tense — for events that happened before another past event',
        icon: '⏮️',
        color: '#0891B2',
        sections: [
            {
                title: 'Formation',
                explanation: 'The plus-que-parfait is formed with the imperfect of avoir or être + past participle. The same être/avoir split as passé composé applies.',
                examples: [
                    { french: 'j\'avais mangé', english: 'I had eaten' },
                    { french: 'tu avais fini', english: 'you had finished' },
                    { french: 'elle était partie', english: 'she had left' },
                    { french: 'nous nous étions levés', english: 'we had got up' },
                ],
            },
            {
                title: 'When to Use It',
                explanation: 'Use the plus-que-parfait for an event that happened before another past event. It is always combined with a passé composé or imparfait main clause.',
                examples: [
                    { french: 'Quand je suis arrivé, elle était déjà partie.', english: 'When I arrived, she had already left.' },
                    { french: 'Il a mangé tout ce que j\'avais préparé.', english: 'He ate everything I had prepared.' },
                    { french: 'Je ne savais pas qu\'ils avaient déménagé.', english: 'I didn\'t know they had moved.' },
                ],
            },
            {
                title: 'Sequence Markers',
                explanation: 'These words signal a past-before-past relationship.',
                examples: [
                    { french: 'déjà', english: 'already' },
                    { french: 'avant de (+ infinitif)', english: 'before (doing something)' },
                    { french: 'après que (+ plus-que-parfait)', english: 'after (that)' },
                    { french: 'une fois que', english: 'once / as soon as' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Quand il est entré, je ___ (finir) de manger.', answer: 'avais fini', hint: 'imperfect of avoir + past participle' },
            { sentence: 'Elle ___ (partir) avant notre arrivée.', answer: 'était partie', hint: 'partir uses être; feminine subject' },
            { sentence: 'Tu n\'as pas mangé ce que je ___ (cuisiner) ?', answer: 'avais cuisiné', hint: 'imperfect of avoir + cuisiné' },
            { sentence: 'Ils ___ déjà (voir) ce film.', answer: 'avaient déjà vu', hint: 'imperfect of avoir; déjà goes between auxiliary and participle' },
            { sentence: 'Nous ___ (ne pas encore / arriver) quand la fête a commencé.', answer: 'n\'étions pas encore arrivés', hint: 'arriver uses être; negation wraps the auxiliary' },
            { sentence: 'J\'ai réalisé que j\' ___ (oublier) mon portefeuille.', answer: 'avais oublié', hint: 'imperfect of avoir + oublié' },
        ],
    },
    {
        unit: 1,
        id: 'relative-pronouns',
        title: 'Pronoms Relatifs',
        level: 'B1',
        description: 'Who, which, that, where — join clauses and replace nouns to avoid repetition',
        icon: '🔗',
        color: '#0891B2',
        sections: [
            {
                title: 'Qui and Que',
                explanation: 'Qui (subject) and que (object) are the most common relative pronouns. Qui never drops its -i before a vowel; que becomes qu\' before a vowel.',
                examples: [
                    { french: 'La femme qui chante est ma sœur.', english: 'The woman who is singing is my sister.' },
                    { french: 'Le film que j\'ai vu était excellent.', english: 'The film (that) I watched was excellent.' },
                    { french: 'C\'est l\'ami qu\'elle a invité.', english: 'He\'s the friend she invited.' },
                ],
            },
            {
                title: 'Dont and Où',
                explanation: 'Dont replaces de + noun (possession, certain verbs). Où replaces a place or time expression.',
                examples: [
                    { french: 'Le livre dont je t\'ai parlé est épuisant.', english: 'The book I told you about is exhausting.' },
                    { french: 'C\'est l\'artiste dont j\'admire le travail.', english: 'That\'s the artist whose work I admire.' },
                    { french: 'Je connais la ville où il habite.', english: 'I know the city where he lives.' },
                    { french: 'Le jour où je l\'ai rencontré, il pleuvait.', english: 'The day (when) I met him, it was raining.' },
                ],
            },
            {
                title: 'Preposition + Lequel',
                explanation: 'After a preposition (other than de), use lequel/laquelle/lesquels/lesquelles for things. For people, use qui after a preposition.',
                examples: [
                    { french: 'La table sur laquelle j\'écris est ancienne.', english: 'The table on which I\'m writing is old.' },
                    { french: 'L\'ami avec qui je travaille est sympa.', english: 'The friend I work with is nice.' },
                    { french: 'Le projet pour lequel il travaille est difficile.', english: 'The project he\'s working on is difficult.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'La personne ___ a appelé est ma mère. (who)', answer: 'qui', hint: 'qui = subject relative pronoun' },
            { sentence: 'Le gâteau ___ il a mangé était délicieux. (that)', answer: 'que', hint: 'que = object relative pronoun' },
            { sentence: 'C\'est le musée ___ je t\'avais parlé. (that I told you about)', answer: 'dont', hint: 'dont replaces de + noun; parler de → dont' },
            { sentence: 'La ville ___ je suis né est petite. (where)', answer: 'où', hint: 'où replaces a place' },
            { sentence: 'C\'est un problème ___ je n\'ai pas de solution. (for which)', answer: 'pour lequel', hint: 'preposition pour + lequel for a thing' },
            { sentence: 'L\'ami ___ je suis allé au cinéma est acteur. (with whom)', answer: 'avec qui', hint: 'preposition avec + qui for a person' },
        ],
    },
    {
        unit: 2,
        id: 'si-clauses-type1',
        title: 'Si + Présent : Conditions Réelles',
        level: 'B1',
        description: 'Real / likely conditions — si + present tense, result in future tense',
        icon: '🔀',
        color: '#0891B2',
        sections: [
            {
                title: 'The Structure',
                explanation: 'For real, likely conditions (Type 1), use si + présent in the condition clause and futur simple or imperative in the result clause. Never use futur in the si-clause.',
                examples: [
                    { french: 'Si tu travailles, tu réussiras.', english: 'If you work, you will succeed.' },
                    { french: 'Si elle vient, nous serons contents.', english: 'If she comes, we will be happy.' },
                    { french: 'Si tu as faim, mange quelque chose !', english: 'If you\'re hungry, eat something!' },
                ],
            },
            {
                title: 'Si vs Quand for the Future',
                explanation: 'After quand (when) referring to a future event, use the futur simple — unlike English which uses the present. After si, always use the present.',
                examples: [
                    { french: 'Quand tu arriveras, appelle-moi.', english: 'When you arrive (tomorrow), call me.' },
                    { french: 'Si tu arrives, appelle-moi.', english: 'If you arrive, call me.' },
                ],
            },
            {
                title: 'Word Order',
                explanation: 'The si-clause can come first or second — if it comes second, no comma is used.',
                examples: [
                    { french: 'Si j\'ai le temps, je lirai ce livre.', english: 'If I have time, I\'ll read this book.' },
                    { french: 'Je lirai ce livre si j\'ai le temps.', english: 'I\'ll read this book if I have time.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Si tu ___ (avoir) faim, dis-le-moi.', answer: 'as', hint: 'si + présent (never futur)' },
            { sentence: 'Il ___ (partir) si tu ne viens pas. (futur)', answer: 'partira', hint: 'result clause → futur simple' },
            { sentence: 'Si vous ___ (étudier) plus, vous réussirez.', answer: 'étudiez', hint: 'si + présent' },
            { sentence: 'Nous ___ (aller) à la plage si il fait beau demain.', answer: 'irons', hint: 'result clause → futur simple of aller' },
            { sentence: 'Quand elle ___ (rentrer), nous mangerons. (future context)', answer: 'rentrera', hint: 'quand + futur when referring to future event' },
            { sentence: 'Si tu as le temps, ___ (venir) me voir !', answer: 'viens', hint: 'imperative is also valid in result clause' },
        ],
    },
    {
        unit: 2,
        id: 'subjunctive-intro',
        title: 'Le Subjonctif : Introduction',
        level: 'B1',
        description: 'The subjunctive mood — express wishes, doubts, necessity, and emotion',
        icon: '🎭',
        color: '#0891B2',
        sections: [
            {
                title: 'Formation',
                explanation: 'Take the ils/elles form of the present tense, drop -ent, and add: -e, -es, -e, -ions, -iez, -ent. Être and avoir are fully irregular.',
                examples: [
                    { french: 'parler → ils parlent → que je parle', english: 'to speak → that I speak' },
                    { french: 'finir → ils finissent → que tu finisses', english: 'to finish → that you finish' },
                    { french: 'être → que je sois / que nous soyons', english: 'to be → that I am / we are' },
                    { french: 'avoir → que j\'aie / que vous ayez', english: 'to have → that I have / you have' },
                ],
            },
            {
                title: 'Key Triggers (Verbs & Expressions)',
                explanation: 'The subjunctive is required after these common triggers — they all imply subjectivity, wish, doubt or emotion.',
                examples: [
                    { french: 'vouloir que (+ subj.)', english: 'to want (someone) to…' },
                    { french: 'il faut que (+ subj.)', english: 'it is necessary that…' },
                    { french: 'avoir peur que (+ subj.)', english: 'to be afraid that…' },
                    { french: 'douter que (+ subj.)', english: 'to doubt that…' },
                    { french: 'bien que / quoique (+ subj.)', english: 'although…' },
                    { french: 'pour que (+ subj.)', english: 'so that…' },
                ],
            },
            {
                title: 'Common Irregular Subjunctives',
                explanation: 'These 10 verbs have irregular or semi-irregular subjunctive stems.',
                examples: [
                    { french: 'aller → que j\'aille', english: 'to go → that I go' },
                    { french: 'pouvoir → que je puisse', english: 'to be able → that I can' },
                    { french: 'savoir → que je sache', english: 'to know → that I know' },
                    { french: 'faire → que je fasse', english: 'to do → that I do' },
                    { french: 'vouloir → que je veuille', english: 'to want → that I want' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Il faut que tu ___ (partir) maintenant.', answer: 'partes', hint: 'partir → ils partent → part- + -es' },
            { sentence: 'Je veux qu\'il ___ (faire) ses devoirs.', answer: 'fasse', hint: 'faire → irregular subjunctive: fasse' },
            { sentence: 'Bien qu\'elle ___ (être) fatiguée, elle sourit.', answer: 'soit', hint: 'être → irregular subjunctive: soit' },
            { sentence: 'Il est important que vous ___ (avoir) votre passeport.', answer: 'ayez', hint: 'avoir → irregular subjunctive: ayez' },
            { sentence: 'Je doute qu\'il ___ (pouvoir) venir.', answer: 'puisse', hint: 'pouvoir → irregular subjunctive: puisse' },
            { sentence: 'Pour que nous ___ (comprendre), parle plus lentement.', answer: 'comprenions', hint: 'comprendre → ils comprennent → comprenn- → comprenions (nous form)' },
        ],
    },
    {
        unit: 3,
        id: 'y-en-pronouns',
        title: 'Les Pronoms Y et En',
        level: 'B1',
        description: 'Y replaces à + place/thing; en replaces de + noun or a partitive quantity',
        icon: '📍',
        color: '#0891B2',
        sections: [
            {
                title: 'The Pronoun Y',
                explanation: 'Y replaces: (1) a place introduced by à, dans, en, sur, etc.; (2) à + thing/idea (but not à + person). It means "there" or "to/at it".',
                examples: [
                    { french: 'Tu vas à Paris ? — Oui, j\'y vais.', english: 'Are you going to Paris? — Yes, I\'m going there.' },
                    { french: 'Il pense à son avenir. → Il y pense.', english: 'He thinks about his future. → He thinks about it.' },
                    { french: 'Elle répond à la question. → Elle y répond.', english: 'She answers the question. → She answers it.' },
                ],
            },
            {
                title: 'The Pronoun En',
                explanation: 'En replaces: (1) de + noun (partitive or source); (2) quantities (with or without a number). It means "some", "any", "of it/them", or "from there".',
                examples: [
                    { french: 'Tu veux du café ? — Oui, j\'en veux.', english: 'Do you want coffee? — Yes, I want some.' },
                    { french: 'Il vient de Lyon. → Il en vient.', english: 'He comes from Lyon. → He comes from there.' },
                    { french: 'Elle a trois chats. → Elle en a trois.', english: 'She has three cats. → She has three (of them).' },
                ],
            },
            {
                title: 'Position and Set Expressions',
                explanation: 'Y and en follow the same pronoun-order rules as other object pronouns — before the conjugated verb, the auxiliary, or the infinitive. Common set phrases:',
                examples: [
                    { french: 'il y a', english: 'there is / there are' },
                    { french: 'ça y est !', english: 'that\'s it! / done!' },
                    { french: 's\'en aller', english: 'to go away / to leave' },
                    { french: 'en avoir marre', english: 'to be fed up' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Elle va au marché. → Elle ___ va.', answer: 'y', hint: 'au marché = à + place → y' },
            { sentence: 'Nous pensons à nos vacances. → Nous ___ pensons.', answer: 'y', hint: 'à + thing → y' },
            { sentence: 'Il mange du pain. → Il ___ mange.', answer: 'en', hint: 'du pain = partitive → en' },
            { sentence: 'Elle revient de Rome. → Elle ___ revient.', answer: 'en', hint: 'de + place → en' },
            { sentence: 'Ils ont deux enfants. → Ils ___ ont deux.', answer: 'en', hint: 'quantity → en (keep the number)' },
            { sentence: 'Tu te souviens de ce film ? → Tu t\' ___ souviens ?', answer: 'en', hint: 'se souvenir de → en' },
        ],
    },
    {
        unit: 4,
        id: 'present-participle',
        title: 'Le Participe Présent & le Gérondif',
        level: 'B1',
        description: 'The -ant form — as adjective, in relative clauses, or with en as a gerund',
        icon: '🔄',
        color: '#0891B2',
        sections: [
            {
                title: 'Formation',
                explanation: 'Take the nous form of the present tense, drop -ons, and add -ant. Three irregulars: être → étant, avoir → ayant, savoir → sachant.',
                examples: [
                    { french: 'parler → nous parlons → parlant', english: 'speaking' },
                    { french: 'finir → nous finissons → finissant', english: 'finishing' },
                    { french: 'prendre → nous prenons → prenant', english: 'taking' },
                    { french: 'être → étant', english: 'being' },
                ],
            },
            {
                title: 'Uses: Adjective and Clause',
                explanation: 'As an adjective it agrees with the noun. As a verbal phrase it is invariable and can replace a relative clause.',
                examples: [
                    { french: 'une histoire fascinante', english: 'a fascinating story' },
                    { french: 'un enfant souriant', english: 'a smiling child' },
                    { french: 'La personne attendant à la porte est mon père.', english: 'The person waiting at the door is my father.' },
                ],
            },
            {
                title: 'En + Participe Présent (Gérondif)',
                explanation: 'En + present participle means "while/by doing". The subject of both clauses must be the same. It is invariable.',
                examples: [
                    { french: 'En mangeant, il lisait le journal.', english: 'While eating, he was reading the paper.' },
                    { french: 'Elle apprend le français en regardant des films.', english: 'She learns French by watching films.' },
                    { french: 'Il s\'est blessé en faisant du sport.', english: 'He hurt himself playing sport.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Former le participe présent de : chanter', answer: 'chantant', hint: 'nous chantons → chant- + -ant' },
            { sentence: '___ (en / courir), il est tombé.', answer: 'En courant', hint: 'en + present participle = while/by doing' },
            { sentence: 'C\'est une idée ___ (intéresser — adjective, feminine).', answer: 'intéressante', hint: 'as adjective it agrees: intéressant + -e' },
            { sentence: 'Elle travaille tout ___ (écouter) de la musique.', answer: 'en écoutant', hint: 'tout en + participe présent = while…' },
            { sentence: 'Participe présent de : être', answer: 'étant', hint: 'irregular: être → étant' },
            { sentence: '___ (ne pas savoir) quoi dire, il a gardé le silence.', answer: 'Ne sachant pas', hint: 'irregular: savoir → sachant; negation: ne + participle + pas' },
        ],
    },
    {
        unit: 4,
        id: 'negation-advanced',
        title: 'La Négation Avancée',
        level: 'B1',
        description: 'Beyond ne…pas — nuanced negation with jamais, plus, rien, personne, que, ni…ni',
        icon: '🚫',
        color: '#0891B2',
        sections: [
            {
                title: 'Common Negative Pairs',
                explanation: 'These two-part negations wrap the conjugated verb (or auxiliary in compound tenses).',
                examples: [
                    { french: 'ne…jamais', english: 'never' },
                    { french: 'ne…plus', english: 'no longer / not anymore' },
                    { french: 'ne…rien', english: 'nothing / not anything' },
                    { french: 'ne…personne', english: 'nobody / not anyone' },
                    { french: 'ne…que', english: 'only' },
                    { french: 'ne…ni…ni', english: 'neither…nor' },
                ],
            },
            {
                title: 'Position in Simple and Compound Tenses',
                explanation: 'In simple tenses: ne + verb + second part. In compound tenses: ne + auxiliary + second part + past participle. Exception: personne and que come after the past participle.',
                examples: [
                    { french: 'Je ne mange jamais de viande.', english: 'I never eat meat.' },
                    { french: 'Il n\'a plus de travail.', english: 'He has no work anymore.' },
                    { french: 'Elle n\'a rien dit.', english: 'She said nothing.' },
                    { french: 'Nous n\'avons vu personne.', english: 'We saw nobody.' },
                    { french: 'Je n\'ai lu que deux livres.', english: 'I only read two books.' },
                ],
            },
            {
                title: 'Ne…guère and Stacking',
                explanation: 'Ne…guère means "hardly/scarcely" (literary/formal). Some negations can stack: ne…plus jamais, ne…plus rien.',
                examples: [
                    { french: 'Il ne travaille guère.', english: 'He hardly works.' },
                    { french: 'Je ne ferai plus jamais cette erreur.', english: 'I\'ll never make that mistake again.' },
                    { french: 'Elle ne dit plus rien.', english: 'She doesn\'t say anything anymore.' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Je ___ mange ___ de sucre. (never)', answer: 'ne…jamais', hint: 'jamais = never' },
            { sentence: 'Il ___ travaille ___. (no longer)', answer: 'ne…plus', hint: 'plus = no longer/not anymore' },
            { sentence: 'Elle n\'a ___ mangé. (nothing)', answer: 'rien', hint: 'rien in compound tense: between auxiliary and past participle' },
            { sentence: 'Nous n\'avons vu ___. (nobody)', answer: 'personne', hint: 'personne comes after the past participle' },
            { sentence: 'Il ___ boit ___ café ___ thé. (neither…nor)', answer: 'ne…ni…ni', hint: 'ni…ni follows the verb for each item' },
            { sentence: 'Je ___ lis ___ le matin. (only / in the morning)', answer: 'ne…que', hint: 'que comes directly before the element it restricts' },
        ],
    },
    {
        unit: 5,
        id: 'double-pronoun-order',
        title: 'L\'Ordre des Doubles Pronoms',
        level: 'B1',
        description: 'When using two object pronouns together, the order is fixed — master it here',
        icon: '🔢',
        color: '#0891B2',
        sections: [
            {
                title: 'The Full Order Table',
                explanation: 'When two object pronouns precede the verb, the order is always: me/te/se/nous/vous → le/la/les → lui/leur → y → en.',
                examples: [
                    { french: 'Il me le donne.', english: 'He gives it to me.' },
                    { french: 'Elle les lui a montrés.', english: 'She showed them to him/her.' },
                    { french: 'Tu nous en as parlé.', english: 'You told us about it.' },
                    { french: 'Je le lui ai dit.', english: 'I told him/her it.' },
                ],
            },
            {
                title: 'With Infinitives',
                explanation: 'When the pronoun pair governs an infinitive, both pronouns go before the infinitive.',
                examples: [
                    { french: 'Je vais le lui expliquer.', english: 'I\'m going to explain it to him.' },
                    { french: 'Elle peut te les envoyer.', english: 'She can send them to you.' },
                ],
            },
            {
                title: 'Affirmative Commands',
                explanation: 'In affirmative commands, pronouns follow the verb and are joined with hyphens. The order changes: direct object before indirect object. Me → moi, te → toi.',
                examples: [
                    { french: 'Donne-le-moi !', english: 'Give it to me!' },
                    { french: 'Dis-le-lui !', english: 'Tell it to him/her!' },
                    { french: 'Envoie-les-nous !', english: 'Send them to us!' },
                ],
            },
        ],
        exercises: [
            { sentence: 'Il donne le livre à Marie. → Il ___ ___ donne.', answer: 'le lui', hint: 'le (direct) before lui (indirect)' },
            { sentence: 'Elle montre les photos à nous. → Elle ___ ___ montre.', answer: 'nous les', hint: 'nous comes before les' },
            { sentence: 'Tu as parlé de ça à eux. → Tu ___ ___ as parlé.', answer: 'leur en', hint: 'leur (indirect) before en' },
            { sentence: 'Donnez le stylo à moi ! (affirmative command)', answer: 'Donnez-le-moi !', hint: 'in commands: verb-direct-indirect; me → moi' },
            { sentence: 'Je vais expliquer la règle à toi. → Je vais ___ ___ expliquer.', answer: 'te la', hint: 'te before la before the infinitive' },
            { sentence: 'Il y a des pommes ? Mets-en dans le panier ! → Mets-___ !', answer: 'Mets-en !', hint: 'en stays as en in affirmative commands' },
        ],
    },
    {
        unit: 1,
        id: 'imparfait',
        title: 'L\'Imparfait',
        level: 'B1',
        description: 'The imperfect tense — for habits, ongoing states and background descriptions in the past',
        icon: '🌅',
        color: '#0891B2',
        sections: [
            {
                title: 'Formation',
                explanation: 'Take the nous present-tense stem (remove -ons) and add: -ais, -ais, -ait, -ions, -iez, -aient. Only être is irregular: ét-.',
                examples: [
                    { french: 'parler → nous parlons → je parlais, tu parlais, il parlait…', english: 'I was speaking, you were speaking…' },
                    { french: 'finir → nous finissons → je finissais…', english: 'I was finishing…' },
                    { french: 'prendre → nous prenons → je prenais…', english: 'I was taking…' },
                    { french: 'être → j\'étais, tu étais, il était…', english: 'I was, you were, he was…' },
                    { french: 'avoir → j\'avais, tu avais, il avait…', english: 'I had, you had, he had…' },
                ],
            },
            {
                title: 'Habitual Actions in the Past',
                explanation: 'Use the imparfait for things that happened repeatedly or regularly in the past.',
                examples: [
                    { french: 'Quand j\'étais petit, je jouais au foot tous les samedis.', english: 'When I was little, I played football every Saturday.' },
                    { french: 'Elle prenait toujours le métro.', english: 'She always took the metro.' },
                    { french: 'Nous nous retrouvions au café.', english: 'We used to meet at the café.' },
                    { french: 'Il lisait avant de dormir.', english: 'He used to read before sleeping.' },
                ],
            },
            {
                title: 'Descriptions and Background',
                explanation: 'Use the imparfait to describe how things were or what was happening as background to a story.',
                examples: [
                    { french: 'Il faisait froid et la neige tombait.', english: 'It was cold and snow was falling.' },
                    { french: 'Elle portait une robe rouge.', english: 'She was wearing a red dress.' },
                    { french: 'La ville était calme ce matin-là.', english: 'The city was quiet that morning.' },
                    { french: 'J\'avais peur.', english: 'I was afraid.' },
                ],
            },
            {
                title: 'Passé Composé vs Imparfait',
                explanation: 'Use passé composé for single completed actions; use imparfait for ongoing background, states, or habits.',
                examples: [
                    { french: 'Je lisais (imparfait) quand le téléphone a sonné (passé composé).', english: 'I was reading when the phone rang.' },
                    { french: 'Hier, il a plu (PC) toute la journée mais il faisait (imp.) doux.', english: 'Yesterday it rained all day but it was mild.' },
                    { french: 'Elle aimait (imp.) la musique et elle a décidé (PC) d\'apprendre la guitare.', english: 'She loved music and she decided to learn guitar.' },
                ],
            },
        ],
        exercises: [
            { sentence: "Quand j'étais petit, je ___ au foot tous les samedis.", answer: 'jouais', hint: 'imparfait, habitual action, jouer → nous jouons → joua-' },
            { sentence: "Il ___ froid et la neige tombait.", answer: 'faisait', hint: 'imparfait, description, faire → nous faisons → faisa-' },
            { sentence: "Elle ___ toujours le métro.", answer: 'prenait', hint: 'imparfait, habitual, prendre → nous prenons → prena-' },
            { sentence: "Je lisais quand le téléphone ___ sonné.", answer: 'a', hint: 'passé composé for completed action (sonnner → a sonné)' },
            { sentence: "J'___ peur. (imparfait de avoir)", answer: 'avais', hint: 'avoir → j\'avais (imparfait)' },
            { sentence: "La ville ___ calme ce matin-là.", answer: 'était', hint: 'imparfait of être, description' },
        ],
    },
    {
        unit: 2,
        id: 'futur-conditionnel',
        title: 'Future & Conditional',
        level: 'B1',
        description: 'Talking about what will happen and what would happen',
        icon: '🔮',
        color: '#7C3AED',
        sections: [
            {
                title: 'Futur Simple — Formation',
                explanation: 'Add these endings to the infinitive (drop final -e from -RE verbs): -ai, -as, -a, -ons, -ez, -ont. Many irregulars have unique stems.',
                examples: [
                    { french: 'parler → je parlerai', english: 'I will speak' },
                    { french: 'finir → elle finira', english: 'she will finish' },
                    { french: 'prendre → il prendra', english: 'he will take' },
                    { french: 'être → nous serons', english: 'we will be' },
                    { french: 'avoir → vous aurez', english: 'you will have' },
                ],
            },
            {
                title: 'Futur Simple — Usage',
                explanation: 'Use for future events, promises, predictions, and after quand/lorsque/dès que (when English uses present).',
                examples: [
                    { french: 'Je t\'appellerai demain.', english: 'I will call you tomorrow.' },
                    { french: 'Quand tu arriveras, je serai là.', english: 'When you arrive, I will be there.' },
                    { french: 'Il fera beau demain.', english: 'It will be fine tomorrow.' },
                    { french: 'Un jour, tu comprendras.', english: 'One day, you\'ll understand.' },
                ],
            },
            {
                title: 'Conditionnel Présent — Formation',
                explanation: 'Use the same stems as the futur simple, but add the imparfait endings: -ais, -ais, -ait, -ions, -iez, -aient.',
                examples: [
                    { french: 'parler → je parlerais', english: 'I would speak' },
                    { french: 'être → il serait', english: 'he would be' },
                    { french: 'avoir → nous aurions', english: 'we would have' },
                    { french: 'aller → j\'irais', english: 'I would go' },
                ],
            },
            {
                title: 'Conditionnel Présent — Usage',
                explanation: 'Use for hypothetical situations, polite requests, reported speech, and the result clause of si (if) sentences.',
                examples: [
                    { french: 'Je voudrais un café, s\'il vous plaît.', english: 'I would like a coffee, please.' },
                    { french: 'Si j\'avais de l\'argent, je voyagerais.', english: 'If I had money, I would travel.' },
                    { french: 'Il a dit qu\'il viendrait.', english: 'He said he would come.' },
                    { french: 'Pourriez-vous m\'aider ?', english: 'Could you help me?' },
                    { french: 'Ce serait formidable !', english: 'That would be wonderful!' },
                ],
            },
        ],
        exercises: [
            { sentence: "Je t'___ demain. (appeler, futur)", answer: 'appellerai', hint: 'appeler → appellera- + -i (futur)' },
            { sentence: "Il ___ beau demain. (faire, futur)", answer: 'fera', hint: 'irregular futur stem: fer-' },
            { sentence: "Quand tu ___, je serai là. (arriver, futur)", answer: 'arriveras', hint: 'futur after quand' },
            { sentence: "Je ___ un café, s'il vous plaît. (vouloir, conditionnel)", answer: 'voudrais', hint: 'irregular conditional stem: voudr-' },
            { sentence: "Si j'avais de l'argent, je ___. (voyager, conditionnel)", answer: 'voyagerais', hint: 'conditionnel présent: voyager- + -ais' },
            { sentence: "Nous ___ contents d'y aller. (être, conditionnel)", answer: 'serions', hint: 'irregular conditional stem: ser-' },
        ],
    },
];
